### ISSUE TITLE
Workspace is re-cloned every build for definitions with no root repository mapping

### ISSUE THREAD

**Issue by ppejovic** [microsoft/azure-pipelines-agent#1093]
This relates to issues #438 and #398.

When a build has no root repository mapping, the current behavior results in an exception being thrown by `tf vc scorch` which in turn leads to the workspace being re-cloned on every build. Given the remap of workspace mappings through `tf vc workfold /map` is not performant, this leads to a significant increase in build time for builds with many mappings. For example, in our production environment we have a build definition with 139 mappings, where the **Get Sources** step increases from 26 seconds to 12.5 minutes when upgrading from the v1.105.6 agent to v2.112.0.

It seems this issue, and others related to workspace mappings with no root mapping, can be resolved by providing a wildcarded source directory `itemspec` (e.g. `D:\B\1\2\s\*`) and `/recursive` to the `tf vc` command.

**Comment by ericsciple** [comment]
If i remember correctly, I think this is intentional because scorch won't delete files that fall outside of the mapping. For example, if the mapping is:
```
$/foo => C:\a\1\s\foo
$/bar => C:\a\1\s\bar
```

Then I think scorch `C:\a\1\s\* /r` won't remove `C:\a\1\s\baz`

**Comment by ericsciple** [comment]
I would prefer to see a fix in TF.exe rather than introduce a reliability problem in the agent (sometimes cleans files under build.sourcesDirectory, sometimes doesn't).

What's the major problem(s) for your scenario? Is recreating the workspace taking a long time because adding each individual mapping takes a long time? Or does getting the files take a long time? Or both?

Would a workaround be: add a root mapping, cloak subfolders, and explicitly map underneath? Or a single-level root (which effectively an empty folder), and then explicit mappings underneath?

**Comment by ericsciple** [comment]
Another workaround would be to set the clean option to false on the build definition, and then add your own step to call tf.exe scorch. If you check Allow scripts access to OAuth token, then you can use the environment variable $SYSTEM_ACCESS_TOKEN and specify the same authentication settings like the agent when you call tf.exe (agent adds tf.exe to your PATH).

**Comment by ppejovic** [comment]
> What's the major problem(s) for your scenario? Is recreating the workspace taking a long time because adding each individual mapping takes a long time? Or does getting the files take a long time? Or both?
> 
> Would a workaround be: add a root mapping, cloak subfolders, and explicitly map underneath? Or a single-level root (which effectively an empty folder), and then explicit mappings underneath?

It's recreating the workspace that is the bottleneck. Each call to `tf vc workfold /map` can take upwards of 2 seconds. For our production build servers it can be up to 12 seconds, which I assume is correlated to the number of workspaces that exist for a server and the build agent identity. The majority of the time of the `map` invocation is actually time spent processing the request on the application tier. (I have a support ticket open with MS for this).

Adding a root mapping to an empty folder is probably the most feasible workaround, but it seems awkward and requires our development teams to have explicit knowledge of builds without a root mapping being problematic.

**Comment by swythan** [comment]
This is still an issue for us, although we're mid - migration to git, so we will be caring less going forward.
