### ISSUE TITLE
Agent installer does not support group managed service accounts (gMSA)

### ISSUE THREAD

**Issue by michael-baker** [microsoft/azure-pipelines-agent#1294]
## Agent version and platform
2.117.2 (from https://go.microsoft.com/fwlink/?linkid=851123) on Windows.

## OS of the machine running the agent? 
Windows Server 2016

## VSTS type and version
On-Prem TFS - TFS 2017 Update 2

## What's not working?
I am attempting to use a gMSA (group managed service account) for my build agent but the unattended install progress does allow me to install the agent as a Windows service as it the installer does not understand that gMSA users do not need to provide a password.

My PowerShell install script invokes config.cmd thus

```
.\config.cmd --unattended --url $tfsHost --auth Integrated --pool $agentPool --agent $agentName --windowslogonaccount "domain\buildservice$" --runasservice --work "$workingDirectory" --replace
```
This fails with **Invalid configuration provided for windowslogonpassword.**
If I provide a blank value for --windowslogonpassword the same error occurs.

If I provide a " " (space) the install will fail due to invalid credentials.

My work around is 

1. remove --runasservice and --windowslogonpassword 
2. Register AgentService.exe with SC.exe manually
3. Profit! The agent successfully connects to TFS and everything works.

Logs of failure

```
Agent: stoic_tiger Working directory C:\B\641
Installing agent stoic_tiger

>> Connect:

Connecting to server ...

>> Register Agent:

Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
2017-11-13 04:43:53Z: Settings Saved.
Invalid configuration provided for windowslogonpassword. Terminating unattended configuration.

```

It would be good to have the installer understand gMSA so I do not need to call SC.exe myself.

**Comment by bryanmacfarlane** [comment]
The agent uses OAuth tokens per build to access resources.  Is there a specific reason you need the service to run as a gMSA account instead of network service or local system?  Our goal is the account the agent runs as is mostly irrelevant.  I'm interested in your scenario.

**Comment by michael-baker** [comment]
Our build has many integration points. In some of these points we need login to various services or access resources a valid Windows user account (not machine like Network Service), so for us the agent needs to run as a Windows user.
gMSA lets us achieve this without having to worry about passwords in scripts which setup the agents on the machines in the build farm.

**Comment by bryanmacfarlane** [comment]
Thanks.  We will add to our backlog and leave this open so you can track progress

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jabbera** [comment]
gMSA are also great for on prem release agents that are in deployment groups. No one need to know the password of the deployment account then.

**Comment by TingluoHuang** [comment]
@michael-baker @jabbera any of you would like to can help me testing some private bits about gMSA support, since i don't have an environment for testing? :D

**Comment by jabbera** [comment]
Sure but it would have to be compantible with TFS 2018z

**Comment by TingluoHuang** [comment]
I have create a branch with my changes that might enable GMSA support. :) 
https://github.com/Microsoft/vsts-agent/tree/users/tihuang/gmsa

Steps to test:
1. git clone the repository 
2. git checkout users/tihuang/gmsa
3. run `cd src/`
4. run `./dev.cmd layout`
5. run `cd ../_layout`
6. run `config.cmd` to configure the agent.

the `_layout` folder is the agent folder, if needed, you can zip it and copy across machines.

please share with me the diag log after attempt to configure.

Thanks for help me testing this.

**Comment by DHowett-MSFT** [comment]
Has there been any movement on this?

**Comment by michael-baker** [comment]
Hi

Wonderful work, I will get my team to pickup this branch and see if this works for us. Sorry for the very long delay in getting back to you.

**Comment by tastyeggs** [comment]
Would be really nice to get this working. Currently the only service that requires a domain user in my entire cluster are these build agents.

I tried applying the workaround above, but the agent didn't come online (I probably did something wrong). 

But as a security best-practice, would be really nice to get first-class support for MSAs.

**Comment by michael-baker** [comment]
I currently do the same workaround as @TingluoHuang 
`
.\config.cmd --unattended --url $tfsHost --auth Integrated --pool $agentPool --agent $agentName --windowslogonaccount "domain\tfsbuildservice$" --work "$workingDirectory" --replace`

Then 

```
$command = "sc create `"VSTS Agent (tfs.$agentName)`" binpath=$agentInstallationPath\bin\AgentService.exe obj= `"ADERANT_AP\tfsbuildservice$`" start= delayed-auto"
& cmd /c $command
net start "VSTS Agent (tfs.$agentName)"
```

**Comment by tlofreso** [comment]
> Thanks. We will add to our backlog and leave this open so you can track progress Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: Michael Baker <notifications@github.com> Sent: Sunday, December 10, 2017 3:00:03 AM To: Microsoft/vsts-agent Cc: Bryan MacFarlane; Comment Subject: Re: [Microsoft/vsts-agent] Agent installer does not support group managed service accounts (gMSA) (#1294) Our build has many integration points. In some of these points we need login to various services or access resources a valid Windows user account (not machine like Network Service), so for us the agent needs to run as a Windows user. gMSA lets us achieve this without having to worry about passwords in scripts which setup the agents on the machines in the build farm. — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvsts-agent%2Fissues%2F1294%23issuecomment-350534326&data=04%7C01%7Cbryanmac%40microsoft.com%7C95ac0b134f874afd3beb08d53fac67e0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636484932070898081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=cjG17NnrHtKFuvcUd9hx7XCtJp6L44IuAsp%2BVdMoSNQ%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA4IDOelBZaIG43aVqreATJWvpLmMYKMks5s-52TgaJpZM4QbZGr&data=04%7C01%7Cbryanmac%40microsoft.com%7C95ac0b134f874afd3beb08d53fac67e0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636484932070898081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=JolGjCmZ92QgIpRX1WzOCpHqiD%2BUOwhWaSTmfMp4Z3w%3D&reserved=0>.

On the topic of tracking progress... how's this coming?

**Comment by Justin-DynamicD** [comment]
Following up/echoing this:

It's a pretty common scenario for build agents to need to "reach out" and grab artifacts or even run test frameworks as a domain-authenticated account.  Being able to use a gMSA account seems rather ideal here.

**Comment by avivanoff** [comment]
How come the support for gMSA has not been added after more than two years it was asked for? If I am not mistaken, it should not be harder then allowing to specify no password during configuration.

My workaround is to configure the agent service to run as NETWORK SERVICE, and then use sc.exe to reconfigure the created service:

`sc.exe config vstsagent.Org.Pool.Name obj= yourgmsa$@youdomain.com password= ""`

**Comment by gabrielmccoll** [comment]
Another plea for making this easier to implement without workarounds.

**Comment by peterbarendse** [comment]
Would love to have this feature implemented!

**Comment by gabrielmccoll** [comment]
Not stale.

**Comment by tastyeggs** [comment]
Not stale

**Comment by gabrielmccoll** [comment]
What the deuce.  People commented not stale. Bad bot.

**Comment by poke** [comment]
I just hit this as well, using the interactive configuration. The configuration wizard is able to pick up the service account correctly, but then the validation for the password fails because passwords for managed service accounts are empty:

```
Enter run agent as service? (Y/N) (press enter for N) > y
Enter User account to use for the service (press enter for NT AUTHORITY\NETWORK SERVICE) > domain.test\vsts-agent$
Enter Password for the account domain.test\vsts-agent$ >
Enter Password for the account domain.test\vsts-agent$ >
Enter Password for the account domain.test\vsts-agent$ >
Enter Password for the account domain.test\vsts-agent$ >
…
```

As far as I can tell, the validation happens here:

https://github.com/microsoft/azure-pipelines-agent/blob/66e6e9a9aa4503139f5dcf4a9894ce349b68e0ab/src/Agent.Listener/CommandSettings.cs#L389-L397

Here, the validator `Validators.NonEmptyValidator` is being used. This _may_ make sense for usual accounts (although I think technically user accounts can have empty passwords too?) but for managed service accounts, the password will always be empty.

I think a quick fix would be to simply remove that validator there. If it is desired to keep the validator for normal accounts (assuming that empty passwords are indeed an accident), then an alternative idea would be to check for a managed service accounts over here:

https://github.com/microsoft/azure-pipelines-agent/blob/66e6e9a9aa4503139f5dcf4a9894ce349b68e0ab/src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs#L69-L74

The code there already checks for well-known accounts, skipping the password prompt. The same could be done for managed service accounts. A simple check, that would avoid talking to the AD first, would be to check for a trailing dollar sign (`$`) since managed service accounts will end with that when used.

Let me know if you want me to contribute any of these changes, and I will happily do so.

---

> The agent uses OAuth tokens per build to access resources. Is there a specific reason you need the service to run as a gMSA account instead of network service or local system? Our goal is the account the agent runs as is mostly irrelevant. I'm interested in your scenario.

The agent uses OAuth to talk to Azure DevOps, yes. But this is about the permissions the process *executing* the jobs runs with. If you run your agent with the default NT Service account, then you are essentially giving it administrator privileges. It shouldn’t be surprising that we don’t want to give administrator access to a process that locally runs arbitrary code that is checked in remotely. So using a separate account gives us control over what the process can do, and what resources it can access. And using gMSA for that is considered a good practice.

**Comment by jimbo8098** [comment]
I would love to use gMSAs in order to forgo the need to have passwords floating around in my configurations so this would be great to see. I confirm the same as @poke , I see the following:

```
[2021-07-22 16:51:51Z INFO WindowsServiceControlManager] LogonAccount after transforming: DOMAIN\WinAzureAgent$, user: WinAzureAgent$, domain: DOMAIN
[2021-07-22 16:51:51Z INFO CommandSettings] Arg 'windowslogonpassword': ''
[2021-07-22 16:51:51Z INFO CommandSettings] Flag 'unattended': 'True'
[2021-07-22 16:51:51Z INFO PromptManager] ReadValue
[2021-07-22 16:51:54Z ERR  Agent] System.ArgumentNullException: Value cannot be null. (Parameter 'Invalid configuration provided for windowslogonpassword. Terminating unattended configuration.')
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.PromptManager.ReadValue(String argName, String description, Boolean secret, String defaultValue, Func`2 validator, Boolean unattended)
   at Microsoft.VisualStudio.Services.Agent.Listener.CommandSettings.GetArgOrPrompt(String argValue, String name, String description, String defaultValue, Func`2 validator)
   at Microsoft.VisualStudio.Services.Agent.Listener.CommandSettings.GetWindowsLogonPassword(String accountName)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.WindowsServiceControlManager.ConfigureService(AgentSettings settings, CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2021-07-22 16:51:54Z ERR  Terminal] WRITE ERROR: Value cannot be null. (Parameter 'Invalid configuration provided for windowslogonpassword. Terminating unattended configuration.')
```
If you add a fake password, then authentication fails and agent configuration fails with it. If you specify a blank string as the password, an InvalidOperationException is thrown and the agent configuration fails.

Were the --windowsLogonPassword argument to simply be ignored, that would seem to be the fix. The exact same fix @poke recommends seems to be the solution.

**Comment by tastyeggs** [comment]
Azure DevOps team, you should take a look at this issue. It is Microsoft's [best-practice security guidance that we use gMSAs for services](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/service-accounts-group-managed), as regular user accounts for these purposes expose security issues.

So the only conclusion that we can come to after 3.5 years of this issue being open, in a service that we pay for, is that either the Azure DevOps team does not care about best-practice security guidelines that their own organization creates, or that the person in-charge of triaging and prioritizing these issues doesn't understand security.

I strongly urge you to consider fixing this issue. As it stands today, the only service in our entire cluster that require hard-coded passwords that need to be floated around is the Azure DevOps Agent.

Please fix this.

**Comment by jimbo8098** [comment]
While not ideal, btw, I had success setting the credentials the default unattended user then setting the service to what I needed manually. The ansible for it basically boiled down to:

So after a rework I did find that I could use the Azure Agent with a gMSA using:
```
     - name: Configure agent
       win_shell: ./config.cmd --unattended --runAsService --url "https://dev.azure.com/{{ agent_account }}" --auth pat --pool "{{ agent_pool }}" --token "{{ agent_token }}" --agent "{{ agent_name }}"
       args:
         chdir: "C:\\azagents\\{{ agent_account }}"
 
     - name: Assign service to gMSA
       win_service:
         name: "vstsagent.{{ agent_account }}.{{ agent_pool }}.{{ hostname }}"
         username: "{{ agent_win_user }}"
```
I added some bits to the above for my organisation but you get the idea. In the above I'd set agent_win_user to the gMSA.

**Comment by poke** [comment]
@tastyeggs I wouldn't go that far. Yes, it is a bit annoying that you cannot set up the service to use a gMSA during setup but it's not impossible. As mentioned earlier you can reconfigure the created service to use a different account after it has been created.

So yes, an annoyance but not a super critical security issue.

That being said, I'm still willing to contribute a fix.

**Comment by biiiipy** [comment]
> Azure DevOps team, you should take a look at this issue. It is Microsoft's [best-practice security guidance that we use gMSAs for services](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/service-accounts-group-managed), as regular user accounts for these purposes expose security issues.
> 
> So the only conclusion that we can come to after 3.5 years of this issue being open, in a service that we pay for, is that either the Azure DevOps team does not care about best-practice security guidelines that their own organization creates, or that the person in-charge of triaging and prioritizing these issues doesn't understand security.
> 
> I strongly urge you to consider fixing this issue. As it stands today, the only service in our entire cluster that require hard-coded passwords that need to be floated around is the Azure DevOps Agent.
> 
> Please fix this.

100% this. Let's not forget MS is one of worlds biggest companies and we have to beg them to enable out-of-the-box basic security features.

**Comment by rkieslinger** [comment]
Bump. Same feature request. Pls come one MS!

**Comment by zbuchli** [comment]
Also facing this same issue. Would love to see this feature get integrated into the next release.

**Comment by aledeniz** [comment]
I am not sure how this is not the top priority of the team delivering the agent.
To be honest in your place I would (1) allow the configuration as gMSA during the deployment and (2) recommend all your users to adopt that.

**Comment by rkieslinger** [comment]
> How come the support for gMSA has not been added after more than two years it was asked for? If I am not mistaken, it should not be harder then allowing to specify no password during configuration.
> 
> My workaround is to configure the agent service to run as NETWORK SERVICE, and then use sc.exe to reconfigure the created service:
> 
> `sc.exe config vstsagent.Org.Pool.Name obj= yourgmsa$@youdomain.com password= ""`
> 
> Next, remove NETWORK SERVICE from VSTS_AgentService_XXXX group and add yourgmsa$@youdomain.com instead.

Is it necessary to grant the gMSA "Log on as a service" rights?

**Comment by anatolybolshakov** [comment]
Hi everyone! We are currently working on this issue - created [PR](https://github.com/microsoft/azure-pipelines-agent/pull/3791)

**Comment by rkieslinger** [comment]
@anatolybolshakov Thank you very much for putting the time and effort in. Can I kindly ask you, when we can expect the feature to be released? I have to set up a bunch of new build servers and that change would come in very handy 😊
