### ISSUE TITLE
Agent is stuck at tf.exe Get Sources step

### ISSUE THREAD

**Issue by creoman** [Microsoft/azure-pipelines-agent#1365]
The last thing I see in a log:
Matching workspace found.
tf vc status /workspace:ws_1_6 /recursive /nodetect /format:xml /collection:http://***/ /loginType:OAuth /login:.,******** /noprompt

I tried to run tf.exe without parameters from externals\vstsom\ (on the buid machine)
It displays help message and then waits for about minute or two before returning me to console prompt.

TFS 2018 on premises
tf.exe version: 15.121.26803.0

**Comment by TingluoHuang** [comment]
@creoman can you share your agent/worker diag log?

**Comment by TingluoHuang** [comment]
close as we are not getting any response for a while. :)
