### ISSUE TITLE
Build logs not fully persisted when build fails due to timeout

### ISSUE THREAD

**Issue by chrispat** [microsoft/azure-pipelines-agent#1413]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## Agent version and platform
Version of your agent? 11.120

OS of the machine running the agent? Linux

## VSTS type and version
VSTS

If On-Prem TFS, which release, 2015 RTM/QU1/QU2?

If VisualStudio.com, what is your account name? http://devdiv.visualstudio.com

## What's not working?
When a build is cancelled due to timeout it appears that the overall Job log and the log from the task that was running is not uploaded to the server.  this makes it very difficult to debug these types of issues.

**Comment by Djvacto** [comment]
Hey @chrisrpatterson 

Just to clarify, is the timeout the same as the kind described [here](https://github.com/Microsoft/vsts-agent/blob/47875bd0ec301de77373fd26f78273d889c91a1a/docs/troubleshooting.md#workaround-httptimeoutexception)?
