### ISSUE TITLE
Layout of our command doc is bad

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/azure-pipelines-agent#1414]
it makes you scroll.

this should be a vertical web layout:  https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

**Comment by Djvacto** [comment]
@bryanmacfarlane When you say vertical web layout, do you mean something like [this?](https://css-tricks.com/responsive-data-tables/)

Main downside I would see is the table could get potentially kinda long vertically, but at least there is only scrolling in one dimension, and maybe it could be helped by expanding the content of the row the user is looking for?
