### ISSUE TITLE
Deployment Groups - Cannot Add Agent To Multiple Deployment Groups

### ISSUE THREAD

**Issue by alpacamybags118** [microsoft/azure-pipelines-agent#1421]
I'm working through configuring agents on our various servers and adding them to deployment groups. I noticed as I was going through configuration that you cannot add an agent to multiple deployment groups.  It seems that if you want to have a machine to be part of multiple deployment groups, you have to install multiple agents on the server.

This doesn't necessarily scale very well as that's more resource being taken away from the machine and more agents to maintain/upgrade.

There are cases where a server may be part of multiple application groups, and those application groups may contain multiple servers that aren't in the same "family". You can technically accomplish these deployments by adding multiple deployment group phases in the release, but this can get messy and hard to maintain over time.

I think it should be possible to add an agent to multiple deployment groups, to get around these issues of scaling and maintainability.

**Comment by kmkumaran** [comment]
If you are interested in sharing the agent across multiple DGs, you can follow the guidance here. https://blogs.msdn.microsoft.com/devops/2018/01/11/sharing-of-deployment-groups-across-projects/

**Comment by alpacamybags118** [comment]
Thanks for getting back to me! I don't think this is quite what I'm looking for unfortunately. I actually don't even have the options listed there. To be clear, we are using on-prem TFS and not VSTS.

Our setup currently uses one big team project for most items. What I want to accomplish is while using one team project, being able to associate one agent on a server to multiple deployment groups, and not having to install an agent on the server for each deployment group that I want that server to be part of.

Let me know if you need any more information on my setup or what I'm looking for.

**Comment by chshrikh** [comment]
@alpacamybags118 we currently dont support the agent sharing with DG's in same project.

**Comment by eanders-MS** [comment]
@chshrikh Can you suggest a workaround? My use case: I have a deployment group with a set of VMs in it. When I bring up a new VM, I want to deploy to just the new one. One way I thought to do this was to have it be part of two deployment groups: the All VMs group and another group containing just the single VM itself.

I tried filtering the deployment group by machine tag, but couldn't get that working. All examples show machine tags like "web" and "db". But machine tags are of the form name:value, not just name.

**Comment by chshrikh** [comment]
@eanders-MS I think [this ](https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/jul-10-vsts#automatically-deploy-to-new-targets-in-a-deployment-group)should help you.

You can deploy the latest deployment on newly added targets with same tag in DG.

**Comment by eanders-MS** [comment]
Oh nice! That should do the trick. Thanks.
