### ISSUE TITLE
Config TFS 2017 or later download agent path to on-prem TFS Server

### ISSUE THREAD

**Issue by JackyChiou** [Microsoft/azure-pipelines-agent#1451]
Scenario:
Just like https://github.com/Microsoft/vsts-agent/issues/903
1. Customers' environment can't connect to internet.
2. I understand the installation iso file size is important.

Is it possible let us config it?
1. Customers can download the agent zip file and copy it to TFS AP server. The path can be accessed by agents.
2. Agents can perform update process via TFS server.

Thank you for your consideration.
Jacky

**Comment by bryanmacfarlane** [comment]
Yes, we have that exact feature on our backlog.  Place the zip in a prescribed place on the ATs and the product and updates will discover it

**Comment by JackyChiou** [comment]
Thank you for your reply.

從我的 iPhone 傳送

Bryan MacFarlane <notifications@github.com<mailto:notifications@github.com>> 於 2018年3月14日 下午7:07 寫道：


Yes, we have that exact feature on our backlog. Place the zip in a prescribed place on the ATs and the product and updates will discover it

**Comment by japj** [comment]
@bryanmacfarlane any insight if this backlog item is in the TFS2018 or next major version timeline?

**Comment by TingluoHuang** [comment]
https://docs.microsoft.com/en-us/tfs/release-notes/azuredevops2019#locally-update-your-agent

close this issue, the feature is checked-in and included in Azure DevOps Server 2019

**Comment by riveryc** [comment]
> https://docs.microsoft.com/en-us/tfs/release-notes/azuredevops2019#locally-update-your-agent
> 
> close this issue, the feature is checked-in and included in Azure DevOps Server 2019

Hi @TingluoHuang ,

Actually I don't see any documentation to describe how to do this... I saw the release notes, but still don't know how to ... 
Is there any doc I can follow?

I'm located in China and the access to MS's VS Agent download is super slow, I have to use local install... 


Thanks
River
