### ISSUE TITLE
Cooperative cancel support in tasks

### ISSUE THREAD

**Issue by alanmcgovern** [microsoft/azure-pipelines-agent#1452]
When a step takes too long to complete in VSTS it times out and the build is cancelled.

If the issue is a rare deadlock in a process it can be hard to reproduce locally. To make it easier to diagnose these things after the fact Mono has the ability to write a stacktrace for all managed threads on demand. All you need to do is send the `QUIT` signal to the mono process and the data will be written to stdout.

How feasible would it be for VSTS to send a QUIT signal to all processes  do this automatically, or to add some extensibility so it can be enabled by users?

Alternatively/additionally could we attach GDB or LLDB to the process and use them to backtrace it?

An implementation of this which has been used in production for years can be seen here: https://github.com/mono/monkeywrench/blob/master/MonkeyWrench/ProcessHelper.cs

**Comment by bryanmacfarlane** [comment]
That would be something the task would be responsible for (agent knows nothing about mono) - agent just runs a list of tasks.

However the agent is responsible enforcing the timeout.  We would have to send a signal to the task along with a task lib hook (on cancel / timeout).  Basically, a cooperative cancel.

**Comment by alanmcgovern** [comment]
That makes sense. I felt it was more appropriate filed against the agent as only the agent would be in a position to walk all of it's child processes and generate a stacktrace with lldb/gdb. A child process, or a child process of a child process, would not be in a position to do that.

Same reasoning applies to the `kill -QUIT` request :)

**Comment by alanmcgovern** [comment]
I no longer work in this area so I dont have a need to push for this
