### ISSUE TITLE
Unnecessary translation in LOC string

### ISSUE THREAD

**Issue by TingluoHuang** [microsoft/azure-pipelines-agent#1464]
We should never translate `(Yes/No)` in LOC string.

Correct behavior in Windows `DEL`:
```
C:\Users\huang>del /P Checksum_SHA256.txt
C:\Users\huang\Checksum_SHA256.txt，要删除(Y/N)吗?
```
Wrong translation in our agent:
```
PS H:\Source\vsts-agent\_layout> .\config.cmd

>> 连接:

输入 服务器 URL > https://tingweu.visualstudio.com
输入 身份验证类型 (对于 PAT 按 Enter) >
输入 个人访问令牌 > ****************************************************
正在连接到服务器...

>> 注册代理:

输入 代理池 (对于 default 按 Enter) >
输入 代理名称 (对于 HTMS 按 Enter) >
正在扫描工具功能。
正在连接到服务器。
输入 替换? (是/否) (对于 N 按 Enter) >
```

I would never expect customer on localized OS to type the translation of Yes/No.

**Comment by juliobbv** [comment]
In PromptManager.cs, there's code to 'translate' the Y/N values that are input by the user, according to a current locale:

```cs
        public bool ReadBool(
            string argName,
            string description,
            bool defaultValue,
            bool unattended)
        {
            string answer = ReadValue(
                argName: argName,
                description: description,
                secret: false,
                defaultValue: defaultValue ? StringUtil.Loc("Y") : StringUtil.Loc("N"),
                validator: Validators.BoolValidator,
                unattended: unattended);
            return String.Equals(answer, "true", StringComparison.OrdinalIgnoreCase) ||
                String.Equals(answer, StringUtil.Loc("Y"), StringComparison.CurrentCultureIgnoreCase);
        }
```

Which appears to be counter to how command-line prompts in Windows work, like the example Ting gave, or this one from a [Russian OS running chkdsk](https://cloud.githubusercontent.com/assets/22033543/18433307/791b968e-78ef-11e6-8048-823ee7071f41.png).

We could hard-code the prompt options to Y (for yes) and N (for no), respectively. @TingluoHuang, @bryanmacfarlane, what are your thoughts of doing this change?

**Comment by TingluoHuang** [comment]
@juliobbv that's depends on certain locale's keyboard layout, Ex: chinese keyboard layout has (Y/N) and japanese keyboard layout may not has (Y/N)

**Comment by johnliu2016** [comment]
Global linguistic review implemented
Changed to "Y/N" in Chinese languages, other locales are OK as are.

**Comment by jtpetty** [comment]
closing as this issue appears to be addressed
