### ISSUE TITLE
Support for Arm64

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/azure-pipelines-agent#1521]
Arm64 support is now available at the tip of  the .Net Core libraries  and I'm seeing some of its support trickling into vsts-agent.  Do you know if building vsts-agent has been tested yet on arm64 systems running ubuntu and whether or not it should work?  If not,  do you know if you plan on supporting this platform in the future? And if you are when that would be.  If not, could you give me some pointers on what it would take to get the library building?  I can get the .NET core library downloaded an installed for the build but I'm not sure if there are a bunch of nuget packages that are also needed that would need to also be rebuilt for arm64.   Just let me know.  I have an arm64 system running Ubuntu 16.04 that I would like to run the build agent on.

**Comment by TingluoHuang** [comment]
@bbusacker we don't support Linux arm64 yet, and i don't know the timeline to support it. 
I made up a user branch which should create the agent package that runnable in linux-arm64.
https://github.com/Microsoft/vsts-agent/tree/users/tihuang/linuxarm64
You can follow the instruction [here](https://github.com/Microsoft/vsts-agent/blob/users/tihuang/linuxarm64/docs/contribute.md) to build the agent package.

@chrisrpatterson FYI,

**Comment by bryanmacfarlane** [comment]
we've talked about it.  marking as enhancement for consideration

**Comment by jkleinsc** [comment]
@TingluoHuang I need an arm64 build agent so I checked out your branch, but it seems like there isn't a built version .net sdk for arm64:
```
-----------------------------------------
Ensure Dotnet SDK
-----------------------------------------
Download dotnetsdk into /root/vsts-agent/src/../_dotnetsdk/2.0.3
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.3/dotnet-sdk-2.0.3-linux-arm64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.3/dotnet-sdk-2.0.3-linux-arm64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.3/dotnet-dev-ubuntu.16.04-arm64.2.0.3.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet_install: Error: Could not download .NET Core SDK version 2.0.3
Failed: dotnet-install.sh Failed with return code 1
```

Any pointers on getting this working?  Is there an alternate download for the SDK?

**Comment by TingluoHuang** [comment]
@jkleinsc i tweak the script a little bit, try git pull that branch and try run `dev.sh layout` again.

**Comment by tylerl0706** [comment]
@TingluoHuang I'm hitting this issue:

```
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 10497 ms
Expanding 100% 20798 ms
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  2cbcf4bac192d1da6155331a99c128add035972b
  Building 2cbcf4bac192d1da6155331a99c128add035972b --- linux-arm64
  Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
  Copyright (C) Microsoft Corporation. All rights reserved.

    Restoring packages for /Users/tylerleonhardt/Downloads/vsts-agent/src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj...
    Installing Microsoft.IdentityModel.Logging 1.1.5.
    Installing Microsoft.IdentityModel.Tokens 5.1.5.
    Installing Microsoft.Bcl 1.1.9.
    Installing System.IdentityModel.Tokens.Jwt 5.1.5.
    Installing Microsoft.Net.Http 2.2.22.
    Installing System.ComponentModel.Annotations 4.4.1.
    Installing YamlDotNet.Signed 4.2.1.
    Installing System.Threading.Tasks.Dataflow 4.8.0.
    Installing Microsoft.IdentityModel.Clients.ActiveDirectory 3.17.2.
    Installing System.Security.Cryptography.OpenSsl 4.4.0.
    Installing System.Security.Cryptography.ProtectedData 4.4.0.
    Installing HtmlAgilityPack 1.6.5.
    Installing Microsoft.AspNet.WebApi.Client 5.2.3.
    Installing System.Configuration.ConfigurationManager 4.4.1.
    Installing vss-api-netcore 0.5.61-private.
    Generating MSBuild file /Users/tylerleonhardt/Downloads/vsts-agent/src/Microsoft.VisualStudio.Services.Agent/obj/Microsoft.VisualStudio.Services.Agent.csproj.nuget.g.props.
    Generating MSBuild file /Users/tylerleonhardt/Downloads/vsts-agent/src/Microsoft.VisualStudio.Services.Agent/obj/Microsoft.VisualStudio.Services.Agent.csproj.nuget.g.targets.
    Restore completed in 11.97 sec for /Users/tylerleonhardt/Downloads/vsts-agent/src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj.
/Users/tylerleonhardt/.nuget/packages/microsoft.netcore.app/2.0.0/build/netcoreapp2.0/Microsoft.NETCore.App.targets(19,5): error : Project is targeting runtime 'linux-arm64' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core. [/Users/tylerleonhardt/Downloads/vsts-agent/src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj] [/Users/tylerleonhardt/Downloads/vsts-agent/src/dir.proj]
/Users/tylerleonhardt/Downloads/vsts-agent/src/dir.proj(34,5): error MSB3073: The command "dotnet publish Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj --output "/Users/tylerleonhardt/Downloads/vsts-agent/src/../_layout/bin" --runtime linux-arm64 -c Debug" exited with code 1.
Failed: build
```

on macOS. I'll give it a try on Windows.

**Comment by tylerl0706** [comment]
On Windows it fails before that:

```
-----------------------------------------
Ensure Dotnet SDK
-----------------------------------------
Download dotnetsdk into /e/projects/vsts-agent/src/../_dotnetsdk/2.0.3
dotnet_install: Error: OS name could not be detected: UName = MINGW64_NT-10.0
Failed: dotnet-install.sh Failed with return code 1
/e/projects/vsts-agent/src
```

**Comment by tylerl0706** [comment]
And then on my raspberry pi running Raspbian Stretch:

```
pi@raspberrypi:~/Desktop/vsts-agent/src $ ./dev.sh l
~/Desktop/vsts-agent/src ~/Desktop/vsts-agent/src


-----------------------------------------
Ensure Dotnet SDK
-----------------------------------------
Download dotnetsdk into /home/pi/Desktop/vsts-agent/src/../_dotnetsdk/2.0.3
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.101/dotnet-sdk-2.1.101-linux-arm.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.101/dotnet-sdk-2.1.101-linux-arm.tar.gz
dotnet_install: Error: Could not download .NET Core SDK version 2.1.101
Failed: dotnet-install.sh Failed with return code 1
~/Desktop/vsts-agent/src
```

**Comment by TingluoHuang** [comment]
I published 2 branch for ARM agent for people who want's to try out.
`users/tihuang/linuxarm`  -> 32 bits ARM  @tylerl0706  helped me tested out this one, seems to work.
`users/tihuang/linuxarm64`  -> 64 bits ARM

**Comment by tylerl0706** [comment]
It's awesome 🎉

**Comment by bbusacker** [comment]
@TingluoHuang I tested arm64 and it fails with an illegal instruction error executing:

"dotnet msbuild" 

This is the same issue I had before and seems to be some defect in the dotnet  cli itself.  Can anyone else confirm or deny this problem on an arm64 system?

**Comment by tylerl0706** [comment]
@bbusacker are you building on the arm device?

**Comment by TingluoHuang** [comment]
@bbusacker what kind of device you are using? what's the OS?

**Comment by bbusacker** [comment]
Exynos-based phone development board.  Unbuntu 16.04

Sent from my iPhone

On May 25, 2018, at 8:52 PM, Ting <notifications@github.com<mailto:notifications@github.com>> wrote:


@bbusacker<https://github.com/bbusacker> what kind of device you are using? what's the OS?

**Comment by bbusacker** [comment]
Yes

Sent from my iPhone

On May 25, 2018, at 8:36 PM, Tyler James Leonhardt <notifications@github.com<mailto:notifications@github.com>> wrote:


@bbusacker<https://github.com/bbusacker> are you building on the arm device?

**Comment by TingluoHuang** [comment]
@bbusacker can you share the full output of `./dev.sh layout`

**Comment by TingluoHuang** [comment]
@bbusacker try use dotnet sdk under `/home/ufs/vsts-agent-users-tihuang-linuxarm64/_dotnetsdk/2.1`
run:
`dotnet new`
`dotnet run`

I want to make sure whether dotnet core is supported in your device.

**Comment by bbusacker** [comment]
@TingluoHuang 

dotnet new fails with illegal instruction on ubuntu 16.04 arm64 so it's pretty clear it's a dotnet cli issue.   Can you think of any workaround for this issue?

**Comment by TingluoHuang** [comment]
@bbusacker i would suggest you to seek help from dotnet core people, you can log an issue at https://github.com/dotnet/cli

**Comment by TingluoHuang** [comment]
@jkleinsc what's the full log looks like? i would hope dotnet provide some usefully output before it exits.

**Comment by TingluoHuang** [comment]
@jkleinsc i found something similar online https://github.com/dotnet/roslyn/issues/26505
looks like a CSC issue.

**Comment by TingluoHuang** [comment]
@jkleinsc can you also try use dotnet sdk under /root/vsts-agent/_dotnetsdk/2.1
run:
dotnet new
dotnet run

**Comment by bbusacker** [comment]
@jkleinsc Are you building on an arm64 system directly?  My build seems to be taking a different path than yours.  My path is invoking msbuild to build while yours seems to be invoking publish.  Are you just doing ./dev.sh layout on the command-line?

**Comment by jkleinsc** [comment]
@bbusacker yes building on arm64 directly.  And I am running ./dev.sh layout on the command-line.

@TingluoHuang dotnet new and run seem to work.  Output here: 
```
root@arm64-ci:~/vsts-agent/_dotnetsdk/2.1# ./dotnet new
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.


Templates                                         Short Name         Language          Tags
----------------------------------------------------------------------------------------------------------------------------
Console Application                               console            [C#], F#, VB      Common/Console
Class library                                     classlib           [C#], F#, VB      Common/Library
Unit Test Project                                 mstest             [C#], F#, VB      Test/MSTest
xUnit Test Project                                xunit              [C#], F#, VB      Test/xUnit
Razor Page                                        page               [C#]              Web/ASP.NET
MVC ViewImports                                   viewimports        [C#]              Web/ASP.NET
MVC ViewStart                                     viewstart          [C#]              Web/ASP.NET
ASP.NET Core Empty                                web                [C#], F#          Web/Empty
ASP.NET Core Web App (Model-View-Controller)      mvc                [C#], F#          Web/MVC
ASP.NET Core Web App                              razor              [C#]              Web/MVC/Razor Pages
ASP.NET Core with Angular                         angular            [C#]              Web/MVC/SPA
ASP.NET Core with React.js                        react              [C#]              Web/MVC/SPA
ASP.NET Core with React.js and Redux              reactredux         [C#]              Web/MVC/SPA
Razor Class Library                               razorclasslib      [C#]              Web/Razor/Library/Razor Class Library
ASP.NET Core Web API                              webapi             [C#], F#          Web/WebAPI
global.json file                                  globaljson                           Config
NuGet Config                                      nugetconfig                          Config
Web Config                                        webconfig                            Config
Solution File                                     sln                                  Solution

Examples:
    dotnet new mvc --auth Individual
    dotnet new xunit
    dotnet new --help
```
and:
```
./dotnet run
Couldn't find a project to run. Ensure a project exists in /root/vsts-agent/_dotnetsdk/2.1, or pass the path to the project using --project.
```

**Comment by bbusacker** [comment]
@jkleinsc  do ./dotnet new console  then do ./dotnet run.  

Also could you post the output from ./dotnet --info.  I'd like to compare it to what I have.

**Comment by jkleinsc** [comment]
FWIW the arm64 hardware I am trying to build on is a Hisilicon D05.

**Comment by jkleinsc** [comment]
@TingluoHuang I am now trying the arm build instead of the arm64 one and I am running into this error: 
```
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.CreateAppDomainManager()
   at System.AppDomain.Setup(System.Object)
./dev.sh: line 178: 32203 Aborted                 dotnet --version
```

That I can tell there aren't icu packages that will work on arm, so do you know what I need to do to get past this error?  I see directions here: https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md to use a file called "*.runtimeconfig.json", but I'm not sure where that file is and/or where it should exist.

**Comment by TingluoHuang** [comment]
@jkleinsc you can export CORECLR_GLOBAL_INVARIANT=1 as well

**Comment by jkleinsc** [comment]
@TingluoHuang that doesn't help.  When I run ./dotnet --version I see this error:
```
root@arm64-ci:~/vsts-agent-arm/_dotnetsdk/2.1# echo $CORECLR_GLOBAL_INVARIANT
1
root@arm64-ci:~/vsts-agent-arm/_dotnetsdk/2.1# ./dotnet --version
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.CreateAppDomainManager()
   at System.AppDomain.Setup(System.Object)
Aborted

**Comment by TingluoHuang** [comment]
@jkleinsc what about "_dotnetsdk\2.0.3\sdk\2.0.3\dotnet.runtimeconfig.json" ?

**Comment by jkleinsc** [comment]
@TingluoHuang that worked.  It looks like `dev.sh layout` and `dev.sh build` worked!  Dumb question -- where do I find the executable(s) from the build?

**Comment by vielmetti** [comment]
Is there anything we can do to move this forward? It appears that this is a blocker for Electron development on arm64.

**Comment by kxxt** [comment]
Does dotnetcore support arm64 now?
I found this url , and tried it :
https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.300-linux-arm64-binaries 

I can run dotnetcore apps which I complied on Windows , but when I tried to build a helloworld app , an error occured:
"error MSB6006: "csc.dll" exited with code 139"

#26505

**Comment by TingluoHuang** [comment]
https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#linux
dotnet core haven't support ARM64 yet, but i think you can run the 32 bit app on ARM64 device.

**Comment by TingluoHuang** [comment]
@vielmetti understand, but that problem is not scope to this repo, we rely on dotnet core on OS support.
there are lot of issues at dotnet repo around ARM64, https://github.com/dotnet/core/search?q=arm64&type=Issues
From what i know, the fully ARM64 support work in dotnet core haven't finished yet.

**Comment by NiekGr** [comment]
Since this issue is about arm64, should there also be a issue for arm32?

The documentation is really lacking that vsts-agent is only support for linux x86-64 and nothing else. Now it says it supports several linux distributions.
And because .Net Core 2.1 support arm32, I would expect that VSTS also supported deploying to it.

**Comment by bryanmacfarlane** [comment]
@NiekGr - part of supporting arm is moving to net core 2.1.  Its currently on 2.0.

**Comment by NiekGr** [comment]
@bryanmacfarlane thank you

**Comment by TingluoHuang** [comment]
We add ARM32 support in 2.141.0, here is the final build we are about to release.
https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.141.0

**Comment by jkleinsc** [comment]
Thanks for getting this done @TingluoHuang!  I am really looking forward to using it!

**Comment by vielmetti** [comment]
@TingluoHuang refers to arm32 support, which is great, and the issue refers to arm64 support, which is different.

**Comment by TingluoHuang** [comment]
@vielmetti dotnet core haven't support ARM64 yet, we will produce ARM64 agent once dotnet core support them, i will update the issue title.

**Comment by jkleinsc** [comment]
@vielmetti btw the arm client works fine on the Hisilicon D05 "Type 2A2" hardware.  And I think I can build arm64 builds with in.

**Comment by vielmetti** [comment]
@jkleinsc There are some Arm SoCs that are server-class and also 32-bit capable (that Hisilicon Hi1616). Many (most) of the server-class chips are 64-bit only (Cavium, Qualcomm, Ampere).

**Comment by TingluoHuang** [comment]
https://github.com/dotnet/announcements/issues/82
we will add ARM64 after dotnet core 3.0 release.
