### ISSUE TITLE
Linux proxy credentials storage

### ISSUE THREAD

**Issue by JacobHenner** [microsoft/azure-pipelines-agent#1542]
Reading through the agent's [proxy documentation](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?view=vsts#tabpanel_7ufbwiC3ad-2_unix), I've discovered that proxy credentials are now stored after being encrypted, instead of being saved in cleartext environment variables. The implementation for Linux, however, appears to rely on the value of /etc/machine-id to generate the symmetric encryption key. This machine-id file is globally readable.

Presumably, anyone who would have access to see the cleartext environment variables would also have the ability to obtain the value of /etc/machine-id and the encrypted credentials. If this is true, the stored password can be easily decrypted. Accordingly, I'm trying to better understand the threat model. Is this storage method intended to protect against:

1. Users who have access to run builds through VSTS?
2. Users who have access to modify build pipelines through VSTS?
3. Users who have access to modify the contents of repositories which are to be built using VSTS?
4. Users who have access to the server running the agent, as the user who runs the agent?
5. Users who have access to the server running the agent, but not as the user who runs the agent? 
6. Sysadmins who have storage access to the directory where the agent and its encrypted credentials are stored?
7. Accidental disclosure?
8. Someone/something else?

Do we generally expect all users with permissions to run or modify builds on an agent to have the credentials for the account that the agent is running as?

**Comment by TingluoHuang** [comment]
7. Accidental disclosure

**Comment by JacobHenner** [comment]
With that in mind, should there be a notice within the documentation that states the _encryption_ is only effective at preventing accidental disclosure, and could be easily reversed by a determined adversary?

Could a privilege de-escalation method be used instead (like how web servers manage SSL keys)? The VSTS agent could be started as a privileged user, read these tokens, and then drop the privileged permissions. There'd have to be a way to protect them from being read by rogue tasks, though.

**Comment by bryanmacfarlane** [comment]
The machine-id was to prevent copying the agent and/logs off and being sent around (yes, accidental disclosure).  Same policy with us masking secrets from logs etc...  Getting code running on the box means it's trusted.

Tasks (user code) that runs in the agent is trusted and installed into the account by an admin.  We have discussed the option of allowing running the worker as a different account.  But, the worker has it in memory and proxy info is handed over to tasks programmatically (that's the point, tasks need to talk back to the system).  So a task is handed tokens and proxy creds to do it's work so it doesn't help.  We do extra measures for tokens like time bomb them to the build etc...

The determined adversary would have to get an admin to install that task code it in his account.

**Comment by JacobHenner** [comment]
If the primary purpose of the encryption is to prevent accidental disclosure, can the documentation be updated to reflect that the VSTS admins should not rely on the encryption to prevent users of the agent (through VSTS or otherwise) from obtaining the password of the account used to authenticate against the proxy?

**Comment by bryanmacfarlane** [comment]
By "users of the agent" do you mean tasks?  Of course the admin setting up the agent has it :)

**Comment by JacobHenner** [comment]
Not tasks, steps within a pipeline for a specific build or release. If the user has the ability to modify the build/release definition, the user could obtain the encrypted password value and the machine-id, and then decrypt the password value.

**Comment by bryanmacfarlane** [comment]
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?view=vsts#tabpanel_7ufbwiC3ad-1_unix

"Agent will expose proxy configuration via environment variables for every task execution"

All steps are tasks even script steps.

We also support envvars so you can store however you deem most secure for your environment and pass via startup.

**Comment by JacobHenner** [comment]
On that page:
> We store your proxy credential securely on each platform.

if VSTS users have access to the credentials, and if non-VSTS users with access to the node running the agent can decrypt the credential, this statement is misleading.

**Comment by bryanmacfarlane** [comment]
will chat with some folks

**Comment by vtbassmatt** [comment]
We agreed to either remove the password, or make it really obvious that it's hardcoded and not intended to provide any security.

**Comment by mletterle** [comment]
The text on the page has been updated, looks like this can be closed:

> We store your proxy credential responsibly on each platform to prevent accidental leakage. On Linux, the credential is encrypted with a symmetric key based on the machine ID. On macOS, we use the Keychain. On Windows, we use the Credential Store.
