### ISSUE TITLE
Deployment Group Target can't access its own tags via a built in Release Variable

### ISSUE THREAD

**Issue by MarkIannucci** [microsoft/azure-pipelines-agent#1553]
## Agent Version and Platform
Version of your agent? 2.131.0

OS of the machine running the agent? Windows

## VSTS Type and Version
On-Prem TFS, 2018.2 RC 2

## What would be a good addition to the agent?
It would be very helpful if VSTS offered us the ability to access an Agent's tags via the release variables.  Our particular use case is that we need to create scheduled tasks on a VM.  Our approach is to create a deployment group with a bunch of VMs in it and then store the VMs scheduled task time in a tag.  From there, read the target would read the tag as part of the script and know when to execute the scheduled task.

**Comment by MarkIannucci** [comment]
We worked around this issue, by creating a build script which writes the targets in a particular deployment group to a JSON file which gets added to the build artifact.  The release then reads that file to know what to do.  PowerShell follows:

```
<# create output file #>
$outputFile = New-Item -Path "$env:BUILD_ARTIFACTSTAGINGDIRECTORY\targets.json" -ItemType file
echo "{""targets"": [ " | Out-File -Append $outputFile

<# get deployment group object and members #>
[string] $uriString = "$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$env:SYSTEM_TEAMPROJECT/_apis/distributedtask/deploymentgroups/$env:DEPLOYMENTGROUPID/targets?"
$deploymentGroup = Invoke-RestMethod -Method Get -ContentType "application/json-patch+json" -UseDefaultCredentials -Uri $uriString 

<# write individual target json object to output file because deployment group doesn't create a list of tags and individual target does #>
foreach($target in $deploymentGroup.Value)
{
    [string]$targetId = $target.Id
    $uriString = "$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$env:SYSTEM_TEAMPROJECT/_apis/distributedtask/deploymentgroups/$env:DEPLOYMENTGROUPID/targets/$targetId"
    Invoke-RestMethod -Method Get -ContentType "application/json-patch+json" -UseDefaultCredentials -Uri $uriString |
      ConvertTo-Json | 
      Out-File -Append $outputFile

    <# add comma if there is another item in the array #>
    if ($target -ne $deploymentGroup.value[-1])
    { echo "," | Out-File -Append $outputFile }
}

<# close out JSON #>
echo "]}" | Out-File -Append $outputFile
```

**Comment by MarkIannucci** [comment]
@chshrikh , agreed.  Thank you for tagging and taking this on as capacity allows.

**Comment by eanders-MS** [comment]
This would be a nice enhancement. We sometimes want to deploy to a single instance, vs the entire group. Example is when we add a new VM to the group and need to deploy services to it. We don't want to deploy to all VMs, just the new one.

**Comment by stephenmichaelf** [comment]
@chshrikh Could you take a look? We should either confirm we want to do this or close.

**Comment by chshrikh** [comment]
This is low priority as per customer asks, closing this for now
