### ISSUE TITLE
VSTS Agent routine maintenance to clean downloaded build artifacts as well

### ISSUE THREAD

**Issue by sakash279** [microsoft/azure-pipelines-agent#1563]
Our build agent disk space is getting filled up pretty quickly, as we need to download build drop files on the machine. It would be great if the routine maintenance provided by VSTS can provide the option to clean up the downloaded build artifact directories as well.

It would be great to expose the directories (either a get/set- command, or in the UI or both) selected for maintenance, so that it becomes easier for the customers to understand what is contributing to disk space usage and accordingly update build definitions.

**Comment by bryanmacfarlane** [comment]
@TingluoHuang - let's discuss before we implement.  I have some ideas

**Comment by TingluoHuang** [comment]
@sakash279 @bryanmacfarlane i thought RM add delete artifact directory as part of pool maintenance job, what's your agent version? make sure your have 2.133.3.

**Comment by sakash279** [comment]
Hi Ting,

This is part of build definition step. I just checked our version on the agent and they seem to be a mix of: 2.133.3 and 2.133.2. 

We also have another email thread going on about this discussion with Bryan. 

Thanks,
Akash
