### ISSUE TITLE
Strip or honor ASCII color coding

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-agent#1569]
## Agent Version and Platform
2.133.3
Windows | Linux

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://psd30.visualstudio.com

## What's not working?
When a commandline tool issues ASCII colour coding information (e.g. `[?25l`) they are shown in the logs and make it harder to read.

```
2018-05-19T15:43:16.7926995Z It looks like this is your first time using Cypress: 2.1.0
2018-05-19T15:43:16.7938560Z 
2018-05-19T15:43:16.7958404Z [?25l[15:43:05]  Verifying Cypress can run /opt/vsts/_work/r1/a/xxx-CI/src/node_modules/cypress/dist/Cypress [started]
2018-05-19T15:43:16.7980465Z [15:43:06]  Verifying Cypress can run /opt/vsts/_work/r1/a/xxx-CI/src/node_modules/cypress/dist/Cypress [completed]
2018-05-19T15:43:16.8000804Z [?25h
2018-05-19T15:43:16.8019478Z Opening Cypress...
```
It would be useful to either honor the color coding, somehow instruct/configure the terminal as monochrome or stripping out the nonsense characters.

**Comment by bryanmacfarlane** [comment]
Yeah, this is on our backlog.  labelling as an enhancement.

**Comment by adamralph** [comment]
Any update? As the maintainer of a build package which uses ANSI colours, I'm starting to [get questions](https://github.com/adamralph/bullseye/issues/150).

**Comment by TingluoHuang** [comment]
we are fixing this step by step.
1. get all UTF-8 characters back correctly #1975 
2. the Web UI might already support color coding. :)

**Comment by adamralph** [comment]
Thanks for the info. AFAIK the web UI still doesn't support ANSI colour codes, see https://dev.azure.com/blairconrad/SendComics/_build/results?buildId=9&view=logs&jobId=011e1ec8-6569-5e69-4f06-baf193d1351e&taskId=b8cbf579-6a08-5e02-2788-e25b5bd52b1b&lineStart=13&lineEnd=14&colStart=1&colEnd=1

@blairconrad you reported https://github.com/adamralph/bullseye/issues/150 - are you still seeing this problem in the web UI?

**Comment by blairconrad** [comment]
@adamralph, I see no change. ANSI codes show up in the web UI:

https://dev.azure.com/blairconrad/SendComics/_build/results?buildId=13

**Comment by yaananth** [comment]
The web UI supports minimal set of escape codes, but the full support is coming soon.
We are prioritizing this.
Since this is UI issue and not agent issue, feel free to post something here
https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea

But we understand the request and are working on it.

**Comment by yaananth** [comment]
Changes should be rolling out. We support ANSII color code now.
Here's what we support:

> 0 (reset), 
> 1 (bold), 
> 3 (italic), 
> 4 (underline),
> 22 (not bold), 
> 23 (not italic), 
> 24 (not underline), 
> 39 (default fg), 
> 49 (default bg),
> 
> fg colors - 30 (black), 31 (red), 32 (green), 33 (yellow), 34 (blue), 35 (magenta), 36 (cyan), 37 (white), 90 (grey)
> bg colors - 40 (black), 41 (red), 42 (green), 43 (yellow), 44 (blue), 45 (magenta), 46 (cyan), 47 (white)

**Comment by TingluoHuang** [comment]
Close this issue base on this colorful screenshot. :D
![image](https://user-images.githubusercontent.com/1750815/49951119-31aa6e00-fec7-11e8-9121-8742f6e34acd.png)

**Comment by blairconrad** [comment]
PRETTY!

**Comment by blairconrad** [comment]
Not to be a Negative Nelly, but I notice that while the _completed_ build output looks nice and colourful, the in-progress output does not deal well with the ANSI codes:

![image](https://user-images.githubusercontent.com/3275797/50003074-5f97bd00-ff70-11e8-9faa-7601b151ccc4.png)

(from the in-progress build of https://dev.azure.com/blairconrad/blair%20bullseye/_build/results?buildId=18)

**Comment by yaananth** [comment]
That's a known limitation now unfortunately, we don't use the same view for both views :( 
This is getting addressed though, just won't be super soon :)

**Comment by blairconrad** [comment]
Oh, thanks for the speedy response. Glad it's known!

**Comment by yaananth** [comment]
Here are the known limitations with this feature -

- Visually text won't appear selected if you try to select the text (by copy-paste works)
- Live feed won't honor color codes
- Color codes with < > tags will make them disappear

This is something we decided to live with until we address all of them together in the next spike which is planned soon. We decided to go ahead with the feature even with those as it's much better than showing some random useless characters :)

Thanks for reporting and we understand the issues you mentioned and we plan to work on those, let us know if you find anything else.

For this particular issue, I think having it here makes sense as everything is being discussed here, but in general yes, dev community is the place to track these.

**Comment by blairconrad** [comment]
Thanks for the response @yaananth. I had doubts about https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea as the "idea" at the end sounds more like feature requests, not bug reports.

I eagerly await the next release and appreciate all your efforts.

And I realize that every client is different, but given the choice between "bonus funny characters in the output" and "some sections of the output just omitted altogether", I'd've picked the second. The recovery mode of the first is "just try not to look at the funny characters" while for the second it's "hopefully realize something is wrong and then pore over the source HTML".

**Comment by yaananth** [comment]
You can report a problem: https://developercommunity.visualstudio.com/content/problem/post.html?space=21

**Comment by adamralph** [comment]
@yaananth earlier you said:

> We decided to go ahead with the feature even with those...

So you have knowingly introduced a bug. Why do you need someone to "report" it?

**Comment by olafurpg** [comment]
> Visually text won't appear selected if you try to select the text (but copy-paste works)

@yaananth Is there an open issue to fix this limitation? I searched in the Visual Studio Community but couldn't find a related discussion. Copy-paste works for in-progress builds but it stops working when the colors have rendered after the build completes. To reproduce, try copy-pasting line 4000 from the `CmdLine` entry in https://dev.azure.com/olafurpg/Metals/_build/results?buildId=51

**Comment by sbachstein** [comment]
Have there been any advances regarding the character encoding not being resolved?

**Comment by yaananth** [comment]
[Multistage pipelines feature](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml) will bring new views which will honor ansii codes, evening when live streaming!

**Comment by btl5037** [comment]
While coloring is better with the multistage feature enabled, codes are still dumped in the output of the multistage build

<img width="585" alt="image" src="https://user-images.githubusercontent.com/9400927/63050715-b7911580-bea9-11e9-82a6-903159472096.png">

**Comment by yaananth** [comment]
We support https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit
It's possible the tool is using other specifications, eg: https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit

Which we don't support yet.
However we should be parsing them out.
So, looks like there's some bug there.
Could you send a repo text file or link to where it happens (if it's a public run).
Thanks!

**Comment by btl5037** [comment]
This is actually the output of a `git diff --color`

Here is the link, it is the second step labeled CmdLine. We are just getting started on our migration so we are noticing small nuances like this.

[https://dev.azure.com/Hyperledger-CICD/Fabric/_build/results?buildId=291](Build 291)

**Comment by octogonz** [comment]
(Not sure why this was closed 9 months ago, when the problem was clearly only partially solved.)  But today I noticed that if you enable the "Multi-stage pipelines" preview feature, then colors are displayed properly for the realtime log output.  (In Azure DevOps, click your profile --> "..." --> "Preview features".) 

Hurray! 🎉

**Comment by malkinfedor** [comment]
@octogonz 
Yes, you're completely right, I've enabled this feature and now ansible output looks pretty good!
Thansk for this advice!

**Comment by elisherer** [comment]
Issue is back on release (not build) logs

**Comment by liamfoneill** [comment]
This really is not a finished feature. Take a look at what 'Terraform Plan' output looks like without using the '-no-color' flag:

![image](https://user-images.githubusercontent.com/1243172/70036458-bac12600-15ac-11ea-9130-424d37e05460.png)

Please don't say just use multi-stage pipelines. That is not an option. There are still lots of things you can not yet do in YAML pipeline that can be done in 'Classic'. 

Please prioritize this issue.

**Comment by timotheecour** [comment]
@TingluoHuang could you please re-open this issue, since it's clearly not fixed?

**Comment by TingluoHuang** [comment]
@vtbassmatt FYI.

**Comment by mcollis2** [comment]
Yes we are seeing this issue too with terraform in Azure Devops classic pipelines.  Would very much appreciate a fix on this as it worked 1-2 months ago.

**Comment by jtpetty** [comment]
@azureDaveOps - David, would this be something that your team would own the fix for?

**Comment by scottboehmer** [comment]
Adding @prativen since this looks to be impacting release logs and not build logs.

**Comment by octogonz** [comment]
For me, the PR build logs seem to render correctly with the **"Multi-stage pipelines"** preview feature enabled.  But if that feature is disabled, then the color codes are garbled, making the logs unreadable.  ([Example log](https://dev.azure.com/RushStack/GitHubProjects/_build/results?buildId=2822))

How long will **"Multi-stage pipelines"** be kept in preview? Lots of NodeJS tools want to print colors to their log output.

**Comment by scottboehmer** [comment]
We've started the process of making the multi-stage pipelines feature on-by-default, and I expect to be on everywhere with the option to go back to the old UI removed sometime in early 2020.

**Comment by rene-fonseca** [comment]
@yaananth, not sure if you prefer a separate issue but I'll try this one since it is still open.

**<ESC>[0m** for resetting all attributes is not resetting foreground color - I didn't check if other attributes are reset but this would likely be the case.

Also noticed **<ESC>[4m** for underscore and **<ESC>[3m** for italic are ignored. So maybe there is a general problem for the lower m values. But per your earlier note these codes should be supported.

Example line:
2020-01-02T20:53:10.4177461Z THROW in [34m[1mclass base::MyOtherObject &__cdecl base::Reference<class base::MyOtherObject>::operator *[0m[34m[3m(void)[34m[1m[0m at [37m[1mbase/mem/Reference.h:342[0m

The **<ESC>[0m** just before "at" above - should ensure "at" gets presented in default color - but for now it uses the color that is active before.

Full public log example is available at - I do use ANSI colors a lot and it is really nice the pipeline supports it :)
https://dev.azure.com/renefonseca/base/_build/results?buildId=820&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=3d94a178-cdfb-5c90-a971-5deeccbbe043&l=51

Here is an working example from Visual Studio Code terminal (run on macOS) for comparison:
<img width="865" alt="visual studio code terminal on macos" src="https://user-images.githubusercontent.com/58829966/71696083-53b5ad80-2db4-11ea-8d95-41d408226e03.png">

**Comment by jamessampford** [comment]
I'm using SSH in my pipeline to run a bash script and getting the codes appear as well (rather than the colours), example below:

`2020-01-08T09:08:30.6597072Z [1;34m### RECEIVED BUILD 120 ###[0m`

Tried a variety of escape and colour codes but all the same...
\x1b[1;34m
\x1b[34m
\033[1;34m
\033[34m

**Comment by santiago-ld** [comment]
I'm having the issue using terraform too, hope to see this fixed soon.

**Comment by stephenmichaelf** [comment]
@davekenn Could you route to the right person on your team to take care of this?

**Comment by jz3xyz** [comment]
I'm having the same issue with a bash script in a release pipeline.

I'm setting colors using
```
# Set colors
BOLD="\e[1m"
ITALIC="\e[3m"
RESET="\e[0m"
RED="\e[31m"
GREEN="\e[92m"
CYAN="\e[96m"
```
Ado likes to interpret them as is
```
[96m[1mUsage: ...[0m
```

**Comment by thiagofborn** [comment]
Hello there. 

I hope you guys are having loads of fun. 
However, I need to ask... 

Did you find any workaround for this? 

<img width="703" alt="Capture" src="https://user-images.githubusercontent.com/6710946/74876605-e35eed80-535b-11ea-8761-f83f954ec063.PNG">

**Comment by edjwhho** [comment]
Hi, anyone managed to get a work around for the terraform plan to output colours in azure pipeline?

**Comment by octogonz** [comment]
Today we were trying to make a copy of an Azure DevOps pipeline, but could not find the "clone" menu item.  (Screenshots are shown [here](https://stackoverflow.com/questions/57827447/is-there-a-way-to-clone-or-copy-an-existing-ci-cd-pipeline-in-azure-devops).)

After much frustration, @iclanton figured out that the "Multistage pipelines" preview removes that feature. 😕

So it seems, I have to manually enable "Multistage pipelines"  to see ANSI colors in my build logs, but remember to turn it off when I want to clone a pipeline.  

@scottboehmer was this intentional?  What's the deal?

**Comment by scottboehmer** [comment]
Is your definition using a yaml file? If so, then it is intentional that clone is unsupported because the recommended pattern is to copy the yaml file rather than creating a cloned definition pointing at the same underlying file.

**Comment by up2geek** [comment]
I too would like to see a fix or workaround to allow terraform plan color coding output to display properly in ADO release pipeline log output.

**Comment by octogonz** [comment]
> Is your definition using a yaml file? If so, then it is intentional that clone is unsupported because the recommended pattern is to copy the yaml file rather than creating a cloned definition pointing at the same underlying file.

@scottboehmer No, it is a non-YAML job.  It's a manually invoked job, where we usually edit the steps before running it (e.g. changing which folders it runs in, or skipping certain steps).  Thus creating a Git branch and YAML file would be a clumsy approach.

**Comment by lynn-fisher** [comment]
I would also like to see a fix for this when I run my Mocha tests locally using a deeply equal to compare two objects I get a colorful console output where the actual colors represent the difference between the two objects being compared

![image](https://user-images.githubusercontent.com/34034697/78801684-e6b64300-79b4-11ea-86d6-74e274864279.png)

When I run this test in an Azure pipeline using YAML there is no color in the output which renders the results virtually meaningless. I could go with the '-' and '+' but with a lot of results that is hard to read.

Any settings I have missed or is this still not possible?

**Comment by ppanyukov** [comment]
I'm not 100% sure why it's so difficult to take raw log files and convert them to HTML and do ASCII colors? Here is a bash script that does it, this can be done even in bash.  https://github.com/pixelb/scripts/blob/master/scripts/ansi2html.sh

It works for terraform output and git diff and whatnot.

**Comment by octogonz** [comment]
Well, "Multi-stage pipelines" has been officially released.  We can no longer workaround this problem by disabling the preview feature. 

@scottboehmer  What's the product team's position on:
- providing a way to clone a classic (non-YAML) pipeline
- properly supporting ASCII colors like every other tool does

It may be that these customer requests are not a priority and will never get fixed.  In that case, please just say so and close the issue.

**Comment by scottboehmer** [comment]
As far as I'm aware, clone is working for non-yaml pipelines. On a sample project, I see it in the menu when on a definition's page:
![image](https://user-images.githubusercontent.com/30327435/82238436-46cdcc80-9905-11ea-97b4-425438963652.png)
@octogonz do you not see that menu entry? Or does it fail when you try to use it? If it is a failure, could you share any error information logged in the browser's console.

I'm not sure on the status of extending ASCII color support on the logs page, so adding @vijayma and @jtpetty to see if they know of any plans for additional work.

**Comment by octogonz** [comment]
> As far as I'm aware, clone is working for non-yaml pipelines. On a sample project, I see it in the menu when on a definition's page

You are right! I overlooked that. Consider the "Clone" item resolved then!  👍

**Comment by Marcus-James-Adams** [comment]
This issue thread seemed to get hijacked by cloning but can we have an update as to where we are with colours displaying as escape characters and other text corruptions in the release pipelines as currently, it makes them unreadable, especially for actions like terraform that use colours and characters to explain what changes there will be.

eg
`2020-06-25T09:50:54.6379881Z [1m  # azurerm_network_security_rule.rdp-access-utils-subnet[0m will be updated in-place[0m[0m
2020-06-25T09:50:54.6384644Z [0m  [33m~[0m[0m resource "azurerm_network_security_rule" "rdp-access-utils-subnet" {
2020-06-25T09:50:54.6385107Z         [1m[0maccess[0m[0m                                     = "Allow"
2020-06-25T09:50:54.6398898Z         [1m[0mdestination_address_prefix[0m[0m                 = "*"`

**Comment by tknerr** [comment]
I can confirm on what @ppanyukov commented above in https://github.com/microsoft/azure-pipelines-agent/issues/1569#issuecomment-618505636 that it does not work for Release pipelines yet.

**Comment by diegosucaria** [comment]
Hello everyone!  

No updates so far on this 2-years-old issue???

Did anyone found a workaround?

**Comment by santiago-ld** [comment]
> Hello everyone!
> 
> No updates so far on this 2-years-old issue???
> 
> Did anyone found a workaround?

Nop, just using -no-color for terraform :/.

**Comment by edjwhho** [comment]
alternatively you can use azure cli task and run terraform commands manually which will give you colour output from terraform commands.

```
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'terraform'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #!/usr/bin/env bash
          echo "**************************************"
          echo "  setting up env vars"
          export ARM_SUBSCRIPTION_ID=$(az account show --query="id" -o tsv)
          export ARM_CLIENT_ID="${servicePrincipalId}"
          export ARM_CLIENT_SECRET="${servicePrincipalKey}"
          export ARM_TENANT_ID=$(az account show --query="tenantId" -o tsv)
          export ARM_ACCESS_KEY="${accessKey}"
          echo "***************************************"
          echo "  terraform init"
          terraform init
          echo "***************************************"
          echo "  terraform plan"
          terraform plan

**Comment by ed-graham** [comment]
Now 23rd December 2020 and the problem of output colours and formatting in release-pipeline logs (as so eloquently explained by @Marcus-James-Adams) is still at large.  Don't suppose the product team fancies giving us all a late Christmas present?  In the meantime, I'll continue to use the `-no-color` work-around suggested by @santiago-ld .

**Comment by onlyann** [comment]
The output from `New-AzResourceGroupDeployment -Whatif` isn't color coded using the AzurePowershell task from the pipeline web console.
Is it related to this issue?

**Comment by stvpalumbo** [comment]
March 19th 2021 - Colors are still not supported properly in the Release Pipeline log viewer. This makes our selenium step so painful to debug...

![image](https://user-images.githubusercontent.com/13643497/111834730-3bdf2200-88b1-11eb-9b14-6541d16053e2.png)

**Comment by JoseFMP** [comment]
Would be great to have the colors supported. Otherwise when you copy the text directly from the output you copy those wrong characters instead of the right colored one's. Even if you lose the colors, I want to copy the right chars!

**Comment by DmytroSokhach** [comment]
> Close this issue base on this colorful screenshot. :D

@TingluoHuang 
could you please share how did you get this screenshot? https://github.com/microsoft/azure-pipelines-agent/issues/1569#issuecomment-447024091

**Comment by Marcus-James-Adams** [comment]
A year on and yet still no response

**Comment by marciobarbato** [comment]
any updates for that feature ?

**Comment by jgabyey** [comment]
Is there any ETA on a resolution to this issue? When I look at that StdErr portion of the log file at "C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.12\Status" after running a CSE, I've run into the issue where PowerShell7 error messages are also outputting their ANSI escape characters, and it makes debugging a nuisance. See an example below: 

`{"name":"StdErr","status":"success","code":0,"formattedMessage":{"lang":"en-US","message":"\u001b[91mLog-Output: \u001b[0mC:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.12\\Downloads\\0\\MainScript.ps1:85\r\n\u001b[96mLine |\r\n\u001b[96m  85 | \u001b[0m         \u001b[96mLog-Output -output $_ -tag 3 -path $homeDir\u001b[0m\r\n\u001b[96m     | \u001b[91m         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n\u001b[91m\u001b[96m     | \u001b[91m2021/08/27 18:38:32.8804 FATAL ERROR\r\n\u001b[96m | \u001b[91mMissing Services \r\n\u001b[0m\r\n"}}]}}]`

**Comment by smeathers** [comment]
Debugging a Teraform pipeline has lead me here.  Like others I can make the logging more readable with the -no-color switch but the lack of colour in the output still reduces the readability of what I'm looking at.  It would be a huge help if this could be supported.

**Comment by jwedel** [comment]
Would also appreciate this, as Cypress output in releases windows is pretty much unreadable:
![image](https://user-images.githubusercontent.com/4849728/150963781-7602e62e-3cac-4668-aa31-e671fee2a6a8.png)

**Comment by ransagy** [comment]
Another chime in hope someone from MS responds to this in any way, including "this is backlog/icebox/what".
@bryanmacfarlane @TingluoHuang @yaananth @vijayma @jtpetty - Can anyone point us at the right direction here?

**Comment by anatolybolshakov** [comment]
Hi everyone, this issue does not seem to be related to the agent itself (since agent does not handle logs view, but only sends them to server) - for the Azure DevOps features/issue reports I would suggest to open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.

**Comment by wwestrop** [comment]
For anyone following the thread: https://developercommunity.visualstudio.com/t/Colorful-logs-in-Release-Pipeline-as-wel/1652600

**Comment by martingalvan-nordic** [comment]
@jessehouwing why is this closed? I'm still seeing this issue, particularly on the "raw logs" view of Azure CI pipelines.

**Comment by MattJeanes** [comment]
This is still an issue unfortunately

**Comment by FreddyAyala** [comment]
Hello, this is still a big issue, are we actively working on it? If you give me access to the internal Repo here in MS I can try to give a hand. Thanks.

**Comment by solidcloudio** [comment]
Energizer bunny...   Still going..

**Comment by williamdphillips** [comment]
Any progress on this?

**Comment by FreddyAyala** [comment]
Bump, still very important feature missing.

**Comment by mloskot** [comment]
Any news on fixing this annoyance?

**Comment by mloskot** [comment]
The feedback I've just received from Azure DevOps to my request posted at https://twitter.com/mloskot/status/1760636981028016191 seems to suggest that begging Azure for attention here is a waste of time:

> [We understand how you feel. However, at the moment, our dev community is the best place to report issues or suggest ideas to our product team.](https://twitter.com/AzureDevOps/status/1760668701798347202)

**Comment by dewolfs** [comment]
Looking forward to get this fixed

**Comment by MaxSolabAzb** [comment]
One more voice to get this fixed. Or at least give me an option to opt out of the colours so that my logs don't look like dog's vomit. And adding `$PSStyle.OutputRendering = "PlainText"` does not seem to do anything. 


![image](https://github.com/user-attachments/assets/ecac3472-0945-417c-9d3c-151ae281cd64)

**Comment by Depact** [comment]
Another one bumps the thread. Looking forward to be fixed

**Comment by Saulopv** [comment]
+1

**Comment by OranguTech** [comment]
+1

**Comment by BenjaminBrienen** [comment]
+1

**Comment by Nico385412** [comment]
+1

**Comment by Landom3562** [comment]
+1
