### ISSUE TITLE
Agents fail to start

### ISSUE THREAD

**Issue by acm74** [Microsoft/azure-pipelines-agent#1610]
I am provisioning new VMs for use in a testing process.  The VMs use Windows 10 Pro (Azure gallery image RS3-Pro, or RS2-Pro), and use DS2v2 (2 vCPU, 7GB RAM). The VMs are configured with a VSTS agent running as a service and connected to a deployment group.  

I am seeing 2 problems:

1 - the provisioning will report failure, with agents taking > 6 hours to establish communication with VSTS (over 1 hour before any agents are communicating with VSTS)

inspection of VMs will typically show successful configuration of an agent, and rebooting VMs is often enough to establish agent communication with VSTS/deployment group.

2 - when starting VMs, not all agents will start.  6-10 agents (out of 99) will randomly not start, requiring VMs to be restarted.  

This is a serious impediment to being able to use these VMs in a VSTS release process.

**Comment by bryanmacfarlane** [comment]
For failure to start, grab the _diag logs and attach.  They should highlight what's happening in the the failure to start cases.

Regarding the 6 hours, is that your code provisioning the VMs?  Have you broken down the time?  Where is that code running?  A hosted vs 2017 machine?  (those are limited to 6 hours, private build/release agents on your own VMs have no limits).

As a comparision our machine management provisions machines into a pool in minutes and the agent starts up almost immediately.  So something odd is going on.

**Comment by acm74** [comment]
@bryanmacfarlane I am running a VSTS release process to provision multiple VMs via an ARM template.  It's using a hosted VS2017 agent.  The release I have going at the moment has been running for just over 2 hours, and there are now 92 agents registered in the deployment group (out of 99 being provisioned).

All but a few minutes of the releases have been taken within an azure resource group deployment task, which is executing the ARM template provisioning.

A quick inspection of _diag logs (Agent_20180606-082625-utc) on a VM where the agent failed to start showed:
System.Net.Http.WinHttpException: The server name or address could not be resolved

_diag logs from that VM are attached.
[lab2-23-dgagentlogs.zip](https://github.com/Microsoft/vsts-agent/files/2076146/lab2-23-dgagentlogs.zip)

**Comment by acm74** [comment]
@bryanmacfarlane one of your colleagues told me a couple of months ago that there were issues with VSTS agents and VMs with < 4 CPU cores.  This was part of a [previous issue](https://developercommunity.visualstudio.com/content/problem/188185/provisioning-vm-false-negative-failure.html) where the release was always reporting that provisioning had failed, because it was taking longer than expected for the extensions on the VM to be provisioned.  I am not sure if this is still a problem

**Comment by bryanmacfarlane** [comment]
I'm sending this to the release team.  I think you need to separate the agent application (this repo) from the assertion about the VM (machine) needing 4 cores for your scenario (if that assertion is indeed correct).   Not sure what the application can do but we will certainly look at it.

If the hosted agent specs (6 hour max, 2 cores) is not sufficient for your scenario, then the other option is to create a private build/release agent to run the release on.

https://docs.microsoft.com/en-us/vsts/pipelines/agents/agents?view=vsts

I'm forwarding this to the release folks (Bishal, Muthu) to investigate and comment on.

**Comment by acm74** [comment]
@bryanmacfarlane the issue with < 4 cores was supposed to have been addressed last month.  I mention it because that's what I was told was the root cause of previous releases failing.  

When I started provisioning these VMs, I expected the ARM template execution to complete in around 40 minutes (using a hosted agent).  As it is currently, I can only expect that this will not complete, but will timeout instead.

From Azure portal I can see that there are problems with some of the VMs, but I cannot find further information.  e.g. this is what I see from my current release:
Provisioning failed. OS Provisioning for VM 'wkb-lab3-28' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later.. OSProvisioningTimedOut

**Comment by niadak** [comment]
@acm74 , Can you try the following:

1. Create a release to provision VMs without configuring VSTS agent and check if it is faster? This may be issue with VM provisioning and not related to VSTS agent.

2. Configure VSTS agent to deployment group manually from the newly provisioned VM. Steps to do that are:
       a. Go to Deployment group details page
       b. Click on Use PAT token check box and click on copy script on clip board button.
       c. Login to the Azure VM, Open PowerShell admin console and run the script.

![image](https://user-images.githubusercontent.com/11937515/41080398-f14009be-6a43-11e8-8e66-9bb66897678a.png)


Please let us know which step is taking most of the time. We can debug further once we the info.

**Comment by bishal-pdMSFT** [comment]
@acm74 can you please share following information with us:

1. ARM template deployments logs. You can get it by going to the resource group which you created using VSTS
 
![image](https://user-images.githubusercontent.com/7830141/41080556-bb5e6484-6a44-11e8-9fbb-7fdfa3a8b242.png)
 and then clicking on the latest deployment which timed out
  
![image](https://user-images.githubusercontent.com/7830141/41080587-e70d28ea-6a44-11e8-99c4-49833fd9516d.png)
 if you click on operation details you will be able to see more details

2. VM extension logs from one of the VMs which did not get configured properly. You can get the logs by remoting into the VM at location C:\windowsazure\logs\plugins\Microsoft.VisualStudio.services.Teamservicesagent folder.

**Comment by acm74** [comment]
@bishal-pdMSFT the deployment that timed out is still marked as in progress.  The VMs (including storage account, IP addresses, NICs) deployed successfully.  All the VM extensions are marked as in conflict.  These VMs have 3 extensions - for IAAS Diagnostics, a custom extension for WinRM, and the Team Services Agent extension.  All show the same error- "an internal execution error occurred".

[TeamServicesAgentLogs.zip](https://github.com/Microsoft/vsts-agent/files/2079361/TeamServicesAgentLogs.zip)

![deployfail_lab2](https://user-images.githubusercontent.com/36503947/41084830-799f69a8-6a35-11e8-8997-a0cd465f2e17.PNG)

**Comment by acm74** [comment]
@niadak I will remove all the extensions from my template and attempt a small release with that.  Given what I just posted, I expect this to complete quickly and successfully.

**Comment by bishal-pdMSFT** [comment]
@acm74 The TeamServicesAgent extension logs don't point to anything wrong. It has successfully configured agent against deployment group. Are you still not seeing this deployment group agent in VSTS?
The culprit here seems to be Conflict status. Can you also look into logs of other extensions - they are in similar place as TeamServicesAgent logs. Is any other extension failing with "an internal execution error occurred"?
Are you creating new VM for every deployment, or just updating existing VM with extensions?

**Comment by acm74** [comment]
@bishal-pdMSFT I can't see anything wrong with the other 2 extensions.  The logs from the same VM are attached here.

To clarify what I am trying to do - I am building new VMs to use for Coded UI Testing.  Once the VMs is provisioned, I am using the deployment group agent to configure all the software we need, along with all the other little configuration details necessary for Coded UI Testing.

[Microsoft.Compute.CustomScriptExtension.zip](https://github.com/Microsoft/vsts-agent/files/2079467/Microsoft.Compute.CustomScriptExtension.zip)
[Microsoft.Azure.Diagnostics.IaaSDiagnostics.zip](https://github.com/Microsoft/vsts-agent/files/2079468/Microsoft.Azure.Diagnostics.IaaSDiagnostics.zip)

**Comment by acm74** [comment]
@bishal-pdMSFT I also see Azure portal come up with these messages 

This is from the latest lab I am building.  For the VMs listed, there are no extensions installed (no log files either).

![provisionfail](https://user-images.githubusercontent.com/36503947/41087534-41a91f32-6a3d-11e8-873e-f18983ecd473.PNG)

**Comment by acm74** [comment]
@niadak ARM template without extensions provisioned successfully 3 VMs in approx. 11 minutes.  I had to wait almost an hour before I could successfully remote into any of the VMs (see screen shot).

The deployment group agent installation took less than 2 minutes to complete on the VMs I could log into.

![cannotlogin](https://user-images.githubusercontent.com/36503947/41090955-bcff6f12-6a45-11e8-927d-2c36bc681931.PNG)

**Comment by acm74** [comment]
@niadak I provisioned 2 new VMs with a larger size (Standard_DS3_v2_Promo, which is 4 core and 14 GB RAM).  Provisioning finished in just under 10 minutes, I was able to remote into VMs within 5 minutes of this and install deployment group agent.

**Comment by acm74** [comment]
@niadak I provisioned 2 new VMs, including extensions, using a 4 CPU, 14GB VM size.  The Provisioning took 30 minutes to complete.  It's now going through post-provisioning configuration.

**Comment by bishal-pdMSFT** [comment]
This looks like the [issue](https://developercommunity.visualstudio.com/content/problem/188185/provisioning-vm-false-negative-failure.html) which you referenced earlier. Let me involve Tejas who was investigating it.

**Comment by acm74** [comment]
@bishal-pdMSFT I have another issue, and I am wondering if this is related to what we are seeing here.  In our post-provisioning configuration we install software.  We're using Chocolatey for some of this, but we see errors like "The term 'choco' is not recognized as the name of a cmdlet, function, 
script file, or operable program".

Sometimes it works and choco commands are available, often they are not.

**Comment by acm74** [comment]
@bishal-pdMSFT has there been any progress?

**Comment by acm74** [comment]
@bishal-pdMSFT this morning I am now seeing that one of my labs has somehow had their interactive agents removed.  This is not the first time I have seen this behavior.


![agentmissing](https://user-images.githubusercontent.com/36503947/41220829-e031e97c-6d62-11e8-9154-e1e49650446b.PNG)

**Comment by acm74** [comment]
@niadak @bishal-pdMSFT I have deleted all 2 CPU VMs, and am in the process of re-creating VMs.  The first group has just been provisioned (using 4 vCPU, 16 GB RAM VM size), and is about to start its post-provisioning configuration.  It took 50 minutes for the provisioning to complete.  I believe the majority of that time was spent provisioning the extensions on the VMs.  All 99 VMs have successfully registered into the deployment group.

**Comment by bishal-pdMSFT** [comment]
@acm74 we are following up with VM team to understand whether the May update has been rolled out or not. I will keep you posted.

**Comment by bishal-pdMSFT** [comment]
@acm74 will it be possible for you to provide the azure subscription id which you are using for provisioning VMs. Also, please tell us the resource group name for 2 CPU VMs which were timed out earlier. I am trying to look into telemetry to get more data.

**Comment by acm74** [comment]
@bishal-pdMSFT I can provide this - is there a less public way I can get the details to you?

**Comment by bishal-pdMSFT** [comment]
please e-mail on our customer queries alias RM_Customer_Queries AT microsoft.com

**Comment by acm74** [comment]
@bishal-pdMSFT @niadak FYI today I will be rebuilding labs - I will post results of this later today.

**Comment by bishal-pdMSFT** [comment]
@acm74 I assume you used 4core VMs only.
Can you check your 2 core VMs to see if they have [KB 4103720](https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=bfe22406-863a-4845-b6bd-c3f5c43e2b7a) installed? This KB contains the fix for VM agent issue. You can RDP into VM and check “Windows Installed Updates” in the Control Panel,

**Comment by acm74** [comment]
@bishal-pdMSFT the new labs are only 4 core VMs.  Neither they nor the remaining 2 core VMs have KB4103720 installed.  

Because these are Windows 10 client VMs, it's really hard to have any control over windows update.  Both 2 and 4 core VMs have updates pending.  I am going to try and get these updates installed and see if KB4103720 can be found.

**Comment by bishal-pdMSFT** [comment]
From whatever info I could get from VM/Image team, this KB will mostly make into gallery in near future - 1 week or so. But nothing in my hand. I will update you as and when I get more info.
Unfortunately, till that time you will have to keep using 4 core VMs.

**Comment by acm74** [comment]
I will investigate next week whether I can install this directly instead.

Sent from VMware Boxer

On Jun 15, 2018 4:13 PM, Bishal Prasad <notifications@github.com> wrote:

From whatever info I could get from VM/Image team, this KB will mostly make into gallery in near future - 1 week or so. But nothing in my hand. I will update you as and when I get more info.
Unfortunately, till that time you will have to keep using 4 core VMs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Microsoft_vsts-2Dagent_issues_1610-23issuecomment-2D397634219&d=DwMCaQ&c=tv8X2YgD7mG0v9N2vuBcgw&r=xJTxU_1AyVNfmdD-m3wt_-SqdjRcubABKXNgK38tqfo&m=xft4bN277kf-A8ufMESDXZkFkHveQxS4ec6CO52j_M0&s=9mPSlbwEwDCoc5O07mhYT1Fem3pOzlAksE09F24oDcw&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ai0Bi4E3m9-5FZ8AAOe9pCMSBpLnt4EZ4Mks5t88EbgaJpZM4UcUe5&d=DwMCaQ&c=tv8X2YgD7mG0v9N2vuBcgw&r=xJTxU_1AyVNfmdD-m3wt_-SqdjRcubABKXNgK38tqfo&m=xft4bN277kf-A8ufMESDXZkFkHveQxS4ec6CO52j_M0&s=WWiZ0BOsDUFYnG6EwXiLhScMKgO2cWseyM0Rf3o8fEQ&e=>.

Confidential Communication: The contents of this e-mail including any attachment are confidential and intended solely for the person(s) to whom they are addressed. Any reader of this email who is not the intended recipient is notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this e-mail in error, please notify the sender immediately and delete all copies from your computer system. Subsequent alterations to this email after its transmission will be disregarded.

**Comment by tejasd1990** [comment]
@acm74 Can you check with 1-2 core VMs and let us know? I tested and did not get the error this time. Thanks.

**Comment by acm74** [comment]
@tejasd1990 thanks for the update.  I will try to do this next week.  At the moment we are seeing some instability in West Europe region, so I am unsure if we could get a clean result if I tried this now.  I will post again when I've had a chance to try this.

**Comment by acm74** [comment]
@tejasd1990 I still see errors with a 2 core VM deployment.
[VMProvisionLogs_r52_id_804.zip](https://github.com/Microsoft/vsts-agent/files/2197376/VMProvisionLogs_r52_id_804.zip)

**Comment by tejasd1990** [comment]
@acm74 This issue has not been fixed for RS3, but RS4 should work. Can you try with RS4 SKUs and update?

**Comment by TingluoHuang** [comment]
Close this issue since it's not really scope to the agent and our partner team has provided a fix.
