### ISSUE TITLE
Agent update failed after a reboot 

### ISSUE THREAD

**Issue by sibbl** [microsoft/azure-pipelines-agent#1611]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.131 -> 2.133.3

OS of the machine running the agent? Windows

## VSTS Type and Version
usi.visualStudio.com

## What's not working?

We set up several Windows VMs using Azure RM templates and install the VSTS Agent in a deployment group of VSTS. This works properly until there's a new version at some time.

However, after a restart...
1. the machine appeared as offline in the VSTS deployment group
2. the VSTS* windows service was removed
3. the folder structure was changed
![update-dir](https://user-images.githubusercontent.com/866535/41040043-9195f2ba-699b-11e8-856c-d5c0de42a0a7.jpg)

4. the logs files (attached below) shows `Authentication failed with status code 401.`.
5. changing the folder names so that `run.cmd` finds all files and works again, the agent spins up properly and also appears as online. So the stored credentials are still valid.

We had this problem multiple times on several VMs already, also with older versions where the service was not added with "delayed start" (which was added in some recent version) and PATs from other users.

Most important for us: is it possible to disable the auto-update functionality for now until the bug is fixed? Triggering the updates via VSTS works totally fine.

Please include error messages and screenshots.

## Agent and Worker's Diagnostic Logs
[Agent_20180605-081432-utc.log](https://github.com/Microsoft/vsts-agent/files/2076372/Agent_20180605-081432-utc.log)

**Comment by sibbl** [comment]
Hi @TingluoHuang,

thanks for the quick response. Please find the log before the one I already posted attached: 
[Agent_20180605-081356-utc.log](https://github.com/Microsoft/vsts-agent/files/2076471/Agent_20180605-081356-utc.log)

Maybe it describes why the unregistering happens? If it helps, I can also provide logs from the system event viewer. It's definitely triggered from the reboot, we do nothing manually and the system logs also show the reboot.

**Comment by TingluoHuang** [comment]
@sibbl 
```
[2018-06-05 08:14:09Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\VSTSAgent\.credentials_rsaparams
[2018-06-05 08:14:10Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-06-05 08:14:11Z INFO MessageListener] Session created.
[2018-06-05 08:14:11Z INFO Terminal] WRITE LINE: 2018-06-05 08:14:11Z: Listening for Jobs
[2018-06-05 08:14:11Z INFO JobDispatcher] Set agent/worker IPC timeout to 30 seconds.
[2018-06-05 08:14:32Z INFO Terminal] WRITE LINE: Exiting...
[2018-06-05 08:14:32Z INFO ConfigurationStore] IsServiceConfigured()
[2018-06-05 08:14:32Z INFO ConfigurationStore] IsServiceConfigured: True
[2018-06-05 08:14:32Z INFO Agent] Received Ctrl-C signal, stop agent.listener and agent.worker.
[2018-06-05 08:14:32Z INFO HostContext] Agent will be shutdown for UserCancelled
[2018-06-05 08:14:33Z WARN VisualStudioServices] GET request to https://xxx.visualstudio.com/_apis/distributedtask/pools/9/messages?sessionId=72feec74-0417-489f-8ae7-0bc33f52214f has been cancelled.
[2018-06-05 08:14:33Z INFO MessageListener] Get next message has been cancelled.
[2018-06-05 08:14:33Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2018-06-05 08:14:33Z INFO AgentProcess] Agent execution been cancelled.
```
the agent process is up and running after the agent upgrade, but somehow something is trying to unconfigure the agent which remove the windows service, and stop the windows service will send Ctrl-C to the running agent process.

What's your Azure RM template looks like? will it unconfigure the agent?

**Comment by TingluoHuang** [comment]
auto update is required for new task or new feature added to the server, we don't have a feature to allow you disable auto update.

**Comment by bryanmacfarlane** [comment]
Right, the agent only updates if you use a feature or task that demands a new version of the agent.  for example, when we did gated checkin, it required service changes and agent changes.  When you used that new feature service side, it will add a demand on the agent version and it will get pulled forward.  To ensure the agent never gets pulled forward, you would have to ensure the service / features never move forward.  That's on prem TFS and an option if that's the most important factor.  If you want new features and cloud then it (collectively) moves forward every sprint.

**Comment by tejasd1990** [comment]
@sibbl Can you share the extension status folder 'C:\Packages\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.20.0.0\status', and the extension logs folder 'C:\WindowsAzure\Logs\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.20.0.0\'

**Comment by sibbl** [comment]
```
The Extension failed to execute: Error while downloading VSTS agent. Please make sure that you enter the correct VSTS account name and PAT token..
```

is logged there, see the detailed logs: 
[logs.zip](https://github.com/Microsoft/vsts-agent/files/2077537/logs.zip)

It seems like the RM extension runs on every reboot and downloading the agent each time? Could this be avoided somehow? Is it possible to update the PAT (which we indeed revoked)?

**Comment by tejasd1990** [comment]
@sibbl  Hi, these logs do not indicate what caused the extension to unconfigure. Please share the complete logs under 'C:\WindowsAzure\Logs\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent' which includes older versions of the extension as well.

**Comment by sibbl** [comment]
Hi @tejasd1990, thanks a lot for the reply.

The uninstall commands are triggered by v0.19 as far as I can see in the logs. Please find them attached, also including the RMExtensionHandler*.log files: [logs.zip](https://github.com/Microsoft/vsts-agent/files/2079335/logs.zip)

**Comment by tejasd1990** [comment]
If the Azure agent on the VM(not to be confused the VSTS agent) finds out that a newer extension version is available than the one currently installed on the VM, it uninstalls the current extension version and installs the new version, with the same settings(PAT included). So, because of the revoked PAT, the extension update failed.

As a workaround, you can keep the PAT and not revoke it, so that in the future, new extension updates don't fail. 

Although, version 1.20 was released more than a month ago, and the agent update should have happened earlier. We will look into this.

**Comment by sibbl** [comment]
Thanks a lot for the insights and you guys looking into thi. It would be great if it would be possible to revoke PATs and the extension still updating properly.

Two questions regarding some workarounds:

1. Is it possible to change the PAT which the extension uses on the machine either manually or via a powershell script (or something else?)? We have quite a lot of machines which we set up this way and which will get into this problem sooner or later.

2. Is it possible to uninstall/disable the extension (while keeping the VSTS agent installed) or is it necessary to keep it? As far as I understand it should be enough to set up the agent via the extension once and the agent will also auto update itself, right?

3. Is there recommended/better way to use Azure RM scripts to set up a resource group incl VMs and install the VSTS agent via a VSTS release definition? We'd like to avoid the same problem in the future once the tokens expire/are revoked again.

**Comment by mmajcica** [comment]
Judging by the code if there is an env variable named `agent.disableupdate` the auto-update will not be triggered. Can anyone confirm that?

**Comment by tejasd1990** [comment]
@sibbl 

1. For the extension, PAT is a protected setting, and comes in an encrypted form(encrypted by Azure), which is then decrypted by the extension. So, PAT won't be able to be changed. (PAT is not stored on the VM, the extension takes care of that.)

2. The extension is a wrapper for the VSTS agent, so the extension takes care of configuring the agent as a service and unconfiguring it. You can manually set up agent without the extension. The [vsts agent documentation[https://github.com/Microsoft/vsts-agent/]] explains that.

3. Revoking PAT is not the normal workflow because of the reason that happened in your case. One way is that you can create a PAT and store it in a [Team Foundation Service Endpoint[https://docs.microsoft.com/en-us/vsts/pipelines/library/service-endpoints?view=vsts#sep-tfsts]], where it will be secure(you won't be able to retrieve the PAT from the endpoint). Then, you can use the service endpoint in the [Azure Resource Group Deployment[https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureResourceGroupDeploymentV2#advanced-deployment-options-for-virtual-machines]] task with "Enable Prerequisites" dropdown option selected as "Configure with Deployment Group agent". This also executes the same functionality and no need to install the extension through template.

**Comment by TingluoHuang** [comment]
@mmajcica don't use `agent.disableupdate`, that is a legacy variable coming from legacy 1.x agent, we are not support it moving forward.

**Comment by bryanmacfarlane** [comment]
Correct, that was from when we actually did auto update on restart.  we stopped doing that so setting it has no effect.  Per above, we update when the features / service demand it.

**Comment by mmajcica** [comment]
@bryanmacfarlane @TingluoHuang is there a way to prevent this behavior?

**Comment by bryanmacfarlane** [comment]
@mmajcica - please read the whole thread above.  we explained.

https://github.com/Microsoft/vsts-agent/issues/1611#issuecomment-395137363

We certainly could add a policy to never (we have discussed).  Curious though, what would you propose we do when the service (which always moves forward) uses a new feature / capability that the old agent is not capable of servicing the request?

**Comment by jeffrey-opdam** [comment]
Hi Bryan,

We are making changes to our TFS environment, through a CD pipeline (TFS as well). So to be predictable and test any changes, we cannot have that our production environment updates itself. 
Those change should go through DTAP as well.

**Comment by bryanmacfarlane** [comment]
@jeffrey-opdam - TFS environments don't update themselves automatically - the user updates TFS.   This discussion is about VSTS which does move forward every sprint.  That's the key difference between TFS and VSTS.

**Comment by TingluoHuang** [comment]
@mmajcica there is a button in UI to allow you update all agents within a pool to latest version.
Note: it will upgrade to the version your TFS server store, not the latest version from Github
![image](https://user-images.githubusercontent.com/1750815/41854551-7b535c14-785e-11e8-8cfd-9fdd9d5a79c1.png)

**Comment by mmajcica** [comment]
@TingluoHuang  I am well aware of that button, but as @jeffrey-opdam explained, due to need to control the changes, I am looking to mimic that from a script so that we can deploy newer versions of the agents in predictable manner.

**Comment by alexvy86** [comment]
> For the extension, PAT is a protected setting, and comes in an encrypted form(encrypted by Azure), which is then decrypted by the extension. So, PAT won't be able to be changed. (PAT is not stored on the VM, the extension takes care of that.)

@tejasd1990, so the extension is persisting the PAT somewhere and trying to reuse it during updates to the VSTS agent? If that's the case I'm curious why it is done that way, when my current understanding is that the PAT is only needed the first time you configure an agent. Agent updates after that don't need it. I'm not entirely sure what steps are followed when a VSTS Agent update is triggered manually from the VSTS portal, but right now I would guess that it doesn't need to generate a new PAT...? (cc @bryanmacfarlane, to make sure I understood that right).

Also to complement this discussion, in [this issue](https://github.com/Microsoft/vsts-agent/issues/1614) I showed the logs from the Linux VM agent running in 2 of my servers, which seemed to indicate that no PAT was passed in to the script being run after updating the VSTS agent (see `Arg 'token': ''` below). Now, it is true that I revoked that PAT a while back, but if the extension persisted it, I would have expected to see something passed in to the script, and then a failure saying that the PAT isn't valid, but in fact it seems like there was no PAT stored at all. Here's what I see in those logs (`/VSTSAgent###/_diag/Agent_<timestamp>.log`):
```
[2018-08-16 04:52:30Z INFO CommandSettings] Arg 'auth': 'PAT'
[2018-08-16 04:52:30Z INFO CommandSettings] Remove auth from Arg dictionary.
[2018-08-16 04:52:30Z INFO ConfigurationManager] Creating credential for auth: PAT
[2018-08-16 04:52:30Z INFO CredentialManager] GetCredentialProvider
[2018-08-16 04:52:30Z INFO CredentialManager] Creating type PAT
[2018-08-16 04:52:30Z INFO CredentialManager] Creating credential type: PAT
[2018-08-16 04:52:30Z INFO PersonalAccessToken] EnsureCredential
[2018-08-16 04:52:30Z INFO CommandSettings] Arg 'token': ''
[2018-08-16 04:52:30Z INFO CommandSettings] Flag 'unattended': 'True'
[2018-08-16 04:52:30Z INFO PromptManager] ReadValue
[2018-08-16 04:52:30Z INFO Terminal] WRITE LINE: Failed: Removing agent from the server
[2018-08-16 04:52:30Z ERR  Agent] System.Exception: Invalid configuration provided for token. Terminating unattended configuration.
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.PromptManager.ReadValue(String argName, String description, Boolean secret, String defaultValue, Func`2 validator, Boolean unattended)
   at Microsoft.VisualStudio.Services.Agent.Listener.CommandSettings.GetArgOrPrompt(String name, String description, String defaultValue, Func`2 validator)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.PersonalAccessToken.EnsureCredential(IHostContext context, CommandSettings command, String serverUrl)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.GetCredentialProvider(CommandSettings command, String serverUrl)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<UnconfigureAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__5.MoveNext()
```

**Comment by tejasd1990** [comment]
Hi, apologies for replying late.
Commenting on some of the issues discussed here,

1.  We have made some fixes recent to the Azure Pipelines Agent(formerly TeamServicesAgent) extension. The agent installed through the extension should remain online after machine reboot, or an extension version update, even when the PAT has expired/revoked. If there are some issues related to this, please let me know.

2.  I think the 'update' in the title refers to the extension update, not the agent update. The Azure Pipelines Agent extension can be installed with disabled auto updation. This means that when new extension versions are released, the extension on your machine won't auto update. How to do it through ARM templates is described [here](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/features-windows#extension-updates). It can also be done when installing the extension through azure cli, or azure powershell.

We are about to close this issue, let us know if there are more issues/queries

**Comment by chshrikh** [comment]
closing as per @tejasd1990
