### ISSUE TITLE
Describe a way to use MSI and AAD access token for configuration

### ISSUE THREAD

**Issue by perbergland** [microsoft/azure-pipelines-agent#1612]
## Agent Version and Platform
v2.134.2 
Windows 2016 Datacenter (VS2017 packer-built image)

## VSTS Type and Version
VisualStudio.com 

## What's not working?
I want to use [Managed Service Identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/how-to-use-vm-token) of the VM where the agent runs to get an access token for the VM Service Principal and use it to register the agent with VSTS, but I can't seem to find any documentation on how to do that.
All documentation I've found describes how to get VSTS to create a Service Principal, not how to get an existing SP in AD access to VSTS resources.

**Comment by perbergland** [comment]
Looking at the source code, there is an [OAuthCredential](https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Listener/Configuration/OAuthCredential.cs) class but I don't know how get an Azure OAuth token to pass to it.

Is it as simple as passing some magic application id uri into the Azure AD token generator?
Should I first add the Azure Service Principal of the VM to an AD Group that has been added to a VSTS group/role such as "Project Build Administrators"

I'm thinking of something like this:
(Azure CLI 2)
`az account get-access-token --resource "https://visualstudio.com"`

or similarly from the [VM MSI](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/how-to-use-vm-token)

`$response = Invoke-WebRequest -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://visualstudio.com' -Method GET -Headers @{Metadata="true"} 
`

**Comment by TingluoHuang** [comment]
@perbergland Sorry, i am little bit confused. What are you trying to accomplish? are you not able to configure the agent?

**Comment by perbergland** [comment]
What I’m trying to accomplish is to take out the PAT from the process since it’s a brittle part and instead rely completely the AD. If the VM has an MSI and its principal is added to an AD group then it should be able to register itself with VSTS. The missing piece here is how to get a VSTS api token when you have the MSI VM oauth endpoint.

**Comment by TingluoHuang** [comment]
@chrisrpatterson for idea.

**Comment by TingluoHuang** [comment]
@perbergland i am working in allow you use AAD device code auth flow when configure agent, so you don't have to aquire PAT token, will that help your scenario?
https://github.com/Microsoft/azure-pipelines-agent/pull/1924

**Comment by perbergland** [comment]
Hmmmm not sure how that would work tbh. I was thinking of using the msi local endpoint on the vm and send in the resource url of ado (not sure what that would be) to get an access token that I could send to the vsts agent instead of a pat. Then if the msi ad identity of the vm is in an add group that has the required access right it would just work. Does this make sense?

**Comment by perbergland** [comment]
I specifically want to have a way to do this without any user interaction because the setup script will run through the vm PowerShell extension mechanism and deployed by terraform

**Comment by cwoolum** [comment]
I'm interested in this as well. My use case is specifically for Kubernetes. I'd like to deploy the agent on a pod that has managed identity enabled. Ideally, the agent would start, pick up an access token and use that. This would eliminate problems with PATs expiring.
