### ISSUE TITLE
Agent.Worker high cpu usage

### ISSUE THREAD

**Issue by ahoka** [Microsoft/azure-pipelines-agent#1613]
## Agent Version and Platform

vsts-agent-linux-x64-2.134.2

## VSTS Type and Version

On-premises TFS, Version 15.112.26307.0

## What's not working?

The Agent.Worker process is using a ridiculous amount of CPU:
```
 85813 buildus+  20   0 3221564  98176  50116 S  **96.0**  1.4  24:58.30 Agent.Worker
```
This is a whole core just for running the worker, and this affects our build machine's performance.

System wide profiling shows the following:
```
  Children      Self  Command          Shared Object                            Symbol
+   21.64%     0.00%  Agent.Worker     System.Private.CoreLib.dll               [.] 0xffff805fc9b48b3b
+   21.64%     0.03%  Agent.Worker     System.Globalization.Native.so           [.] GlobalizationNative_IndexOf
+   12.85%     1.45%  Agent.Worker     libicui18n.so.55.1                       [.] usearch_openFromCollator_55
+    8.45%     0.00%  Agent.Worker     libicui18n.so.55.1                       [.] usearch_next_55
+    8.43%     0.01%  Agent.Worker     libicui18n.so.55.1                       [.] usearch_handleNextCanonical_55
+    8.42%     0.73%  Agent.Worker     libicui18n.so.55.1                       [.] usearch_search_55
+    6.86%     1.27%  Agent.Worker     libicui18n.so.55.1                       [.] _ZN6icu_5513UCollationPCE13nextProcessedEPiS1_P10UErrorCode
+    6.52%     0.28%  Agent.Worker     libicui18n.so.55.1                       [.] _ZN6icu_5524CollationElementIterator15getMaxExpansionEPK10UHashtablei
+    6.24%     0.58%  Agent.Worker     libicuuc.so.55.1                         [.] uhash_igeti_55
+    5.62%     3.30%  Agent.Worker     libicui18n.so.55.1                       [.] _ZN6icu_5524CollationElementIterator4nextER10UErrorCode
+    1.68%     1.68%  Agent.Worker     libicui18n.so.55.1                       [.] _ZN6icu_5522UTF16CollationIterator14handleNextCE32ERiR10UErrorCode
```
It seems that it is doing some kind of text processing? My guess would be the console output, as our builds are very chatty (but not unreasonably, we need that info on failed tests).

## Agent and Worker's Diagnostic Logs

Logs are filled with the following lines:

[2018-06-08 08:42:15Z INFO JobServerQueue] Try to append 6 batches web console lines for record 'c481c53d-04ad-4e05-b5f8-f2c7ca648656', success rate: 6/6.
[2018-06-08 08:42:16Z INFO JobServerQueue] Try to append 6 batches web console lines for record 'c481c53d-04ad-4e05-b5f8-f2c7ca648656', success rate: 6/6.
[2018-06-08 08:42:17Z INFO JobServerQueue] Try to append 6 batches web console lines for record 'c481c53d-04ad-4e05-b5f8-f2c7ca648656', success rate: 6/6.
[2018-06-08 08:42:17Z INFO JobServerQueue] Try to append 6 batches web console lines for record 'c481c53d-04ad-4e05-b5f8-f2c7ca648656', success rate: 6/6.
[2018-06-08 08:42:18Z INFO JobServerQueue] Try to append 6 batches web console lines for record 'c481c53d-04ad-4e05-b5f8-f2c7ca648656', success rate: 6/6.
[2018-06-08 08:42:19Z INFO JobServerQueue] Try to append 6 batches web console lines for record 'c481c53d-04ad-4e05-b5f8-f2c7ca648656', success rate: 6/6.
[2018-06-08 08:42:20Z INFO JobServerQueue] Try to append 6 batches web console lines for record 'c481c53d-04ad-4e05-b5f8-f2c7ca648656', success rate: 6/6.

**Comment by TingluoHuang** [comment]
@ahoka looks like you have tons of output from your task.
6 batches = 6 * 100 lines, every line might contains at most 1024 chars.
is it possible for you to reduce console output, instead, output to a file, and upload the file on test failure?

**Comment by ahoka** [comment]
I don't see a simple way of doing this. Is there a way to optimize for larger amounts of output?

**Comment by TingluoHuang** [comment]
it's hard, we have to scan all lines of output to mask secrets.
What's you definition looks like? what task are you using that produce the outputs?

**Comment by ahoka** [comment]
It's a single monolithic Command Line task. Is there a way to disable the filtering?

**Comment by bryanmacfarlane** [comment]
You can write a script and invoke the cmdline and pipe output to a file and then attach the log to the build or upload as an artifact.  Of course that's not ideal because you see no output while watching.  there's other similar approaches where you invoke, capture output and just grab key lines like starting test, result etc...

We run some pretty huge build and tests at microsoft and we generally don't see cpu bottlenecks.  Curious as to what size machine this is (compute) and how many secrets are those.  Low cpu and a very large number of secrets would be the worst scenario.

**Comment by bryanmacfarlane** [comment]
lack of activity.  we can re-open with more info

**Comment by sunilsurana** [comment]
Hi.

I am facing the same issue. I did redirection >op.txt to my command but still no improvement in performance.

**Comment by mathiash98** [comment]
I have also experienced this for the second time in the span on 3 months. I don't have any huge dockerfile, my files is on average 25 lines long.
