### ISSUE TITLE
`config.sh remove` output incomplete

### ISSUE THREAD

**Issue by JacobHenner** [Microsoft/azure-pipelines-agent#1615]
When executing `config.sh remove`, the following output is emitted:

> Connecting to server ...
Succeeded: Removing agent from the server
Removing .credentials
Succeeded: Removing .credentials
Removing .agent
Succeeded: Removing .agent

This is misleading, as several other files are removed (if they exist), including .proxy, .proxybypass, etc.

**Comment by JacobHenner** [comment]
Extra files include
1. .proxycredentials
2. .proxybypass
3. .proxy
4. .certificates

**Comment by TingluoHuang** [comment]
@JacobHenner thanks, looks like the information is a little bit out of date.
`Removing .credentials` is actually removing credential related setting files which includes `.credential` and `.credential_params`
`Removing .agent` is actually removing agent config related setting files which includes `.proxy`, `.certificates` and `.agent`.

I think i will change the string to be:
Removing credential settings
Removing agent configuration settings

**Comment by deeptivanne** [comment]
Is there a way to do this unattended? i tried doing this command .\config.cmd remove -ArgumentList "--unattended","--Auth pat",$token i get error saying unrecognised CLI arguments.

**Comment by TingluoHuang** [comment]
@deeptivanne `.\config.cmd remove --unattended --auth pat --token myToken` should work.
