### ISSUE TITLE
./config.sh: line 29: 6458 Segmentation fault: 11 ./bin/Agent.Listener configure "$@"  MAC

### ISSUE THREAD

**Issue by qubuss** [Microsoft/azure-pipelines-agent#1617]
## Agent Version and Platform
Version of your agent? 2.122.1

OS of the machine running the agent? Mac OS High Sierra 10.13.5

## VSTS Type and Version
local TFS server

## What's not working?
Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N) > y

Connect:
Enter server URL > https://tfs.company.local
Enter authentication type (press enter for Negotiate) > PAT
Enter personal access token > ****************************************************
Connecting to server ...
./config.sh: line 29: 6458 Segmentation fault: 11 ./bin/Agent.Listener configure "$@"

**Comment by TingluoHuang** [comment]
@qubuss should be same issue as https://github.com/Microsoft/vsts-agent/issues/1007
can you try latest version agent? 2.122.1 might still built on top of dotnet core 1.0 which doesn't support macos 10.13

**Comment by qubuss** [comment]
@TingluoHuang Yeah I tried lates version and it did not help. #1007 info from this don't help too.

**Comment by TingluoHuang** [comment]
@qubuss can you share your agent log and system log?
agent log is under `_diag` folder of the agent root directory.
system log is under `~/Library/Log/`

**Comment by phraustbyte** [comment]
[Agent_20180620-183241-utc.log](https://github.com/Microsoft/vsts-agent/files/2120601/Agent_20180620-183241-utc.log)

I am having the same issue - log file is attached. I also have been through #1007 and it does not resolve. 
Not sure which system log you are looking for, but I can probably post that as well.

Thanks

**Comment by TingluoHuang** [comment]
@qubuss any luck or any updates?

**Comment by TingluoHuang** [comment]
also, please check how many version of openssl installed on your box, make sure you have 1 libssl and it's version is 1.0.x
I am going to close this issue now since we did hear back from you for a while.
