### ISSUE TITLE
Question: Use of \run.cmd localRun with YAML-Definitions

### ISSUE THREAD

**Issue by alexiffland** [Microsoft/azure-pipelines-agent#1618]
Because we are developing machine controls, which have very long development cycles, we need to decouple our builds from the rapidly evolving VSTS. 

For decoupling our builds from our buildservers we need the possibility to run them locally. We just found that you can run the agent locally with `\run.cmd localRun` and pass a yaml file with a builddefinition. 

In the docs this feature is inside an "outdated" folder with the remark that the feature is "in flux". What exactly does that mean and when can we expect the feature to get fully released?

Thanks, 
Alex

**Comment by TingluoHuang** [comment]
@bryanmacfarlane @chrisrpatterson  for answer.

**Comment by alexiffland** [comment]
@TingluoHuang @bryanmacfarlane @chrisrpatterson do you have any new information about this topic?

We also thought about a possibility to decouple the build-tasks from vsts/tfs e.g. with fetching them from nuget-packages? Do you think something like that will be possible in the future?

Thanks,
Alex

**Comment by alexiffland** [comment]
@TingluoHuang @bryanmacfarlane @chrisrpatterson Just another quick follow up on my question from June 11. Any news for us? Would be great to get an answer for this exciting topic...

Thanks,
Alex

**Comment by bryanmacfarlane** [comment]
Can you detail more on this?

> For decoupling our builds from our buildservers

**Comment by alexiffland** [comment]
Thanks for your reply. 
Yes we actually want to trigger builds locally without having to register an agent. 

In our company, we have software that we may have to rebuild in 10 years - for example machine controls software. So we want to use the vsts agent locally for executing the yaml files. 
For that, we also would need a possibility to store and fetch the buildsteps defined in the yaml in another place then our tfs/vsts otherwise we can't guarantee that we can rebuild changes on machines in 10 years. 
It would be great if we could run the agent locally with also specifying an alternative source for buildsteps (e.g. a NuGet-package feed)..

What do you mean with "buddy test"? And when can we expect the feature to get released?

Thanks very much!
Alex

**Comment by TingluoHuang** [comment]
We have created a new repository for all YAML related issues, please move the current issue to there.
https://github.com/Microsoft/azure-pipelines-yaml

**Comment by ericsciple** [comment]
@vtbassmatt to consider the scenario

**Comment by bryanmacfarlane** [comment]
closing since answered.  if anything left to answer, see the point above about moving to azure-pipelines-yaml
