### ISSUE TITLE
consider eliminating svc.sh sudo requirement

### ISSUE THREAD

**Issue by carct** [microsoft/azure-pipelines-agent#1625]
Hi,

I know that svc.sh can be run only by root, but the things is that I am able to use it only if 'sudo su' is being used before.
//this is a custom VSTS agent in Linux VM

I want to make an agent refresh via bash script and tried using the below command to stop the service:
"echo $admpass | sudo -S /my/path/VSTSagent/svc.sh stop"

also tried the command by hand from console and it is not working and neither is:
"sudo /my/path/VSTSagent/svc.sh stop"
Always getting "Failed: Must run from agent root or install is corrupt"

only if i use 'sudo su' prior to '/my/path/VSTSagent/svc.sh stop' it will work 

am i doing something wrong ? if not, can this be changed to handle this kind of execution as well ?

Thanks !

**Comment by carct** [comment]
ok, so after looking a bit around, i might have misunderstood the error.
looked into this:
https://github.com/Microsoft/vsts-agent/blob/master/src/Misc/layoutbin/systemd.svc.sh.template

the error seems to actually refer to the current path that my prompt is into, although i have stated the full path of the svc.sh script

i have now made the change but will check outcome tomorrow

**Comment by TingluoHuang** [comment]
@carct make sure the `pwd` is `/my/path/VSTSagent` when you run the script, or add a `cd /my/path/VSTSagent`

**Comment by carct** [comment]
riiight i thought that so (although i don't see the reason for this need) and my last few lines from my script are like this:
cd /my/path/VSTSagent
echo $admpass | sudo -S ./env.sh
echo $admpass | sudo -S ./svc.sh stop
echo $admpass | sudo -S ./svc.sh start
echo $admpass | sudo -S shutdown -r +1 &

i still don't see all the capabilities that i should, in the past once i manually made this refresh (env / stop / start) they appeared like a charm, so i guess this time they will as well

**Comment by carct** [comment]
still no success, tried a bunch of diff approaches that seem to execute just fine but no effect in the displayed capabilities in the agent pool\agent

**Comment by TingluoHuang** [comment]
@carct have you check the `.env` file?

**Comment by TingluoHuang** [comment]
https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-linux?view=vsts#service-update-environment-variables

**Comment by carct** [comment]
yea, i use those exact steps as sudo and with their pwd

**Comment by carct** [comment]
current status:
- Fresh VM Agent shows up in the correct pool but with missing capabilities
- Set a release definition to demand one of the wrong capabilities showing up on the FreshAgent
- two tasks ("Command Line" - now supporting bash) used to be sure that env.sh has time to execute, therefore one has working directory the correct path to env.sh and it only executes one command "./env.sh"
- second task looks likes this:
echo "#!/bin/bash" >> refresh.sh
echo "./svc.sh stop" >> refresh.sh
echo "sleep 10" >> refresh.sh
echo "./svc.sh start" >> refresh.sh
chmod +rx refresh.sh
./refresh.sh &

Of course that the release fails due to that stop, but it doesn't go on either (tried using '&' at the end of the calls but still no success

at first i had the ./env.sh execution the same way, in refresh.sh, and it was not working, when going to machine console and executing refresh.sh it worked perfectly and loaded new env-var + stop + start agent.

any ideas ? thanks!

**Comment by bryanmacfarlane** [comment]
Let's step back.  What are you trying to accomplish?  Recycle the agent running the job from inside a task?

**Comment by carct** [comment]
well yeah, because i was unable to do this from the initial provision+config of the VM agent
still unclear why it doesn't work... seems like no matter what i do, i still need to execute env.sh / svc.sh stop + start by hand

clearly i`m missing something....

**Comment by Craig1f** [comment]
I am having this problem today, trying to register a runner in userdata during startup.
