### ISSUE TITLE
Run a single job and exit/unregister

### ISSUE THREAD

**Issue by cmenzi** [Microsoft/azure-pipelines-agent#1630]
## Agent Version and Platform
Version of your agent? 2.134.2
Windows 2016 DataCenter w/ Containers

## VSTS Type and Version
https://buhlergroup.visualstudio.com

## What's not working?
We currently using Windows 2016 DataCenter w/ Containers and have another Agent (DinD) which build docker images of vsts with some additional tools on it.

After the new image is built we spin up a new docker image running Vsts.Listener. But this instance should only run a single job and die. 

It would be great if there is command-line switch `run-single` like https://docs.gitlab.com/runner/commands/#gitlab-runner-run-single. With this it's possible to that the docker container dies and get deleted after every single job. 

We then spin up a new container by a Task-Scheduler on Host OS which check, if there are constantly e.g 5 containers running. When one container, with the agent in it, is done and exited, the scheduled task spins up another one, with a virgin start. With this we test for example choco package installations in a clean environment. 

Or are there any other options to dynamically spin up "docker build agents" for one job? Like https://docs.gitlab.com/runner/executors/docker.html

We basically want to move from GitLab -> VSTS (Company Decision), so we have to adopt our ci/cd pipeline.

**Comment by TingluoHuang** [comment]
@bryanmacfarlane @chrisrpatterson

**Comment by ericsciple** [comment]
@TingluoHuang it sounds like the feature to specify the container image to use would solve this scenario. Do we have docs for that?

**Comment by cmenzi** [comment]
@TingluoHuang, @ericsciple any updates on this?

**Comment by ericsciple** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml

**Comment by ericsciple** [comment]
sorry for the delay. The link I posted sounds like it fits the scenario. Please reopen if not.
