### ISSUE TITLE
Failure when pre-execution handler + filePath input + tfvc

### ISSUE THREAD

**Issue by ericsciple** [microsoft/azure-pipelines-agent#1671]
Tasks with a pre-execution handler and ‘filePath’ inputs, fail on tfvc. When the job runs, the prejobexecution tries to resolve the filepath provided and fails. For example:

```
##[debug]tf vc resolvePath $\foo\abc.txt /loginType:OAuth /login:.,* /noprompt
##[error]The system cannot find the file specified
```

 This resolution should be skipped if the sources don't exist yet when the pre-execution handler runs.

**Comment by TingluoHuang** [comment]
#2130
