### ISSUE TITLE
Support building from tar.gz

### ISSUE THREAD

**Issue by ethomson** [microsoft/azure-pipelines-agent#1676]
## Agent Version and Platform
Agent version: 2.136.1, using the tar.gz package from https://github.com/Microsoft/vsts-agent/releases/tag/v2.136.1

Machine: Linux amd (Raspberry Pi 3+) running Raspbian.  Linux 4.14.52-v7+ armv7l

## What's not working?
Builds fail; they look for information (the version information?) in the git repository.  Since this source tree was expanded from a tarball instead of a git repository, this fails.

```
% ./dev.sh b
~/tmp/vsts-agent-2.136.1/src ~/tmp/vsts-agent-2.136.1/src
Prepend /home/ethomson/tmp/vsts-agent-2.136.1/src/../_dotnetsdk/2.1.300 to %PATH%


-----------------------------------------
Dotnet SDK Version
-----------------------------------------
2.1.300


-----------------------------------------
Pre-cache external resources for linux platform ...
-----------------------------------------
Download exists: TEE-CLC-14.134.0.zip
Download exists: vso-task-lib.tar.gz
Download exists: node-v6.10.3-linux-x64.tar.gz


-----------------------------------------
Building ...
-----------------------------------------
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  fatal: Not a git repository (or any of the parent directories): .git
/home/ethomson/tmp/vsts-agent-2.136.1/src/dir.proj(4,5): error MSB3073: The command "git rev-parse HEAD" exited with code 128.
Failed: build
~/tmp/vsts-agent-2.136.1/src
```

The obvious workaround is to clone the git repository and check out v2.136.1, but it's awkward that one can't simply build from the source release.

**Comment by TingluoHuang** [comment]
@ethomson does it normal people build from source release? the pattern we used is learned from dotnet core. we try to bake the commit sha into source code, so customer can see which commit their agent package built from.

**Comment by bryanmacfarlane** [comment]
yeah, we don't support building from the tar ball.  

https://github.com/Microsoft/vsts-agent/blob/master/docs/contribute.md

**Comment by bryanmacfarlane** [comment]
If the goal is to build 136 then clone the commit in this release tab:  https://github.com/Microsoft/vsts-agent/releases/tag/v2.136.1

**Comment by ethomson** [comment]
In @libgit2, we definitely have a lot of people who take a tarball instead of a git repository.

This may not be a typical use case for people who want to contribute to the vsts-agent, but starting with a release tarball is the obvious getting-started scenario for people who just want to create a build to use for themselves.  (Example: there's no binaries for their platform, like Linux ARM.)

**Comment by bryanmacfarlane** [comment]
we can update the script to set commit to none for this case.  we take PRs - want to give it a shot @ethomson ?

**Comment by ethomson** [comment]
@bryanmacfarlane If you find that #1703 is useful to the project, then I would be very interested in updating the script and will follow up with a PR.
