### ISSUE TITLE
Feedback on BYOS

### ISSUE THREAD

**Issue by wsmckenz** [microsoft/azure-pipelines-agent#1682]
#design 
#enhancement 

Really love the idea of [managed agent pools in your own subscription](https://github.com/Microsoft/vsts-agent/blob/master/docs/design/byos.md). You may already have these in your design, but a couple of things that would be good:

- Running the agents on a private VNET.
- Allow the customer to provide a set of azure tags that are applied to all of the agents. This allows us to use org codes and cost centers to map to our standard billing recovery processes.

**Comment by bryanmacfarlane** [comment]
@wsmckenz - thanks so much for the feedback.  We will ensure we consider this feedback in the design phase.

**Comment by damccorm** [comment]
Hey, thanks for the feedback - we're tracking this internally and it should be coming soon. I'm going to close here since the feedback has been propogated internally.

**Comment by MichaelDenwood** [comment]
HI @bryanmacfarlane,
Can you tell me if this has been released yet or where it is in your priorities?  Maybe point me to a roadmap item with it?  My organization is very much interested in this. 

Running the agents on a private VNET.

Thank you!
