### ISSUE TITLE
BYOS feedback

### ISSUE THREAD

**Issue by jabbera** [microsoft/azure-pipelines-agent#1691]
I subscribe to the throwaway model of build servers. I see this working one of two ways:

Point VSTS at a managed image and an arm template. When a build is queued a VM is spun up from the image used and tossed away (potentially after being unused for a time interval to reduce latency). This also allows multiple agents to be spun up and used if there is a large team working. Personally I'd build the image using packer so the script to create my build image is committed with my code.

My less preferred option would be to take a snapshot of the build agent when its "done" and that snapshot is rolled back to after a certain time internal.

**Comment by bryanmacfarlane** [comment]
It will probably be very similar to the way our hosted pool works.  That is - spinning up machines ahead of demand.  It creates a buffer of machines within configuration constraints.

We build our images with packer ( https://github.com/Microsoft/vsts-image-generation ) but that's orthogonal.  There will be a config option pointing to the image and how it's built is up to the consumer.  Building the image JIT is not an option - it takes hours for us to build and publish the images for hosted.

**Comment by jabbera** [comment]
Sounds amazing!

**Comment by damccorm** [comment]
Hey, thanks for the feedback - we're tracking this internally and it should be coming soon. I'm going to close here since the feedback has been propogated internally.
