### ISSUE TITLE
Using Azure Team Services Agent extension without specifying a deployment group 

### ISSUE THREAD

**Issue by riezebosch** [microsoft/azure-pipelines-agent#1714]
With the current (version) of the Team Services Agent Extension, it is required to specify the Team Project and the Resource Group. Therefore it is not possible to use this extension as a normal/generic build agent where just only the Agent Pool should be specified.

Is that something you deliberately don't support? Because as far as I found out it worked that way before. If I'm correct the extension itself isn't open source?

<img width="1792" alt="screen shot 2018-07-19 at 09 48 37" src="https://user-images.githubusercontent.com/1427334/42929086-54913cc0-8b39-11e8-8acb-9ccdf1d41f53.png">

**Comment by TingluoHuang** [comment]
@RoopeshNair Can you help answer this question?
BWT, is there a repository for this extension? so forks can log issue in there.

**Comment by RoopeshNair** [comment]
@riezebosch - Your inference is right, the extension configures only deployment group agent. It has been that way since the beginning. We never added support for build & release agent configuration via this agent.

**Comment by RoopeshNair** [comment]
@TingluoHuang - I don't think the extension code is public. @sachinma for confirmation

**Comment by sachinma** [comment]
You are right @RoopeshNair, it is not public as of now. We can discuss if we should make it public

**Comment by TingluoHuang** [comment]
@sachinma @RoopeshNair it would be great if there is a place users can leave feedback or report issues for the extension, so far most customer leave their feedback or issue in the agent repository which is not really the right place. :D

**Comment by riezebosch** [comment]
Plus we could make our own extension based on the work you already did. 🎉

**Comment by fume** [comment]
Hi, sorry for re-opening this old discussion but i had the same problem with a client today. The extension description is really misleading, saying that Build and Release Agent capabilities will be installed but that's FALSE. Please, change the extension description!!!

**Comment by andreymir** [comment]
What is a recommended way to provision a VM with Build Agent in Azure? Is it possible to create an ARM template that creates a VM with Build Agent installed and adds the Build Agent into the Agent Pool?

**Comment by RoopeshNair** [comment]
You can use custom script extension ([Windows](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows) | [Linux](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux)) of ARM template and configure the build agent in [unattended mode](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts#unattended-config)

**Comment by riezebosch** [comment]
> What is a recommended way to provision a VM with Build Agent in Azure? Is it possible to create an ARM template that creates a VM with Build Agent installed and adds the Build Agent into the Agent Pool?

Not recommended per se but you can get some inspiration from here: https://github.com/Azure/azure-quickstart-templates/tree/master/vsts-fullbuild-ubuntu-vm

It currently is outdated but you can inspect my PR here: https://github.com/Azure/azure-quickstart-templates/pull/5470

**Comment by chshrikh** [comment]
We are updating the description to make it clear that the extension is for Deployment Groups only
