### ISSUE TITLE
What would be a best practice for unregistering dynamic VSTS agents unattended?

### ISSUE THREAD

**Issue by alessandromuresan** [Microsoft/azure-pipelines-agent#1730]
We have a testing process for an MSI that needs to run on fresh environments, therefore we need to dynamically provision a lot of VSTS agents, and then delete them after the process has completed. We achieve the provisioning part in a phase that runs on a Hosted 2017 agent, by executing an ARM template.
 The actual cleanup process has two steps:
1. Remove the agent from the VSTS pool
2. Destroy the agent VM in Azure

Due to the fact that there are no API endpoints exposed for manipulating agents, we have implemented the removing via running a remote script on the Azure VMs that calls `config.cmd remove --unattended [...]`, which is quite time consuming.
I wonder if there would be a better way of implementing dynamic agent removal. Should we call `config.cmd remove` while executing the actual job **inside** the agent? Is there an API endpoint for doing this without being forced to actually be inside the agent?

Thank you in advance!

**Comment by bryanmacfarlane** [comment]
Can't unconfig while an agent is participating in a job.  it has to be outside in.

It sounds like you need this feature:  https://github.com/Microsoft/vsts-agent/blob/master/docs/design/byos.md

**Comment by carct** [comment]
we've been experimenting around the subject and actually you can do this, the only 'problem' is that the the agent remains in the Agent Pool, so for an unknown reason it does the remove only from the machine (deletes service).

the way to do this is by using:
Invoke-WmiMethod -Class Win32_Process to call up a powershell process that is not child of the job :)
if you call up a small script, with the new powershell process, that sleeps for a couple of seconds and then calls the config.cmd with 'remove' and other arguments the job finishes successfully in VSTS and the agent goes offline.

this would not be such an issue if the DevTestLab artifact for build agent would accept the '-replace' switch , hence replacing that offline agent with the new one

would you be so kind and either look into why it is not actually removed from the pool or to simply add the switch in the DTL Artifact options ?

Thanks,
Andrei

**Comment by giuliov** [comment]
You have REST API to manage the agents: I used a similar Powershell script in the past.

```Powershell
# Get agent pools (Request method: Get):
$uri = "${vstsUrl}/_apis/distributedtask/pools?api-version=${apiVersion}"
Write-Host ">>> calling $uri"
$allPoolsResult = Invoke-RestMethod -Uri $uri -Method Get @restCallSplat

foreach ($poolRec in $allPoolsResult.value) {

    Write-Host "Processing Agent Pool '$( $poolRec.name )'"

    # Get agents of an agent pool (Request method: Get):  
    $uri = "${vstsUrl}/_apis/distributedtask/pools/$( $poolRec.id )/agents?api-version=${apiVersion}"
    $thisPoolResult = Invoke-RestMethod -Uri $uri -Method Get @restCallSplat

    foreach ($agentRec in $thisPoolResult.value) {

        Write-Host "  Processing Agent '$( $agentRec.name )'"

        if ($agentRec.name -match $agentPoolPattern) {

            Write-Host "  Deleting Agent '$( $agentRec.name )'" -ForegroundColor Red

            #Delete an agent from an agent pool (Request method: Delete):
            $uri = "${vstsUrl}/_apis/distributedtask/pools/$( $poolRec.id )/agents/$( $agentRec.id )?api-version=${apiVersion}"
            Invoke-RestMethod -Uri $uri -Method Delete @restCallSplat

        }#if

    }#for agents
    
}#for pools 
```
