### ISSUE TITLE
Crash on updating Mac agent to 2.138.4

### ISSUE THREAD

**Issue by vitru** [Microsoft/azure-pipelines-agent#1742]
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
2.131.0 updating to 2.138.4

OS of the machine running the agent? OSX

## VSTS Type and Version
office.visualstudio.com

## What's not working?
2.138.4 agent crashes when doing first boot as part of auto-update, which leaves machines without a running agent. Manually restarting agent works fine.

## Agent and Worker's Diagnostic Logs
From the crash dump:
Date/Time:             2018-08-01 17:29:02.781 -0700
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

From the agent log:
[2018-08-02 00:29:02Z INFO ConfigurationManager] Settings Loaded
[2018-08-02 00:29:02Z INFO MessageListener] {
  "AcceptTeeEula": true,
  "AgentId": 2539,
  "AgentName": "oetest-macpro-03",
  "PoolId": 132,
  "ServerUrl": "https://office.visualstudio.com/",
  "WorkFolder": "_work"
}
[2018-08-02 00:29:02Z INFO Terminal] WRITE LINE: Scanning for tool capabilities.
[2018-08-02 00:29:02Z ERR  Terminal] WRITE ERROR: An error occurred: Input/output error

[Agent.Listener_2018-08-01-172908_oetest-macpro-03.zip](https://github.com/Microsoft/vsts-agent/files/2251595/Agent.Listener_2018-08-01-172908_oetest-macpro-03.zip)

**Comment by TingluoHuang** [comment]
@vitru looks like dotnet core problem to me, since the app crashed. I will log an issue for them.

**Comment by TingluoHuang** [comment]
@vitru can you share your systemlog from that machine? maybe under `/var/log/system.log`

**Comment by TingluoHuang** [comment]
the crash is caused by STDOUT/STDERR stream got close after agent updates.

**Comment by bryanmacfarlane** [comment]
we can reactivate if we get something actionable like the log asked for above.
