### ISSUE TITLE
Github Enterprise Repositories are not listed when i give Sources as Github Enterprise in my VSTS build definition.

### ISSUE THREAD

**Issue by Ashwin1983** [Microsoft/azure-pipelines-agent#1748]
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...
I am using the MS hosted agent

OS of the machine running the agent? OSX/Windows/Linux/...
Windows
## VSTS Type and Version
VisualStudio.com 

If On-Prem TFS, which release? 2015 RTM/QU1/QU2/...

If VisualStudio.com, what is your account name? https://ashwin1983.visualstudio.com

## What's not working?
Github Enterprise Repositories are not listed when i give Sources as Github Enterprise in my VSTS build definition. I have already configured the the connection but when i am creating the connection using Personal access Token it fails with below error message.
"Failed to query service connection API: https://github.schneider-electric.com/SESA248678/NextGenPdm.gitapi/v3. Error Message: The remote name could not be resolved: 'github.schneider-electric.com'. 
Note: Verification may fail if the URL is not accessible from Visual Studio Team Services. However, it might still be valid and accessible from the agent that executes Build/Release. "

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by TingluoHuang** [comment]
@madhurig for github enterprise integration question.
@Ashwin1983 i would suggest you post the question to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), since your question is not scope to the build/release agent.

**Comment by madhurig** [comment]
@Ashwin1983: As the error indicates, VSTS is unable to reach your GHE server
**_The remote name could not be resolved: 'github.schneider-electric.com'._**

To use GHE integration in VSTS, you will need to make the server accessible to VSTS. If you want to keep everything in your private network, we recommend installing the latest version of Team Foundation Server in your network that includes GHE support.

Thanks,
Madhuri
