### ISSUE TITLE
Multiple repositories in same project do not create two build definitions

### ISSUE THREAD

**Issue by RemiGri** [Microsoft/azure-pipelines-agent#1768]
## VSTS Type and Version
Using Visual Studio online

## What's not working?
I have a project in VSTS where I have two repositories (Lets call them repo A and B). Repo A has .vsts-ci.yml file from which a build definition is created for repo A. Once I created repo B and I pushed in .vsts-ci.yml file for that repo I expected a new build definition to be created for that repo, but no build definitions were created. 

So it seems that we can only have one build definition created from .vsts-ci.yml file per project rather than per repository, is this correct assumption? Will there be future updates so that a build definition is created per repository rather than project?

**Comment by TingluoHuang** [comment]
We have created a new repository for all YAML related issues, please move the current issue to there.
https://github.com/Microsoft/azure-pipelines-yaml

**Comment by ericsciple** [comment]
I would not expect this behavior. it should work for both.

**Comment by ericsciple** [comment]
Note, the workaround is to manually create the definition. The new-definition experience in the web allows you to pick the path to your yaml file.

**Comment by bryanmacfarlane** [comment]
closing since answered.  if anything left to answer, see the point above about moving to azure-pipelines-yaml
