### ISSUE TITLE
Cannot create build pipelines with different branches via YML file and UI does not show pipeline steps when using YML file configuration

### ISSUE THREAD

**Issue by ngeegoh** [Microsoft/azure-pipelines-agent#1773]
I cannot change the pipeline name when using yml file to configure the build pipeline in VSTS. 
The default name is always <REPO_NAME>/<REPO_NAME> CI which is not ideal if we want to have separate build pipeline for different branches of a repository. Currently, whenever I push up new changes in any branches, VSTS builds all branches under 1 build pipeline which is not very ideal because we could not keep track on the builds of every branch in that repo and we expect they built separately in separate pipelines.

Moreover, after VSTS creates a new build pipeline in VSTS from that yml file, the UI does not show up the actual build steps in the edit mode, it just shows that the pipeline is using the yml file and the pipeline somehow in dev branch instead of the branch that i push the new change. From the user perspective, it is expected to see VSTS convert the build steps from .vsts-ci.yml to the web-based build steps that users could edit directly on the UI.

**Expectations:**

- Ability to change the name of build pipeline like <REPO_NAME>-<BRANCH_NAME> (in yml file) in order to distinguish between different branches of the repository and we could better manage and monitor our builds in each branch of the repository.
- Ability to modify the pipeline steps on a web-based interface when using yml file to configure the pipeline in VSTS.

**Comment by TingluoHuang** [comment]
We have created a new repository for all YAML related issues, please move the current issue to there.
https://github.com/Microsoft/azure-pipelines-yaml

**Comment by ericsciple** [comment]
@ngeegoh for the first issue, it sounds like you want to set the build number format within the yaml file. Here is the doc for how to do that. https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=vsts&tabs=yaml#build-number-format

Regarding a visual designer to edit the yaml file, soon we are shipping a vs code extension soon to help edit the yaml file. Eventually we hope to build that into the web experience also.

**Comment by bryanmacfarlane** [comment]
closing since answered.  if anything left to answer, see the point above about moving to azure-pipelines-yaml
