### ISSUE TITLE
Custom conditions not working for agent phases but do work for tasks

### ISSUE THREAD

**Issue by Wojtek8881** [Microsoft/azure-pipelines-agent#1779]
I have created a simple condition but it does not work on the agent phase (it does work if set on the task level):
not(and(in(variables['BuildConfiguration'], 'ReleaseABC', 'ReleaseDEF'), eq(variable['BuildPlatform'], 'x86')))

The multiplier is set to BuildConfiguration and BuildPlatform on the agent. I did expected that the x86, ReleaseABC and x86 ReleaseDEF will be omitted but it is not the case.

**Comment by TingluoHuang** [comment]
@Wojtek8881 since this is more like a service question, you might want to report at https://developercommunity.visualstudio.com/spaces/21/index.html,
i will help you redirect if you can share some screenshot of your build definition shows how did you setup condition on phase.
