### ISSUE TITLE
Document the  .\config.cmd --unattended options

### ISSUE THREAD

**Issue by jawn** [Microsoft/azure-pipelines-agent#1793]
The agent install allows unattended installation and uninstallation.

I found info and examples [on stackoverflow](https://stackoverflow.com/a/46166325/65545).

I would expect this info to be clearly documented in the VSTS-Agent repo or on the docs site. Maybe I overlooked it?

**Comment by TingluoHuang** [comment]
@jawn you can get those info by running `./config.cmd --help` or `./run.cmd --help`

**Comment by jawn** [comment]
Thanks @TingluoHuang. 

My question is not how to use it, rather I am surprised the unattended installation option isn't clearly mentioned in any online documentation I found (apart from stackoverflow). The benefit would be that people know about it.

**Comment by TingluoHuang** [comment]
the closest thing i can find is https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-windows?view=vsts#help-on-other-options i am pretty sure that is not what we want, i will work with our Doc author on this.

**Comment by vtbassmatt** [comment]
I'll take this one.

**Comment by vtbassmatt** [comment]
Fixed in a PR. Should deploy tomorrow.

**Comment by jawn** [comment]
@vtbassmatt Where can I see the update?
