### ISSUE TITLE
[YAML] Set Retention Policies

### ISSUE THREAD

**Issue by drewkg** [Microsoft/azure-pipelines-agent#1798]
Is it possible to set retention policies within YAML configurations?

If no, are there any plans to do so?

**Comment by ericsciple** [comment]
@vtbassmatt @chrisrpatterson fyi

@drewkg it is not possible today. Matt/Chris can correct me if I'm wrong, but I don't think this kind of policy information is something intend to live with the yaml process file. Do you want different retention rules per branch?

**Comment by drewkg** [comment]
@ericsciple we already configure different policies per branch depending on if its a release / feature branch etc, I was just trying to get a handle on what would eventually be possible when configuration as code is made GA.  Thank you for your prompt answer.

**Comment by vtbassmatt** [comment]
We're still working through where policy information should live. I'm with @ericsciple -- putting it in the YAML file has potential downsides with respect to multiple branches, so we need to tread carefully here.

**Comment by drewkg** [comment]
The only advantage I can see would be if there was the ability to use a template for the policy from a separate repo, this way if the policy needs updating there would be one location and it would be simpler to ensure correct settings across multiple builds in multiple repositories.  However I can also see the downsides with respect to multiple branches, especially if a branch is removed and the information becomes effectivley invisible.

**Comment by TingluoHuang** [comment]
We have created a new repository for all YAML related issues, please move the current issue to there.
https://github.com/Microsoft/azure-pipelines-yaml

**Comment by bryanmacfarlane** [comment]
closing since answered.  if anything left to answer, see the point above about moving to azure-pipelines-yaml
