### ISSUE TITLE
Be able to select agent queue with matrix, similar way as container

### ISSUE THREAD

**Issue by VasiliyNovikov** [Microsoft/azure-pipelines-agent#1815]
Provide a way to select agent queues with matrix the same way as containers described here: [
YAML getting started - Containers - With a matrix strategy](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-containers.md#with-a-matrix-strategy)

Use case - I have .NET Core library that needs to be built and tested on all platforms - Windows, Linux & Mac. Right now I can solve it with [Phase templates](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-reusephase.md#yaml-getting-started---phase-reuse) but I think matrix would be more "natural" and less verbose way to do that

**Comment by TingluoHuang** [comment]
@VasiliyNovikov it's on our backlog, should be there pretty soon.

We have created a new repository for all YAML related issues, please move the current issue to there.
https://github.com/Microsoft/azure-pipelines-yaml

**Comment by VasiliyNovikov** [comment]
Moved to here: [#4](https://github.com/Microsoft/azure-pipelines-yaml/issues/4)
