### ISSUE TITLE
YAML - Powershell task error "Unexpected value 'arguments'"

### ISSUE THREAD

**Issue by fernisoites** [Microsoft/azure-pipelines-agent#1818]
Adopted from "View YAML":
![image](https://user-images.githubusercontent.com/10563480/45313738-8ca58100-b4e4-11e8-9ddf-08e38fce7f00.png)

"arguments" is not working when build using .yml

## Have you tried trouble shooting?
Yes

## Agent Version and Platform
2.140.0

OS of the machine running the agent? 
Windows

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://account.visualstudio.com
intentionaltest.visualstudio.com

## What's not working?
steps:
- powershell: ./ 'src/Print-Log.ps1'
  arguments: '-identity foobar'
  displayName: "Print Log"

Error:
build.yml (Line: 7, Col: 3): Unexpected value 'arguments'

**Comment by SachaLhopital** [comment]
I was facing the same issue this morning. @TingluoHuang solution did the trick for me !

**Comment by TingluoHuang** [comment]
We have created a new repository for all YAML related issues, please move the current issue to there.
https://github.com/Microsoft/azure-pipelines-yaml

**Comment by bryanmacfarlane** [comment]
closing since answered.  if anything left to answer, see the point above about moving to azure-pipelines-yaml
