### ISSUE TITLE
Using YAML builds seems to have blown away caching

### ISSUE THREAD

**Issue by dalemyers** [Microsoft/azure-pipelines-agent#1819]
## Agent Version and Platform
2.140.0 on macOS

## VSTS Type and Version
http://office.visualstudio.com

## What's not working?
With the traditional build definitions, the repository cache on each agent was tied to the build definition. After switching to YAML builds, this caching no longer appears to be a thing. We are doing a full clone each time now which adds several minutes to our build process. It also uses significantly more disk space, which has required us to step up our cleanup scripts. 

## Agent and Worker's Diagnostic Logs
[Agent_20180906-205558-utc.log](https://github.com/Microsoft/vsts-agent/files/2370658/Agent_20180906-205558-utc.log)

**Comment by TingluoHuang** [comment]
@dalemyers can you share 2 a full build logs for the same definition that indicate doing full clone?

**Comment by dalemyers** [comment]
That's the weird thing. The logs don't show that. They show that it does a clean and then a fetch as you'd expect. The difference is that it takes around 3 minutes with YAML builds and around 5 seconds on non-YAML builds, so something is clearly different. 

Each time we run a build, it's now downloading a couple of gigabytes of data on each "Checkout" step. For non-YAML builds, it's only a few MB. 

Both run the same commands.

**Comment by TingluoHuang** [comment]
@dalemyers share some sample log with me, i can help you check around. :)
a yaml build definition that build on commit SHA1_A
a non-yaml build definition also build on commit SHA1_A

**Comment by dalemyers** [comment]
We worked on this offline. It turns out that the repo was set to shallow clone once upon a time. The `--unshallow` flag on git wasn't removing the `.git/shallow` file once it had completed the rehydration though, so it was going through this every time. Removing that file from each agent solved this.
