### ISSUE TITLE
Error while saving YAML build pipeline in visualstudio.com

### ISSUE THREAD

**Issue by StefH** [Microsoft/azure-pipelines-agent#1824]
## Agent Version and Platform
Version of your agent = I don't know, I'm using the DevOps cloud version.
OS of the machine running the agent = See above.

## VSTS Type and Version
VisualStudio.com, The account name is http://stef.visualstudio.com

## What's not working?
I've defined two build definitions. One is working, the other always fails.
Note that the second one is a clone from the first one, and the second one uses a different YML file.

## Agent and Worker's Diagnostic Logs
Error message when starting a build is

> An error occurred while loading the YAML build pipeline. Repository self references endpoint 2b99e55b-2992-4c1e-8aa0-46e5783600d4 which does not exist or is not authorized for use.

Screenshots:
**Pipeline**
![pipeline](https://user-images.githubusercontent.com/249938/45426223-e7350d80-b69b-11e8-8000-be4692b3afe6.png)

**Error**
![error](https://user-images.githubusercontent.com/249938/45426205-da181e80-b69b-11e8-8073-ad88d7b48ed8.png)

**Comment by TingluoHuang** [comment]
@StefH try steps here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts#troubleshooting-authorization-for-a-yaml-pipeline

**Comment by StefH** [comment]
@TingluoHuang This does indeed solve my problem. Thanks a lot!

**Comment by oceaneLonneux** [comment]
I personally still have this problem. 
I only have one branch, master, and 2 service connections : the github one and the docker one. 

When I do a pipeline and use Docker with the Featured template, it works. When I want to use a YAML, it returns
An error occurred while loading the YAML build pipeline. The service connection name 00000000-0000-0000-0000-000000000000 is ambiguous. 
and I just don't understand why? I make it use the Github service connection, which is working with the other pipelines but not with the YAML one.

Here is the code of my azure-pipelines.yaml
`resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: NAME


- task: Docker@1
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: NAME

    command: 'Push an image'
`

**Comment by TingluoHuang** [comment]
@oceaneLonneux `dockerRegistryEndpoint: NAME`, what's the name you give? is it docker registry endpoint you added?

**Comment by oceaneLonneux** [comment]
> @oceaneLonneux `dockerRegistryEndpoint: NAME`, what's the name you give? is it docker registry endpoint you added?

I just updated my comment! I am using the name of my github connection.
Sorry the layout looks a bit bad...

**Comment by TingluoHuang** [comment]
@oceaneLonneux you need to create an endpoint that talks to your docker registry.
![image](https://user-images.githubusercontent.com/1750815/50349403-b02b8f00-0509-11e9-960b-f3e57302d3f2.png)
and reference that as your docker endpoint.

**Comment by oceaneLonneux** [comment]
Hello guys, I found a way for my own problem!

SOLUTION : I called the connection oceaneLonneux (like my username) and it didn't find it. Renamed it github oceane, and it works.

You can NOT call it like the key or the build will fail!

**Comment by santusri** [comment]
@TingluoHuang Hi Ting, surprisingly, my pipelines are not working with some error.
An error occurred while fetching the pipeline. Could not find the service connection associated with this pipeline. I am unable to edit the pipeline, to check for connection issues

**Comment by santusri** [comment]
@TingluoHuang  Moreover i use to add build task during build pipeline, but why i am not able to see UI format to add tasks to my pipeline?, instead its redirecting to "azure-pipelines.yml". I have to give every thing as yaml specs. Please let me know how do i get the UI format to add tasks to build pipeline.

thanks
