### ISSUE TITLE
Agent Node.js version is outdated

### ISSUE THREAD

**Issue by ms007** [Microsoft/azure-pipelines-agent#1826]
The current agent download contains an outdated node.js version (6.10.3)

We built a VSTS build pipeline extension that requires ES6 features from Node.js. 

The required version would be 8 or higher.
Can you please update the used Node version?

Or would it be possible to use the version that is already installed in the system instead of the node version in the agent?

In this issue [here](https://github.com/Microsoft/azure-pipelines-agent/issues/1415) a similar problem was solved nicely.

**Comment by chrisrpatterson** [comment]
We currently do not support anything beyond node 6 in our task infrastructure through with the typescript compiler you can take advantage of async and await to make your task development easier.    It is something we have on the backlog but it will require us to create a new handler and tasks will need to opt-in to that.  Simply switching could potentially break things for existing extensions.

**Comment by bryanmacfarlane** [comment]
The node/npm version to run user code (npm run ...) uses the node/npm in the path installed on the system (that's what the npm task does or if you script or use cmdline task).  The node the agent carries is used to run tasks code only.  As Chris pointed out, we can't just update it as there's marketplace tasks that were coded and released with expectation of node 6 runtime.  We will add a new task handler and the agent will also carry a new version of node.  We will like do that when node 10 goes LTS next month.

**Comment by cadsit** [comment]
I was just bit by this as the docs do not mention that the agent only runs node 6 even if a more recent version of node is installed on the agent (cc https://github.com/MicrosoftDocs/vsts-docs/issues/4130).

Is there any update on whether or not this landed or if there is a timeline to rolling out the new handler?

**Comment by cadsit** [comment]
Ah, I see from http://blog.majcica.com/2018/12/04/node10-provider-available-for-agent-v2-144-0/ that it's already been deployed. Thanks!
