### ISSUE TITLE
Azure pipelines github app endpoint connection

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/azure-pipelines-agent#1828]
Hi everyone,

I'm having some troubling with the new Azure Pipelines app for GitHub while trying to get the Endpoint.

It returns a new type of parameters as you can see here https://github.com/marceloavf/github-tools-vsts/issues/29. I tried to check for some documentation but didn't find anything. IIs there somewhere to ask about this problem or get some information?

Here is a piece of the code that get it:

```js
const tl = require('vsts-task-lib/task')

const githubEndpoint = tl.getInput('githubEndpoint')
const githubEndpointObject = tl.getEndpointAuthorization(githubEndpoint)

if (githubEndpointObject.scheme === 'PersonalAccessToken') {
  githubEndpointToken = githubEndpointObject.parameters.accessToken
} else if (githubEndpointObject.scheme === 'OAuth') {
  githubEndpointToken = githubEndpointObject.parameters.AccessToken
} else if (githubEndpointObject.scheme === 'Token') {
  // Azure Pipeline
  githubEndpointToken = githubEndpointObject.parameters.Signature
}
```

Thank you!

**Comment by TingluoHuang** [comment]
@marceloavf sorry for this, seems like a bug that we even allow user to choose that endpoint for regular task. I have reported the problem internally and they will work it. thanks for reporting this to us.

**Comment by TingluoHuang** [comment]
@marceloavf i am going to close this issue here since your issue in task-lib already in our email thread internally and this repository is more for the build agent. :) 
https://github.com/Microsoft/vsts-task-lib/issues/400
