### ISSUE TITLE
Alpine: dependencies is missing for Dotnet Core

### ISSUE THREAD

**Issue by rjudin** [Microsoft/azure-pipelines-agent#1829]
# Azure pipelines agent (VSTS/TFS Agent) failed to start at dotnet:alpine images.

I tried different combination of alpine3.7+ image with dotnet2.1.4 or even 3.0
Each time run-time stuck because of dotnet dependencies issue:
>su -c /agent/config.sh vsts-user
```bash
ldd: cannot load ./bin/libcoreclr.so: No such file or directory
ldd: cannot load ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: cannot load ./bin/System.IO.Compression.Native.so: No such file or directory
ldd: cannot load ./bin/System.Net.Http.Native.so: No such file or directory
Libicu's dependencies is missing for Dotnet Core 2.0
Execute ./bin/installdependencies.sh to install any missing Dotnet Core 2.0 dependencies.
```

> /agent/bin/installdependencies.sh
```
--------OS Information--------
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.0
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
------------------------------

/agent/bin/installdependencies.sh: line 182: [: ==: unary operator expected
Can't detect current OS type base on /etc/os-release.
Can't install dotnet core dependencies.
You can manually install all required dependencies base on follwoing documentation
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
```

Dockerfile
```Dockerfile
#FROM microsoft/dotnet:2.1.4-runtime-alpine3.7
#FROM microsoft/dotnet:2.1.4-runtime-deps-alpine3.7
#FROM microsoft/dotnet:2.1.4-aspnetcore-runtime-alpine3.7

FROM microsoft/dotnet-nightly:3.0-runtime-alpine
MAINTAINER rjudin (lifeci)

#perisstent install
RUN  apk update; apk --update add \
     curl git \
     jq icu-libs libcurl \
     libunwind~=1.2 \
     netcat-openbsd~=1.130 \
     sudo~=1.8 bash~=4.4 \
     openssl
     #ca-certificates;

#temp install
RUN apk --update add --virtual build-dependencies

#temp install cleaning
RUN apk del build-dependencies; \
     rm -rf /var/cache/apk/*

#ARG VSTS_AGENT_VERSION='2.131.0'
ARG VSTS_AGENT_VERSION='2.140.0'
ARG VSTS_AGENT_URL="https://vstsagentpackage.azureedge.net/agent/${VSTS_AGENT_VERSION}/vsts-agent-linux-x64-${VSTS_AGENT_VERSION}.tar.gz"

RUN echo "VSTS_AGENT_URL is $VSTS_AGENT_URL"

RUN set -x \
 && curl -fSL $VSTS_AGENT_URL -o agent.tgz \
 && mkdir agent \
 && cd agent \
 && tar -xz --no-same-owner -f ../agent.tgz \
 && cd .. \
 && rm agent.tgz

COPY ./start-vsts.sh .
RUN chmod +x start-vsts.sh

RUN adduser vsts-user; mkdir /vsts; chown -R vsts-user:root /vsts;
#USER vsts-user
RUN ls -la /vsts; whoami

CMD ["./start-vsts.sh"]

```

Related (closed) issues:
https://github.com/Microsoft/azure-pipelines-agent/issues/1319
https://github.com/dotnet/core/issues/226

**Comment by bryanmacfarlane** [comment]
Yes, we need to doc what's needed for alpine.

BTW, curious, I get alpine for your app image you're building.  But Alpine seems like an odd choice for building since it needs so many system and build tools.  You're also taking a tiny alpine for apps and add a couple hundred MB agent :) Can you clarify why you want to build in alpine?  Smallest feasible I've seen for building is debian-stretch.  

Also, for building you don't want the agent in your container.  We support agent running in the host and running your steps in a container:  https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/preview/yamlgettingstarted-containers.md

The agent auto updates itself and it can take down your container.

**Comment by chrisrpatterson** [comment]
At the moment the agent targets .NET Core 2.0 and Alpine is not on the list of supported operating systems https://github.com/puppetlabs/puppetserver/pull/1793#issuecomment-421442660.  This is something that could be tackled as we move to 2.1

**Comment by glazeus** [comment]
@bryanmacfarlane yes this is the reason why we considered alpine as base image - minimalism in package lists. I can't answer why VSTS has 'couple hundred MB agent' and hope it will be reduced by Microsoft.

Thank you for link 'agent running in the host and running your steps in a container'. We are NOT trying to implement docker host with each agent scenario. VSTS inside container for creating building pipeline as a code by ansible role/playbook

> The agent can update itself and it can take down your container.

How do you predict such behavior at https://github.com/Microsoft/vsts-agent-docker ?

---
@chrisrpatterson Thank you for clarification that agent targets to .NET Core 2.0 only. That explains why I was not able to run it with 2.1 deps. Can we expect backward compatibility between versions?

Cheers
_
RJ

**Comment by bryanmacfarlane** [comment]
@glazeus - vsts-agent-docker pulls latest agent JIT (downloaded) at container startup instead of being baked into the image.  that reduces the risk but doesn't eliminate it.  the vsts-agent-docker will need to handle that but doesn't currently - our plan is to change it to call a script which handles update return codes.  more later

Most of the agent size is externals tools and net core.  It has to carry it's own net core runtime since it can update itself.

**Comment by bryanmacfarlane** [comment]
And yes, you can expect back compat.

**Comment by nschonni** [comment]
There is an official Alpine Node container https://github.com/nodejs/docker-node/blob/master/10/alpine/Dockerfile but you're right that they have to build Node for the container instead of using a packaged version

**Comment by bryanmacfarlane** [comment]
We have to package with the agent.  Let us know if you have an issue building with debian-stretch.

**Comment by bryanmacfarlane** [comment]
Also, if you could add details on the project you're building (source, dependencies, yaml), that would help.

**Comment by TingluoHuang** [comment]
@nschonni your build failed before we are trying to map the `node` executable that the agent carried into the container and run it. However, the version of `node` that the agent carried is built on top of `glibc` which is not capable to run in `Alpine (musl-libc based)`. That weird error message is just the result of `node` can't find native dependencies it required.

**Comment by vtbassmatt** [comment]
@nschonni we now support bringing your own Node.js implementation, which should unblock running tasks with an Alpine container. (It does not, and will not, support _running an agent_ in an Alpine container.) See [this doc](https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/design/non-glibc-containers.md) for the details.

**Comment by gabrielfsousa** [comment]
why binary wont run on alpine ?

```
/vsts/agent/bin # ./Agent.Listener
sh: ./Agent.Listener: not found
```

**Comment by vtbassmatt** [comment]
We don't ship a musl-compatible agent implementation, just glibc.

**Comment by mo-saeed** [comment]
Hi @vtbassmatt I am getting this error while I am using the steps here https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/docker?view=azure-devops
with Alpine

```
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by ./bin/libcoreclr.so)
Error relocating ./bin/libcoreclr.so: __finite: symbol not found
Error relocating ./bin/libcoreclr.so: __isnan: symbol not found
Error relocating ./bin/libcoreclr.so: __finitef: symbol not found
Error relocating ./bin/libcoreclr.so: __isnanf: symbol not found
Error relocating ./bin/libcoreclr.so: pthread_attr_setaffinity_np: symbol not found
Error relocating ./bin/System.Net.Http.Native.so: __strdup: symbol not found
libicu's dependencies missing for .NET Core 3.1
Execute ./bin/installdependencies.sh to install any missing dependencies.
```
Any workaround to fix this ?

**Comment by vtbassmatt** [comment]
I'm no longer working on Azure Pipelines. You can try opening a support ticket via https://azure.microsoft.com/support/devops/

**Comment by iuooip** [comment]
> why binary wont run on alpine ?
> 
> ```
> /vsts/agent/bin # ./Agent.Listener
> sh: ./Agent.Listener: not found
> ```

There is probably `#!/bin/bash` and Alpine doesn't have that by default.
