### ISSUE TITLE
support for various triggers on jobs?

### ISSUE THREAD

**Issue by chvalean** [Microsoft/azure-pipelines-agent#1834]
## VSTS Type and Version
VisualStudio.com

## Question
Is there a roadmap to support multiple trigger types for jobs?
Currently what I'm seeing is that jobs are triggered only by code changes in the github repo.
Looking for something similar as in other CI's:
1. build on demand
2. build on schedule
3. build with input/manual parameters

Thank you!

**Comment by chrisrpatterson** [comment]
We support all of those trigger types

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=designer
