### ISSUE TITLE
No possibility to trigger only on protected branches

### ISSUE THREAD

**Issue by dza89** [Microsoft/azure-pipelines-agent#1836]
## Have you tried trouble shooting?
Yes, haven't found a solution.

## Agent Version and Platform
Latest.

OS of the machine running the agent? OSX/Windows/Linux/...
Windows & Linux

## VSTS Type and Version
http://sos-team.visualstudio.com

## What's not working?
I can't seem to trigger an agent on specific/protected branches only. 
Gitlab has a function built-in where you are able to have a agent trigger on a specific/protected branch only.  ![image](https://user-images.githubusercontent.com/20373984/45750554-c165b680-bc0f-11e8-95b3-8dd12690bdc1.png)

From a security perspective this is vital to be protected from malicious created artifacts. Am I missing an option somewhere or this doesn't exist?

They closed my issue in the dev community: https://developercommunity.visualstudio.com/idea/333707/unable-to-trigger-agent-on-one-specific-branch.html

**Comment by bryanmacfarlane** [comment]
I don't believe this is an agent issue.  I'm forwarding this to the team that owns this area on the service

**Comment by madhurig** [comment]
We don't have support for GitLab features in Azure Pipelines currently. We have the ability to enable CI for Git repos using just URL which is the only option we support for GitLab.

Thanks,
Madhuri

**Comment by madhurig** [comment]
@dza89: I think I misunderstood. There isn't a feature in Azure Pipelines to restrict running on some agents. We will triage the developer community ticket that you created. Thanks!

**Comment by dza89** [comment]
@madhurig 
I do not have permission to access the ticket. Is it an internal ticket or something?
https://developercommunity.visualstudio.com/idea/333707/unable-to-trigger-agent-on-one-specific-branch.html

**Comment by madhurig** [comment]
@dza89 : I noticed that the link is not accessible publicly now, I a following up on that but it is open and I can see it when I log in.

**Comment by madhurig** [comment]
@dza89 : You should be able to access the link now: https://developercommunity.visualstudio.com/content/problem/349325/unable-to-trigger-agent-on-one-specific-branch.html

Thanks,
Madhuri
