### ISSUE TITLE
Release trigger: "Outdated target/agent is online"

### ISSUE THREAD

**Issue by torangel** [Microsoft/azure-pipelines-agent#1838]
When releasing to a deployment group with one or more offline targets the deployment fails. There is no mechanism to redeploy to only the offline agents when they come online again. This should be possible to automate the same way as https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/jul-10-vsts#automatically-deploy-to-new-targets-in-a-deployment-group

For more details see this post:
https://stackoverflow.com/questions/52387916

**Comment by bryanmacfarlane** [comment]
This doesn't seem to be an agent issue.  If the agent is offline it can't absorb this issue.  It would need service work.  Please log an issue at developer community
