### ISSUE TITLE
Create a global daemon instead of a user agent on macOS

### ISSUE THREAD

**Issue by JacobHenner** [Microsoft/azure-pipelines-agent#1843]
Are there any plans to let the user create a global daemon for the VSTS service, instead of a user agent (using svc.sh)? This would allow VSTS to run without requiring the user to login to the GUI.

Of course, this would limit some of the processes which require the GUI to be available, but it could be useful for others.

**Comment by bryanmacfarlane** [comment]
No plans.  The mainline scenarios we created this for (iOS apps, emulator, UI tests, etc...) all required the GUI and user login context.

That said, there's nothing stopping anyone from creating a machine scoped daemon.  The one our shell script creates is a convenience.  If you want a machine scoped one, go ahead and create it.  It's a matter of creating a single file.

**Comment by JacobHenner** [comment]
Sounds good, I'll work to add that to the Puppet module (https://github.com/JacobHenner/puppet-vsts_agent/issues/7). I inquired, as I try to have the Puppet module conform to the agent's standards, and wanted to make sure nothing was being duplicated or implemented in a non-standard way. Thank you for the quick response.
