### ISSUE TITLE
https://aka.ms/yamlauthz currently 404s

### ISSUE THREAD

**Issue by eerhardt** [Microsoft/azure-pipelines-agent#1848]
Navigate to https://aka.ms/yamlauthz

it will redirect you to https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/preview/yamlgettingstarted-authz.md which gives me:

![image](https://user-images.githubusercontent.com/8291187/46045960-f2992780-c0e4-11e8-9a5c-cffdaca56ea5.png)

**Comment by TingluoHuang** [comment]
@bryanmacfarlane i think you own that link. :D

**Comment by buzzfrog** [comment]
I can still verify that it is still a 404.

**Comment by TingluoHuang** [comment]
thanks for reporting, we will update the aka link to the right one.
here is the doc it suppose to point to: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts#troubleshooting-authorization-for-a-yaml-pipeline

**Comment by TingluoHuang** [comment]
the problem should be fixed. i am going to close this issue.
