### ISSUE TITLE
SSH keyboard interactive auth

### ISSUE THREAD

**Issue by RichAlpert** [Microsoft/azure-pipelines-agent#1851]
I've installed TFS 2018 Update 3 + build agent version 2.141.

There i created a build defenition with build step that tries to execute remote SSH command. During step execution i get the following error: "All configured authentication methods failed."

Reason was that the server uses only keyboard interactive auth. But default build step settings don't have any switch for that case.

I found a solution by editing build step source files. In ssh2helpers.js i changed function setupSshClientConnection like this:

`function setupSshClientConnection(sshConfig) {
    var defer = Q.defer();
    var client = new Ssh2Client();
    client.on('ready', () => {
        defer.resolve(client);
    }).on('keyboard-interactive', function (name, instructions, instructionsLang, prompts, finish) {
	console.log('Connection :: keyboard-interactive');
	finish([sshConfig.password]);
    }).on('error', (err) => {
        defer.reject(err);
    }).connect(sshConfig);
    return defer.promise;
}`

and in file ssh.js on initializing sshConfig i added parameter:

`tryKeyboard: true`

After that all worked like a charm. I'm asking you to add this feature to default build step.

**Comment by TingluoHuang** [comment]
@RichAlpert you might want to report this problem at https://github.com/Microsoft/vsts-tasks
that is the repository for all in box tasks.

**Comment by TingluoHuang** [comment]
I am going to close this issue here, please open in the task repository.
