### ISSUE TITLE
How to controls the size of _work directory? 

### ISSUE THREAD

**Issue by melezhik** [Microsoft/azure-pipelines-agent#1871]
Hi agent devs!

How can I control/configure the size of agent `_work` directory? Eventually it grows to big size (~ dozens GB in few months ).  The reason I am asking it is that I am facing the issue when building a project, which I suspect has a caching nature, as I have no idea in how many places the cache exists inside `_work` directory, I end up removing the directory at all. But this is hard as I found that just after a few months (~4) of using agent the size of directory around 20-40 GB, this is complicated by the fact that I have 3 build agents , and I have to remove around ~60-120 GB data which takes awhile ...

**Comment by TingluoHuang** [comment]
@melezhik have you try http://www.codewrecks.com/blog/index.php/2017/05/06/maintenance-for-build-agent-in-tfs-build/ ?

**Comment by melezhik** [comment]
Hi @TingluoHuang ! Thanks for information. It helped.
