### ISSUE TITLE
How to optimize Docker image pull time?

### ISSUE THREAD

**Issue by cdietschrun** [Microsoft/azure-pipelines-agent#1874]
I'm iterating on our pipeline running with our container and one major time sink is the time required to pull the Docker container (which we can't really make too much smaller) to run the pipeline in the container. Is there anyway we can do better? Would self-hosted builds help by being able to control the machine's local Docker image cache and then agents spawned on that machine not need to download?

**Comment by escalonn** [comment]
Yes, self-hosted agent would help, for that reason.

**Comment by TingluoHuang** [comment]
@cdietschrun we are also working on cache popular container base image on the hosted pool, can you share the base image info with us? you can also just point me to the dockerfile if it's public.

**Comment by cdietschrun** [comment]
@TingluoHuang  I can't, our base is a custom base. Thanks though.

Sounds good, I will dig into the self hosting aspect. Any idea if we can self host in Azure?

**Comment by TingluoHuang** [comment]
@cdietschrun sure, the agent is just a xcopy zip/tar.gz, you can download and run it anywhere you want, like Azure VM.

**Comment by cdietschrun** [comment]
This has worked well for me so I'm closing the question. Thanks all!
