### ISSUE TITLE
Chocolatey package to install agent

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/azure-pipelines-agent#1875]
I've created a Chocolatey package to help automate installing the agent on Windows.

The initial release of the package is currently awaiting moderation, but you can preview it here - https://chocolatey.org/packages/azure-pipelines-agent
The source for the package is in https://github.com/flcdrg/au-packages/tree/master/azure-pipelines-agent

The first version was created by hand, but I'll create an update.ps1 script that automates package generation in the future.

I'm happy to keep maintaining the package, but if it's something Microsoft would like to take over then I'm happy with that too 😃

**Comment by bryanmacfarlane** [comment]
That's awesome.  We're happy for you to own it.  If you need something specific (shouldn't) let us know

**Comment by flcdrg** [comment]
Thanks @bryanmacfarlane !

For updating the package, is it reasonable to just rely on the Github releases feed, or is there some public URL (eg json data etc) that I can query to check what the latest available version is?

**Comment by TingluoHuang** [comment]
https://github.com/Microsoft/azure-pipelines-agent/releases/download/v2.141.0/assets.json might help you.
