### ISSUE TITLE
Can not queue a build after yaml change

### ISSUE THREAD

**Issue by andrewsuiter** [Microsoft/azure-pipelines-agent#1876]
As of yesterday afternoon 10/8 we have noticed that we unable to queue a new build from our existing agents.  The only agents that we are able to run a pipeline on is Hosted 2017.  

![image](https://user-images.githubusercontent.com/38952151/46678635-f07da100-cb99-11e8-8697-5428f824d03a.png)

We were able to run this before. 

Please advice if there was a recent change.

**Comment by TingluoHuang** [comment]
@andrewsuiter what's your VSTS account name?

**Comment by andrewsuiter** [comment]
andrewsuiter@chevron.com

**Comment by TingluoHuang** [comment]
what's your {account}.visualstudio.com? i am going to delete your comment that contains your email address from here. :D

**Comment by andrewsuiter** [comment]
thanks my bad, yeah its chevron.visualstudio.com

**Comment by TingluoHuang** [comment]
there is a bug that causing the problem, engineer on our side is working on mitigation, i hope it can be fix soon.

**Comment by andrewsuiter** [comment]
ok great thanks
