### ISSUE TITLE
Run agent interactively with root permissions

### ISSUE THREAD

**Issue by StiviiK** [Microsoft/azure-pipelines-agent#1877]
Hi,

i'm wondering why can't you run the agent interactively with root permissions?
I'm trying to build a agent which runs in a docker container, everything works fine, except i can't start the agent with root permissions. So in my builds i can't install for example packages or global node modules.
What is the point of disallowing to run as root?
For the `config.sh` a flag has been added (https://github.com/Microsoft/azure-pipelines-agent/commit/1c0cfdb125ed87fec56ebdf833a4be38205dc751), wouldn't this also be possible for `run.sh`?

For reference this is my [Dockerfile](https://github.com/StiviiK/azure-multiarch-buildagent/blob/master/Dockerfile), maybe you have some suggestion to workaround this problem.

**Comment by TingluoHuang** [comment]
@StiviiK you can raise a PR if you want, to workaround, you can just call `bin/Agent.Listener run $*` from the root folder of you agent.

**Comment by StiviiK** [comment]
@TingluoHuang i've raised an PR. Thanks i didn't thought about this workaround, to easy i guess 😅

**Comment by TingluoHuang** [comment]
i am going to close this issue since the PR has been merged, thanks for your contribution!
