### ISSUE TITLE
Question: PAT for build user

### ISSUE THREAD

**Issue by johnkors** [Microsoft/azure-pipelines-agent#1879]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes

## Agent Version and Platform
Version of your agent?
latest

OS of the machine running the agent? Windows

## VSTS Type and Version
Azure DevOps

## What's not working?
PATs.

## Question:
When installed and using PATs, I want the PAT to be from a build user/service account instead of connected to my personal account. How do I achieve this?

Follow-up: Will creating a build user/service account affect the amount of users? If on free plan, I have 5 users available —  will a build user/service account then take 1 of the 5?

**Comment by TingluoHuang** [comment]
@johnkors see whether the following doc can help you a little bit.
https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/design/auth.md

**Comment by TingluoHuang** [comment]
@johnkors i am not sure why you want to create a build user/service account.

**Comment by johnkors** [comment]
So the PAT entered while configuring/installing the agent is only used at install time, not for communication between the agent & vsts when doing builds/deploys?

**Comment by bryanmacfarlane** [comment]
Also not the token created during config using your creds gives you permission to listen to the queue.  Per build (and time bombed to that build) another OAuth token is generated equating to the service account and that is used to communicate with the service.

**Comment by johnkors** [comment]
Ok, thanks for clarifying! This makes alot more sense :)

**Comment by cawoodm** [comment]
> Also not the token created during config using your creds gives you permission to listen to the queue. Per build (and time bombed to that build) another OAuth token is generated equating to the service account and that is used to communicate with the service.

I can't parse that - what is this "service account" of which you speak? Where is it visible in DevOps?
