### ISSUE TITLE
Agent install doesn't detect AndroidSDK capability when tools installed using VS installer

### ISSUE THREAD

**Issue by oliverhruby** [Microsoft/azure-pipelines-agent#1880]
Version of your agent? 2.140.2
OS of the machine running the agent? Windows
VSTS Type and Version: VisualStudio.com

The agent is using ANDROID_HOME and some registry paths to detect the AndroidSDK capability. Neither of these things is found on the machine when the Android tools (emulator, sdk) have been installed as the Visual Studio component (not using the Android Studio). The only place where the ANDROID_HOME variable is actually mentioned in the docs is on the Android Studio page, there's nothing about that in the Visual Studio docs.
I would suggest to update the detection system or maybe this issue should go to the Visual Studio team to adjust the installer.

**Comment by TingluoHuang** [comment]
@madhurig @yacaovsnc

**Comment by joshmgross** [comment]
Hey @oliverhruby, thanks for your feedback. Capability detection is a legacy feature and currently is disabled on all Hosted agents. If you are using a private agent and are being blocked by a task that demands a certain AndroidSDK capability, you will have to edit the task to disable that check. You may also be able to set the ANDROID_HOME environment variable to point to the path where VS Installer places your Android SDK.

**Comment by TingluoHuang** [comment]
@joshmgross do we need to update the detection script for AndroidSDK?

**Comment by madhurig** [comment]
@TingluoHuang - It will be hard to fix this since VS update might keep changing it. And capabilities are only used for self hosted agents. The only task that relies on "AndroidSDK" capability is "AndroidSigning", I will update that task to remove the demand and not attempt making a fix on the agent for detecting AndroidSDK that is installed by Visual Studio. 

Thanks,
Madhuri

**Comment by TingluoHuang** [comment]
@madhurig understand, please link the task PR that remove the capability, and i will close the issue on the agent repo.

**Comment by madhurig** [comment]
https://github.com/Microsoft/azure-pipelines-tasks/pull/8912

**Comment by TingluoHuang** [comment]
@madhurig thanks.
close this issue, since the task will remove the problematic demand.
