### ISSUE TITLE
Git clone issue w/ submodules on self hosted Ubuntu VM agent

### ISSUE THREAD

**Issue by cdietschrun** [Microsoft/azure-pipelines-agent#1882]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...
2.140.2

OS of the machine running the agent? OSX/Windows/Linux/...
Ubuntu 16.04

## VSTS Type and Version
VisualStudio.com or On-Prem TFS?
VisualStudio.com

If VisualStudio.com, what is your account name? http://account.visualstudio.com
will relay internally instead of via github

## What's not working?
Please include error messages and screenshots.
2018-10-11T13:57:26.3330668Z fatal: could not read Username for 'https://<redacted>.visualstudio.com': terminal prompts disabled
2018-10-11T13:57:26.3331419Z fatal: clone of 'https://redacted.visualstudio.com/redacted/_git/redacted' into submodule path 'redacted' failed
2018-10-11T13:57:26.3703771Z ##[error]System.InvalidOperationException: Git submodule update failed with exit code: 128
   at Agent.Plugins.Repository.GitSourceProvider.<GetSourceAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.CheckoutTask.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.PluginHost.Program.Main(String[] args)
2018-10-11T13:57:26.4704396Z ##[section]Finishing: Get sources

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.
Have plenty of logs I'd be willing to share internally but not here.

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Azure-Pipelines-Yaml](https://github.com/Microsoft/azure-pipelines-yaml) - contains YAML templates and samples for Azure Pipelines. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.
- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by cdietschrun** [comment]
I put <redacted> in the logs where it shows our organization and projects and GitHub seems to have stripped that entirely.

**Comment by TingluoHuang** [comment]
@cdietschrun try this doc, see whether it help.
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/repository?view=vsts#checkout-submodules

**Comment by TingluoHuang** [comment]
@cdietschrun the error means the we don't have credential to clone your submodules.

**Comment by cdietschrun** [comment]
Thanks for the fast reply! 

Just for my understanding, I haven't had any problems with our project layout's git cloning with submodules on the Hosted agents. Also, in our .gitmodules file, the locations of the submodule repos are an absolute path. I don't fully follow how to make a relative path. Essentially we have

Organization
  mainProject
    repo
  submoduleProject
    submodule_repo1
    submodule_repo2
    submodule_repoN

How should my .gitmodule file look to make sure this works?

**Comment by TingluoHuang** [comment]
@cdietschrun can you share the full log of `checkout` step and you .gitsubmodule file with me?
you can send email to me if you have concern of leaking private information in github.

`tihuang @ microsoft .com`

**Comment by cdietschrun** [comment]
Version of git was too old. Problem fixed! Thanks Tingluo
