### ISSUE TITLE
Hosted Ubuntu agent capability

### ISSUE THREAD

**Issue by blade-feng-wang** [Microsoft/azure-pipelines-agent#1884]
are you sure the following variables paths are for Ubuntu??? It seems like Windows paths. And this persists for months.  
![image](https://user-images.githubusercontent.com/6714701/46815684-f77cfd00-cdad-11e8-98e6-2f7f92362441.png)

**Comment by TingluoHuang** [comment]
@dakale

**Comment by adventworks** [comment]
Ignore those capabilities. We are in the process of updating the UI for agent pools.

**Comment by blade-feng-wang** [comment]
> Ignore those capabilities. We are in the process of updating the UI for agent pools.

But I need to get some paths on this agent, where can I get them now

**Comment by TingluoHuang** [comment]
close this issue since we didn't hear back from customer.
please reopen if more help is needed.
