### ISSUE TITLE
VSTS agent: Testing agent connection PAT Authorization

### ISSUE THREAD

**Issue by bmpcon** [Microsoft/azure-pipelines-agent#1891]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
2.141.1

Windows Server 2016

## VSTS Type and Version
https://vf-commonit.visualstudio.com

## What's not working?
We are running local on-Prem VSTS agent to deploy artifacts that have been build within Azure DevOps (VSTS). When registering a new local on-Prem agent on Windows Server 2016 we are successful in registering the agent:
**[2018-10-16 12:37:17Z INFO Terminal] WRITE LINE: Successfully added the agent**
but when testing agent connection we get an authentication error:
[2018-10-16 12:37:17Z INFO Terminal] WRITE LINE: Testing agent connection.
**[2018-10-16 12:37:19Z WARN VisualStudioServices] Authentication failed with status code 401.**

But zhe agent connection test seems to use KerberorsAuth and tries to authenticate with the current Windows user that is running PowerShell instead of PAT token. This fails. However our local windows user is not allowed to access Azure and we want to use PAT authentication like when adding the agent (above).

## Agent and Worker's Diagnostic Logs
(see attachment)

Best regards
Björn
[github.txt](https://github.com/Microsoft/azure-pipelines-agent/files/2483151/github.txt)

**Comment by bmpcon** [comment]
Why does the agent want to authenticate with its Windows credentials and does not use the PAT provided like in the previous function when registering the agent itself?

**Comment by TingluoHuang** [comment]
@bmpcon the agent didn't use Windows credential, it's trying to exchange an oauth credential through a public endpoint, however the public endpoint `https://vf-commonit.vssps.visualstudio.com/_apis/oauth2/token` seems like got blocked by your firewall/proxy.

**Comment by bmpcon** [comment]
Within enterprise firewall we have a positive rule for "*.visualstudio.com". 
Also the proxy says within the logfile that the agent tries to access:
"
Auth Method: Kerberos
Auth Realm: EUR.CORP.mycompany.COM
Auth Username: currentwindowsuser
URL: https://vf-commonit.vssps.visualstudio.com/_apis/oauth2/token
"

**Comment by TingluoHuang** [comment]
@bmpcon you might want to try get http trace from the agent and see what auth header it is sending.
https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=vsts#http-trace-logs

the agent should not sending any auth header while exchange the oauth token.

**Comment by TingluoHuang** [comment]
close this issue for now, looks like a network problem, please reopen if need more help.
