### ISSUE TITLE
Multiple self hosted agents on same VM, Docker container name collissions

### ISSUE THREAD

**Issue by cdietschrun** [Microsoft/azure-pipelines-agent#1892]
Basically I have two agents on the same VM. My project has a YAML config using the container resource. On agent 1, this build seems to go through with no issues, but recently I've started seeing this error on agent 2. I don't seem to have any control over the name of the image that it passes to Docker in the YAML, and it uses the same for both, maybe causing this problem. Is there a setting on the job I can pass to use a different name? Or is there a different setting on the container alongside image and endpoint? Is it the options https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml#options ? It so, how do I make sure it never causes a collission?

## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...
2.140.2

OS of the machine running the agent? OSX/Windows/Linux/...
Ubuntu 16.04

## VSTS Type and Version
VisualStudio.com or On-Prem TFS?
VisualStudio.com

If VisualStudio.com, what is your account name? http://account.visualstudio.com
will share internally

## What's not working?
Please include error messages and screenshots.
2018-10-16T14:31:14.7551308Z ##[command]/usr/bin/docker create --name modeling_build_ci_cpscontainersazurecriomodelingbuild_cilatest --network=vsts_network_cdbe9bbe8bcf48c3828306b4df77f18b -v /var/run/docker.sock:/var/run/docker.sock -u 0   -v "/home/cpsdevops/myagent2/_work2/2":"/__w/2" -v "/home/cpsdevops/myagent2/_work2/_temp":"/__w/_temp" -v "/home/cpsdevops/myagent2/_work2/_tool":"/__t" -v "/home/cpsdevops/myagent2/_work2/_tasks":"/__w/_tasks" -v "/home/cpsdevops/myagent2/externals":"/__a/externals":ro -v "/home/cpsdevops/myagent2/_work2/.taskkey":"/__w/.taskkey" cpscontainers.azurecr.io/modeling/build_ci:latest "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
2018-10-16T14:31:14.9261903Z Error response from daemon: Conflict. The container name "/modeling_build_ci_cpscontainersazurecriomodelingbuild_cilatest" is already in use by container "45d9d39fa3cf38a1291e3ac5d143bbea7567a01bd53e0b49d3758c47b17159ff". You have to remove (or rename) that container to be able to reuse that name.
2018-10-16T14:31:15.0078257Z ##[command]/usr/bin/docker logout ***

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Azure-Pipelines-Yaml](https://github.com/Microsoft/azure-pipelines-yaml) - contains YAML templates and samples for Azure Pipelines. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.
- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by cdietschrun** [comment]
Ah, awesome @TingluoHuang , thanks!

**Comment by cdietschrun** [comment]
While I'm here, for my self hosted agent, I manually copied over an agent tarball and unzipped it and then registered it with Azure DevOps. When this new agent release happens what will I need to do to pick up these changes?

**Comment by TingluoHuang** [comment]
you can update them through the webUI 
![image](https://user-images.githubusercontent.com/1750815/47028691-dc0c4c00-d137-11e8-88b0-67ab956d4615.png)

**Comment by cdietschrun** [comment]
Ah, that's what that does. Thanks for the support!

**Comment by cdietschrun** [comment]
Weird, I just ran that, and it actually moved my agent version backward to 2.139.1. Is there some setting somewhere that I missed?

**Comment by TingluoHuang** [comment]
what's your agent version before update? 2.140.2 suppose to be the version across all service.

**Comment by cdietschrun** [comment]
Nevermind, total idiot move by me there. Nothing is wrong! It's still at 2.140.2. Is there anyway to be notified that a new agent has been released by you all?

**Comment by TingluoHuang** [comment]
https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.140.2
once the release in github has `latest release` means all service has it, `pre-release` means we are in the process of release it to all VSTS service.

**Comment by cdietschrun** [comment]
Thanks again, I subscribed to the .atom feed for https://github.com/Microsoft/azure-pipelines-agent/releases.atom to be notified of the releases. Closing this as it should be fixed in your next release.
