### ISSUE TITLE
The address of http resource where auto update process downloads new version of agent

### ISSUE THREAD

**Issue by melezhik** [Microsoft/azure-pipelines-agent#1893]
Hi! This is based on https://github.com/Microsoft/azure-pipelines-agent/issues/1696

We are facing auto update issues, suspecting the IP address is blocked in our firewall. This prevent agents from autoupdate, can you tell the  address of http resource where auto update process download s new version of agent. So we can adjust our firewall rules.

Thanks

**Comment by TingluoHuang** [comment]
@melezhik the agent is downloaded from CDN `https://vstsagentpackage.azureedge.net/agent/2.141.1/vsts-agent-win-x64-2.141.1.zip`, i am not sure i can provide IP address for you since it will be different across the world.

**Comment by melezhik** [comment]
Thanks!

**Comment by TingluoHuang** [comment]
@melezhik cool, are you good with closing this issue?

**Comment by melezhik** [comment]
Yeah. Thanks @TingluoHuang
