### ISSUE TITLE
expose $(Build.Repository.Name) in release pipeline tasks

### ISSUE THREAD

**Issue by tvald** [microsoft/azure-pipelines-agent#1898]
Various other build variables are exposed, but not `$(Build.Repository.Name)`. This is a useful variable for tagging a release or connecting it to appropriate resources.

Ideally, this would be exposed for every artifact via `$(Release.Artifacts.*.Repository.Name}`.

**Comment by TingluoHuang** [comment]
@GitHubSriramB

**Comment by omeshp** [comment]
We did change in march to start populating $(RELEASE.ARTIFACTS.*.REPOSITORY.NAME), due let us know if it isn't working for you.

**Comment by tjanko04** [comment]
Hello omeshp,

Using $(RELEASE.ARTIFACTS.*.REPOSITORY.NAME) as part of the build number format causes an error and cannot be saved.

**Comment by omeshp** [comment]
@tjanko04 These variables can be used in a release not build. Are you facing the issue with release name format?

**Comment by tjanko04** [comment]
@omeshp I haven't actually tried this with a release yet, I'm currently only working with builds in this phase of my implementation.  So the project name isn't exposed for doing a build in any way, is that correct?

**Comment by davejhahn** [comment]
This works, e.g. Release.Artifacts.{alias}.Repository.Name

A suggestion, add to the documentation.  This was added almost a year ago and is not in the documentation.  I only found it by running across this issue.

Current documentation:
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch
