### ISSUE TITLE
Build times out after 30 minutes regardless of settings

### ISSUE THREAD

**Issue by grecoe** [Microsoft/azure-pipelines-agent#1903]
## Have you tried trouble shooting?
Yes, timeout during execution occurs regardless of timeout values set.

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...

OS of the machine running the agent? OSX/Windows/Linux/...
Hosted Linux Preview

## VSTS Type and Version
VisualStudio.com or On-Prem TFS?
VisualStudio.com

If VisualStudio.com, what is your account name? http://account.visualstudio.com
Grecoe@microsoft.com

## What's not working?
Regardless of timeout values set, build cancels after 30 minutes with the following error:

Job Issues:

##[Error 1]
The job exceeded the maximum allowed time of 00:30:00 and was stopped. Please visit  for more information. 

Pipeline/Options/Timeout = 60
Phase/Timeout = 0
Python Script Task/Control Options/Timeout = 100

## Agent and Worker's Diagnostic Logs

[diagnostic_log_timeout.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2506130/diagnostic_log_timeout.zip)

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Azure-Pipelines-Yaml](https://github.com/Microsoft/azure-pipelines-yaml) - contains YAML templates and samples for Azure Pipelines. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.
- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by TingluoHuang** [comment]
https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-more-build-vs?view=vsts#microsoft-hosted-cicd

@grecoe base on the doc you can only run 30 mins build for free.

**Comment by TingluoHuang** [comment]
close as by design. let me know if you need more help.

**Comment by ravitej-senseon** [comment]
So, can I run builds for longer than 30 minutes on the hosted agents if I pay for an extra parallel pipeline?

**Comment by grecoe** [comment]
>           So, can I run builds for longer than 30 minutes on the hosted agents if I pay for an extra parallel pipeline?

Yes, that is correct. The free build tier will timeout earlier, but with paid pipelines you can run up to 6 hours, according to the documentation.
