### ISSUE TITLE
"Hosted Ubuntu 1604" and "Hosted Linux Preview" behaves different when executing command 

### ISSUE THREAD

**Issue by michaeljqzq** [Microsoft/azure-pipelines-agent#1910]
## Agent Version and Platform
Version of your agent? 2.140.2

OS of the machine running the agent? Linux

## VSTS Type and Version
If VisualStudio.com, what is your account name? http://zhqqitest.visualstudio.com

## What's not working?
I found the "Hosted Ubuntu 1604" and "Hosted Linux Preview" behaves different with executing command need elevated permission.
If I run `apt-get install xxx`, on "Hosted Linux Preview" it works, but on "Hosted Ubuntu 1604" it will show permission denied. Add `sudo` before command will make it work on "Hosted Ubuntu 1604"

**Comment by bryanmacfarlane** [comment]
That's expected.  Hosted Linux Preview is being deprecated.  It's an artifact of how it ran on the preview pool.  We ran it in a container to being the tools but that had many side effects especially around other container scenarios.  Ubuntu 1604 is a VM and offers a passwordless sudo which you found.

**Comment by michaeljqzq** [comment]
@bryanmacfarlane Thanks for clarification. Actually our team owned [this extension](https://marketplace.visualstudio.com/items?itemName=vsc-iot.iot-edge-build-deploy). Recently the retire of `Hosted Linux Preview` was affecting our customers. I would like to know is there a way to track break-changes of hosted agents or can I get some kind of notification for the change of hosted agents? Thank you
