### ISSUE TITLE
Add support for aarch64 release builds

### ISSUE THREAD

**Issue by toolboc** [microsoft/azure-pipelines-agent#1911]
My team recently encountered a situation where we needed to run the azure-pipelines-agent on an aarch64 (ARM 64bit) device.  

At this time, the official release builds only support:
* Windows x86/64
* macOS
* Linux x64/ARM32

We were able to install and run the Linux ARM32 release flavor by installing the armhf dependencies on an aarch64 device ([Jetson TX2](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems-dev-kits-modules/)), however, it would be nice to have first class support for this architecture due to it's prevalence in the IoT space ([Raspberry Pi 3B+](https://www.raspberrypi.org/blog/raspberry-pi-3-on-sale/), [PINE64](https://www.pine64.org/), [Nividia Jetson](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems-dev-kits-modules/) etc.).

```
#Install the ARM32 gcc toolchain
sudo apt-get install gcc-arm-linux-gnueabihf

#Symlink the armhf ld kernel module (this allows loading ARM32 bins on ARM64 OS and comes with the ARM32 toolchain)
sudo ln -s /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 /lib/ld-linux-armhf.so.3

#Add arm-linux-gnueabihf libs to LD_LIBRARY_PATH 
#(This tells ld where it can find libs in addition to the default /lib dir,
#Point it to the default path for armhf libs
export LD_LIBRARY_PATH="/usr/arm-linux-gnueabihf/lib/"

#OR For a persistent version of the above
#Symlink the relevant kernel modules
sudo ln -s /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 /lib/ld-linux-armhf.so.3
sudo ln -s /usr/arm-linux-gnueabihf/lib/libdl.so.2 /lib/libdl.so.2
sudo ln -s /usr/arm-linux-gnueabihf/lib/libpthread.so /lib/libpthread.so
sudo ln -s /usr/arm-linux-gnueabihf/lib/libpthread.so.0 /lib/libpthread.so.0
sudo ln -s /usr/arm-linux-gnueabihf/lib/libstdc++.so.6 /lib/libstdc++.so.6
sudo ln -s /usr/arm-linux-gnueabihf/lib/libm.so.6 /lib/libm.so.6
sudo ln -s /usr/arm-linux-gnueabihf/lib/libgcc_s.so.1 /lib/libgcc_s.so.1
sudo ln -s /usr/arm-linux-gnueabihf/lib/libc.so.6 /lib/libc.so.6
sudo ln -s /usr/arm-linux-gnueabihf/lib/librt.so.1 /lib/librt.so.1

#Enable installation of armhf packages
dpkg --add-architecture armhf

#Install armhf version of libcurl and libicu
apt-get install libcurl4-openssl-dev:armhf libicu55:armhf

#Install dotnet core (aarch 64 build prolly works here too)
wget https://download.visualstudio.microsoft.com/download/pr/10b96626-02d8-415a-be85-051a2a48d0c2/5ec51d3d9f092ba558fb5f1f03d26699/dotnet-sdk-2.1.403-linux-arm.tar.gz
mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-2.1.403-linux-arm.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

**Comment by TingluoHuang** [comment]
@toolboc we are waiting for dotnet core to add ARM64 support, it's part of dotnet core 3.0 which will release in 2019.
https://github.com/dotnet/announcements/issues/82

**Comment by toolboc** [comment]
@TingluoHuang , looks like current dotnet core (v2.1.5) already supports ARM64 => https://www.microsoft.com/net/download/dotnet-core/2.1

![image](https://user-images.githubusercontent.com/2018336/47891395-13aa1200-de21-11e8-8907-1356ee0a9d95.png)

Is there any interest in adding support sooner?

**Comment by TingluoHuang** [comment]
@toolboc i really wish. :)
https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#linux

From what i have been told, it's runnable but dotnet core team won't support it when you runs into issue.
The official support will be added as part of dotnet core 3.0.

**Comment by vtbassmatt** [comment]
ARM64 support in .NET Core: https://github.com/dotnet/announcements/issues/82

**Comment by nicolasg-playster** [comment]
Now that .NET Core 3.0 is officially released, can we expect an updated agent which supports ARM64 soon?

**Comment by BrianMouncer** [comment]
What is the status on this work?

I am looking into self hosting a Linux ARM32 and 64 build agent, as cross compiling in docker is adding several hours to our projects build time, and my hope is that compiling with native toolset could reduce our build time by an hour or so.

**Comment by nicolasg-playster** [comment]
I have the same issue. I have to run arm64 docker builds manually on my machine using the QEMU emulation layer which is painfully slow.

Having proper arm64 support for the Azure pipeline agent is critical for us. Hopefully this gets prioritized...

**Comment by BrianMouncer** [comment]
Also, when Linux ARM64 support is available, will we then see a "Microsoft Hosted Agent" for this platform, just like we have for Ubuntu X64?

**Comment by freyshen** [comment]
Also waiting for the ARM64 version agent on linux ARM64 platform.
Is there any release plan for it?

**Comment by vtbassmatt** [comment]
We haven't scheduled the work. I hope we can get to it this calendar year, though that's not a commitment.

@BrianMouncer no, we don't plan a hosted pool of ARM64 agents.

**Comment by vkrasnov** [comment]
I would love to see ARM64 support as well.
FWIW the changes to current version to make it run on ARM64 are very minimal:

https://github.com/vkrasnov/azure-pipelines-agent/tree/vlad/arm64_fix

**Comment by eXXL** [comment]
Support for ARM64 or guidance how to build and deploy agent on my own on raspberry 4 would be great.

**Comment by kaysan13** [comment]
Hello,

Here is a vsts version that supports arm64, I was able to create a build from a ubuntu 18.04.3 arm64 LTS.

> https://github.com/kaysan13/azure-pipelines-agent.git

To build the project, go to the src directory and then 

```
./dev build
./dev.sh package
```

then you download the azure agent, you replace the bin directory by your bin builder directory.

I hope I can help with this little fix,

Let me know if you have any problems

**Comment by liminany** [comment]
Has any roadmap for this ?

**Comment by vtbassmatt** [comment]
Sorry, nothing publicly tracking it. Same state as before: we need to move the agent to .NET Core 3.0 and then this becomes easy.

**Comment by BrianMouncer** [comment]
@vtbassmatt back in October.
> We haven't scheduled the work. I hope we can get to it this calendar year, though that's not a commitment.

It's December, is there any update on this work (will it still make this calendar year)?

I see there was an initial PR for the agent changes, but needed test cases and lab hardware to finish., Then another that re-did this work on the current state of master, but not definitive indication when the PR will be completed, or when the new agent should be available in production.

https://github.com/microsoft/azure-pipelines-agent/pull/2256

https://github.com/microsoft/azure-pipelines-agent/issues/1911

**Comment by isgallagher** [comment]
Any update to this?  Would be great to have a hosted agent running for e.g. multiarch/ubuntu-core:arm64-xenial to build arm64 packages.

**Comment by vtbassmatt** [comment]
There will not be hosted agents running ARM64, even once we ship an ARM64 agent. You'll be able to use self-hosted or elastic self-hosted pools, though.

**Comment by NGPixel** [comment]
@vtbassmatt Any ETA or status update when it will be available?

**Comment by vtbassmatt** [comment]
Unfortunately no. I've made soft promises before and had to break them, so I won't do that here. Hopefully soon!

**Comment by jkunkee** [comment]
Note that on ARM64 Windows desktop, the x86 client should run under emulation. I have not tried this, so of course YMMV, but it should be on par with the x86 client on x64.

Once the client is on .NET Core and .NET Core supports ARM64 Windows, then it should(TM) Just Work.

**Comment by Qinka** [comment]
It's 2020! Where is officially build of agent for aarch64?

I bought an ARM server from Huawei Cloud, and I want to run the agent on it.

**Comment by michalpenka** [comment]
This is a blocker for me too atm. I see the related pull request is getting stale. Any plans to move with this forward? Cheers.

**Comment by vtbassmatt** [comment]
I appreciate everyone continuing to chime in - hearing the demand definitely helps us prioritize this work! Things are happening, just slower than I would prefer.

**Comment by philipktlin** [comment]
+1; I have been waiting vsts agent to support ARM64 for more than a year.  Please prioritize it and it will be great to know what it will be available.

**Comment by vtbassmatt** [comment]
Update: I have ordered hardware to serve as our build farm, and we're also working on a new PR to add this support. Especially with the pandemic ongoing, I think we're still several weeks away from any new news, but things are happening!

**Comment by richlander** [comment]
@vtbassmatt  tell me if you need any help from my team. .NET Core should work A-OK on ARM64 at this point, but we're happy to help.

You don't need ARM64 machines to build the ARM64 version of your product, just to test it. Maybe you intend to do both of your new hardware.

**Comment by vtbassmatt** [comment]
Thanks! We can't release until we test. We're definitely trying to move to building on the fastest VM (Linux) for all flavors, but I don't want to block this work on that either.

**Comment by vielmetti** [comment]
If the team would like to get access to linux/arm64 server hardware, I run the @worksonarm program at Packet which enables CI for build infrastructure and/or bare metal Linux for test/development of arm64 systems for qualified projects at no charge. Reach out here or at https://github.com/worksonarm/cluster/issues to open a new issue to help get the process rolling.

Very much looking forward to helping out with this effort @vtbassmatt - I know you have gear on order so this need not be a long term commitment if not necessary.

Works on Arm is sponsored by Arm Holdings and is managed by me (@vielmetti) at Packet, an Equinix company.

**Comment by vielmetti** [comment]
Hoping your cluster made it to you by now @vtbassmatt ! Though I know that logistics everywhere are awkward.

**Comment by vtbassmatt** [comment]
Yes! I had two failed microSD cards from a lot of 5 (note to self, don't buy that brand again) but we have three ARM64 agents up and running now. [2.166.2](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.166.2) is the first build, and I'd say we're in "release candidate" quality. That is, we think we have all the bugs ironed out, but would love some community testing.

![image](https://user-images.githubusercontent.com/714283/79483437-51ccce80-7fe0-11ea-82d7-39aa45faa7fc.png)

**Comment by vtbassmatt** [comment]
@toolboc @nicolasg-playster @BrianMouncer @freyshen @vkrasnov @eXXL @liminany @NGPixel @Qinka @michalpenka @philipktlin - good news, there is an ARM64 agent now. Sorry for the looong delay.

**Comment by vtbassmatt** [comment]
(Leaving open until we're officially official with support)

**Comment by michalpenka** [comment]
This is excellent, thanks @vtbassmatt for an update. I'll give it a try later today and will report any bug should I find any.

Like your ARM build btw!

**Comment by vtbassmatt** [comment]
In case anyone is interested in the details, it's a [PicoCluster](https://www.picocluster.com) 5H with Raspberry Pi 4Bs running Ubuntu Server 18.04 64-bit. The bottom two, currently disconnected units will probably get 32-bit Raspbian or Ubuntu Server, as the Pi4 is about twice as fast as our current ARM32 build machines.

**Comment by michalpenka** [comment]
It's just such a shame PicoCluster is so expensive. But looks great and neat!

Anyways, well done @vtbassmatt for all the work on the agent.

**Comment by patschaefer** [comment]
Thanks @vtbassmatt for this. We have been running a hacked up version based on 2.159 for a few months, I upgraded my agents to the 2.166.2 last week and have seen no issues so far.

**Comment by amaslenn** [comment]
Link to `arm64` package is broken in [v2.166.3](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.166.3), both `arm` and `arm64` point to `arm` file.
This one https://vstsagentpackage.azureedge.net/agent/2.166.3/vsts-agent-linux-arm64-2.166.3.tar.gz doesn't exist.

**Comment by vtbassmatt** [comment]
Thanks @amaslenn. I'll file a separate issue to make sure we track that.

**Comment by michalpenka** [comment]
I've successfully deployed 2.166.2 (.3 link really not available) to my Kubernetes cluster and so far I have found no issues. Will keep you updated should I find any. Thanks again!

**Comment by kushalkoolwal** [comment]
Are there any remaining tasks to complete before we close this one out? Seems like Arm/Arm64 builds are now available with latest releases up to 2.168.2

**Comment by vtbassmatt** [comment]
Thanks for the reminder. Yes, this is official now.

**Comment by philipktlin** [comment]
Btw I think we need to update the New Agent download page in DevOps Website (click "New Agent" button on DevOps website) to include ARM64 with download link and steps.

**Comment by mthalman** [comment]
Just wanted to drop a note saying that we've begun using this for our CI builds of the official .NET Docker images: https://github.com/dotnet/docker-tools/pull/564.  We make use of NVIDIA Jetson machines that we've updated to install the ARM64 version of the agent.  Originally, we had AMD64-based Linux VMs that run the pipeline agent software and acted as a proxy, sending remote Docker commands to the Jetson machines.  Now we can completely get rid of those proxy machines.  Everything's working great at this point.

**Comment by BrianMouncer** [comment]
I’m assuming the “NVIDIA Jetson machines” are selfhosted agents?

Now that we have a functional ARM agent, are there any plans to have ARM agents in the MS hosted pools?

Thanks,

Brian.

**Comment by vtbassmatt** [comment]
No plans for a hosted pool of these.

**Comment by lewcianci** [comment]
Are there any plans for a Hosted pool of these? If not, can we use docker buildx to build arm64 images on an azure pipeline?

**Comment by dennisameling** [comment]
@lewcianci I'm working on adding `arm64` images for DDEV using docker buildx on a x64 host. They're using CircleCI but I assume you can use similar or the same steps in Azure Pipelines (include everything that's in the `Prepare docker buildx for multi-arch builds` step): https://github.com/drud/ddev/pull/2454/files#diff-1d37e48f9ceff6d8030570cd36286a61R267

Then you can e.g. run `docker buildx build --platform linux/amd64,linux/arm64 ......` further down in the pipeline as described here: https://github.com/docker/buildx#documentation

**Comment by vtbassmatt** [comment]
@lewcianci no plans for a hosted pool.

**Comment by lewcianci** [comment]
> @lewcianci no plans for a hosted pool.

I find that strange considering that Microsoft has invested quite heavily in IoT and yet we can't use the build agents to build ARM64 images natively and have to use QEMU to build instead. But it's perhaps not in high enough demand yet 😄 

Thanks for getting back to me

**Comment by rajeshaz09** [comment]
> > @lewcianci no plans for a hosted pool.
> 
> I find that strange considering that Microsoft has invested quite heavily in IoT and yet we can't use the build agents to build ARM64 images natively and have to use QEMU to build instead. But it's perhaps not in high enough demand yet 😄
> 
> Thanks for getting back to me

It's surprise to me as well.

**Comment by rajeshaz09** [comment]
> > @lewcianci no plans for a hosted pool.
> 
> I find that strange considering that Microsoft has invested quite heavily in IoT and yet we can't use the build agents to build ARM64 images natively and have to use QEMU to build instead. But it's perhaps not in high enough demand yet 😄
> 
> Thanks for getting back to me

It's surprise to me as well
