### ISSUE TITLE
Set agent's capabilities though configure script

### ISSUE THREAD

**Issue by melezhik** [Microsoft/azure-pipelines-agent#1912]
I'd like to set agent's capabilities through `configure.exe` script when register new agent. Is it possible?

Thanks

**Comment by TingluoHuang** [comment]
@melezhik the only way i can think would be (not ideal):
Create a `.env` file under agent root and put your capability there in format:
```
foo=bar
test=test1
```
the agent will add `foo` and `test` as environment variables and report those as system capabilities.

**Comment by melezhik** [comment]
Yeah, thanks @TingluoHuang  sounds like a workaround
