### ISSUE TITLE
Expose YAML validation features as standalone tool

### ISSUE THREAD

**Issue by tomasaschan** [Microsoft/azure-pipelines-agent#1914]
Looking at [this document](https://github.com/Microsoft/azure-pipelines-agent/blob/d504d4ef0e82d34439aa0eb494f218c2d9146a95/docs/preview/yamlgettingstarted-runlocal.md) (which I found [with some help](https://stackoverflow.com/a/53047000/38055)) it seems that this repository contains all the necessary functionality to validate YAML pipeline definitions locally, without actually sending any build commands to build servers.

I tried to use `run.sh --yaml <my-yaml-file> --what-if` as shown in that document, but that complained about not finding `bin/Agent.Listener` and I couldn't find any instructions on how to build that file correctly. However, based on the descriptions in the document, it seems to do exactly what I would need to avoid having to push code to the repository just to see if my build config is valid.

It would be awesome if that could be exposed as something I can run from within my repository (e.g. a dotnet global tool).

**Comment by TingluoHuang** [comment]
move to https://github.com/Microsoft/azure-pipelines-yaml/issues/34

**Comment by tomasaschan** [comment]
@TingluoHuang Not saying it was incorrect to move the issue, but do note that although it concerns YAML templates, it's not specifically about the templates but rather about the tooling around them, for which there seems to be very little in Microsoft/azure-pipelines-yaml.

**Comment by vtbassmatt** [comment]
On it.
