### ISSUE TITLE
AzCopy.exe packaged with the Agent doesn't use TLS 1.2 by default

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/azure-pipelines-agent#1928]
## Agent Version and Platform
Version of your agent? 2.142.0

OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com

## What's not working?
AzCopy.exe packaged with the Agent doesn't use TLS 1.2 by default. On any client machine where TLS 1.0 or 1.1 is blocked calls made by AzCopy.exe fails.

This is impacting the functioning of the JmeterLoadTest and CloudLoadTest task both of which use this to upload something to the Azure blob.

## Suggestion
Latest version of AzCopy.exe packaged for DotNetCore uses TLS 1.2 by default, can the version packaged with the Agent be changed to the latest?

**Comment by TingluoHuang** [comment]
@ShreyasRmsft the `AzCopy.exe` that packaged with the agent is for compat reason, it is for task that written for 1.x agent. We will leave it as it is until we deprecate the 1.x agent compat layer (legacy powershell handler). you should package all your dependencies with your task or find it in %PATH%

**Comment by ShreyasRmsft** [comment]
Fair, will probably go with packaging it with the task.
