### ISSUE TITLE
Multiple "Only single test suite found, parsing its information"

### ISSUE THREAD

**Issue by henri-tremblay** [Microsoft/azure-pipelines-agent#1966]
You can see an example of the problem [here](https://dev.azure.com/TerracottaCI/ehcache/_build/results?buildId=342&view=logs). Look at the Gradle build logs.

## What's not working?

We get hundreds of "Only single test suite found, parsing its information" log. It seems to be caused by the paser finding one `<testsuite>` in each `TEST-*.xml` file instead of one big file containing `<testsuites>`.

This is a pretty normal output and it matches what is proposed by the documentation when setting `testResultsFiles: '**/TEST-*.xml'`

This error message is coming from `src/Agent.Worker/TestResults/JunitResultReader.cs`. It seems to dislike files with a single suite. I don't know why.

Why? What is the logic behind it?

If considered normal, then the documentation should explain how to aggregate.

**Comment by TingluoHuang** [comment]
@nigurr

**Comment by SadagopanRajaram** [comment]
I have checked in a commit to remove the redundant commit

**Comment by henri-tremblay** [comment]
@SadagopanRajaram So it means my problem was fixed? Can you reference the commit or PR here please?

**Comment by SadagopanRajaram** [comment]
Commit [here](https://github.com/Microsoft/azure-pipelines-agent/commit/2f004a1fe316660ef2fd3ae80d6587db911c6ca5#diff-794b066dfa08920779551a9a83d82956)

**Comment by henri-tremblay** [comment]
Thanks. Great fix :-)
