### ISSUE TITLE
Container PATH being overridden (Caused by ##vso[task.appendpath])

### ISSUE THREAD

**Issue by davidroberts63** [Microsoft/azure-pipelines-agent#1969]
When running a build within a container (YAML container builds) the running container's PATH is getting overridden with the host's PATH, plus values for various tasks (nuget tool for instance). Is there a way to set this to prepend or append to the container PATH?

This seems related to #109 but that was from before container builds were generally available. I'm seeing the same effect though. When I run the container directly (outside of Pipelines) I see the expected PATH value (local binary paths, etc). But when the pipelines agent runs it, $ENV:PATH shows a value that matches what the host has, overriding what the container had when started.

I also posted a question about this on the [developer community](https://developercommunity.visualstudio.com/content/problem/376841/pipelines-window-container-path-being-overridden.html) but I've only received one response that didn't assist.

Here's part of the debug from a build:
```
##[debug]Set env: Path=C:\__t\NuGet\4.3.0\ia32;C:\[MYSERVERNAME]\externals\git\cmd;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Docker;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
```

But I expect to see a PATH that includes things such as the NETFX directories and other binaries that I've added.

Agent Version: 2.141.1
Commit: 8c0163e534b3740f4959826c54b099d679a64458
Host: Datacenter-Core-1803-with-Containers-smalldisk (Nothing else installed except the Pipelines agent)
Agent is running as a service (Local System)
Container: Based on microsoft/dotnet-framework:4.7.2-sdk-windowsservercore-1803 (but adds other binaries)
VisualStudio.com/dev.azure.com (-not- on prem tfs)

**Comment by TingluoHuang** [comment]
@davidroberts63 thanks for reporting this. looks like a limitation we have today. 
one quick question, why you are using tool installer task for container job? should your container bring in all required dependency for your job?

**Comment by davidroberts63** [comment]
Long term, will likely have the nuget in the container and not need that tool installer. I noticed this as I had added node to the container and couldn't run 'node' since it's path, 'C:\nodejs' in my case, was no longer in the PATH.

I vaguely recall poking around in the Handler or TaskPlugin that if no tool installers were used it wouldn't try to overwrite the path. But that was several days ago. Does that sound accurate?

**Comment by TingluoHuang** [comment]
@davidroberts63 yep, i will fix that in next agent release.

**Comment by davidroberts63** [comment]
Thank you @TingluoHuang for the incredibly quick replies on this. I'd be happy to test an update of this on one of our hosts if that helps.

**Comment by TingluoHuang** [comment]
#1977

**Comment by TingluoHuang** [comment]
close this issue since 2.144.0 has released to the service.
