### ISSUE TITLE
A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system.

### ISSUE THREAD

**Issue by roizentner** [Microsoft/azure-pipelines-agent#1971]
Hi,

Not sure if this should go here or at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks).

I recently installed a new agent on a local VM.
For some reason, two tasks fail with the following error:
`##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X86)'. Contact the task author for more details.`

The two tasks that fail are:

1. File System - Robocopy v1.0.12 by Jungerius IT
2. Regex Replace v1.0.8 by Ivan Boyko

I suspect this is not related to the tasks themselves because they weren't modified recently.
My guess is that either I'm running an agent with a bug or I'm missing something on my machine.

## Agent Version and Platform
Agent.Version: 2.141.1
Agent.OS: Windows
Agent.OSVersion: 10.0.14393
Agent.OSArchitecture: X86 (This is odd because the machine is running Windows Server 2016 x64)
VSTS: https://votiro.visualstudio.com

Please advise

**Comment by TingluoHuang** [comment]
@roizentner the error means those 2 tasks are using legacy task execution engine that not support in x86 environment.
the legacy execution engine is x64 only, you might want task author knows about this.

**Comment by roizentner** [comment]
@TingluoHuang But I'm running it on a x64 environment...

**Comment by TingluoHuang** [comment]
@roizentner then why you are using x86 agent? Agent.OSArchitecture: X86
we produce both x86 and x64 version agent.
where do you get your agent package?
https://vstsagentpackage.azureedge.net/agent/2.141.2/vsts-agent-win-x64-2.141.2.zip

**Comment by roizentner** [comment]
@TingluoHuang I downloaded it directly from VSTS. Now I see there are 'x86' and 'x64' tabs to choose under Windows agent. I've never noticed that before, is that new?
I'll replace the agent with an x64 one and report back...

**Comment by roizentner** [comment]
@TingluoHuang I replaced the x86 agent with an x64 agents and it fixed the issue. I'm really surprised I haven't noticed this before. Thanks for pointing me in the right direction!!
