### ISSUE TITLE
VSTS Agent makes instance inaccessable

### ISSUE THREAD

**Issue by BookOfGreg** [Microsoft/azure-pipelines-agent#1973]
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
Version of agent: 2.140.0
OS: Linux/Ubuntu-18.04

## What's not working?
When a release pipeline triggers, the VSTS agent goes offline and is no longer reachable via SSH. It becomes fully disabled.

![image](https://user-images.githubusercontent.com/637868/48558154-74852000-e8e0-11e8-89e6-5ecb040ff3ff.png)

![image](https://user-images.githubusercontent.com/637868/48558176-86ff5980-e8e0-11e8-97ac-10f8c259952f.png)

## Agent and Worker's Diagnostic Logs
There are no logs. VSTS completely crashed the instance.

**Comment by TingluoHuang** [comment]
@BookOfGreg who managed your "Self-Hosted" pool, where are those machine that host the agent binary? can you log on those machine and check the agent log?

**Comment by BookOfGreg** [comment]
@TingluoHuang I manage the self-hosted pool. They are the default Ubuntu 18-04 AMI from AWS running on T2.micro.
They no longer respond on any port so I cannot log onto them.

**Comment by TingluoHuang** [comment]
@BookOfGreg then, it sounds like AWS VM issue, are those instance still shows running is the AWS EC2 portal?

**Comment by BookOfGreg** [comment]
How did you come to the conclusion that VSTS Agent bricking a VM is AWS's fault?
They are still showing as running but they do not respond to restart or stop commands.

**Comment by TingluoHuang** [comment]
can you stop or restart that VM from AWS portal?
if you can, we can log in to the AWS VM figure out what's going wrong with the agent.
if you can't, then that means AWS is having trouble to control that VM from outside in, regardless of what's running inside that VM

**Comment by BookOfGreg** [comment]
> can you stop or restart that VM from AWS portal?

Nope, it becomes fully unresponsive. Can only terminate it.
Surely that means this is a security issue with VSTS that can DoS the entire server.

**Comment by vtbassmatt** [comment]
Hi @BookOfGreg. PM on Azure Pipelines here. If you feel you've found a security vulnerability in a Microsoft product, please report it through the [Microsoft Security Response Center](https://portal.msrc.microsoft.com/en-us/engage/sbr). Likewise, if you feel you've found a security vulnerability in AWS, please report it through [Amazon's vulnerability reporting tool](https://aws.amazon.com/security/vulnerability-reporting/). No one who contributes to this repository is authorized to talk openly about security incidents.

That aside, I don't see the security angle here. If you agree, we can figure out together how to debug what's happening with your AWS-hosted agents.

**Comment by BookOfGreg** [comment]
I can replicate it on Azure too if that helps.

**Comment by vtbassmatt** [comment]
Please raise a case with [MSRC](https://portal.msrc.microsoft.com/en-us/engage/sbr) if you believe it's a security issue.

**Comment by santusri** [comment]
I am trying to install vsts(azure DevOps) profiles on AWS EC2, intend to achieve tracking of jobs and increase number of parallel jobs. I found vsts test and controller agent installers as .exe`s, unable to find for Linux versions. I am not sure of how to establish a connection between aws(EC2) and azure(vsts). please share me your experiences.  Thanks!!

**Comment by TingluoHuang** [comment]
@santusri where do you find the installers? the agent build from this repository has several distributions supported.
https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.147.1

**Comment by santusri** [comment]
@TingluoHuang Thanks for the link. Is there any way to monitor and manage the builds, releases and mapping pools from aws ec2 instance, where vsts agent has been configured. please share me your thoughts and references.

**Comment by TingluoHuang** [comment]
@santusri the agent pool page should give you some idea, i am not quite sure what kind of monitor or manage you want.
![image](https://user-images.githubusercontent.com/1750815/53660485-fc8efb80-3c2b-11e9-9aa7-58f127e37f4f.png)

**Comment by santusri** [comment]
@TingluoHuang want to monitor and control jobs and agent pools from aws services, but not on vsts. Please don't feel offended, if it's not the correct question for you :)

**Comment by TingluoHuang** [comment]
@santusri  i think the closest thing would be use REST api to query those information. 
https://docs.microsoft.com/en-us/rest/api/azure/devops/build/?view=azure-devops-rest-5.0
