### ISSUE TITLE
Detached heads using VSO build tools

### ISSUE THREAD

**Issue by anandkkumar** [Microsoft/azure-pipelines-agent#1980]
## Agent Version and Platform
Version of agent: 2.140.2
OS of the machine running the agent: Linux

## VSTS Type and Version
VisualStudio.com
Account Name: http://dev.azure.com/imquant

## What's not working?
I use the 'GetSources' function in the build definition and specify the branch I want to checkout. Our git repo is also hosted on dev.azure.com. When I look at the logs it appears that the actual command being run is git checkout --force <commit_SHA>. This results in a DETACHED head in git. 

Why is this? I would like it to just do a git checkout <branch> and not result in detached heads. Can this be fixed or at least be something that's an option? I would imagine most people do not want a detached head (see screen shots below)

![image](https://user-images.githubusercontent.com/4745059/48797000-b211f080-ecc6-11e8-9fed-91b6fa875842.png)

![image](https://user-images.githubusercontent.com/4745059/48796990-a7eff200-ecc6-11e8-8e95-4033aececa8e.png)

**Comment by TingluoHuang** [comment]
@anandkkumar does detached head cause any problem to you?
the agent never checkout branch. if someone push to the branch you are trying to build after you queue the build on the server but before the agent checkout the branch. You will be end up in a situation where the server think the agent build SHA_1, but the agent actually build SHA_2. that will cause lots of problem in a CI system.

**Comment by anandkkumar** [comment]
thanks for the quick response. I see your point and didn't think of that possibility.

**Comment by szogun1987** [comment]
Can I configure a pipeline to check out on the actual branch? I have version file in my source control. I would like to commit this file back to branch from where it comes from. I accept the fact that my build would fail if multiple pushes would be performed at the same time.

**Comment by szogun1987** [comment]
Once I've added 
```
- checkout: self
  persistCredentials: true
  clean: true
```
It is important to add [ci skip] to commit message to avoid infinite build loop.
