### ISSUE TITLE
Allow System.AccessToken (OAuth 2.0 Token) to be used to register an agent

### ISSUE THREAD

**Issue by m-vanengelen-triple** [Microsoft/azure-pipelines-agent#1988]
The Agent registration mechanism currently supports quite a few registration possibilities such as PAT.

VSTS/ADOS leverages an OAuth 2.0 authentication token to be used in scripts (the System.AccessToken environment variable); a result of a successful authentication by the platform.
The token has the lifetime of the running build or release.

As part of the process we implement we create agents "on the fly" and destroy them after publishing the artifacts. The agents currently use a PAT to authenticate to VSTS/ADOS, however PAT's have a limited lifetime and is therefore not desired to use long-term.
Ideally the System.AccessToken is used - this lives just during the build/release. During registration of the agent a JWT token for internal communication is created/generated (so when the OAuth token would expire, the service would still be able to start/stop, hence the reason with PAT you have to re-enter the PAT during remove).

What considerations would have with the introduction of this token authentication for registering agents?

**Comment by m-vanengelen-triple** [comment]
Please do note I will prepare a PR with the functionality requested.

**Comment by TingluoHuang** [comment]
@m-vanengelen-triple i would not suggest doing this, since the scope of `System.AccessToken` is either per team project or the entire vsts account. By default, `System.AccessToken` doesn't have permission to configure/unconfigure agents (pool management permission), by doing this, any person who has permission to queue a build might able to break your agent pool (unconfigure some agent).

have you try choose `PAT` during agent configure, and paste `System.AccessToken` as the PAT?

**Comment by m-vanengelen-triple** [comment]
@TingluoHuang, the lifespan of our agents is very minimal.
Only on the spawn & die pools this scenario is applicable. In the scenario that you describe the person who queue's the build also needs to have permission to create a definition with a task to kill the pool.

It's very unfortunate the pool security system is flawed. There is no scenario where an administrator creates a pool, where a user or bit more privileged user can register an agent in the pool.
Certainly hope this will change in the past (and I'm sure the setup I'm proposing will change then as well).

**Comment by m-vanengelen-triple** [comment]
The PR that I made doesn't consider the `System.AccessToken` to be of any concern.
That we would be using it to feed that specific token to the `--auth oat --token <TOKEN>` is a concern of ours. I don't know for what kind of other scenario's this might be useful for others.

**Comment by TingluoHuang** [comment]
@m-vanengelen-triple 
i just did a test, you don't have to modify the agent code in order to use `System.AccessToken` to configure the agent.
you can use that token as `PAT` during agent configure.

![image](https://user-images.githubusercontent.com/1750815/49171268-2e7e8200-f30c-11e8-8c91-7507f87d8550.png)


the configure failed since i didn't grant it permission, but you can use the token to authenticate with service during config.

**Comment by TingluoHuang** [comment]
i am closing this issue for now, please reopen if my suggestion doesn't work.

**Comment by rkeegan** [comment]
I feel like there was not an actual suggestion here and there was never a solution. 
Is it possible to change the security/scope of the access tokens that are created during a release?

**Comment by m-vanengelen-triple** [comment]
> I feel like there was not an actual suggestion here and there was never a solution.
> Is it possible to change the security/scope of the access tokens that are created during a release?

The suggestion/workaround as proposed by @TingluoHuang was to use the System.AccessToken (which is an OAuth token), and use this in the PAT field (as it accepts these).
The downside of using this approach, is you must grant the Build Service user (which is collection based, not project based) with explicit permissions to manage a agent pool and/or deployment group.

It works as a charm though...!

**Comment by rkeegan** [comment]
@m-vanengelen-triple @TingluoHuang thank you, I misunderstood the suggestion. We were using the system access token similar to the original ticket, and running into identifier issues which we thought had to do with permissions. It did, and to do with the global vs project pool identifiers. We wiped everything and used new groups with the same permissions and everything works as expected, as a charm. IDK! Thanks for following up with me

**Comment by Locoxella** [comment]
If you are not used to admin privileges in Azure DevOps like me, save yourself some trouble. You need to grant administrator to the project scoped identity (https://learn.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml#scoped-build-identities) which is formatted like so: {Project Name} Build Service ({Org Name})

You need to grant that to your pool at the organization level. You can either go to Pools in organization settings or select "Organization" on the dropdown from the top-right corner in the list of permissions editor.

**Comment by h-batal** [comment]
> If you are not used to admin privileges in Azure DevOps like me, save yourself some trouble. You need to grant administrator to the project scoped identity (https://learn.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml#scoped-build-identities) which is formatted like so: {Project Name} Build Service ({Org Name})
> 
> You need to grant that to your pool at the organization level. You can either go to Pools in organization settings or select "Organization" on the dropdown from the top-right corner in the list of permissions editor.

I'm using System.AccessToken to clone another repo in the pipeline both of the repos are in the same organization and private, and I don't want to disable the "Limit job authorization scope to current project for non-release pipelines" for the whole organization, 
I added the builder of the first project and gave permissions on the other but still no luck
