### ISSUE TITLE
libcurl4 not found by bin/installdependencies.sh

### ISSUE THREAD

**Issue by BookOfGreg** [Microsoft/azure-pipelines-agent#1990]
## Agent Version and Platform
Version of your agent: 2.140.0

Ubuntu 18.04

## What's not working?
VSTS Agent fails to install on Ubuntu 18.04 due to not picking up latest libcurl correctly.
```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package liblttng-ust0
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcurl4
E: Package 'libcurl3' has no installation candidate
```

`sudo apt-get install libcurl4` before `dependencies.sh` fixes issue.

**Comment by BookOfGreg** [comment]
https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/installdependencies.sh#L39

**Comment by TingluoHuang** [comment]
@BookOfGreg where is the error coming from? i try to install `libcurl3` on ubuntu:18.04 and it succeed.

**Comment by BookOfGreg** [comment]
@TingluoHuang 
This AMI filter will trigger it. (packer or terraform style)
```
"source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "ubuntu/images/hvm-ssd/ubuntu-*-18.04-amd64-server-*",
          "root-device-type": "ebs"
        },
        "owners": [
          "099720109477"
        ],
        "most_recent": true
      },
```

**Comment by TingluoHuang** [comment]
@BookOfGreg base on https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore21#ubuntu

dotnet core still claims libcurl3 is their requirement. we need get confirm from them before making the change, i will do more search.

**Comment by TingluoHuang** [comment]
@BookOfGreg i did more search and libcurl4 should be fine. i let a comment in your PR, but i am think i am good with this changes. thanks again.
