### ISSUE TITLE
File path build filters trigger builds when content doesn't change

### ISSUE THREAD

**Issue by josh-endries** [Microsoft/azure-pipelines-agent#2008]
On our visualstudio.com instance, build definition CI Path Filters don't seem to work like I would expect. If I put in path filters, builds get queued frequently when those paths (or content under them) don't really change. For example, when I create a new branch, it triggers a build. I would expect it to only trigger a build when there's a content change in the files within that path. In this case, it's trying to push nuget packages that are identical to the most recent package (which was built off the branch it just branched from). Fortunately this build def prevents dupes and doesn't automatically change package version numbers, so we don't have dozens of new packages. I can see how in other cases you may want it to trigger when a new branch is created, so maybe this could be a toggle.

**Comment by TingluoHuang** [comment]
@josh-endries you might want to report this to https://developercommunity.visualstudio.com/spaces/21/index.html, since the problem you described is not scope to the pipeline agent.

**Comment by TingluoHuang** [comment]
i am closing this issue since the question is not scope to the agent.
https://developercommunity.visualstudio.com/spaces/21/index.html is a better place to post this question. :)
