### ISSUE TITLE
YAML: service connection name 00000000-0000-0000-0000-000000000000 is ambiguous

### ISSUE THREAD

**Issue by oceaneLonneux** [Microsoft/azure-pipelines-agent#2026]
Hello everyone, I'm facing an issue when I try to do a YAML build pipeline.
I only have one branch, master, and 2 service connections : the github one and the docker one. I am using the visual designer.

When I do a pipeline and use Docker with the Featured template, it works. When I want to use a YAML, it returns
**An error occurred while loading the YAML build pipeline. The service connection name 00000000-0000-0000-0000-000000000000 is ambiguous.**
And I just don't understand why...? I make it use the Github service connection, which is working with the other pipelines, but not with the YAML one.

Here is the code of my azure-pipelines.yaml
`resources:
  repositories:
  - repository: NameRepo
    type: github
    endpoint: NameConnectionGithub

queue:
name: Hosted Ubuntu 1604
steps:

task: Docker@1
displayName: 'Build an image'
inputs:
containerregistrytype: 'Container Registry'

dockerRegistryEndpoint: NAME

task: Docker@1
displayName: 'Push an image'
inputs:
containerregistrytype: 'Container Registry'

dockerRegistryEndpoint: NAME

command: 'Push an image'
`

**Comment by oceaneLonneux** [comment]
Hello guys, I found a way for my own problem!

SOLUTION : I called the connection oceaneLonneux (like my username) and it didn't find it. Renamed it github oceane, and it works.

You can NOT call it like the key or the build will fail!

**Comment by TingluoHuang** [comment]
@oceaneLonneux can you share your yaml files (2 files) that are not working and the one with your change that start working?

**Comment by oceaneLonneux** [comment]
> @oceaneLonneux can you share your yaml files (2 files) that are not working and the one with your change that start working?

I am using the file I showed on the top for the yaml pipeline. I literally copied it from the steps I got from the visual designer.

It did seem that with the yaml pipeline, Azure Devops get confused very fast with name...

**Comment by bariscaglar** [comment]
@TingluoHuang I am having the same problem. Not sure how @oceaneLonneux fixed it by changing the service connection name. I've tried modifying it and creating a new one but the problem is still there.

**Comment by bariscaglar** [comment]
In fact all of our pipelines are failing with the same problem.

**Comment by TingluoHuang** [comment]
@bariscaglar what's your yaml file looks like?

**Comment by bariscaglar** [comment]
@TingluoHuang Please see the new issue #2209 since this one is already closed.
