### ISSUE TITLE
Visual Studio Build Task fails on logging when any filenames contain [ or ]

### ISSUE THREAD

**Issue by moswald** [Microsoft/azure-pipelines-agent#2033]
_[Copied from azure-pipelines-tasks #6314](https://github.com/Microsoft/azure-pipelines-tasks/issues/6314#issue-292884713)._ /cc: @steelerc

## Issue Description
If a solution has any project with a filename containing either of [ or ] the build process succeeds, but is marked as failed.  Actual build step logs show:
2018-01-30T16:13:36.3337662Z Build succeeded.
2018-01-30T16:13:36.3337906Z     0 Warning(s)
2018-01-30T16:13:36.3338086Z     0 Error(s)
2018-01-30T16:13:36.3338222Z 
2018-01-30T16:13:36.3338415Z Time Elapsed 00:00:08.30
2018-01-30T16:13:36.4870583Z ##[section]Finishing: Build solution

But build output shows errors below
### Error logs
Unable to process command '##vso[task.logdetail id=927b3194-b008-473a-b822-91af5a4dadcb;parentid=;name=QuotingRepository\Interfaces\IBaseRepository[T].cs;type=Build;starttime=2018-01-30T16:13:01.2494103Z;state=InProgress;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Type is required for this new timeline record.
d:\a\1\s\QuotingRepository\Interfaces\IBaseRepository[T (0, 0)
d:\a\1\s\QuotingRepository\Interfaces\IBaseRepository[T(,): Warning : .cs;linenumber=23;columnnumber=22;code=SA1649;]File name must match first type name.
Unable to process command '##vso[task.logdetail id=927b3194-b008-473a-b822-91af5a4dadcb;parentid=;type=Build;result=Failed;finishtime=2018-01-30T16:13:01.2594098Z;progress=100;state=Completed;parentid=;name=;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Name is required for this new timeline record.

**Comment by TingluoHuang** [comment]
@moswald the task needs to escape those char, i thought we already fix this in MSBuild logger.

**Comment by moswald** [comment]
@TingluoHuang I would have expected the same, but I didn't really dig into it yet. I was just cleaning up our GitHub issues assigned to Area: Build.

**Comment by TingluoHuang** [comment]
@moswald we do fix the logger, but i guess we didn't consume the logger in the task.
[Pull Request 250269: Add escaping of closing bracket](https://dev.azure.com/mseng/_git/AzureDevOps/pullrequest/250269?path=%2FDistributedTask%2FAgent%2FMSBuild.Logger%2FConsoleEventListener.cs&_a=overview)

**Comment by stephenmichaelf** [comment]
Interesting. I thought we did fix it for the task. @damccorm Could you take a look?

**Comment by stephenmichaelf** [comment]
@damccorm can we close this?

**Comment by damccorm** [comment]
Yeah, sorry I meant to when I merged the PR.
