### ISSUE TITLE
I am trying to upload a log file that is still being written to.

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/azure-pipelines-agent#2034]
## Having generic issue with Azure-Pipelines/VSTS/TFS?
I am trying to upload a log file that is still being written to. I don't have full control over the termination of the handle for this log file.

When the agent tries to upload this file it attempts to open the file with FileShare.Read option [here](https://github.com/Microsoft/azure-pipelines-agent/blob/6cbbd67bb8ab28e95cc8565bd48184fa9798d575/src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs#L647)

This causes the open to fail as there is a process that still has a write handle on this file. (Although the actual logging has completed)

Is there a particular reason why the agent doesn't allow the upload of files still being written to?

## Agent Version and Platform
Latest

## VSTS Type and Version
VisualStudio.com

## Stack trace from diagnostic logs
[2019-01-03 05:42:32Z INFO JobServerQueue] Catch exception during log or attachment file upload, keep going since the process is best effort.
[2019-01-03 05:42:32Z ERR  JobServerQueue] System.IO.IOException: The process cannot access the file 'C:\AgentSmith133mseng\_work\_temp\TraceLogs-32345473_0f6cdf14-046c-44a6-a014-fec3543c33c2.diag' because it is being used by another process.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String ***h, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.<UploadFile>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDis***chInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.<ProcessFilesUploadQueueAsync>d__36.MoveNext()

## Agent and Worker's Diagnostic Logs
[Build 20190102.3-Agent job 1.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2723101/Build.20190102.3-Agent.job.1.zip)

**Comment by TingluoHuang** [comment]
@ShreyasRmsft the agent only need to read the file to upload, why it needs to open the file in ReadWrite mode?
are you able to repro this all the time? what about anti-virus setting?

**Comment by ShreyasRmsft** [comment]
Hey @Tingluo Huang, it's not the File access param I'm changing, it's the file share option

**Comment by ShreyasRmsft** [comment]
What it basically means is that other process are allowed to read or write to the file while the agent reads (in this case) the file

**Comment by TingluoHuang** [comment]
@ShreyasRmsft why we allow other process write? if the write happen after agent start upload the file, that means the end user won't get them.
i would argue the task needs to finish writing first before it issue ##vso command to let the agent upload the file.

**Comment by ShreyasRmsft** [comment]
The task author would have a choice to upload either after the entire file has been written or if need be upload as much data as been written.

**Comment by TingluoHuang** [comment]
@ShreyasRmsft that is not what the ##vso command designed for. :)
for your situation, why not put the `echo ##vso` in your `finally{}` block.

**Comment by ShreyasRmsft** [comment]
So here's the thing, the code that is doing the logging is part of the test platform. Not directly a part of my task code. Hence the problem. If I was directly in control of the logging I could have done this.

**Comment by ShreyasRmsft** [comment]
It'd be sweet if the agent allowed this.

**Comment by TingluoHuang** [comment]
```
[2019-01-03 05:42:32Z ERR JobServerQueue] System.IO.IOException: The process cannot access the file 'C:\AgentSmith133mseng_work_temp\TraceLogs-32345473_0f6cdf14-046c-44a6-a014-fec3543c33c2.diag' because it is being used by another process.
at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
```

if i understand the error message correct, the error means the agent process can't open the file handle to read the file. the file is hold by some process and that process doesn't allow agent process to read it.

you PR is try to change the `FileShare` option of how agent opens the file, that only matters for subsequent opening of the file, it won't change the fact the file is current locked by other process and agent can't open it for read.
https://docs.microsoft.com/en-us/dotnet/api/system.io.fileshare?view=netframework-4.7.2#fields

**Comment by ShreyasRmsft** [comment]
Hmm very strange. I tried out a simple experiment wherein first I opened a file in write mode with share set to readwrite

Then in a separate process I tried to open the file in read mode with share set to read and it failed with the above exception.

Then when I modified the share option to readwrite in the process and it was able to read without issues

Despite what the document says about subsequent access, the behavior is that it check previous accesses also

**Comment by ShreyasRmsft** [comment]
I'm not sure if this is a bug in dotnet or the docs are misleading. I can share the sample console apps I created. Or you should be able to whip this up in a minute and verify.

Note: I authored 2 dotnet 4.5 applications, don't know if there's a difference in behavior between dotnet and dotnetcore

**Comment by ShreyasRmsft** [comment]
I can guarantee that the process that has created file in my case has the fileshare set to readwrite

**Comment by ShreyasRmsft** [comment]
https://code.i-harness.com/en/q/1e812

To quote the relevant section:

This is the closest to the truth IMO... " Whenever a program tries to open a file, you specify a FileAccess and FileShare parameter (or defaults are taken if they're not explicitly passed). What Windows then has to do is check all existing open file handles, and determine whether they're compatible. So it compares your FileAccess parameter against everyone else's FileShare parameters - are you allowed to do what everyone else has said they're happy for others to do? And then it performs the opposite check - does your FileShare parameter match up with their FileAccess parameters? - are they doing things that you're happy for them to be doing? Only if both checks pass can your particular open request be approved."

**Comment by TingluoHuang** [comment]
got it. i left 1 comment in your PR, please address that, i will merge your PR.
thanks for finding and fixing this. :)

**Comment by ShreyasRmsft** [comment]
On it.

**Comment by ShreyasRmsft** [comment]
Your comment did not get published I think. I don't see it in the pr

**Comment by ShreyasRmsft** [comment]
Done

**Comment by TingluoHuang** [comment]
close the issue as PR merged, thanks again for fixing this. :)
