### ISSUE TITLE
Agent connection fail

### ISSUE THREAD

**Issue by scottunik** [Microsoft/azure-pipelines-agent#2036]
## Agent Version and Platform

Agent version 2.136.1 win-x64
Platform Windows 2016 

## VSTS Type and Version
On-Prem TFS 2018 Update 3,1

## What's not working?
System wide agent failure after restart of application tier.  We are running 10 build machines and approximately 30 agents which all failured with the following

[2019-01-02 07:43:44Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file D:\Builds\Agent1\.credentials_rsaparams
[2019-01-02 07:43:44Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file D:\Builds\Agent1\.credentials_rsaparams
[2019-01-02 07:45:24Z WARN VisualStudioServices] GET request to http://tfsapp02:8080/tfs/_apis/connectionData?connectOptions=1&lastChangeId=32&lastChangeId64=32 timed out after 100 seconds.
[2019-01-02 07:45:24Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-01-02 07:45:24Z INFO AgentServer] Catch exception during connect. 4 attemp left.

This problem first started after upgrading from TFS 2018 update 2 to TFS update 3.1, where we saw this problem after immediately updating.  Non of our agents could connect to the TFS instance.  After many hours of debugging the problem was resolved by removing the https binding.   The problem reoccured after a routine restart of application tieir a week ago.  After many restarts of our builder servers and the application tieir the problem was resolved by adding and removing a IIS binding on the application tieir.
[Agent_20190102-074341-utc.log](https://github.com/Microsoft/azure-pipelines-agent/files/2723608/Agent_20190102-074341-utc.log)

## Agent and Worker's Diagnostic Logs
I have atatched ahent log file.

**Comment by scottunik** [comment]
**Aditional information.**  

I have examined the ISS log on application tieir and it is the POST of the token that is failing,

POST /tfs/_apis/oauth2/token - 80 - 10.50.1.159 VstsAgentCore-win-x64/2.136.1+(Microsoft+Windows+10.0.14393)+VSServices/16.136.27801.0+(NetStandard;+Microsoft+Windows+10.0.14393) - 400 0 0 15

Is there any logging made for the oauth2/token?

**Comment by scottunik** [comment]
@TingluoHuang thanks for that but the eventd for that period have been overwritten.  I have increase the size of the log.  Are there any other places that could help me debuf this issue?  Does that log output mean anything to you?

**Comment by TingluoHuang** [comment]
```
POST /tfs/_apis/oauth2/token - 80 - 10.50.1.159 VstsAgentCore-win-x64/2.136.1+(Microsoft+Windows+10.0.14393)+VSServices/16.136.27801.0+(NetStandard;+Microsoft+Windows+10.0.14393) - 400 0 0 15
```
the server returns `400`  which is weird, you might want to capture Http trace in the agent side, and see what's in the payload of that 400 response.
https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=vsts#windows
