### ISSUE TITLE
TF_BUILD environment variable missing from container job

### ISSUE THREAD

**Issue by gitfool** [Microsoft/azure-pipelines-agent#2039]
## Agent Version and Platform
Version of your agent? 2.144.0

OS of the machine running the agent? Linux; Ubuntu 16.04 with Docker

## VSTS Type and Version
Azure Pipelines

## What's not working?
Following up from https://github.com/cake-build/cake/issues/2432, the container job in [Cake.Dungeon/azure-pipelines.yml#L6-L17](https://github.com/gitfool/Cake.Dungeon/blob/master/azure-pipelines.yml#L6-L17) uses [cake-build/cake](https://github.com/cake-build/cake) and is not working as expected because the `TF_BUILD` environment variable has not been passed to the Docker container.

See [Cake.Dungeon/#20190107.3/Docker job](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=09181c4b-3f3c-50e9-b57f-22616eaa56ea&lineStart=19&lineEnd=121&colStart=1&colEnd=1) for all the build step environment variables, which have been logged as seen from inside the container. Note that the `TF_BUILD` environment variable is missing.

For comparison, [Cake.Dungeon/#20190107.3/Linux job](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03&lineStart=141&lineEnd=142&colStart=1&colEnd=1) and [Cake.Dungeon/#20190107.3/Windows job](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=c37637b8-ed57-5a02-c556-da2855a7e2d3&lineStart=163&lineEnd=164&colStart=1&colEnd=1), are both run directly on the agent and see the `TF_BUILD` environment variable.

The `TF_BUILD` environment variable is required for Cake build to correctly detect if it is running on Azure Pipelines and affects subsequent build behavior such as only publishing artifacts when detected.

**Comment by TingluoHuang** [comment]
@gitfool thanks for reporting this. we will fix this.

**Comment by gitfool** [comment]
@TingluoHuang thanks for the fast turnaround! Any idea when it will be deployed? (I’m not sure if you’re continuously deploying to production.)

**Comment by gitfool** [comment]
FTR, workaround removed as fixed in azure pipelines agent 2.146.0 deployed ~Feb 6. Thanks again!
