### ISSUE TITLE
Job Abandoned: Agent machine reboots or shuts down on ubuntu regularly

### ISSUE THREAD

**Issue by BookOfGreg** [microsoft/azure-pipelines-agent#2041]
Same as #1973 Not sure why it was closed last time.

VSTS when running builds on a blank ubuntu box will start hitting 100% CPU at random and the box becomes unreachable by SSH.

This happens on AWS and Azure so it is NOT an AWS issue as microsoft employees said in the last issue for some reason.

![image](https://user-images.githubusercontent.com/637868/50967175-44689080-14cf-11e9-9bad-516635bb8438.png)

Reproduction:
```shell
#!/bin/bash
set -e
set -x

# Ubuntu 18
sudo add-apt-repository universe # https://askubuntu.com/questions/1073695/18-04-server-unable-to-locate-package-redis-server
sudo apt-get update
# Tools to install things
sudo apt-get install -y software-properties-common apt-transport-https
# Basic Libs
sudo apt-get install -y git-core zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libffi-dev
# Redis
sudo apt-get install -y redis-server redis-tools
# Postgres
sudo apt-get install -y libpq-dev
# Automatic security upgrades
sudo apt-get install unattended-upgrades


# VSTS Agent install
mkdir Downloads
curl https://vstsagentpackage.azureedge.net/agent/2.140.0/vsts-agent-linux-x64-2.140.0.tar.gz -o ~/Downloads/vsts-agent-linux-x64-2.140.0.tar.gz
mkdir myagent && cd myagent
tar xzf ~/Downloads/vsts-agent-linux-x64-2.140.0.tar.gz
sudo ./bin/installdependencies.sh
# GET Personal Access Token from https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts#create-personal-access-tokens-to-authenticate-access
./config.sh --unattended --url YOUR_URL --auth pat --token YOUR_TOKEN --pool Self-Hosted --agent utils-agent-$PACKER_BUILD_NAME --acceptTeeEula
sudo ./svc.sh install
# sudo ./svc.sh start # Started later
git --version

sudo apt-get install -y curl # Microsoft installer messes with it.
curl --version



# .NET Core Install
echo 'export DOTNET_CLI_TELEMETRY_OPTOUT=1' >> ~/.bashrc
export DOTNET_CLI_TELEMETRY_OPTOUT=1
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install -y dotnet-sdk-2.1
dotnet --version

# Docker Install
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
sudo apt-get update
sudo apt-get install -y docker-ce
docker -v
sudo usermod -a -G docker ubuntu

# Docker Compose Install
sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose -v

# Update VSTS Agent capabilities
./env.sh
sudo ./svc.sh stop
sudo ./svc.sh start
```

Then keep running builds through it and it will hit 100% cpu and die.

I will be able to get logs this time as the disk was snapshotted.

**Comment by BookOfGreg** [comment]
The last log before the rough time it became inaccessible is this:
```
[2019-01-10 11:24:48Z INFO JobServerQueue] Try to append 1 batches web console lines for record '28e14b79-1d95-5195-ee03-3a68ac48a418', success rate: 1/1.
[2019-01-10 11:24:48Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2019-01-10 11:24:48Z INFO JobServerQueue] Try to append 1 batches web console lines for record '28e14b79-1d95-5195-ee03-3a68ac48a418', success rate: 1/1.
[2019-01-10 11:24:56Z INFO JobServerQueue] Try to append 1 batches web console lines for record '28e14b79-1d95-5195-ee03-3a68ac48a418', success rate: 1/1.
[2019-01-10 11:24:57Z INFO JobServerQueue] Try to append 1 batches web console lines for record '28e14b79-1d95-5195-ee03-3a68ac48a418', success rate: 1/1.
[2019-01-10 11:25:37Z INFO JobServerQueue] Stop aggressive process web console line queue.
```

**Comment by TingluoHuang** [comment]
@BookOfGreg what's your build process looks like, does it consume lots of CPU? Can you try create some idle definition, like `ping  -c 1000 127.0.0.1`, and queue that definition? So we can check whether the agent/worker process consume all your CPU resource for no reason?
also, can you try check the system log `/var/log`?

**Comment by BookOfGreg** [comment]
![image](https://user-images.githubusercontent.com/637868/50972471-9f55b400-14de-11e9-9baf-adce20c77d24.png)

In this instance it failed in between two stages. Looking at the server I can see that there is nothing in the Rails test log so it had not begin the rails test phase.

Previous failures I've seen it fail between tasks or before starting the first task.
I've also seen it fail during releases between tasks as well as builds.
It might be worth mentioning all my tasks are using the Bash Script inline script task in case that is relevant.
I've not seen it fail during a task.

**Comment by BookOfGreg** [comment]
The agent crashed in between jobs over the weekend. There is nothing in the _diag/worker logs from the 11th, on the morning of the 12th the last entry is :
```
Jan 12 01:32:34 ip-10-0-1-141 runsvc.sh[775]: <Buffer 32 30 31 39 2d 30 31 2d 31 32 20 30 31 3a 33 32 3a 33 34 5a 3a 20 41 67 65 6e 74 20 63 6f 6e 6e 65 63 74 20 65 72 72 6f 72 3a 20 54 68 65 20 48 54 54 ... >
```
Which is the VSTS agent.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=vsts#install
Not sure what it did, will look at other logs on the box to see if I can see anything else.

**Comment by BookOfGreg** [comment]
Problem solved. It runs out of RAM.

The VSTS agent takes more than 1GB of ram while running tasks and causes the system to fail.
I'm seeing 100% used slabs in slabtop and I managed to get the syslog during failure which contained failed mallocs. VSTS just uses a ton of RAM, fixed by allocating a bigger box.

Are there any recommended server sizes?

**Comment by BookOfGreg** [comment]
May I recommend this tool install itself the way Postgres does, create a new user on installation.
This would allow me to automatically put the process in a [cgroup](https://unix.stackexchange.com/questions/34334/how-to-create-a-user-with-limited-ram-usage).

The reason I get this where other people might not is I am not running the Out Of Memory (oom) killer, but now I look at `tail -n+1 /proc/*/oom_*`, the `/home/me/myagent/bin/Agent.Listener run --startuptype service` has by far the highest OOM score, therefore Ubuntu would have normally terminated that process for majority of users.

The agent died between tasks in a build, it doesn't appear it launched the build itself.
The build in my case was:
```
tar -xvf drop/app.tar.gz
aws s3 sync build s3:/mywebsite/index.html
etc etc
```

**Comment by bryanmacfarlane** [comment]
The Agent.Listener process is tiny and just does a long poll to pull messages.  Each build is a separate Agent.Worker process and the lifetime of that process is the build.  The memory consumption of Agent.Listener is tiny but the process tree might be large.  Listener --> Worker --> Node (task) --> (your tool process).  Are you sure it's not reporting the memory consumption of the process tree?

**Comment by bryanmacfarlane** [comment]
Re-opening because I want to drill in on the memory consumption point.  Also, I don't think the agent is crashing - can you confirm?  I think the machine is running out of resources.  I would like to understand what's using the resources.

**Comment by BookOfGreg** [comment]
Good morning @bryanmacfarlane ,
I suspect above I have been jumping to conclusions during diagnosis.
If the process is a child of Agent.Listener then it would be appearing that it was that process failing, and my belief that this was the case was strengthened due to the logs I provided above showing that as the last output, in addition to <company>.visualstudio.com showing the failure as between builds with no further evidence that the build had actually started.
There were two other factors leading me to believe it was the VSTS agent, which is when I ran the content of the failing task by hand it never OOM'ed, not even once, and that HTOP when the process is running reports the VSTS agent not the AWS or Node or Docker task that was actually running.

Its hard to know if it crashes or not as the only way to regain access is a reboot.
The machine IS running out of resources but as mentioned running the task directly does not OOM, whereas running it in VSTS does. When I ran it directly VSTS was idling in the background so the total system memory should have been relatively similar. This does not happen every time but did not happen at all when the task was not process intensive (the ping test mentioned above).

I wonder if it's just the case of VSTS agent behaving badly during OOM where other processes still yield enough resources to the system. Could you run a Node process that uses 1.1gb of ram on a 1gb Linux server and see if you can SSH to it, then run that same process inside of VSTS and see if you can SSH to it?

As an aside, there was a Hacker News post this week where some fraction, maybe 1/5, mention VSTS crashing as a reason to stop using it so I reckon even though it's probably my inability to spot the OOM in my own processes, this kind of issue seems to affect others. Could the agent somehow report an OOM to the host server perhaps?

**Comment by bryanmacfarlane** [comment]
Good thoughts.  We can dig in an experiment.  I do suspect if there's no swap disk, 1GB and something uses more than 1GB, very bad things will happen that an app can't recover from ;) . It would be good to figure out what's using the memory.  Perhaps something running in the background that writes the process and memory used to a log on an interval and then retry?  We have discussed having something in the agent that tracks resources (and disk space etc...) and logs/reports in cases like this.

**Comment by bryanmacfarlane** [comment]
we might need a feature in the agent to watch for resources

**Comment by BookOfGreg** [comment]
Do you have any thoughts on the suggestion above to install the VSTS agent in a service account, and put it in a cgroup, the same way as Docker and Postgres install themselves as users for isolation?

**Comment by bryanmacfarlane** [comment]
Yes.  We are investigating that.  We take PRs

**Comment by dakale** [comment]
Hey @BookOfGreg Im helping out on this investigation too. You mentioned you have the oom killer disabled on your linux vms, so I am assuming you have `vm.oom-kill = 0`, correct? 

Can you expand on your configuration, namely, what settings are you using for `vm.overcommit_memory` and `vm.overcommit_ratio`? 

Ubuntu defaults are going to be overcomitting memory (`vm.overcommit_memory = 0`) so I could see a scenario where you are running out of memory and nothing is being killed, causing the system to hang. 

However it seems more likely that you are not overcommitting memory along with having `oom-kill = 0`, just want to confirm that is your configuration first

**Comment by dakale** [comment]
Also, for cgroups, I think that is going to be dependent on you since you are self hosting. On our hosted pools, the agent *is* run as a `vsts` user account, but for that we would need to set up the cgroup config on those machine images, not the agent itself. If you want to use cgroups on your AWS or Azure vms, I believe you would need to manually set that up such such processes named `Agent.*` (`Agent.Listener` and `Agent.Worker` run in the cgroup you configure, which would then limit the memory, cpu usage, etc.

**Comment by chrisrpatterson** [comment]
@bryanmacfarlane and @dakale we have a configuration script for configuring the agent to run as a serviced unit. It seems like we should add whatever configuration we decided on for our hosted VMs to that script so customers with self-hosted agents benefit.

**Comment by BookOfGreg** [comment]
@dakale I've installed according to the instructions provided, and most of it is also inside the task: `sudo ./bin/installdependencies.sh`
Could the installdependencies.sh also include creating and installing the tool into a VSTS user? Agree that cgroups may be specific to where and how it is being installed, so I understand if that may not be possible.
Regarding the `vm.` settings, I don't think I have any on this server, at least non that I can find in the /etc directory. It's the official Canonical AMI on AWS that I'm using so whatever the defaults are is what I am using.

**Comment by bryanmacfarlane** [comment]
@BookOfGreg - update

Apologies for the issues you ran into.  We are in progress of testing cgroup, swap disks and other improvements in this area.

We've been digging into abandoned builds and while the likelyhood overall is very low, if you're in that bucket that's consuming more memory or other resources, you can fall into a bucket where you fail frequently.  

We're taking this very seriously, allocating quite a bit of resources toward it and I'm hopeful that our first round of changes will help in this area.

I'll let you know when it's available and we would appreciate you trying again when it's ready.

Thank you so much for raising this issue and working with us.

**Comment by bryanmacfarlane** [comment]
@chrisrpatterson - I'll follow up with @dakale on the setup stuff
