### ISSUE TITLE
java capability not detected properly with Amazon Corretto & Java 10 & 11

### ISSUE THREAD

**Issue by ckruegerkpmg** [microsoft/azure-pipelines-agent#2045]
If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

2018 Update 3

## What's not working?
The TFS agent didn't pickup a java installation of
https://aws.amazon.com/corretto/

src\Misc\layoutbin\powershell\Add-JavaCapabilities.ps1
lookes only for:

 Define the JRE/JDK key names.
$jre6KeyName = "Software\JavaSoft\Java Runtime Environment\1.6"
$jre7KeyName = "Software\JavaSoft\Java Runtime Environment\1.7"
$jre8KeyName = "Software\JavaSoft\Java Runtime Environment\1.8"
$jdk6KeyName = "Software\JavaSoft\Java Development Kit\1.6"
$jdk7KeyName = "Software\JavaSoft\Java Development Kit\1.7"
$jdk8KeyName = "Software\JavaSoft\Java Development Kit\1.8"

But Corretto adds the build number to the registry path
\SOFTWARE\JavaSoft\Java Development Kit\1.8.0.192

Java 10 & 11 are not detected at all (even the Oracle version)

**Comment by TingluoHuang** [comment]
@madhurig FYI,

**Comment by akuryan** [comment]
As with #2046 I can advise you to set ```java``` environment variable to point to coretto installation manually (or in script).
