### ISSUE TITLE
Segmentation fault with Agent with Raspberry Pi Zero W

### ISSUE THREAD

**Issue by Deph0** [Microsoft/azure-pipelines-agent#2047]
## Agent Version and Platform
**Version of your agent?**
Latest (2.144.0 vsts-agent-linux-arm-2.144.0)

**OS of the machine running the agent?**
OS: Linux Raspbian
Machine: Raspberry Pi Zero W

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

## What's not working?
Attempting to install / run the linux agent provided by Azure DevOps for ARM ends up at seg fault.
The Prerequisites tells us ARM32 is supported, and thus armv7 should run as it contains 32bit instructions. I was unable to find anything about which RPI is supposedly actually supported. I do not have access to any other RPI at this time.

## Agent and Worker's Diagnostic Logs
```
$ wget https://vstsagentpackage.azureedge.net/agent/2.144.0/vsts-agent-linux-arm-2.144.0.tar.gz
$ tar xvfz vsts-agent-linux-arm-2.144.0.tar.gz
$ ./config.sh
./config.sh: line 86:  3165 Segmentation fault        ./bin/Agent.Listener configure "$@"

$ ./run.sh
./run.sh: line 28:  3239 Segmentation fault        $DIR/bin/Agent.Listener run $*

$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
```

**Comment by TingluoHuang** [comment]
@Deph0 your CPU info shows it's  `ARMv6`, which is not supported by the agent (dotnet core). `ARMv7` or above is required.
```
$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
```

**Comment by Deph0** [comment]
Ok, thanks. I heavily suggest updating the prerequisite with this kind of information.
