### ISSUE TITLE
"VS30063: You are not authorized to access https://dev.azure.com." when using Integrated auth but works with PAT

### ISSUE THREAD

**Issue by deadlydog** [Microsoft/azure-pipelines-agent#2052]
Hello, we just migrated our on-prem TFS to Azure DevOps today. I'm now trying to install the build agent on our on-prem build servers. I am using vsts-agent-win-x64-2.144.0 on Windows Server 2016.

The command I am using to configure the build agent is:

```
config.cmd --unattended --url https://dev.azure.com/iqmetrix --auth Integrated --pool default --agent IQ-RGTFSBLD010 --work C:\Builds\_work --runasservice --windowslogonaccount IQMETRIXHO\TFSService --windowslogonpassword Redacted
```

and the error message I receive is:

> VS30063: You are not authorized to access https://dev.azure.com.

I receive this error both when attempting to install using `--unattended` as well as when installing it interactively when logged in as TFSService.
![image](https://user-images.githubusercontent.com/1187140/51094199-8106e700-1770-11e9-8544-3acf22257efa.png)

I believe TFSService has all of the required permissions, as if I change from using `Integrated` auth to using a TFSService `PAT` then it installs fine. I would rather not have to use a PAT though because they expire, meaning we'll have to remember to go and update them in all of our build agents periodically.

Is this a bug with Azure DevOps or the agent? Or is it something misconfigured on my end?

Here is the log file generated when attempting to install using the command I pasted above.
[Agent_20190114-022849-utc.log](https://github.com/Microsoft/azure-pipelines-agent/files/2753894/Agent_20190114-022849-utc.log)

**Comment by TingluoHuang** [comment]
@deadlydog `Integrate` auth is only support for on-prem TFS, you need to use `PAT` to configure agent against DevOps Service.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts#authenticate-with-a-personal-access-token-pat

You don't need to worris about `PAT` expire, since we only use to at config/unconfig time. the agent is running as low previlege service account when running jobs. you can learn agent auth from https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/design/auth.md

**Comment by deadlydog** [comment]
Ah, that makes sense. It's still not ideal since we provision our on-prem build servers via PowerShell DSC. This means that we'll still need to generate a new PAT every year and update our DSC config files with it. Not a big problem, but a bit of a nuisance. This does solve my problem though. Thanks for the quick reply!

P.S. It would be nice if the build agent command prompt could output a more descriptive / helpful error message, since this is a known limitation.
