### ISSUE TITLE
Docker socket is not accessible from inside the Docker container

### ISSUE THREAD

**Issue by gitfool** [Microsoft/azure-pipelines-agent#2056]
## Agent Version and Platform
Version of your agent? 2.144.0

OS of the machine running the agent? Linux; Ubuntu 16.04 with Docker

## Azure DevOps Type and Version
Azure Pipelines

## What's not working?
The container job in [BoardGameGeek.Dungeon/azure-pipelines.yml](https://github.com/gitfool/BoardGameGeek.Dungeon/blob/master/azure-pipelines.yml#L8), which uses [cake-build/cake](https://github.com/cake-build/cake) via a Docker container ([cake-docker/Dockerfile](https://github.com/gitfool/cake-docker/blob/master/Dockerfile)) and [Cake.Dungeon](https://github.com/gitfool/Cake.Dungeon) scripts to [build](https://github.com/gitfool/Cake.Dungeon/blob/master/scripts/tasks.cake#L115) and [push](https://github.com/gitfool/Cake.Dungeon/blob/master/scripts/tasks.cake#L203) a Docker image to Docker Hub, is not working as expected because the Docker socket is not accessible from inside the Docker container.

See [BoardGameGeek.Dungeon/#20190115.6/Docker job](https://dev.azure.com/gitfool/BoardGameGeek.Dungeon/_build/results?buildId=66&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=09181c4b-3f3c-50e9-b57f-22616eaa56ea&lineStart=352&lineEnd=352&colStart=30&colEnd=134) for all the build step environment variables, which have been logged as seen from inside the container. Note the error at the bottom:
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock
```
Is there a way to mount or otherwise make the Docker socket accessible to Azure Pipelines container jobs?

**Comment by gitfool** [comment]
@TingluoHuang I've tried everything I can think of but I haven't managed to fix the permission issue:

- Add build steps for:
  - `usermod -a -G docker $USER`
    - [usermod: group 'docker' does not exist](https://dev.azure.com/gitfool/BoardGameGeek.Dungeon/_build/results?buildId=68&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=ddee3446-9f1b-56c7-8e99-261e20073079&lineStart=13&lineEnd=13&colStart=30&colEnd=68)
  - `groupadd docker && usermod -a -G docker $USER`
    - [groupadd: Permission denied](https://dev.azure.com/gitfool/BoardGameGeek.Dungeon/_build/results?buildId=69&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=ddee3446-9f1b-56c7-8e99-261e20073079&lineStart=11&lineEnd=11&colStart=30&colEnd=75)
  - `usermod -a -G docker $USER` (after adding docker group to my container)
    - [usermod: Permission denied](https://dev.azure.com/gitfool/BoardGameGeek.Dungeon/_build/results?buildId=72&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=ddee3446-9f1b-56c7-8e99-261e20073079&lineStart=12&lineEnd=12&colStart=30&colEnd=56)
- Remove build steps above after adding vsts_azpcontainer (1001) user in docker group to my container
  - [Got permission denied while trying to connect to the Docker daemon socket](https://dev.azure.com/gitfool/BoardGameGeek.Dungeon/_build/results?buildId=74&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=09181c4b-3f3c-50e9-b57f-22616eaa56ea&lineStart=352&lineEnd=352&colStart=30&colEnd=134)

I think I'm on the right track but I can't seem to solve it from my end. What am I missing?

**Comment by TingluoHuang** [comment]
@gitfool have you try `SUDO groupadd/usermod`?

**Comment by TingluoHuang** [comment]
@gitfool 
my following yaml seems works fine.
```yaml
resources:
  containers:
  - container: ubuntu
    #image: ubuntu:16.04
    image: microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard  # this image has docker installed
phases:
- phase: test1
  queue:
    name: 'Hosted Ubuntu 1604'
    container: ubuntu
  steps:
  - script: printenv|sort
  - script: |
      sudo docker run hello-world
```

**Comment by gitfool** [comment]
@TingluoHuang There's a fundamental difference though; the Cake build does not use `sudo` to run docker, so I need to [run docker as a non-root user](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user).

The Azure Pipelines agent creates a user in the container but does not create a docker group or use the `group-add` option of docker [create](https://docs.docker.com/engine/reference/commandline/create/). Others have [grappled](https://github.com/moby/moby/issues/21184) with this issue as the docker group id is not fixed or well-known and depends on the host operating system.

Eventually I found the best way to work around this issue with Azure Pipelines was to do the following:
- [Install sudo](https://github.com/gitfool/cake-docker/blob/master/Dockerfile#L4) into my builder container
  - not installed by default in the base Ubuntu Bionic container and `su -c` requires a terminal
- Add a separate build step to [BoardGameGeek.Dungeon/azure-pipelines.yml](https://github.com/gitfool/BoardGameGeek.Dungeon/blob/master/azure-pipelines.yml#L23-L24) to:
  - Use `stat` to read the group id from the mounted `/var/run/docker.sock`
  - Use `sudo groupadd` to create the docker group with the read group id
  - Use `sudo usermod` to add the executing user to this group

The subsequent Cake build step then [successfully](https://dev.azure.com/gitfool/BoardGameGeek.Dungeon/_build/results?buildId=103) runs docker as a non-root user! 😅

**Comment by gitfool** [comment]
@TingluoHuang the above workaround is not pretty. I might be missing something but wouldn’t this “work out of the box” if the Azure Pipelines agent was changed to use `docker create --group-add docker ...`?

**Comment by TingluoHuang** [comment]
@gitfool when you define the container in your yaml file, you can provider addition options for docker create.
```yaml
- container: ubuntu
    image: ubuntu:16.04
    options: '--group-add docker'
```

**Comment by gitfool** [comment]
Okay, that’s great news and good to know! I’ll try that soon. However, it still feels that, to fall into the pit of success, this should be specified by default by the agent.

**Comment by TingluoHuang** [comment]
@gitfool we try to not modify the original container customer provided when we run `docker create`, plus the `--group-add docker` is not a requirement for customer who don't need to run `docker` command inside the container.

**Comment by gitfool** [comment]
In that case it should be documented how to set up a "docker in docker" scenario for a non-root user.

It's not quite that easy ... yet; I get error [unable to find group docker](https://dev.azure.com/gitfool/BoardGameGeek.Dungeon/_build/results?buildId=113&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=17e788f2-af09-4701-8f13-1dc666f086da&lineStart=82&lineEnd=82&colStart=75&colEnd=102) after adding the options. So the agent image should be modified to create the `docker` group with name `docker` and should probably add the `vsts` user to this group to set the stage.

**Comment by vtbassmatt** [comment]
Hey @gitfool thanks for engaging with us. I'm the product manager for the agent (and other platform parts of Azure Pipelines). Running Docker from within Docker isn't something I want to push people towards by default, which explains why it isn't a native capability. Once you have this working successfully (with our help), I'd like to update our docs so that advanced users don't have to reinvent the wheel.

StackOverflow seems to think that the group [must exist in the image already](https://stackoverflow.com/a/41101828), which we don't control. I don't have any objections to adding the host `vsts` user to `docker`, though I'm not sure when we can get to that work.

**Comment by chrisrpatterson** [comment]
If you have sudo in the container image you could try to run a script that adds the vsts_azpcontainer user to a docker group inside that container and then run your docker commands in a subsequent step.  I think with a new process starting you would get your groups re-evaluated.

**Comment by gitfool** [comment]
@chrisrpatterson yes, that's my current workaround.

**Comment by artparks** [comment]
@gitfool feels like my last 48 hours have pretty much replicated yours in trying to resolve this issue! this thread was a lifesaver to finally stumble across.

i think this should be documented more thoroughly as DinD is a pretty valid use-case here. chances are, if you're looking to run your builds inside containers, you're quite likely to be trying to ship (and therefore build) containers, meaning you need access to docker build/push type commands to be able to run these builds. 

glad it works though!

**Comment by vtbassmatt** [comment]
@bryanmacfarlane this one feels like it's standing in the way of a fully sane Docker experience. When someone frees up from a bigger rock, we can take this one tactically.

**Comment by artparks** [comment]
now that we have this working we're on the brink of a really great CI/CD setup via this. at the moment we're going through all the hassle of running our own agents in aurora/mesos which is a hassle and an overhead for our ops team. 

this will streamline things so much as each project can just maintain a separate Dockerfile (or from a separate repo of common generic environments) that defines its build env and we're good to go.

**Comment by gitfool** [comment]
Once you "dockerize" your build there's no going back, it's so empowering! The only trade-off is that caching sucks so the builds take much longer than they should.

**Comment by TingluoHuang** [comment]
i create a PR #2142 might help this scenario.

**Comment by AviateX14** [comment]
Hey @gitfool, would you be willing to share your pipeline & Dockerfile? I'm facing the same problem at the moment and can't get my head around it :(

**Comment by TingluoHuang** [comment]
the agent has released, the user inside the container should have access to docker daemon without `sudo`, i am going to close this issue for now, please reopen if needed.

**Comment by gitfool** [comment]
@TingluoHuang hacks removed and worked perfectly; thanks!
