### ISSUE TITLE
Hosted VS2017 os Family version

### ISSUE THREAD

**Issue by ntragas** [Microsoft/azure-pipelines-agent#2073]
Hello. We are using the latest Hosted VS2017 agent (2.144.2) to release a .Net app in Azure DevOps. The release succeeds when we specify Os Family to 5 but fails when setting it to 6. with the following error:

BadRequest : The OS family 6 you are trying to deploy is not supported by the SDK package. The SDK package supported OS families:3,4,5,1,2,98,97. Please try to deploy to a different operating system. To do this specify a different osFamily and/or osVersion in your .cscfg file.

**Comment by bryanmacfarlane** [comment]
This appears to be a VS issue, not an agent
