### ISSUE TITLE
azure pipeline checkout Many times

### ISSUE THREAD

**Issue by chenshuai2144** [Microsoft/azure-pipelines-agent#2076]
Every job will perform a checkout and need npm install. I want to share files between jobs.
this is my [yaml](https://github.com/ant-design/ant-design/blob/master/azure-pipelines.yml)
I think this is a waste, and checkout is redundant.
But I didn't find any solution. Or task can use matrix.

**Comment by TingluoHuang** [comment]
@chenshuai2144 you can have `job1` fetch code, npm install, npm build and upload compiled artifacts to server, and have `job2` to `job2` depends on `job1` and download artifacts produced by `job1` and run tests in parallel.
You choose this workflow if your fetch + npm install + compile time is greater than artifact upload + download time.
