### ISSUE TITLE
Feature request: When stopping an agent (./svc.sh stop), let the agent wait for the current job to finish

### ISSUE THREAD

**Issue by jeffrey-opdam** [Microsoft/azure-pipelines-agent#2085]
## Agent Version and Platform
Version of your agent? 2.146.0

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com

## Feature request
We are currently (predictive) autoscaling the agents. When the agents are downscaled, we want the agent to wait with starting the actual 'remove' when the current job has finished.

Suggestion:
- Add a switch to the '.svc.sh stop' command line
- Take the agent offline, so no new jobs get queued for that agent.
- Wait until the agents finishes the job.
- Continue with the 'stop' (launchctl unload) process.

**Comment by TingluoHuang** [comment]
@jeffrey-opdam 
you need to disable the agent from server side first.
Anything on the agent side might have race condition, since it is the server decide whether to send new job to the agent.

**Comment by jeffrey-opdam** [comment]
@tingluohuang that is my step two. Is this something that can be done?

**Comment by TingluoHuang** [comment]
@jeffrey-opdam you can use REST API to disable the agent.

it's a PATCH to `https://xxxx.visualstudio.com/_apis/distributedtask/pools/1/agents/25`
the PATCH body looks like:
```JSON
{
        "id": 25,
	"name": "XXX",
	"enabled": false,
}
```

you can get an example of REST call by F12 browser. :)
![image](https://user-images.githubusercontent.com/1750815/52373270-41a68000-2a28-11e9-87ca-4ebe073c8517.png)

**Comment by bryanmacfarlane** [comment]
Ting is correct, you need to disable from the service before tearing down the agent.
