### ISSUE TITLE
Issue checkout task from Agent Windows version 2.144.2 -> File not found: 'chcp' 

### ISSUE THREAD

**Issue by bertrandpons** [Microsoft/azure-pipelines-agent#2086]
Hi,

From yesterday, I get an error everytime I launch a build with a private agent version for Windows, version vsts-agent-win-x64-2.144.2 or version vsts-agent-win-x64-2.146.0.

![image](https://user-images.githubusercontent.com/26971151/52326868-53693280-29ea-11e9-8b3d-8672899c1af1.png)
****

I don't meet this problem with the version vsts-agent-win-x64-2.144.0

Any idea about this problem?

Thank you

**Comment by TingluoHuang** [comment]
@bertrandpons what's your windows version? try set `agent.retainDefaultEncoding=true` on your definition, that should unblock you.
can you run `where chcp` from a command prompt on your machine?

**Comment by TingluoHuang** [comment]
@damccorm FYI,

**Comment by bertrandpons** [comment]
@TingluoHuang thanks for your reply. It does work with agent.retainDefaultEncoding=true set in the definition. Where does the problem come from, as it suddenly appeared?

When I run where chcp, it returns _INFO: Could not find files for the given pattern(s)._

My windows version is Windows Server 2012 R2 Datacenter.

**Comment by TingluoHuang** [comment]
@bertrandpons what's your `%PATH%` looks like? 
can you run `set PATH`?
`chcp` suppose located un `C:\Windows\System32`

**Comment by TingluoHuang** [comment]
we added a feature in 2.144.2 so it can handle task output encoding better, we try to run `chcp 65001` during your build, but the agent didn't find `chcp` on your machine. :)

**Comment by damccorm** [comment]
Added a PR so that we don't fail in future cases like this.

**Comment by bertrandpons** [comment]
chcp.com is indeed located in C:\Windows\System32. 
Even if I add this location to the %PATH%, it does not change anything. Therefore I will use the workaround meanwhile!

**Comment by bryanmacfarlane** [comment]
We should understand why it doesn't change anything if it's added to the path.  The workaround gets you unblocked and the PR is good but @bertrandpons can you work with us to figure out why?

**Comment by bertrandpons** [comment]
@bryanmacfarlane ok sorry I replied too fast. It works when added to the path.

**Comment by TingluoHuang** [comment]
@bertrandpons i am going to close this issue since the problem has been solved, please reopen if you need more help.

**Comment by bertrandpons** [comment]
Thanks for the support
