### ISSUE TITLE
Docker image for ARM architecture?

### ISSUE THREAD

**Issue by arnvanhoutte** [microsoft/azure-pipelines-agent#2090]
I tried running a vsts build agent with [docker](https://hub.docker.com/r/microsoft/vsts-agent/) on a raspberry pi. There has been ARM support for this in [release 2.141](https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.141.0).

When running the command 

    docker run \
    -e VSTS_ACCOUNT=<name> \
    -e VSTS_TOKEN=<pat> \
    -it microsoft/vsts-agent
 I get an error saying 
>standard_init_linux.go:207: exec user process caused "exec format error".

 Upon researching it seems that this is because of the wrong architecture. Is there a way to run or build this as ARM?

**Comment by TingluoHuang** [comment]
@arnvanhoutte 
You need to build your own image with https://vstsagentpackage.azureedge.net/agent/2.146.0/vsts-agent-linux-arm-2.146.0.tar.gz
i think https://hub.docker.com/r/microsoft/vsts-agent/ only has agent built on Linux-x64

**Comment by arnvanhoutte** [comment]
Yes at the moment manual build seems to be the way to go. However I do believe it could be useful to create docker images for other architectures so we can containerize our agents.

**Comment by TingluoHuang** [comment]
@vtbassmatt i think customer is asking about the vsts-agent docker registry.

**Comment by NNTin** [comment]
+1
All the images listed [here](https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent) are for amd64 architecture. Please include other architectures as well.  
The RPi has arm architecture.

**Comment by MrGlaurung** [comment]
Are there any plans to include ARM building in the standard docker component soon??

**Comment by vtbassmatt** [comment]
We aren't planning to ship our own agent Docker images anymore. We've instead documented the process by which you can build your own: http://docs.microsoft.com/azure/devops/pipelines/agents/docker

(In full disclosure, we've been getting some feedback about this decision, and are open to reconsidering. It isn't clear what benefit there is in shipping an image which almost certainly won't have all the tools you need, or be the right base OS, or whatever.)

**Comment by MrGlaurung** [comment]
Thank you very much for getting by to me.
Have a great day.

Mvh
Anders Lidén

Caora AB
Kronhusgatan 11
411 05 Göteborg

E-post: anders.liden@caora.se <3D"mailto:anders.liden@caora.se">
Mobil: 0735 - 34 10 11

------ Original Message ------
