### ISSUE TITLE
Nuget cache is not working

### ISSUE THREAD

**Issue by alesdvorakcz** [Microsoft/azure-pipelines-agent#2096]
I am using self hosted agent from docker image "microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard". When my dotnet solution is builded nuget packages are downloaded. 
But it looks like there is no cache for next build.

In agent log I can see:
```
2019-02-10T15:16:35.4660517Z   Restoring packages for /home/vsts/work/1/s/Sources/....csproj...
2019-02-10T15:16:40.7118180Z   Installing RabbitMQ.Client 5.1.0.
2019-02-10T15:16:40.7119377Z   Installing Sentry.Protocol 1.0.3.
2019-02-10T15:16:40.7120829Z   Installing Newtonsoft.Json 10.0.2.
...
```
It takes around 2minutes. Is it intended behavior or not? Or should I "turn on" nuget cache somehow?
In documentation I found nuget uses ~/.nuget/packages as a location where downloaded packages are installed. But when I connect to my agent there is no ~/.nuget folder.

**Comment by TingluoHuang** [comment]
@alesdvorakcz does the same container instance up and run those 2 builds?
after the first build finish, can you `docker exec -it <SHA> bash` to your running container and check what's under `~/,nuget`?

**Comment by alesdvorakcz** [comment]
Yes its the same container and it builded multiple builds. after successful build I connected to container and there is no ~/.nuget folder, thats what is weird

**Comment by TingluoHuang** [comment]
@alesdvorakcz can you try run `dotnet nuget locals all --list`? base on https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders#viewing-folder-locations

also, try to `printenv|sort` see whether there is any variable that might redirect nuget cache to somewhere else.

**Comment by alesdvorakcz** [comment]
`dotnet nuget locals all --list` gives me this output:
```
info : http-cache: /root/.local/share/NuGet/v3-cache
info : global-packages: /root/.nuget/packages/
info : temp: /tmp/NuGetScratch
info : plugins-cache: /root/.local/share/NuGet/plugins-cache
```

Then I listed content of /root/.nuget:
- NuGet
--NuGet.Config

That is all. no .nuget/packages folder
`printenv|sort` looks like there is nothing related to nuget

**Comment by alesdvorakcz** [comment]
Oh I am sorry, its my fault. I use yaml pipeline and I did not specified name of my pool (I only selected pool in graphic wizard)
![image](https://user-images.githubusercontent.com/1890782/52633031-79e40d80-2ec3-11e9-9d9b-f98cb13efd3b.png)

This field is for some reason ignored. I added name to yaml file and not itw working:
![image](https://user-images.githubusercontent.com/1890782/52632977-4ef9b980-2ec3-11e9-8d70-2a414d588fef.png)

**Comment by TingluoHuang** [comment]
@alesdvorakcz glad you unblock,you might want to remove the `vmImage: "Ubuntu-16.04"` from your yaml file.
