### ISSUE TITLE
Windows Agent running a command in a linux container

### ISSUE THREAD

**Issue by akash3456** [Microsoft/azure-pipelines-agent#2098]
i have a windows build pipeline which is switching to a Linux container mode through the command line and when i attempted to enter the Linux container interactively using docker exec I seem to get this message - 

the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

I am using a windows build agent.

**Comment by TingluoHuang** [comment]
@akash3456 what `docker exec` command you use, `docker exec -it` requires you to have a interactive TTY. When agent running your pipeline job, it doesn't have TTY.

**Comment by akash3456** [comment]
Docker command I run is: 

Docker exec -it containername bash

**Comment by akash3456** [comment]
Docker exec -it containername bash

**Comment by TingluoHuang** [comment]
@akash3456 why you need `-it` in a CI system? can you run your bash command without `-it`? :)

**Comment by akash3456** [comment]
I’ll try it

**Comment by akash3456** [comment]
it worked but I don't understand why -it should be redundant. could you please explain?

**Comment by TingluoHuang** [comment]
@akash3456  when you pass `-it` to `docker exec`, docker will expect it's on a console/terminal. Base on your agent's configuration, the agent might running as systemd service process that doesn't have a console/terminal at all. So `docker` raise error when you tell it `-it` but it doesn't find the console/terminal.

**Comment by akash3456** [comment]
so is this right then, if I configured the build agent to run as a windows service I would not be able to execute command line arguments interactively through a shell?

**Comment by TingluoHuang** [comment]
@akash3456 I think this is by design, process that launched by windows service will not have interactive session. it also seems weird you need interactive session in a CI system unless you are doing UI testing.
