### ISSUE TITLE
Support custom variables from Builds in Releases

### ISSUE THREAD

**Issue by mbrancato** [Microsoft/azure-pipelines-agent#2101]
Currently, if custom variables are created in the build process, they are not available in the release process. My use case here is really version / container tags. I want the code to define the version and tag for the internal process and image updates.

e.g. the following cannot be reference in a docker build / push task in Release:

```yaml
variables:
  version: 2.0
```

**Comment by bryanmacfarlane** [comment]
Not so much an agent issue in this repo.  Developer community might be a better place to report since that would be a feature in the release service.

**Comment by mbrancato** [comment]
@bryanmacfarlane is there a different repo that would be good place to request this using GitHub issues? I'm not sure what the "developer community" is if not here. I can try asking our EA account team, but they have apparently been MIA for over a month. Since this is the repo for the agent that performs both build and release, per the README, I figured I could start here.

**Comment by bryanmacfarlane** [comment]
https://developercommunity.visualstudio.com/spaces/21/index.html

The service is not OSS
