### ISSUE TITLE
##[error]git : Switched to a new branch 'master'

### ISSUE THREAD

**Issue by wangfeng19890** [Microsoft/azure-pipelines-agent#2103]
## Agent Version and Platform
Agent Version: **2.146.0**
Platform: **Windows Server 2019**

## Azure DevOps Type and Version
Azure DevOps Type:
**dev.azure.com**

Organization name:
**https://dev.azure.com/CarbonDevOps**

## What's not working?

![image](https://user-images.githubusercontent.com/22190701/52771486-fb2cd300-3070-11e9-88cc-789a326ed471.png)

**Comment by TingluoHuang** [comment]
@wangfeng19890 makes share you have `Fail on standard error` unchecked, since `git.exe` print out status update to standard error.
![image](https://user-images.githubusercontent.com/1750815/52790817-88eacd00-3035-11e9-86f5-5f13376b5800.png)

**Comment by wangfeng19890** [comment]
@TingluoHuang After I make it checked, I got detailed log and it is attached.
It looks like a powershell error.


[log_5_209.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2867510/log_5_209.zip)

**Comment by TingluoHuang** [comment]
@wangfeng19890 makes sure you have `Fail on standard error` **unchecked**

**Comment by wangfeng19890** [comment]
@TingluoHuang Yes, unchecked. But same error.

![image](https://user-images.githubusercontent.com/22190701/52830817-3ed51a80-310d-11e9-92ad-5bd3fcfb59a6.png)

**Comment by TingluoHuang** [comment]
can you share the log?

**Comment by wangfeng19890** [comment]
[log_5_209.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2867583/log_5_209.zip)
This is the log.

**Comment by TingluoHuang** [comment]
that's the log for build 209, where is log for 210?

**Comment by wangfeng19890** [comment]
Sorry.
[log_5_210.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2867592/log_5_210.zip)

**Comment by TingluoHuang** [comment]
@wangfeng19890 did you provide credential when executing `git pull`?
i think `git checkout master` succeed but `git pull` failed.

**Comment by wangfeng19890** [comment]
![image](https://user-images.githubusercontent.com/22190701/52832447-86f73b80-3113-11e9-8164-bd5e35ea127e.png)

you mean this one?

**Comment by wangfeng19890** [comment]
@TingluoHuang I have the same agent installed on my PC, it is running correctly. But when I switch it to the agent installed on server, the error happens.

**Comment by TingluoHuang** [comment]
Which agent pool you are using that have this problem?

**Comment by wangfeng19890** [comment]
I create a pool and it is called CarbonAgentPool

**Comment by TingluoHuang** [comment]
what's the version of powershell you have?

**Comment by wangfeng19890** [comment]
![image](https://user-images.githubusercontent.com/22190701/52836610-3f2ddf80-3126-11e9-9ad3-1e4b00c3cd21.png)

**Comment by wangfeng19890** [comment]
On the server, the version is:
![image](https://user-images.githubusercontent.com/22190701/52836745-d7c45f80-3126-11e9-8b3c-40fc89575bf4.png)

**Comment by TingluoHuang** [comment]
The version on VS2017 hosted pool is 5.1.14393.2636 and i can't repro your issue with it.
2019-02-15T13:48:29.3142524Z Name             : ConsoleHost
2019-02-15T13:48:29.3143190Z Version          : 5.1.14393.2636
2019-02-15T13:48:29.3144015Z InstanceId       : 8f9940cc-4bf5-4c5f-b2a1-1afbf0eec39e
2019-02-15T13:48:29.3144591Z UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
2019-02-15T13:48:29.3145371Z CurrentCulture   : en-US
2019-02-15T13:48:29.3146719Z CurrentUICulture : en-US
2019-02-15T13:48:29.3147357Z PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
2019-02-15T13:48:29.3148512Z DebuggerEnabled  : True
2019-02-15T13:48:29.3148624Z IsRunspacePushed : False
2019-02-15T13:48:29.3148687Z Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by wangfeng19890** [comment]
@TingluoHuang Yes, I installed the same agent on my laptop and it is working well without this issue.
But it is not working on Server side, so I hope we can find out the root cause and fix it.
Could you please help me? I have reinstalled the agent on server but no luck.

**Comment by TingluoHuang** [comment]
@wangfeng19890 i don't think your issue is caused by the agent, might be something about powershell or environment.
the command that agent runs:
```
"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\GeneratedScript.ps1'"
```

The generate script looks like:
```PS1
$ErrorActionPreference = 'stop'
$host
git checkout master
git pull
if (!(Test-Path -LiteralPath variable:\LASTEXITCODE)) {
    Write-Host '##vso[task.debug]$LASTEXITCODE is not set.'
} else {
    Write-Host ('##vso[task.debug]$LASTEXITCODE: {0}' -f $LASTEXITCODE)
    exit $LASTEXITCODE
}
```

Can you try create the generated file yourself on the the build server that has the problem, and run powershell command line directly see whether powershell can return cleanly?
