### ISSUE TITLE
update to Maven 3.6

### ISSUE THREAD

**Issue by cforce** [Microsoft/azure-pipelines-agent#2106]
Currently the vsts agent only offers old Maven release 3.3.9
https://vstsagentpackage.azureedge.net/agent/2.146.0/vsts-agent-win-x86-2.146.0.zip
We are not able build of Spring boot applications which seems to use features from this maven release.

see https://maven.apache.org/download.cgi

**Comment by TingluoHuang** [comment]
@cforce https://github.com/Microsoft/azure-pipelines-image-generation might be a better place for your question.
this repository is for the agent executable, the agent doesn't offer any tools you need during your pipeline jobs, those tools are part of the VM image the agent runs on.

**Comment by cforce** [comment]
Tx,  i will move my request there
