### ISSUE TITLE
Git fetch failed with exit code: 128

### ISSUE THREAD

**Issue by markofranjic** [Microsoft/azure-pipelines-agent#2116]
## Having issue with software on Hosted Agent?
Hi Team, I have problem with Hosted Agent. When I tried to build solution I got error on Get Sources Job
2019-02-20T05:56:43.5708405Z fatal: The remote end hung up unexpectedly
2019-02-20T05:56:43.5726175Z error: RPC failed; curl 52 Empty reply from server
2019-02-20T05:56:43.7161877Z ##[error]Git fetch failed with exit code: 128
2019-02-20T05:56:43.7174861Z ##[section]Finishing: Get Sources

On other project build works as Excepted, with only one I have problem.

## Have you tried troubleshooting?
I have added git config --global http.postBuffer 157286400 sslVerify=false and nothing happend.

## Agent Version and Platform
Agent: 2.120.2
VSTS: 16.131.27701.1

OS of the machine running the agent? Windows 10

If on-premises, which release? 
TFS 2018.2

## What's not working?
Please include error messages and screenshots.[
_
![2019-02-20_7-18-49](https://user-images.githubusercontent.com/15909773/53070785-88907d00-34e0-11e9-9216-40207f556a62.png)

## Agent and Worker's Diagnostic Logs
[Agent_20190220-055242-utc.log](https://github.com/Microsoft/azure-pipelines-agent/files/2883273/Agent_20190220-055242-utc.log)
[Worker_20190220-055542-utc.log](https://github.com/Microsoft/azure-pipelines-agent/files/2883274/Worker_20190220-055542-utc.log)

**Comment by TingluoHuang** [comment]
@markofranjic i don't think this is a problem about the agent, the agent invoke `git.exe` and it returns 128.
check your TFS AT's event log, see whether there is any exceptions on server side.

**Comment by markofranjic** [comment]
> @markofranjic i don't think this is a problem about the agent, the agent invoke `git.exe` and it returns 128.
> check your TFS AT's event log, see whether there is any exceptions on server side.

Hi Huang,

I don't see any error logs about TFS. I see only informations logs like this
TF200030: Team Foundation Server completed group synchronization for the following group: Sync Tree.

Incremental sync (current cycle start time (UTC) 20.2.2019. 16:00:11, cycle duration 1.00:00:00, number of syncs per cycle 24).

Application Domain: TfsJobAgent.exe
Service Host:       f3a91bc8-f499-4f1f-a93a-be4146db3794 (TEAM FOUNDATION)

I don't understand why Get Source works on other repository but on one repository I got 128 code error.

**Comment by TingluoHuang** [comment]
@markofranjic have you retry the build? are you getting 128 all the time for this repository?

**Comment by markofranjic** [comment]
> @markofranjic have you retry the build? are you getting 128 all the time for this repository?

Yes I have retry build many times but not success. When I change repository, other project build works as excepted.  

Only one project have that problem

**Comment by TingluoHuang** [comment]
@markofranjic make sure you check the TFS event log.
![image](https://user-images.githubusercontent.com/1750815/53107622-63613600-3503-11e9-92ab-a820e8986bc2.png)

I think there must be some server problems, as the agent just use `git.exe` to fetch the repository.
if you can't find any useful error in the TFS event log, you might want to open issue at https://developercommunity.visualstudio.com/spaces/22/index.html or ask for TFS customer support.

**Comment by markofranjic** [comment]
![2019-02-20_17-38-48](https://user-images.githubusercontent.com/15909773/53107977-81945980-3536-11e9-9a07-c267391e49c1.png)
Unfortunately I see only logs from 2015, I will open issues to developer community

**Comment by TingluoHuang** [comment]
@markofranjic not that folder, 3 lines below on the left tree.

`Microsoft-Team Foundations Server\Debug`

**Comment by markofranjic** [comment]
I have checked that logs and I can see any logs which I can reference with exists problem wit build
[Debug.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2885710/Debug.zip)

**Comment by TingluoHuang** [comment]
@markofranjic the event log has info after `2019-02-20T08:23:45`, the build log you shared is `2019-02-20T05:55:45`, have you tried another build after `2019-02-20T08:23:45 UTC`? i need some timestamp so i can link the event log and the agent log. :)

**Comment by markofranjic** [comment]
Hi Huang,

I have found error log. I have started build and I got this`
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Team Foundation Server" Guid="{80761876-6844-47D5-8106-F8ED2AA8687B}" /> 
  <EventID>0</EventID> 
  <Version>5</Version> 
  <Level>2</Level> 
  <Task>1</Task> 
  <Opcode>10</Opcode> 
  <Keywords>0x8000000000000001</Keywords> 
  <TimeCreated SystemTime="2019-02-20T17:28:40.682719000Z" /> 
  <EventRecordID>75114403</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="2536" ThreadID="2896" /> 
  <Channel>Microsoft-Team Foundation Server/Debug</Channel> 
  <Computer></Computer> 
  <Security UserID="S-1-5-20" /> 
  </System>
- <UserData>
- <Info TraceId="{00000001-0001-0001-0000-000000000000}" xmlns="http://schemas.microsoft.com/TeamFoundation/2010/Framework">
  <Tracepoint>261053255</Tracepoint> 
  <ServiceHost>{00000000-0000-0000-0000-000000000000}</ServiceHost> 
  <ContextId>0</ContextId> 
  <ProcessName>w3wp</ProcessName> 
  <Username /> 
  <VSID>{00000000-0000-0000-0000-000000000000}</VSID> 
  <CUID>{00000000-0000-0000-0000-000000000000}</CUID> 
  <TenantId>{00000000-0000-0000-0000-000000000000}</TenantId> 
  <ProviderId>{00000000-0000-0000-0000-000000000000}</ProviderId> 
  <Service /> 
  <Method /> 
  <Area>PluginLoader</Area> 
  <Layer>DisposableCollection</Layer> 
  <UserAgent /> 
  <Uri /> 
  <Path /> 
  <UniqueIdentifier>{00000000-0000-0000-0000-000000000000}</UniqueIdentifier> 
  <UserDefined /> 
  <ExceptionType /> 
  <Message>DisposableCollection<Microsoft.TeamFoundation.Build2.Server.IBuildSourceProvider> was not disposed!</Message> 
  <E2EID>{00000000-0000-0000-0000-000000000000}</E2EID> 
  </Info>
  </UserData>
  </Event>`

**Comment by TingluoHuang** [comment]
i am not sure that the right error, i would expect there are some message around `git` area.
do you might send me the log (build and event log)?

**Comment by markofranjic** [comment]
You can find enclosed logs
[logs_2233.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2885811/logs_2233.zip)
[Debug.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2885812/Debug.zip)

Time From: 20.02.2019 18:32.51
Time To: 20.02.2019 18:35.00

UTC+1

**Comment by TingluoHuang** [comment]
the event log has everything <= `2019-02-20T17:13:28.391762000Z`, the build log shows the problem happened at `2019-02-20T17:28:54.5037277Z`, you might want to re-save the log. :)

**Comment by markofranjic** [comment]
Huang Thank you,
You thing that 
 <HostId>{BE1A6908-4BA7-474A-9C10-99630450EC2B}</HostId> 
  <Application>Authentication</Application> 
  <Command>FrameworkBasicAuthenticationModule.OnEndRequest</Command> 
  <Status>-1</Status> 
  <ExecutionCount>1</ExecutionCount> 
  <StartTime>2019-02-20T17:13:24.329285800Z</StartTime> 
  <ExecutionTime>9454</ExecutionTime> 
  <UserAgent>JGit/3.7.0.201502260915-r</UserAgent> 
  **<ExceptionType>UnauthorizedRequestException</ExceptionType>** 
  <VSID>{00000000-0000-0000-0000-000000000000}</VSID> 
  <TimeToFirstPage>9454</TimeToFirstPage> 
  <ActivityStatus>1</ActivityStatus> 
  <IsExceptionExpected>false</IsExceptionExpected> 
  <Feature>Identity</Feature> 
  <HostType>4</HostType> 
  <ParentHostId>{F3A91BC8-F499-4F1F-A93A-BE4146DB3794}</ParentHostId> 
  <AnonymousIdentifier /> 
  <CUID>{00000000-0000-0000-0000-000000000000}</CUID> 
  <TenantId>{00000000-0000-0000-0000-000000000000}</TenantId> 
  </ActivityLogCore>
Unauthorized is problem?

How I can authorize agent, because I have installed agent by standard procedure.
Why other project can build?

Thank you

**Comment by TingluoHuang** [comment]
this is not the right error either, the error is coming form `JGit/3.7.0.201502260915-r` which is not the agent.

**Comment by markofranjic** [comment]
Sorry, above record is form jGit.
Did you think of beyond error?

If yes? What can I do that resolve this problem. I'm new in TFS and every help I appreciate 

JGit/3.7.0.201502260915-r
UnauthorizedRequestException
TF400813: Resource not available for anonymous access. Client authentication required.

**Comment by TingluoHuang** [comment]
@markofranjic can you send me a new copy of your event log?

**Comment by markofranjic** [comment]
I have enclosed logs
[Debug.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2886119/Debug.zip)

I have run build at 20.05:31 UTC+1
And failed at 20:05:53 UTC+1.

Many thanks for your help

**Comment by markofranjic** [comment]
Sorry, enclosed updated logs
[Debug.zip](https://github.com/Microsoft/azure-pipelines-agent/files/2886144/Debug.zip)

**Comment by TingluoHuang** [comment]
I find the error, but not sure what's that means.
I will find someone to help me take a look, if i can find an answer to you, you might need to post the question to developer community.
![image](https://user-images.githubusercontent.com/1750815/53118851-0cb42600-351c-11e9-8a6f-70737a9d0e2d.png)

**Comment by markofranjic** [comment]
Hi Huang,

Thank you very much for your help. I have posted question to developer community.

Regards,
Marko

**Comment by congyiwu** [comment]
It looks like the developer community issue is https://developercommunity.visualstudio.com/content/problem/464060/git-fetch-failed-with-exit-code-128-2.html

We'll handle it there.

**Comment by congyiwu** [comment]
Also, @markofranjic you wrote:
> I have added git config --global http.postBuffer 157286400 sslVerify=false and nothing happend.

Please don't forget to unset both of those settings ASAP.
sslVerify=false leaves you vulnerable to MITM attacks.
http.postBuffer is almost always useless nowadays.  See https://docs.microsoft.com/en-us/azure/devops/repos/git/rpc-failures-http-postbuffer?view=azure-devops

**Comment by TingluoHuang** [comment]
i am going to close this issue here since it's not scope to a problem within the agent.

**Comment by trytocatchme** [comment]
I would say is very rare problem and occurs occasionally. I suggest to change the agent and run pipeline once again. I know that is not the best way to fix it but it works.

your pipline file
pool:
  name: agent1_AgentPools
  #name: agent2_AgentPools repleace to this one when problem occurs

Ofcourse it will work only when you have more than 2 agents.
