### ISSUE TITLE
GIT does not bring all references where agent is running

### ISSUE THREAD

**Issue by OmkarPathak** [Microsoft/azure-pipelines-agent#2120]
## Agent Version and Platform
Self hosted Agent 2.140.2 on RHEL 7.5

## Problem
We are trying to automate the Pull Request generation based on `git diff`. However, when we try to checkout from a specific commit, we get the following error:
```
fatal: ambiguous argument '<commit_id>': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

```

On checking the `git log` we do not see the specified <commit_id>. After closely inspecting the logs, we found that certain logs where not fetched by the agent during checkout. We tried the same by explicitly firing the `git pull origin <branch_name>` but weren't able to fetch missing references. Is there any option to be specified on the agent side. to fetch all the commits?

**Comment by TingluoHuang** [comment]
@OmkarPathak which branch you are trying to fetch? does it belongs to `origin`?

**Comment by OmkarPathak** [comment]
@TingluoHuang Yes it belongs to `origin`

**Comment by TingluoHuang** [comment]
@OmkarPathak can you share a full build log? include what git command the agent has run, and what git command you are trying to run.

**Comment by OmkarPathak** [comment]
Solved the issue. I just enabled the `Accept the OAuth` token in build option.
