### ISSUE TITLE
Agent.WorkFolder not writable from build running in container

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/azure-pipelines-agent#2122]
## Agent Version and Platform
Version of your agent? 2.147.1

Linux (Ubuntu 18.04 container image with .NET Core running in Hosted Ubuntu build agent)

## Azure DevOps Type and Version
dev.azure.com 

https://rlsolutions.visualstudio.com

## What's not working?
Code in my build script is trying to create a file in the directory resolved from `Agent.WorkFolder`, but is failing with 'access denied'.

eg.

```
##[debug]Processed: ##vso[task.logdetail finishtime=02/25/2019 05:00:15;progress=100;result=Succeeded;id=3f293bfc-27b1-42cf-af56-139f503340c8;]update
##[debug]Processed: ##vso[task.logdetail finishtime=02/25/2019 05:00:15;progress=100;state=Completed;result=Succeeded;id=0ffa0556-53ab-4a01-8f8a-c7dd226e3a15;]update
Error: One or more errors occurred. (Access to the path "/__w/tasksummary.md" is denied.)
	Access to the path "/__w/tasksummary.md" is denied.
##[debug]Exit code 1 received from tool '/bin/bash'
##[debug]STDIO streams have closed for tool '/bin/bash'
```

This code worked correctly when run directly on the hosted agent (before we switched to containers).

I'm unclear why the `/__w` directory would not be writable by the build script. Should build scripts use another location (eg. `Build.StagingDirectory` etc)?

**Comment by flcdrg** [comment]
The actual code that is run which is trying to create a file is from https://github.com/agc93/Cake.BuildSystems.Module/blob/develop/src/Cake.TFBuild.Module/TFBuildReportPrinter.cs#L73

**Comment by TingluoHuang** [comment]
@flcdrg `Build.StagingDirectory` should work. basically, you need to use a folder that under `Agent.BuildDirectory`, since that's the root folder we mapped into container. We didn't map in the entire `Agent.WorkFolder`.

**Comment by flcdrg** [comment]
I might submit a docs update for WorkFolder if that's the case.

Thanks for the clarification
