### ISSUE TITLE
How Azure Devops Analyzes your repository to suggest a compatible template?

### ISSUE THREAD

**Issue by dreaminplus** [Microsoft/azure-pipelines-agent#2127]
Hi, recently Azure Devops could recommend the template when user defines its own pipeline.
But I cannot find the source code from this repository,  I found the wrong position?
If I am wrong, could you help me out how to get the source position?

**Comment by TingluoHuang** [comment]
@dreaminplus that part of code might not be open sourced, you can report any issue you found to [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html).
