### ISSUE TITLE
Windows: Registration script does not work behind proxy

### ISSUE THREAD

**Issue by geofflamrock** [Microsoft/azure-pipelines-agent#2133]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting) Yes

## Agent Version and Platform
Version of your agent? N/A as issue is prior to agent running

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
Azure DevOps: https://dev.azure.com/blueshift

## What's not working?
Hi,

The registration script for powershell in Windows that gets shown in a deployment group doesn't always work when the user is behind a proxy, it detects the proxy ok but the download of the agent zip file fails as the credentials are not set properly on the proxy.

Adding `$WebClient.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials` to the script seems to make it work.

I was redirected from https://github.com/MicrosoftDocs/vsts-docs/issues/2731 to raise here.

If this would be able to be fixed in the registration script that would be great.

Thanks :)

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

N/A as issue is prior to agent running

**Comment by TingluoHuang** [comment]
@chshrikh can you help us take this? i think customer is talking about deployment group config script.
![image](https://user-images.githubusercontent.com/1750815/53705018-73c0bd00-3def-11e9-927a-2db71e8fab75.png)

**Comment by TingluoHuang** [comment]
@geofflamrock i think the script is for convenience, however with advance scenario like proxy/certificate the script might not works well.
you might want to check the following doc for run agent behind proxy 
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows

**Comment by geofflamrock** [comment]
@TingluoHuang thanks for responding, yes the screenshot you've added is where the registration script I am referencing is coming from, sorry I should have included a screenshot. 

Thanks for the proxy documentation link, we have used that in the past to get an agent running behind a proxy in certain sites.

I agree that the agent could be installed by downloading the binaries and copying across, bypassing the proxy issue in this script, however this script is the entry point when it comes to release pipelines/deployment groups as separate from agent pools for build pipelines. There is no download agent link on this page, this script is the thing that users would run and so it would be great if it handled this proxy situation properly.

Thanks for your assistance with this, please let me know if I can provide any further information.

**Comment by geofflamrock** [comment]
@TingluoHuang would you have any update on this? Thanks.

**Comment by RoopeshNair** [comment]
@geofflamrock - It is the same agent for both build/release and deployment groups. i.e., the agent that you download from agent pools page can be used to register with deployment groups as well. 
We hear your feedback on the script being entry point. However, we would like to keep the script minimalistic given that it can be customized to suit varied requirements. If you still feel strongly about it, please take a moment and add your suggestions [here](https://developercommunity.visualstudio.com/spaces/21/index.html). It will help us to prioritize appropriately. Thank you

**Comment by geofflamrock** [comment]
Ok thanks @RoopeshNair I think we can close this out, like you mentioned the script can be customized which is what we've done internally.

**Comment by SiulOgait** [comment]
Hi can you let us know where on the deployment group config script you add the "$WebClient.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials" that seems to make it work?

Thanks
