### ISSUE TITLE
Issue with colors on logs and character escapes

### ISSUE THREAD

**Issue by konpikwastaken** [Microsoft/azure-pipelines-agent#2140]
## Agent Version and Platform
Windows

## Azure DevOps Type and Version
Hosted VS
https://microsoft.visualstudio.com

## What's not working?
- We are running `yarn jest --colors` and while we do see colors, we also see a number of characters not being unescaped.

Actual output:
```
[packagename]/build-scripts: ================================================================================
[packagename]&#x2F;build-scripts: ‌Snapshot Summary‌
[packagename]&#x2F;build-scripts: ‌ › 1 snapshot failed‌ from 1 test suite. ‌Inspect your code changes or run `yarn run jest -u` to update them.‌
[packagename]&#x2F;build-scripts: ‌Test Suites: ‌1 failed‌, ‌3 passed‌, 4 total‌
[packagename]&#x2F;build-scripts: ‌Tests:       ‌1 failed‌, ‌1 skipped‌, ‌11 passed‌, 13 total‌
[packagename]&#x2F;build-scripts: ‌Snapshots:   ‌1 failed‌, ‌5 passed‌, 6 total‌
[packagename]&#x2F;build-scripts: ‌Time:‌        57.322s‌
[packagename]&#x2F;build-scripts: ‌error‌ Command failed with exit code 1.‌
[packagename]&#x2F;build-scripts: ‌info‌ Visit ‌https:&#x2F;&#x2F;yarnpkg.com&#x2F;en&#x2F;docs&#x2F;cli&#x2F;run‌ for documentation about this command.‌
[packagename]&#x2F;build-scripts: ‌error‌ Command failed with exit code 1.‌
[packagename]&#x2F;build-scripts: ‌info‌ Visit ‌https:&#x2F;&#x2F;yarnpkg.com&#x2F;en&#x2F;docs&#x2F;cli&#x2F;run‌ for documentation about this command.‌
[packagename]&#x2F;cli: ‌ PASS ‌ ‌__tests__&#x2F;‌utils.test.ts‌ (‌91.044s‌)‌
[packagename]&#x2F;cli: ‌ PASS ‌ ‌__tests__&#x2F;‌validation-helpers.test.ts‌ (‌6.074s‌)‌
```

Related: #1569

**Comment by TingluoHuang** [comment]
@konpikwastaken the agent just redirect STDOUT/STDERR from whatever tool you invoke, so this might be a UI problem.

@yaananth FYI,

**Comment by olafurpg** [comment]
I am experiencing the same issue, colors render correctly but `/` characters render as `&#x2F`. The screenshot below is from the following public build https://dev.azure.com/olafurpg/Metals/_build/results?buildId=51

<img width="528" alt="Screenshot 2019-03-09 at 04 43 54" src="https://user-images.githubusercontent.com/1408093/54065815-fef1e680-4225-11e9-89ca-5ee1efadbcce.png">

In my iTerm macOS console, the `/` characters render as expected

<img width="366" alt="Screenshot 2019-03-09 at 04 45 32" src="https://user-images.githubusercontent.com/1408093/54065830-411b2800-4226-11e9-82d1-697db0e1a573.png">

**Comment by yaananth** [comment]
This a known limitation with escape codes, we have a replacement view that will address this and is in internal preview, will be out soon. 
Sorry for the limitations here with ansii code support.

**Comment by konpikwastaken** [comment]
Thanks. For what it's worth the console output locally in vscode prints colors correctly, with ecsped characters shown as expected.

Can this issue be kept open and closed when the new view is released?

**Comment by yaananth** [comment]
this isn't agent issue, you can submit feedback https://developercommunity.visualstudio.com/topics/Azure+DevOps.html if you would like to track.

**Comment by octogonz** [comment]
Today I noticed that if you enable the "Multi-stage pipelines" preview feature, then colors are displayed properly.  (In Azure DevOps, click your profile --> "..." --> "Preview features".)   

Lack of colors support was a major annoyance for Azure DevOps (compared to other CI systems), so it's really awesome that this is finally getting solved!
