### ISSUE TITLE
Create a new working directory per build id (Self-hosted agent)

### ISSUE THREAD

**Issue by peters** [Microsoft/azure-pipelines-agent#2145]
Is it possible to create a new build directory that matches current build id? The `vsts-agent` is failing because it cannot checkout git repository due to the following error:

![image](https://user-images.githubusercontent.com/869/54021089-a3751980-418f-11e9-81bf-2a63c660ae39.png)

Since we are using docker on Windows (pre-built image) we don't necessarily benefit from a previously "cached" build anyway.

**Comment by TingluoHuang** [comment]
@peters we might have a feature that will ship in next agent release allow you doing this. i would also want to understand how did you get into this permission problem, can you share more information about your setup?

**Comment by peters** [comment]
@TingluoHuang That is great news! The permission issue happens because an executable from a previous test run segfaulted (ghost process, i.e. the process has crashed but the kernel still keep it around). This project has unit tests attempting to `fork` a new process in order to test input command line parameters. So if one of the forked executables segfaults (crashes) and then on the next build, `vsts-agent` attempts to prune the build directory (Ref: "Clean directory" setting on Azure pipeline website) the file cannot be deleted because of `The process cannot access the file 'F:\vsts-agent\_work\1\s\build\native\Windows\win-msvs-15-x64\Release\Snap.CoreRun.Tests\Release\042a1a4a-5c63-4de9-84d2-ced70dd2b3e0\app-25.0.0' because it is being used by another process.`

**Comment by peters** [comment]
@TingluoHuang Is there a preview release available with this feature? :)

**Comment by TingluoHuang** [comment]
@peters not yet, the agent suppose to clean up all staled process at the end of each job, you said you also using docker on Windows, how does that impact on this problem?

**Comment by peters** [comment]
@TingluoHuang Ahh :crab:  The docker container is only used for building the native components and then returns to the host OS to run the actual unit tests. Docker does not impact this problem and I only mentioned it to shed some light upon why we would like a new build directory per build.

**Comment by TingluoHuang** [comment]
@peters the agent will set a special environment variable when it run a job, ex: VSTS_PROCESS_ID=GUID, then any child process launched in your job will has that environment variable. at the end of the build, the agent will try find all processes that has that environment variable and kill them.
do you happen to have the build log and agent log for the build that cause the segfault?

**Comment by peters** [comment]
@TingluoHuang I understand. I think I've found the root cause, I logged onto the build agent and the folder the `vsts-agent` was attempting to delete was open in `Windows Explorer`. So I guess my theory about orphaned child processes was probably incorrect:

![image](https://user-images.githubusercontent.com/869/54037396-59575c80-41be-11e9-9bb0-b402b5d1cafc.png)

Closing `Windows Explorer` solved the problem :sob: 

Build log: https://dev.azure.com/youpark/snapx/_build/results?buildId=188

**Comment by TingluoHuang** [comment]
@peters do you happen to know how the file explorer get opened, by some UI test?

**Comment by peters** [comment]
@TingluoHuang No, it only spawns console processes. The `vsts-agent` does not run as a privileged service. I'm embarrassed to say but this was purely a PEBCAC on my end. I probably logged onto the build agent in order to investigate a few failing unit tests and forgot to close the directory.

**Comment by TingluoHuang** [comment]
@peters that's fine. glad we figure this out to unblock you. 😄 
feel free to close the issue once you get everything back on track.

**Comment by peters** [comment]
@TingluoHuang Thanks for helping :)
