### ISSUE TITLE
Unable to map secrets to global environment variable

### ISSUE THREAD

**Issue by ivailop** [Microsoft/azure-pipelines-agent#2148]
## Agent Version and Platform
Any

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
Unable to map secrets to global environment variables.

* example.yaml
```
variables:
  MY_MAPPED_ENV_VAR: $(mySecret)
...
  steps:
  - script: |
      echo "This prints nothing: $MY_MAPPED_ENV_VAR" 
```

The [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) provides an example of mapping per task, but does not explicitly say anything about restrictions on global mapping.

**Comment by TingluoHuang** [comment]
@ivailop 
when you have a secret variable defined in your build definition, we won't expose the secret variable through environment variable by default.
you need to either map the secret variable into environment variable per task, or use the secret variable as your task input.

Ex:  assume you define a secret variable mySecret=password in your definition
```yaml
- script: echo "This prints secret: $(mySecret)" 
```

```yaml
- script: echo "This prints secret: $MY_MAPPED_ENV_VAR" 
  env: 
    MY_MAPPED_ENV_VAR: $(mySecret)
```

**Comment by ivailop** [comment]
I understand that. I need it mapped as a global environment variable and this is why I do it on a global level (not per task). 
As I stated, the documentation does not prohibit that (does not explicitly state mapping is per task only) so I assumed it was possible.

**Comment by TingluoHuang** [comment]
@ivailop i don't think we support that, secret variable requires explicit action per task.
@vtbassmatt FYI.

**Comment by ivailop** [comment]
For a pipeline with multiple jobs and multiple scripts/tasks requiring secrets mapping it is very inconvenient to repeat it everywhere. 
Isn't that the purpose of having global environment variables?

**Comment by vtbassmatt** [comment]
I see why this is confusing. `variables` isn't a place for "global environment variables", although they do incidentally get promoted into the environment. The only time we'll map a secret into an environment variable is specifically in an `env` block.

I'll try to clean up the docs to make the distinction between pipeline variables and environment variables more clear.

In this case, could you just use `$(mySecret)` everywhere that you need the secret?

**Comment by ivailop** [comment]
The secret needs to mapped to an environment variable. Yes, I could do that per script/task, but as I stated it is very inconvenient if it has to be repeated number of times.

**Comment by vtbassmatt** [comment]
If you have tasks that expect to get the secret as a variable, you do have to map it in every time. But for inline scripts, it's the difference between saying `$MY_MAPPED_SECRET` in Bash (or `%MY_MAPPED_SECRET%` in Cmd) vs `$(MySecret)` and _not_ needing to map it in.

Workarounds aside: the feedback is well-taken. This is functioning as designed but I understand the irritation it causes. We'll consider changes as we evolve how YAML represents secrets and env vars.

**Comment by cleankode** [comment]
I am having the same issue - unable to access secret variables defined in azure pipeline inside my custom vsix task that uses PowerShell. How do you do the mapping?

**Comment by vtbassmatt** [comment]
Tasks can accept secrets as inputs, typically strings. Then the user supplies the $(ActualSecret) as the value of the input.

**Comment by pajcarpentier** [comment]
Hello,
i'm facing the same problem as i have to set my ARM_CLIENT_SECRET to a go@0 task to run terratest.
i tried the following without any success : 

        - task: Go@0
          displayName: 'Run Go terratest for resource_group'
          inputs:
            command: test
            arguments: '$(TF_LOG) $(pathToTerraformRootModule)\resource_group'
          env: 
            MY_MAPPED_SECRET: $(LOC_VAR_PERSONNAL_SECRET)

(trying first with tested secret before using real secret) with LOC_VAR_PERSONNAL_SECRET being a secret in my pipeline GUI.

trying to show the secret just give me stars as follow : 

```
<code>
	my_personnal_secret := os.Getenv("MY_MAPPED_SECRET")
	fmt.Printf("\n***** My PERSONNAL_SECRET is %s *****\n",my_personnal_secret)

<output>
***** My PERSONNAL_SECRET is *** *****

```
surely I'm doing something wrong actually, but I don't know how to pass my secret pipeline variable to my Go@0 task actually...

**Comment by cleankode** [comment]
@pajcarpentier 
I finally did resolve it and documented it here: https://bitbucket.org/ZelalemW/how-to-access-secrets-in-ado/src/master/

**Comment by hdGuild** [comment]
Hello @cleankode 
Thanks for the reply. 

I just point out this night that secrets are just not revealed in Azure pipelines output.
The way I used was the good one and the secret is well used in my go script... but just not printed :=)

Thanks for your code.

**Comment by cleankode** [comment]
@hdGuild  yes, secrets won't be printed in readable format - which is a good thing preventing accidentally leaking them in log outputs.
