### ISSUE TITLE
Support for AWS on hosted 

### ISSUE THREAD

**Issue by steven-cuthill-otm** [Microsoft/azure-pipelines-agent#2149]
would be nice if you could add the following to the default hosted images and the public docker image. 

AWSPowerShell.NetCore
Python boto , boto3
AWS CLI ( Windows & Linux )

**Comment by TingluoHuang** [comment]
@steven-cuthill-otm https://github.com/Microsoft/azure-pipelines-image-generation might be a better place for this kind of request. that's the repository for control what's installed on the hosted image.

**Comment by TingluoHuang** [comment]
i am closing this issue since it's not scope to this repository.
