### ISSUE TITLE
Download Artifact flakey on slow connections

### ISSUE THREAD

**Issue by alexwiese** [microsoft/azure-pipelines-agent#2150]
## Agent Version and Platform
Version of your agent? 2.147.1 
OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? dev.azure.com

If dev.azure.com, what is your organization name? https://pulselogistics.visualstudio.com

## What's not working?
When the agent's Internet connection is slow or laggy, artifacts are not correctly downloaded, although the step succeeds. It appears there is no checksum/verification/retry happening. Sometimes we have to retry the deploy step 10 or 20 times before it correctly downloads the artifact. I would expect some basic checksum verification and retry logic would happen on the download step. 

This raises two concerns, the first issue being the deploy step has to be retried again and again until the artifacts are downloaded correctly, the second is that artifacts that are not detected as being corrupt could be deployed to a production environment. We are downloading an archive so we can tell immediately if the file is corrupt as the Extract Archive step fails, but imagine customers who are downloading raw binary files and deploying them when they are corrupted.

**Comment by TingluoHuang** [comment]
@alexwiese can you share some log with me, so i can better route the issue?
you can attach the log to the issue of send me in email if you don't want to expose in internet.
`tihuang @ microsoft.com`

**Comment by TingluoHuang** [comment]
@madhurig looks like customer having issue with download/upload artifact task, i will forward customer's log to you.

**Comment by alexwiese** [comment]
@TingluoHuang @madhurig any update on this? This is a major pain point for us using Azure Devops

**Comment by omeshp** [comment]
@alexwiese Sorry for late response, this definitely is concerning. The download should have failed if it wasn't able to download the archive. From the logs it isn't apparent why it happened, I will look at the prod traces to narrow it down. 
To unblock yourself can you start using [Pipeline Artifacts](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/pipeline-artifacts.md).

**Comment by alexwiese** [comment]
@omeshp thanks I'll take a look at Pipeline Artifacts

**Comment by omeshp** [comment]
@alexwiese I am closing the issue since we are moving away from "Download Build Artifacts" to "Download Pipeline Artifacts". Let's us know if you are facing the issue with "Download Pipeline Artifact" too.
