### ISSUE TITLE
Ubuntu Agent - Can't access to pipeline variables in powershell

### ISSUE THREAD

**Issue by eflorespalma** [Microsoft/azure-pipelines-agent#2160]
Hi,
I create a build with an Ubuntu agent and I'm trying to access to my pipeline variables through powershell task, but always return me empty value and when i run the same script on windows agent i can get the value correctly, the script that I use is 

Write-Host  "My Variable is $env:URLAPI"
Write-Host  "My Another Variable is $env:Build.BuildNumber"

I just want to know why this works on Windows Agent and not on the Ubuntu Agent. Thank you

**Comment by TingluoHuang** [comment]
@eflorespalma double check your variables casing, `A` vs `a`. Windows ignore case but linux don't.

**Comment by eflorespalma** [comment]
@TingluoHuang, yes I checked for that reason, I used a default variable **Build.BuildNumber** too, but I realized that there is a section in the powershell task called environment variables and when I define a variable there, the powershell task can retrieve the value correctly, but when I use the pipeline variables don't do it. I don't want to use in that section because I would have to repeat my pipeline variables there. Is there any explanation for this? because with a windows agent works great.

**Comment by TingluoHuang** [comment]
@eflorespalma when you use a pipeline variables, the system toUpper your variables name when it pass through the environment.
ex:
define`myvar`=`foo` on your definition.
when retrieve variable on linux, you should use `MYVAR`  instead.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

**Comment by eflorespalma** [comment]
@TingluoHuang Sorry, I did not understand you in your first message, I just tried and it worked perfect. thank you.

**Comment by TingluoHuang** [comment]
@eflorespalma cool, glad you unblock. :)
you can close this issue if you don't have more questions. :)
