### ISSUE TITLE
what feed does azuredevops-testresultparser come from?

### ISSUE THREAD

**Issue by freebird8x** [Microsoft/azure-pipelines-agent#2167]
I cloned the repo and and tried to build but it failed with this error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package azuredevops-testresultparser. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org, Private MyGet	Test	I:\Source\xTemp\azure-pipelines-agent\src\Test\Test.csproj	1	
```
What feed does the package **azuredevops-testresultparser** come from? Google didn't help much.

**Comment by TingluoHuang** [comment]
@nigurr

**Comment by TingluoHuang** [comment]
it might coming from `myget.org`

**Comment by freebird8x** [comment]
It's not on myget.org. Myget.org only has vss-api-netcore

**Comment by nigurr** [comment]
https://www.myget.org/feed/testresultparser/package/nuget/azuredevops-testresultparser

**Comment by freebird8x** [comment]
Thanks Nigurr. How did you search for the package? I was searching from [myget gallery](https://www.myget.org/gallery) earlier using azure keyword but it didn't show me the right feed.

**Comment by TingluoHuang** [comment]
@freebird8x he is the one that published that package. :D

**Comment by freebird8x** [comment]
@TingluoHuang lol OK! fair enough :joy:

btw, I just created [another issue ticket here](https://github.com/Microsoft/azure-pipelines-agent/issues/2171). Appreciate any help to resolve the problem since we have been trying to make the pipelines work during the past 7 weeks. The problem described in the ticket is probably the last one we have to face.
