### ISSUE TITLE
Min docker version check fails for container jobs

### ISSUE THREAD

**Issue by lenisha** [Microsoft/azure-pipelines-agent#2174]
Agent Version and Platform:
Hosted Ubuntu 1604 Image

If dev.azure.com, what is your organization name? 
https://eneros.visualstudio.com

1.Setup YAML Build with Container job
resources:
  containers:
  - container: nodejs
    image: node:8.15-jessie

jobs:
- job: RunNodeBuild
  container: nodejs
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
    - script: 
        npm install 
      displayName: 'Run npm install'

2. Error:
[section]Starting: Initialize containers
[command]/usr/local/bin/docker version --format '{{.Server.Version}}'
'3.0.4'
Docker daemon version: '3.0.4'
[command]/usr/local/bin/docker version --format '{{.Client.Version}}'
'17.12.0-ce'
Docker client version: '17.12.0-ce'
[error]Min required docker server version is '17.12', your docker ('/usr/local/bin/docker') server version is '3.0.4'
[section]Finishing: Initialize containers

It sounds like coming from
https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/ContainerOperationProvider.cs#L98-100

And agent is running on Moby docker engine with version reported by Moby 3.0.4, while vsts agent has docker 17.12. 
Could this check be fixed in code?

**Comment by TingluoHuang** [comment]
@lenisha i am in the process of releasing 2.148.2 agent that should fix this.

**Comment by TingluoHuang** [comment]
#2165

**Comment by lenisha** [comment]
would it make it to vsts-agent-docker images ?

**Comment by vtbassmatt** [comment]
This is fixed

**Comment by caoyangjiang** [comment]
@vtbassmatt 

I am having the exact same problem just now. Just for the sake of experiment, I ran two pipelines from two accounts using identical YAML file. One builds successfully and the other fails with
"Min required docker server version is '17.12', your docker ('/usr/bin/docker') server version is '3.0.4' ".  What could be cause?

**Comment by walfie** [comment]
I'm also having the same issue. It seems like the agent pool for my account is still on agent version `2.148.0`

**Comment by TingluoHuang** [comment]
@walfie what's your account name?

**Comment by walfie** [comment]
it's `walfie`. Here's an example of a failed build, for reference:
https://dev.azure.com/walfie/sandbox/_build/results?buildId=18&view=logs&jobId=9a26be13-2289-5111-10aa-68406177efe5

**Comment by caoyangjiang** [comment]
@TingluoHuang  The problem I had is with a organizational account. All projects fail with the same error. Can you also look into this organizational account at https://dev.azure.com/HypeVR/ ? If you need other information, please let me know. Thanks!

**Comment by TingluoHuang** [comment]
@caoyangjiang your account is in a newly created data center that missing some configuration, i will fix the config if i can find my manager to approve my production config change request during the weekends, otherwise i will get it fix first thing on Monday morning.

**Comment by caoyangjiang** [comment]
@TingluoHuang No hurry. If it can be fixed on Monday, it would be great! Have a good weekend!

**Comment by caoyangjiang** [comment]
@TingluoHuang Is there an agent that has GPU-support and able to run CUDA code?

**Comment by vtbassmatt** [comment]
@caoyangjiang in hosted we offer [DS2_v2 machines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#capabilities-and-limitations) which I don't believe have GPU / CUDA capabilities. You can always stand up your own self-hosted agent on the Azure VM of your choosing.

**Comment by mloskot** [comment]
Could anyone clarify what's the status of this issue?
I've just followed up similar issue here https://github.com/MicrosoftDocs/vsts-docs/issues/2987#issuecomment-492335691 but it is unclear to me which one is relevant?

I'm being hit by the version bug on  https://dev.azure.com/osgeo/gdal/

![image](https://user-images.githubusercontent.com/80741/57719598-b8fe3800-7645-11e9-9b9a-f8bd7e297159.png)

```
jobs:
  - job: 'Documentation'
    pool:
      vmImage: 'ubuntu-16.04'
    container:
      image: osgeo/proj-docs
      options: --privileged
...

**Comment by TingluoHuang** [comment]
@mloskot looks like your account is in a different deployment that also miss configured on our side, i am fixing it right now, eta 10-15 min.

**Comment by mloskot** [comment]
@TingluoHuang Sounds great, thank you!

**Comment by caoyangjiang** [comment]
@TingluoHuang The problem has been resolved and now it no longer throw the error. Also, thanks for the information on the GPU VM.
