### ISSUE TITLE
Tortoise SVN 

### ISSUE THREAD

**Issue by KarlMaynardDK** [microsoft/azure-pipelines-agent#2175]
The SvnCliManager.cs adds the cli switch '--trust-server-cert' when the option _acceptUntrusted is set (true).

('Accept untrusted SSL certificates' is checked for the service connection in DevOps.)

This only handles cases where the certificate is self signed, it does not allow for cases when the certificate name does not match - which can occur if the url for the svn repository is the ip address.

Since version 1.9 (august 2015) --trust-server-cert has been depricated. It has been replaced with a new switch '--trust-server-cert-failures' that accepts a comma seperated list of conditions that may be allowed.

https://subversion.apache.org/docs/release-notes/1.9

```
 --trust-server-cert      : deprecated; same as --trust-server-cert-failures=unknown-ca

  --trust-server-cert-failures ARG : with --non-interactive, accept SSL server
                             certificates with failures; ARG is comma-separated
                             list of 'unknown-ca' (Unknown Authority),
                             'cn-mismatch' (Hostname mismatch), 'expired'
                             (Expired certificate), 'not-yet-valid' (Not yet
                             valid certificate) and 'other' (all other not
                             separately classified certificate errors).
```

Can we detect the version of the svn client, or allow it to be specified in the configuration somewhere. If the version is >=1.9 the code  at line 498 in SvnCliManager.cs should be update to support these newer options.

```
            // Add the common parameters.
            if (_acceptUntrusted)
            {
                formattedArgs.Add("--trust-server-cert");
            }
```

[Relates to Microsoft support case REG:119031221004513]

**Comment by TingluoHuang** [comment]
@madhurig for SVN related question.

**Comment by madhurig** [comment]
Thanks for notifying us of the issue and sharing the details. `Accept Untrusted SSL certificates` was meant to only help with self signed certificates. It appears for that we will need to update to `--trust-server-cert-failures=unknown-ca` for new SVN clients instead of `--trust-server-cert`. 

Why are you using IP for the SVN url? 

Thanks,
Madhuri

**Comment by KarlMaynardDK** [comment]
@madhurig
> Why are you using IP for the SVN url?
It is a matter that is currently outside of my control.

**Comment by madhurig** [comment]
Can you please vote on this ticket? https://developercommunity.visualstudio.com/content/problem/465423/azure-devops-using-pipelines-with-svn-and-accept-u.html

We are reviewing the best way to fix this issue without breaking another set of customers.

**Comment by TingluoHuang** [comment]
closed as tracked in the developer community.
