### ISSUE TITLE
TFS 2018: Agent 2.136.1 wrong user account on config with powershell

### ISSUE THREAD

**Issue by Vinzz** [Microsoft/azure-pipelines-agent#2179]
## Agent Version and Platform
Agent 2.136.1

OS of the machine running the agent? Windows Server 2016

## Azure DevOps Type and Version
on-premises TFS 
If on-premises, which release? 2018.3.2.2

## What's not working?
Upon configuring the agent with the following command line:

`config.cmd --url https://mytfs.com/tfs --agent $name1 --unattended --runAsService --pool default --auth Negotiate --userName $username --password $password --work _work `

The service does not run under the $username account, but rather on Local Service

Is there a way to make it run under the provided user account?

**Comment by TingluoHuang** [comment]
you need to set `windowsLogonAccount` and `windowsLogonPassword` for the windows service account.
.\config.cmd --unattended --url https://myaccount.visualstudio.com --auth Negotiate --userName $username --password $password --pool default --agent myAgent --runAsService --`windowsLogonAccount` myDomain\myUserName --`windowsLogonPassword` myPassword

**Comment by Vinzz** [comment]
Thanks @TingluoHuang ! I'll test that right away

**Comment by Vinzz** [comment]
And it works perfectly, thanks Ting! @
