### ISSUE TITLE
Local branches not cleaned up

### ISSUE THREAD

**Issue by Cheesebaron** [microsoft/azure-pipelines-agent#2189]
## Agent Version and Platform
Version of your agent? 2.148.2

OS of the machine running the agent? macOS 10.13.6

## Azure DevOps Type and Version
dev.azure.com https://trackman.visualstudio.com

## What's not working?
Local branches are not cleaned up. It appears to me that the Agent creates a numbered folder in the _work directory for a project, then every run, it checks out a branch and ensures it is up to date. However, after it has ended the build, it does not delete this local branch. Even though Cleaning is set to Clean All Sources for the pipeline.

Not removing these local branches, means that tasks such as GitVersion will eventually start running for a _very_ long time, since it takes into account all these local branches as well as remote branches.

I've tried all the different Cleaning options for Git repositories you can set up for the pipeline. I've also tried running maintenance for the pipeline. None of these are cleaning up the local branches.

**Comment by TingluoHuang** [comment]
@Cheesebaron the agent never checkout a branch, it always checkout on a detected HEAD. Do you have any definition that use script to checkout some branch?

**Comment by Cheesebaron** [comment]
We don't run any scripts for checking anything out.

If I run `git branch` to list local branches, I get a whole bunch of checked out branches, which seems strange to me.

**Comment by TingluoHuang** [comment]
@Cheesebaron what about tasks? are there any tasks you used in your definition may checkout branch?

**Comment by Cheesebaron** [comment]
Nope, my pipeline definition does:

- install iOS provisioning profile
- install iOS distribution cert
- run Cake build script
- upload to AppCenter

The Cake build script does not check any code out through git.

**Comment by ChristianStadelmann** [comment]
In my case, I see hundreds of branches when executing `$ git branch --all`. They all have the schema `remotes/pull/[PR number]/merge`

**Comment by ChristianStadelmann** [comment]
@azure-pipelines-bot : Please un-close this issue. IT is still present.
