### ISSUE TITLE
Error installing AzAgent on an Ubuntu VM in Azure

### ISSUE THREAD

**Issue by Leon99** [Microsoft/azure-pipelines-agent#2198]
I'm not trying to achieve something unorthodox - just want to install an AzAgent on a Ubuntu 18.04-LTS VM in Azure (using Azure's stock image) with a little help of cloud-init. I realized that the registration script AzDO (not sure what's the proper way to abbreviate the cloud TFS now) generates is incorrect and added `./bin/installdependencies.sh` before `./config.sh`, as per https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/start/envlinux.md. This is what I get after the script finishes (when executed by cloud-init):
```
Must not run with sudo
sudo: ./svc.sh: command not found
sudo: ./svc.sh: command not found
```
When executed interactively from the admin user:
```
touch: cannot touch '.env': Permission denied
./env.sh: line 39: .path: Permission denied
./env.sh: line 34: .env: Permission denied

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/azagent/_diag' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.VisualStudio.Services.Agent.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32 pageSizeLimit, Int32 retentionDays)
   at Microsoft.VisualStudio.Services.Agent.HostContext..ctor(String hostType, String logFile)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.Main(String[] args)
./config.sh: line 86: 15997 Aborted                 (core dumped) ./bin/Agent.Listener configure "$@"
sudo: ./svc.sh: command not found
sudo: ./svc.sh: command not found
```
Any ideas appreaciated.

**Comment by TingluoHuang** [comment]
@Leon99 what's your logon user? how did you run the `config.sh` script? run with `SUDO`?

**Comment by Leon99** [comment]
Not sure I can add much information on top of what is in my report. First result is after the script was executed under root, second is after executing by the admin user (the one specified during VM creation).

**Comment by TingluoHuang** [comment]
@Leon99 you need to run the `installdependencies.sh` as `root` since it needs to run `apt-get install`, you need to run `config.sh` as the admin user so the file generated during configure can be used by your admin user. Hope this help. :)

**Comment by Leon99** [comment]
Good to know, thanks @TingluoHuang. It would be good to specify it in the documentation BTW. However, it doesn't solve the problem. Let me clarify what I did: `./bin/installdependencies.sh` was run under root and worked fine. I ran `config.sh`  after that as the admin user, and it returned errors:
```
touch: cannot touch '.env': Permission denied
./env.sh: line 39: .path: Permission denied
./env.sh: line 34: .env: Permission denied

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/azagent/_diag' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.VisualStudio.Services.Agent.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32 pageSizeLimit, Int32 retentionDays)
   at Microsoft.VisualStudio.Services.Agent.HostContext..ctor(String hostType, String logFile)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.Main(String[] args)
./config.sh: line 86: 15997 Aborted                 (core dumped) ./bin/Agent.Listener configure "$@"
sudo: ./svc.sh: command not found
sudo: ./svc.sh: command not found
```

**Comment by TingluoHuang** [comment]
@Leon99 which you used to download and unzip the agent package? make sure it's the admin user.
if not, try download and unzip the agent package as the admin user and run through the config again. :)

**Comment by Leon99** [comment]
Aha ok that makes sense. I'll have a problem with that though since the whole script is executed by cloud-init, but I guess it's my worry. Thanks for your prompt response.

**Comment by TingluoHuang** [comment]
Cool, you can close the issue once you unblock, or post back questions. :D
