### ISSUE TITLE
config.sh --replace parameter not working

### ISSUE THREAD

**Issue by infogulch** [Microsoft/azure-pipelines-agent#2199]
## Agent Version and Platform
Agent version 2.148.2
[Update: Also tested on 2.149.2 with the same results.]
OS: Ubuntu 16.04

## Azure DevOps Type and Version
dev.azure.com/[org]

## What's not working?
I'm running the following command as part of a first-boot script in an azure scaleset.

> /data/a/config.sh **--replace** --unattended --url "https://dev.azure.com/[org]" --auth pat --token "[token]" --pool MyAgentPool --agent "[scaleset instance name e.g. 'agent000003']" --acceptTeeEula

This command *sometimes* gives the error:

> Cannot configure the agent because it is already configured. To reconfigure the agent, run 'config.cmd remove' or './config.sh remove' first.

I expected to not get this error because I included the `--replace` parameter which I expect to replace an agent by that name if it already exists instead of having to remove it first.  This expectation is based on the output of `config.sh --help`:

> Configure options:
>  --replace Replace the agent in a pool. If another agent is listening by that name, it will start failing with a conflict.

Note that the conflict mentioned here is impossible in this case because instance names are  unique at a given point in time (i.e. you can't have two instances with the name agent000003 at once).

My goal is to register pipeline agents with the name based on the scaleset instance name.  If an instance is reimaged the old agent with that name no longer exists and it is safe to override any existing agents with that name.

## Agent and Worker's Diagnostic Logs
[Agent_20190403-221956-utc.log](https://github.com/Microsoft/azure-pipelines-agent/files/3041006/Agent_20190403-221956-utc.log)

**Comment by TingluoHuang** [comment]
@infogulch the `--replace` is to let a different agent instance to take over the agent slot on server side. you need to run `config --remove` or delete the hidden `.agent` and `.credential` files under the agent root before reuse the same local agent instance.

**Comment by infogulch** [comment]
@TingluoHuang thanks for the direction.  I thought it was installing to a clean directory, but it turns out my assumptions were wrong.  I'm using a data disk attached to the vm as the agent install/work directory.

I expected this disk to be wiped when a vmss instance is reimaged, but it turns out this is not the case!  (This behavior is quite reasonable, actually.)  Adjusting my cloud-init script to force-recreate the data disk filesystem on first-boot fixed it for me, since this is the behavior that I want.

Thank you for your help!
