### ISSUE TITLE
Agent Hosted in VM Fails with "An error occurred: VS30063: You are not authorized to access https://dev.azure.com."

### ISSUE THREAD

**Issue by keithhodomicrosoft** [microsoft/azure-pipelines-agent#2202]
## Having generic issue with Azure-Pipelines/VSTS/TFS?
Cross-link: https://developercommunity.visualstudio.com/content/problem/520839/agent-hosted-in-vm-fails-with-an-error-occurred-vs.html

## Have you tried troubleshooting?
Yes, for the last 18 hours

## Agent Version and Platform
vsts-agent-win-x64-2.149.2

OS of the machine running the agent? 
Windows Server 2012

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

If dev.azure.com, what is your organization name? https://dev.azure.com/mpneng or https://mpneng.visualstudio.com

## What's not working?
I have been working on our build that we host in a vanilla Azure VM. Almost every build that I have run fails with the error "An error occurred: VS30063: You are not authorized to access https://dev.azure.com.". I have removed and re-installed the agents multiple times. Each time my build works fine until I hit a long-running task and it looks like an outbound https call (I'm assuming over 443) will randomly fail and cause the entire build to fail. Are these outbound calls to update the AZDO build status wrapped in a retry mechanism?

I am building using .NET Core sdk 2.1.505, NuGet 4.7.1 and using the Visual Studio build task (my solution is dotnet core except for a database project).

It usually will fail after my build and packaging is all done. After that I run my unit tests and integration tests and these will typically fail with the error "The operation was canceled."

When I look in Event Viewer the only thing I find from the agent is the error in the title. Please let me know where to look for further diagnostics.

## Agent and Worker's Diagnostic Logs
Attached
[Agent_20190406-194853-utc.zip](https://github.com/Microsoft/azure-pipelines-agent/files/3050975/Agent_20190406-194853-utc.zip)

**Comment by keithhodomicrosoft** [comment]
Please note that I have also tried switching back to https://mpneng.visualstudio.com and I am still seeing the error. I can clear the error logs and generate more errors if that would help.

My PAT shouldn't be randomly getting rejected by AAD. It's rather odd.

**Comment by TingluoHuang** [comment]
@keithhodomicrosoft can you ping me on skype or team 4/7? i am in EST timezone. I want to try something with you. :)

**Comment by TingluoHuang** [comment]
close as the issue resolved offline, there was an issue on the service side that causing this issue. The agent behaves correctly.
