### ISSUE TITLE
Using secret variables from c# code

### ISSUE THREAD

**Issue by filip998** [Microsoft/azure-pipelines-agent#2204]
I have question:

I need to use secret variables for my unit testing.
Unit tests are written in c# code and tests are executing on some databases. To be able to connect to those databases I need some credentials, so I decided to store them as secret variables.

So my question is:
Is there a way to access those secret variables from c# code?

**Comment by TingluoHuang** [comment]
@filip998 how do you run your tests?
if you are using script task, you can map secret into environment variable. [doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables)
if you are using msbuild/vsbuild/vstest task, you might need to pass the secret as msbuild args, ex `/p:connection=$(SecretVariable)`

**Comment by TingluoHuang** [comment]
@filip998 
![image](https://user-images.githubusercontent.com/1750815/55731960-15d45600-59e9-11e9-90fe-633eb08bfd70.png)

Is it possible to define a place hold for the variable in your setting file and overwrite it with the value from the secret variable?

**Comment by filip998** [comment]
@TingluoHuang 
Thanks, I will try this. I will report to you when I try it.

**Comment by filip998** [comment]
@TingluoHuang UPDATE: It works like this, thank you so much !

**Comment by TingluoHuang** [comment]
cool, glad you unblocked. :)

**Comment by artemious7** [comment]
I'm sorry, I'm new to Azure Pipelines, so I don't know what this means and how to do it. Could anyone provide a step-by-step for this, please?

> place hold for the variable in your setting file and overwrite it with the value from the secret variable?
