### ISSUE TITLE
Allow download location to be specified when selecting deployment group artifacts

### ISSUE THREAD

**Issue by bendursley** [Microsoft/azure-pipelines-agent#2207]
We're in a position at present where we are using the Download Pipeline Artifact to create a folder structure for our build artifacts (about 8 of them), as we have another tool which generates our patches from a specific output.

Is there any intention to give us the download option directly on the Artifact Download section of the Deployment Group and Agent jobs, rather than having to do this in tasks?

Or is it always expected to be only supported in tasks?

**Comment by TingluoHuang** [comment]
@chshrikh for deployment group question.

**Comment by omeshp** [comment]
@bendursley You can set system.artifactsdirectory variable on release definition to change the download directory of artifacts

**Comment by bendursley** [comment]
@omeshp isn't that for all artifacts, however, rather than just specific ones.

My example, so there's some clarity here:
If I have four artifacts, I download them to different directories as follows:
Database: $(System.ArtifactsDirectory)
Client: $(System.ArtifactsDirectory)\Bin\Client
Service: $(System.ArtifactsDirectory)\Bin\Service\Bin
Templates: $(System.ArtifactsDirectory)\Templates

We then build up our server patches based on this fixed locations.  
It's possible to have this flexibility with the Download Pipeline Tasks.

**Comment by omeshp** [comment]
Hi @bendursley, We currently don't support setting download location per artifact. We will support it in yaml based pipelines in future. Till then one option you can take is to move the artifacts to correct locations after download.

**Comment by bendursley** [comment]
Thanks for the info @omeshp
