### ISSUE TITLE
once flag (--once) is not working

### ISSUE THREAD

**Issue by iambernics** [Microsoft/azure-pipelines-agent#2217]
The latest Agent (2.149.2) ignore the `--once` argument and accept more than one Job.

**Run once agent**

> If you're using infrastructure such as Azure Container Instances to run elastic private agents, often, you want each agent to accept only one job before going away. Until now, this wasn't easy since you had to terminate the agent (possibly causing a failure to be reported) or accept the risk that an agent might receive another job before you could shut it down. With this update, we added the --once flag to the agent configuration. When you configure the agent this way, it'll accept only one job and then shut itself down.

https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-150-update#run-once-agent

Environment: Windows Server 2016 Standard

**Comment by TingluoHuang** [comment]
@iambernics can you share your agent log file?

**Comment by iambernics** [comment]
Sorry, I used this argument on the configuration instead as the run.cmd parameter (.\run.cmd –once).
I am closing the issue.

**Comment by TingluoHuang** [comment]
Cool, let me know if you need more help.

**Comment by iambernics** [comment]
Thanks, can I use this parameter / function with the service (AgentService.exe) too?

**Comment by TingluoHuang** [comment]
no, you can not.
