### ISSUE TITLE
build agent 'loses connection to server'

### ISSUE THREAD

**Issue by geepy** [microsoft/azure-pipelines-agent#2221]
We have upgraded our TFS on-premise from 2017 Release 3.0 to 2017 release 3.1 + Patch 3.1.

Then we switched the public URL from http to https.
We reregistered all build agents to use https.

After each service restart the build agent can connect to the tfs server and handle builds, but only for a limited time.
After that it continues to accepts build requests (status in TFS changes to "running"), but after 5 minutes the server cancels the build and gives the reason 
`The agent XXX lost communication with the server. Verify the machine is running and has a healthy network connection. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610`

When browsing the agent log in the _diag folder, I see the folowing entry for failed builds:
`
[2019-04-18 10:34:40Z WARN VisualStudioServices] Authentication failed with status code 401.
Date: Thu, 18 Apr 2019 10:34:40 GMT
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Server: Microsoft-IIS/8.5
WWW-Authenticate: Bearer, Basic realm="https://_myserver_:8443/tfs", Negotiate, NTLM
X-TFS-ProcessId: 873e3eb7-2fcf-4e3d-979d-019cd1441792
ActivityId: d129a548-2a33-4be0-bc36-da2af6974cce
X-TFS-Session: a31e8c39-ba35-474b-a5ca-eb9581c44a3a
X-VSS-E2EID: 597551cd-62ac-4232-9507-18a43524da74
X-FRAME-OPTIONS: SAMEORIGIN
X-TFS-SoapException: %3c%3fxml+version%3d%221.0%22+encoding%3d%22utf-8%22%3f%3e%3csoap%3aEnvelope+xmlns%3asoap%3d%22http%3a%2f%2fwww.w3.org%2f2003%2f05%2fsoap-envelope%22%3e%3csoap%3aBody%3e%3csoap%3aFault%3e%3csoap%3aCode%3e%3csoap%3aValue%3esoap%3aReceiver%3c%2fsoap%3aValue%3e%3csoap%3aSubcode%3e%3csoap%3aValue%3eUnauthorizedRequestException%3c%2fsoap%3aValue%3e%3c%2fsoap%3aSubcode%3e%3c%2fsoap%3aCode%3e%3csoap%3aReason%3e%3csoap%3aText+xml%3alang%3d%22en%22%3eTF400813%3a+Resource+not+available+for+anonymous+access.+Client+authentication+required.%3c%2fsoap%3aText%3e%3c%2fsoap%3aReason%3e%3c%2fsoap%3aFault%3e%3c%2fsoap%3aBody%3e%3c%2fsoap%3aEnvelope%3e
X-TFS-ServiceError: TF400813%3a+Resource+not+available+for+anonymous+access.+Client+authentication+required.
`

On the server I see the 401 in the iis log. 
But: the agent does still communicate successfully with the server; there are lots of requests from the very same agent before and after the 401 that contain 20x http codes.
And fore each and every 401 entry in the iis log there is another from ste same client, timestamp and session that is authenticated successfully and gets a 200 result.

Except for one call, namely the url https://_myserver_:8443/tfs/_apis/connectiondata. This URL seems to be called from inside the build worker. It works fine the first time a build is run after restarting the service, but fails on subsequent builds.

An interesting fact is that one of my agents is running version 2.112.0 (user agent string 
`VSServices/15.255.65000.0+(NetStandard)+VstsAgentCore-win7-x64/2.112.0+(Microsoft+Windows+6.3.9600)` (whereas all other run 2.123.0, user agent string `VSServices/15.125.27010.0+(NetStandard;+Microsoft+Windows+6.3.9600)+VstsAgentCore-win7-x64/2.124.0+(Microsoft+Windows+6.3.9600)` ), and this agent can successfully communicate over that url...

Any ideas how to fix that?

Guenter

**Comment by TingluoHuang** [comment]
@geepy can you share a full agent/worker log from the same agent instance that had this problem? (it start the build but failed after 5 mins)

**Comment by geepy** [comment]
Hi,

please find attached two logs, one ("success.log") that runs fine and another ("failure .log") that fails from the very same agent some minutes before.
Both tasks are just maintenance jobs, so the build is really short, but I believe all important information is contained.
[success.log](https://github.com/Microsoft/azure-pipelines-agent/files/3098653/success.log)
[failure.log](https://github.com/Microsoft/azure-pipelines-agent/files/3098654/failure.log)

**Comment by geepy** [comment]
To be precise: the problem is not that the build fails after 5 minutes. That is just the observation when yxou look at the TFS web application. The failing job immediately loses connection (see logfiles above), bit TFS does not believe that and waits another 5 minutes before calling the build dead...

**Comment by TingluoHuang** [comment]
@geepy check all your ATs' TFS debug event log around `2019-04-19 12:08`, there should be some information to tells us why the agent get 401 with it's token. you can also send the event log to me if you want, `tihuang at microsoft.com`

**Comment by geepy** [comment]
Together with @TingluoHuang we found the problem's root:
When upgrading from TFS 2017.3 (onprem) to TFS 2017.3.1 on a two-machine-app tier configuration, the setup does not work correctly.
What happens is: 

- first app tier runs setup, detects that the configuration database is old and runs migration scripts. One of those is to register the app server as a valid OAuth2 token generator.
- second app tier runs setup, detects that the configuration database is already the correct version, and does _not_ register itself as valid OAuth2 token generator.

Because both app tiers run the TFS Build Agent Service (not the one in this repository, but the one from the TFS team that runs on the TFS app server), both check for conditions to start a build and, when met, create a build job on the server, which is the package the pipeline agent needs to run a build. Part of this package is an OAuth token that is needed to fetch sources from the TFS source control (is not needed for GIT or azure repositories, though),
When the second app server creates such a package, the request to fetch sources form TFS source control fails because of an unauthorized OAuth token, which causes the pipeline agent to fail all following requests to Source Control.

The solution is a fix to the configuration database, that Tingluo advised to me. I won't go into detail on this because it could break your TFS instance if applied incorrectly - if you need it, you have to ask MS for the bits :-)

So technically it was not a problem of this code, but inside the setup procedure of TFS 2017.3.1.

Thanks to the folks on this repo for helping me fix this awkward problem.
