### ISSUE TITLE
config.cmd should provide service name and description parameters

### ISSUE THREAD

**Issue by MovGP0** [Microsoft/azure-pipelines-agent#2223]
## Current Behaviour

`config.cmd` is currently missing parameters for the service name and description. this way, it is 
not trivially possible to configure multiple deployment agents on the same machine. 

```powershell
    .\config.cmd `
        --unattended --acceptteeeula --url 'https://tfs.internal/' --collectionname 'Foo' `
        --auth pat --token $patToken `
        --agent $env:COMPUTERNAME `
        --work '_work' `
       # user and password can be configured, but not the service name 
        --runasservice --windowsLogonAccount $ServiceUserName --windowsLogonPassword $ServicePassword `
        --deploymentgroup --deploymentgroupname $DeploymentGroupName --ProjectName $ProjectName;
```

## Expected Behaviour

There should be additional parameters for the service name and description

```powershell
    .\config.cmd `
        --unattended --acceptteeeula --url 'https://tfs.internal/' --collectionname 'Foo' `
        --auth pat --token $patToken `
        --agent $env:COMPUTERNAME `
        --work '_work' `
        --runasservice --windowsLogonAccount $ServiceUserName --windowsLogonPassword $ServicePassword --serviceName $serviceName -- serviceDescription $serviceDescription`
        --deploymentgroup --deploymentgroupname $DeploymentGroupName --ProjectName $ProjectName;
```

## Workaround

My current workaround is to create the service with the default name, and rename the service after creation. 

```powershell
C:\Windows\System32\sc.exe config "vstsagent.apitfs.$($env:computername)" DisplayName= "$DisplayName";
cd HKLM:\SYSTEM\CurrentControlSet\Services
mv "vstsagent.apitfs.$($env:computername)" vstsagent.apitfs.$ProgramName.Staging
Restart-Computer
```

The drawback is that this approach requires a restart of the computer before creating another agent.

**Comment by TingluoHuang** [comment]
@MovGP0 we should generate unique service name for deployment group agent, that's seems like a bug to me. i don't think you need these extra arguments if we fix this issue.

**Comment by juliobbv** [comment]
@MovGP0, I have PR #2229 out that I believe should address your issue. We were not considering the pool information while generating the service name, so two agent instances targeting the same account, but different pools would generate the same service name.

As a workaround, you can provide a unique agent name per config invocation, which would transfer to the service name as well.
