### ISSUE TITLE
Agent work prioritisation causing most pipeline processing on first agent registered into pool

### ISSUE THREAD

**Issue by ossentoo** [microsoft/azure-pipelines-agent#2228]
We currently have a 5 instance Azure scaleset for a pool of 5 pipeline agents.

The priority to "grab" works by these agents seems always to be in the order that instances were created and registered into the pool.  This means for example:

- **agent01** (which signifies the agent that was registered first into the pool) ends up running most of the builds/releases.  this is especially the case because we only periodically have multiple builds/releases running on agents at the same time.  
- there seems to be functionality in the build/release selections which means the same agent will be select if possible by any definition that has run in the past (probably for caching).    Therefore if builddef01 runs a 2nd, 3rd, 4th time and agent01 is available, it will tend to use that agent.

The impact of this is agent01 sometimes runs out of disk space.

We have a maintenance plan setup for the pool, but have had to set this to a very low number of days to ensure agents don't run out of disk space.  During busy periods, we sometimes run out of disk space on agent01 within a day after re-imaging the scaleset instance even with maintenance setting set to 1 day.

For us, it would be better if first time pipeline runs where more equitably spread across all agents.  This would mean 2nd time runs, would also be more equitably spread as well and so on.  Of course any pipeline definition running (where it is not the first time), if the agent it ran on the first time is not available (i.e. it is busy or offline), the selection of the agent that will run the work, should also not necessarily be the first agent that was registered into the pool.

So my suggestion is that work load be evening distributed across all agents more equitably.

These suggestions were logged on Developer Community and User Voice. Please see the links below: 
https://developercommunity.visualstudio.com/content/idea/365620/build-agent-priority.html 
https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/17701630-build-agent-priority

Pipeline Agent versions:

![image](https://user-images.githubusercontent.com/7569380/56730736-8cdf4d80-6750-11e9-93de-803722656e9a.png)

**Comment by geirsagberg** [comment]
This is still an issue, according to the (at the moment of writing) 136 votes on this user-voice: https://developercommunity.visualstudio.com/idea/365620/build-agent-priority.html
