### ISSUE TITLE
Deployment pool agents: clean up artifact folder after release or on maintenance

### ISSUE THREAD

**Issue by serhit** [microsoft/azure-pipelines-agent#2231]
Currently build agent pool has an option to configure maintenance task and clean stale working folders - this is of great help keeping build machines under control.

Unfortunately, similar feature is not available for agents in deployment pools. This lead to constantly growing disk consumption - especially in case when many different releases are deployed to the same server.

Is there any plan to include maintenance of deployment agent (preferable) or to setup automated cleaning of release artifacts / folders after deployment? For landscapes with hundreds of deployment agents it would be of great help for Ops teams.

**Comment by omeshp** [comment]
@serhit We already clean up artifacts folders for releases older than 30 days on maintenance job run. Is it not working for you?

**Comment by serhit** [comment]
Unfortunately, 30 days are too long for us - too much releases of feature branches. Is there any way to control the retention period? So that we may set it to shorter period?

**Comment by omeshp** [comment]
@serhit You can control these settings from the collection level pool settings. Look at [this blog](http://www.codewrecks.com/blog/index.php/2017/05/06/maintenance-for-build-agent-in-tfs-build/)

**Comment by serhit** [comment]
@omeshp settings for builds agents is well known and we are using it. 
This issue is regarding similar settings we need for **deployment group agents**.

**Comment by omeshp** [comment]
@serhit Same settings should work for both. Is it not working for your case?

**Comment by omeshp** [comment]
@serhit Got it. @chshrikh We already have logic on agent side to handle the settings for agent pools, it looks like deployment groups are missing these settings. Can you confirm?

**Comment by RoopeshNair** [comment]
We will add it our backlog however it will be a while before we can get to it (~5-6 months). We know this is important for you, currently we are addressing the issues that are affecting broader set of customers. We will continue to monitor this. 

As a workaround, you can have a release with scheduled triggers that can periodically clean up the artifact folders on the disk using custom inline script.

**Comment by serhit** [comment]
Thank you for taking this to backlog - I'm sure it will bring benefits to all customers.

"Good things come to those who wait"

**Comment by xantari** [comment]
Not sure where this got put onto the backlog as there are no backlog items to fix this issue linked to this post. For others reading this, the only way we can fix this issue is to put this as last task in release pipeline:
![image](https://user-images.githubusercontent.com/6610039/91072394-10d46e80-e5ff-11ea-8e55-6a9c5009d713.png)

**Comment by FreshPrinceMayo** [comment]
@RoopeshNair Hi any update on this ?

**Comment by jhoff909** [comment]
Any updates on this?  Is there a backlog item to add this feature?

**Comment by anatolybolshakov** [comment]
Hi everyone, could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 for proper routing to clarify - since this feature is related more to the server-side?

**Comment by jhoff909** [comment]
here it is more than 3 years later and this is still an issue.  What's the status?
