### ISSUE TITLE
 Fail to download task. HTTP Status: NotFound

### ISSUE THREAD

**Issue by DJRobertson** [microsoft/azure-pipelines-agent#2235]
Hi @TingluoHuang
## Agent Version and Platform Version of your agent?
Agent:  v2.151.0, macOS	vsts-agent-osx-x64-2.151.0.tar.gz

OS of the machine running the agent? 
OSX, Mojave Version 10.14.4

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
On-Prem TFS, which release? 
Team Foundation Server 2015 (14.0.23128.0 (Tfs2015))

## What's not working?
Error: Fail to download task. HTTP Status: NotFound

## Agent and Worker's Diagnostic Logs

[v2.151.0 Failed to download task.txt](https://github.com/Microsoft/azure-pipelines-agent/files/3131058/v2.151.0.Failed.to.download.task.txt)

**Comment by TingluoHuang** [comment]
@DJRobertson can you hit `http://tfs01:8080/tfs/_apis/distributedtask/tasks/0f077e3a-af59-496d-81bc-ad971b7464e0/1.0.3` from any browser and see what do you get?

**Comment by DJRobertson** [comment]
@TingluoHuang
The task is downloaded in both Safari and chrome

**Comment by TingluoHuang** [comment]
@DJRobertson i assume you are using Safari and Chrome on the same machine as the agent. :)
do you have any proxy the browser use?
you mind want to try get http trace base on https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#use-built-in-http-tracing

and send the log to me directly, since it may contains secrets.
`tihuang @ microsoft.com`

**Comment by DJRobertson** [comment]
@TingluoHuang
Yes,  you assumed correctly that the agent was on the same machine as Chrome & Safari.
Also sent logs via email.
Thanks

**Comment by TingluoHuang** [comment]
@DJRobertson try use `export VSTS_AGENT_HTTPTRACE=true` and restart the agent process and send agent diag log to me via email, BTW, is this a regression or it never works for you?

**Comment by TingluoHuang** [comment]
@DJRobertson is your agent configured as service? if so, you might want to add `VSTS_AGENT_HTTPTRACE=true` to the `.env` file under agent's root and then restart the agent service.

the log you send me shows the environment variable is not properly propagate to the process. :D

**Comment by TingluoHuang** [comment]
@DJRobertson base on the log, looks like the request never made to TFS app, it's blocked by IIS.
I am wonder something is wrong with our REST routing. can you try use an older version agent? like 

https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.139.1
or 
https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.131.0

**Comment by DJRobertson** [comment]
@TingluoHuang 
Using agent version: '2.139.1'
Error
Unable to match any source repository endpoints with any of the supported source providers.
System.Exception: Unable to match any source repository endpoints with any of the supported source providers.
I sent the logs to your email

**Comment by TingluoHuang** [comment]
@DJRobertson sorry, i forgot 139.1 may had a bug, can you try https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.131.0

**Comment by DJRobertson** [comment]
@TingluoHuang

I sent you the logs using version 2.131.0

**Comment by TingluoHuang** [comment]
@DJRobertson the log still contains a weird error, can you try queue a build with `Build.SyncSources=false` variable set and send me log?

**Comment by DJRobertson** [comment]
@TingluoHuang

Set the variable and sent you the logs Ting.

**Comment by DJRobertson** [comment]
@TingluoHuang

Hi Ting, any update on the connection issue?

**Comment by TingluoHuang** [comment]
@DJRobertson sorry, i was on vacation, will take a look today.

**Comment by DJRobertson** [comment]
@TingluoHuang
No probs, hope you had a good one.

**Comment by DJRobertson** [comment]
@TingluoHuang
Hi Ting, had a chance to look at this yet?

**Comment by DJRobertson** [comment]
@TingluoHuang
Hi Ting, had a chance to look at this yet?

**Comment by DJRobertson** [comment]
@TingluoHuang
Hi Ting, had a chance to look at this yet?
Or have you abandoned it?

**Comment by TingluoHuang** [comment]
Sorry, I was stuck on all different kind of busy stuff.
Here is what we already know and tested:
- You are able to download the task.zip from a browser by hitting URL http://tfs01:8080/tfs/_apis/distributedtask/tasks/0f077e3a-af59-496d-81bc-ad971b7464e0/1.0.3
- Base on the log from 2.131.0 agent, the agent is trying to hit http://tfs01:8080/tfs/_apis/distributedtask/tasks/0f077e3a-af59-496d-81bc-ad971b7464e0/1.0.3 with a  Bearer auth token, but the request rejected by IIS with 404

This basically tells me IIS doesn't like the URL agent is using, the request does not even reach to the TFS app, it gets block by IIS first.

How did you authenticate with TFS from your mac, NTLM?
Try run the following curl command:
```
curl -v -i -H 'Accept:application/zip' -o task.zip --ntlm --negotiate -u <USER>:<PASSWORD> http://tfs01:8080/tfs/_apis/distributedtask/tasks/0f077e3a-af59-496d-81bc-ad971b7464e0/1.0.3
```
Have you tried to configure build agent from any other machine?

**Comment by DJRobertson** [comment]
Hi @TingluoHuang 
1. Yes I was Authenticating with NTLM from my MacBook Pro.
2. I tried the curl command and was getting Unauthorised (See below).
3. This is the only Mac we have in this building.

< HTTP/1.1 401 Unauthorized
< Cache-Control: private
< Content-Type: text/html
< Server: Microsoft-IIS/8.0
< X-TFS-ProcessId: 63327ad5-a9f5-4abf-a498-4cc069d17977
< X-FRAME-OPTIONS: SAMEORIGIN
< Access-Control-Allow-Origin: *
< Access-Control-Max-Age: 3600
< Access-Control-Allow-Methods: OPTIONS,GET,POST,PATCH,PUT,DELETE
< Access-Control-Expose-Headers: ActivityId,X-TFS-Session
< Access-Control-Allow-Headers: authorization
< Set-Cookie: Tfs-SessionId=ec9dfd91-cf09-4c3b-a48b-cdffd5eef018; path=/
< Set-Cookie: Tfs-SessionActive=2019-06-24T14:14:17; path=/
< WWW-Authenticate: NTLM
< X-Powered-By: ASP.NET
< P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
< X-Content-Type-Options: nosniff
< Date: Mon, 24 Jun 2019 14:14:17 GMT
< Content-Length: 1293

**Comment by jtpetty** [comment]
@DJRobertson - I apologize for the  delay in someone getting back to you. Are you still seeing this problem?
