### ISSUE TITLE
Self-hosted agent self update failed due to 30 minutes timeout

### ISSUE THREAD

**Issue by on99** [microsoft/azure-pipelines-agent#2241]
1. Downloading agent from mainland China is too slow (< 50KBps), can you put agent on CDN so we can benefit from it.
2. Seems like 30 minutes timeout for self update is not configurable. It's better if it can be configured by us, otherwise it keeps retrying self update.

**Comment by TingluoHuang** [comment]
@on99  the agent is distributed through Azure CDN already. :(

**Comment by TingluoHuang** [comment]
@juliobbv

**Comment by on99** [comment]
> @on99 the agent is distributed through Azure CDN already. :(

sorry to hear that. :(
Even though I setup a proxy to download agent from Hong Kong, it's also pretty slow.

Making it configurable should be a compromise solution for us.

Thank you!

**Comment by on99** [comment]
#2183 
Seems like it's configurable via environment variable `AZP_AGENT_DOWNLOAD_TIMEOUT` and defaults to 15 minutes. I will give it a shot.

**Comment by juliobbv** [comment]
Hi @on99, before I close this issue, I wanted to verify if setting the environment variable worked for you.

**Comment by juliobbv** [comment]
Closing this issue.

**Comment by on99** [comment]
> Hi @on99, before I close this issue, I wanted to verify if setting the environment variable worked for you.

It works for me, thank you!
