### ISSUE TITLE
Git fetch fails with exit code 1 and "would clobber existing tag" message

### ISSUE THREAD

**Issue by danegsta** [microsoft/azure-pipelines-agent#2243]
## Have you tried troubleshooting?
Yes

## Agent Version and Platform
2.150.3 Windows

## Azure DevOps Type and Version
https://dev.azure.com/DevDiv

## What's not working?
The git fetch command in the pipeline checkout step is failing on agents that have cached an old tag that was subsequently updated. This seems to be related to a [change](https://github.com/git/git/commit/0bc8d71b99e91c9e90b519073b639a5066119591) in how git fetch handled tags that was introduced in git version 2.20. Previously --force was implicitliy applied when fetching tags, but now it's not, so git fetch --tags can fail if the upstrem tags changed without manually specifying --force.

It looks like the git version of the agent was bumped from 1.18 to 1.21 in #2166, so adding an explicit --force to the list of options in GitCommandManager.GitFetch and GitCliManager.GitFetch should match the old behavior and prevent this particular error.

## Example error log:
```
##[section]Starting: Checkout
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Syncing repository: *** (Git)
Prepending Path environment variable with directory containing 'git.exe'.
##[command]git version
git version 2.21.0.windows.1
##[command]git lfs version
git-lfs/2.1.0 (GitHub; windows amd64; go 1.8.1; git bd2c9987)
##[command]git config --get remote.origin.url
##[command]git clean -ffdx
##[command]git reset --hard HEAD
HEAD is now at 6edf0415 ***
##[command]git config gc.auto 0
##[command]git config --get-all http.***
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --tags --prune --progress --no-recurse-submodules origin
remote: Azure Repos        
remote: 
remote: Found 37 objects to send. (7 ms)        
From ***
   518103d2..1c1f03e1  master         -> origin/master
 ! [rejected]          16.1_P3        -> 16.1_P3  (would clobber existing tag)
##[warning]Git fetch failed with exit code 1, back off 4.465 seconds before retry.
##[command]git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --tags --prune --progress --no-recurse-submodules origin
From ***
 ! [rejected]          16.1_P3    -> 16.1_P3  (would clobber existing tag)
##[warning]Git fetch failed with exit code 1, back off 4.481 seconds before retry.
##[command]git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --tags --prune --progress --no-recurse-submodules origin
From ***
 ! [rejected]          16.1_P3    -> 16.1_P3  (would clobber existing tag)
##[error]Git fetch failed with exit code: 1
##[section]Finishing: Checkout
```

**Comment by TingluoHuang** [comment]
@danegsta thanks for reporting this.
@juliobbv we should fix this.

**Comment by geofflamrock** [comment]
If anyone is facing this issue before the fix lands in a released agent version, it seems that setting

```
workspace:
  clean: all
```

for yaml builds works, although this will re-clone the entire repo on every build (which may not be ideal I suppose).
