### ISSUE TITLE
Exit code 100 returned from process: file name 'tf', arguments 'eula -accept' / Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:http://myserver/mycollection/" -jwt:*** -noprompt'.

### ISSUE THREAD

**Issue by jjbencomo** [microsoft/azure-pipelines-agent#2245]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.136.1 / 2.150.3
OS of the machine running the agent? OSX - macOS Mojave Version 10.14.4

## What's not working?
After starting a new build and error executing the tf command comes up.

##[section]Starting: Get Sources
Prepending PATH environment variable with directory containing 'tf'.
##[debug]PATH: '/Users/Shared/Agents/vsts-agent-osx-x64-2.136.1/externals/tee:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands'
##[command]tf eula -accept
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'eula -accept'

and after that another by querying the Workspace information

##[warning]Exit code 100 returned from process: file name 'tf', arguments 'eula -accept'.
Querying workspace information.
##[debug]tf workspaces -format:xml "-collection:http://myserver/mycollection/" -jwt:*** -noprompt
##[error]Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:http://myserver/mycollection/" -jwt:*** -noprompt'.
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:http://myserver/mycollection/" -jwt:*** -noprompt'.

I tried to execute both manually and the tf seemed to be unresponsive. No error received.
Also tried to installed TEE via Homebrew and executing it manually from the Terminal and no response nor error.

**Comment by TingluoHuang** [comment]
@jjbencomo try https://github.com/microsoft/azure-pipelines-agent/issues/1273#issuecomment-427464041

**Comment by jjbencomo** [comment]
Hi @TingluoHuang! Thank you for your fast response. After a long search, the thread you sent me was a good hint to solve the problem. Apparently the Java version was incompatible. I uninstalled the 12 version (https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html) and installed the 8 version ( https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) and it worked.

Previous Java (not working):
Java 12.0.1 2019-04-16
Java (TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot (TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

New Java (working):

java version "1.8.0_211"
Java (TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
