### ISSUE TITLE
Environment Variables From Variable Groups Should be loaded as it is

### ISSUE THREAD

**Issue by blueelvis** [microsoft/azure-pipelines-agent#2248]
## Agent Version and Platform
2.150.3

## OS of the machine running the agent?
Linux (Ubuntu 16.04)

## What's not working?
I have a variable group which has the following environment variable names -
1. ConfigStorageAccountContainerName
2. ConfigStorageAccountName
3. DeploymentServicePrincipalAppId
4. DeploymentServicePrincipalSecret (Secret Credential)

For, 1, 2 & 3, what is happening is that these environment variables are being fully capitalized and then loaded into the operating system and  when the script is trying to consume the environment variable with the exact same name as above, it is failing to find it. As you can see from the snippet, it has been converted to all caps -
![image](https://user-images.githubusercontent.com/6985763/57527417-3b88ae00-734d-11e9-8804-fdfb3ca0e964.png)

But, for 4, which is again passed as an Environment Variable to the "PowerShell Task" as per guidelines, that gets created as shown above -
![image](https://user-images.githubusercontent.com/6985763/57527495-7985d200-734d-11e9-9c6e-941d46cf2150.png)

Is it possible to generalize this? PowerShell on Linux checks the environment variables case-sensitively whereas that is not the case on Windows.

Thanks,
Pranav

**Comment by juliobbv** [comment]
Hi @blueelvis,

One thing to keep in mind is that 'Pipeline variables' or 'Variables' (defined at the build/release level), and 'Environment variables' (defined in your Powershell task) are two related, but fundamentally different concepts.

Pipeline variables are exposed to tasks as environment variables after undergoing a name transformation. [This article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-pipeline) explains all the details of such transformation:

>The syntax for using these environment variables depends on the scripting language. Name is upper-cased, . replaced with _, and automatically inserted into the process environment. Here are some examples:
>
>Batch script: `%VARIABLE_NAME%`
>PowerShell script: `$env:VARIABLE_NAME`
>Bash script: `$VARIABLE_NAME`

The above means that you'd want to manually perform the translation above if you want to keep environment variable names consistent.

Hope this explanation helped. 😊

Thanks,
Julio

**Comment by blueelvis** [comment]
@juliobbv  -- Thanks for thee explanation! Just curious, is there a reason why transformation is done in 1 place but not the other?
