### ISSUE TITLE
git submodule commands fail on self

### ISSUE THREAD

**Issue by kmscode** [microsoft/azure-pipelines-agent#2249]
## Agent Version and Platform
Version of your agent? 

2.148.1 & 2.150.3

OS of the machine running the agent? 

Windows Server 2016

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

Org name:
intellicheck.visualstudio.com

## What's not working?
The pipeline's get sources task has "checkout submodules" checked:
![image](https://user-images.githubusercontent.com/16654335/57533662-4d962c80-730c-11e9-83c4-20f3fbb8d7a3.png)

But the git submodule commands fail:

```
##[command]git submodule sync
##[command]git -c http.https://{ORG_NAME}@dev.azure.com.extraheader="AUTHORIZATION: bearer ***" submodule update --init --force --depth=1
Submodule '{COMPONENT_BASE_NAME}-engine-common' (https://{ORG_NAME}.visualstudio.com/Development/_git/{COMPONENT_BASE_NAME}-engine-common) registered for path '{COMPONENT_BASE_NAME}-engine-common'
Submodule '{COMPONENT_BASE_NAME}-engine-windows-common' (https://{ORG_NAME}.visualstudio.com/Development/_git/{COMPONENT_BASE_NAME}-engine-windows-common) registered for path '{COMPONENT_BASE_NAME}-engine-windows-common'
Cloning into 'C:/agent/_work/2/s/{COMPONENT_BASE_NAME}-engine-common'...
fatal: could not read Username for 'https://{ORG_NAME}.visualstudio.com': terminal prompts disabled
fatal: clone of 'https://{ORG_NAME}.visualstudio.com/Development/_git/{COMPONENT_BASE_NAME}-engine-common' into submodule path 'C:/agent/_work/2/s/{COMPONENT_BASE_NAME}-engine-common' failed
Failed to clone '{COMPONENT_BASE_NAME}-engine-common'. Retry scheduled
Cloning into 'C:/agent/_work/2/s/{COMPONENT_BASE_NAME}-engine-windows-common'...
fatal: could not read Username for 'https://{ORG_NAME}.visualstudio.com': terminal prompts disabled
fatal: clone of 'https://{ORG_NAME}.visualstudio.com/Development/_git/{COMPONENT_BASE_NAME}-engine-windows-common' into submodule path 'C:/agent/_work/2/s/{COMPONENT_BASE_NAME}-engine-windows-common' failed
Failed to clone '{COMPONENT_BASE_NAME}-engine-windows-common'. Retry scheduled
Cloning into 'C:/agent/_work/2/s/{COMPONENT_BASE_NAME}-engine-common'...
fatal: could not read Username for 'https://{ORG_NAME}.visualstudio.com': terminal prompts disabled
fatal: clone of 'https://{ORG_NAME}.visualstudio.com/Development/_git/{COMPONENT_BASE_NAME}-engine-common' into submodule path 'C:/agent/_work/2/s/{COMPONENT_BASE_NAME}-engine-common' failed
Failed to clone '{COMPONENT_BASE_NAME}-engine-common' a second time, aborting
##[error]Git submodule update failed with exit code: 1
##[section]Finishing: Checkout
```

## Agent and Worker's Diagnostic Logs

[logs.zip](https://github.com/microsoft/azure-pipelines-agent/files/3166874/logs.zip)

**Comment by kmscode** [comment]
So some additional notes:

- MS Hosted build agents do not have this problems
- On self-hosted using latest with with system.prefergitfrompath does not resolve the problem 
- On self-hosted using the relative path in the .gitmodules file **_appears to resolve this issue_** (reference: https://github.com/Microsoft/azure-pipelines-agent/issues/577#issuecomment-253138869 that my co-worker was able to dig out - my google-fu was lacking today)


So I guess the proper description of this issue now is git submodules fail when submodules point to the full path of the repo? Though I haven't tested any submodules that are in an external/3rd party repo where the full path would be required...

Relative paths do appear to be supported by git directly, so it's a viable solution for me:
https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-add-bltbranchgt-f--force--nameltnamegt--referenceltrepositorygt--depthltdepthgt--ltrepositorygtltpathgt

> This may be either an absolute URL, or (if it begins with ./ or ../), the location relative to the superproject’s default remote repository

**Comment by TingluoHuang** [comment]
@kmscode if your submodules are in the same VSTS/AzureDevOps account, i would suggest to use relative path when register submodules to your main repository as the following doc described, then you don't have to worry about dev.azure.com vs. *.visualstudio.com
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#checkout-submodules

**Comment by kmscode** [comment]
Thanks @TingluoHuang - This is what I did to get around the problem. However, I still believe that there isa bug floating around somewhere with the build agent. The full path is valid syntax in the .gitmodules, yet authentication fails when pulling the submodules via the full path.

**Comment by juliobbv** [comment]
Hi @kmscode,

I'm following up on this issue. One question for you: when you mentioned that authentication didn't work with submodules with full paths, were you using the same base URL (either dev.azure.com/<orgname> or <orgname>.visualstudio.com) between the parent repository, and each of the submodule references?

The reason I ask is that currently we don't support mix-and-matching old and new style URLs, when the agent instructs git to checkout files.

**Comment by kmscode** [comment]
Hi @juliobbv,

Thanks for the follow up...

The URLS for the submodules were using *.visualstudio.com.

Our org accesses everything via *.visualstudio.com - is that URL effectively deprecated?

Thanks again!

**Comment by juliobbv** [comment]
I see, thanks for the clarification.

\*.visualstudio.com URLs are deprecated in the sense that users are encouraged to switch to the newer dev.azure.com\*. However, \*.visualstudio.com URLs in submodules are still supported, even as full paths. I'll take a look and see if I can repro the issue on my end.

**Comment by juliobbv** [comment]
BTW @kmscode, I tried the scenario with my local account. Both the top-level and submodule repos were checked out successfully with full *.visualstudio.com paths, so I don't believe there's a bug here.

```
[submodule "submodule"]
	path = submodule
	url = https://juliobv.visualstudio.com/DefaultCollection/git/_git/sub
```

```
##[command]git checkout --progress --force d586dddd544623ad3917fa7ba669eb80448542db
Note: checking out 'd586dddd544623ad3917fa7ba669eb80448542db'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d586ddd Updated azure-pipelines.yml
##[command]git submodule sync
##[command]git -c http.https://juliobv.visualstudio.com.extraheader="AUTHORIZATION: bearer ***" submodule update --init --force
Submodule 'submodule' (https://juliobv.visualstudio.com/DefaultCollection/git/_git/sub) registered for path 'submodule'
Cloning into 'E:/ap-agent/_layout/_work/1/s/submodule'...
Submodule path 'submodule': checked out 'bd82b5ce9d4c1296e972a1ceb06a5b9f0e0e96aa'
##[section]Finishing: Checkout
```

Given the results above (and also because relative paths is the preferred approach to specify submodules), I'll close this issue.

**Comment by XzaR90** [comment]
@joeax How can I change that setting, it is disabled for me.
![image](https://user-images.githubusercontent.com/5103382/159156255-28d89bfd-bba4-44de-acc3-6b9c7e81e67d.png)
