### ISSUE TITLE
Creating git label from bash script is not working

### ISSUE THREAD

**Issue by laczau** [microsoft/azure-pipelines-agent#2257]
Hi!
I'm having troubles running git commands from script. What I'm trying to do is to create a new tag on each merge commit from pipelines automatically.
Since we build the sw for many platforms (AIX, hp-unix, etc...), our yml file is quite simple and everything is basically handled by a bash script (build.sh) and I'd like to create the git tag from that script.

yml snippet:
steps:
  - checkout: self
    persistCredentials: true

  - script: |
      export BUILDID="$(Build.BuildId)"
      export BUILDREASON="$(Build.Reason)"
      export BUILDBRANCH="$(Build.SourceBranchName)"
      export QUEUED_BY="$(Build.QueuedBy)"
      export SYSTEM_ACCESSTOKEN="$(System.AccessToken)"
      ./build.sh
    displayName: 'Building product'
    failOnStderr: false

bash script snippet:
`git tag ${git_tag}`
`git -c http.extraheader="AUTHORIZATION: bearer ${SYSTEM_ACCESSTOKEN}" push origin ${git_tag} >> ~/giterr.txt 2>&1`

I read the following error in giterr.txt:

`remote: 001f# service=git-receive-pack
remote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\1a17aecc-befc-4727-832c-8b8c73d1e7c4', scope 'repository'.
remote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\1a17aecc-befc-4727-832c-8b8c73d1e7c4', scope 'repository'.
fatal: unable to access 'https://1id@dev.azure.com/***/***/_git/***/': The requested URL returned error: 403`

I'm not the administrator of the project in devops, but I'm pretty sure that I have the necessary rights (create tag: allow inherited).

**Comment by TingluoHuang** [comment]
@laczau when the build running, it's not running as you, it's running as service account `Build\1a17aecc-befc-4727-832c-8b8c73d1e7c4`, you need to grant that account permission.
![image](https://user-images.githubusercontent.com/1750815/57930008-d53ae880-7882-11e9-8fd5-ebbf0bf845b0.png)

**Comment by laczau** [comment]
You are right, this option was not set! Thank you!

**Comment by whiskeysierra** [comment]
What exactly is the "Create Tag" permission doing then?

> Can push tags to the repository. 
>
> https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page

Sounds like it should be enough.
