### ISSUE TITLE
Parallel upload of code coverage files.

### ISSUE THREAD

**Issue by mitchdenny** [microsoft/azure-pipelines-agent#2262]
I would like to start a conversation about improving the performance of upload of code coverage files in Azure Pipelines. The Azure SDK team has a number of mono-repos where the client libraries for each of the Azure services is present. When we do a full test pass there is a very large amount of code-coverage data collected and it can take 7-9 minutes to upload the files from a full test pass.

After looking at the code coverage publishing task, and following the implementation I found that there is code within the agent code base which uploads the content to the file container service. The code is serialized.

```csharp
public async Task PublishCodeCoverageFilesAsync(IAsyncCommandContext context, Guid projectId, long containerId, List<Tuple<string, string>> files, bool browsable, CancellationToken cancellationToken)
{
    var publishCCTasks = files.Select(async file =>
    {
        var browsableProperty = (browsable) ? bool.TrueString : bool.FalseString;
        var artifactProperties = new Dictionary<string, string> {
            { ArtifactUploadEventProperties.ContainerFolder, file.Item2},
            { ArtifactUploadEventProperties.ArtifactName, file.Item2 },
            { ArtifactAssociateEventProperties.ArtifactType, ArtifactResourceTypes.Container },
            { ArtifactAssociateEventProperties.Browsable, browsableProperty },
        };

        FileContainerServer fileContainerHelper = new FileContainerServer(_connection, projectId, containerId, file.Item2);
        await fileContainerHelper.CopyToContainerAsync(context, file.Item1, cancellationToken);
        string fileContainerFullPath = StringUtil.Format($"#/{containerId}/{file.Item2}");

        Build.BuildServer buildHelper = new Build.BuildServer(_connection, projectId);
        var artifact = await buildHelper.AssociateArtifact(_buildId, file.Item2, ArtifactResourceTypes.Container, fileContainerFullPath, artifactProperties, cancellationToken);
        context.Output(StringUtil.Loc("PublishedCodeCoverageArtifact", file.Item1, file.Item2));
    });

    await Task.WhenAll(publishCCTasks);
}
```

I'd like to propose that we allow for greater parallelism in this upload process. It might be as easy as doing a ```Parallel.ForEach(...)``` over the set of files, or more involved (requires more investigation). However before I go an put any effort into doing this and submitting a PR I wanted to flag the issue here to see whether there would be any concerns.

The one that I do think we need to look at is whether parallelism would cause issues for on-premises Azure DevOps Server installations which can't spread the requests across a larger pool of ATs (so could result in request queuing for unrelated requests).

My mitigation for that would be to have the degree of parallelism controllable and for on-premises based builds set the parallelism to 1.

**Comment by acesiddhu** [comment]
@TingluoHuang your thoughts on this? does Filecontainerserver supports uploading file in parallel. i assume it should

**Comment by TingluoHuang** [comment]
@mitchdenny what's the size of those code coverage files? and how many are they?
@acesiddhu the `FileContainerServer` will do parallel upload (2 thread uploading) when you request it to upload a folder.

**Comment by mitchdenny** [comment]
@TingluoHuang we have ~6500 files being uploaded per leg of the run. There are 7 legs that publish code coverage so we are uploading about 45,500 files in total, but because of parallelism its the 6500 we are trying trying to optimize. I wonder whether this could be cut over to use the same back-end as Pipeline Artifacts?

**Comment by TingluoHuang** [comment]
@mitchdenny of course we can switch to use ArtifactService, we just need someone change the agent and the service.

**Comment by mitchdenny** [comment]
Do you think the service could handle greater parallelism on FCS today (quick fix?)

**Comment by TingluoHuang** [comment]
@mitchdenny FCS should be fine since lots of people are still using the old upload/down task that using FCS

**Comment by mitchdenny** [comment]
OK - I'll look at creating a PR that does more parallelism. I was thinking making it parallel to the number of cores on the agent?

**Comment by karanjitsingh** [comment]
> OK - I'll look at creating a PR that does more parallelism. I was thinking making it parallel to the number of cores on the agent?

Hi @mitchdenny, did you get around to creating a PR for this?
PS: You can keep parallelism = cores on agent / 2

**Comment by mitchdenny** [comment]
@karanjitsingh I didn't. We ended up restructuring our pipelines to build less which resulted in less coverage files per pipeline run so this became less of an issue for us. From my point of view this can be closed, but you could certainly take on optimizing the upload of these files if you wanted to :)
