### ISSUE TITLE
Remote YAML Template over HTTP

### ISSUE THREAD

**Issue by dferretti-fig** [microsoft/azure-pipelines-agent#2271]
I see you can use templates from remote git repositories with `- template: common.yml@templates` which references an entry from the `repositories` section. Is there a way I can use a similar syntax to define a template location located at an HTTP endpoint?

And this might be dipping too much into feature request territory, but would it be possible to provide parameters to this template HTTP request? I'm envisioning something like an HTTP POST to an HTTP endpoint I control, that receives:
- the git repo location
- the commit sha
- the branch name
- maybe the same set of parameters that exist for the REST endpoint server tasks
And this endpoint is able to use custom logic to generate a dynamic YAML template to return. 

Is something like that currently possible or on the roadmap?

**Comment by dferretti-fig** [comment]
This would allow me to analyze the provided repo, for example count the number of C# projects inside it that fit a certain criteria, and return a YAML template that contains a certain number of server or agent tasks to correspond to each project. 
I don't know if something like this is possible currently - if I reference a static git repo for templates it has no way of customizing what it provides based on the calling pipeline.

**Comment by dferretti-fig** [comment]
After poking around the source, I see the agent just receives individual jobs from AzDO, so its place in the system falls after any yaml generating or retrieving - so I'm going to move this over to the azure-pipelines-yaml repo. 
Will just leave open for a few days out of curiosity to see if anyone knows if something like this is possible or planned.

**Comment by TingluoHuang** [comment]
Closing since this issue is not scoped to the agent itself and you already logged an issue in the azure-pipelines-yaml repository.

**Comment by TingluoHuang** [comment]
the agent doesn't deal with yaml file at all, the server pulls all templates and convert to a JSON based job message for the agent.
