### ISSUE TITLE
Build fails during second lfs fetch in Checkout job if the repository uses Git LFS - Log shows Git credential and password errors

### ISSUE THREAD

**Issue by edgariscoding** [microsoft/azure-pipelines-agent#2272]
## Having issue with Tasks?
During the Checkout job of the build process, the agent checks the Git version (2.21.0.windows.1) and the Git LFS version (2.7.1). Based on some research I've done, it seems like version 2.7.1 of Git LFS may be causing this issue. Version 2.7.2 was released a few days ago to address this but my agent still has 2.7.1 and I'm not sure how to update this specific package. Running the build on a repository with the same codebase that does not use LFS works perfectly fine, it's only when LFS is used that I receive these errors. The errors also seem to be related to credential/password issues... so if there's something else you can suggest to fix this, I'd be glad to try. 

See the GitHub issues below for details:
https://github.com/git-lfs/git-lfs/issues/3571
https://github.com/microsoft/azure-pipelines-image-generation/issues/800

## Agent Version and Platform
Version of your agent? 2.150.3

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com
If dev.azure.com, what is your organization name? https://dev.azure.com/CiraConnect

## What's not working?
Here are some of the relevant lines from the Checkout Job log:
```
##[command]git version
git version 2.21.0.windows.1
##[command]git lfs version
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
##[command]git init "D:\a\1\s"
Initialized empty Git repository in D:/a/1/s/.git/
##[command]git remote add origin https://MyOrg@dev.azure.com/MyOrg/My%20Project/_git/Proj
##[command]git config gc.auto 0
##[command]git config --get-all http.https://MyOrg@dev.azure.com/MyOrg/My%20Project/_git/Proj.extraheader
##[command]git config --get-all http.proxy
##[command]git lfs install --local
Updated git hooks.
Git LFS initialized.
##[command]git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --tags --prune --progress --no-recurse-submodules origin
remote: Azure Repos        
remote: 
remote: Found 565657 objects to send. (1283 ms)        
Receiving objects:   0% (1/565657)   
Receiving objects:   1% (5657/565657) 
Receiving objects: 100% (565657/565657), 2.11 GiB | 24.13 MiB/s, done.
...
Resolving deltas:   0% (0/436110)   
Resolving deltas:   1% (4362/436110)   
...
Resolving deltas: 100% (436110/436110), done.
...
##[command]git -c http.https://MyOrg@dev.azure.com.extraheader="AUTHORIZATION: bearer ***" lfs fetch origin 4cbe37*
fetch: Fetching reference 4cbe37*
fatal: could not read Password for 'https://MyOrg@dev.azure.com': terminal prompts disabled
batch response: Git credentials for https://MyOrg@dev.azure.com/MyOrg/My%20Project/_git/Proj not found.
error: failed to fetch some objects from 'https://MyOrg@dev.azure.com/MyOrg/My%20Project/_git/Proj.git/info/lfs'
##[warning]Git lfs fetch failed with exit code 2, back off 5.844 seconds before retry.
##[command]git lfs logs last
No logs to show
##[error]Git lfs fetch failed with exit code: 2. Git lfs logs returned with exit code: 0.
```

**Comment by juliobbv** [comment]
Hi @edgariscoding,

A new Windows image containing version 2.7.2 of `git lfs` will be deployed, expected to begin this week. The Checkout Job should eventually start working once the such image gets deployed to CiraConnect.

**Comment by TingluoHuang** [comment]
Closing this issue since it's not agent problem, please reopen if needed. :)
