### ISSUE TITLE
Nuget push task self signed certificate

### ISSUE THREAD

**Issue by gnimor** [microsoft/azure-pipelines-agent#2276]
The agent is running for a self hosted devops 2019 instance. I have configured a build pipeline with a NUGET push task. The devops server is using a self signed certificate. All steps in the build task work as expected until it comes to the "nuget push" task. The task fails complaining about the self signed certificate. The debug log is:

> 2019-05-27T11:20:53.6186076Z ##[debug]Quirks for 4.4.1.4656:
> 2019-05-27T11:20:53.6190911Z ##[debug]    NoTfsOnPremAuthConfig
> 2019-05-27T11:20:53.6193565Z ##[debug]NuGet.ForceEnableCredentialProvider=undefined
> 2019-05-27T11:20:53.6197876Z ##[debug]NuGetTasks.IsHostedTestEnvironment=undefined
> 2019-05-27T11:20:53.6199523Z ##[debug]System.ServerType=OnPremises
> 2019-05-27T11:20:53.6199885Z ##[debug]V1 credential provider is enabled
> 2019-05-27T11:20:53.6200212Z ##[debug]NuGet_ForceEnableCredentialProviderV2=undefined
> 2019-05-27T11:20:53.6201010Z ##[debug]NuGetTasks.IsHostedTestEnvironment=undefined
> 2019-05-27T11:20:53.6201375Z ##[debug]System.ServerType=OnPremises
> 2019-05-27T11:20:53.6201595Z ##[debug]V2 credential provider is disabled.
> 2019-05-27T11:20:53.6206431Z ##[debug]NuGet.ForceEnableCredentialConfig=undefined
> 2019-05-27T11:20:53.6206959Z ##[debug]NuGetTasks.IsHostedTestEnvironment=undefined
> 2019-05-27T11:20:53.6207274Z ##[debug]System.ServerType=OnPremises
> 2019-05-27T11:20:53.6207577Z ##[debug]Credential config is disabled due to on-prem quirks.
> 2019-05-27T11:20:53.6212825Z ##[debug]Agent.BuildDirectory=E:\Agent\Sources\2
> 2019-05-27T11:20:53.6213322Z ##[debug]build.buildId=21
> 2019-05-27T11:20:53.6218168Z ##[debug]feedPublish=841e0cef-c695-4cb8-80bc-7628c6dc0e0c
> 2019-05-27T11:20:53.6283525Z ##[debug]NuGet.OverwritePackagingCollectionUrl=undefined
> 2019-05-27T11:20:53.6288270Z ##[debug]Getting registry url from https://XXXXXXX/XXX/
> 2019-05-27T11:20:53.6289302Z ##[debug]Agent.ProxyUrl=undefined
> 2019-05-27T11:20:53.6312321Z ##[debug]Packaging.SavePublishMetadata=undefined
> 2019-05-27T11:20:53.6638974Z ##[debug]{"code":"DEPTH_ZERO_SELF_SIGNED_CERT"}
> 2019-05-27T11:20:53.6639620Z ##[debug]Waiting 100ms...
> 2019-05-27T11:20:53.7650257Z ##[debug]Retrying...
> 2019-05-27T11:20:53.7655608Z ##[debug]{"code":"DEPTH_ZERO_SELF_SIGNED_CERT"}
> 2019-05-27T11:20:53.7656161Z ##[debug]Waiting 200ms...
> 2019-05-27T11:20:53.9662634Z ##[debug]Retrying...
> 2019-05-27T11:20:53.9663853Z ##[debug]{"code":"DEPTH_ZERO_SELF_SIGNED_CERT"}
> 2019-05-27T11:20:53.9664090Z ##[debug]Waiting 400ms...
> 2019-05-27T11:20:54.3663282Z ##[debug]Retrying...
> 2019-05-27T11:20:54.3667359Z ##[debug]{"code":"DEPTH_ZERO_SELF_SIGNED_CERT"}
> 2019-05-27T11:20:54.3667996Z ##[debug]Waiting 800ms...
> 2019-05-27T11:20:55.1678366Z ##[debug]Retrying...
> 2019-05-27T11:20:55.1680592Z ##[debug]{"code":"DEPTH_ZERO_SELF_SIGNED_CERT"}
> 2019-05-27T11:20:55.1808537Z ##[error]Error: Error: self signed certificate

**Comment by TingluoHuang** [comment]
@gnimor https://github.com/microsoft/azure-pipelines-tasks might be a better place for this issue, that the repository for all in-the-box tasks.
how did you configure the agent with your server's self-signed certificate?
looks like the task is not follow the agent's certificate setting?

**Comment by gnimor** [comment]
So the configuration was no problem I just had to add the self signed certificate to the certificate store of the computer running the agent. Therefore I thought all tasks triggered by the agent should also work - which seems not to be the case.

**Comment by TingluoHuang** [comment]
One thing to noticed, not all the tools work with windows certificate store, during agent config there is a way to configure the agent knows about the self signed cert and then the agent can teach the tasks about your self signed cert.

I think during config you can do —sslcacert 
 Sorry I am on my phone, hard to typing.


https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2019#work-with-ssl-client-certificate

**Comment by TingluoHuang** [comment]
Closing since it's not an issue with the agent.
