### ISSUE TITLE
Cannot edit YAML files on Azure Devops interface

### ISSUE THREAD

**Issue by rafael-aero** [microsoft/azure-pipelines-agent#2290]
I'm hitting an issue similar to #2016, in which I cannot edit the YAML file being used by the build on Azure Devops - this happens to all the build pipelines I currently have on Azure Devops

![image](https://user-images.githubusercontent.com/8791811/59014688-822ed280-883d-11e9-93a5-359320586de5.png)

Already tried creating a new Personal Access Token as recommended in #2016, and change the settings for the pipeline, but the problem persists. 

The old and new tokens have the correct scope as per [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml):

> **If the repo is in a GitHub organization that you own**
> The PAT must have the required access scopes under Personal access tokens: repo, admin:repo_hook, read:user, and user:email.
> You must be added as a collaborator, or your team must be added, in the repository's settings under "Collaborators and teams".

**Comment by rafael-aero** [comment]
Not sure if useful, but all builds are working without issues - i.e. they queue and run fine, it's just the edit interface that is broken

**Comment by TingluoHuang** [comment]
The error means you are OAuth with GitHub, but the OAuth token might not have permission to that repository. you might want to report at https://developercommunity.visualstudio.com/spaces/8/index.html since this is not scoped to the pipeline agent

**Comment by TingluoHuang** [comment]
Closing since it's not an issue about the agent.
