### ISSUE TITLE
dotnet core system capabilities not detected in self hosted agents

### ISSUE THREAD

**Issue by RonakThakkar** [microsoft/azure-pipelines-agent#2291]
## Agent Version and Platform
Version of your agent? 2.150.3

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
visualstudio.com

## What's not working?
I have created a new VM in Azure to be used as a self-hosted agent which has .NET Core installed. I run commands to register this agent as a self-hosted agent in Azure Devops project. Everything works fine and the agent is registered.

But when I check the System Capabilities, I find that .NET Core is not registered as a system capability.

**Comment by juliobbv** [comment]
@RonakThakkar, the agent doesn't register .NET Core as a system capability.

We're in an ongoing process to deprecate the capability concept, so it's now up to the pipeline scripts and code to keep track of where the .NET core SDK and runtime directories are located on disk.

You can use either run the `dotnet --list-sdks` and `dotnet --list-runtimes` commands to find out where they are located, or you can install your own side-by-side copy.

**Comment by bitbonk** [comment]
If you are deprecate the capability concept, how would a build choose a a build agent from the pool that is fit for the job?

**Comment by kitingChris** [comment]
@juliobbv would you can you answer the question of @bitbonk ?
