### ISSUE TITLE
Self hosted agent unable to connect to Package source

### ISSUE THREAD

**Issue by Scott-Emberson** [microsoft/azure-pipelines-agent#2292]
## Agent Version and Platform
v2.150.3

OS of the machine running the agent?
Windows Server 2016

## Azure DevOps Type and Version
On-premises TFS 2017 Update 3

## What's not working?
The hosted agent is unable to connect to TFS package source when the agent has been connected to TFS via PAT over windows credentials. 

When trying to connect I am presented with the following error. "Please provide credentials for:...". After some investigation, I found that I should add credentials into the C:\User\{UserName}\AppData\Roaming\NuGet\NuGet.config. After adding the credentials via the following command:
`nuget sources add -name Company -source PackageSource -username Username -password PATofUser -configfile C:\User\{UserName}\AppData\Roaming\NuGet\NuGet.config`

The agent continues to fail to install the package. 
![image](https://user-images.githubusercontent.com/8268155/59157790-bd810980-8aa8-11e9-9a3f-588e83b367a5.png)

I am simply trying to install a package that we use in our builds.
`.\nuget.exe install NuGetPackageName -Source "PackageSource" -NoCache -DependencyVersion Highest -OutputDirectory "$(Build.SourcesDirectory)\PackageSource"`

This works fine on all our other servers that have been connected to TFS via windows credentials over PAT. This new server has to be connected via PAT as it's hosted on a different domain and we don't want to use local users.

**Comment by Scott-Emberson** [comment]
Was able to fix this in the end by setting the credentials in the AppData NuGet config by using the NuGet Add

**Comment by reuben-wcg** [comment]
I am getting an error similar to yours. My Nuget REstore task get stuck when executing this  line E:\Agent\vsts-agent-win-x64-2.192.0\_work\_tool\NuGet\5.4.0\x64\nuget.exe restore E:\Agent\vsts-agent-win-x64-2.192.0\_work\2\s\SPV.sln -Verbosity Detailed -NonInteractive -ConfigFile E:\Agent\vsts-agent-win-x64-2.192.0\_work\2\s\.nuget\NuGet.Config

There is no error message nothing.
