### ISSUE TITLE
EACCESS seen on builds from certain types of PRs

### ISSUE THREAD

**Issue by MattGal** [microsoft/azure-pipelines-agent#2298]
@omeshp FYI.

## Agent Version and Platform
Version of your agent? 2.152.1

OS of the machine running the agent? OSX & Linux

## Azure DevOps Type and Version
dev.azure.com 

If dev.azure.com, what is your organization name? **dnceng**

## What's not working?
Random EACCESS failures in various places when the build comes from PRs:

Successful builds:
Direct master:
https://dev.azure.com/dnceng/public/_build/results?buildId=223004
PR: 
https://dev.azure.com/dnceng/public/_build/results?buildId=222302

EACCESS Failures:
https://dev.azure.com/dnceng/public/_build/results?buildId=222956

## Agent and Worker's Diagnostic Logs
Not available ; this happens on hosted too, maybe grab those?

**Comment by TingluoHuang** [comment]
@MattGal why this is an agent issue? but succeed build and failed build are using the same version agent. :)

**Comment by echesakovMSFT** [comment]
@TingluoHuang Can this be an issue with DownloadBuildArtifacts task?

The [last succeeded build](https://dev.azure.com/dnceng/public/_build/results?buildId=222302) uses version **0.151.0** 
The [first failing build](https://dev.azure.com/dnceng/public/_build/results?buildId=222368) uses version **0.152.2**

**Comment by TingluoHuang** [comment]
@echesakovMSFT it is highly possible since the version changed between 2 builds. :)

**Comment by MattGal** [comment]
@TingluoHuang I wasn't sure whether to blame Task / Agent, but it seems it got fixed overnight... so I'd bet someone in VSTS knows the root cause.

**Comment by TingluoHuang** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/10617
