### ISSUE TITLE
installdependencies.sh - WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

### ISSUE THREAD

**Issue by RonakThakkar** [microsoft/azure-pipelines-agent#2304]
## Agent Version and Platform
Version of your agent? 2.153.1

OS of the machine running the agent?
Linux - Canonical - UbuntuServer - 16.04-LTS

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization}

## What's not working?
I have created a Linux VM.
I have logged into Linux VM and downloaded https://vstsagentpackage.azureedge.net/agent/2.153.1/vsts-agent-linux-x64-2.153.1.tar.gz using wget
I have extracted the above file

Now when I run below command
sudo ./bin/installdependencies.sh

it works successfully, however WARNING: apt does not have a stable CLI interface. Use with caution in scripts. I read on internet which suggest to use apt-get instead.

**Comment by juliobbv** [comment]
I was reading up on what the this message means.

https://askubuntu.com/questions/990823/apt-gives-unstable-cli-interface-warning

Apparently, apt is a 'porcelain' command (vs apt-get which is a 'plumbing' command), where the output is not meant to be parse-able by scripts, and the format may be subject to change with newer versions. In the case of  `installdependencies.sh`, the script is only relying on the error codes for decision taking, so we should be fine with apt.

**Comment by TingluoHuang** [comment]
Closing for now, please reopen if needed.
