### ISSUE TITLE
Checkout/clean process can leave stale files on the file system

### ISSUE THREAD

**Issue by j0tt** [microsoft/azure-pipelines-agent#2307]
## Agent Version and Platform
Version: 2.153.2
OS: Windows

## What's not working?
In the event of a submodule moving, it is possible for the clean event to not clear out the old submodule's directory.

Our example was a header only submodule, `A`, was placed in `external\A`. And the person who committed it incorrectly added `external\` to the include paths so they could `#include "A\stuff.h"`.

We then moved submodule A to `external\A\include` so we can make the include path `external\A\include` and `#include "A\stuff.h"` still works.

This caused issues on agents who have built the previous tree after the fix because it looks like the agent is doing the following at checkout (with clean selected):
```
git clean -ffdx​
git reset --hard HEAD​
git submodule foreach git clean -ffdx​
git submodule foreach git reset --hard HEAD​
git submodule update --init --force --recursive
```

because the submodules were previously init'd, the first `git clean -ffdx` doesn't delete the submodule that is about to be moved, leaving undesired files on the agent, and in our case fails the build.
​
We solved this by running `git clean -ffdx` as the first step of the pipeline, directly after checkout, but I think the correct fix is to run `git submodule deinit --all --force` before the top level `git clean --ffdx`

**Comment by juliobbv** [comment]
Thanks @j0tt for reporting this issue.

I was reading up on [`git submodule` documentation](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-deinit-f--force--all--ltpathgt82308203). The main problem with `git submodule deinit` is that the command removes the entire submodule's work tree, which is something not very desirable for i.e. the `Clean Sources` strategy (which I believe it's the one being used by your pipeline). The vast majority of checkouts don't move submodules between runs, so work tree recreation would incur an unnecessary perf cost. 😟

There's this [gist](https://gist.github.com/nicktoumpelis/11214362) which suggests re-ordering the clean/reset commands, so submodule folder updates are naturally taken care of. This might be the way to go.

**Comment by j0tt** [comment]
Yeah, the negatives of deinit occurred to me later in the day. 

that gist looks good, but thinking further (and being nudged by the suggestion on the gist) running `git submodule sync` first _should_ update the config to point to the new module path, thus letting the top level `git clean -ffdx` clear out the old. Right?

**Comment by v-strob** [comment]
Is this something that might be worked on in the near future? We've been forced to do one of two workarounds:

1. Stop using the Azure Pipelines built-in submodule checkout option and instead do a submodule deinit and init during each build, which can add up to an additional 15 mins to the total pipeline run time.
2. Make sure all supported branches use the same set of submodules in the same locations so the built-in cleanup steps are successful

If we were to submit a fix that got accepted, roughly how long would it take to become available as an upgrade in Azure Pipelines?

**Comment by jtpetty** [comment]
@v-strob - I apologize for taking so long to answer your question. We  had a number of new features go into the agent which of course led to some unfortunate issues, but now that 2.164.6 of the agent is out, we should be much more responsive in reviewing PRs.

As for your main question, I am going to defer to @vtbassmatt  as to whether or not this is something we can take on and how it might impact other customers.

**Comment by vtbassmatt** [comment]
I'm modestly "pro" this feature. Anything to make working with submodules less irritating. Big questions to answer would be:
- what happens if the Git repo doesn't have any submodules, is that command still safe?
- what other side effects does it have, either with or without submodules?
- is this globally desirable for all customers or is it a targeted fix?

@j0tt if you're still interested in the problem space, getting your input on the first two questions would be helpful. @jtpetty and I can confer about the third. Assuming all goes well, then we'd be able to take a PR (with tests) and get it into the agent within a sprint. Sprints here are 3 weeks long.

**Comment by vtbassmatt** [comment]
Whoops also @v-strob since it was actually you who asked about submitting a PR :grin:

**Comment by v-strob** [comment]
When I run each of the git submodule commands mentioned above on a repo that doesn't have submodules, I get no errors and no output so it seems pretty safe to me. So if the gist ordering linked above means no more stale files, that would be good for everyone.

**Comment by vtbassmatt** [comment]
We'd likely accept a PR on this if you want to submit one. We have [some tests](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Test/L0/Worker/Build/GitSourceProviderL0.cs) in this area, so please make sure you update those and add any new ones that are needed.
