### ISSUE TITLE
Unable to locate executable file: 'bash' and others missing that are in PATH (packer, ansible, any.)

### ISSUE THREAD

**Issue by rparsonsbb** [microsoft/azure-pipelines-agent#2329]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
**Yup.**

## Agent Version and Platform
Version of your agent? 
**2.153.2**

OS of the machine running the agent? OSX/Windows/Linux/...
**Ubuntu 16.04**

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
**dev.azure.com**

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com
**BlackBookUSA**

## What's not working?
Please include error messages and screenshots.
**No executable files able to be located, from bash to packer to ansible etc. This is a clean, minimal install from the community ubuntu 16.04 AWS ami including packer, ansible and the ADO agent**
[no_bash.txt](https://github.com/microsoft/azure-pipelines-agent/files/3337368/no_bash.txt)
[no_ansible-playbook.txt](https://github.com/microsoft/azure-pipelines-agent/files/3337369/no_ansible-playbook.txt)
```
ubuntu@ip-10-99-99-195:~/ado-agent$ which packer
/usr/local/bin/packer
ubuntu@ip-10-99-99-195:~/ado-agent$ which ansible-galaxy
/usr/bin/ansible-galaxy
ubuntu@ip-10-99-99-195:~/ado-agent$ which bash
/bin/bash
ubuntu@ip-10-99-99-195:~/ado-agent$ ./run.sh 
Scanning for tool capabilities.
Connecting to the server.
2019-06-28 02:27:52Z: Listening for Jobs
2019-06-28 02:28:34Z: Running job: Job
2019-06-28 02:28:46Z: Job Job completed with result: Failed
^CExiting...
```

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.
[_diag.zip](https://github.com/microsoft/azure-pipelines-agent/files/3337364/_diag.zip)

**Comment by rparsonsbb** [comment]
:/ someone added a path variable that overwrote the _actual_ path, and I didn't see it

**Comment by dennisroche** [comment]
To highlight this further as I just suffered through a few hours of debugging this. 

You will get this error if you have a **variable** named `path` in your pipeline as overwrites the environment variable on the agent. 

```
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  configuration: Release
  platform: Any CPU
  path: src/MyProject

steps:
  - script: |
      printenv
```

💥 🤦‍♂
