### ISSUE TITLE
Pull request build sequential stage and stage re-run checkout behaviors are not constant

### ISSUE THREAD

**Issue by pjcollins** [microsoft/azure-pipelines-agent#2330]
The pull request "revision" that is checked out can "drift" in between stages in a multi-stage pipeline, or when a partial rebuild is triggered. If the target branch of a pull request (e.g. `master`) changes in between stages, the merge commit which is checked out in subsequent stages will not match the commit from the first stage. As an example:

Stage 1:
```
##[command]git checkout --progress --force refs/remotes/pull/3296/merge
HEAD is now at 7a04c13d Merge 6d6b90779d04fb646a9bd12b4faac85285917b43 into 638e3b1bf1d0715d394fb21f3d3d461c2d305af1
```
Stage 2 (30 minutes later, or hours later if a failure occurred and a stage rebuild is triggered):
```
##[command]git checkout --progress --force refs/remotes/pull/3296/merge
HEAD is now at 1d54cfc4 Merge 6d6b90779d04fb646a9bd12b4faac85285917b43 into aba094702eaf599ad8f9c74fdd5d3799307bfbf0
```

Shouldn't the revision of the target branch also be constant for each pull request build instance?

**Comment by juliobbv** [comment]
Hi @pjcollins,

I was checking with a co-worker who works on multi-stage pipelines, and I was told that there was a change a few sprints ago to not update the revision used to checkout git sources the between stages. Is this issue still repro'ing for you as of today?

Thanks,
Julio

**Comment by pjcollins** [comment]
@juliobbv I spent some time testing this today with a small repro and it looks like this has not been resolved entirely. If I attempt to "re-run" a stage which failed in a PR against master, _after_ more commits have landed in master, those changes from master are still being pulled in. I'm using the Azure Pipelines GitHub app to "re-run" a failed stage, which results in an additional "attempt" being added to the failed stage. However, the merge commit used for the initial attempt and previous stages does not match the merge commit used for the "re-run" attempt on the same build instance.
