### ISSUE TITLE
BYOS Feedback

### ISSUE THREAD

**Issue by bgoeppner** [microsoft/azure-pipelines-agent#2336]
This is actually exactly what we are looking for: Using an elastic pool with our own images. 
Unfortunately, we cannot use the hosted images because 
1. Our workspace/repo is about 100GB and therefore too big for the hosted agents (I think they have 20GB?)
2. We need some 3rd party software installed that is not available on hosted pools. 

Currently we have a fixed size pool, but agents are ideling most of the time, which is expensive. 
As a workaround, we are looking into Azure Functions to start and stop agents via serverless phases at the beginning and end of our job, but the elastic pool just sounds great! :rocket:

Please, we want this! And we are happy to be alpha tester and give some feedback if you want to...

**Comment by bryanmacfarlane** [comment]
@zachariahcox

**Comment by vijayma** [comment]
@bgoeppner Can you let us know the name(s) of Azure DevOps org(s) where you would like to preview this feature?

**Comment by bgoeppner** [comment]
Hi @vijayma, this sounds awesome! I am following the roadmap and release-notes since the feature was planned for 2020Q1 😁 Great to hear about an update. 

**The org would be cmd-sw.**

I have to say I recently moved to a different company, but I will let my former colleagues - who are still waiting for this - know.

Thanks for your awesome work!

**Comment by ulrich-schreck-tfs** [comment]
Hi @vijayma,
I´m one of Ben´s former colleagues and yes we ware still waiting for this and it would really be great to preview this feature. 

Thanks in advance
