### ISSUE TITLE
Agent version 2.154.1 (Pre-Release) randomly stops during releases

### ISSUE THREAD

**Issue by ryanspletzer** [microsoft/azure-pipelines-agent#2337]
## Agent Version and Platform
Version of your agent? 2.154.1 (Pre-Release)

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? dev.azure.com

If on-premises, which release? N/A

If dev.azure.com, what is your organization name? https://dev.azure.com/adsk-des-dpe-paas or https://adsk-des-dpe-paas.visualstudio.com

## What's not working?
Agent pre-release version service seems to randomly stop during releases. (Or, it may be randomly stopping more frequently than just during releases, we just notice it during releases -- may happen during long builds, too, uncertain as we don't have long builds.)

I was watching the agent service as it did a build with `while ($true) { get-service | ?{$_.name -like "*vsts*"}; start-sleep -Seconds 1 }`

![image](https://user-images.githubusercontent.com/1481108/60607655-b4bfe280-9d8b-11e9-8dbb-cd96dbb4f60d.png)

This is what it looks like when it happens during a release:

![image](https://user-images.githubusercontent.com/1481108/60607914-37e13880-9d8c-11e9-894d-a02678ae588a.png)

One may ask why we're running a pre-release version of the agent -- the reasoning for this is the xVSTSAgent DSC Resource provided by Microsoft at [this repo](https://github.com/microsoft/VSTSAgent.PowerShell) (which we're using to deploy our build VM's) by default will look for the latest version of the agent from this agent repo, and if there happens to be a pre-release version out at the time of deployment it may pick that.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

Logs included here:

[logs.zip](https://github.com/microsoft/azure-pipelines-agent/files/3355858/logs.zip)

**Comment by TingluoHuang** [comment]
@ryanspletzer can you check the event log to see why the service gets stopped?

**Comment by ryanspletzer** [comment]
@TingluoHuang Yes, so I see:

![image](https://user-images.githubusercontent.com/1481108/60609411-9c51c700-9d8f-11e9-90f7-fbf4730375ee.png)

Followed immediately by:

![image](https://user-images.githubusercontent.com/1481108/60609457-b1c6f100-9d8f-11e9-9d1d-25a13fbdf7ae.png)

Followed immediately by:

![image](https://user-images.githubusercontent.com/1481108/60609476-bc818600-9d8f-11e9-99b3-3c5465d0e48a.png)

On second thought I think this may be an issue with DSC doing its apply and autocorrect. It's odd because we hadn't seen this before but perhaps something about its Test-TargetResource every 15 minute consistency check is now out of date with what is going on in the newer versions of the agent (because that DSC Resource hasn't been touched in a year).

Apologies, feel free to close. :)
