### ISSUE TITLE
Powershell Agent does not subscribe to force completed events

### ISSUE THREAD

**Issue by thboop** [microsoft/azure-pipelines-agent#2338]
## Agent Version and Platform
Version of your agent? 2.152.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
https://dev.azure.com/mseng

## What's not working?
The Powershell Agent does not subscribe to force completed events. This can result in agents running powershell builds that do not terminate the powershell instance for whatever reason continuing to run until the timeout occurs, even if they have executed all commands. See the original issue posted here: https://github.com/microsoft/azure-pipelines-task-lib/issues/410

**Comment by vtbassmatt** [comment]
I think this should read the PowerShell handler doesn't subscribe to force completed events. It looks like we're [breaking into the debugger](https://devblogs.microsoft.com/powershell/powershell-break-all-command/) which is a mistake in a CI agent. It looks like PowerShell Core has [opted to not have this on by default](https://github.com/PowerShell/PowerShell/pull/4283) when running `-NonInteractive`.

In a 15 minute session of random searching, I don't see how to make PowerShell 5 and below mimic this behavior. Maybe we can Beetlejuice @paulhigin for some help?

**Comment by stephenmichaelf** [comment]
@vtbassmatt Could you take another look at this?

**Comment by PaulHigin** [comment]
Sorry, I somehow missed this.  Yes, Ctrl+Break causes PowerShell to break into the script debugger.  Ctrl+C stops any running script.  

In older versions of PowerShell, Ctrl+Break  used to terminate the current session.  We could add that behavior back as an option, but it would require an update.

**Comment by vtbassmatt** [comment]
Thanks @PaulHigin - so should we be sending Ctrl+C and never Ctrl+Break to trigger the behavior we want?

**Comment by PaulHigin** [comment]
Yes.  But keep in mind that Ctrl+C sends a stop signal to the currently running PowerShell script or command.  If PowerShell is running a native command, it cannot respond to the stop signal until the command call returns.  So in a hang (waiting indefinitely for a native command call t return) situation, the stop signal will not be effective.

**Comment by vtbassmatt** [comment]
Gotcha, thanks. I'm not sure there's more we can do, then. We already try sending Ctrl+C first and wait a bit before sending Ctrl+Break. That should cover all the scenarios I think.
