### ISSUE TITLE
Unable to change the Build Sources Directory in Azure Pipeline Agent

### ISSUE THREAD

**Issue by Selvaraj1989** [microsoft/azure-pipelines-agent#2341]
Hi,

As per my build definition, I need to map the "build_sourcesdirectory" to a custom folder (like "D:\BuildSourceDirectory") instead of default build source directory (like "2\\s") and I am trying to update the Build Sources Directory in project.json (from SourceRootMapping folder) file of the Azure Pipeline Agent.

I am able to update the same in the project.json file, however the issue is that when the Build is queued, the value "build_sourcesdirectory" is replaced with default as "2\\s".

Below is the log I am getting which says that Build Source Directory is required to replace as "'D:\vsts-agent-win-x64-2.153.2\_work\2\s"

**Log file from Build :**
_Processed: ##vso[plugininternal.updaterepositorypath alias=__designer_repo;]D:\vsts-agent-win-x64-2.153.2\_work\2\s
Repository requires to be placed at 'D:\vsts-agent-win-x64-2.153.2\_work\2\s', current location is 'D:\BuildOutputDirectory'
Repository is current at 'D:\BuildOutputDirectory', move to 'D:\vsts-agent-win-x64-2.153.2\_work\2\s'.
Move existing repository 'D:\BuildOutputDirectory' to 'D:\vsts-agent-win-x64-2.153.2\_work\2\s' via staging directory 'D:\vsts-agent-win-x64-2.153.2\_work\_temp\_1_

Also, I have attached the "project.json" file for reference.

Hence, please help us to proceed further by answering the below questions : 
    
1. how to update the Build Source Directory to the custom folder? If unable to do that, how to point the Build Source directory to a custom folder (which is an option available in TFS 2018)

Azure Pipeline Agent Version: 2.153.2

Please let me know if you need any other information.
[project.txt](https://github.com/microsoft/azure-pipelines-agent/files/3367307/project.txt)

Thanks
Selvaraj C

**Comment by TingluoHuang** [comment]
@Selvaraj1989 you can't modify the mapping json file, that's internal to the agent. :)
we don't support you to put the folder into arbitrary location, it has to under a namespace folder, this is trying to prevent accidental collision with another build folder since those folders are reusable.

**Comment by Selvaraj1989** [comment]
Thanks @TingluoHuang for the confirmation. You mean to say modifying the "project.json" file inside SourceRootMapping folder is not supported since you mentioned that "can't modify mapping.json file", I am asking this again to reconfirm my understanding.

Also, I would like to know whether modifying the "project.json" is not supported starting from Azure DevOps Services because I was able to modify the Build Sources Directory to a custom folder in TFS 2018.

Please confirm.

Thanks
Selvaraj C

**Comment by TingluoHuang** [comment]
Yes, you should not modify that, anything we haven't publicly documented might change and we never hold compat on them. :)

**Comment by Selvaraj1989** [comment]
Thanks, @TingluoHuang for the confirmation once again.
