### ISSUE TITLE
Powershell script containing pipe causes failure

### ISSUE THREAD

**Issue by dkalbertson** [microsoft/azure-pipelines-agent#2342]
## Agent Version and Platform
2.153.2

Windows 7

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) 

https://lms-bioptigen.visualstudio.com

## What's not working?
I have a custom build script (Powershell) that pulls down a perforce repository containing our org's signing certificates. The script builds a temporary workspace spec and outputs it to standard output with the pipe that reads in the spec from standard input. i.e. 
`P4.exe -d "path_to_checkout_repo_to" client -o "unique_client_name" | p4.exe client -i`

This worked as expected on version 2.141.1 of the build agent. However, on version 2.153.2, I get errors from the p4.exe command line as well as `Syntax error in '﻿'.` from the execution of the build task.

[Diag.zip](https://github.com/microsoft/azure-pipelines-agent/files/3369502/Diag.zip)

**Comment by TingluoHuang** [comment]
@dkalbertson you are using a customized task, you might need to find the owner of that task and report the error.
```
      "reference": {
        "id": "860e6431-0940-4d7b-a2cf-c3c9dab8d63e",
        "name": "PerforceCheckout",
        "version": "1.0.3"
      },
```

**Comment by dkalbertson** [comment]
@TingluoHuang I am the owner of the customized task. If I switch my build agent back to version 2.141.1 this task works correctly. When I update the agent to the newest (which is currently 2.153.2). The task errors out.

**Comment by TingluoHuang** [comment]
can you share a build log?

**Comment by dkalbertson** [comment]
Sure! see attached...
[logs_8902.zip](https://github.com/microsoft/azure-pipelines-agent/files/3369691/logs_8902.zip)

**Comment by dkalbertson** [comment]
@TingluoHuang I'm attaching a second build log from agent 2.141.1 that works as expected
[logs_8921.zip](https://github.com/microsoft/azure-pipelines-agent/files/3369852/logs_8921.zip)

**Comment by TingluoHuang** [comment]
@dkalbertson I can't find any obvious change might cause this, do you might help me narrow down to which version of the agent introduces the regression? Pick a version between 141.1 and 153.2 binary search which version has the problem.
Also, are those two build runs on agents on the same machine?

**Comment by dkalbertson** [comment]
@TingluoHuang I apologize for the radio silence. I've been working on getting a release out. I'll try to make some time to binary search the different versions within the next week.

To answer your question, yes, the two builds were run on the same build machine. They were actually run on the same agent. I just changed versions on that agent in between runs.

**Comment by dkalbertson** [comment]
@TingluoHuang I did some testing and narrowed down the build agent version that first introduced the failure. Build Agent version 2.144.1 produces the failure. The previous version, 2.144.0 does not. The test builds ran on the same machine and on the same build agent. I only change the version of the build agent and restarted the agent in between test runs. I verified by switch the versions back and forth a few times. I've attached logs from the two builds.
[BuildAgent_2.144.0_logs_9161.zip](https://github.com/microsoft/azure-pipelines-agent/files/3497548/BuildAgent_2.144.0_logs_9161.zip)
[BuildAgent_2.144.1logs_9160.zip](https://github.com/microsoft/azure-pipelines-agent/files/3497549/BuildAgent_2.144.1logs_9160.zip)

**Comment by TingluoHuang** [comment]
@dkalbertson can you try add the following variable to your definition
`agent.retainDefaultEncoding=true` and run the build again on 2.144.1 runner? see whether that mitigate the problem.

**Comment by dkalbertson** [comment]
@TingluoHuang That did mitigate the problem. I already have a variable group of settings for that particular task. So, I'll include `agent.retainDefaultEncoding=true`  in that variable group as well. Thanks for the support.

**Comment by LordBigSky** [comment]
> ## Agent Version and Platform
> 
> 2.153.2
> 
> Windows 7
> ## Azure DevOps Type and Version
> 
> dev.azure.com (formerly visualstudio.com)
> 
> https://lms-bioptigen.visualstudio.com
> ## What's not working?
> 
> I have a custom build script (Powershell) that pulls down a perforce repository containing our org's signing certificates. The script builds a temporary workspace spec and outputs it to standard output with the pipe that reads in the spec from standard input. i.e. `P4.exe -d "path_to_checkout_repo_to" client -o "unique_client_name" | p4.exe client -i`
> 
> This worked as expected on version 2.141.1 of the build agent. However, on version 2.153.2, I get errors from the p4.exe command line as well as `Syntax error in '﻿'.` from the execution of the build task.
> 
> [Diag.zip](https://github.com/microsoft/azure-pipelines-agent/files/3369502/Diag.zip)

Workflow
