### ISSUE TITLE
Can't use function to set variable value.

### ISSUE THREAD

**Issue by alucardu** [microsoft/azure-pipelines-agent#2343]
In my azure cli task I can run: 

`call az storage account keys list -g CustomersV2 -n $(prSourceBranchName) --query [0].value -o tsv`

This outputs a string with the key value. I want to call this function in another azure function:

`call az storage blob upload-batch --source "$(System.DefaultWorkingDirectory)/_ClientWeb-Build-CI/ShellArtifact/out/build" --destination "$web" --account-key call az storage account keys list -g CustomersV2 -n $(prSourceBranchName) --query [0].value -o tsv --account-name $(prSourceBranchName)`

When I run the task I get a: `ERROR: az: error: unrecognized arguments: az storage account keys list -g CustomersV2 -n *****to`

Is it not possible to nest a function in azure cli?

**Comment by juliobbv** [comment]
Hi @alucardu,

This repository is to talk about issues related to the Azure Pipelines Agent, which is a different product than Azure CLI. Looks like your question has already been answered at [StackOverflow](https://stackoverflow.com/questions/56952078/how-to-use-azure-cli-function-in-function).

I'll close this issue.

Thanks,
Julio
