### ISSUE TITLE
custom build agent sometimes failed to restore packages or push packages

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/azure-pipelines-agent#2345]
## Agent Version and Platform

Version of your agent? 2.148.1

Custom Linux Build Agent

## Azure DevOps Type and Version

https://mvn11.visualstudio.com

## What's not working?

get error when try to restore packages or push packages, error as as follows:

```
Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
```

dotnet restore error:

```
##[section]Starting: dotnet restore
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.153.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
##[error]Error: Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[error]Packages failed to restore
##[section]Finishing: dotnet restore

```

dotnet push error:

```
##[section]Starting: dotnet push
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.153.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
##[warning]Can\'t find loc string for key: Warning_SessionCreationFailed
##[warning]Warning_SessionCreationFailed {}
##[error]Error: Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[error]Packages failed to publish
##[section]Finishing: dotnet push
```

**Comment by TingluoHuang** [comment]
@WeihanLi looks like a task issue, can you open issue at https://github.com/microsoft/azure-pipelines-tasks

**Comment by WeihanLi** [comment]
Hi @TingluoHuang, I'm not sure whether it's a task issue or not, the same task differ in Microsoft build agent and custom build agent, it happened only when use custom build agent. It works great with Microsoft build agent, so I'm wondering if there some difference caused that

**Comment by TingluoHuang** [comment]
@WeihanLi have you try using the same version of the agent that works great in the Hosted pool?

**Comment by WeihanLi** [comment]
can not find the microsoft build agent agent version, is there a guide for that?

There're the two Microsoft build agent I use

![image](https://user-images.githubusercontent.com/7604648/61016671-089d7d80-a3c3-11e9-909b-ebd373640e59.png)
![image](https://user-images.githubusercontent.com/7604648/61016747-51553680-a3c3-11e9-9d73-667ea49912e5.png)

**Comment by TingluoHuang** [comment]
@WeihanLi if you run a build, the version get print out in the `initialize job` log

**Comment by WeihanLi** [comment]
Thanks @TingluoHuang , microsoft build agent version is `2.153.2`

**Comment by WeihanLi** [comment]
tried with the latest version `2.153.2` same version with Microsoft Build Agent, this problem still exists @TingluoHuang

**Comment by bryanmacfarlane** [comment]
That error is coming from the task which is calling the tools installed on the image.  Please log an issue in azure-pipelines-task repo and I can route to the packaging team.
