### ISSUE TITLE
Strange issue with docker.

### ISSUE THREAD

**Issue by equidevium** [microsoft/azure-pipelines-agent#2346]
So hello guys.

I am running into a strange issue which i am not really sure this is the right place to post. 
So please excuse my missing intel since i am quite new to azure functions and azure pipelines. 

So i am having a python project ( DELTA detected to throw this post somewhere else i know ) that i wanted to publish. That is fine. Though i fell into the need to use 

func azure functionapp publish amazingAppname --build-native-deps

because i needed to package all of the plugins that where in need of a wheel installation. 

That was fine to test. Then though i had to install the docker engine. I did as the tutorial said and did a restart as prompted.

Though when restarting the docker for windows was starting by default. I though that this is ok since i have Hyper V and Virtualizaton enabled. But after a couple of seconds BSOD appeared with driver  irql not less or equal message. 

I know that this may sound quite lame to post here but i thought maybe there must be someone that have had the same problem before. When i deactivated ( i was fast in doing so after several restarts ) docker to be enabled on windows startup this problem went away ( but now i am in a position that i cannot deploy my app paradox ). If i start the docker for windows app i still get the blue screen. 

Any kind person that can give me some tips here?

**Comment by juliobbv** [comment]
Hi @equidevium,

This repository is to talk about issues related to the Azure Pipelines Agent. Looks like your particular question might better be directed to the Docker for Windows team: https://github.com/docker/for-win.

I'll close this issue.

Thanks,
Julio
