### ISSUE TITLE
Question: How to run a build definition on every agent in an agent pool

### ISSUE THREAD

**Issue by kichalla** [microsoft/azure-pipelines-agent#2347]
**My team's scenario:**
We have around 15 build agents in which we build docker images etc. We do not aggressively clean up docker images after every build since we want to use the cache as much as possible for good user experience. But since we consume disk space over time because of this we are planning to have a job like thing which runs let's say every 2 weeks(ex: 3.00 A.M on Saturday) on **every** agent in the pool and just deletes every docker image on it. 
We considered using a cron job on the agent machines but were worried about race conditions. For example, if a build gets triggered right when a cron job is happening. This could cause the build to fail or the cron job might not able to finish successfully. We considered the build definition approach since we know only one instance of a build can run on an agent at any given time.

**Question**:  
How can I enable a build definition to do a build on _every_ agent in the pool? Ideally I would like to avoid adding agent names as demands as that is cumbersome and error-prone.

**Comment by kichalla** [comment]
cc @arroyc

**Comment by arroyc** [comment]
Hi Guys, Any update on this? As a workaround we created a yaml build definition where we are placing demand for every agent in the agent pool and set a schedule for the build. This works ok. But when there are situations where an agent is temporarily offline or disabled, this build goes into infinite wait. I have tried to use timeout but it's not working. Any better way to deal this?

Note: It would be nice if we can place a demand on agent status as well. For example if we can set a demand like agent.name equal "A" and agent.status equal "active".

**Comment by juliobbv** [comment]
Hi @kichalla, @arroyc:

Azure DevOps doesn't support running a given build definition on every agent in a pool.

That said, there are ways to clean up the agent environments. The most common and simplest solution is to have a task that runs at the end of the build definition that calls a script basically no-ops, unless it detects that the docker image cache is full (or a certain time has passed -- e.g. by keeping track with a file with a timestamp), then it performs the actual cleanup. The main disadvantage is that there will be a slower build every now and then, but comes with the advantage of not having to modify demands or having to place agents offline. This is the usual strategy used by our internal (at Microsoft), and external customers.

Thanks,
Julio

**Comment by paule96** [comment]
But that isn't a solution for shared environments. Because you can trust the people that write build definitions. So many build definitions doesn't have a clean task at the end. 

So the agent need this know how. Maybe the single run flag is an option. So you configure your agent to shutdown after build. If this happens the OS of the agent can clean up the storage and start the agent again. But this is very hacky way to do this.

**Comment by bryanmacfarlane** [comment]
The right solution for this problem is BYOS pool providers.  @zachariahcox

**Comment by damccorm** [comment]
Hey, thanks for the feedback - we're tracking this internally and it should be coming soon. I'm going to close here since the feedback has been propogated internally.
