### ISSUE TITLE
Possible to run something after every build

### ISSUE THREAD

**Issue by paule96** [microsoft/azure-pipelines-agent#2352]
Hi,
I have a very easy questions regarding the Pipelines agent. 

I would like to configure the Agent in way  that he is able to execute a custom local action after every build. Like a Post Job Command. 
Is something like this possible?

Currently I have the problem regarding a Linux Agent which mainly executes Docked tasks. The agent itself has about 20G storage. 

The problem is that the storage is full after several builds and I would like to enable some housekeeping to free the storage from the docker stuff after a build. 

Therefore it would be nice to have the ability to implement a custom script extension after Job completion. In my case I would like to use “docker system prune -a” to delete all the docker stuff after a job. Currently I am doing this manually. 

Although I know that it is possible to use a crown job to solve this issue, I don’t like the idea in that case. Because it could happen that the prune command is executed during a pipeline run.  

Any Ideas on this one?

Regards,

paule

**Comment by kichalla** [comment]
Seems like both of our use cases are similar: https://github.com/microsoft/azure-pipelines-agent/issues/2347

**Comment by juliobbv** [comment]
Hi @paule96,

I left a comment in #2347 on a usual pattern to cleaning up agent machines by adding a step to the the main build/release definition. I'll close this issue, but you can leave your comments in #2347.

Thanks,
Julio

**Comment by mohag** [comment]
Any solution for this that doesn't rely on everyone making pipelines consistent?
