### ISSUE TITLE
Cannot install on Debian 10 (buster)

### ISSUE THREAD

**Issue by petrparik** [microsoft/azure-pipelines-agent#2355]
## Agent Version and Platform
vsts-agent-linux-x64-2.154.3.tar.gz

OS of the machine running the agent? 
Linux Debian 10 (buster)

## Azure DevOps Type and Version
dev.azure.com 
https://dev.azure.com/petrparik

## What's not working?
Cannot install the agent.

I tried to follow these steps: https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
There is no version for Debian 10. 
When I run sudo apt-get update, I get this error:

```
sudo apt-get update
Hit:1 http://deb.debian.org/debian buster-backports InRelease
Hit:2 http://debian-archive.trafficmanager.net/debian buster InRelease
Get:3 https://packages.microsoft.com/debian/10/prod buster InRelease [23.0 kB]
Err:3 https://packages.microsoft.com/debian/10/prod buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Reading package lists... Done
W: GPG error: https://packages.microsoft.com/debian/10/prod buster InRelease: The following signatures couldn't be verified because the public key is not avail
able: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/debian/10/prod buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by juliobbv** [comment]
Hi @petrparik,

FYI, the agent comes in a self-contained package, which doesn't require installing the SDK. You can set up the agent by following [these instructions](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/start/envlinux.md#install-net-core-2x-linux-dependencies).

Also, be aware there's issue #2373 open, which impedes configuring the agent in Debian buster. You can try out [this unofficial package](https://github.com/microsoft/azure-pipelines-agent/issues/2373#issuecomment-518337437) to unblock yourself, or wait for the next official agent release.

**Comment by juliobbv** [comment]
Hi @petrparik,

I wanted to give you an update. I checked the official .NET Core 2.1 Linux OS documentation, which indicates they do not officially support Debian 10. We'll need to wait for the final version of .NET Core 3.0 to be released in order for us to start offering agent support (in other words, we cannot support OSes that .NET Core doesn't support).

In the meantime, you can run the agent [in any of the supported OS from this list](https://github.com/microsoft/azure-pipelines-agent/blob/895826cee93db70a99264a01f116fbec6b499793/docs/start/envlinux.md). I apologize for the inconvenience.

**Comment by petrparik** [comment]
Hi @juliobbv,
thanks a lot for info! I hope .NET Core 3 will support Debian 10 (in the documentation only 9 is mentioned for .NET Core 3 preview 1).
https://docs.microsoft.com/cs-cz/dotnet/core/linux-prerequisites?tabs=netcore30
