### ISSUE TITLE
Increasing Max Attachment Size for Build Attachments

### ISSUE THREAD

**Issue by MattDavisRM** [microsoft/azure-pipelines-agent#2361]
## Agent Version and Platform
2.141.1

## Azure DevOps Type and Version
Azure DevOps Server 2019.0.1

## What's not working?
Is there a way to increase the max attachment size for the builds?  We are receiving the follow error message when attempting to enable code coverage.  It is creating a 117MB file, but we get the following warning message:

Skipping attachment as it exceeded the maximum allowed size 75MB

**Comment by juliobbv** [comment]
@nigurr to follow up on this issue.

Looks like the 75 MB limit is currently hard-coded, by current design, and was introduced by [this PR](https://github.com/microsoft/azure-pipelines-agent/pull/1128/files).

**Comment by nigurr** [comment]
@juliobbv @MattDavisRM  this is currently limitation and we are working on increasing to GBs.
Can you please share your account details and scenario?

**Comment by shueybubbles** [comment]
hi, my team's project at msdata.visualstudio.com/sqlservermanagementstudio is hitting this same limitation. 
We run daily tests using vstest and our TRX files now won't get attached.
Published test results: 338
Publishing Attachments: 2
##[warning]Skipping attachment as it exceeded the maximum allowed size 75MB: F:\msdata\_work\_temp\TestResults\<redacted>_2019-09-27_08_33_39.trx.

**Comment by ShreyasRmsft** [comment]
@shueybubbles you can try setting custom batching to true with a small batch size (say around x/10 where x is your total number of tests). This should generate smaller trx files one for each batch of tests. Consider it an immediate workaround to get yourself unblocked.

**Comment by ankit-arora12** [comment]
@shueybubbles With vstesttask, attachments greater than 75MB should not be a problem now. Can you please validate it.
@MattDavisRM If you use Publish Test Results Task, then this should work on a windows machine currently. We are working on providing the same support for linux/mac and which will be available after a month. Let me know if you are still hitting the issue on windows machines.

**Comment by johnwhoffman** [comment]
We have the same issue on ado22.. trx file exceeeds 75mb
