### ISSUE TITLE
Sha256Managed is IDisposable

### ISSUE THREAD

**Issue by oising** [microsoft/azure-pipelines-agent#2365]
These types of instances require disposal. 

example:

https://github.com/microsoft/azure-pipelines-agent/blob/184544d202802a81f7628a898047b0f73c10bb86/src/Agent.Plugins/PipelineCache/FingerprintCreator.cs#L162

**Comment by jtpetty** [comment]
@stephenmichaelf - can you take a look at this one and see if the static analysis work you are doing will flag it?

**Comment by oising** [comment]
Ping.

**Comment by oising** [comment]
Not stale.
