### ISSUE TITLE
Issue when trying to "pre-cache" docker image

### ISSUE THREAD

**Issue by MLoughry** [microsoft/azure-pipelines-agent#2366]
## Agent Version and Platform
Version of your agent? 2.149.2

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? dev.azure.com

If dev.azure.com, what is your organization name? https://outlookweb.visualstudio.com

## What's not working?
We currently run our builds on self-hosted docker agents that we spin up for single-use for each build, in order to meet demand and minimize compute cost. As a HackWeek project, I was trying to "pre-cache" the build by enlisting, yarn-ing, and building in `/agent/_work/1/s`, and I verified that the data was present in the resulting image. 

However, when I run a build against the container, it seems that either the agent or a build step blows away all of the content of the `/agent/_work/1/s` directory before enlisting, which means we get none of the cache benefits.

Other issues/documentation references cache benefits from running multiple builds on the same agent, so obviously the data is meant to persist in some cases. However, I can't determine how to bake this into a docker image such that it will be used.

## Agent and Worker's Diagnostic Logs
[dummy-agent - miclo.zip](https://github.com/microsoft/azure-pipelines-agent/files/3437555/dummy-agent.-.miclo.zip)

**Comment by juliobbv** [comment]
Hi @MLoughry,

How are you 'baking in' the source enlistment/yarn packages/build files into the docker image? Are you x-copy'ing these files from an external share into the `/agent/_work/1/s` directory of the container? Or are you running a build inside the container (which sets up the sources directory), then snapshot the image, which is later used for subsequent runs?

Thanks,
Julio

**Comment by MLoughry** [comment]
The latter.

I figured out that ADO’s git sync seems to be wiping the directory, as setting the option to skip the sync leaves the files in place.

In our particular case, unfortunately, we found that the added time to spin up the Azure container made most of the time savings later in the build a wash. We hope to investigate moving to beefier and semi-persistent VMs in the future, depending on the cost calculations.

- Michael
________________________________

**Comment by juliobbv** [comment]
Got it. Thanks for the heads-up, @MLoughry.

Given that the idea didn't work out, I'll close this issue for now, but feel free to re-open it if needed.

- Julio
