### ISSUE TITLE
No predefined variables to know if a build agent is enabled or disabled/offline

### ISSUE THREAD

**Issue by arroyc** [microsoft/azure-pipelines-agent#2367]
we are using yaml builds where we want to run clean up task in every agent we have. Right now  the build goes to infinite loop as some of the agents become disabled/offline. Is there any predefined variables/workaround to this problem?

**Comment by juliobbv** [comment]
Hi @arroyc,

We'll need some more details before continuing looking at this issue:

1. How does your clean-up task look like? Is the task itself causing the agent to go offline?
2. What do you mean that the build goes into an infinite loop? Does the build never complete?
3. Are you using self-hosted agents, or a Microsoft-hosted agents? What OS are the agents running with?

Thanks,
Julio

**Comment by arroyc** [comment]
@juliobbv thanks for responding... here are the answers
1. cleaning task is basically "docker system prune"
2. yes build never completes, because we place a demand to run this clean up (docker system prune) command in a specific agent and when the build agent is disabled/offline, build keeps on waiting.
3. yes self hosted Linux agents.

Some more details #2347

**Comment by arroyc** [comment]
cc @kichalla

**Comment by juliobbv** [comment]
Hi @arroyc,

I responded back to the original issue #2347, with a suggestion on how to perform clean up on the agents.

I'll close this issue.

Thanks,
Julio
