### ISSUE TITLE
Agent Update is not working 2.155.1

### ISSUE THREAD

**Issue by peckhamm** [microsoft/azure-pipelines-agent#2368]
I have a Azure DevOps Server 2019 box and I placed the .ZIP file for 2.155.1 in the _%ProgramData%\Microsoft\Azure DevOps\Agents_ directory.  I then went to the agent pool and told it to update all agents.

4 agents reside on a seperate build server and 1 agent resides on the DevOps Server 2019 application server.  They all went offline and came back online but they are still running 2.144.2.

I then re-read the instructions and unzipped the package, placing all the files into the Agent directory (above) and attempted it again.  Same result.

Instructions I was referencing:
Can I update my v2 agents that are part of an Azure DevOps Server pool?
on:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops-2019#

Thank you.

**Comment by TingluoHuang** [comment]
@peckhamm you should keep them in zip/tar.gz format.
what's your local folder structure looks like under `%ProgramData%\Microsoft\Azure DevOps\Agents`, do you mind sharing a screenshot?

also, can you post the agent log zip to us?

**Comment by peckhamm** [comment]
![2019-07-30_115934](https://user-images.githubusercontent.com/26437284/62145540-a3ea8a00-b2c1-11e9-9c07-3dea7cd412b4.png)

@TingluoHuang Here is the screen shot.

**Comment by TingluoHuang** [comment]
@peckhamm 
from your log
`[2019-07-30 13:37:11Z ERR  VisualStudioServices] GET request to https://xxxxxxxxxxxxxx/_apis/distributedtask/packages/agent/win-x86/2.155.1 failed. HTTP Status: NotFound`

You might want to copy all agent release packages to your local folder (x64/x86/linux/mac), the agent is x86, the package you downloaded is only x64

**Comment by peckhamm** [comment]
Ahhhh, that explains it.
