### ISSUE TITLE
Build Agent Installed on fresh Windows 10 / VS2019 Does Not Discover Xamarin/Android Capabilities

### ISSUE THREAD

**Issue by charristti** [microsoft/azure-pipelines-agent#2372]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes

## Agent Version and Platform
Version of your agent? 2.154.3 Windows

OS of the machine running the agent? Windows 10

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com

frcfms

## What's not working?
Xamarin Android build is not picked up by the agent.
Adding Xamarin.Android capability as user defined allows agent to run the build

So the capability detection is not working properly if only VS2019 is installed on clean windows 10 machine. On another machine which has VS2017 and VS2019 and had other android tools installed. All worked as expected.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

[Agent_20190802-210940-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/3462985/Agent_20190802-210940-utc.log)
[vs2019.vsconfig.txt](https://github.com/microsoft/azure-pipelines-agent/files/3462990/vs2019.vsconfig.txt)

**Comment by charristti** [comment]
Here are the capabilities I added manually to get the build agent working for my Xamarin.Android project with Build and Signing tasks.



![image](https://user-images.githubusercontent.com/33519407/62406708-f35cde80-b57d-11e9-81c3-0dea5404405e.png)

**Comment by charristti** [comment]
Another item to be checked is whether usage of the new Microsoft openjdk for Android work flow is being detected and processed properly.

**Comment by jtpetty** [comment]
Closing issue as this should have been addressed by the mentioned PR. If this is not addressed, please feel free to open a new issue and we will continue to investigate.
