### ISSUE TITLE
Cannot configured on Debian 10

### ISSUE THREAD

**Issue by hajuuk** [microsoft/azure-pipelines-agent#2373]
## Agent Version and Platform
Version of your agent? 2.155.1

## OS of the machine running the agent?
Debian 10
Linux local-dev 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)
https://dev.azure.com/IllawarraTaxiNetwork

## What's not working?
>> Connect:

Enter server URL > https://dev.azure.com/IllawarraTaxiNetwork
Enter authentication type (press enter for PAT) > 
Enter personal access token > ****************************************************
No usable version of the libssl was found
./config.sh: line 86:   519 Aborted                 ./bin/Agent.Listener configure "$@"

I also tried to using the dependency install script, here is the output:

hajuuk@local-dev:~/myagent/bin$ sudo ./installdependencies.sh
--------OS Information--------
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
------------------------------
The current OS is Debian based
--------Debian Version--------
10.0
------------------------------
/usr/bin/apt
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://ftp.au.debian.org/debian buster InRelease                         
Hit:3 http://ftp.au.debian.org/debian buster-updates InRelease                 
Hit:4 https://dl.yarnpkg.com/debian stable InRelease                           
Hit:5 https://packages.microsoft.com/debian/9/prod stretch InRelease           
Hit:6 https://deb.nodesource.com/node_12.x buster InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libkrb5-3 is already the newest version (1.17-3).
libkrb5-3 set to manually installed.
liblttng-ust0 is already the newest version (2.10.3-1).
liblttng-ust0 set to manually installed.
zlib1g is already the newest version (1:1.2.11.dfsg-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcurl4

E: Package 'libcurl3' has no installation candidate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcurl4 is already the newest version (7.64.0-4).
libcurl4 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.0' has no installation candidate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0.2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.2' has no installation candidate
'apt' failed with exit code '0'
Can't install dotnet core dependencies.
You can manually install all required dependencies based on following documentation
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

## Agent and Worker's Diagnostic Logs
Not able to install the agent.

**Comment by juliobbv** [comment]
Hi @hajuuk,

Can you try installing OpenSSL 1.1? i.e. `apt install libssl1.1`, and config the agent again? Let me know the results. If that succeeds, I'll update installdependencies.sh so it installs OpenSSL 1.1 if 1.0.x don't exist.

**Comment by hajuuk** [comment]
Actually, the openssl 1.1 is pre-installed.

Here is what i tried.

hajuuk@local-dev:~/myagent$ sudo apt install libssl1.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl1.1 is already the newest version (1.1.1c-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hajuuk@local-dev:~/myagent$ openssl version
OpenSSL 1.1.1c  28 May 2019
hajuuk@local-dev:~/myagent$ ./config.sh

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /home/hajuuk/myagent/externals/tee/license.html

Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N) > Y

>> Connect:

Enter server URL > https://dev.azure.com/illawarraTaxiNetwork/
Enter authentication type (press enter for PAT) > 
Enter personal access token > ****************************************************
No usable version of the libssl was found
./config.sh: line 86:  2401 Aborted                 ./bin/Agent.Listener configure "$@"
hajuuk@local-dev:~/myagent$

**Comment by juliobbv** [comment]
Thanks @hajuuk for the confirmation.

I was reading up on dotnet/corefx#33870 and dotnet/corefx#34443, and apparently OpenSSL 1.1 support was added to .NET Core 2.1 at a later patch version (which the agent consumes). I'll try out creating an agent package for you to try on you machine built with an up-to-date .NET Core 2.1.

**Comment by juliobbv** [comment]
@hajuuk, can you try out installing this package and try configuring the agent again? Let me know if it works for you.

https://1drv.ms/u/s!AkcNSSfO5EWU203yB2etXzMwZOsU?e=byfT3H

This package was built against the latest LTS version of the .NET Core 2.1 SDK.

**Comment by juliobbv** [comment]
Hi @hajuuk,

I checked the official .NET Core 2.1 Linux OS documentation, which indicates they do not support Debian 10. We'll need to wait for the final version of .NET Core 3.0 to be released in order to start offering agent support.

In the meantime, you can run the agent [in any of the supported OS from this list](https://github.com/microsoft/azure-pipelines-agent/blob/895826cee93db70a99264a01f116fbec6b499793/docs/start/envlinux.md).
