### ISSUE TITLE
Allow a job to be retried before the whole build fails

### ISSUE THREAD

**Issue by mthalman** [microsoft/azure-pipelines-agent#2382]
I would like an option to be able to retry jobs that have failed in a build without waiting for the build to complete.  This would be nice for builds that have many jobs, some of which take a long time to run.  If one of those jobs fail early on during the build, it's a waste of time to just sit around and wait for the rest of the jobs to complete before I can retry the build to get that failed job to run again.  It'd be better to just get that failed job to retry right away so that it can execute in parallel and end up with a much faster overall build time.

**Comment by juliobbv** [comment]
CC @vijayma for awareness

Currently, Azure Pipelines doesn't support retrying failed runs, but it's a feature on the [roadmap](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1454027/) to be implemented in a future version, planned for 2019 Q3.
