### ISSUE TITLE
Mounting host directories into container from Windows self-hosted agent

### ISSUE THREAD

**Issue by richardgavel** [microsoft/azure-pipelines-agent#2383]
## Agent Version and Platform
2.155.1

OS of the machine running the agent? OSX/Windows/Linux/...
Windows Server 2019 (1903)

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
Running a build within a Windows container + mounting a host directory (this is on a self-hosted agent). The mount works fine (I'm guessing the mount string is just passed as is, with variable replacement). However, subsequent steps fail with the following error:

##[error]Value cannot be null. |  
-- | --
  | Parameter name: value |  
  | ##[debug]System.ArgumentNullException: Value cannot be null. |  
  | Parameter name: value |  
  | at System.String.StartsWith(String value, StringComparison comparisonType) |  
  | at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match) |  
  | at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.ContainerStepHost.ResolvePathForStepHost(String path) |  
  | at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync() |  
  | at Microsoft.VisualStudio.Services.Age

I believe the issue is in https://github.com/microsoft/azure-pipelines-agent/blob/13a2f4823d584526ae801b73fdf46c8e45e8364e/src/Agent.Worker/Container/ContainerInfo.cs#L262 in that it does not account for the possibility of drive letters in the volume mount, resulting in more colons than any of it's expected use cases.

**Comment by jtpetty** [comment]
@richardgavel  - are you able to try this with agent version 2.156 or later and verify this fixes your issue?

**Comment by jtpetty** [comment]
Closing after no response and issue is determined to be fixed from our side.
