### ISSUE TITLE
Output Variable Documentation Issues

### ISSUE THREAD

**Issue by MattDavisRM** [microsoft/azure-pipelines-agent#2392]
## Agent Version and Platform
Version of your agent? 2.144.2

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
Azure Devops Server

If on-premises, which release? 2019.0.1

## What's not working?
In a release pipeline, I have two Job phases:

Job1 - Name:Prepare
 - Task1 - PowerShell - Load computer names from a file, attempt to set an output variable
Job2 - Name:Snapshot
  - Setup Multi-Configuration with a multiplier.  I'd like to multiplier on the output variable from Job1.

The documentation [here](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/preview/outputvariable.md) is not very helpful at all. 

- [Here](\\pdfsevolv01corp\data\Builds\Configuration\DSC\ConfigData\estreamprd\r-4.5.2_Prod_4.5.2.13\_postdeploy) starts to reference AcquireToken but then starts using generic XCode and Variable1.  Be consistent
- [Here](\\pdfsevolv01corp\data\Builds\Configuration\DSC\ConfigData\estreamprd\r-4.5.2_Prod_4.5.2.13\_postdeploy) Could you pick a specific task and use that as the example.  I don't know if this is the assigned Task name I've picked, or the name of the task like Powershell, and I don't know how I would find which specific task name to use.
- [Here](\\pdfsevolv01corp\data\Builds\Configuration\DSC\ConfigData\estreamprd\r-4.5.2_Prod_4.5.2.13\_postdeploy) Can you please make this more concrete, with a specific task instead of generic.  Pick a real use case, maybe using PowerShell task as an example.
- [Here](\\pdfsevolv01corp\data\Builds\Configuration\DSC\ConfigData\estreamprd\r-4.5.2_Prod_4.5.2.13\_postdeploy) You have a TODO and your documentation sounds like an unfinished spec document.  **Your link in Azure DevOps server points to this in progress github page.**  Maybe host the md file instead like the other documentation and link to that instead.

**It is frustrating to probably have a feature available and not be able to get it working. **

**Comment by vtbassmatt** [comment]
Sorry for the frustration this caused. Those docs aren't current (and I'm going to get them removed). Documentation for that feature is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-output-variables-from-tasks).

**Comment by MattDavisRM** [comment]
> Sorry for the frustration this caused. Those docs aren't current (and I'm going to get them removed). Documentation for that feature is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-output-variables-from-tasks).

Thanks @vtbassmatt - Are there any plans to bring the output variable usages between jobs to release pipelines?  Appears to mention that is only available on YAML.
