### ISSUE TITLE
Agent bearer token is not yet valid

### ISSUE THREAD

**Issue by alexwiese** [microsoft/azure-pipelines-agent#2393]
## Agent Version and Platform
2.153.2

OS of the machine running the agent? OSX/Windows/Linux/...
Windows

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com
dev.azure.com/pulselogistics

## What's not working?
We are suddenly receiving this error on our agent (we haven't changed anything our end). It seems it's being given a bearer token that is somehow not yet valid.
Most likely yet another timezone issue on the Devops server end.

`Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenRequestException: The bearer <secret removed> is not valid until 8/15/2019 4:49:16 AM. Current server time is 8/15/2019 3:03:52 AM.`

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by alexwiese** [comment]
[Agent_20190815-044756-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/3504188/Agent_20190815-044756-utc.log)

**Comment by alexwiese** [comment]
Turns out the system clock on the server was out - problem solved after changing the clock.

**Comment by cuong0993** [comment]
Hi Alex, 
May I know how to change the clock here? I could not find it in Azure DevOps.
Thank you for your help

**Comment by alexwiese** [comment]
> Hi Alex,
> May I know how to change the clock here? I could not find it in Azure DevOps.
> Thank you for your help

We were using a private agent (virtual machine). I logged into the virtual machine and changed the system clock.
You can't do that for the hosted agents (only private ones).
