### ISSUE TITLE
 Download in China is very slow

### ISSUE THREAD

**Issue by mingyanzhen** [microsoft/azure-pipelines-agent#2394]
Hello, Download in China is very slow. Can you put the vsts-agent software into Microsoft's official download? Download there is very fast.
![image](https://user-images.githubusercontent.com/6066974/63075461-609c4680-bf64-11e9-9392-29e343e9fec5.png)

**Comment by vtbassmatt** [comment]
The agent update process is built around using the Azure CDN. I'm not opposed to doing something like this, but we won't get to it any time soon. Therefore I'm going to close the issue (but others should feel free to pile on if they want to +1 the feature).

**Comment by wizicer** [comment]
I'm also suffering from this issue as agent is refused to build without latest update. Now I'm trying to extend timeout mentioned in #2241 .
