### ISSUE TITLE
An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/azure-pipelines-agent#2395]
## Agent Version and Platform

Version of your agent? 2.153.2

OS of the machine running the agent? Linux

## Azure DevOps Type and Version

https://mvn11.visualstudio.com

## What's not working?

seemed can not connect the build agent, it happens by chance, and may work after times retry

![image](https://user-images.githubusercontent.com/7604648/63143942-4aa18b00-c023-11e9-884b-a294fcf5d0e8.png)

![image](https://user-images.githubusercontent.com/7604648/63144021-96eccb00-c023-11e9-8808-4529f0731a19.png)

I'm wondering if we could do some retry when connect the build agent

## Agent and Worker's Diagnostic Logs

[logs_3768.zip](https://github.com/microsoft/azure-pipelines-agent/files/3508072/logs_3768.zip)

**Comment by juliobbv** [comment]
Hi @WeihanLi,

The agent already comes with a mechanism to retry requests (up to 5 times) to the server in case there's any issues. This sounds like a connectivity problem. Can you reliably use Azure DevOps from the agent machine?

Thanks,
Julio

**Comment by WeihanLi** [comment]
I think it's a problem of agent network, I'll do some retry for now when I met the problem

**Comment by WeihanLi** [comment]
I've looked at the `RetryExecutor` <https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/Release/RetryExecutor.cs#L71>

![image](https://user-images.githubusercontent.com/7604648/63250444-4208b900-c29e-11e9-9410-7ece2e989fa2.png)

I think the code I marked should use `await` to wait the delay, and the delay should be increase with the retry times, for example, delay time should be : 2s/4s/8s/16s/32s/64s ...

**Comment by WeihanLi** [comment]
Hi @juliobbv , I'm not sure if you're using the retry policy like <https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/Release/RetryExecutor.cs> defined, I think there maybe a problem when retry, it does no wait the delay as wished. I'd made a pr here #2397
