### ISSUE TITLE
Support git SSH access keys for Service Connections

### ISSUE THREAD

**Issue by luyseyal** [microsoft/azure-pipelines-agent#2399]
We use bitbucket. Please support SSH Access Keys. These are nice for granting quick read-only access to build agents like Azure DevOps that don't expire/timeout and don't require creation of fake robot service accounts in Atlassian.

https://confluence.atlassian.com/bitbucket/access-keys-294486051.html

Thank you!!!

Stephen Olander-Waters
Austin, Texas

**Comment by luyseyal** [comment]
This is not stale. This request is still valid, as far as I know.

**Comment by luyseyal** [comment]
@zachariahcox Why did @github-actions close this if I commented? That makes no sense...

**Comment by pauldotknopf** [comment]
lmao, I love the support. There is none!

**Comment by anatolybolshakov** [comment]
Hi @luyseyal @pauldotknopf could you please elaborate your scenario? Do you want to add support for SSH Access Keys? This sounds like a DevOps side feature - I would suggest to open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.
