### ISSUE TITLE
Suggestion: echo config data back to console to allow for self-troubleshooting

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-agent#2403]
A customer filed an issue through another channel, reporting that proxy config wasn't being picked up. It turned out to be misbehavior by Ansible - the hostname was being written down with quotes, making it an invalid hostname. If we had echo'd back the exact data we saw on ./config, the customer would likely have seen the problem sooner and not had to reach out to us for troubleshooting.

For consideration: in this specific instance, we also could have validated that it looked like a correctly-formatted hostname. I have some trouble with this, though - we catch the occasional stray issue like this one, at the risk of having incorrect validation logic that blocks someone else. The regex or validator could be fairly complex -- having to account for internationalized domains, IPv4 and IPv6 addresses, and probably more I'm not thinking of, while also being likely to catch an incorrect hostname.

**Comment by jtpetty** [comment]
I'll take a look at dumping the config data to stdout

**Comment by bryanmacfarlane** [comment]
Are we sure we want to do that?  The user could have dumped it to stdout for troubleshooting (use the automation system itself to troubleshoot the workflow).  Instead, having it always dumped out is taking time, perf, logs for everyone.  What else will we start dumping out?  For troubleshooting it could effectively become any machine / tool config state.

**Comment by jtpetty** [comment]
After spending a lot of time today looking through the code, I've come to a similar conclusion. Dumping out all the config data seems difficult to maintain as not all config information is kept in the same object  along with the performance implications you mentioned. 

Something I have started looking down that path of, is can we let the user know on stdout that there is something interesting in the diag logs that they should take a look at. My initial approach was that if a Warning, Error or Critical message was written to Trace, we should mention something in the console output. 

Thoughts?

**Comment by vtbassmatt** [comment]
Since it's in the diagnostic log, I can't push too hard to also dump it someplace else. Thanks for taking a look.

**Comment by vtbassmatt** [comment]
(Forgot to add - but the warning about "hey, go look at the diagnostics" is a good one.)
