### ISSUE TITLE
Oracle 7 private agent configured failed with error: Couldn't find a valid ICU package installed on the system.

### ISSUE THREAD

**Issue by KennyChen0909** [microsoft/azure-pipelines-agent#2410]
## Agent Version and Platform
Oracle 7

OS of the machine running the agent? Linux
## Azure DevOps Type and Version
dev.azure.com 

## What's not working?
when we run ./config.sh, it shows this error FailFast: Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
![image](https://user-images.githubusercontent.com/40878442/63735175-85bc7d80-c8b1-11e9-95d9-1ae05bfad3dc.png)

we tried to use yum install icu to install icu package but showing no package icu available:
![image](https://user-images.githubusercontent.com/40878442/63735271-d338ea80-c8b1-11e9-8721-b7e036eb5b5e.png)

What we need to do?

**Comment by mjanorabon** [comment]
This one fixed the problem:

{
    "runtimeOptions": {
        "configProperties": {
            "System.Globalization.Invariant": true
        }
    }
}

The one available in the internet has a comma ( , ) on line 5. I just removed it (the comma) and saved to Agent.Listener.runtimeconfig.json

I now have a running agent, working as expected.
