### ISSUE TITLE
[Feature Request] sign agent download packages

### ISSUE THREAD

**Issue by Carlovo** [microsoft/azure-pipelines-agent#2412]
Please correct me if I am wrong, but the downloads of the agent .zip/.tar.gz packages are not signed, right?

It would be nice if these downloads would be signed, as the agent software is vital to us and we put a lot of trust in its correct assembly and functioning.

**Comment by TingluoHuang** [comment]
all windows packages should be signed, all Linux/mac packages are not signed.
did you find any windows package that is not signed?

**Comment by Carlovo** [comment]
Well, how do I check? If I right-click the "vsts-agent-win-x64-2.155.1.zip" download in Windows Explorer it doesn't tell me anything about being signed or something (in comparison, if I do the same with the "azure-cli-2.0.70.msi" it gives me a tab telling it's signed by Microsoft Corporation).

Am I missing/misunderstanding something?

**Comment by TingluoHuang** [comment]
we don't sign the zip file, if you unzip it, all dlls under it are signed by MSFT on windows.

**Comment by Carlovo** [comment]
Okay, then could you provide a way to recursively check all the files in that .zip?

As a user in the end, I am only interested in the correct compilation of the whole, not some individual files. Also, by quickly browsing through the files I came across a few which are not signed.

Furtermore, this does not solve the Linux/Mac part of it

**Comment by vtbassmatt** [comment]
Following up with our code signing folks to figure out the story here.
