### ISSUE TITLE
Missing LD_LIBRARY_PATH environment variable for RHEL

### ISSUE THREAD

**Issue by djsowa** [microsoft/azure-pipelines-agent#2417]
For RHEL based distributions service definition should contains definition of environment variable called: LD_LIBRARY_PATH=/usr/local/lib
Without this agent service will fail to start.
Service definition template located under: src/Misc/layoutbin/vsts.agent.service.template

Service startup error:

> buildagent-vm0 runsvc.sh[1136]: Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalizati
> buildagent-vm0 runsvc.sh[1136]: at System.Environment.FailFast(System.String)
> buildagent-vm0 runsvc.sh[1136]: at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
> buildagent-vm0 runsvc.sh[1136]: at System.Globalization.GlobalizationMode..cctor()
> buildagent-vm0 runsvc.sh[1136]: at System.Globalization.CultureData.CreateCultureWithInvariantData()
> buildagent-vm0 runsvc.sh[1136]: at System.Globalization.CultureData.get_Invariant()
> buildagent-vm0 runsvc.sh[1136]: at System.Globalization.CultureInfo..cctor()
> buildagent-vm0 runsvc.sh[1136]: at System.StringComparer..cctor()
> buildagent-vm0 runsvc.sh[1136]: at System.AppDomain.InitializeCompatibilityFlags()
> buildagent-vm0 runsvc.sh[1136]: at System.AppDomain.Setup(System.Object)
> buildagent-vm0 runsvc.sh[1136]: Agent listener exited with error code null
> buildagent-vm0 runsvc.sh[1136]: Agent listener exit with undefined return code, re-launch agent in 5 seconds.

**Comment by jtpetty** [comment]
@djsowa - If you add the following line in the `[Service]` section of the vets.agent.service file, does it resolve your issue?

```
Environment=LD_LIBRARY_PATH=/usr/local/lib
```

**Comment by djsowa** [comment]
It solves issue.
But how we can automate this ? Service definition file name has been changed in last few months.

This solution should be done on Your side. You even check LD_LIBRARY_PATH exists on VM but You done this too late.

**Comment by jtpetty** [comment]
@djsowa - Thanks for confirming. I will work on getting this file updated.

**Comment by jtpetty** [comment]
@zachariahcox - Do you mind taking a look at this issue and the PR referenced above and weigh in on if you think this is the right approach?
