### ISSUE TITLE
Feature request: DownloadPipelineArtifact support partially succeeded builds

### ISSUE THREAD

**Issue by bchurchill** [microsoft/azure-pipelines-agent#2429]
##  Agent Version and Platform
windows-latest

## Azure DevOps Type and Version
dev.azure.com
If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

## What's not working?
If you have a build that only partially succeeded, this task will not find it.  Instead, it will give you the most recent one that fully succeeded.  For the DownloadBuildArtifact task this is configurable via the allowPartiallySucceededBuilds parameter, but it's not for DownloadPipelineArtifact.

**Comment by jahsu-MSFT** [comment]
Hi @bchurchill, this feature is being worked on. The be released in 1-2 weeks. Thanks. 
https://github.com/microsoft/azure-pipelines-tasks/issues/11556

**Comment by jahsu-MSFT** [comment]
@bchurchill The support for partially succeeded builds is in the latest agent version. Can you please verify and close this ticket? If it still doesn't work, please let us know.

**Comment by stephenmichaelf** [comment]
Closing as this feature has been released.
