### ISSUE TITLE
Argument --once is not working when invoked from config

### ISSUE THREAD

**Issue by michax** [microsoft/azure-pipelines-agent#2432]
## Agent Version and Platform
2.551.0, Windows Server 2016

## Azure DevOps Type and Version
dev.azure.com

## What's not working?

--once parameter doesn't work if invoked with ./config and runAsAutoLogon.
It doesn't seem to work at all for configuration. 

If it should be only used with ./run command, please update your documentation which clearly indicate it can be used as part of unattended config:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#unattended-config

**Comment by kirkone** [comment]
Hi this is also tracked here:
https://github.com/MicrosoftDocs/vsts-docs/issues/5487

**Comment by alex-peck** [comment]
Fixed in documentation.
