### ISSUE TITLE
Azure build pipline - Triggers

### ISSUE THREAD

**Issue by 188867052** [microsoft/azure-pipelines-agent#2437]
Could you add a filter based on the github commit log to the azure build pipline - triggers setting? Because in some situations I don't want to trigger automatic builds, it is not proper to filter by file path or version branch.

**Comment by jtpetty** [comment]
@vijayma - Can you comment on this issue?

**Comment by vijayma** [comment]
This is the first time I am hearing about this. So, can you please share the need for this? If this is for PR builds, you can use comments to trigger a PR build.
