### ISSUE TITLE
Error evaluating stage condition results in AggregateException with no other detailed information

### ISSUE THREAD

**Issue by richardgavel** [microsoft/azure-pipelines-agent#2446]
## Agent Version and Platform
Version of your agent? 2.155.1

OS of the machine running the agent? OSX/Windows/Linux/... Windows Server 2016

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com
Ascendon

## What's not working?
We had an issue during evaluation of stage level conditions within a multi-stage pipeline. We can no longer recreate the issue, but this issue is more about the insufficient diagnostic information.
1. The log files (even running in debug mode) do not include anything relating to the stage unless it actually runs. There should be a log file relating to stage, to at least cover the evaluation of the condition.
2. What made this even tough as well was that the run detail screen just shows the run failing, with the first (non-conditional) stage succeeding, the others showing as cancelled (not skipped), and a error "One of more errors occurred". This is clearly an AggregateException that needs to display it's child exception information somehow and because of item 1, this is the only evidence I can find of that error.
3. Also, because the icon differences were so subtle (skipped vs cancelled) and the lack of logging, there was not enough context available to even know the issue was actually with the condition evaluation of those stages with conditions.

**Comment by vtbassmatt** [comment]
Sorry for the issues you faced in September, and for the delay in responding. This doesn't sound like an agent issue, and should be filed on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Something to include in that report: did it fail or was the stage skipped? I agree that we could do a better job "showing our work" when we compute that a stage should be skipped. But a failure shouldn't cause cancellation, nor should it be so ambiguous.
