### ISSUE TITLE
Agent & TFS / Devops / Team Services Version

### ISSUE THREAD

**Issue by JDCain** [microsoft/azure-pipelines-agent#2448]
Does the agent version correlate with version of TFS / Devops / Team Services?
We use TFS2017.3 and I noticed that the agent does not update past the version which shipped with it: 2.122.1

Does that mean newer versions of the agent are not supported on that version of TFS? If so how can I tell what versions of TFS each agent supports?

**Comment by DotNetSparky** [comment]
The "update agent" feature in TFS will only install the version it shipped with.  But, you can manually download the newer agents from this repo and install them.  Myself, I had no issues for the short time I was running the newer agents with 2017 (finally updated to 2019, and still running with the latest agent installed manually).

**Comment by jtpetty** [comment]
This is correct. You can manually update to newer agent versions manually.
