### ISSUE TITLE
sudo shutdown or sudo kill -9 1 should terminate Linux agent with failure

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-agent#2453]
To work around https://github.com/microsoft/azure-pipelines-tasks/issues/11334, I've tried the two standard POSIX ways I know of to shut down a system from inside: `sudo shutdown now` and `sudo kill -9 1` (which, on bare-metal Linux, would trigger a kernel panic from `init` or `systemd`). Neither has any detectable effect; I still get "The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited." followed by a false report of success.

**Comment by stephenmichaelf** [comment]
Related issue is closed so closing this.

**Comment by bneumann** [comment]
I think it is an agent problem really as I describe here: https://github.com/microsoft/azure-pipelines-tasks/issues/11334#issuecomment-591904067
