### ISSUE TITLE
Red Hat Issue: No usable version of the libssl was found, vsts-agent-rhel.6-x64-2.155.1.tar.gz

### ISSUE THREAD

**Issue by chetanku** [microsoft/azure-pipelines-agent#2454]
## Having issue with YAML?
Please log an issue at [Azure-Pipelines-YAML](https://github.com/Microsoft/azure-pipelines-yaml). Over there we discuss YAML templates, samples for Azure Pipelines, and designs for upcoming YAML features. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.

## Having issue with Tasks?
Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.

## Having issue with software on Hosted Agent? **"Installing self-hosted agent"**
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.

## Having generic issue with Azure-Pipelines/VSTS/TFS?
Please report it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)Yes

## Agent Version and Platform
Version of your agent? **2.155.1**

OS of the machine running the agent? OSX/Windows/Linux/...**Linux, Red Hat 8**

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? **dev.azure.com**

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com

## What's not working?
Please include error messages and screenshots.

**when i run ./config.sh, I get**  

**No usable version of the libssl was found
./config.sh: line 86:  6055 Aborted                 (core dumped) ./bin/Agent.Listener configure "$@"**

- yum list installed | grep ssl
- openssl.x86_64                                1:1.1.1-8.el8                                    @anaconda
- openssl-devel.x86_64                          1:1.1.1-8.el8                                    @rhel-8-baseos-rhui-rpms
- openssl-libs.x86_64                           1:1.1.1-8.el8                                    @anaconda
- openssl-pkcs11.x86_64                         0.4.8-2.el8                                      @anaconda

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by chunkystew** [comment]
I had the same issue, this is fixed by installing compat-openssl10 (at least on CentOS 8). I am guessing that this issue does not crop up on previous releases that natively provide older versions of OpenSSL.

Perhaps this is something that belongs in the prerequisite installer?

**Comment by HassanHashemi** [comment]
So what's the solution here?

**Comment by tintin10q** [comment]
There is none

**Comment by tomaustin700** [comment]
I don't understand why this was closed, the issue still remains. Just tried installing the agent on Ubuntu 22.04 and ran into the exact same issue, I had to use 20.04 to get it to work. Either the prerequisites need changing to install whats needed or the agent needs changing to work with newer OS's.

**Comment by pboko** [comment]
same here with ubuntu 22.04

**Comment by SuperJC710e** [comment]
Just hit this issue as well, just testing it now, but I think what is described here might solve it: [https://dev.to/n3wt0n/no-usable-version-of-the-libssl-was-found-solved-2ffa#install-the-older-version](https://dev.to/n3wt0n/no-usable-version-of-the-libssl-was-found-solved-2ffa#install-the-older-version)

`sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install libssl-dev`

**Comment by oviliz** [comment]
Essentially we need to install an older OpenSSL version.

`wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.5_amd64.deb && sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.5_amd64.deb && rm libssl1.1_1.1.1l-1ubuntu1.5_amd64.deb`
And then do:
`sed -i 's/openssl_conf = openssl_init/#openssl_conf = openssl_init/g' /etc/ssl/openssl.cnf`

Usual M$ crap...

**Comment by dreagor** [comment]
this worked for me in Ubuntu 22.04.1 LTS
apt-get install -y libssl1.1
apt-get install -y openssl
