### ISSUE TITLE
Prevent agents automatically updating

### ISSUE THREAD

**Issue by dhirschfeld** [microsoft/azure-pipelines-agent#2455]
Our on-prem self-hosted Azure DevOps server just tried to update the agents and broke our CI/CD pipeline.

Could this "feature" please be made optional - e.g. by a command line switch to opt-out.

**Comment by dhirschfeld** [comment]
This issue is the same as https://github.com/microsoft/azure-pipelines-agent/issues/446 which wasn't resolved.

> *The agent only updates itself when it must*

Agents *never* ***have*** to update themselves. Best practice dictates immutable infrastructure which this clearly breaks. This causes the exact sort of problems experienced by us and in #446

Updating in-place is fragile and too magical - if a build requires a feature from a newer agent I'd expect the build to fail with a meaningful error message which would prompt me to deploy a *new* agent pool with the updated version - I definitely don't want my existing agents broken.

**Comment by zugl** [comment]
I'm also having problems with this.

Our build agents are unable to receive jobs because despite setting `agent.disableupdate=true` the server sends the update request and awaits the agent to update before considering the agent available.

As the agents are running inside k8s pods this is unwanted. I'd rather use the agent as a stateless deployment.

**Comment by dhirschfeld** [comment]
I was going to mention I found `agent.disableupdate` by grepping the source:
https://github.com/microsoft/azure-pipelines-agent/blob/d9a8b0774e8b6b9d997c0a77ca9686fe849c4584/src/Agent.Listener/Agent.cs#L296


...but we're observing the same behaviour - the server jsut waits for the agent to update :/

**Comment by mfourieshieldai** [comment]
We have the same problem.

**Comment by cawoodm** [comment]
We got around it ("it" being a stalled update) by removing any junctions and re-creating them. In our case `bin` was deleted by the updater and then it hung/crashed so it's:

```
mklink /j bin .\bin.2.159.2
rmdir extensions
mklink /j externals externals.2.159.2
```

Next, restart the agent.

**Comment by alex-peck** [comment]
Automatic agent updates can now be disabled in the organization pool settings.

**Comment by JanneRantala** [comment]
@alex-peck Where is this option to disable automatic update in on-premise version of Azure DeveOps Server 2020 Update 1? We started facing this issue after update to that version, and our Docker build agents keep on updating themselves useless.

**Comment by alex-peck** [comment]
@JanneRantala Organization settings > Agent pools > (your pool) > Settings > "Allow agents in this pool to automatically update"

**Comment by JanneRantala** [comment]
@alex-peck Thanks! I was looking from project settings and couldn't find it.

**Comment by sametnur** [comment]
Is there any way to schedule it out of hours?

**Comment by git-anuragjain** [comment]
How do we disable the same for Deployment Pools?

**Comment by echalone** [comment]
> How do we disable the same for Deployment Pools?

Yep, Microsoft did not implement that functionality for deployment pools.
However, you can disable it via REST API. Just execute the following in Powershell and set $CollectionUri to the URL of your Organisation/Collection and set $PoolId to the ID of the deployment pool you want to disable auto update for. You can see the ID of your deployment pool in the URL when you go to the Azure DevOps site where you manage your deployment pool. Will say something like "<CollectionUri>/_settings/deploymentpools?view=pool&poolid=37&tab=Targets" in your browser address bar. In the case of this example 37 would be the pool id.

Then use the following Powershell commands to disable auto update for your pool:
```
$Uri_SpecificPool = "$CollectionUri/_apis/distributedtask/pools/$($PoolId)?api-version=7.0"
Invoke-RestMethod -Uri $Uri_SpecificPool -Method Patch -UseDefaultCredentials -Body "{ autoUpdate: 'False' }" -ContentType "application/json" | Out-Null
```
@alex-peck are there plans to implement this functionality on the GUI side for deployment tools too? Was it just forgotten maybe?
