### ISSUE TITLE
Agent break stage on warning state

### ISSUE THREAD

**Issue by SebastienHo** [microsoft/azure-pipelines-agent#2458]
## Agent Version and Platform
Version of your agent? 2.155.1

OS of the machine running the agent? Windows Core (2016 1803)

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/dev-traceparts-com

## What's not working?

When performing a run, commands that return warning are breaking the build, (did not happen on Windows 2012 R2 nor on windows host 2019).

## Agent and Worker's Diagnostic Logs

##[section]Starting: CI process using Cake
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
Formatted command: . 'C:\agent\_work\1\s\.cicd\cake\build.ps1' -Script './.cicd/cake/build.cake' -Target 'CIProcess' -ScriptArgs '--settings_skipverification=true --BUILD_NUGET_SOURCE="https://pkgs.dev.azure.com/dev-traceparts-com/_packaging/Nuget-Packages/nuget/v3/index.json" --SYSTEM_ACCESSTOKEN=*** --BUILD_SOURCEBRANCHNAME="development" --BUILD_DOCKER_LOGIN="TracePartsDockerRepo" --BUILD_DOCKER_PASSWORD="***" --BUILD_DOCKER_ADDRESS="tracepartsdockerrepo.azurecr.io" --BUILD_SONAR_LOGIN="azure_devops_service" --BUILD_SONAR_PASSWORD="***" --BUILD_SONAR_ADDRESS="https://dev-sonar.traceparts.com" --BUILD_DESCRIPTION="Tracks solution" --BUILD_SONAR_BUILDBREAKERQUERYMAXATTEMPS=600 --BUILD_SONAR_BREAKIFQUALITYFAILS=false --BUILD_PROJECT_NAME="TraceParts.tracks.get.api" --BUILD_VERSION="2019.261.430.32" --BUILD_DB_CONNECTION_STRINGS="./connectionstring.json"'
========================== Starting Command Output ===========================
##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\agent\_work\_temp\92ca2303-7223-444d-9eae-798d778d53a9.ps1'"
Preparing to run build script...
Running build script...
  Restore completed in 79.21 ms for C:\agent\_work\1\s\.cicd\minicover\minicover.csproj.
  Restore completed in 212.82 ms for C:\agent\_work\1\s\.cicd\minicover\minicover.csproj.
Solution file C:/agent/_work/1/s/TraceParts.Tracks.sln

----------------------------------------
Setup
----------------------------------------

========================================
JobInit
========================================
Branch name: development
Version: 2019.261.430.32
Solution file: C:/agent/_work/1/s/TraceParts.Tracks.sln
Current folder: C:/agent/_work/1/s
Solution name: TraceParts.Tracks
Project description: Tracks solution
Sonar address: https://dev-sonar.traceparts.com
Sonar buildbreaker max attemps: 600
Sonar break if fails quality gate: False
Nuget source: https://pkgs.dev.azure.com/dev-traceparts-com/_packaging/Nuget-Packages/nuget/v3/index.json
Nuget Api: ***

========================================
ContainerRegistryLogin
========================================
Start docker cleanup
No container to stop !!

No images to delete
Docker environment is ready to rumble!
Cake.exe : WARNING! Using --password via the CLI is insecure. Use --password-stdin.
At line:1 char:1
+ & "C:\agent\_work\1\s\.cicd\cake\tools\Cake\Cake.exe" ./.cicd/cake/bu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING! Using ...password-stdin.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
##[error]PowerShell exited with code '1'.
##[section]Finishing: CI process using Cake

**Comment by michaelharrod** [comment]
I get the same issue with a YAML pipeline and:
```
pool:
  vmImage: 'windows-latest'
```

Do we have any workarounds for now?

**Comment by michaelharrod** [comment]
I was getting this warning which was causing the build to fail:

`az : WARNING: No credential was provided to access Azure Container Registry. Trying to look up...
`
This had no efffect:
`powerShellIgnoreLASTEXITCODE: true
`

This fixed it:

```
pool:
  vmImage: 'vs2017-win2016'
```


That's my workaround for now.

**Comment by damccorm** [comment]
Hey @michaelharrod sorry for the slow response. This looks like an issue with the image the agents are hosted on, not the agent itself. If its still an issue, would you mind filing it at https://github.com/actions/virtual-environments/issues?
