### ISSUE TITLE
GIT clone failure when using client cert auth

### ISSUE THREAD

**Issue by ScottGuymer** [microsoft/azure-pipelines-agent#2460]
## Agent Version and Platform
Version of your agent? 2.155.1

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
on-premises TFS 2018

If on-premises, which release? Version 16.122.27102.1

## What's not working?
Configured the agent to connect to the TFS server using client certificates.

The agent connects and registers correctly and can receive new jobs from the server.

Fails to GIT clone source due to an issue with the client certificate when used by GIT.

When trying GIT clone outside of the agent the same issues occur. 

Using CURL directly with the same certs works as expected.

## Agent and Worker's Diagnostic Logs

I have an open question on SO for this with relevant lots and diag information.

https://stackoverflow.com/questions/57473558/git-with-client-certificates-failing-and-working-with-curl

**Comment by jtpetty** [comment]
@ScottGuymer - I apologize for the delay in responding. Are you still having issues with this?

**Comment by ScottGuymer** [comment]
Yes this is still an issue and does not work on Linux OS 
It does seem to mostly work on windows (i think there is a workaround needed for this too)

**Comment by jtpetty** [comment]
Have you tried this with the latest agent release?

**Comment by ScottGuymer** [comment]
Im not 100% sure it is a pipelines issues or if it is an issue with GIT itself.

Do you test the agent in this configuration on linux?

**Comment by jtpetty** [comment]
I am not aware of an explicit test we have with using client certificates. Since we do not ship git with the agent for Linux, what version of git do you have installed?

**Comment by ScottGuymer** [comment]
I tried a couple. I did a write up on SO here 

https://stackoverflow.com/questions/57473558/git-with-client-certificates-failing-and-working-with-curl
