### ISSUE TITLE
Make agent exit on job completed

### ISSUE THREAD

**Issue by fgervais** [microsoft/azure-pipelines-agent#2473]
As a bit of context, I'm running the agent inside a container.

I'd like to add a startup option to the agent so it runs in a mode where is will exit when the job is completed.

Doing so, it will make the container shutdown and then restart so the next job gets a fresh container. This will replicate the feel of an hosted agent.

What would be the best way to add this agent runtime mode?

**Comment by kirkone** [comment]
Hi,

there is an `--once` flag when running the agent as described here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#agent-setup

**But!**
Be aware of this issues:
https://github.com/MicrosoftDocs/vsts-docs/issues/5487
and
https://github.com/microsoft/azure-pipelines-agent/issues/2332

I hope this helps.

**Comment by fgervais** [comment]
This is exactly what I needed, thanks @kirkone.

If it helps others, I use the `--once` flag in my docker container like this:

```
exec ./externals/node/bin/node ./bin/AgentService.js interactive --once
```

as described in https://github.com/MicrosoftDocs/vsts-docs/issues/5910.

Coupled with:

```
tmpfs:
      - /azp/agent/_work
restart: always
```

Gives me a fresh environment every time.

**Comment by kirkone** [comment]
@fgervais I also build something like you described above, if you want you can have a look here:
https://github.com/codez-one/docker-azure-pipelines-agent

I would appreciate suggestions and feedback.
