### ISSUE TITLE
Deletion of existing build directory is too slow

### ISSUE THREAD

**Issue by ustun** [microsoft/azure-pipelines-agent#2474]
We are using hosted agent with Azure Devops. I have noticed that for our CI pipeline, the build takes too long to initialize. After enabling system diagnostics, it turns out that the deletion of existing build directory seems to take about 2-3 minutes. 

This is a fairly typical node.js app, so I'm guessing it takes too long to delete the `node_modules` folder.

I'm wondering whether it might make sense to rename the old directory instead of deleting, and delete the old directory behind the scenes?

<img width="1073" alt="Screen Shot 2019-09-27 at 1 41 38 PM" src="https://user-images.githubusercontent.com/94374/65771612-48157380-e141-11e9-9477-cb68b30900cf.png">

**Comment by ustun** [comment]
I tried to delete node_modules manually at the end of the build via a Bash script `rm -rf $BUILD_WORKINGDIRECTORY/node_modules` and that one took about 2-3 minutes as well. We are using standard SSD's, we'll try to give premium SSD's a try as well. However, it still does not make sense that the deletion takes that slow on an SSD.

**Comment by ustun** [comment]
We switched to using ephemeral disks on Azure for our build servers, and our build time went from 11 minutes to 3.5 minutes.

The initialization stage, which was taking about 3-4 mins now takes 5 seconds.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/ephemeral-os-disks

**Comment by jtpetty** [comment]
@ustun - It seems as if you were able to resolve your issue on your own using faster disks. Is this correct?

**Comment by ustun** [comment]
Yes, using ephemeral disks. Most people might not be aware of this solution though.

**Comment by jtpetty** [comment]
@ustun - Thanks for sharing your solution!
