### ISSUE TITLE
Retry move of directory when updating agent version

### ISSUE THREAD

**Issue by jtpetty** [microsoft/azure-pipelines-agent#2475]
It is possible when doing an auto-update of an agent that the file handle lock on the bin/ directory will take remain some time after the process is shutdown, especially on Windows hosts. This can cause the update process to fail as it tries to move the current directories out of the way and install the new versions. 

We can reduce the likelihood of a failed update by attempting retires on the move operation.

**Comment by alex-peck** [comment]
Perhaps a better solution would be to have the `run.sh` script use the new version of the bin folder instead of moving it.
So for example:
Agent starts with `bin/` and `externals/`
During the update, instead of moving files around, we download the new binaries to `bin.(VERSION)` (similar to what we do now).
Then, the `run.sh` script knows to look for the highest version available and just runs the .dll from that folder.

**Comment by jtpetty** [comment]
I think that would work if we could guarantee no customer is relying on accessing the binaries through bin/ or externals/. I am not sure we can do that. There are a few places where we reference git or node through $AGENT_ROOT/externals. The ```run.sh``` script is not the only entry point to the agent.

**Comment by jtpetty** [comment]
Another option as I think about it might be to use ```rename``` instead of ```move```. I am not sure if ```rename``` works better with file locks.

**Comment by stephenmoloney** [comment]
Hi @jtpetty and @alex-peck 

I quite like the idea of downloading to new directories - but as you say there are potential impacts on other customers who make direct references to those files.

Some further thoughts:

- Check for any residual file handles. Log the existence of such file handles. Close any residual file handles. Perhaps [handle](https://docs.microsoft.com/en-us/sysinternals/downloads/handle) is useful here but I don't know if this is installed on windows systems by defaults and especially not sure when it comes to docker windows-servercore and nanoserver. So this is probably a non-runner.

- Poll for any residual locks on that folder and simply wait for them to be closed by the os. Although, hopefully such locks are closed.

**Comment by stephenmichaelf** [comment]
@jtpetty This is related to our current agent work stream.
