### ISSUE TITLE
Peering Az DevOps agents possible?

### ISSUE THREAD

**Issue by rdagumampan** [microsoft/azure-pipelines-agent#2477]
Hi Az Pipelines Agent team,

This is an open question and I am open to other ideas. 
Scenario: We started an initiative to finding ways to do Continuous Delivery to our OT-based services. OT-based services are typical self-hosted services running on Windows servers under secured perimeter of our OT Network Zones. Typically, we package the application and manually deploy changes by going thru layers and Jump Hosts. Could there be a way to do this differently? Can we achieve the same level of Continuous Delivery as we do in normal IT-services? One idea could be peering Az DevOps Agents as indicated in Purple lines and boxes but I'm not sure if its technically feasible. Appreciate your advise.

Flow works like this:
- Dev commits code, test, deployed to dev, test, staging (all in IT)
- Release manager make a release, approved for deployment to OT
- Az DevOps Agent (IT) mirrors the release into Az DevOps (OT) Agent running in OT
- Az DevOps Agent (OT) deploys the packages
- Az DevOps Agent (OT) notifies deployment status to IT to Az DevOps Dashboard

![image](https://user-images.githubusercontent.com/5895952/65948868-5a422b00-e43b-11e9-8397-8359b1f2b83e.png)

**Comment by vtbassmatt** [comment]
@rdagumampan hi, and sorry for the delay responding. I'm sure that I don't fully understand your tooplogy and requirements, so please forgive me if I miss something obvious.

The Azure DevOps agent needs to have line of sight to both your deployment target and to Azure DevOps. However, the Azure DevOps server doesn't itself need to have line of sight to your deployment target. I think the layer I don't understand is what you've titled "Enterprise Layer IT". What stops you from simply having:

```
(INTERNET)                    [ Azure DevOps ]
                            _.        /|\
                            /|         |
                       push code       |
                         /             |
(ENTERPRISE)     [ developer ]         |
                                 HTTP long poll
                                 initiated from
                                 agent, but job
                                 logically flows
                                 down to agent
                                       |
--- FIREWALL --------------------------|---------------------------------
                                       |
(PROCESS CONTROL)            [ Pipelines agent ]-->[ Target environment ]
```

(Sorry for the crappy ASCII art, I don't draw many network diagrams :grin:)
