### ISSUE TITLE
Agent info for Ubuntu 1604 is incorrect (Google Chrome Version and others)

### ISSUE THREAD

**Issue by JSalazar88** [microsoft/azure-pipelines-agent#2493]
## Agent Version and Platform
Ubuntu 1604

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

## What's not working?
The agent info popups indicate Google Chrome is installed as "Google Chrome (Google Chrome 75.0.3770.100 )"

This is not correct, and is very misleading.

It is "Google Chrome (Google Chrome 76.0.3809.100 )", as shown in the project Github page for the [latest release pushed](https://github.com/microsoft/azure-pipelines-image-generation/blob/75c7279063e1fa827b9c49dbfb32f75978dc228e/images/linux/Ubuntu1604-README.md).

Whomever did the PR which merged the Chrome updates definitely forgot to update the docs as well.

**Comment by jtpetty** [comment]
@JSalazar88 - Thank you for reporting this issue, but this is an issue with the agent image (https://github.com/microsoft/azure-pipelines-image-generation), not the agent code itself. Unfortunately, I do not have the ability to transfer the issue for you.
