### ISSUE TITLE
Agent not working on macOS 10.15, *.dll been blocked by Security Settings

### ISSUE THREAD

**Issue by KhuongNtrd** [microsoft/azure-pipelines-agent#2496]
## Agent Version and Platform
2.158.0 OSX
## What's not working?
Current agent work correctly in macOS 10.14, but while upgrade to macOS 10.15, while start agent by ./run.sh command OS asking "macOS cannot verify the developer of System.Runtime.dll. Are you sure..."

I tried allow this dll in Security Settings, but OS keep get warning with another dll file of agent.

**Comment by jtpetty** [comment]
@KhuongNtrd - is this issue still occurring?

**Comment by stephenmichaelf** [comment]
This should be fixed with .NET Core 3.1.

**Comment by KhuongNtrd** [comment]
@jtpetty the latest version of agent work perfectly

**Comment by jtpetty** [comment]
Great! Thanks for letting us know.
