### ISSUE TITLE
PAT auth suggestions and +1 for BYOS

### ISSUE THREAD

**Issue by pdylanross** [microsoft/azure-pipelines-agent#2500]
## Agent Version and Platform
2.158.0 - Ubuntu 18.04

## Azure DevOps Type and Version
dev.azure.com/CuraDigitalHealth

## Issue
I've been working on developing a pipeline to maintain our self hosted agents in AWS using packer+ansible to build machine images and terraform to deploy them. The end goal is to have an entirely gitops based workflow around managing build agents. I have the pipeline working, however I am forced to run the packer builds manually because the agent provisioning process requires a PAT (I know I could make a PAT and save it as a secret in azure devops, but if I ever get hit by a bus / move jobs, someone will be really confused after they disable my user account).

After pouring over the docs I can't seem to find much useful information about alternative authentication methods that would work in this paradigm. The auth information I would prefer to use would either be available to the build agent user at build time or to the AAD/IAM user the agent runs under. Managing via AAD/IAM & fetching creds at startup would be preferable - that would allow us to avoid baking auth information into machine images.

This seems like it would be crucial for the [BYOS proposal](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/byos.md). What I've done with my workflow is more or less a child's play version of that. From my perspective, this is the only major blocker from making that happen.

**Comment by btl5037** [comment]
Why do you own the Azure Devops account. The account should be owned by an organizational functional ID within your company, that persists beyond you. Then the organization would grant your personal user access to the resources you need as the GitOps leader. The PAT would be generated by the functional ID account.

**Comment by pdylanross** [comment]
From my experience that is not how PAT's work. The whole reason that I am worried about the hit by bus / closed user account scenario is because at the last company I worked for the devops team would throw pats around like nobody's business and whenever someone left the company it was always an exciting exercise of cleaning up the mess. The reason is that on the org admin side of things as soon as someones employment was terminated they would go disable all associated user accounts - even when developers would specifically ask them not to. It was outside of our control. 

That being said - I've passed the buck on this issue for the time being. For now I'm using the hosted agent everywhere and I have built a decent set of pipeline templates for installing specific dependencies build time. Not ideal but it works.

**Comment by vtbassmatt** [comment]
BYOS handles this by handing out an access token that's good for registering an agent. I'm researching what options you have outside of that specific path.

**Comment by vtbassmatt** [comment]
From talking with our identity/authZ folks, this isn't easy to do. For anyone who wants to push on this, the best path is opening a suggestion ticket on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by vijayma** [comment]
@pdylanross Can you let us know the name(s) of Azure DevOps org(s) where you would like to preview the BYOS feature, if you are interested in that option?

**Comment by btl5037** [comment]
@vijayma The Hyperledger org would love to test the BYOS functionality if a preview becomes available.
