### ISSUE TITLE
yaml pipelines with (self-hosted) Agent pools via Virtual Machine Extension Microsoft.VisualStudio.services TeamServicesAgent

### ISSUE THREAD

**Issue by brwilkinson** [microsoft/azure-pipelines-agent#2510]
I am trying to transition from Azure DevOps Pipeline Releases, using (self-hosted) Deployment Groups agents….

To yaml pipelines with (self-hosted) **Agent pools**.

The unattended install is documented . .  

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#unattended-config

However I prefer to use the ARM VM “TeamServicesAgent” extension from “Microsoft.VisualStudio.Services”

I believe the Agent is the same, however the arguments to install into the pools is different.

Does anyone know if this extension will support Agent Pools ? or if there will be an update? Perhaps a 2.0 version?

![devOpsagent](https://user-images.githubusercontent.com/3605266/66707867-a5422500-ecfc-11e9-99e5-359bb7eb2f47.png)

**Comment by moswald** [comment]
Hi @brwilkinson, this is a good question, and something I'm looking into for my own purposes within Azure DevOps. I'll keep you posted on what I find.

cc: @bradwillis

**Comment by brwilkinson** [comment]
Thanks @moswald  and @bradwillis

**Comment by moswald** [comment]
I just finished my explorations here, and apparently our VM extension is meant just for deployment groups. As you suggested, I think I'll probably have to create a v2.0 in order to support my own needs, but I can't tell you when I'll be able to do that. Hopefully it's something I can get to before the end of the year, but I can't commit to any concrete timeframe.

Let me know if you have any questions or comments.

**Comment by brwilkinson** [comment]
Hi @moswald any chance you might want to look into the V2 extension for this?

The install process is the same, it's just a slightly different command line argument to connect into the Deployment Agents, instead of the Deployment groups.

**Comment by brwilkinson** [comment]
@moswald I just wanted to check in on this one.

The agent pools and the deployment groups get installed with the exact same agent/package.

There is only small parameter differences between installing between the two different options.

This seems like a good opportunity to extend the capability here, rather than to duplicate the effort ?

This is the example of the agent pool:

```powershell
.\config.cmd --agent $agentName --auth pat --token $token --url $orgUrl --pool $Pool --acceptTeeEula --runAsService --unattended
```

This is the example of what you have with the deployment groups:

```powershell
.\config.cmd --agent $agentName --auth pat --token $token --url $orgUrl --projectname $project --deploymentgroup --deploymentgroupname $group --work '_work' --acceptTeeEula --runAsService
```

So the main difference is just between the ...

deployment group project info
**--projectname $project --deploymentgroup --deploymentgroupname $group**

and the pool info
**--pool $Pool**

**Comment by moswald** [comment]
Sorry, @brwilkinson, I missed your question a month ago. We ended up going a different route to get the feature out quickly, but we're still considering moving to a full extension for the final version. There's no traction there yet, but it's not off the table, either.

cc: @WillLennon

**Comment by brwilkinson** [comment]
@moswald okay thank for the follow up.

What was the route that you went for this? was it related to the agent pools?

**Comment by moswald** [comment]
We are currently using the Azure Custom Script VM Extension to install the agent, but since you're only allowed to create one of those it's limiting for customers who want to use their own custom script.

**Comment by brwilkinson** [comment]
@moswald okay no problem

We currently use DSC extension for this anyway, in a way that has been more flexible for installing multiple instances of the agent, however we would still prefer to be able to install the first instance via a dedicated extension if available.

**Comment by brwilkinson** [comment]
adding link to sample code to deploy agents in case anyone else is looking.

https://gallery.technet.microsoft.com/scriptcenter/Setup-Azure-DevOps-Agent-dfa6f49a

**Comment by surlypants** [comment]
> adding link to sample code to deploy agents in case anyone else is looking.
> 
> https://gallery.technet.microsoft.com/scriptcenter/Setup-Azure-DevOps-Agent-dfa6f49a

any chance this code can be re-shared?

better yet, any chance this extension will be modularized to support "environment" (as well as the requested "pool"?

2022 and this is still relevant.

**Comment by brwilkinson** [comment]
@surlypants sure I moved it here.

https://github.com/brwilkinson/msdn-scriptcenter-repo/blob/main/artifacts/481820/%5B226535%5D%20setDevOpsAgentPool.ps1

I also turned this into a DSC Module:

https://github.com/brwilkinson/DevOpsAgentDSC
