### ISSUE TITLE
Releases in Github are incorrectly marked as pre-release

### ISSUE THREAD

**Issue by giggio** [microsoft/azure-pipelines-agent#2521]
Your [releases](https://github.com/microsoft/azure-pipelines-agent/releases) are incorrectly marked as pre-releases. The current available version on Azure DevOps is `2.159.1`, but that version is marked as pre-release (see https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.159.1).
Same for `2.158.1` and `2.159.0`. The latest non pre-release is `2.158.0`, which is more than a month old.

Please fix this, as we are watching the releases and this is reporting incorrectly.

**Comment by kirkone** [comment]
Hi,

I stumbled across the same issue. Is there any documentation which version is a valid release?

@giggio can you give me a hint how you monitor the releases from outside of this repo? I really could use this in my repo too, thanks.

**Comment by giggio** [comment]
@kirkone We are using the Github API. This is what we want to do when this bug is fixed:

https://github.com/Lambda3/docker-azure-pipelines-agent-windows/blob/a061932d4ce26cd15a7627e797995e1f29d0d822/agent/Dockerfile#L77-L85

This might be a bug with the @azure-pipelines-bot, as it is the one releasing.

@jtpetty or @vtbassmatt I can see from the commits that you maintain this repo. Would you be able to help us?

**Comment by vtbassmatt** [comment]
@giggio thanks and sorry about that. I'm not sure what changed but we will take a look.

**Comment by jtpetty** [comment]
The marking of releases as "no longer Pre-Release" is a manual step and was accidentally left out of our process. This has been updated and we are now properly marking versions as no longer pre-release.

**Comment by giggio** [comment]
Ok, but the process seems to not be working. Release 2.160.0 was released 10 days ago and it is still marked as prerelease, but it is available for download from the Azure DevOps site.

**Comment by vtbassmatt** [comment]
Looks like it's updated now.

**Comment by giggio** [comment]
Cool, thanks!
