### ISSUE TITLE
Pre-warm hosted agents - BYOS ?

### ISSUE THREAD

**Issue by rickardp** [microsoft/azure-pipelines-agent#2523]
This is more of an enhancement request. Currently we use the hosted agents, as well as self-hosted agents hosted in our development AKS cluster. 

Our reason for self-hosting is purely because pulling the entire build system from Docker adds a minute to each build stage, but maintaining the build agents is tedious and not something we want the team to focus on. Since we have many stages that can be allocated to different agents, the downloading of images adds minutes to the build time (a significant amount since our builds are otherwise quick).

One thing that I thing would be really useful for us is if we could use something like the BYOS proposal and perhaps run a YAML pipeline upon creation of such an agent where we can define the initialization tasks, such as downloading all our docker images locally etc, before the image is created. This has to run every time the base image is updated or if we change something such as build system docker image versions, but not just because the number of build agents is scaled.

I don't know if that is something you considered, but for us it would be highly useful instead of having to "burn" a VM image etc.

**Comment by btl5037** [comment]
It feels to me like this would be part of the image from which you create the scale set, would it not. You specify the VM and image when you create the scale set, and then tie the scale set to BYOS like it is in the pictures.

**Comment by rickardp** [comment]
That sounds like a possible implementation. As the set of base images change frequently, that would require that it is easy to extend the base image, e.g. by caching base images. Building and upgrading the base images is something I would want to do directly from Azure pipelines in this case.

**Comment by vtbassmatt** [comment]
This will eventually be part of BYOS / elastic self-hosted agents. It's not feasible for hosted agents in any timeframe I can foresee.

**Comment by damccorm** [comment]
Hey, thanks for the feedback - we're tracking this internally and it should be coming soon. I'm going to close here since the feedback has been propogated internally.

**Comment by vijayma** [comment]
@rickardp Can you let us know the name(s) of Azure DevOps org(s) where you would like to preview this feature?

**Comment by rickardp** [comment]
@vijayma You got mail :)
