### ISSUE TITLE
Standard file descriptors missing from procfs on Ubuntu during shell script task

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-agent#2532]
While testing the fix/workaround from https://github.com/microsoft/azure-pipelines-tasks/issues/11334#issuecomment-533233625, I needed to tee the output from a subshell to the root shell's stdout, so that the log would still contain some information while the task was in progress. My solution, which seems to be pretty standard in Linux, is:

```
ROOT_SHELL=$$
(
# ...
) 2>&1 < prng_out | tee ../dieharder.txt /proc/${ROOT_SHELL}/fd/1 | (grep -m 1 'FAILED' &&\
(
  pkill dieharder
  pkill java
  exit 1
))
```

This works fine on my workstation. But when it runs on Azure Pipelines with the `ubuntu-latest` image, I get:
```
tee: /proc/7072/fd/1: No such device or address
```
This suggests that either the script's root shell has been replaced with a different process mid-task, or it has closed its stdout prematurely and started writing the log to a different fd, or procfs is somehow non-POSIX (or at least doesn't follow the same de-facto standards as bare-metal systems) on Azure. Is there still a way to write to the log from a stdout-redirected subshell, other than creating a named pipe for the purpose?

**Comment by jtpetty** [comment]
@Pr0methean - This is an issue with the host image for agents, not the agent code itself. Can you post this issue on https://github.com/microsoft/azure-pipelines-image-generation ? Unfortunately, I do not have the ability to move this issue to that project.
