### ISSUE TITLE
Unable to detect build errors Using build definition

### ISSUE THREAD

**Issue by girishgalla** [microsoft/azure-pipelines-agent#2537]
I Have created a build definition for ASP.net core 2.2 application on .sln file,
i intensionally commited wrong code which i will get build error in visual studio 2017, but when build definition is run build task it is not showing any error and build is also passing ....please help me

![1](https://user-images.githubusercontent.com/44398188/67258208-26dc4480-f4ad-11e9-8665-b227de9ab99c.png)

![2](https://user-images.githubusercontent.com/44398188/67258214-280d7180-f4ad-11e9-8942-9b9023e08b2d.png)

![3](https://user-images.githubusercontent.com/44398188/67258216-293e9e80-f4ad-11e9-8f58-4c1c9530b223.png)

![4](https://user-images.githubusercontent.com/44398188/67258218-2a6fcb80-f4ad-11e9-8b08-dc9de9a7c090.png)

![5](https://user-images.githubusercontent.com/44398188/67258219-2c398f00-f4ad-11e9-8648-172a9e54d1f8.png)

![6](https://user-images.githubusercontent.com/44398188/67258225-30fe4300-f4ad-11e9-9aaf-24cac14c8e8e.png)

![7](https://user-images.githubusercontent.com/44398188/67258227-322f7000-f4ad-11e9-927b-d0d27b08b81f.png)

**Comment by vtbassmatt** [comment]
It looks like you're in need of tech support, not reporting an issue with the agent. Please see our [support resources](https://azure.microsoft.com/support/devops/), up to and including opening a ticket. Thanks.
