### ISSUE TITLE
Clarify PAT Scope and Expiration

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-agent#2552]
Installing "Agent.Listener.exe" with a PAT it is unclear what the scope of the PAT is in terms of authorization required and how long the PAT must be valid.

The docs say the PAT is only required during installation (config.cmd) which begs the question: which user/authorization process is in place after the installation??

We are seeing 401 errors in our logs and agents not responding to jobs and this could potentially be a PAT issue.

Windows 2012 Server.

**Comment by cawoodm** [comment]
I agree the docs claim this but we had the experience of using the same PAT on multiple agents and the initial agents stopped working so I wasn't sure. It's also not clear which rights the PAT should have so I guess the doc could be improved.

**Comment by vtbassmatt** [comment]
That's fair. I'll see if our doc writers can take a swing at improving that. https://github.com/MicrosoftDocs/vsts-docs/issues/6209
