### ISSUE TITLE
Fallback to Service Mode

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-agent#2564]
Hi All,

We would like use the Windows Agents with "--once" argument for self-hosted one time agents.
However, we would like keep the service mode open as fallback option. 

That's why we do not configure the Agent with "--runAsService" argument on the first time but we deploying a new Windows Service and preparing the .service file manually. 
This file is contain the new service name and the service is running the AgentService.exe binary.

The Agent is running properly with interactive mode.
The Service is running but the Agent state keep offline after starting.

1) Is there any requirement for the service mode?

2) Can we configure the Agents with "--runAsService"  WITHOUT starting the service automatically after the Agent configured itself?
This is the reason why we are not using the "--runAsService" for service creation.

Thanks a lot!

Regards,
Gabor

**Comment by vtbassmatt** [comment]
:wave: @iambernics - I'm not sure I fully followed the question. Why do you want to run as a service but shut down after just one job? Running as a service is designed to be resilient and run constantly, while running once is designed for scenarios where agent hosts (such as containers) are disposable.

**Comment by iambernics** [comment]
Hi Matt,

I would like provisioning a new instance for every job due to privacy and security reasons in enterprise environment, similar like the Microsoft hosted Agents.
The "--once" is providing the trigger for reverting the Agent from snapshot.
I would like avoid the Windows auto-login function for starting the Agent in interactive mode and the WinRM is a point of failure for the long-term sessions.

Regards,
Gabor

________________________________

**Comment by vtbassmatt** [comment]
Thanks, that makes sense. You can configure the agent as a service, and you shouldn't have to run it right away.
