### ISSUE TITLE
Permissions Issue Linux

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-agent#2575]
## Agent Version and Platform
* Agent 2.159.2
* Linux CentOS 7.6.1810

## Azure DevOps Type and Version
* dev.azure.com

What is your organization name?
buhlergroup

## What's not working?
As documented [here](https://stackoverflow.com/questions/58705495/nodejs-linux-checkpermissions-node-modules) there is a permissions issue where `npm install` is failing even though the service user has full access to all directories.

**Comment by jtpetty** [comment]
@cawoodm - Looking at the referenced post: 

The group power user does not have write access to /xxx/yyy/node_modules, only the user serviceuser.  

Run as serviceuser to give write access to the group:

`% chmod w+g node_modules`

**Comment by cawoodm** [comment]
True, however the Pipeline is run by an agent (daemon) which runs as the `serviceuser` and that's where we first logged this problem. I think I then logged in `su - serviceuser` and could reproduce the problem.
I'll get back to you...

**Comment by jtpetty** [comment]
@cawoodm - Any update? Is this still an issue for you?

**Comment by cawoodm** [comment]
Sorry, due to time constraints we gave up on Linux for the moment and will take it up again next year.
I'll close out and get back if we run into this again.
Thanks!
