### ISSUE TITLE
Is Windows Server 2019 a supported OS for agent?

### ISSUE THREAD

**Issue by gholliday** [microsoft/azure-pipelines-agent#2580]
Under `Check prerequisites` section of [Self-hosted Windows agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops) it links to https://aka.ms/vstsagentwinsystem which links to https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/start/envwin.md, which makes no mention of `Windows Server 2019`

I expect that it **is** supported, given that the [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) have a `windows-2019` image which runs the same agent.

Can we get the docs updated with what OS's the agent is supported on? Even if it's a future-proof statement like "anything .NET Core runs on" as mentioned in https://github.com/microsoft/azure-pipelines-agent/issues/483#issuecomment-239413801

/CC https://github.com/MicrosoftDocs/vsts-docs/issues/6250

**Comment by jtpetty** [comment]
@vtbassmatt - Can you take a look at this and update our docs?
