### ISSUE TITLE
Update ubuntu-latest to Zulu 13

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-agent#2582]
Azul Zulu OpenJDK 13 has been available since September, but tonight I learned that it still isn't pre-installed in the Microsoft-hosted `ubuntu-latest` pool (at least not with a path that follows the pattern of previous versions):
```
/home/vsts/work/_temp/bf6bce63-30e5-48f2-abfa-2e76f8006e04.sh: line 1: /usr/lib/jvm/zulu-13-azure-amd64/bin/java: No such file or directory
```
https://github.com/Pr0methean/BetterRandom/blob/master/azure.yml partially works around this issue, since it uses AdoptOpenJDK's JDK13 build with OpenJ9 rather than another JDK12 build in the matrix. (OpenJ9 isn't available through Zulu anyway, so the jobs download it rather than using pre-installed copies.) But this would probably be much harder in a build system that didn't respect the JAVA_HOME environment variable consistently as Maven does.

**Comment by jtpetty** [comment]
@Pr0methean - This issue is with the image of the host running the agent, not with the agent code itself. Can you open this issue on this project https://github.com/microsoft/azure-pipelines-image-generation ? Unfortunately, I do not have a way of transferring it for you.
