### ISSUE TITLE
Remove legacy powershell handler

### ISSUE THREAD

**Issue by damccorm** [microsoft/azure-pipelines-agent#2593]
We said we were going to do this in https://github.com/microsoft/azure-pipelines-agent/pull/2314 and it seems like it won't cause too many issues. I think we should start failing tasks using this handler in our next release (m161) and completely remove it in the following release.

@vtbassmatt are you still good moving forward with this? Looks like you had some say in this last time, not sure if you remember any context to add

**Comment by vtbassmatt** [comment]
I'm +1 on making this change.

We shouldn't make this an adoption blocker for Server 2020, though. I propose we start failing tasks with that handler right now, but leave in an option to override / get back to old behavior. After we snap for 2020 (meaning that 2020 will ship with an agent capable of -- but not happy to -- run these legacy tasks), we can fully remove it in the next agent release. Thoughts?

**Comment by vtbassmatt** [comment]
We'll postpone this until 163 to give RM a chance to update their tasks.

**Comment by damccorm** [comment]
I believe we decided not to do this after some conversations with RM
