### ISSUE TITLE
Registering under a pool does not add tags

### ISSUE THREAD

**Issue by mrtristan** [microsoft/azure-pipelines-agent#2610]
Using agent version `v2.160.0`

when using flags `--deploymentpool --deploymentpoolname XXX` i was hoping to be able to also add tags to this registered agent using the `--addDeploymentGroupTags --deploymentGroupTags XXX` flags. I was hopeful that this would work but was expecting that there was a chance it wouldn't since the tags vars are specific to "Deployment Groups" and not "Deployment Pools"

Is there some overarching reason why this is not possible or is it feasible that a small update to the agent registration will also add the tags to the machine?

**Comment by damccorm** [comment]
@chshrikh could you take a look or route to someone on the RM side who can help on this?

**Comment by chshrikh** [comment]
@mrtristan  "Deployment Pool" is collection level entity and can be shared pool across project, and tags are scoped with project. You can not add tags to agent you see with deployment pool. If you need to add the tags to agent, share the pool with project and then go to "Deployment Group" page in project, there you will be able to add the tags.

**Comment by mrtristan** [comment]
@chshrikh thanks, was looking to do this in ci / cd pipelines. is the agent able to perform the actions you're describing?

**Comment by chshrikh** [comment]
Just want to understand your requirement clearly,  do you want to add tags to deployment target in CI/CD flow or you want to share the "deployment pool" with project ?

-- you can add the tags to "Deployment Group" target while doing configuration itself
