### ISSUE TITLE
Elastic Self Hosted Agents Feedback

### ISSUE THREAD

**Issue by jpm63** [microsoft/azure-pipelines-agent#2615]
Awesome to see you guys adding this functionality to your roadmap. We have written and deployed a similar autoscaling solution internally to address the challenges you list in your specification document. Having a flavor this functionality built into Azure DevOps would be a significant value-add for us and would be one less thing we have to worry about. A couple thoughts on your current spec:

1. I can understand targeting Azure first, but until we can target other clouds, this solution will be of limited utility to us. We have various factors which drive us to host at least a portion of our agents on premise, which would be out of scope of the spec as written.

Have you considered leveraging the service hooks feature of Azure DevOps to allow the configuration of a provision/deprovision URL on a per-pool basis? This architecture would insulate the control algorithm from where the agent actually lives, and allows your customers to integrate their on-premise systems (which are inevitably unique) or other cloud providers while still offloading as much of the intelligence to Azure DevOps.

2. We maintain a set of build/release definitions which we use for agent testing. Any significant changes must successfully execute each job before the configuration change is accepted. It would be great to allow the optional configuration of 1..N jobs to verify functionality before making an agent available for gen-pop usage.

Otherwise - great stuff and looking forward to seeing this implemented!

**Comment by stephenmichaelf** [comment]
FYI @vtbassmatt @jtpetty

**Comment by vtbassmatt** [comment]
@vijayma for the elastic self-hosted agents feedback.

@jpm63 elastic self-hosted agents are built on top of a lower-level system called pool providers. It works essentially as you describe :grin: We haven't moved forward with productizing it into something you could consume, but we've got a few internal customers kicking the tires right now. I'll add your voice as a +1 to us prioritizing this next planning cycle.
