### ISSUE TITLE
git clean follows junction points

### ISSUE THREAD

**Issue by sunahe** [microsoft/azure-pipelines-agent#2626]
## Agent Version and Platform
Agent 2.153.1 running on Windows Server 2012R2 or Windows Server 2019 

## Azure DevOps Type and Version
Azure DevOps Server 2019.1

## What's not working?
When `git clean -ffdx` is run by the agent as a part of checkout, git recursively follows NTFS junction points and deletes everything in there. That can cause problems when junctions are created into cache folders, and more serious problems when a junction is created into drive root by mistake.

The issue was addressed in git 2.23 by git-for-windows/git#2268 so updating the bundled git to 2.23 or later would resolve this.

**Comment by jtpetty** [comment]
@vtbassmatt - Do you know of any reason why we could not update the version of git for windows in the agent?

**Comment by vtbassmatt** [comment]
@jtpetty we should do this. At one point, I was even hoping to automate updates (or at least automate grabbing + testing them) to GfW so that the agent would always be on latest.

**Comment by jtpetty** [comment]
Agent 2.164.0 has been updated to use mint 2.24.0.2. This was done with PR #2657

**Comment by jtpetty** [comment]
This was released in agent 2.146.6
