### ISSUE TITLE
Containers on Windows failed to start

### ISSUE THREAD

**Issue by kant2002** [microsoft/azure-pipelines-agent#2639]
I experience issue which is related to docker/for-win#1560 where in my build that nagging errors happens. I solve that by running `docker container prune`, but I believe that can be solved by running something on the container job cleanup tasks. 

VSTS Agent: 4e012a623b4b3dfaaf9594a7ddb3a9731c1bb09c (maybe I should try on absolutely latest)

My setup is agent on Windows 1909 host + build definition has service container.

**Comment by kant2002** [comment]
In my experience this is related to case when same task started on the same agent consequentially. Maybe just was not enough time for the removal of `taskkey` file

**Comment by jtpetty** [comment]
@kant2002 - do you have any logs from when this issue occurs that you can share?

**Comment by kant2002** [comment]
Yes. Process following.
Build definition
```
1. Initialize containers
..
2. Tests which use container
...
3. Stop Containers
```

- First build on that agent fail on `Step 2. Tests`. Logs in 
[vsts_docker_issue_build_1_step_15.txt](https://github.com/microsoft/azure-pipelines-agent/files/3944214/vsts_docker_issue_build_1_step_15.txt)
- Second build fail to start container. Logs from that task. Logs here:
[vsts_docker_issue_build_2_step_4.txt](https://github.com/microsoft/azure-pipelines-agent/files/3944218/vsts_docker_issue_build_2_step_4.txt)

**Comment by kant2002** [comment]
I fixing that right now, manually removing `C:\b\_work\.taskkey` after that everything running fine.

**Comment by kant2002** [comment]
Seems to be this is not fully fixed. After I run tests on the latest master

```
Error response from daemon: error while creating mount source path '/host_mnt/c/b/_work/.taskkey': mkdir /host_mnt/c: file exists
Error: failed to start containers: 3019a8d27476811494e4aceac118556989267ef42aea6bd2a52ede401026241e
```

And what's interesting is that there no file `c:\b\_work\.taskkey`

**Comment by kant2002** [comment]
On occasion `Initialize containers` task complain on `_temp` folder, and I experience situation where I was stuck and no `docker container prune` nor removing offending folders helps. Build start working only after I restart `Docker for Windows`. Not sure what's cause for this issue. If somebody explain me what's `.taskkey` file for, and on what phase it is created, I may introduce more logging and try to troubleshoot myself.

**Comment by jtpetty** [comment]
From what I understand, the .taskkey file is used as a key vault during a job run. It is initially an empty file and can be thrown away at the end of the job. With containers, it gets tricky since some tasks run inside a container and some on the host which is why the .taskkey is created on the host and mounted inside the container.

Let me take a look at the code and see if I see anything obvious. I know one of there are some issues with Windows and Docker running Linux containers with regards to file mounting. It may be the issue is there and not with anything on the agent.
