### ISSUE TITLE
Pipeline.Workspace broken in version 2.161.1

### ISSUE THREAD

**Issue by pvizeli** [microsoft/azure-pipelines-agent#2648]
## Agent Version and Platform
Version of your agent? 2.161.1

OS of the machine running the agent? Ubuntu 16.04.6 LTS

## Azure DevOps Type and Version
dev.azure.com

## What's not working?

It seems like `Pipeline.Workspace` should contain /__w/1/, however, it now contains  /home/vsts/work/1/ and it fails.

`Pipeline.Workspace` is used for cache flows and this issue breaks the functionality of Cache@2.

I think this issue is also the same as #2646 
I have open a support request with number: 119120425000466

## Agent and Worker's Diagnostic Logs

https://dev.azure.com/home-assistant/Home%20Assistant/_build/results?buildId=18593&view=results

**Comment by pvizeli** [comment]
I found also this report: https://developercommunity.visualstudio.com/content/problem/844025/container-build-jobs-paths-are-incorrectly-mapped.html

**Comment by jtpetty** [comment]
This is the same issue as #2646 and we are working to push out a fix. If you have a self-hosted agent, you should be able to manual downgrade your agent to 2.160.1.
