### ISSUE TITLE
The agent's Win32 service .exe fails on Windows IoT Core

### ISSUE THREAD

**Issue by seanmcd-msft** [microsoft/azure-pipelines-agent#2666]
Related to issue #2665 and PR #2664 The failure is because it expects the application event log to always be present. and, the application event log doesn't exist on Onecore based editions of windows. Fixing this is more complex than i have time to tackle right now. i'm just posting the issue for awareness.  The workaround is to run the agent interactively on boot via schtasks.exe and redirect console output to a log file so that you can diagnose any crashes in the agent itself.

**Comment by jtpetty** [comment]
This was released in agent 2.146.6
