### ISSUE TITLE
Elastic Self-hosted Agent Pools

### ISSUE THREAD

**Issue by btl5037** [microsoft/azure-pipelines-agent#2677]
This is a game changing feature for us (Hyperledger org in AZP).
We run nearly 20 projects in AZP and we have several issues today with the size of nodes, in particular hitting timeouts when compiling code in tests (causes dozens of flakes a day where our only remedy is to extend timeouts and increase test runtime). Being able to deploy nodes where we can choose the size (and throw them away after each run) would be something we are extremely interested in and can't wait to beta test this.
Just throwing our name in the hat as a feature we are greatly interested in.

**Comment by vijayma** [comment]
Noted. Thanks.
