### ISSUE TITLE
Linux self-hosted - Container jobs - Pipelines build error

### ISSUE THREAD

**Issue by Fizcko** [microsoft/azure-pipelines-agent#2678]
Hi,

I'm trying to run container jobs on self-hosted Linux agent but i have an error :

```
##[debug]Evaluating condition for step: 'Initialize containers'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Initialize containers
##[error]Nullable object must have a value.
##[debug]System.InvalidOperationException: Nullable object must have a value.
   at Agent.Sdk.PlatformUtil.get_RunningOnRHEL6()
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[section]Finishing: Initialize containers
```
## Pipeline file
```
name: $(Build.BuildID)
jobs:
- job: One
  pool: Docker
  container: ubuntu:16.04
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'hostname'
```

## Current settings :

Agent Host : Centos 7
```
cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
```

Agent version : Linux x64 2.162.0

Azure DevOps Server (On premise)  : 2019.1

## Possible fix
By analysing the code in https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Util/PlatformUtil.cs the function DetectRHEL6() do not set detectedRHEL6 to false if the file "/etc/redhat-release" do not contains "CentOS release 6." or "Red Hat Enterprise Linux Server release 6.". This is may be the cause of the problem.

**Comment by Fizcko** [comment]
I've just try to rename the file "/etc/redhat-release" to ""/etc/redhat-release.old" the job now start without error.

So my diagnostic seem to be good, the is a problem in the function DetectRHEL6().

Is it possible to fix it on the next release ?

Thanks a lot.

regards

**Comment by jtpetty** [comment]
@Fizcko - Thanks for the assist in triaging this issue. I have pushed a PR to fix it.

**Comment by Fizcko** [comment]
@jtpetty Thanks !
