### ISSUE TITLE
YAML pipeline demands agent version that does not exist

### ISSUE THREAD

**Issue by JoeGaggler** [microsoft/azure-pipelines-agent#2686]
## Agent Version and Platform
Version of your agent? 2.160.1

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com/Emdat

## What's not working?
YAML pipeline is demanding a version of the agent that is not yet available in our organization:

<img width="437" alt="ticket-no-agent-version" src="https://user-images.githubusercontent.com/27233871/71034398-fb598d00-20de-11ea-9e75-1d143bd76b56.png">

Forcing an upgrade via the Azure DevOps Agent Pools screen only updates to 2.160.1.

The pipeline we are trying to run was previously working yesterday, and has not been altered since.

## Agent and Worker's Diagnostic Logs
There are no logs because the agent does not even start. No additional information is shown when diagnostics are turned on for a subsequent run.

**Comment by packersking** [comment]
we are seeing the same issue
https://dev.azure.com/msi-cie/

**Comment by Sayshu** [comment]
Same here

**Comment by huahua82** [comment]
Same here

**Comment by johncrim** [comment]
I'm seeing the same, but using Ubuntu 16.04 build agent in the US. The agent version is 2.160.1. This exact build worked as expected yesterday. I hope this is P0, as I imagine it's blocking a lot of development teams using Azure DevOps.

**Comment by pipes592** [comment]
Yep same here

**Comment by yossarian123** [comment]
bump, same

**Comment by StandBackBurrito** [comment]
same issue seen here

**Comment by PaulVrugt** [comment]
This is making our builds fail, our pipelines have come to a screaming halt. Please fix this asap!

**Comment by LtDrak** [comment]
We can't build anything anymore. We have already wasted 2 hours today with 10+ people not being able to work. Fix is needed as soon as possible.

**Comment by svanuden** [comment]
Same problem here, no successful runs after yesterday.

**Comment by MichaelKoster70** [comment]
Same here. The temporary solution posted in[developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/content/problem/859606/build-pipeline-failing-no-agent-found-in-pool-azur.html) worked in my case.

**Comment by mhedbergge** [comment]
We also have this issue since yesterday. Truly annoying :(
Is this something we should expect - that our pipelines suddenly stops running?

**Comment by grhm** [comment]
This appears to be an issue with the `DownloadPipelineArtifact@2` task.
A workaround is to try altering your yaml to use `DownloadPipelineArtifact@1`

**Comment by nor0x** [comment]
@grhm @MichaelKoster70 thanks for the workaround. It's a temporary solution which works fine in my case

**Comment by packersking** [comment]
testing this morning, the issue appears to be resolved. the [developer community](https://developercommunity.visualstudio.com/content/problem/859606/build-pipeline-failing-no-agent-found-in-pool-azur.html) page is marked as closed

**Comment by stephenmichaelf** [comment]
I apologize for the issue, the fix has been rolled out and things should be resolved now.

We ran into issues when rolling out our Agent and because of that a task was able to deploy ahead of the Agent version it required, thus the inability to get an Agent with the version the task needed. We are working on our internal deployment processes to make sure this doesn't happen again.

**Comment by johncrim** [comment]
@stephenmichaelf : Please consider improving the error message, so it is easier to diagnose problems like this next time. Something like the following would be much more useful:

```
##[error]No agent found in pool Azure Pipelines which satisfies the specified demands:
     Agent.Version -gtVersion 2.161.0 - required by DownloadPipelineArtifact@2
```

Next, there is nothing in the build logs for this error, even when Diagnostic mode is turned on. So adding this info to the build logs is also needed.

All this should be done in addition to the "why did it happen/how can we prevent it" analysis. This type of blocking issue is a huge problem to the businesses that have bet on Azure DevOps.

**Comment by stephenmichaelf** [comment]
@johncrim Thanks for the feedback! I will create an internal ticket to improve the error message.

I agree this was an unfortunate issue and we have made changes to our internal processes to prevent it from happening again.
