### ISSUE TITLE
Feedback on BYOS

### ISSUE THREAD

**Issue by chevonc** [microsoft/azure-pipelines-agent#2693]
#design
#enhancement

I think elastic pools will really move azur devops ahead in CI world by leaps and bounds. We currently have a haphazardly configured "dynamic pool" of machines using azure vm scale sets + auto scaling parameters. However, one issue with our setup due to the lack of integration back into azure dev ops is when azure scales down the VMs and machines are deallocated, azure dev ops leaves behind the agents 

![image](https://user-images.githubusercontent.com/684657/71280939-7efac000-2311-11ea-8981-a0f19bdda353.png)

I saw the initial designs and they look amazing, wondering if we can ensure this clean up step happens? 

Another quick questions, any ETA/update on when [BYOS](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/byos.md) will be available? We're starting to look into other solutions due to these limitations

**Comment by btl5037** [comment]
I would also like to know if and when AZP plans to deliver BYOS, the limited size of the available disposable VM's is a very limiting factor. We have had to change a lot of how we work (doing testing in parallel), simply because the VM's aren't powerful enough to handle the tests.

**Comment by vijayma** [comment]
This work is ongoing, and we expect to have an initial version by the end of this quarter. @chevonc , we will keep the list of agents clean on the agent pool UI. One way to do that is by treating those as slots (instead of real agents) just like we do for hosted pools. We have not finalized the design for that part yet, but the requirement is clear.

**Comment by damccorm** [comment]
Hey, thanks for the feedback - we're tracking this internally and it should be coming soon. I'm going to close here since the feedback has been propogated internally.

**Comment by vijayma** [comment]
@btl5037, @chevonc Can you let us know the name(s) of Azure DevOps org(s) where you would like to preview this feature?

**Comment by btl5037** [comment]
@vijayma The Hyperledger org would love to test the BYOS functionality. You can reach me out of band at brett.t.logan@ibm.com if necessary

**Comment by MarcDenman** [comment]
@vijayma Is there any chance we could get in on the preview as well? We are moving to VMSS from Azure VMs and this could save us a lot of work.

**Comment by vijayma** [comment]
Sure. Send me a note to vijayma_at_microsoft_dot_com with the name of your Azure DevOps organization, and we will enable the preview for you.

**Comment by MarcDenman** [comment]
> Sure. Send me a note to vijayma_at_microsoft_dot_com with the name of your Azure DevOps organization, and we will enable the preview for you.

Emailed, thank you :)
