### ISSUE TITLE
./config.sh: Error: Unable to find a match: libopenssl (Fedora 30)

### ISSUE THREAD

**Issue by arcotek-ltd** [microsoft/azure-pipelines-agent#2695]
## Agent Version and Platform
vsts-agent-linux-x64-2.163.1.tar.gz

OS of the machine running the agent? 
Fedora Server 30

## Azure DevOps Type and Version
dev.azure.com 

If dev.azure.com, what is your organization name? Private

## What's not working?
When attempting to configure agent, using `./config.sh` I receive the error:
```
No match for argument: libopenssl
Error: Unable to find a match: libopenssl
```
This is after entering the PAT.

You say Fedora 30 is supported, but it would appear there is a library missing from the prerequisites script. From the resolution of #2454, in #2616, it looks like the prerequisits installs .NET core, but I guess it's the wrong version?
## Agent and Worker's Diagnostic Logs
N/A. Agent not configured yet.

**Comment by arcotek-ltd** [comment]
Having had a look at `bin/installdependencies.sh`, I noticed you classify Fedora under RHEL. I have downloaded and run `config.sh` against the RHEL version and this time, after PAT entry I get:
```
No usable version of the libssl was found
```

It looks like there is something still missing.

**Comment by arcotek-ltd** [comment]
I resolved it, by installing .[NET Core SDK](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-fedora30#install-the-net-core-sdk) 2.1 manually, following: https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-fedora30, changing the version to `2.1`.

Although this has resolved my issue, I think something needs to be fixed, probably in `installdependencies.sh`

**Comment by arcotek-ltd** [comment]
Also works with .NET Core runtime 2.1:
```
rpm --import https://packages.microsoft.com/keys/microsoft.asc 
wget -q -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/fedora/31/prod.repo
dnf install dotnet-runtime-2.1 -y
```
Installed .NET using root.

**Comment by jtpetty** [comment]
@mjroghelia - We should check on this and see what needs to be adjusted now that we are using .NET Core 3.1

@vtbassmatt - Did you recently update this with your investigation of the ARM64 work?

**Comment by vtbassmatt** [comment]
@jtpetty no changes other than making it non-fatal to be missing libcurl (since we will hopefully remove that dependency soon). I noticed that the install prereqs stuff no longer seems to work with Debian 10, so it would not surprise me if a newer Fedora didn't work either.

.NET used to have pretty decent documentation about their runtime dependencies. The list is now a set of specific packages only for one version of Ubuntu along with a note that "package names may differ on different versions". I'm not sure how we resolve this in a bigger sense.
