### ISSUE TITLE
TF400813: Resource not available for anonymous access

### ISSUE THREAD

**Issue by Arenoros** [microsoft/azure-pipelines-agent#2704]
Agent v2.164.0
Log: [Agent_20200101-215536-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/4014573/Agent_20200101-215536-utc.log)

TFS version: 17.153.29522.3 (AzureDevOps2019.Update1.1)

I tried enable all type auth in iis
![IIS Auth](https://user-images.githubusercontent.com/2578918/71646556-8354af00-2cfb-11ea-85e3-8a645b2252e0.png)

I looked at all the links that I found in Google:  #1500 #2214 #1839 #759 #2565

What am I doing wrong?

**Comment by cliftonz1** [comment]
I am having the exact same issue. If I use negotiate and pass in a username and password the agent installs correctly however if I use a pat it gives: 
```txt
TF400813: Resource not available for anonymous access. Client authentication required.
```

**Comment by alexanderwieland** [comment]
https://developercommunity.visualstudio.com/solutions/802663/view.html
Use "https://[servername]/[organizationname]"

**Comment by sobjornstad** [comment]
@alexanderwieland's solution worked. Bizarre that it works without the collection/org name on a Negotiate but not with a PAT...and that there's no obvious documentation of this.

**Comment by Arenoros** [comment]
> https://developercommunity.visualstudio.com/solutions/802663/view.html
> Use "https://[servername]/[organizationname]"
@alexanderwieland,
OMG!! It's work, many thanks!

**Comment by robertmuehsig** [comment]
I had the same issue with an OnPrem Azure DevOps Server 2019 Update 1 and tried different things, but my college finally noticed, that the UI was missing an important [part](https://stackoverflow.com/questions/59302537/cant-see-generated-pat-on-azure-devops-server-2019-after-installing-december-20).

The fix: Our Azure DevOps Service account needed __write__ permissions on this directory: 

    C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys

**Comment by chrismcclure** [comment]
@alexanderwieland  What a life saver. Great answer!
