### ISSUE TITLE
System.ArtifactsDirectory is not cleared if "Artifact download" is set to "None"

### ISSUE THREAD

**Issue by avivanoff** [microsoft/azure-pipelines-agent#2711]
## Agent Version and Platform
Version of your agent? 2.163.1

## OS of the machine running the agent?
Windows Server 2019

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

## What's not working?
Because of limitations in release pipelines "Artifact download" (it does not allow partial download of artifacts), we set "Artifact download"  to "None" and use "Download build artifacts" task instead. In such configuration, System.ArtifactsDirectory is never cleaned before the deployment.

**Comment by jtpetty** [comment]
@jahsu-MSFT - Is this something you can look at?

**Comment by jahsu-MSFT** [comment]
Since it's build artifacts, I think the right team to look at this issue is Leah's team. @leantk Could you please look into this issue or assign to a right person on the team to look into it?

Thanks,

**Comment by avivanoff** [comment]
@jahsu-MSFT, @leantk, do you have any updates on this issue?

**Comment by avivanoff** [comment]
@leantk, it has been more than 6 months, please provide updates.

**Comment by leantk** [comment]
@avivanoff we don't have the bandwidth to make this update at this time. I would say we could circle back to this in a couple months to see if we have time then. If this is critical to your needs, the tasks are open sourced in the below repo and we welcome contributions from anyone so please feel encouraged to create a PR with the fix if you want
https://github.com/microsoft/azure-pipelines-tasks

**Comment by avivanoff** [comment]
@leantk, why did you close this issue? Please re-open it.

**Comment by leantk** [comment]
Sorry it got tagged Stale and the automated bot closed it

**Comment by tatyana-kostromskaya** [comment]
@avivanoff Changes with new input option, that allow to clean up destination folder before artifacts download, were merged.
This change will be available next sprint.

I'll update the issue when changes are deployed.

**Comment by tatyana-kostromskaya** [comment]
Task version with this update was deployed.
