### ISSUE TITLE
A triggered build in Azure Devops Server takes approx one minute to connect to the build agent before the build task starts

### ISSUE THREAD

**Issue by RealdolmenBizDevOps** [microsoft/azure-pipelines-agent#2716]
**Issue:** 
Some weeks ago we upgraded our Azure Devops Server environment to version 2019 update 1.1
Since the upgrade we experience weird behavior with some specific agents. It takes one minute to connect to a build agent, when the job is executed on another agent then the previous job execution or when the previous job execution ran more then approx 5 minutes before.
When running a job continuously on the same agent, shortly after each other (say within a minute of the previous run), this issue does not occur.

We've updated to the latest version of the build agent without avail. When returning to the agent version (2.141.1) used before the upgrade the issue did not appear.

Following can be found in the build agent log after triggering a build:
_[2019-12-10 15:27:09Z WARN VisualStudioServices] PATCH request to https://[server]/tfs/_apis/distributedtask/pools/41/jobrequests/141004?lockToken=00000000-0000-0000-0000-000000000000 timed out after 60 seconds.
[2019-12-10 15:27:09Z ERR  JobDispatcher] Catch exception during renew agent jobrequest 141004.
[2019-12-10 15:27:09Z ERR  JobDispatcher] System.TimeoutException: The HTTP request timed out after 00:01:00. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled._

After that a new connection is made, the next jobs are started immediatly (detailed log: 
[log.txt](https://github.com/microsoft/azure-pipelines-agent/files/4040111/log.txt)
)

The Azure devops Server is on a hosted VM, which is domain joined. The Azure Devops Agents, are on a seperate Azure subscription and not domain joined. (not possible). These agents are on a hosted linux VM (Ubuntu 16.04). 
Connection is allowed via Azure Firewall. The NSG allows the public IP of the firewall (see visualization in attachment)
![infra](https://user-images.githubusercontent.com/59688716/72063796-c81fad80-32da-11ea-82c8-66faa6d661bc.png)

**Other information**
- The agent on the Linux machine runs as a local user. Authentication to Azure Devops Server is done using basic credentials.
- No proxy is being used.
- Checked the known issues, nothing seems to be relevant.
- When removing the azure firewall, and go directly over the internet, the issue can not be reproduced and everything works fine (this is not a desired solution!)
- Testing with the latest version of the agent results in the same issue.

**Extra information:**
- Azure devops Server environment
Version: 17.153.29522.3 (Azure Devops2019.Update1.1)
OS: Windows Server 2012 R2

- Build agents
Version: 2.153.2
OS: Ubuntu 16.04

**Comment by jtpetty** [comment]
I have been doing some investigation and have a theory:

Previously, all communication with the server was done over a single connection.

The agent was updated to use separate connections for listening for messages from the server and for job renew request (job heartbeat). The message connection is constantly active as we are constantly long polling the server for new messages. The job renew request is only active during the running. of a job. Between jobs, this connection is idle. Your logs are only seeing problems on this connection.  

My theory is that if the firewall is aggressive (short time-to-live) on idle connections, the firewall could be closing the connection. When the agent gets a new job message (on the message connection), it tries to communicate on the job renew request connection, the firewall has closed the connection, so we timeout after 60 seconds, and then we forcibly recreate the connection and everything works smoothly again until the next long delay between jobs.

So, one way to verify this is to see if there is a setting on the firewall regarding how long to wait before closing idle connections. If we can increase that and see an improved performance, this would validate this theory.

We could also update the agent to forcibly refresh the job renew request connection at the start of a new job. I am not sure what the performance ramifications are for that. We could also do that only if some amount of time has passed between jobs, but we would need to know what that time span should be.
