### ISSUE TITLE
dotnet-install.sh does not show any progress while SDK downloading in some cases

### ISSUE THREAD

**Issue by sergeyg-earnin** [microsoft/azure-pipelines-agent#2730]
It might confuse users with slow connection. I think the reason is [silent mode (`-s`) enabled in `curl` command](https://github.com/microsoft/azure-pipelines-agent/blob/1a7a551e625959f8dc99470326a392e4ea9de317/src/Misc/dotnet-install.sh#L733). Note progress is shown if the script [uses wget to download SDK](https://github.com/microsoft/azure-pipelines-agent/blob/1a7a551e625959f8dc99470326a392e4ea9de317/src/Misc/dotnet-install.sh#L754)

**Comment by jtpetty** [comment]
@sergeyg-earnin - this dotnet-install.sh in our repo is just an exact local copy of what is published by the dotnet team. You would need to file an issue with that project.
