### ISSUE TITLE
self hosted linux agent 2.164.1/3 stopped running jobs

### ISSUE THREAD

**Issue by dvescovi1** [microsoft/azure-pipelines-agent#2734]
## Agent Version and Platform
Version of your agent?
2,164.1/3 Ubuntu18.04

## Azure DevOps Type and Version
on premise not sure how to get version 

If dev.azure.com, what is your organization name? 
https://dev.azure.com/jblhive/

## What's not working?
I had agent 2.164.1 installed and working on two Azure hosted Ubuntu 18.04 vm's. in my againt pool.
This was working and it was running several pipeline jobs right along.
Not sure what happened but now jobs are just waiting in que and never run.
Status of pending jobs say:
"The agent request is not running because all potential agents are running other requests. Current position in queue:1"
If I look at the pipeline agent pool status shows:
The agent "online", "Idle" and "enabled"

It also looks like 2.164.3 may have been pushed and may be the issue I can not tell.
It tried reinstalling the agent but still no luck. Agent logs show some errors.

[Agent_20200117-143327-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/4077664/Agent_20200117-143327-utc.log)
## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

[Agent_20200117-144037-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/4077665/Agent_20200117-144037-utc.log)

**Comment by dvescovi1** [comment]
more info:
david@Ubuntu1804b:~/azp/agent$ sudo ./svc.sh status

/etc/systemd/system/vsts.agent.jblhive.WASP_BUILD_POOL.waspbuilder\x2db.service
● vsts.agent.jblhive.WASP_BUILD_POOL.waspbuilder\x2db.service - Azure Pipelines Agent (jblhive.WASP_BUILD_POOL.waspbuilder-b)
   Loaded: loaded (/etc/systemd/system/vsts.agent.jblhive.WASP_BUILD_POOL.waspbuilder\x2db.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-01-17 14:33:27 UTC; 45min ago
 Main PID: 7654 (runsvc.sh)
    Tasks: 17 (limit: 9513)
   CGroup: /system.slice/vsts.agent.jblhive.WASP_BUILD_POOL.waspbuilder\x2db.service
           ├─7654 /bin/bash /home/david/azp/agent/runsvc.sh
           ├─7664 ./externals/node/bin/node ./bin/AgentService.js
           └─8636 /home/david/azp/agent/bin/Agent.Listener run --startuptype service

Jan 17 14:40:35 Ubuntu1804b runsvc.sh[7654]: Error reported in diagnostic logs. Please examine the log for more details.
Jan 17 14:40:35 Ubuntu1804b runsvc.sh[7654]:     - /home/david/azp/agent/_diag/Agent_20200117-143327-utc.log
Jan 17 14:40:35 Ubuntu1804b runsvc.sh[7654]: An error occurred: Access to the path '/home/david/azp/agent/env.sh' is denied.
Jan 17 14:40:35 Ubuntu1804b runsvc.sh[7654]: Agent listener exited with error code 2
Jan 17 14:40:35 Ubuntu1804b runsvc.sh[7654]: Agent listener exit with retryable error, re-launch agent in 5 seconds.
Jan 17 14:40:37 Ubuntu1804b runsvc.sh[7654]: Starting Agent listener with startup type: service
Jan 17 14:40:37 Ubuntu1804b runsvc.sh[7654]: Started listener process
Jan 17 14:40:38 Ubuntu1804b runsvc.sh[7654]: Scanning for tool capabilities.
Jan 17 14:40:38 Ubuntu1804b runsvc.sh[7654]: Connecting to the server.
Jan 17 14:40:40 Ubuntu1804b runsvc.sh[7654]: 2020-01-17 14:40:40Z: Listening for Jobs
david@Ubuntu1804b:~/azp/agent$ 
P

**Comment by dvescovi1** [comment]
It looks like an update may be the cause as I see this in the directory:
bin bin.2.164.3 externals externals.2.164.3  

I do not remember seeing these when it was working.

**Comment by jtpetty** [comment]
@dvescovi1 - it looks like there was a problem during the auto update. I see this in the log:

```
[2020-01-17 14:40:32Z ERR  AgentProcess] System.UnauthorizedAccessException: Access to the path '/home/david/azp/agent/env.sh' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)
```

It seems that the permissions on this file is such that the running agent process was not able to remove it.

**Comment by dvescovi1** [comment]
I thought something along those lines. 
For what ever reason it seems to want to install 2.164.3

**Comment by jtpetty** [comment]
We are rolling out that version of the agent, so it makes sense that the agent would attempt to self update. The issue is the permissions on the env.sh file. There is an assumption that the user the agent is running as owns and has write permission to all of the files in the agent install directory.

**Comment by jtpetty** [comment]
@dvescovi1 - Can I ask, what were the permissions on that /home/david/azp/agent/env.sh? We should update the agent to not completely crash in this instance. Did you just remove write permission or was it owned by a different users?

**Comment by dvescovi1** [comment]
I finally got it running by brute force. I deleted all the agent stuff on all the clients in the pool, deleted and recreated the pool. then reinstalled all the agents with 2.164.3 and that seems to fixed everything. not pretty.

**Comment by dvescovi1** [comment]
seems to have happened again with the 2.164.6 update.
Appears every time there is an update pushed it stops working.
All the same symptoms.
when I do the service status it does show a permission error on env.sh
Again I had to brute force uninstall, clean and reinstall with 2.163.6 to get going again.
This is a critical build machine so I did not have much time to trouble shoot.

**Comment by jtpetty** [comment]
@dvescovi1 - If the env.sh is write protected by the owner or if it is owned by another user other than the user the agent is running as, this situation will occur. What are the permissions on this file?

**Comment by dvescovi1** [comment]
I no longer have the state of the file when the error occurred as I had to rebuild the agent to get the build host back up. I can tell you this as it should be easy to reproduce.:
I used a standard Ubuntu18.04 VM created with my Azure subscription. I installed the agent using:
https://raw.githubusercontent.com/MicrosoftDocs/mslearn-azure-pipelines-build-agent/master/build-agent.sh script. Using instructions here https://docs.microsoft.com/en-us/learn/modules/host-build-agent/
I created a PAT from my DevOps user account and used it in an environment variable as instructed.
The only deviation was I set PAT scope to "full access" instead of "Read and Manage" Agent Pools could this be the problem? I seem to recall I had issues with "Read and Manage". Anyway "full access" seemed to work as it registered with DevOps" and everything ran ok.

**Comment by jtpetty** [comment]
Are you able to log on the machine now and do a 'ls -l' in the directory where you installed the agent?  This issue has nothing to do with the PAT scope.

**Comment by dvescovi1** [comment]
this is the status of a "working" install. the script installed it in ~/azp/agent  directory.
david@Ubuntu1804b:~/azp/agent$ ls -l
total 52
drwxr-xr-x  3 david david  4096 Feb  4 16:23 _diag
drwxrwxrwx 27 root  root   4096 Jan 27 04:29 _work
drwxr-xr-x 22  1001   117 20480 Jan 26 22:37 bin
-rwxr-xr-x  1  1001   117  2940 Jan 23 02:33 config.sh
-rwxr-xr-x  1  1001   117   707 Jan 23 02:33 env.sh
drwxr-xr-x  6  1001   117  4096 Jan 23 02:34 externals
-rwxr-xr-x  1  1001   117  2014 Jan 23 02:33 run.sh
-rwxr-xr-x  1 david david   510 Jan 26 22:37 runsvc.sh
-rwxr-xr-x  1 david david  4070 Jan 26 22:37 svc.sh
david@Ubuntu1804b:~/azp/agent$

I noticed that after it tried to upgrade (and stopped working) there were several other folders. I don't have that status as I wiped and reinstall to get back on line.  If it fails again I will recheck status of those.

**Comment by dvescovi1** [comment]
did it again this morning.
 Broken upgrade and build machine down again.

the directory now looks like:
david@Ubuntu1804b:~/azp/agent$ dir
_diag  _work  bin  bin.2.164.7  config.sh  env.sh  externals  externals.2.164.7  run.sh  runsvc.sh  svc.sh
david@Ubuntu1804b:~/azp/agent$
david@Ubuntu1804b:~/azp/agent$ ls -l
total 76
drwxr-xr-x  3 david david  4096 Feb  5 14:11 _diag
drwxrwxrwx 27 root  root   4096 Feb  5 14:11 _work
drwxr-xr-x 22  1001   117 20480 Jan 26 22:37 bin
drwxr-xr-x 22 david david 20480 Feb  5 14:11 bin.2.164.7
-rwxr-xr-x  1  1001   117  2940 Jan 23 02:33 config.sh
-rwxr-xr-x  1  1001   117   707 Jan 23 02:33 env.sh
drwxr-xr-x  6  1001   117  4096 Jan 23 02:34 externals
drwxr-xr-x  6 david david  4096 Feb  5 14:11 externals.2.164.7
-rwxr-xr-x  1  1001   117  2014 Jan 23 02:33 run.sh
-rwxr-xr-x  1 david david   510 Jan 26 22:37 runsvc.sh
-rwxr-xr-x  1 david david  4070 Jan 26 22:37 svc.sh
david@Ubuntu1804b:~/azp/agent$

**Comment by dvescovi1** [comment]
attached console dump showing ls -l
[broken agent upgrade.txt](https://github.com/microsoft/azure-pipelines-agent/files/4159976/broken.agent.upgrade.txt)

**Comment by dvescovi1** [comment]
is there a way to turn off upgrades?

**Comment by dvescovi1** [comment]
PLEASE tell me how to fix this. Its becoming very problematic!

**Comment by jtpetty** [comment]
@dvesccovi1 - The issues is that some of the directories and files in your agent install directory are owned by mid 1001 but you are running the agent as user 'david'.

If you run the following command:
```
% chown -R david:david /azp/agent
```
That should fix your problem and prevent it from happening again.

We currently do not have a method for disabling auto updates.

**Comment by dvescovi1** [comment]
I'll give it a try … thanks for the quick reply

**Comment by jtpetty** [comment]
@dvescovi1 - you may need to do

```
% sudo  chown -R david:david /azp/agent
```

Since I just noticed your _work directory is owned by root.

**Comment by dvescovi1** [comment]
yes the _work directory is mapped to a large storage drive on Azure as I am building a large yocto image which consumes a large amount of space, I am also storing some saved download and state files there needed for yocto builds  Is that going to be a problem?

**Comment by dvescovi1** [comment]
the standard Linux vm allocated on Azure does not have a big enough drive so I had to mount an extra 2TB drive to _work mount point

**Comment by jtpetty** [comment]
Then I would do the following:

```
% chown david:david /azp/agent/*.sh
% chown -R david:david /azp/agent/bin
% chown -R david:david /azp/agent/externals
```

**Comment by dvescovi1** [comment]
looks like the original install script I used put the agent in my home directory /home/david/azp …should it be off the root?

**Comment by jtpetty** [comment]
it can be wherever, but all the files need to be owned by the user the agent is being run as.

**Comment by dvescovi1** [comment]
look like queued jobs are now running!

**Comment by dvescovi1** [comment]
is there a command I can use to dump version number and status that is running?

**Comment by IvanDonoso** [comment]
hello, the last hint didn't work for me, on ubuntu 20.04, it seems to be a permissions issue because i removed the validation from the user in config.sh and run sh script and run the scripts with sudo ./config.sh and sudo ./run.sh and it worked. now i will investigate what is happening what is the missing permission.
`# we want to snapshot the environment of the config user

if [ $user_id -eq 0 -a -z "$RUNNER_ALLOW_RUNASROOT" ]; then
    echo "Must not run with sudo"
    exit 1
fi
`

**Comment by IvanDonoso** [comment]
> > hello, the last hint didn't work for me, on ubuntu 20.04, it seems to be a permissions issue because i removed the validation from the user in config.sh and run sh script and run the scripts with sudo ./config.sh and sudo ./run.sh and it worked. now i will investigate what is happening what is the missing permission. `# we want to snapshot the environment of the config user
> > if [ $user_id -eq 0 -a -z "$RUNNER_ALLOW_RUNASROOT" ]; then echo "Must not run with sudo" exit 1 fi `
> 
> @IvanDonoso did you ever determine the source of this error? I am hitting the same thing though it seems to me that all agent-related files are owned by the correct user.

hi jweyer8
I did not find the origin, but something that worked for me was to delete everything and reinstall the runner with this link
https://docs.github.com/actions/hosting-your-own-runners/adding-self-hosted-runners#adding-a-self-hosted-runner-to-a-repository
