### ISSUE TITLE
Docker Image Size differs on local compared to the one on Agent

### ISSUE THREAD

**Issue by nreddipalle** [microsoft/azure-pipelines-agent#2736]
I am trying to build a docker image using https://hub.docker.com/_/microsoft-dotnet-framework-aspnet/ image.. when pulling it locally (windows 10 laptop) it is showing the size as 5.58GB
![image](https://user-images.githubusercontent.com/28302399/72748485-663a3000-3b85-11ea-9fe7-459674a6acb5.png)

whereas the same image is showing as 14.6GB on self-hosted devops agent (Windows Server 2016) after pulling... 

![image](https://user-images.githubusercontent.com/28302399/72748960-b1087780-3b86-11ea-8697-7bba2c7d2bca.png)

Has anyone faced a similar issue?. Thanks

**Comment by jtpetty** [comment]
@nreddipalle - The image ids do not appear to match between the two tags of your images. I think you are comparing two different things.

**Comment by jtpetty** [comment]
I am closing this as I do not think it is an agent issue. If you continue to have problems, please feel free to open a new issue
