### ISSUE TITLE
YAML Validation  ./run.sh --yaml <PATH> --whatif failing

### ISSUE THREAD

**Issue by Nirav-Bhadradiya** [microsoft/azure-pipelines-agent#2740]
While trying to run  **./run.sh --yaml <PATH> --whatif** to validate YAML file it fails with **"~/src/Misc/layoutroot/bin/Agent.Listener: No such file or directory"**

I tried building project with ./dev.sh build still no luck.

**Comment by vtbassmatt** [comment]
Hi @Nirav-Bhadradiya - the --yaml and --whatif flags were experiments that we abandoned over 2 years ago, and just failed to remove from the code. I'm sorry for surprising you with their removal. They never functioned properly in the first place - could you share what you were using their output for?

Also note that we have a server-side version of "what if" coming very shortly. It's based on the exact same code that parses YAML definitions today, so it's going to have a much better shot at accurately transforming a YAML file.

**Comment by Nirav-Bhadradiya** [comment]
Hi @vtbassmatt I  was trying to validate yaml before i ran against it build just to make sure it does not just throw me validation errors. do you have any other way to validate yamls before we ran it from pipeline ?

**Comment by vtbassmatt** [comment]
You can get partial validation using this [VS Code extension](https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines). It doesn't understand the template syntax unfortunately, but will help for other syntax.
