### ISSUE TITLE
Containerized agents immediately self terminate on signal from cluster

### ISSUE THREAD

**Issue by EPinci** [microsoft/azure-pipelines-agent#2745]
## Agent Version and Platform
Version of your agent? latest

OS of the machine running the agent? Linux Container on AKS

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

## What's not working?
We have built the agents container according to https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops
We then bundled a number of this in an AKS kubernetes statefulset that has a “terminationGracePeriodSeconds: 900”.

Now agents handle on their own agent updates but we’re facing issue when updating the container’s images (e.g.: on new builds of the image).
In that case we reset the image of the manifest specs causing a redeployment of the pods (ordered by the statefulset).
When we do that, Kubernetes signals the pod the impending shutdown and our expectations where that the pods would try finish the current job up to the above terminationGracePeriodSeconds but, instead, we can see that the agent software receives the Kubernetes signal and immediately truncates the current job and self terminates.

What are we missing in order for the agents to try to complete the running jobs before self-terminating?

**Comment by vtbassmatt** [comment]
Thanks for raising this issue. It's a good scenario and one we want to have better support for.

A few questions from our end:
1. Is [run-once mode](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#run-once) acceptable for your scenarios? In that case, the agent process will only run one job and then terminate itself. I know in something like ACI, this would cause a new instance of the container to come up. I'm not very familiar with K8s and its semantics, so don't know if this would be a good practice.
2. Can you share the logs from an instance where this happened? We want to double-check exactly what signal gets sent (I'm assuming `SIGINT`, but perhaps not?).

**Comment by hbuckle** [comment]
I'm investigating running agents on AKS as well and have been thinking about how to handle this - I'm planning to run the agents with run-once mode, but still want to ensure they don't get terminated mid job (due to cluster upgrade or similar). Is there any way to query the agent to find out if it is currently running a job? Then something like a pre-stop hook could be used to block termination until the job completes

**Comment by vtbassmatt** [comment]
@casey-robertson I could have sworn there was another issue more related to the behavior you're describing, but now I can't find it. What can a container/process do to indicate to Kubernetes that it's shutting down on purpose, not due to failure?

**Comment by ericrdgz** [comment]
We are facing this same exact issue. We would like to use the run-once mode but for jobs execute in super fast fashion, Kubernetes treats these pods as "crashing" and starts doing exponential crash loop backoff.

**Comment by Abdulthetechguy** [comment]
> We are facing this same exact issue. We would like to use the run-once mode but for jobs execute in super fast fashion, Kubernetes treats these pods as "crashing" and starts doing exponential crash loop backoff.

Did you by any chance find a solution to this? I am facing the same issue too.

**Comment by Abdulthetechguy** [comment]
> We are having some of our own issues running agents in Kubernetes (EKS in our case). We are using the RunOnce model. The problem is that Kubernetes sees these a broken pods because they are shutting down when the job finishes. If it does this over "x" threshold, Kubernetes puts the pod in a CrashLoopBackoff state and doesn't reschedule it for 5 minutes. This is causing backups in our pipelines.

Did you by any chance find a solution to this? I am facing the same issue too.

**Comment by milanmayr** [comment]
I have the exact same issue. Would love to find a workaround or a fix for this.
