### ISSUE TITLE
BYOS Feedback

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/azure-pipelines-agent#2746]
I wanted to submit some additional feedback regarding the [BYOS design doc](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/byos.md).

I make heavy use of a self-hosted build agent in order to utilize MSI, so I can skip having to use and update the various DevOps connections for deployments. Rather, it's far easier to just use a system-assigned identity to restrict access to Azure resources as necessary. Given that VMSSes support identity integration, this would be a big draw towards elastic build pools for me.

**Comment by damccorm** [comment]
Hey, thanks for the feedback - we're tracking this internally and it should be coming soon. I'm going to close here since the feedback has been propogated internally.

**Comment by vijayma** [comment]
@WhitWaldo can you let us know the name(s) of Azure DevOps org(s) where you would like to preview this feature?
