### ISSUE TITLE
Invalid executable path error- for git version cmd on RAM Disk

### ISSUE THREAD

**Issue by VenumadhavDuriseti** [microsoft/azure-pipelines-agent#2747]
## Agent Version and Platform
Version of your agent? 2.169.2/2.164.6

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) 

If dev.azure.com, what is your organization name? https://dev.azure.com/onebranch or https://onebranch.visualstudio.com

## What's not working?
I set up RAM Disk drive (X:) on my machine, using imdisk (and osfmount etc) and downloaded the agent binaries from [2.164.6](https://vstsagentpackage.azureedge.net/agent/2.164.6/vsts-agent-win-x64-2.164.6.zip) and tried running git version, it fails saying "Invalid executable path" 

![image](https://user-images.githubusercontent.com/9970018/73028752-06dd5980-3deb-11ea-9ba8-c0f7a18a9de0.png)

## Background info
I'm trying to run the vsts agent in ram disk present on the agent machine - for performance, and seems like the build is failing in source code check out stage itself. With the following code logs below. So I went ahead to test it locally to see if I can reproduce the issue. 

On my machine, I created RAM Disk drive (using Imdisk and also tried osfmount), extracted the vstsgent binaries on it, and ran the cmd git version. It throws the same error.

## What I tried:
I created a VM and remote'd into it with my current computer's drives mapped (including the RAM Disk drive), and then from the VM, I invoked cmd: git version - on the mapped RAM Disk drive (where the vstsagent + git binaries are present), and it works. It doesnt work when I directly execute git version cmd locally on the ram disk..

![image](https://user-images.githubusercontent.com/9970018/73028468-7272f700-3dea-11ea-9f81-b44b43da1672.png)

This path: \\tsclient\X\vsts-agent-win-x64-2.164.6\externals\git is the mapped RAM Disk drive (X:) into the VM.

## Agent and Worker's Diagnostic Logs
##[debug]Get git version.
##[command]git version
##[debug]Starting process:
##[debug]  File name: 'X:\_work\b\1\externals\git\cmd\git.exe'
##[debug]  Arguments: 'version'
##[debug]  Working directory: 'X:\_work\b\1\_work'
##[debug]  Require exit code zero: 'False'
##[debug]  Encoding web name: utf-8 ; code page: '65001'
##[debug]  Force kill process on cancellation: 'False'
##[debug]  Redirected STDIN: 'False'
##[debug]  Persist current code page: 'False'
##[debug]  Keep redirected STDIN open: 'False'
##[debug]  High priority process: 'False'
##[debug]OOM score adjustment is Linux-only.
##[debug]Process started with process id 7820, waiting for process exit.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Exited process 7820 with exit code 1
##[debug]STDOUT/STDERR stream read finished.
Invalid executable path: 
##[debug]Finished process 7820 with exit code 1, and elapsed time 00:00:00.0704877.

##[error]Value cannot be null.
Parameter name: gitVersion
##[debug]Processed: ##vso[task.logissue type=error;]Value cannot be null.%0D%0AParameter name: gitVersion
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.Repository.GitCliManager.LoadGitExecutionInfo(AgentTaskPluginExecutionContext context, Boolean useBuiltInGit)
   at Agent.Plugins.Repository.GitSourceProvider.GetSourceAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
##[section]Finishing: Checkout DemoOneBranchLevel3@master to s

**Comment by jtpetty** [comment]
one thing that seems odd to me is 

```
X:_work\b\1\externals\git\cmd\git.exe
```

Shouldn't it be:
```
X:\_work\b\1\externals\git\cmd\git.exe
```
Also, can you ```X:\_work\b\1\externals\git\cmd\git.exe --version``` from within PowerShell on that machine?

**Comment by VenumadhavDuriseti** [comment]
Looks like a copy paste error for X:\_work. I'm attaching the image here.
![image](https://user-images.githubusercontent.com/9970018/73105681-66506d80-3eae-11ea-9978-0fd6abf499d5.png)


Also I ran X:\b\1\externals\git\cmd\git.exe --version and it has the same output:
![image](https://user-images.githubusercontent.com/9970018/73105503-06f25d80-3eae-11ea-87e1-2836f1b2363c.png)

**Comment by jtpetty** [comment]
If you run ```git.exe --version``` manually and get the same error, then this is not an agent issue. Make sure you grabbed the right binary. Is it possible you are attempting to run the x64 agent on an 32-bit x86 version of windows?

**Comment by VenumadhavDuriseti** [comment]
I tried running both x86 and x64 versions on the same test machine on RAM Disk. 
I get the same error message

![image](https://user-images.githubusercontent.com/9970018/73211609-701ddf00-4101-11ea-8656-539a1f839dc3.png)

**Comment by jtpetty** [comment]
We determined this was a bug in mingit and not with the agent. Most likely related to this issue: https://github.com/git-for-windows/git/issues/2036

The work around is to set ```System.Prefergitfrompath = true```

Closing as this is not an issue with the agent itself.
