### ISSUE TITLE
Git Version Issue

### ISSUE THREAD

**Issue by Mukund-UBS** [microsoft/azure-pipelines-agent#2751]
Issue with newly created rhel agent.

When i am installing git via yum it is giving me issue that version of git is not updated one and then when i am updating git version manuall, even in git version it is giving me the latest version but when i am running the job it says that git version is old. 
Any workaround for the same? 
Regards
Mukund

**Comment by jtpetty** [comment]
@Mukund-UBS - For linux, the agent uses whatever version of git is installed in the path. You can create a task that does a `which git` and see if that matches where you manually installed the latest version. If not, you will need to add that location to the PATH environment variable for the user running your agent.

**Comment by Mukund-UBS** [comment]
Hi @jtpetty  thanks for your reply, i resolved this by installing it in same path only where the actual git gets install i.e. /usr/local/bin/git in PATH

Regards
Mukund

**Comment by thurfir** [comment]
My apologies if this is not the same issue, I believe we have a similar problem on windows:

In our build logs (checkout task) :

##[warning]Unable to run "git clean -ffdx" and "git reset --hard HEAD" successfully, delete source folder instead.
...
remote: Azure Repos        
remote: We noticed you're using an older version of Git. For the best experience, upgrade to a newer version. 

We are using the git bundled with the build agent (2.164.6) . Is it preferable to maintain our own git version on our build servers?

**Comment by jtpetty** [comment]
We are rolling out a new version of the agent (2.164.8) with an updated git (2.25.0). The version shipped with agent does lag a bit. The nudge to upgrade to the latest git is based on security updates. For most customers, waiting for the agent to bundle an updated git is fine. If you need to be bleeding edge with security updates, then you should maintain your own git.

Here is some more information: https://github.blog/2019-12-10-multiple-git-vulnerabilities-in-2-24-and-older/

**Comment by thurfir** [comment]
Thank you @jtpetty , we will update our agents once it is release.
