### ISSUE TITLE
Windows SDK version capability not supported for 10 (/non 'A' versions)

### ISSUE THREAD

**Issue by Lawls91** [microsoft/azure-pipelines-agent#2752]
## Agent Version and Platform
2.164.6

OS of the machine running the agent? OSX/Windows/Linux/...
Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

## What's not working?
The windows SDK for v10 does not display as a capability on agents. I have checked the code, and it appears that in "Add-WindowsSdkCapabilities.ps1", while scanning "Software\Microsoft\Microsoft SDKs\Windows" registry, the script only looks for versions that end in A. e.g. v7.1A. However, the 10 SDK (and other previous non A versions of the SDK) do not get picked up.

`    Get-RegistrySubKeyNames -Hive 'LocalMachine' -View 'Registry32' -KeyName $windowsSdkKeyName |
    Where-Object { $_ -clike 'v*A' }`

Side note, it would be more useful to have the full SDK version as a capability instead of the major number.

**Comment by damccorm** [comment]
@Lawls91 this should be fixed by #2754
