### ISSUE TITLE
"Download Pipeline Artifacts" task is very slow on UNC artifacts

### ISSUE THREAD

**Issue by avivanoff** [microsoft/azure-pipelines-agent#2755]
**Type**: Bug

**Enter Task Name**: "Download Pipeline Artifacts"

## Environment
- Server - Azure Pipelines
 - Agent - Private, 2.164.6

## Issue Description

After [the fix](https://github.com/microsoft/azure-pipelines-tasks/issues/11804) we switched "Download build artifacts" task to "Download Pipeline Artifacts", and our download times for UNC artifacts increased from 4-5 minutes to over an hour.

**Comment by avivanoff** [comment]
@jahsu-MSFT, @fadnavistanmay, anything on this issue?

**Comment by avivanoff** [comment]
@jtpetty, @fadnavistanmay, can we get some updates? This issue is blocking us from using this task.

**Comment by avivanoff** [comment]
@jtpetty, @fadnavistanmay, another week has passed, still no updates.

**Comment by fadnavistanmay** [comment]
Hi @avivanoff - could you please provide the logs for the slow task, with verbose. Are you able to repro this all the time?

**Comment by avivanoff** [comment]
@fadnavistanmay, how do I send them directly to you?

**Comment by avivanoff** [comment]
@fadnavistanmay, how do I send you logs with potentially sensitive information?

**Comment by avivanoff** [comment]
@jtpetty, @fadnavistanmay, I know you are busy, but would it be possible to answer my question about sending the logs with potentially sensitive information?

**Comment by fadnavistanmay** [comment]
Hi @avivanoff - feel free to redact any sensitive information, and you could share the logs to tafadnav@microsoft.com Thanks.

**Comment by fadnavistanmay** [comment]
Adding @samuelkoppes

**Comment by avivanoff** [comment]
@fadnavistanmay, @samuelkoppes, logs are sent tafadnav@microsoft.com.

**Comment by fadnavistanmay** [comment]
Hi,

The decision was made that the customer should continue using download build artifact task, if the artifact is of type UNC and FCS.

Thanks.

cc - @samuelkoppes

**Comment by avivanoff** [comment]
@fadnavistanmay, are you going to update documentation for the task?
