### ISSUE TITLE
BYOS Feedback

### ISSUE THREAD

**Issue by achamayou** [microsoft/azure-pipelines-agent#2756]
Several of our projects (eg. microsoft/CCF, microsoft/EVM-for-CCF) make use of SGX hardware (Standard_DC SKUs in Azure). There is no hosted pool for this series.

At the moment we make do with small private static pools of ansible-deployed executors (combined with an office hours start/stop automation policy in Azure), but we would really love to have elastic pools instead, they would be so much more efficient. They would also allow us to open the CI more widely to contributors, assuming there is a way to automatically recycle the VMs.

The OpenEnclave project (openenclave/openenclave, formerly microsoft/openenclave) would also benefit. It uses a fairly custom Jenkins setup at the moment, for similar reasons at a wider scale. One of the difficulties in porting libraries (such as openenclave/openenclave-curl) is the absence of a simple public CI setup.

**Comment by damccorm** [comment]
Hey, thanks for the feedback - we're tracking this internally and it should be coming soon. I'm going to close here since the feedback has been propogated internally.

**Comment by achamayou** [comment]
@damccorm thank you! If you need beta testers, you can certainly count on us.

**Comment by vijayma** [comment]
Can you list the Azure DevOps organizations in which you would like to preview this feature?

**Comment by vijayma** [comment]
@achamayou Can you list the Azure DevOps orgs in which you would like to preview this feature?

**Comment by achamayou** [comment]
@achamayou MSRC-CCF please :)
