### ISSUE TITLE
Node.exe is returning randomly exit code -1073740791

### ISSUE THREAD

**Issue by h4570** [microsoft/azure-pipelines-agent#2758]
**## Version of your agent?**
2.164.6
**## OS of the machine running the agent?** 
Windows 10 1803 Build 17134.1184
**## Azure DevOps Type and Version**
https://dev.azure.com/

## What's not working?

1. This error appeared on several of our computers during deployments.
2. After the agent was reinstalled, the problem did not disappear.
3. **My temporary solution -> replace "../externals/node/bin/node.exe" with "../externals/node10/bin/node.exe"** 

**The same job -> 2 attempts:**
![1](https://user-images.githubusercontent.com/32263891/73259868-ffda9080-41c8-11ea-9b0b-ff08eba6917a.PNG)
![2](https://user-images.githubusercontent.com/32263891/73259876-049f4480-41c9-11ea-994b-f9370c523015.PNG)

## Agent and Worker's Diagnostic Logs
[worker_20200128_102338-utc_part.txt](https://github.com/microsoft/azure-pipelines-agent/files/4122125/worker_20200128_102338-utc_part.txt)

**Comment by tristanbarcelon** [comment]
Reverting to 2.159.2 or 2.164.6 seems to have fixed the issue. Seems to be a problem with the bundled externals?

In any case, if you have to revert, follow this powershell script. What I present below only applies to how we install agents. Conventions are good, made it easy for me to revert 16 instances of agent in one box.

```powershell
for ([int] $i = 1; $i -le 1 ; $i++)
{
     [string] $AgentPath = "c:\agent\a$($i)"
     [string] $BinPath = "$AgentPath\bin"
     [string] $TargetBinPath = "$AgentPath\bin.2.159.2"
     [string] $ExternalsPath = "$AgentPath\externals"
     [string] $TargetExternalsPath = "$AgentPath\externals.2.159.2"

     New-Item -ItemType SymbolicLink -Path $BinPath -Target $TargetBinPath -Force
     New-Item -ItemType SymbolicLink -Path $ExternalsPath -Target $TargetExternalsPath -Force
     Restart-Service -Name "$youragentnamingconvention.$($i)"
}
```
