### ISSUE TITLE
TFS login and Cyberark

### ISSUE THREAD

**Issue by oryxway** [microsoft/azure-pipelines-agent#2764]
## Having issue with Tasks?
Trying to create a connection component for TFS in CyberArk PAS system and I get the following error after it passes through the admin credentials automatically. What could be going wrong here?

TF400813: Resource not available for anonymous access. Client authentication required.

![ErrorTFS1](https://user-images.githubusercontent.com/54556579/73396367-d5f79b80-42a6-11ea-9c8e-f0a0284f0a85.JPG)

**Comment by vtbassmatt** [comment]
We're not familiar with CyberArk or PAS. Please provide more details, including the steps you took to get here. (From the screenshot it looks like this is in the web someplace. That seems unlikely to be related to the Azure Pipelines agent, which is a command-line daemon.)
