### ISSUE TITLE
Variable Build.Repository.Clean not set anymore

### ISSUE THREAD

**Issue by ReneSchumacher** [microsoft/azure-pipelines-agent#2770]
## Agent Version and Platform
Tested with versions 2.164.7 (latest release, affected), 2.164.6 (previous release, affected), and 2.163.1 (release before 2.164.6, not affected), all on Windows 10.

## Azure DevOps Type and Version
Azure DevOps Services (https://dev.azure.com/almtcger) in west Europe.

## What's not working?
Starting in some version after v2.163.1 the predefined variable Build.Repository.Clean is not set anymore. It simply remains undefined instead of reflecting the repository clean option.

**Comment by jtpetty** [comment]
I was unable to reproduce this in a simple setup.  Are you using YAML pipelines? If so, would you mind sharing your pipeline with me? Specifically the checkout step and how you are using $(Build.Repository.Clean).

**Comment by ReneSchumacher** [comment]
Hey,

for my tests I have been using a classic pipeline working on a Azure Repos Git repo, clean option set to true and source directory. I only put two tasks in the pipeline: one that dumps all variables and one PowerShell task that explicitly logs the values of $env:BUILD_REPOSITORY_CLEAN.

I can repro the problem by simply installing a v2.164.6 private agent. I added you to my internal AzDO project so you can access my pipeline at https://dev.azure.com/almtcger/CodeCoverTest/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=62. If you add a demand for Agent.Name = ReneSchu-A2 it'll run on my private agent that has v2.164.7 and shows the issue. The agent is on my laptop but I try to keep it running and connected during the day.

**Comment by jtpetty** [comment]
@ReneSchumacher - Thanks for the information. I was able to reproduce this now and am working on a fix.

**Comment by jamers99** [comment]
I see this is in [v2.165.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.165.0)! Great! It's been in prerelease for a week now, how soon will that be generally released?
