### ISSUE TITLE
multiple-agent installation, problem name

### ISSUE THREAD

**Issue by xaviertop** [microsoft/azure-pipelines-agent#2774]
Hi,

i have trouble with installation in CENTOS for azure devops agent.
when i install a agent in /data/agents/agent1 with name : "build-linux-docker-prod-172.16.3.35-eu-west-1-a1", i tried to install the second et i have an error in command "sudo ./svc.sh install". 
i think that name of service created is not correct and i can't create a second service for my "build-linux-docker-prod-172.16.3.35-eu-west-1-aZ" agent name.

**Comment by jtpetty** [comment]
@xaviertop - In order to help you we will need more context and logs of what is actually occurring when you are setting up the agent. 

One thing to note, each instance of the agent must be installed in its own directory.

**Comment by xaviertop** [comment]
issue closed
