### ISSUE TITLE
Secrets masking improvements

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-agent#2782]
Two additional scenarios to consider for secrets masking:
- `HTTP_PROXY` and `HTTPS_PROXY` are URLs which could contain an embedded secret in the form of `https://user:password@domain`. There are places in the agent code where this can end up echo'd to the console. I think (but haven't proven) that they're all protected by existing secrets masking.
- More generally, any http(s) URL printed to the screen _could_ contain an embedded secret.

I wonder if in both of these cases, we should be running a regex of the form `https?://[^:]*:([^@]*)@` and masking the captured group on all output.

**Comment by johnterickson** [comment]
> I wonder if in both of these cases, we should be running a regex of the form https?://[^:]*:([^@]*)@ and masking the captured group on all output.

galaxybrain.gif

Love it!

**Comment by vtbassmatt** [comment]
@johnterickson I do too, I just don't what it'll do to perf 🤣

**Comment by johnterickson** [comment]
Just make sure to create the object once and call it with RegexOptions.Compiled :)

There was a bad incident some time ago when the Regex internal cache started trashing 😱

https://docs.microsoft.com/en-us/dotnet/standard/base-types/compilation-and-reuse-in-regular-expressions

**Comment by vtbassmatt** [comment]
Turns out, we already have a regex masker implementation. I just had to throw a new regex at it.
