### ISSUE TITLE
Impersonation in Script Task not possible?

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-agent#2795]
Hi All,

I would like run a python script as different user than the service user of the Agent.
I am trying call the python in PowerShell script task with Start-Process and -Credential attribute.

When the -Credential defined, it fails - looks like the ADO do not support this method.
The script is working in an interactive PS session (RDP) and the second user has local authentication role on the affected Agent.

Regards,
Gabor

```
$WorkingDirectory  = "$(System.DefaultWorkingDirectory)"
$username = "username"
$password = "password"
$pythontestfile = "$WorkingDirectory\pythontestfile2.py"
$python = "D:\build\tools\python\Python3.7.1\python.exe"

#Generate python file
Add-Content $pythontestfile  "import os, getpass, time"
Add-Content $pythontestfile  "import os,sys"
Add-Content $pythontestfile  "import subprocess"
Add-Content $pythontestfile  "orig_stdout = sys.stdout"
Add-Content $pythontestfile  "f = open('pythonuser.txt', 'w')"
Add-Content $pythontestfile  "sys.stdout = f"
Add-Content $pythontestfile  "print (getpass.getuser());"
Add-Content $pythontestfile  "f.close();"

#Create credential
$credentials = New-Object System.Management.Automation.PSCredential -ArgumentList @($username,(ConvertTo-SecureString -String $password -AsPlainText -Force))

#Run as different user..
$process = Start-Process -FilePath "$python" -ArgumentList "$pythontestfile"  -PassThru -WorkingDirectory $WorkingDirectory  -Credential $credentials
$process.waitforexit()

#Check the Python output
get-content  "$WorkingDirectory\pythonuser.txt"
```

**Comment by iambernics** [comment]
Hi @vtbassmatt,

Can you confirm with calling a simple start-process / runas / psexec with different AD user from a Script Task, please?

Thanks a lot!

Regards,
Gabor

**Comment by vtbassmatt** [comment]
I don't see why this wouldn't work, and in fact we've given this as a workaround to customers in the past.

**Comment by sdg002** [comment]
Hello @vtbassmatt  , @iambernics ,
I understand this issue is closed. Could you kindly show a simple code snippet of `Start-Process` launching another PowerShell script with different credentials. I reckon the `-credential` parameter will have to be used. I can get `Start-Process` to launch another CMD.EXE, but, I can't get the impersonation to work.


My sample code below which tries to launch an instance of CMD.EXE by impersonating another local account:

```

$login="johndoe"
$credentials=Get-Credential -UserName "$env:COMPUTERNAME\$login"

$exepath="$env:windir\system32\cmd.exe"
Write-Host "Going to start-process $exepath"
Start-Process -FilePath $exepath -Credential $credentials
Write-Host "All done"

```
I get to see a new CMD.EXE, but the environment variable USERNAME in this CMD.EXE is not pointing to "johndoe".


Thanks,
Sau

**Comment by vtbassmatt** [comment]
I'm sorry, I haven't worked on Azure Pipelines in several years, and no longer have the context to help you out.
