### ISSUE TITLE
Mounting a volume into home directory makes entire home unwritable

### ISSUE THREAD

**Issue by Beakster** [microsoft/azure-pipelines-agent#2804]
## Agent Version and Platform
2.153.1
Ubuntu 18.04 LTS

## Azure DevOps Type and Version
Azure DevOps Server 2019 Update 1

## What's not working?
When a volume is mounted into the home directory, this is done before the user is created.  This causes the agents home directory to be owned by root and read only which breaks the rest of the build.

I am using Azure DevOps to build a Java application with a Maven container.  The idea is that by using the containers the developers don't have to worry about what version of Java/Maven is installed on the build server.

```
resources:
  containers:  #Maven Build Container
  - container: mavenjdk8
    image: 'adoptopenjdk/maven-openjdk8'
    options: --rm -v /var/run/docker.sock:/var/run/docker.sock
    volumes: ['/home/agent/.m2:/home/agent_azpcontainer/.m2'] #Map the Agent's Maven Repository to the Container
```
    
The build agent is running as a unix user called "agent".  We need to mount this volume because the .m2 folder contains the maven cache.  If we didn't do this we would be downloading all of the dependencies every time (significant bandwidth cost and additional build time).

When the "Initialize containers" step runs it correctly mounts the volume.  However, this is done before the agent_azpcontainer user is created.  Which means that it creates /home/agent_azpcontainer with root:root as the owner.

When the step to create the agent_azpcontainer step runs it reports that the home directory already exists:
```
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 useradd -m -u 1001 agent_azpcontainer
useradd: warning: the home directory already exists.
```
After the agent_azpcontainer user is created he does not have write access on his own home directory.  Later steps in the build try to write to .npm and .yarn folders in the home directory and fail.

I've tried to find a work around by running commands to change the permissions or ownership of the home folder, but the maven container images do not have sudo so I can't do anything with root.

I think we need a change to Agent.Worker/ContainerOperationProvider.cs to check if the home directory already exists when the user is created, and if so to set the permissions on it correctly.

## Agent and Worker's Diagnostic Logs
```

##[section]Starting: Initialize containers
##[command]/usr/bin/docker version --format '{{.Server.APIVersion}}'
'1.39'
Docker daemon API version: '1.39'
##[command]/usr/bin/docker version --format '{{.Client.APIVersion}}'
'1.39'
Docker client API version: '1.39'
##[command]/usr/bin/docker ps --all --quiet --no-trunc --filter "label=605351"
##[command]/usr/bin/docker network prune --force --filter "label=605351"
##[command]/usr/bin/docker network create --label 605351 vsts_network_ee799c3473f94c58b7899da739e15d8a
de2ed9429b17137288819310e436879c22804c15175c25301f0513fb3870490a
##[command]/usr/bin/docker pull adoptopenjdk/maven-openjdk8
Using default tag: latest
latest: Pulling from adoptopenjdk/maven-openjdk8
Digest: sha256:7e0811dc1de8b3a5085c3553ea2f6154a99931e414f690c04a697e963cb9e1a7
Status: Image is up to date for adoptopenjdk/maven-openjdk8:latest
##[command]/usr/bin/docker inspect --format="{{index .Config.Labels \"com.azure.dev.pipelines.agent.handler.node.path\"}}" adoptopenjdk/maven-openjdk8
##[command]/usr/bin/docker create --name mavenjdk8_adoptopenjdkmavenopenjdk8_8e9cb6 --label 605351 --network vsts_network_ee799c3473f94c58b7899da739e15d8a --rm -v /var/run/docker.sock:/var/run/docker.sock -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/agent/.m2":"/home/agent_azpcontainer/.m2" -v "/opt/agents/vengeance/_work/3":"/__w/3" -v "/opt/agents/vengeance/_work/_temp":"/__w/_temp" -v "/opt/agents/vengeance/_work/_tool":"/__t" -v "/opt/agents/vengeance/_work/_tasks":"/__w/_tasks" -v "/opt/agents/vengeance/externals":"/__a/externals":ro -v "/opt/agents/vengeance/_work/.taskkey":"/__w/.taskkey" adoptopenjdk/maven-openjdk8 "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4
##[command]/usr/bin/docker start 0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4
0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4
##[command]/usr/bin/docker ps --all --filter id=0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 Up Less than a second
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 sh -c "command -v bash"
/bin/bash
##[command]whoami 
agent
##[command]id -u agent
1001
Try create an user with UID '1001' inside the container.
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 bash -c "grep 1001 /etc/passwd | cut -f1 -d:"
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 useradd -m -u 1001 agent_azpcontainer
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
Grant user 'agent_azpcontainer' SUDO privilege and allow it run any command without authentication.
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 groupadd azure_pipelines_sudo
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 usermod -a -G azure_pipelines_sudo agent_azpcontainer
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 su -c "echo '%azure_pipelines_sudo ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers"
Allow user 'agent_azpcontainer' run any docker command without SUDO.
##[command]stat -c %g /var/run/docker.sock
113
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 bash -c "cat /etc/group"
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 groupadd -g 113 azure_pipelines_docker
##[command]/usr/bin/docker exec  0cf28dcbf5bb816bcc9aa20934f58b83474afdd041b0f9939096f327066951a4 usermod -a -G azure_pipelines_docker agent_azpcontainer
```

**Comment by jtpetty** [comment]
One thing you could try, mount ```/home/agent_azpcontainer/.m2``` as some other path, like ```/tmp/agent_azpcontainer_m2``` and then set ```M2_HOME=/tmp/agent_azpcontainer_m2``` in  the task so that you are not attempting to mount into the home directory.

**Comment by Beakster** [comment]
Hi @jtpetty , Yes that's an option.  What I've actually done now is I'm just mounting the entire /home/agent directory into the container at /home/agent_azpcontainer.  That seems to work well.  It does mean that a build could mess up something else in the home dir, but that could happen when building outside of a container on the agent anyway.

I'm coming to the realisation that as nice as the idea of building with containers is, it's a bit impractical.  Once the builds get complex and have several tools required you need to run multiple containers which involves a lot of publishing and downloading artifacts.  I'm moving towards just doing everything with the regular maven and dotnet build tasks on the agent.

**Comment by jtpetty** [comment]
@Beakster - Yes, containers are not a magic bullet and while they solve some problems, the bring about a different set of complexities. I don't know of any way to fix the issue you are reporting from the agent itself, since docker is creating that directory before we have an opportunity to run commands in the container without a major restructuring of how we handle job containers, which would likely not be backwards compatible. Also, it looks like you are abandoning this route, I am going to close this issue.

**Comment by Nathan187** [comment]
i'm sorry that i'm late to the party on this.  how would one mount the artifacts staging directory?  there's no clear way of doing this (if it's possible).  please help

version: '3'

services:
  something:
    image: myimg:latest
    volumes: 
      - '$(Build.ArtifactStagingDirectory)':/apks-out
