### ISSUE TITLE
Azure Devops Self Hosted Agent 

### ISSUE THREAD

**Issue by Mukund-UBS** [microsoft/azure-pipelines-agent#2813]
Hi 

I am looking for one help where I am creating my Chef Inspec Content Scanning Pipeline. 

For doing this I am using your self hosted agent feature and chef inspec execution task in my YAML file. 

Now in our project, the ask is - what if we can achieve something like below - 

1. Firstly new VM creation 
2. Scan the VM from Chef Inspec content pipeline ( Here i want to use the VM name which is created at step 1) - so i want to parameterize the VM name here in the pipeline.
3. Kill the VM once my work is done. 

Please let me know if it is feasible and if yes, any guidance if you can share. 

Regards
Mukund

**Comment by vtbassmatt** [comment]
You can get community support for specific scenarios on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). We also have support agents who monitor that forum and can provide assistance. This forum is for bugs and feature requests in the agent, not help with using it. Thanks!
