### ISSUE TITLE
Agent runnig on Windows as a service should set service SID type to SERVICE_SID_TYPE_UNRESTRICTED

### ISSUE THREAD

**Issue by avivanoff** [microsoft/azure-pipelines-agent#2814]
## Agent Version and Platform
Version of your agent? 2.164.8

OS of the machine running the agent? Windows Server

## Azure DevOps Type and Version
dev.azure.com

To allow more flexibility with access control of an agent running as a service on Windows, a service SID type should be set to **SERVICE_SID_TYPE_UNRESTRICTED**.

**Comment by jtpetty** [comment]
@vtbassmatt - Do you have any thoughts on this issue?

**Comment by avivanoff** [comment]
@jtpetty, @vtbassmatt, the issue #1294 somewhat related.

**Comment by avivanoff** [comment]
@jtpetty, @vtbassmatt, [this commit](https://github.com/avivanoff/azure-pipelines-agent/commit/a4536c49cdcd991025709f99ff685ba44da209f2) should give you an idea.

**Comment by vtbassmatt** [comment]
@avivanoff after reading a few docs, I still have very little understanding of the consequences of setting this to `SERVICE_SID_TYPE_UNRESTRICTED`. I'm open to accepting a PR of your change but would like to understand the possible impact.
- How does this change the security posture of an agent running as a service?
- Are there circumstances where we should not allow, or not default to, the changed behavior?

Sorry to put this back on you, but I know what I don't know here 😁 and would prefer to hear directly from someone who has more knowledge.

**Comment by avivanoff** [comment]
Services with SID type unrestricted have a service SID added to the service process token. In case of Azure DevOps agent, it will be something like **NT SERVICE\vstsagent.tenant.pool.agent name**. AS a result, you can use this account to grant access to local resources. If you have multiple agents  running on the same box, it will allow to use the same account to run them, while still allowing securing resources on the build box for different agents. For instance, you can secure a folder to be accessible only by **NT SERVICE\vstsagent.tenant.pool.agent 1**, but not **NT SERVICE\vstsagent.tenant.pool.agent 2**.

Ideally, you go even further and allow running the agent as the service account. This is what MS SQL Server does. And while at it you should [allow running agent as gMSA](https://github.com/microsoft/azure-pipelines-agent/issues/1294). This will free admins from managing yet another set of user name/passwords.

@vtbassmatt, let me know if this answers your question, or you need more details.

**Comment by avivanoff** [comment]
@vtbassmatt, another option that untestricted SID will allow you is to run agent as service account **NT SERVICE\vstsagent.tenant.pool.agent name**, yet another way to avoid managing passwords.

**Comment by vtbassmatt** [comment]
@avivanoff thanks. We're still open to taking this one, but haven't found time to schedule it. I appreciate the background & details you've provided.

**Comment by avivanoff** [comment]
@vtbassmatt, any updates?

**Comment by vtbassmatt** [comment]
I'm no longer working on Azure Pipelines.

**Comment by avivanoff** [comment]
@jtpetty, any updates?

**Comment by jtpetty** [comment]
I am no longer working on Azure Pipelines Agent. @mjroghelia thoughts?

**Comment by avivanoff** [comment]
@mjroghelia, any comments?

**Comment by anatolybolshakov** [comment]
Hi @avivanoff! Let us take a look at it.

**Comment by rasmuseeg** [comment]
I think this has been deployed. The prompt asked if I would like to set SERVICE_SID_TYPE_UNRESTRICTED when deploying a new environment agent on a virtual machine.

**Comment by kirill-ivlev** [comment]
Closing this issue since changes was deployed.

@avivanoff @rasmuseeg please feel free to re-open this ticket if you have any additional questions.

**Comment by Nishi183** [comment]
Enter enable SERVICE_SID_TYPE_UNRESTRICTED for agent service (Y/N) (press enter for N) > Y
Needs Administrator privileges for configuring agent as windows service.

**Comment by HeulyaOezer** [comment]
@Nishi183  have you found a solution for this

**Comment by Havunen** [comment]
> @Nishi183 have you found a solution for this

Run the command prompt as admin...
