### ISSUE TITLE
VM extension TeamServicesAgentLinux fails with "Incorrect VSTS account credentials"

### ISSUE THREAD

**Issue by atyourservers** [microsoft/azure-pipelines-agent#2817]
## Agent Version and Platform
Version of your agent?
2.165.0 (Hosted V2017)

OS of the machine running the agent?
CIS Red Hat Enterprise Linux 7 Benchmark L1

Publisher: center-for-internet-security-inc
SKU: cis-rhel7-l1
Offer: cis-rhel-7-v2-2-0-l1

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
dev.azure.com

If dev.azure.com, what is your organization name?
`https://dev.azure.com/cbsp-selfservice-arie`

## What's not working?
I'm installing the "TeamServicesAgentLinux" extension using an [ARM template](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops#install-the-azure-pipelines-agent-azure-vm-extension-using-an-arm-template) on a Linux VM which sits behind a proxy server.

I have modified the ARM template for Linux ("TeamServicesAgentLinux") and changed it to only target one VM. The template is valid. I'm using cbsp-selfservice-arie (the organization name) for "vstsAccountName". The team project specified exists and contains the deployment group to which I try to add the Linux VM. The PAT is valid and has the correct permissions (Deployment Groups - Read & manage).

The provisioning fails with the following error:
```
2020-02-26T08:01:03.1975291Z ##[debug]Exception:
2020-02-26T08:01:03.2000176Z ##[debug]Microsoft.PowerShell.Commands.WriteErrorException: DevOps agent extension installation failed. Template deployment returned the following errors: '8:01:01 AM - Resource Microsoft.Compute/virtualMachines/extensions 'arie01evm01/TeamServicesAgentLinux' failed with message '{
2020-02-26T08:01:03.2013639Z ##[debug]  "status": "Failed",
2020-02-26T08:01:03.2023748Z ##[debug]  "error": {
2020-02-26T08:01:03.2033381Z ##[debug]    "code": "ResourceDeploymentFailure",
2020-02-26T08:01:03.2043024Z ##[debug]    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
2020-02-26T08:01:03.2052842Z ##[debug]    "details": [
2020-02-26T08:01:03.2056638Z ##[debug]      {
2020-02-26T08:01:03.2067335Z ##[debug]        "code": "VMExtensionProvisioningError",
2020-02-26T08:01:03.2079078Z ##[debug]        "message": "VM has reported a failure when processing extension 'TeamServicesAgentLinux'. Error message: \"Incorrect VSTS account credentials\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot "
2020-02-26T08:01:03.2088746Z ##[debug]      }
2020-02-26T08:01:03.2099550Z ##[debug]    ]
2020-02-26T08:01:03.2109735Z ##[debug]  }
2020-02-26T08:01:03.2121397Z ##[debug]}' 8:01:01 AM - VM has reported a failure when processing extension 'TeamServicesAgentLinux'. Error message: "Incorrect VSTS account credentials"
```

When viewing the detailed status (0.status file on the Linux VM itself), I see the following error:
```
[
    {
        "code": "ComponentStatus/Pre-Validation Checks/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "Successfully validated dependecies"
    },
    {
        "code": "ComponentStatus/Read config settings/failed/53",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "AzureDevOpsOrganizationUrl should be specified"
    }
]
```

The extension.log file on the Linux VM itself reads the following:
```
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] sequence number is 0
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] setting file path is/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2/config/0.settings
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] Config decoded correctly.
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] JSON config read successfully
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] Check systemd process exit code : 0
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] stdout : /usr/bin/systemctl
2020/02/26 08:00:46
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] srderr :
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] systemd is installed on the machine.
2020/02/26 08:00:46 ERROR:[Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] AzureDevOpsOrganizationUrl should be specified
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] Setting handler status, code and message as 'error', '53' and 'Incorrect VSTS account credentials' respectively
2020/02/26 08:00:46 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] Change log file to /var/log/azure/Microsoft.VisualStudio.Services.TeamServicesAgentLinux/CommandExecution.log
```

The 0.settings file on the Linux VM itself reads the following:
```
{
    "runtimeSettings": [
        {
            "handlerSettings": {
                "protectedSettings": "",
                "publicSettings": {
                    "DeploymentGroup": "arie01",
                    "AgentName": "arie01evm01",
                    "TeamProject": "SelfService",
                    "VstsAccountName": "https://dev.azure.com/cbsp-selfservice-arie",
                    "Tags": [
                        "arie01"
                    ]
                },
                "protectedSettingsCertThumbprint": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            }
        }
    ]
}
```

The HandlerStatus file on the Linux VM itself reads the following:
```
{
    "status": "NotReady",
    "code": 1009,
    "name": "Microsoft.VisualStudio.Services.TeamServicesAgentLinux",
    "version": "1.20.0.2",
    "extensions": [],
    "message": "[ExtensionOperationError] Non-zero exit code: 53, /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2/AzureRM.py -enable\n[stdout]\n2020/02/26 08:00:46 ERROR:[Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.20.0.2] Error occured during Read config settings. AzureDevOpsOrganizationUrl should be specified\n\n\n[stderr]\n"
}
```

When adding the deployment agent via [unattended config](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#unattended-config) directly on the Linux VM itself, the deployment succeeds when I make use of the proxy server with cURL (to download the agent) and config.sh (for installing and configuring the deployment agent). I have to use the full organization name (`https://dev.azure.com/cbsp-selfservice-arie`) for this method, just like what is shown in the 0.settings file.

This leads me to believe that the error message itself is wrong and that the real error is caused by the proxy server not being used, as it's the only difference which I see? Is my deduction correct and if so, how can we solve this issue?

**Comment by jtpetty** [comment]
@bishal-pdmsft @pulkitaggarwl - Is this some thing that either of your teams handles?

**Comment by bishal-pdMSFT** [comment]
Yes @jtpetty our team owns this vm extension. We will look into this.

**Comment by anuragc617** [comment]
Hi @atyourservers, it looks like the is an issue in the `VstsAccountName` you are passing in the ARMtemplate. It should be `VSTSAccountName`. 
The error log `AzureDevOpsOrganizationUrl should be specified` is correct. The other log `Setting handler status, code and message as 'error', '53' and 'Incorrect VSTS account credentials' respectively` you are seeing in extension.log is the extension status returned back to VM because of which the below log is added to 0.status file.
`{
        "code": "ComponentStatus/Read config settings/failed/53",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "AzureDevOpsOrganizationUrl should be specified"
    }`

**Comment by atyourservers** [comment]
> Hi @atyourservers, it looks like the is an issue in the `VstsAccountName` you are passing in the ARMtemplate. It should be `VSTSAccountName`.
> The error log `AzureDevOpsOrganizationUrl should be specified` is correct. The other log `Setting handler status, code and message as 'error', '53' and 'Incorrect VSTS account credentials' respectively` you are seeing in extension.log is the extension status returned back to VM because of which the below log is added to 0.status file.
> `{ "code": "ComponentStatus/Read config settings/failed/53", "level": "Error", "displayStatus": "Provisioning failed", "message": "AzureDevOpsOrganizationUrl should be specified" }`

Are you talking about the field `VSTSAccountName` in the ARM template? That's already written that specific way; see line 66 of my full ARM template, which I quoted below:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "vmName": {
            "type": "string",
            "metadata": {
                "description": "The name of the VM on which the deployment agent will be installed."
            }
        },
        "location": {
            "type": "string",
            "metadata": {
                "description": "The location of the VM."
            }
        },
        "vstsAccountName": {
            "type": "string",
            "metadata": {
                "description": "The name of the Azure DevOps organization."
            }
        },
        "teamProject": {
            "type": "string",
            "metadata": {
                "description": "The name of the project that has the deployment group defined within it."
            }
        },
        "deploymentGroup": {
            "type": "string",
            "metadata": {
                "description": "The name of the deployment group for the agent to join."
            }
        },
        "agentName": {
            "type": "string",
            "metadata": {
                "description": "The agent name for the VM."
            }
        },
        "tags": {
            "type": "array",
            "metadata": {
                "description": "A comma-separated list of tags that will be set on the agent. Tags are not case sensitive and each must be no more than 256 characters."
            }
        },
        "patToken": {
            "type": "securestring",
            "metadata": {
                "description": "The Personal Access Token that will be used to authenticate against Azure Pipelines to download and configure the agent."
            }
        }
    },
    "resources": [
        {
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "name": "[concat(parameters('vmName'), '/TeamServicesAgentLinux')]",
            "apiVersion": "2019-07-01",
            "location": "[parameters('location')]",
            "properties": {
                "publisher": "Microsoft.VisualStudio.Services",
                "type": "TeamServicesAgentLinux",
                "typeHandlerVersion": "1.0",
                "autoUpgradeMinorVersion": true,
                "settings": {
                    "VSTSAccountName": "[parameters('vstsAccountName')]",
                    "TeamProject": "[parameters('teamProject')]",
                    "DeploymentGroup": "[parameters('deploymentGroup')]",
                    "AgentName": "[parameters('agentName')]",
                    "Tags": "[parameters('tags')]"
                },
                "protectedSettings": {
                    "PATToken": "[parameters('patToken')]"
                }
            }
        }
    ]
}
```

**Comment by atyourservers** [comment]
Do you have an update on this please @bishal-pdMSFT?

**Comment by bishal-pdMSFT** [comment]
@atyourservers Anurag's observation was based on the 0.settings file content you pasted earlier
```
{
    "runtimeSettings": [
        {
            "handlerSettings": {
                "protectedSettings": "",
                "publicSettings": {
                    "DeploymentGroup": "arie01",
                    "AgentName": "arie01evm01",
                    "TeamProject": "SelfService",
                    "VstsAccountName": "https://dev.azure.com/cbsp-selfservice-arie",
                    "Tags": [
                        "arie01"
                    ]
                },
                "protectedSettingsCertThumbprint": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            }
        }
    ]
}
```

Notice the setting named `VstsAccountName`. This can cause problem as extension reads this file to get all settings. Though it is really interesting that somehow settings specified in ARM templates are getting altered.
Is this a VM on which this extension was never installed? If no, can you try this template on VM where this template was not installed previously.

cc @tejasd1990

**Comment by atyourservers** [comment]
> @atyourservers Anurag's observation was based on the 0.settings file content you pasted earlier
> 
> ```
> {
>     "runtimeSettings": [
>         {
>             "handlerSettings": {
>                 "protectedSettings": "",
>                 "publicSettings": {
>                     "DeploymentGroup": "arie01",
>                     "AgentName": "arie01evm01",
>                     "TeamProject": "SelfService",
>                     "VstsAccountName": "https://dev.azure.com/cbsp-selfservice-arie",
>                     "Tags": [
>                         "arie01"
>                     ]
>                 },
>                 "protectedSettingsCertThumbprint": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
>             }
>         }
>     ]
> }
> ```
> 
> Notice the setting named `VstsAccountName`. This can cause problem as extension reads this file to get all settings. Though it is really interesting that somehow settings specified in ARM templates are getting altered.
> Is this a VM on which this extension was never installed? If no, can you try this template on VM where this template was not installed previously.
> 
> cc @tejasd1990

This was on a new Linux VM.

**Comment by atyourservers** [comment]
@bishal-pdMSFT @tejasd1990 any update on this issue?

**Comment by tejasd1990** [comment]
Hi @atyourservers , apologies for the response delay. You should use _AzureDevOpsOrganizationUrl_ instead of _VSTSAccountName_. We will update the documentation for this.
