### ISSUE TITLE
Permission Issues with .taskkey on Linux Build Agents running docker container

### ISSUE THREAD

**Issue by jashan05** [microsoft/azure-pipelines-agent#2821]
Hello Team,
We are using docker containers on self-hosted linux agents and we are getting intermittent issues while in the build pipelines. **Retrying a job works sometimes.**

## Agent Version and Platform
2.155 and 2.165

OS of the machine running the agent? OSX/Windows/Linux/...
Linux

## Azure DevOps Type and Version
dev.azure.com 

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

If dev.azure.com, what is your organization name? https://dev.azure.com/aegon-nl

## What's not working?
Initializing of containers on Build agents:

Starting: Initialize containers 
/bin/docker version --format '{{.Server.APIVersion}}' 
'1.39' 
Docker daemon API version: '1.39' 
/bin/docker version --format '{{.Client.APIVersion}}' 
'1.39' 
Docker client API version: '1.39' 
/bin/docker ps --all --quiet --no-trunc --filter "label=1297fd" 
/bin/docker network prune --force --filter "label=1297fd" 
/bin/docker pull maven-docker-build-container-image-jdk-11:latest 
latest: Pulling from maven-docker-build-container-image-jdk-11 
Digest: sha256:7190f400a68aa6390661e406be2d2439d20d12eaab372dd106c275f2b1f7a4b8 
Status: Image is up to date for maven-docker-build-container-image-jdk-11:latest 
/bin/docker info -f "{{range .Plugins.Network}}{{println .}}{{end}}" 
bridge 
host 
macvlan 
null 
overlay 
/bin/docker network create --label 1297fd vsts_network_52bd910f17db4d19a8e962268e28fe65 
6f541c9ace0a6127884d030cc3d1dec54b8ec09bdd44a79226234c74b7af900f 
**##[error]Access to the path '/home/ec2-user/myagent/_work/.taskkey' is denied.** 
Finishing: Initialize containers

**Comment by jtpetty** [comment]
@jashan05 - What are the permissions on ```/home/ec2-user/myagent/_work/.taskkey``` and what user is the agent running as? If those are not compatible, just delete the .taskkey file and it should get recreated correctly

**Comment by jashan05** [comment]
@jtpetty Permissions are fine on the file and with the correct user. We are using build agents which are short lived (EC2 instances which are killed after sometime) to initialize the containers. I am not sure but it seems somebody is doing something funny on these build agents. Since we have alot of developers using these build agents and therefore not easy to back track the issue.

we also tried removing the .taskkey file manually to see if it causes the issue but it gets generated again when container is initialized. So not sure what can be the issue.

Best Regards
Jashan

**Comment by jtpetty** [comment]
@jashan05 - Is this happening all the time or is it intermittent? That .taskkey file is used by our task model and the agent is supposed to delete it after a job runs and it should get automatically recreated with the next job.

**Comment by jashan05** [comment]
@jtpetty Yes it seems to be an intermittent issue. Once we get this issue , we are not able to initialize containers and we keep on getting this same error.

**Comment by jtpetty** [comment]
@jashan05 - I added a PR that may fix this issue, but given that this is intermittent, I am not 100% sure.

@mjroghelia is working to get a new release of the agent out with this change.

**Comment by jashan05** [comment]
Thanks @jtpetty for the update.

**Comment by jashan05** [comment]
Hello @jtpetty @mjroghelia we are facing the same issue again with agent version 2.175.2

Best Regards
Jashan
