### ISSUE TITLE
Agent is unable to authorize on 2.165.0 (works on 2.164.6)

### ISSUE THREAD

**Issue by edenstrom** [microsoft/azure-pipelines-agent#2824]
## Agent Version and Platform
Version of your agent? 2.165.0

OS of the machine running the agent? Linux (Ubuntu 16.04 LTS (GNU/Linux 2.6.32-042stab136.1 x86_64))

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/esatto

## What's not working?

The agent fails to connect when updated to 2.165.0. Works correctly on 2.164.6. 

On 2.165.0 the agent is unable to connect due to:
`[2020-02-26 14:11:16Z WARN VisualStudioServices] Authentication failed with status code 401.`.

**I can currently bypass the update with:**
1. Queue job
2. Auto-update triggered and updates to 2.165.0
3. Forcible kill process (normal ./svc.sh stop doesn't work. The process never finishes)
4. Delete `bin` and `externals` symlinks
5. Symlink `bin.2.164.6` and `externals.2.164.6` instead.
6. Start with `sudo ./svc.sh start`
7. The job is running
8. Next queued job will trigger auto update again. So this needs to be repeated for every build.

The process is "forever" frozen on the step below.

<img width="969" alt="2020-02-27 at 08 50" src="https://user-images.githubusercontent.com/4541038/75423033-34637880-593e-11ea-8811-70514e481d8e.png">

## Agent and Worker's Diagnostic Logs

- [Agent_20200226-131337-utc_THIS_IS_2.164.6.log](https://github.com/microsoft/azure-pipelines-agent/files/4260166/Agent_20200226-131337-utc_THIS_IS_2.164.6.log)
- [Agent_20200226-141115-utc_AFTER_UPDATE_TO_2.165.0.log](https://github.com/microsoft/azure-pipelines-agent/files/4260167/Agent_20200226-141115-utc_AFTER_UPDATE_TO_2.165.0.log)

**Comment by jtpetty** [comment]
@edenstrom - This is the first report we have had of this issue. Can you try configuring a new agent using 2.165.0 on that same machine? I want to know if it is an with the server or with how the credentials are being stored. The only material change  between 2.164.6 and 2.165.0 is that we upgraded to build it with a newer version of .NET Core.

**Comment by jstraub-sit** [comment]
Seeing a similar issue since the upgrade to 2.6.5 on RHEL 7.6
We start a self hosted agent on RHEL (1 process is running), after some time we see multiple agent processes running and producing tons of logs and error messages. Only solution is to kill the processes and restart the agent.

[Agent_20200317-160324-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/4344775/Agent_20200317-160324-utc.log)

**Comment by petrus0x13** [comment]
I'm encountering very similar problems on Debian 9.13. The configuration script stucks on the message "Connecting to server", other versions like 2.170.0 causes segmentation faults or event if it is possible to configure the agent, it is not able to report build status.

The last working version is 2.164.8, as I see this is the last version based on .NET Core 2.1.

**Comment by sundar85** [comment]
Anyone found any work around? I am kind of blocked in a Go-Live scenario. I even tried with 2.164.6 version still it doesn't work.

**Comment by sundar85** [comment]
Please run Deployment Group script on Windows PowerShell tool like the following, not Windows PowerShell ISE tool. This actually worked for me with 2.175.2.

**Comment by anatolybolshakov** [comment]
Hi @petrus0x13 could you please share your agent logs?

**Comment by anatolybolshakov** [comment]
Hi @petrus0x13 @edenstrom @jstraub-sit is this issue still actual for you?

**Comment by EzzhevNikita** [comment]
@petrus0x13 Could you please attach logs for the stuck run, if the problem is still actual for you? Also, am I understand correctly that the issue that you seeing for now in v2.193.1 is different from the one that you have seen on v2.165.0?

**Comment by EzzhevNikita** [comment]
@petrus0x13 Is it still an actual issue?
