### ISSUE TITLE
Invalid agent archives

### ISSUE THREAD

**Issue by resnikb** [microsoft/azure-pipelines-agent#2827]
## Agent Version and Platform
Platform: Linux-x64
Agent version: Tried with 2.153.1, 2.153.2, 2.165.0

## What's not working?
All of the agent archives I've tried to download today from the release page, are missing `svc.sh` script, and the bin directory contains a bunch of templates that look like they should have been transformed, amongst others there is also `systemd.svc.sh.template`. I tried downloading from several different machines and data centres, with same results. Screenshots attached below:

Root:
![image](https://user-images.githubusercontent.com/169399/75511055-07e45500-5a41-11ea-8ae4-3845985e558c.png)

Part of the `bin` folder, with templates:
![image](https://user-images.githubusercontent.com/169399/75511097-2b0f0480-5a41-11ea-90d7-310cc9724475.png)

## Background
I use a self-hosted agent, where the VM downloads an agent archive on startup, configures it and runs it as a systemctl service. Today it failed with v2.153.1 (from `https://vstsagentpackage.azureedge.net/agent/2.153.1/vsts-agent-linux-x64-2.153.1.tar.gz`) which it has been using without issues for a long time now. I've tried manually downloading that archive, as well as a few other versions (2.153.2, 2.165.0) and they are all in the same state, missing `svc.sh` from the root directory. 

Is anyone else having the same issue?

At the moment, as a temporary solution, I've configured the VM to use `run.sh` to run the agent, but that is only a workaround until the archives are back to having full content.

Please let me know if I can assist further.

**Comment by jtpetty** [comment]
@resnikb - To my knowledge, we have never shipped a ```svc.sh``` script. We ship several templates and a ```runsvc.sh``` script. Could that be what you are looking for?

@vtbassmatt - Do you recall us shipping a ```svc.sh``` script with the agent?

**Comment by resnikb** [comment]
Hi @jtpetty, thanks for pointing me in the right direction. It is entirely my bad - I did not realize that `svc.sh` is generated after a successful run of `config.sh`. In my case, configuration was failing (due to unrelated connection issues), and that failure was followed by errors about missing `svc.sh` script. 

I was focusing on those last errors, and only now saw the configuration-related ones.

Thanks, and apologies for the noise!
