### ISSUE TITLE
Agent.Plugins.PipelineCache.SavePipelineCacheV0 should also run if build status is SucceededWithIssues

### ISSUE THREAD

**Issue by karpis** [microsoft/azure-pipelines-agent#2835]
Today's behavior is that the cache is **not** persisted unless the build status is _Succeeded_ (see if-check [here](https://github.com/microsoft/azure-pipelines-agent/blob/edc22feb913d21b793edafc9b65a7b79b40dd50d/src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs#L27)).

Shouldn't a status of _SucceededWithIssues_ also be allowed? This would allow for persisting the cache in cases where a previous step has the 'continue on error' flag set or for some other reason sets the status to _SucceededWithIssues_. Or are we concerned with potentially poisoning the cache?

**Comment by fadnavistanmay** [comment]
Hello, it was a design decision made to only allow cache for successful builds. Thanks.
