### ISSUE TITLE
agent service not starting when reboot ubuntu host

### ISSUE THREAD

**Issue by luanbon** [microsoft/azure-pipelines-agent#2837]
## Agent Version and Platform
2.165.0

## Os
Ubuntu 18.04

## Azure DevOps Type and Version
dev.azure.com

Organization
https://dev.azure.com/grupoltm

## What's not working?
I am creating an azure linux virtual machine scale set using terraform, and installing build agent by cloud init script (shell script), it wotks properly at creation, but when these machines restarts the agent stop working and the service is not available anymore. The user specified (azure-user) as SUDO_USER is created automatically and the script is executed as root.

## Terraform cloud init shell script

echo "Defining Build Agent Variables"
export AGENT_VERSION="${build_agent_version}"
export VSTS_AGENT_INPUT_URL="${build_agent_url}"
export VSTS_AGENT_INPUT_AUTH="${build_agent_auth}"
export VSTS_AGENT_INPUT_TOKEN="${build_agent_token}"
export VSTS_AGENT_INPUT_POOL="${build_agent_pool}"
export AGENT_ALLOW_RUNASROOT="1"
export HOME=/home/vsts
export SUDO_USER=azure-user

echo "Setting Up Build Agent"
rm -rf $HOME
mkdir $HOME -p
mkdir $HOME/agent
cd $HOME/agent
curl --silent https://vstsagentpackage.azureedge.net/agent/$${AGENT_VERSION}/vsts-agent-linux-x64-$${AGENT_VERSION}.tar.gz | tar -xz
chmod -R 777 .
sudo -u $SUDO_USER \
        ./config.sh \
        --unattended \
        --url $VSTS_AGENT_INPUT_URL \
        --auth pat \
        --token $VSTS_AGENT_INPUT_TOKEN \
        --pool "$VSTS_AGENT_INPUT_POOL" \
        --acceptTeeEula || true
echo HOME=$HOME >> .env
cat /etc/environment | grep -ve PATH | tee -a .env
./svc.sh install $SUDO_USER
./svc.sh start
chmod -R 777 $HOME
sudo chown $SUDO_USER:$SUDO_USER $HOME

**Comment by Joel-K** [comment]
My vms were de-allocated which appears to have removed their dns settings.  Adding a valid dns entry to `/etc/resolv.conf` allowed the vm to reconnect.

My issue might be completely unrelated.  You should check if the linux service is actually running after the reboot.  If its not start it and see what happens.  If its running but not connecting check the latest ```Agent*.log``` file in the ```_diag``` folder where you installed your agent.

**Comment by jtpetty** [comment]
@luanbon - Are you still seeing this issue? Can you share any logs?
