### ISSUE TITLE
Self Hosted Agent - RedHat 7.6 & 7.7 fail.

### ISSUE THREAD

**Issue by utibeng** [microsoft/azure-pipelines-agent#2858]
## Agent Version and Platform
Various - latest agent 2.144.1 for Linux x64.
Followed the steps in https://docs.microsoft.com/en-gb/learn/modules/host-build-agent/4-create-build-agent
This works for Ubuntu but not RedHat.
Error is below;
*****************************************************
-----------------------------
 Finish Install Dependencies
-----------------------------
ldd: warning: you do not have execution permission for `./bin/libcoreclr.so'
ldd: warning: you do not have execution permission for `./bin/System.Security.Cryptography.Native.OpenSsl.so'
ldd: warning: you do not have execution permission for `./bin/System.IO.Compression.Native.so'
ldd: warning: you do not have execution permission for `./bin/System.Net.Http.Native.so'
realpath(): Permission denied
Failed to resolve full path of the current executable [/proc/self/exe]
******************************************************************
OS of the machine running the agent? Redhat Linux. Tried and it works fine with Ubuntu
--------OS Information--------
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
------------------------------
The current OS is Fedora based
--------Redhat Version--------
Red Hat Enterprise Linux Server release 7.7 (Maipo)
------------------------------

**Comment by Fmstrat** [comment]
I am experiencing this as well.

**Comment by Fmstrat** [comment]
I found the problem was the ownership of the files in the folder. They were owned by `1001` instead of the `msagent` user I had created. Running this as `root` for the install worked:

```
# Install MS Build agent
mkdir -p /opt/ms-build-agent &&\
cd /opt/ms-build-agent &&\
wget https://vstsagentpackage.azureedge.net/agent/2.166.2/vsts-agent-linux-x64-2.166.2.tar.gz &&\
tar xvfz vsts-agent-linux-x64-2.166.2.tar.gz &&\
useradd -r -s /bin/false msagent &&\
chown msagent . -R &&\
/opt/ms-build-agent/bin/installdependencies.sh &&\
su -s /bin/bash -c '/opt/ms-build-agent/config.sh' msagent
```

**Comment by dhevany** [comment]
works I am running centos 8
# Install MS Build agent
mkdir -p /opt/ms-build-agent &&\
cd /opt/ms-build-agent &&\
wget https://vstsagentpackage.azureedge.net/agent/2.166.2/vsts-agent-linux-x64-2.166.2.tar.gz &&\
tar xvfz vsts-agent-linux-x64-2.166.2.tar.gz &&\
useradd -r -s /bin/false msagent &&\
chown msagent . -R &&\
/opt/ms-build-agent/bin/installdependencies.sh &&\
su -s /bin/bash -c '/opt/ms-build-agent/config.sh' msagent
