### ISSUE TITLE
CommandLine task failing after update from 2.165.0 to 2.165.2 (Unable to locate executable file: 'bash')

### ISSUE THREAD

**Issue by simonlegeek** [microsoft/azure-pipelines-agent#2864]
## Having issue with YAML?
Please log an issue at [Azure-Pipelines-YAML](https://github.com/Microsoft/azure-pipelines-yaml). Over there we discuss YAML templates, samples for Azure Pipelines, and designs for upcoming YAML features. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.

## Having issue with Tasks?
Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.

## Having issue with software on Hosted Agent?
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.

## Having generic issue with Azure-Pipelines/VSTS/TFS?
Please report it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.165.2

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) 

If dev.azure.com, what is your organization name? https://dev.azure.com/devolutions-net

## What's not working?
When we try to run a task of type CommandLine (alias to script) in a Job running in a Windows container. The task fail with the following message: 

`##[error]Unable to locate executable file: 'bash'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.`

I don't quite understand why it looks for bash while on Windows. This started happening as soon as we updated our agent to version 2.165.2.

We use self-hosted agents running Windows Server 2019 and we run our build inside Windows containers.  We get this error for any kind of CommandLine task we try to run. 

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

![image](https://user-images.githubusercontent.com/38378106/77081413-03241880-69d1-11ea-98d5-fa858e257314.png)

[rawlogs.txt](https://github.com/microsoft/azure-pipelines-agent/files/4355349/rawlogs.txt)

**Comment by jtpetty** [comment]
@simonlegeek - Can you try setting the variable ```agent.preferPowerShellOnContainers = true``` and seeing if this resolves your issue?

**Comment by simonlegeek** [comment]
I'll try this out!

**Comment by simonlegeek** [comment]
It seems to be working fine. My understanding of this is that you actually use PowerShell to launch the actual batch script.  By that I mean, I don't have to change our CMD-style commands (%VARIABLE%, etc) for this to work?

**Comment by jtpetty** [comment]
Correct. It just what mechanism we use start up the task. Our task model supports tasks being launched from PowerShell or Node. The CmdLine task can be launched from either depending on the platform. The issue that prompted the change is that newer Windows containers ship with PowerShell Core and not PowerShell and so we defaulted to choose the Node handler for containers to work around that issue. It seems that breaks if the container does not have bash so we may need to see if we can autodetect that scenario.

**Comment by mback2k** [comment]
I think this issue should be kept open until an automated solution has been implemented.
