### ISSUE TITLE
Agent fails with System.OutOfMemoryException

### ISSUE THREAD

**Issue by rmetzger** [microsoft/azure-pipelines-agent#2886]
## Agent Version and Platform
Version of your agent? `2.165.0` on Linux

## What's not working?

Last night, I saw that a lot of builds were failing with an error message like this:
```
##[error]We stopped hearing from agent AlibabaCI007-agent2. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
```
See: https://dev.azure.com/rmetzger/5bd3ef0a-4359-41af-abca-811b04098d2e/_build/results?buildId=6901

Out of the 16 agents, only this particular one has this issue.

## Agent and Worker's Diagnostic Logs

Here are, what I believe relevant logs from that agent: https://gist.github.com/rmetzger/d313c87bc3aea22f94c20475f67d1b7d

There are more of those cases in the _diag folder.

```
./svc.sh status

/etc/systemd/system/vsts.agent.rmetzger.Default.AlibabaCI007\x2dagent2.service
● vsts.agent.rmetzger.Default.AlibabaCI007\x2dagent2.service - Azure Pipelines Agent (rmetzger.Default.AlibabaCI007-agent2)
   Loaded: loaded (/etc/systemd/system/vsts.agent.rmetzger.Default.AlibabaCI007\x2dagent2.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-02-21 17:42:28 CST; 1 months 9 days ago
 Main PID: 4713 (runsvc.sh)
    Tasks: 37
   Memory: 3.5G
   CGroup: /system.slice/vsts.agent.rmetzger.Default.AlibabaCI007\x2dagent2.service
           ├─ 4713 /bin/bash /home/agent2/myagent/runsvc.sh
           ├─ 4716 ./externals/node/bin/node ./bin/AgentService.js
           ├─ 7031 /home/agent2/myagent/bin/Agent.Listener run --startuptype service
           └─23256 /home/agent2/myagent/bin.2.165.0/Agent.Worker spawnclient 114 120

Apr 01 02:20:45 iZgw814dze6vb5iq9eabnuZ Agent.Worker[28723]: Only single test suite found, parsing its information.
Apr 01 02:20:45 iZgw814dze6vb5iq9eabnuZ Agent.Worker[28723]: PublisherTraceSource Verbose: 0 :
Apr 01 02:21:02 iZgw814dze6vb5iq9eabnuZ runsvc.sh[4713]: 2020-03-31 18:21:02Z: Job test_ci core completed with result: Succeeded
Apr 01 02:28:14 iZgw814dze6vb5iq9eabnuZ runsvc.sh[4713]: 2020-03-31 18:28:14Z: Running job: test_ci python
Apr 01 03:01:44 iZgw814dze6vb5iq9eabnuZ runsvc.sh[4713]: 2020-03-31 19:01:44Z: Job test_ci python completed with result: Succeeded
Apr 01 08:58:01 iZgw814dze6vb5iq9eabnuZ runsvc.sh[4713]: 2020-04-01 00:58:01Z: Running job: test_cron_scala212 legacy_scheduler_core
Apr 01 14:20:09 iZgw814dze6vb5iq9eabnuZ runsvc.sh[4713]: 2020-04-01 06:20:09Z: Agent connect error: The HTTP request timed out a...cted.
Apr 01 14:21:30 iZgw814dze6vb5iq9eabnuZ runsvc.sh[4713]: 2020-04-01 06:21:30Z: Agent reconnected.
Apr 01 15:15:53 iZgw814dze6vb5iq9eabnuZ runsvc.sh[4713]: 2020-04-01 07:15:53Z: Agent connect error: The HTTP request timed out a...cted.
Apr 01 15:17:00 iZgw814dze6vb5iq9eabnuZ runsvc.sh[4713]: 2020-04-01 07:17:00Z: Agent reconnected.
Hint: Some lines were ellipsized, use -l to show in full.
```

Maybe there's a memory leak somewhere in the agent? it's been running for over one month, as you can see from above.

**Comment by damccorm** [comment]
Hey @rmetzger - I'm a little confused - is there a reason to believe that the agent is what is leaking memory and its not just the worker process consuming lots of memory (doing whatever task its running)? The fact that your only seeing this on 1/16 agents makes me think there's something environmental going on as well - is the machine its running on particularly strapped for resources?

Have you tried adjusting the agent process oom scores? See this doc - https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/start/resourceconfig.md - that should also help. If the agent still gets killed after that I'd be much more suspicious of a memory leak or something similar.

**Comment by rmetzger** [comment]
Thank you for looking into this. The machine has 64GB of main memory. 
Next time I see the issue, I will check the kernel log messages if the oom killer was active.
Thanks a lot for this document, it is extremely helpful! I will adjust the oom score (and also look into a cgroup config)
