### ISSUE TITLE
Azure devops offline agents delete

### ISSUE THREAD

**Issue by srisurya777** [microsoft/azure-pipelines-agent#2887]
We are using a kubernetes scheduler and assigning pods to the agents in a deployment pool. During those restart cycles, several new agents would start and others would go offline. The best way I can close on deleting those offline agents is through REST API. However, azure devops document do not recommend calling delete for agents inside agent pool. Can someone help me understand consequences and take measures ? 

or 

If I can delete them in a better way 

Thanks
Naga

**Comment by damccorm** [comment]
Hey @srisurya777 - not 100% sure I understand the question. Is there a reason you can't deconfigure your agent when preparing to go offline using the config script (by calling into `config.sh`). If not, then deleting those agents using the API is fine. The guidance there is to help avoid accidentally deleting agents that are still in existence (and maybe even are still running jobs) - that's a common source of user bugs.

**Comment by srisurya777** [comment]
Thanks for your response. There are too many offline agents and I wanted to delete them through API's (coz quick solution). I wasnt clear about why we dont want to call it but now I get your point. I will close this issue.
