### ISSUE TITLE
Agent will not install properly in combination with xVSTS DSC

### ISSUE THREAD

**Issue by seriousscripts** [microsoft/azure-pipelines-agent#2893]
##Agent Version and Platform
Version of your agent? 2.166.0

OS of the machine running the agent? 
Windows Server 2019

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

If dev.azure.com, what is your organization name? 

## What's not working?
```
PS C:\> Install-VSTSAgent -AgentDirectory C:\VSTSAgents\ -Name 'agentname' -ServerUrl 'https://dev.azure.com/org/' -PAT $pat -Replace
Install-VSTSAgent : Unrecognized command-line input arguments: 'runAsService'. For usage refer to: .\config.cmd --help
or ./config.sh --help
At line:1 char:1
+ Install-VSTSAgent -AgentDirectory C:\VSTSAgents\ -Name 'cki3-ontwikke ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-VSTSAgent
```
The agent service is not installed properly. This has popped up last few days when DSC installed the 2.166.0 version. It is not present in the current stable release. 

## Relevant logs
  "Help": false,
  "Version": false
}
[2020-04-02 13:14:36Z INFO AgentProcess] Arguments parsed
[2020-04-02 13:14:36Z ERR  Terminal] WRITE ERROR: Unrecognized command-line input arguments: 'runAsService'. For usage refer to: .\config.cmd --help or ./config.sh --help

**Comment by damccorm** [comment]
@jeschu1 could you take a look?

**Comment by jeschu1** [comment]
2.166.0 has case sensitivity on args.  We changed that behavior.

Please try v2.166.2.  Note that is also a pre-release, but please let us know if you have any issues.

**Comment by seriousscripts** [comment]
Hi I'm sorry I missed @jeschu1 comment. Indeed this was automatically resolved when our DSC automatically installed a newer version.
