### ISSUE TITLE
Unable to start Mac Agent with the release build (v2.165.2)

### ISSUE THREAD

**Issue by xplatform** [microsoft/azure-pipelines-agent#2912]
##  Agent Version and Platform
v2.165.2 

OS of the machine running the agent? OSX 10.15.4

## What's not working?
After upgrading my Mac to the latest OSX 10.15.4, and the agent to the latest release v2.165.2, I am not able to start the Mac agent with "./run.sh" command, even after allowing all the prompted assemblies to be open in "Security & Privacy" => "General" => "Allow apps downloaded from".

## Agent and Worker's Diagnostic Logs
Diagnostic log is attached.
[Agent_20200407-174251-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/4446382/Agent_20200407-174251-utc.log)

**Comment by damccorm** [comment]
Hey @xplatform - from the diagnostic logs it looks like the agent isn't configured. Have you tried running ./config.sh first?

**Comment by xplatform** [comment]
Ok. I will try it first. I didn't remember I needed to do that in the previous version.

**Comment by xplatform** [comment]
![server url](https://user-images.githubusercontent.com/15225483/79013121-d9b46380-7b1c-11ea-89eb-0fcb54034615.png)

**Comment by damccorm** [comment]
Yep, that's right - you should be able to follow the instructions here - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops#download-and-configure-the-agent

**Comment by xplatform** [comment]
Btw, I am getting a lot of popups like this one, and have to manually allow them in the Security & Privacy setting.

![privacy popup](https://user-images.githubusercontent.com/15225483/79013236-2009c280-7b1d-11ea-8aa5-18709406c129.png)

**Comment by damccorm** [comment]
Looks like that issue is being tracked here - https://github.com/microsoft/azure-pipelines-agent/issues/2457

**Comment by xplatform** [comment]
Ok. Thanks for the instructions. It is working now.
