### ISSUE TITLE
Agent version 2.1.662 giving git exit code 128 when checking out Azure Devops repo. 

### ISSUE THREAD

**Issue by brandonmcclure** [microsoft/azure-pipelines-agent#2923]
## Having issue with Tasks?
Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes

## Agent Version and Platform
2.1662 - Windows x64

OS of the machine running the agent? OSX/Windows/Linux/...
Windows Server 2016

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

If dev.azure.com, what is your organization name? 
https://dev.azure.com/DenverHealth-EpicCogito

## What's not working?
I am getting git exit code 128 errors on my checkout tasks that run on agent version 2.166.2. These errors do not occur on the same pipeline/YAML running on agent v2.164.8 on the same box.  
I noticed this when I configured some new agents directly from the most recent release. I ran the pipeline on a agent with v2.164.8 and the checkout task worked as expected. Upgraded the same agent through the web gui and got the same behavior/error below that the fresh 2.166.2 agent gave me. 

The checkout YAML looks like:

```
- checkout: self
  persistCredentials: true
  lfs: false
```

Log from the checkout task:
```
Syncing repository: Caboodle (Git)
Prepending Path environment variable with directory containing 'git.exe'.
git version
git version 2.25.1.windows.1
git config --get remote.origin.url
git clean -ffdx
git reset --hard HEAD
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
##[warning]Unable to run "git clean -ffdx" and "git reset --hard HEAD" successfully, delete source folder instead.

Recieves objects/resolves deltas

git checkout --progress --force 628ba96f8c0952f530c9bf22c8b10301ea02eaed
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
##[error]Git checkout failed with exit code: 128
```

## Agent and Worker's Diagnostic Logs
I can send these over email if needed.

**Comment by aldodfm** [comment]
and other things: https://developercommunity.visualstudio.com/content/problem/991764/agents-cannot-download-artifacts-on-release-pipeli.html

**Comment by MarkIannucci** [comment]
Developer community indicates that this was fixed in version 2.166.3.  We haven't tested it out yet.

**Comment by brandonmcclure** [comment]
Upgraded an agent to v2.166.3 and ran 2 separate pipelines and they both failed with the same error as above.

**Comment by mjroghelia** [comment]
@brandonmcclure @MarkIannucci The Developer Community issue linked to above is in regards to downloading build artifacts from Release pipelines and is unrelated to the checkout task.

Could you please run your pipeline with the "Enable system diagnostics" option checked from the queue screen? Then use the "Download logs" link in the "..." menu on the build results screen to download the zipped logs. You can attach them to this issue via a comment or email them to me @ mark.roghelia@microsoft.com.

**Comment by MarkIannucci** [comment]
@mjroghelia , thanks for following up, disambiguating the issue, and reaching out.  I've e-mailed you our logs.

**Comment by brandonmcclure** [comment]
Upgrading to v2.166.4 resolved the issue for us. 

We discussed the need to have git-lfs on the build system/PATH on these agents With @mjroghelia via email. 

Updating the agent works now without modifying any of the git-lfs settings on our hosted agent VMs. Closing this issue.
