### ISSUE TITLE
Link to `arm64` package is broken in v2.166.3

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-agent#2928]
Link to `arm64` package is broken in [v2.166.3](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.166.3), both `arm` and `arm64` point to `arm` file.
This one https://vstsagentpackage.azureedge.net/agent/2.166.3/vsts-agent-linux-arm64-2.166.3.tar.gz doesn't exist.

_Originally posted by @amaslenn in https://github.com/microsoft/azure-pipelines-agent/issues/1911#issuecomment-615224898_

**Comment by mjroghelia** [comment]
I've built the ARM64 2.166.3 release and updated the release notes.
