### ISSUE TITLE
Question: Running agent as standalone app

### ISSUE THREAD

**Issue by jeffsaremi** [microsoft/azure-pipelines-agent#2956]
We have many pipelines in Azure DevOps configured using corresponding Yaml files. They're working fine. However, for local, developer testing we'd have to rewrite those yaml files into something else and run them via our own hacked up tools.

Is there a way to use this agent as a library or standalone too to run the same Yaml files in Azure pipelines but on a developers machine? (no Agent setup, no pipeline, no agent pool)

**Comment by mjroghelia** [comment]
No, the agent is dependent on the Azure Pipelines service to execute the workflow described by the YAML.
