### ISSUE TITLE
Cannot register same VM resource into multiple environments

### ISSUE THREAD

**Issue by geofflamrock** [microsoft/azure-pipelines-agent#2961]
## Agent Version and Platform
OS: Windows

## Azure DevOps Type and Version
Azure DevOps Services
https://dev.azure.com/Blueshift

## What's not working?
Hi,

When registering a Windows VM resource into an environment using the script provided by the UI, the same VM cannot be registered into multiple environments. The underlying service that gets created always has the same id (vstsagent.{Organization}..{MachineName}) and so it gets replaced. 

As a workaround we can adjust the install powershell script to change the agent name to include the environment at the end but this leaves the resource name looking strange in the environment.

When using deployment groups  the underlying deployment pool gets put into the service id (vstsagent.{Organization}.{DeploymentPoolId}.{MachineName}) and so the same VM can be registered into multiple deployment groups but this doesn't work for environments.

Is this behaviour expected?

Thanks.

**Comment by chshrikh** [comment]
yes this is by design, if you want to use multiple VM agent from same machine, you need to have unique name for each of them.

**Comment by geofflamrock** [comment]
Ok thanks @chshrikh 

It's a bit of a shame it doesn't work the same as deployment groups, we have a requirement to be able to deploy to multiple environments from the same VM which we could do via deployment groups in the default setup, but can't with environments.
