### ISSUE TITLE
Self hosted agents with throw-away VMs.

### ISSUE THREAD

**Issue by pauldotknopf** [microsoft/azure-pipelines-agent#2963]
* I want self-hosted agents.
* I want to have a clean build environment on each build.
* I don't want to use "Container jobs". It forces me to worry about things like DinD. My builds also do complicated things like chroots which are a pain when running in a container.
* I don't want to depend on Azure. Ideally, I'd like to create VirtualBox/VMWare instances on-the-fly and dispose-when-ran.

I see issues #2051 and #1630, but they depend on either Azure or Container jobs.

With that said, I'd like to investigate what it would take to implement an abstraction over a remote "Agent.Worker". This abstraction would be responsible for things like:

* Setting up the instance (VMWare, VirtualBox, etc).
* Establish a connection to the instance.
* Install a worker that will be executed once.
* Cleaning up the instance.

I'm thinking the "Agent.Listener" would be invoking this abstraction to eventually run a "Agent.Worker" on the remote instance.

Any input/help/guidance on this would be great. I'm currently digging into the code-base to determine what this effort would look like.

Thanks!

**Comment by pauldotknopf** [comment]
After looking around, I think I found a better/easier approach.

I'm thinking of running something like this on the host.

```
while true
    start vagrant instance with image that has agent installed and configured
    ssh vagrant /agent/run.sh --once
    stop vagrant instance
```

What do you guys think?

**Comment by mjroghelia** [comment]
Refactoring the agent with a new worker abstraction would be beyond the scope of changes we'd be interested in supporting. A simple approach using the `--once` option seems reasonable for you to try.
