### ISSUE TITLE
Linux ARM64 package link in v2.168.2 release points to the ARM package

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/azure-pipelines-agent#2964]
In the GH the releases, the ARM64 package link for the [v2.168.2 release](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.168.2) points to the ARM package - https://vstsagentpackage.azureedge.net/agent/2.168.2/vsts-agent-linux-arm-2.168.2.tar.gz. I speculate the link should be https://vstsagentpackage.azureedge.net/agent/2.168.2/vsts-agent-linux-arm64-2.168.2.tar.gz instead.

**Comment by mjroghelia** [comment]
Fixed. Thanks!
