### ISSUE TITLE
Tools help on self-hosted agent shows an incorrect URL

### ISSUE THREAD

**Issue by denravonska** [microsoft/azure-pipelines-agent#2966]
When trying to use UsePythonVersion on a self-hosted agent with missing tools the log displays the following error message:

> If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.

This URL redirects to the main Microsoft page, in my case `https://www.microsoft.com/sv-se/?ref=go`.

Agent version 2.168.2 is affected.

**Comment by mjroghelia** [comment]
This looks like it has been corrected.
