### ISSUE TITLE
Node.js version update to LTS (12) for pipeline tasks

### ISSUE THREAD

**Issue by anatolybolshakov** [microsoft/azure-pipelines-agent#2967]
Hi! Are there any plans to update Node version used for pipeline tasks execution to the current LTS (12)? We are working on CopyFilesOverSSH pipeline and faced with an issue that for Ed25519 key support we need to use at least Node 12 - for current version (Node6 or Node10) it is possible, but it requires much more efforts, so it would be great to have the latest version onboard.

**Comment by MatkovIvan** [comment]
Bump. The current version fails with assert, and it's not supported by node team yet. See https://github.com/nodejs/node/issues/34633

**Comment by rossbeehler** [comment]
Note that the documentation of azure-pipelines-task-lib is indirectly claiming that node14 is supported: https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/nodeEnvironment.md

**Comment by JamieMagee** [comment]
Given that Node.js 10 support ended on 30th April 2021, are there any plans to add Node.js 12 (maintenance LTS) or 14 (active LTS)?

**Comment by Bjego** [comment]
Node 6 is causing problems with the recently updated Root certificate of letsencrypt as well. See the issue(s) with Sonarqubes plugin: https://community.sonarsource.com/t/cert-has-expired-issue-on-sonarqube/25656/29

**Comment by SimonAlling** [comment]
> Given that Node.js 10 support ended on 30th April 2021, are there any plans to add Node.js 12 (maintenance LTS) or 14 (active LTS)?

Or perhaps Node 16, now that "Active Support" for Node 14 ended today [according to endoflife.date](https://endoflife.date/nodejs).

**Comment by BrianMikinski** [comment]
Would really like to see this get updated so we can use Ed25519 ssh keys

**Comment by anatolybolshakov** [comment]
Just as a quick update - there are plans to introduce Node 14 execution handler and start updating tasks to this, but it could take some time due to wide and significant changes.

**Comment by SimonAlling** [comment]
> Just as a quick update - there are plans to introduce Node 14 execution handler and start updating tasks to this, but it could take some time due to wide and significant changes.

Nice! Perhaps even Node 16, since ["Active Support" for Node 14 ended last October](https://github.com/microsoft/azure-pipelines-agent/issues/2967#issuecomment-946840470)?

**Comment by JamieMagee** [comment]
GitHub Action's equivalent change skipped Node 14 and went directly to Node 16: https://github.com/actions/runner/pull/1439

**Comment by JamieMagee** [comment]
There are currently 2 PRs open to add support for new versions of Node.js

- #3861
- #3849

**Comment by JamieMagee** [comment]
@anatolybolshakov I think this can be closed now that #3861 is merged
