### ISSUE TITLE
Agent unable to use TFS proxy server

### ISSUE THREAD

**Issue by NorbertHuethmayr** [microsoft/azure-pipelines-agent#2969]
Hi,

I'm seeing a similar issue where the agent is trying to reach the proxy server but fails to authenticate.
The build output shows the following message

The source control proxy 'tfsproxy.domain.local' is not responding, so the request will be sent to the main server. Please verify your settings.
Additional information:
TF30063: You are not authorized to access Microsoft-IIS/8.5.

Might this be related to the fact that I had to make my agent run using the Admin account?
https://stackoverflow.com/a/13605747/13034542

### Agent version and platform
2.122.1 x64

OS of the machine running the agent
Windows Server 2019

### VSTS type and version

On-Prem TFS
2017 (15.117.27414.0)

**Comment by mjroghelia** [comment]
Please use the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) for configuration help.
