### ISSUE TITLE
Self-hosted agent - Install error on 2 agents for different environments

### ISSUE THREAD

**Issue by PaulGauthier** [microsoft/azure-pipelines-agent#2971]
We have two development teams with their own Azure DevOps project. All pipelines are YAML based and we deploy to Environments. We have a need to use the same on-premise VM in an environment in each project or to be able to share the environment across projects.

When adding a VM resource to an environment, a powershell script is provided that runs the agent as a windows service by default. It is smart enough to create an A2 directory for the second agent, but when it tries to install the windows service the install fails. It uninstalls the windows service from the first agent before it fails so I believe that it is trying to use the same service name for both instances.

I've tried to specify a different -agent value in hopes that it would result in a different service name for the windows service, but that does not work. 

As a workaround, I installed the 2nd instance without the --runAsService parameter. I think I can make a windows service wrapper for it myself, but it seems like this is either a bug or a missing feature.

Is there another way to accomplish this goal?

**Comment by nmdange2** [comment]
I have the same problem.  I was able to work around the issue by manually renaming the first agent's service name in the registry (HKLM\SYSTEM\CurrentControlSet\Services\vstsagent.<name>").  Note you have to restart the server for the registry change to take effect.  After renaming the existing service, the second one can be installed.  

This should really be fixed by using the environment and project names in the Windows service name.

**Comment by anatolybolshakov** [comment]
Hi @PaulGauthier @nmdange2 you can set agent name during agent configuration by setting --agent option for 'config' script ([here's ](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#pool-and-agent-names)some more info about config script options) - so there should be services with different names.

**Comment by PaulGauthier** [comment]
@anatolybolshakov I'm not sure it worked or was available at the time I asked the question, but what I do now add the VM resource from the environment. I take the script provided and change the --agent parm as you mentioned by adding something on the end that identifies the project to which it is associated. I've done that many times now and it works fine.

I'd like to see environments be shared like we can share service connections now. Then we could just install one agent. However, this agent name change works for now.

**Comment by anatolybolshakov** [comment]
> I'd like to see environments be shared like we can share service connections now

@PaulGauthier could you please create a separate ticket for this enhancement?

**Comment by anatolybolshakov** [comment]
@PaulGauthier let me close this ticket since current issue is resolved - please feel free to create a ticket with a feature request for suggestion above.
