### ISSUE TITLE
Http Request timeout from agent on Azure Virtual Machines

### ISSUE THREAD

**Issue by saltniklas** [microsoft/azure-pipelines-agent#2989]
Hi!

We are using Azure Devops for our build and release pipelines. We have installed the pipeline agent on each of our 6 Azure VM's. Deploying works fine, but I have noticed in the server logs that all 6 Virtual Machines are getting a intermittent connection errors:

2020-05-28 20:06:09Z: Agent connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.

Our environment is new and still undergoing testing. The VM's are behind a Azure Load Balancer using NAT Gateway/PIP. The Idle Timeout set on LB and NAT-GW is 4 minutes. Could this be a problem for the Azure Agent? We dont have any problems with other applications on the servers getting timeouts.

Agent installed as extension on the ARM-template used for creating the VM.

Agent package win-x64.
Version: 2.168.2
Running on Windows (X64).
Microsoft Windows 10.0.17763.

Best regards,

Niklas Andersson

Log:
[maskedlog.log](https://github.com/microsoft/azure-pipelines-agent/files/4701079/maskedlog.log)

**Comment by saltniklas** [comment]
[maskedlog.log](https://github.com/microsoft/azure-pipelines-agent/files/4701075/maskedlog.log)

**Comment by andersonsilvaeng** [comment]
I also have the same problem, my server is linux

**Comment by andersonsilvaeng** [comment]
I also have the same problem, my server is linux

**Comment by anatolybolshakov** [comment]
Hi @saltniklas @andersonsilvaeng could you please try to increase http timeout and retry count using VSTS_HTTP_RETRY and VSTS_HTTP_TIMEOUT agent knobs? ([here's ](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Knob/AgentKnobs.cs#L120) you can find default values for these knobs)
If there are some issues with network - it could help to workaround it and make agent more sustainable regarding this.

**Comment by anatolybolshakov** [comment]
Hi @saltniklas @andersonsilvaeng do you have any updates about this one?

**Comment by anatolybolshakov** [comment]
@saltniklas @andersonsilvaeng I'm closing this at the moment due to inactivity, please feel free to reopen or ask any further questions.
