### ISSUE TITLE
Cannot find agent pool settings tab

### ISSUE THREAD

**Issue by anmolah** [microsoft/azure-pipelines-agent#2990]
I see this path is recommended to find the self-hosted agent maintenance job -  Organization Settings -> Agent Pools -> Select Your Agent Pool -> Settings

But I can't seem to find it anytime I follow the path. Is this feature being rolled out ?

**Comment by stephenmichaelf** [comment]
@anmolah Yes that is exactly where it is. Do you have permissions? Can you share a screenshot?

![image](https://user-images.githubusercontent.com/450490/86622389-d1d65500-bf8d-11ea-9177-0a32f04d5cf8.png)

**Comment by anmolah** [comment]
@stephenmichaelf, I am an owner of this pool and an admin on the project/devops instance. I do not see the settings tab

![image](https://user-images.githubusercontent.com/11351400/86622774-523c8c00-bf75-11ea-8869-e14d770ec51f.png)

**Comment by anatolybolshakov** [comment]
Hi @anmolah is this issue still actual for you?

**Comment by anatolybolshakov** [comment]
@anmolah we can't reproduce this issue with the same pre conditions (admin permissions, pool's owner), I'm closing this at the moment due to inactivity - please feel free to reopen it or ask any questions.

**Comment by StefanLundmark** [comment]
I'm running into this as well. 

![image](https://user-images.githubusercontent.com/2816866/103387146-8054f000-4b02-11eb-85c8-a765cea027e1.png)

* I'm the owner of the pool. Under the "Security" tab it says I'm an Administrator (Assigned).
* I'm also in the "Project Administrators" role (Inherited)
* I'm also the owner of the organization and project, if that helps.

**Comment by StefanLundmark** [comment]
Okay. I went trough Organization Settings instead of Project Settings. These two interfaces look very similar but one of the differences is that the Settings tab exists in the former but not in the latter.

**Comment by ffigu002** [comment]
@StefanLundmark thanks for pointing that out! I spent hours troubleshooting the "Project Settings" view when I should've been looking at the "Organization Settings".

Agent Pools show up in both, I don't think the documentation states clearly which interface we should be looking at.
