### ISSUE TITLE
Cannot register agent to both Deployment Group and Environment together

### ISSUE THREAD

**Issue by gdsjerry** [microsoft/azure-pipelines-agent#2997]
## Agent Version and Platform
2.168.2 - Windows 2016

## Azure DevOps Type and Version
ivanti.visualstudio.com

## What's not working?
When trying to register the VM agent, it only seems to work when registering to Deployment group or to Environment, but not to both. When passing both --environment and --deploymentgroup parameters the registration proceeds and no error is thrown, but the VM is actually only registered to Deployment group. It doesn't register or show up in Resources tab in Environments. 

It does work when not providing the --deploymentgroup parameter but we would like to have this agent available both for classic and yaml pipelines. Currently YAML don't support Deployment Groups. 

Is it supported or planned to support having agent both in Environments and Deployment groups at the same time? 

## Agent and Worker's Diagnostic Logs
```
. 'C:\Program Files\VSTS Agent\config.cmd' --url 'https://ivanti.visualstudio.com/' --auth pat --token 'secret' --projectName 'MyProject' --agent $env:computername --runAsService --runAsAutoLogon --environment --environmentname "MyEnvironment" --deploymentGroup --deploymentGroupName 'MyGroup' --unattended

  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.168.2             |_|          (commit 180d386)


>> Connect:

Connecting to server ...

>> Register Agent:

Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
2020-06-02 11:47:35Z: Settings Saved.
Granting file permissions to 'NT AUTHORITY\SYSTEM'.
Service vstsagent.ivanti.MyProject-DeploymentGroup.MyHostname successfully installed
Service vstsagent.ivanti.MyProject-DeploymentGroup.MyHostname successfully set recovery option
Service vstsagent.ivanti.MyProject-DeploymentGroup.MyHostname successfully set to delayed auto start
Service vstsagent.ivanti.MyProject-DeploymentGroup.MyHostname successfully configured
Service vstsagent.ivanti.MyProject-DeploymentGroup.MyHostname started successfully
```

**Comment by DotNetSparky** [comment]
That's by design. You can install two instances, however, one for each type.
