### ISSUE TITLE
Workspace directory GC per-pipeline instead of per-job

### ISSUE THREAD

**Issue by jeevcat** [microsoft/azure-pipelines-agent#3004]
## Agent Version and Platform
v2.169.1

Windows

## Azure DevOps Type and Version
dev.azure.com

https://dev.azure.com/rwone

## What's not working?

As far as I can tell, the BuildDirectoryManager uses the `collectionId` and the `definitionId` (i.e. pipeline identifiers) plus information about the source repositories to decide whether a workspace directory can be re-used. 

However, workspace directories are per job. If you have a pipeline with 1 job who uses 1 repository and another job who uses a different repository, the build directory manager will continuously mark the previous "tracking file" for garbage collection and will create a new workspace directory. 

This effectively means no workspaces are ever re-used. Can a job identifier also be used to uniquely identify a tracking file? This would prevent `LoadExistingTrackingConfig` from trying to use the previous pipeline's config, even though it was from a job with different source repos.

**Comment by mjroghelia** [comment]
This behavior was changed in September. The agent now creates a workspace ID that is generated from the repositories used.
