### ISSUE TITLE
Shallow clone STILL fetches all tags defeating the shallow fetch

### ISSUE THREAD

**Issue by kenotron** [microsoft/azure-pipelines-agent#3013]
## Agent Version and Platform
Version of your agent? 2.165.2

OS of the machine running the agent? Windows & Linux

## Azure DevOps Type and Version
If dev.azure.com, what is your organization name? https://office.visualstudio.com

## What's not working?
git checkout job hardcodes to have `--tags` even with shallow fetches. The Office team has had some previous commits with large binary blobs that had been polluting the history. We have removed these, but the --tags addition will make sure that even shallow fetches will not actually make it checkout the code very much faster.

These commands need to be modified to allow an option to turn off fetching all tags.

https://github.com/microsoft/azure-pipelines-agent/blob/c25985e4410178dae61e03d9cc8e01190ce11ee4/src/Agent.Worker/Build/GitCommandManager.cs#L232

**Comment by DomhnallP** [comment]
This is affecting our pipelines too. any plans to fix?

**Comment by anatolybolshakov** [comment]
Hi @kenotron since this seems to be new input for checkout task and requires some changes throughout Azure DevOps - could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by anatolybolshakov** [comment]
@kenotron let me close this one at the moment since it requires some DevOps side changes.

**Comment by MatthewSteeples** [comment]
Tickets already exist:
https://developercommunity.visualstudio.com/t/Need-to-omit---tags-when-performing-sh/943621?space=21&q=shallow
https://developercommunity.visualstudio.com/t/Exclude-tags-for-shallow-clones-or-at-l/1266211?space=21&q=shallow
