### ISSUE TITLE
stopped hearing from agent Azure Pipelines

### ISSUE THREAD

**Issue by Adithi-Azure** [microsoft/azure-pipelines-agent#3015]
I tried deploying my DACPAC but it runs for sometime and fails with the below error
"We stopped hearing from agent Hosted Agent. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error."

Any solution for this will really be helpful.

**Comment by Adithi-Azure** [comment]
![image](https://user-images.githubusercontent.com/54442708/84672413-d1b3de00-af28-11ea-97d8-0cd89b4a5e41.png)

**Comment by sarthikgupta** [comment]
Hello Adithi, did you get any solution to fix this issue. I am facing the similar issue from past 3 days.

**Comment by boschcrank** [comment]
Same here for a MacOS based (hosted) agent. How should _I_ make sure the "agent machine is running" - the VM is somewhere at Azure, we do not even know where.

**Comment by Akhil1666** [comment]
@Adithi-Azure Have you found any solution for this issue?
