### ISSUE TITLE
./config.sh: line 29: 79387 Segmentation fault: 11  ./bin/Agent.Listener configure "$@"

### ISSUE THREAD

**Issue by caner-karaman** [microsoft/azure-pipelines-agent#3021]
Agent Version and Platform

Version of your agent? 2.122.1

OS of the machine running the agent? MacOS Catalina - 10.15.5

VSTS Type and Version

local TFS server

What's not working?

Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N) > y

Connect:
Enter server URL > https://tfs.company.local
Enter authentication type (press enter for Negotiate) > Negotiate
Enter user name > userName
Enter password > *************
Connecting to server ...
./config.sh: line 29: 79387 Segmentation fault: 11  ./bin/Agent.Listener configure "$@"

**Comment by caner-karaman** [comment]
Because of getting 401 unauthorised error.

**Comment by oneframemobile** [comment]
We have a same problem. Any progress? Is the problem solved?

**Comment by anatolybolshakov** [comment]
Hi @oneframemobile what agent version do you use?
