### ISSUE TITLE
Bundle linux version of node with windows agent

### ISSUE THREAD

**Issue by dferretti** [microsoft/azure-pipelines-agent#3023]
Would it be possible to bundle a linux version of node in the windows agent? 

Currently, there is this limitation: 
https://github.com/microsoft/azure-pipelines-agent/blob/af907e5f6f077f98910c68863ae93742b8a28a0f/src/Agent.Worker/ContainerOperationProvider.cs#L353

I occasionally bump into this limitation if I want to test an existing pipeline on my local machine. For example, if I have a pipeline (that is 100% container job driven) for a repository that normally runs on our company's "main" linux agent that we host ourselves, and I want to test out or debug it by running an agent on my local windows machine, I am unable to run the pipeline without first modifying all the containers it uses to make sure node is manually installed in the container. 

If the windows agent were able to bring its own linux version of node, that would allow me to use the same pipeline without any modification, and without needlessly building wrapper containers with node installed around all of the containers it uses. 

Thanks!

**Comment by anatolybolshakov** [comment]
Hi @dferretti you can use UseNode pipeline task to install node - could you please check if it works for you?

**Comment by anatolybolshakov** [comment]
Hi @dferretti is this issue still actual for you?

**Comment by dferretti** [comment]
Hey @anatolybolshakov sorry I missed your first message! I am not currently working on that project anymore so I can't immediately try out the UseNode solution you mentioned. I imagine that would work fine though. 

The windows agent bundling the linux version of node would be a nice-to-have so you don't have to include that step, but UseNode is a good alternative 👍

**Comment by anatolybolshakov** [comment]
Thanks! Let me leave it as a possible enhancement - to check if we could ship linux node version with agent and use it generally in linux containers.
