### ISSUE TITLE
macOS Catalina 10.15.5 4678 Segmentation fault: 11

### ISSUE THREAD

**Issue by caner-karaman** [microsoft/azure-pipelines-agent#3026]
**### Agent version and platform**

Agent: 2.122.1
macOS Catalina 10.15.5

VSTS type and version

Microsoft Visual Studio Team Foundation Server
Version 16.122.27102.1

What's not working?

Steps taken:

brew install openssl
./config.sh

Expected output:
build agent is now properly configured

Actual output:
Enter server URL > https://*****/tfs
Enter authentication type (press enter for Negotiate) > 
Enter user name > **********
Enter password > **********
Connecting to server ...
./config.sh: line 29:  4678 Segmentation fault: 11  ./bin/Agent.Listener configure "$@"

Agent log:
[Agent_20200623-135917-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/4819894/Agent_20200623-135917-utc.log)

**Comment by mjroghelia** [comment]
Based on the report this is a really old version of the agent. Please try the latest release.
