### ISSUE TITLE
Not working with the Raspberry Pi 4 model (Raspberry Pi OS: Buster)

### ISSUE THREAD

**Issue by SKO85** [microsoft/azure-pipelines-agent#3027]
## Agent Version and Platform
Version of your agent? **2.170.1**
OS of the machine running the agent? **Linux/ARM/v7**
## What's not working?
I am trying to setup the agent on an ARMv7 (32bit) system (Rasbperry Pi 4 model), but the agent does not to work and throws the following error:

```
pi@RPi-1:/srv/devops/myagent $ ./config.sh
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-configure does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
.NetCore 3.1 has been installed and I verified this with the command:
```
pi@RPi-1:/srv/devops/myagent $ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
**Architecture using on RPi4:**
```
pi@RPi-1:/srv/devops/myagent $ uname -a
Linux RPi-1 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
```
**Raspbian OS version:**
```
pi@RPi-1:/srv/devops/myagent $ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
**Used resources:**
```
Agent package: vsts-agent-linux-arm-2.170.1.tar.gz
.NetCore Runtime: aspnetcore-runtime-3.1.5-linux-arm.tar.gz 
.NetCore SDK: dotnet-sdk-3.1.301-linux-arm.tar.gz
```

It indicates that **dotnet-configure** does not exist, but that command is unknown on any documentation i tried to find for the dotnet CLI. On an Raspberry Pi 3 this seems to work fine. On all RPi4 models I have I get the same issue.

The **./config** command also required several dependencies that were not available with the newest Raspbian OS (buster) so I needed to modify the apt source list to use **stretch** instead and get the dependencies.

**Comment by SKO85** [comment]
After no reply and some further investigation now I got some time to search deeper I found that **libcurl3** is missing. I called the install-dependency script, but this packages are not available for the Raspberry Pi OS Buster version.

```
pi@RPi-1:/srv/devops/myagent $ ./config.sh
./bin/System.Net.Http.Native.so: /usr/lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./bin/System.Net.Http.Native.so)
Warning: on some platforms, libcurl3 is required.
```
Anyone having an idea how to fix this and install the agent on an RPi4 model? Is there an alternative build I could use for this?

**Comment by anatolybolshakov** [comment]
Hi @SKO85 starting from [2.177.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.177.0) libcurl is no longer needed by default - could you please try it with the last agent version?

**Comment by anatolybolshakov** [comment]
@SKO85 is this issue still actual for you?

**Comment by biasync** [comment]
Still an issue but with Rasp 3B
Version: vsts-agent-linux-arm-2.179.0
OS: Raspbian GNU/Linux 10 (buster)

Output: 
~/myagent $ ./config.sh 
./bin/System.Net.Http.Native.so: /lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./bin/System.Net.Http.Native.so)
Warning: on some platforms, libcurl3 is required.

**Comment by SKO85** [comment]
@anatolybolshakov : I will be setting up my new kubernetes cluster with the RPI-4 model and will try to verify this this weekend. Thx for your reply. I will keep you posted.

**Comment by anatolybolshakov** [comment]
@biasync did you try to run bin/installdependencies.sh - to install necessary dependencies?

**Comment by anatolybolshakov** [comment]
Hi @SKO85 @biasync do you have any updates?

**Comment by SKO85** [comment]
@anatolybolshakov , yes. Sorry for the late answer. I was not able to test with Raspbian OS, but teststed with Ubuntu 20.04 64bit ARM64 version for Raspberry Pi 4. The package as downloaded from the DevOps site worked without issues for me.

**Comment by anatolybolshakov** [comment]
@SKO85 thanks!
@biasync do you still see this issue with Raspbian OS?

**Comment by anatolybolshakov** [comment]
@biasync I'm closing this ticket due to inactivity at the moment - please feel free to ask any further questions.
