### ISSUE TITLE
ubuntu:18.04 - No usable version of the libssl was found

### ISSUE THREAD

**Issue by koehrlenguillaume** [microsoft/azure-pipelines-agent#3031]
Hey Everyone, 

I'm following the documentation to run a self hosted agent in docker: [link](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops-2019#linux)

But I get stuck with the following error 
```cmd 
>> Connect:

No usable version of the libssl was found
./config.sh: line 86:    69 Aborted                 ./bin/Agent.Listener configure "$@"
```

Do you have an idea why? Maybe this is linked to the release of the new ubuntu image (two weeks ago)

Thanks

**Comment by koehrlenguillaume** [comment]
To fix, you have to change the docker file with 
```cmd
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    git \
    iputils-ping \
    libcurl4 \
    libicu60 \
    libunwind8 \
    netcat \
    libssl1.0 
```

**Comment by ittimtadej** [comment]
@koehrlenguillaume on Ubuntu 20.04.2 LTS I get this: `E: Unable to locate package libicu60` :(

**Comment by lepirlouit** [comment]
> @koehrlenguillaume on Ubuntu 20.04.2 LTS I get this: `E: Unable to locate package libicu60` :(
replace it with `libicu66`
