### ISSUE TITLE
RELEASE_REQUESTEDFOREMAIL:  old value after the migration

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-agent#3043]
Hi All,

We migrate the Azure DevOps user's domain name of primary email address from user@domainA.com to user@domainB.com.
After the migration, RELEASE_REQUESTEDFOREMAIL is pushing the old domain (user@domainA.com).

The primary email addresses are changed on the on-prem AD, AAD and the users are logging with the new domain to the ADO.
Azure Pipelines are using, cached addresses are not possible.

I do not find the source of this attribute in the Agent's source code.

Have you any idea about the source of this attribute?

Regards,
Gabor

**Comment by iambernics** [comment]
@juliobbv Based on your [commit ](https://github.com/microsoft/azure-pipelines-agent/pull/2196/files), maybe you have idea how detect the Agent the value of this variable: Release.Deployment.RequestedForEmail" :)

**Comment by anatolybolshakov** [comment]
Hi @iambernics looks like this variable's value comes from Azure DevOps - could you please create ticket on https://developercommunity.visualstudio.com/spaces/21/index.html to get right eyes on it?

**Comment by anatolybolshakov** [comment]
Let me close this one since it doesn't seem to be related to the agent itself - feel free to ask any further questions!
