### ISSUE TITLE
$(Build.SourceVersionMessage) should be set to the shelveset message for Gated Checkins in TVFC

### ISSUE THREAD

**Issue by siprbaum** [microsoft/azure-pipelines-agent#3045]
## Azure DevOps Type and Version
On-premis TFS Server 2019

Version Dev17.M153.5

## What's not working?
We want to implement certain commit message keywords for skipping tests and to configure the tasks
customn conditon ala `contains(variables['Build.SourceVersionMessage'], '[skip tests]'`
to skip the long running tests.

Sadly, the variable `Build.SourceVersionMessage` doesn't return the propsed commit message of the shelveset.
Instead, it contains the message of the latest changeset!

For a gated checkin, where the changes are always represented as shelvesets, the variable `Build.SourceVersionMessage` should contain the shevelsets message.

**Comment by siprbaum** [comment]
Alternatively, introducing a seperate variable ala Build.ShelvesetMessage would also solve the problem.

**Comment by siprbaum** [comment]
IMHO, that is still a valid feature request

**Comment by anatolybolshakov** [comment]
@MaximMalygin could you please take a look?

**Comment by siprbaum** [comment]
I believe this is still a valid feature request, addressing a gap in how shelveset messages are handled
