### ISSUE TITLE
Self-hosted pipeline agents stuck on version 2.165.0.

### ISSUE THREAD

**Issue by GaTechThomas** [microsoft/azure-pipelines-agent#3049]
## Agent Version and Platform
Version of your agent? 2.165.0

OS of the machine running the agent? OSX/Windows/Linux/...
Windows 10.0.17763

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? 
https://dev.azure.com/3dsi

## What's not working?
Updating the agents in the agent pool doesn't work. This is done via the Agent Pools web UI using the "Update all agents" button. Same behavior if updating one agent at a time via the same UI.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

I don't currently have access to the machine's logs. Starting with the maintenance logs:

[2020-07-20 Build agent maint log.txt](https://github.com/microsoft/azure-pipelines-agent/files/4948961/2020-07-20.Build.agent.maint.log.txt)

**Comment by GaTechThomas** [comment]
Do I need to do something else here? Can I somehow get the logs without direct access to the machine?

**Comment by anatolybolshakov** [comment]
Hi @GaTechThomas unfortunately as I see there's no way currently to retrieve agent logs without access to _diag folder on the agent - is there any way you could retrieve these logs from machine and share it?

**Comment by anatolybolshakov** [comment]
Hi @GaTechThomas do you have any updates about it? Is it possible to get logs so we could investigate it?

**Comment by GaTechThomas** [comment]
I'll see what I can do. Will likely be after the new year.

**Comment by anatolybolshakov** [comment]
Hi @GaTechThomas do you have any updates?

**Comment by GaTechThomas** [comment]
Everything is now working as expected. We have enough in flux that I don't know whether it was something that changed on our side or not.
