### ISSUE TITLE
Add local cache support to Pipeline Artifacts and Pipeline Caching

### ISSUE THREAD

**Issue by johnterickson** [microsoft/azure-pipelines-agent#3053]
Per https://github.com/microsoft/azure-pipelines-tasks/issues/11864#issuecomment-662626823
> It would be nice if there was a first-level cache on the local machine maintained by this task. 

This is actually super close to being there. 

If anyone needs to take this up:

- [ ] BuildXL (or Azure Artifacts on their behalf) will need to publish the some more of the BuildXL cache packages
- [ ] This  DedupStoreHttpClient will need to be wrapped with a  DedupStoreHttpClientWithCache 
 here: https://github.com/microsoft/azure-pipelines-agent/blob/e80c3261724f3256141076ae666bd0ca47e267c7/src/Agent.Plugins/PipelineArtifact/DedupManifestArtifactClientFactory.cs#L39
We'll want to hide this behind an envvar to start with e.g. `AZURE_ARTIFACTS_CACHE_SIZE_IN_MB` with null/0 means no cache.

**Comment by adrian-skybaker** [comment]
>This is actually super close to being there
