### ISSUE TITLE
Agents not available to project

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/azure-pipelines-agent#3072]
## What's not working?
My organization pays for 80 parallel jobs that we need to access from private and public projects. We are not able to access the extra agents from the public project, only the 10 free ones, so our jobs are constantly stuck in the queue, sometimes for hours. 

Are there any settings we need to change to access all of our agents from all our projects?

**Comment by mjroghelia** [comment]
For general Azure DevOps support not specific the the agent code, please open a ticket on Developer Community and customer support will route to the appropriate team. https://developercommunity.visualstudio.com/content/problem/post.html?space=21
