### ISSUE TITLE
Agent becomes a zombie after receiving a cleanup job because of missing repositories element

### ISSUE THREAD

**Issue by aok-foss** [microsoft/azure-pipelines-agent#3073]
## Agent Version and Platform
Version of your agent? 2.168.2, 2.173.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com
If dev.azure.com, what is your organization name? https://dev.azure.com/FossAnalytical
The agents are running on-prem.

## What's not working?
On receiving a build cleanup job, the agent throws an exception internally about "repositories" missing in the job json.
Then the agent does nothing as the job keeps running (for days). Eventually, the whole pool becomes stuck. We have to restart the zombie agent manually and clean up build artefacts manually.

We have seen the issue occur with classic build pipelines using with TFVC and GIT.

## Agent and Worker's Diagnostic Logs
Attached log files 
[Worker_20200806-153610-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/5049399/Worker_20200806-153610-utc.log)
[Agent_20200806-071846-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/5049407/Agent_20200806-071846-utc.log)

**Comment by aok-foss** [comment]
Looks like this was caused by #2768.
The change introduced there is guarded by `agent.useWorkspaceIds` flag. Is there a way to set the flag for all the agents in our pool as a workaround? Guess we cannot use an environment variable because of the dot symbol in the name.

**Comment by aok-foss** [comment]
Another issue introduced by the same change is agent maintenance jobs failures. At least these fail without the agent hanging indefinitely:
[MaintenanceSummary.txt](https://github.com/microsoft/azure-pipelines-agent/files/5050338/MaintenanceSummary.txt)

**Comment by mjroghelia** [comment]
@aok-foss Thank you for the report. We have disabled this feature flag. Restarting the agents in the pool should get them back into a working state. If you could confirm that this issue is fixed for you after the agent restart that would be a big help.

**Comment by aok-foss** [comment]
Yes, the agent restarts did help. We had restart agents every day because the cleanup jobs kept coming, and yesterday we downgraded the whole pool to version 2.166.4. So we will not be able to check the effects of disabling the feature flag.
