### ISSUE TITLE
Need variable in Azure DevOps for the FullSourceBranchName

### ISSUE THREAD

**Issue by ChuckkNorris** [microsoft/azure-pipelines-agent#3076]
Problem
- The `Build.SourceBranchName` variable does not include the full branch name (e.g. `feature/test` is represented incorrectly as `test`). This requires pretty much everyone that deals with branches in their pipelines to write custom scripts to concatenate the full branch name together. The currently broken variable couldn't be fixed for backwards compatibility reasons, but I think we can all agree that the existing branch variable is pretty much useless if we have forward slashes in our branch name.

Solution
- Add another build variable for the full branch name (e.g. `Build.SourceBranchFullName` that correctly includes the entire branch name)

Notes
- Referencing https://github.com/microsoft/azure-pipelines-agent/issues/838 - it was closed, but never resolved

**Comment by justinjstark** [comment]
This would be very helpful. Build.SourceBranchName is wrong. If I have these branches:

dev/foo
hotfix/foo

The Build.SourceBranchName will be "foo" for both of them which is incorrect, unexpected, and can lead to downstream CI/CD confusion and errors. For backward compatibility, having a Build.SourceBranchFullName would suffice.

**Comment by ckolumbus** [comment]
Me2!!! This really problematic for us.

**Comment by ckolumbus** [comment]
I found `Build.SourceBranch` that provides me with the necessary branch information. Does this help?

**Comment by clisc** [comment]
> I found `Build.SourceBranch` that provides me with the necessary branch information. Does this help?

No, this doesn't help because it is prefixed with "refs/head/" or something like that.  You can manipulate that string to get the full branch name but it does not provide it automatically.

I really could use this variable.  I can't believe the way they implemented `Build.SourceBranchName`.

**Comment by biolauri** [comment]
> > I found `Build.SourceBranch` that provides me with the necessary branch information. Does this help?
> 
> No, this doesn't help because it is prefixed with "refs/head/" or something like that. You can manipulate that string to get the full branch name but it does not provide it automatically.

AFAIK, the `Build.SourceBranch` does not provide the correct branch _name_ for Pull Requests as it provides something like `refs/pull/1/merge` (see [Azure Docs on Build Variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services)), which is the internal branch, but not helpful for anything where the (corresponding) corresponding branch name is necessary. So, it's not solely an issue of providing it automatically (which would be just for convenience).

**Comment by anatolybolshakov** [comment]
Hi everyone, since this issue is related to adding of new variable - could you please create ticket on https://developercommunity.visualstudio.com/spaces/21/index.html to get right eyes on it?

**Comment by ChuckkNorris** [comment]
> Hi everyone, since this issue is related to adding of new variable - could you please create ticket on https://developercommunity.visualstudio.com/spaces/21/index.html to get right eyes on it? Let me close this one since it doesn't seem to be related to the agent itself.

Could you please create a new issue on that site and link it here? This is the third time someone has closed the issue without resolution, just kicking the can down the road.

Tired of being pulled multiple directions when everyone seems to be ignoring this issue. We escalated the issue, the least y'all can do is get it to the appropriate team's backlog.
