### ISSUE TITLE
Agent AutoRemoval from Agent Pool on SIGINT or SIGTERM

### ISSUE THREAD

**Issue by ryanpodonnell1** [microsoft/azure-pipelines-agent#3078]
I wanted to see what the expected behavior of the agent when running the cleanup portion of the `start.sh` script:

```bash
trap 'cleanup; exit 130' INT
trap 'cleanup; exit 143' TERM

cleanup() {
    if [ -e config.sh ]; then
        print_header "Cleanup. Removing Azure Pipelines agent..."
        ./config.sh remove --unattended \
        --auth PAT \
        --token $(cat "$AZP_TOKEN_FILE")
    fi
}
```

I would like to delete the agent entirely as we are using ephemeral containers to spin up build agents but still show up in the console as offline. I've reviewed the documentation => [Running a self-hosted agent in Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)

Seems like I could call the `DELETE` endpoint but would prefer if the `./config.sh remove` portion took care of this instead

![image](https://user-images.githubusercontent.com/48141361/90180638-45356880-dd7d-11ea-844a-d8de5c52c307.png)

**Comment by GaryRogers** [comment]
You'll need to preserve the AZP_TOKEN_FILE in that case. Looks like it's removed lower in the script.

**Comment by GaryRogers** [comment]
Also, a PAT with Agent Group and Deployment Group permissions doesn't appear to have rights to remove an agent. I get these errors when trying:

```
Removing agent from the server
Error reported in diagnostic logs. Please examine the log for more details.
    - /azp/agent/_diag/Agent_20210107-154943-utc.log
Failed: Removing agent from the server
TF400813: Resource not available for anonymous access. Client authentication required.
```

**Comment by ToniA** [comment]
This issue still seems valid. We started to use the KEDA Azure Pipelines scaler. Every time it scales down, it leaves 'offline' agents behind.

To me it seems that the agent indeed tries to remove itself from the pool, but doesn't have rights to do so (/azp/.token file exists and seems valid):
```
$ ./config.sh remove --unattended --auth PAT --token /azp/.token
Removing agent from the server
Error reported in diagnostic logs. Please examine the log for more details.
    - /home/agent/_diag/Agent_20220513-125635-utc.log
Failed: Removing agent from the server
VS30063: You are not authorized to access https://dev.azure.com.
```

This is the first error in the log file
```
[2022-05-13 12:56:37Z WARN VisualStudioServices] Basic issued token provider instance 61705107 requires an interactive prompt which is not allowed by the current settings
[2022-05-13 12:56:37Z ERR  VisualStudioServices] GET request to https://dev.azure.com/xxxxxx/_apis/connectionData?connectOptions=0&lastChangeId=212164652&lastChangeId64=212164652 is not authorized
. Details: VS30063: You are not authorized to access https://dev.azure.com.
```
