### ISSUE TITLE
Is "version" a predefined or reserved variable?

### ISSUE THREAD

**Issue by perpetualKid** [microsoft/azure-pipelines-agent#3085]
## Agent Version and Platform
Version of your agent? 2.173.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
Maybe I just haven't found it anywhere in documentation. Having a variable "version" in the pipeline causes some pretty nasty and unexpected side-effects, and I don't see any documentation about [predefined variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml), or any other reserved words.
There are multiple tasks failing and it's no where obvious to the user that where/how that version is passed around and used.

i.e. setting
```
variables:
  Version: '1.2.3.4.5.6'
```

will at first instance cause a Nuget Restore task to fail

> Detected NuGet version 5.7.0.6726 / 5.7.0+b804bf4ba62c0b47c77bbf3e22e196b57cd7a556.b804bf4ba62c0b47c77bbf3e22e196b57cd7a556
> SYSTEMVSSCONNECTION exists true
> C:\hostedtoolcache\windows\NuGet\5.7.0\x64\nuget.exe sources Add -NonInteractive -Name NuGetOrg -Source https://api.nuget.org/v3/index.json -ConfigFile D:\a\1\Nuget\tempNuGet_535.config
> Package source with Name: NuGetOrg added successfully.
> C:\hostedtoolcache\windows\NuGet\5.7.0\x64\nuget.exe restore D:\a\1\s\VersionTest\VersionTest.sln -Verbosity Detailed -NonInteractive -ConfigFile D:\a\1\Nuget\tempNuGet_535.config
> C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\csanes0g.3hy.nugetrestore.targets(160,5): error MSB4018: The "WriteRestoreGraphTask" task failed unexpectedly. [C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\3lxfmmkx.ikw.nugetinputs.targets]
> NuGet Version: 5.7.0.6726
> C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\csanes0g.3hy.nugetrestore.targets(160,5): **error MSB4018: System.ArgumentException: '1.2.3.4.5.6' is not a valid version string**. [C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\3lxfmmkx.ikw.nugetinputs.targets]
> 

Having a more valid version string
```
variables:
  Version: '1.2.3'
  VersionSuffix: 'alpha.1'
```

will override any version(suffix) parameters defined in the solution or passed as arguments to MSBuild Task
```
  - task: MSBuild@1
    displayName: Building the solution
    inputs:
      solution: '$(solution)'
      msbuildArchitecture: 'x64'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '-property:VersionSuffix=$(versionSuffix)'
```

> "D:\a\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.166.2\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -latest -format json
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" "D:\a\1\s\VersionTest\VersionTest.sln" /nologo /nr:false /dl:CentralLogger,"D:\a\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.166.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=|SolutionDir=D:\a\1\s\VersionTest"*ForwardingLogger,"D:\a\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.166.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" -**property:versionsuffix=alpha.1** /p:platform="Any CPU" /p:configuration="Release" /p:_MSDeployUserAgent="VSTS_e52e8498-937d-414a-a9ea-729fef41d04b_build_10_0"
> Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
> 

As per command line, the version suffix is passed correctly, and should be merged with VersionPrefix as defined in a project (or Prefix will default to 1.0.0). However, somewhere the $(version) variable is getting used, and all assemblies' file version and product version are set to "1.2.3" instead of expected "1.0.0-alpha.1"

All works as expected if just renaming the "version" variable.

## Agent and Worker's Diagnostic Logs
As per above.

**Comment by anatolybolshakov** [comment]
Hi @perpetualKid it seems that "Version" environment variable is used by Nuget tool, but this seems to be not documented well - since it's not related to agent, I would recommend to create ticket on https://github.com/NuGet/NuGet.Client - to get right eyes on this issue.

**Comment by anatolybolshakov** [comment]
Closing this also since it's not related to agent itself.
