### ISSUE TITLE
Add tags to environment when configuring agent

### ISSUE THREAD

**Issue by vivaladan** [microsoft/azure-pipelines-agent#3086]
I'm attempting to install the agent on a fresh Azure Linux VM. 

This is going to be deployed to from a YAML pipeline, thus it's installing into an environment and not a deployment group.

This is going to be automated as part of a pipeline, so I would to add the correct environment tags to it on creation. There won't be a chance to do this as a manual step. I see this can be done with addDeploymentGroupTags, but as the name implies this appears to only work when adding to deployment groups, and not environments.

The agent gets created and shows up under environments with the command below, but the tag 'test' is not added.

Is this expected and this would be a new feature, or this this a bug because addDeploymentGroupTags should work for both?

## Agent Version and Platform
Version of your agent? 2.173.0

OS of the machine running the agent? UbuntuLTS

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
mkdir azagent;
cd azagent;
curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.173.0/vsts-agent-linux-x64-2.173.0.tar.gz
tar -zxvf vstsagent.tar.gz
./config.sh --environment --environmentname "Development" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/###/ --work _work --projectname '###' --auth PAT --token ### --addDeploymentGroupTags --deploymentGroupTags "test" --unattended --runasservice;

**Comment by thozook** [comment]
@vivaladan My team encountered this same issue and started to dig through the code to see if this had been added and not documented. 

Looks like the ability to add tags to VM resources in Environments is an undocumented feature. If you look at [Constants.cs](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Constants.cs) under "public static class CommandLine", there is a "virtualmachineresourcetags" arg and a "addvirtualmachineresourcetags" flag.

We tested this out and it did work by using --addvirtualmachineresourcetags in place of --addDeploymentGroupTags and --virtualmachineresourcetags in place of --deploymentGroupTags.

Agent Version: 2.177.1
OS: CentOS Linux release 7.9.2009 (Core)

Looks like this might have been added in through PR #2471 and they never updated either online documentation nor the --help documentation.

**Comment by adamency** [comment]
@anatolybolshakov These options are still not documented in the `--help`. Would it be possible to add it ?

Otherwise (cc @thozook) , these options are documented in a page a buried bit deep in MS Docs about [installing an Azure Pipelines Agent on a Windows host](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops). However they don't have changed anything to the System Capabilities when I go look at the agent in the UI: https://dev.azure.com/<organization>/<project>/_settings/agentqueues?agentId=<agentId>&queueId=<queueId>&view=capabilities

Do they actually work for Windows agent @anatolybolshakov ?

**Comment by anatolybolshakov** [comment]
Hi @adamency sure, let us take a look at update for `--help` option - as I see there are no OS conditions for this logic, so it should work for Windows as well.

**Comment by jbreadner** [comment]
I am using `--addvirtualmachineresourcetags --virtualmachineresourcetags tag1=val1,tag2=val2` kind of syntax, and I also do not see the capabiliities added to the agent once it's in the pool.  This is on Ubuntu 22.04 using agent 2.204.0.

**Comment by AdrianSanguineti** [comment]
The syntax which worked for me on Windows Server Core 2022 using agent 2.217.2 was:

```
--addvirtualmachineresourcetags --virtualmachineresourcetags tag1,tag2,tag3
```

I would expect it's the same format for the agent on other operating systems (but have not confirmed).
