### ISSUE TITLE
"We stopped hearing from agent Hosted Agent..."

### ISSUE THREAD

**Issue by talebi** [microsoft/azure-pipelines-agent#3094]
## Agent Version and Platform
Version of your agent? 2.173.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?

If dev.azure.com, what is your organization name? https://dev.azure.com/arup-dds-aus

## What's not working?
Release pipeline fails with this error usually when agent runs over an hour or so doing builds: 

**_"We stopped hearing from agent Hosted Agent. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error"_**

**screenshot:**
![image](https://user-images.githubusercontent.com/2081646/91292678-32d61880-e7da-11ea-9f92-d6db9f931070.png)

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.
[ReleaseLogs_76.zip](https://github.com/microsoft/azure-pipelines-agent/files/5129178/ReleaseLogs_76.zip)

**Comment by mjroghelia** [comment]
For issues with the hosted service, please create a report on [Developer Community](https://developercommunity.visualstudio.com/content/problem/post.html?space=21). You'll want to provide details about the frequency with which you are seeing disconnects and whether it happens consistently on the same builds and jobs.
