### ISSUE TITLE
Installing an agent on a machine which can't resolve hostnames (dns failure) results in a incomprehensible error

### ISSUE THREAD

**Issue by DOMZE** [microsoft/azure-pipelines-agent#3095]
## Agent Version and Platform
VMSS image : Ubuntu 20.04 LTS

## Azure DevOps Type and Version
Using self-hosted agents

## What's not working?
When using the Azure VMSS agents pool, when the agent tries to install the extension on the VMSS, it fails with

Azure Pipelines Extension failed with message: The Extension failed to execute: cannot concatenate 'str' and 'exceptions.IOError' objects

It would be nice to have a better error message so that we can understand what is going on.

## Agent and Worker's Diagnostic Logs
N/A

**Comment by DOMZE** [comment]
Hello @mjroghelia, is this being planned to be corrected?

**Comment by AnnaOpareva** [comment]
Hi @DOMZE , Please open an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) for support with the Azure VMSS agents pool and Azure Pipelines Extensions
