### ISSUE TITLE
Google Chrome is missing from Windows Build Agents

### ISSUE THREAD

**Issue by Alex-Bowman-Aw** [microsoft/azure-pipelines-agent#3098]
## Having issue with YAML?
Please log an issue at [Azure-Pipelines-YAML](https://github.com/Microsoft/azure-pipelines-yaml). Over there we discuss YAML templates, samples for Azure Pipelines, and designs for upcoming YAML features. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.

## Having issue with Tasks?
Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.

## Having issue with software on Hosted Agent?
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.

## Having generic issue with Azure-Pipelines/VSTS/TFS?
Please report it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...

OS of the machine running the agent? OSX/Windows/Linux/...

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com

## What's not working?
Can't find the chrome browser binaries - this has suddenly disappeared in the last couple of days:

checking google...
total 4
drwxr-xr-x 1 VssAdministrator 197121 0 Aug 27 11:48 Cloud SDK
drwxr-xr-x 1 VssAdministrator 197121 0 Aug 27 10:08 CrashReports
drwxr-xr-x 1 VssAdministrator 197121 0 Aug 27 10:08 Policies
drwxr-xr-x 1 VssAdministrator 197121 0 Aug 27 10:08 Temp
drwxr-xr-x 1 VssAdministrator 197121 0 Aug 27 10:08 Update
checking google app folder...
ls: cannot access 'C:\Program Files (x86)\Google\Application': No such file or directory

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by Talha-B** [comment]
Any update on this?

Our build suddenly stopped failing and it is due to this.

**Comment by anatolybolshakov** [comment]
Hi @Alex-Bowman-Aw @Talha-B do you use hosted agent? If so - could you please share also what image do you use?

**Comment by anatolybolshakov** [comment]
@Alex-Bowman-Aw @Talha-B do you have any updates?

**Comment by Talha-B** [comment]
Sorry Anatoly, it's been a few months since I faced the issue. I cannot remember the resolution we came to. It might have been to make use of self-hosted agents instead of hosted.

**Comment by anatolybolshakov** [comment]
@Talha-B @Alex-Bowman-Aw  ok thanks - let me close this at the moment since there's not enough info currently - please let us know if it's still actual for you to reopen it
