### ISSUE TITLE
Azure Pipeline -  predefined variables

### ISSUE THREAD

**Issue by Resserr** [microsoft/azure-pipelines-agent#3100]
Hi to all,
I am trying to set up deployEnvironment name base on 'System.PullRequest.TargetBranch'. But as I know, this variable is runtime variable and I cannot use it in template expressions in "variables" . Also, I have tried to use Build.SourceBranch, but this variable = merge for PR triggers. Can you add new Build variable which I can use in template expressions to determine source/target branch for my PR? It would be really helpfull.

```ansible
variables:
  ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}: 
     ${{ if eq( variables['System.PullRequest.TargetBranch'], 'refs/heads/test')}}:
        deployEnvironment: 'dev'
     ${{ if ne( variables['System.PullRequest.TargetBranch'], 'refs/heads/test')}}:
        deployEnvironment: $(System.PullRequest.TargetBranch)
  ${{ if ne( variables['Build.Reason'], 'PullRequest' ) }}:
    deployEnvironment: 'dev'
```

**Comment by anatolybolshakov** [comment]
Hi @Resserr I assume this would be some enhancement for Azure DevOps and external assemblies which agent is using - could you please create the ticket on [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html) to get the right eyes on it?

**Comment by anatolybolshakov** [comment]
Let me close this once since it doesn't seem to be related to the agent itself - please feel free to ask any further questions!

**Comment by anatolybolshakov** [comment]
@mjroghelia could it make sense to add new variable for it, what do you think? Would it be enhancement on Azure DevOps side?
Currently 'System.PullRequest.TargetBranch' variable is initialized only if build ran because of Git PR affected by a branch policy according to [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml).

**Comment by anatolybolshakov** [comment]
Hey @Resserr this seems to be more related to Azure DevOps - could you please create ticket on https://developercommunity.visualstudio.com/spaces/21/index.html to get right eyes on it? Let me close this one since it doesn't seem to be related to the agent itself.
