### ISSUE TITLE
On-Premises Agent with Proxy (Application Insights)

### ISSUE THREAD

**Issue by fafinsch** [microsoft/azure-pipelines-agent#3104]
## Agent Version and Platform
Version of your agent? 2.165.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
on-premises TFS/Azure DevOps Server

If on-premises, which release? 2019.1

## What's not working?
We are running the agent behind a proxy, which is working ok.
But we noticed that the used "Application Insights" doesn't use the otherwise configured proxy.
It would be great if you could:
- either make the "Application Insights" use the proxy as well
- or even better provide a config-entry to disable "Application Insights" altogether

Many Thanks + Kind Regards
Marco

**Comment by anatolybolshakov** [comment]
Hi @fafinsch this sounds like a feature for Azure DevOps Server itself - could you please create ticket on https://developercommunity.visualstudio.com/spaces/21/index.html to get right eyes on it?
Let me close this one since it's not related to the agent.
