### ISSUE TITLE
linux agent 2.174.2 runs as root and not the correct user due to systemd setup

### ISSUE THREAD

**Issue by scott-doyland-burrows** [microsoft/azure-pipelines-agent#3111]
## Agent Version and Platform
Version of your agent? 2.174.2

OS of the machine running the agent? OSX/Windows/Linux/...
Linux Ubuntu 18.04
Kernel 4.15.0-112

## Azure DevOps Type and Version
on-premises Azure DevOps Server 2019

## What's not working?
I install and configure the agent successfully.  Agents are installed under an ID called "buildadmin"
However when I run
./svc.sh install
it sets the systemd startup for the agent to be run as root.
The file below is generated:
/etc/systemd/system/vsts.agent.devops.docker.Docker\x20Build\x20Agent\x203.service

This has a line like this:
User=

But it should be
User=buildadmin

"buildadmin" is the ID I use for the agents.

Without specifying the correct line in the file, the agents run as root and this causes pipeline errors, such as:
The user's home directory could not be determined. Set the 'DOTNET_CLI_HOME' environment variable to specify the directory to use

If I alter the file to be correct, and then issue "systemctl daemon-reload" and then run "./svc.sh start" then all runs correctly under buildadmin

**Comment by AjKundnani** [comment]
Hello @scott-doyland-burrows - I came across this bug while troubleshooting similar issue with older version of agent.

Request to submit this issue at https://developercommunity.visualstudio.com/ for faster response from community. I've submitted as part of troubleshooting issue I was working on.

**Comment by scott-doyland-burrows** [comment]
OK - reported here as well.
https://developercommunity.visualstudio.com/content/problem/1253088/linux-agent-21742-runs-as-root-and-not-the-correct.html

**Comment by anatolybolshakov** [comment]
Hi @scott-doyland-burrows is this issue still actual for you? Did steps from described in devcom ticket help you to resolve the issue?

**Comment by scott-doyland-burrows** [comment]
Hi,

The ticket linked above says to run "svc.sh" as the buildadmin user (ie non-root).
This will then put the correct ID (buildadmin) in the relevant systemd file.

The MS docs:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops
say to run svc.sh as root.

The MS docs are correct - it is not possible to run svc.sh as "buildadmin" as the svc.sh script needs root authority to manage systemd.

So in effect - the issue is not resolved, the systemd file ends up without the "buildadmin" ID specified as I need to run svc.sh as root. This can be worked around by simply manually updating the systemd file to include the buildadmin user.  This just needs to be documented in the MS docs.

Thanks.

**Comment by sdobrodeev** [comment]
Hi @scott-doyland-burrows. I researched the problem. First, the `svc.sh` script tries to use the its second parameter as the username and if it is absent, as in your case, then the username is taken from the `$SUDO_USER` environment variable which is set by `sudo` command. It seems that this value is empty for you. Could you check this by calling the echo `$SUDO_USER` command? This can be if you do not switch to root using `sudo`, but just log in under root and run the `svc.sh` script. Also calling the script with the username can help you: `./svc.sh install buildadmin`.

**Comment by scott-doyland-burrows** [comment]
Hi,

Thanks - that is the issue, I ssh'd directly in as root using an ssh key (which I know isn't best practice...).

I guess the documentation could be updated to say the ```svc.sh``` script uses the ```$SUDO_USER``` environment variable and/or to say it will take a second parameter as in your example above.

**Comment by sdobrodeev** [comment]
We update the relevant documentation and close the issue. Please let me know if you have any objection.
