### ISSUE TITLE
Cannot trigger "Online" custom build agents using ./svc.sh script

### ISSUE THREAD

**Issue by michellehodges** [microsoft/azure-pipelines-agent#3119]
### **What I need:**
I need to build a custom build agent on an EC2 instance inside of my VPC environment. The instance is Amazon Linux 2, which is just a modified version of RHEL. I'm running this on an Enterprise Azure DevOps account (dev.azure.com). 

**### The problem:**
The ideal build agent would trigger builds on demand from the pipeline, without having to be "activated" by SSH'ing into the box first. My build agents work fine when I run the script ./run.sh, but doesn't register when I run the script ./svc.sh (which is the script that lets it run as a service.) Without running ./svc.sh, I would have to ssh into the box every time I need to run the build to trigger ./run.sh. 

Screenshots of ./svc.sh runs below... 
1. As you can see, the pipeline is waiting for an available agent, even though this agent is now listed as "Online" after starting the service via ./svc.sh

2. This second image shows the box itself, the box is supposedly listening... but nothing happening. 

**### What I've done:**
1. Changed the type of instance to ensure that systemd is available and running
2. Checked the capabilities to make sure they are available 
3. Use different versions of azure devops build agents 
4. Changed various permissions and file ownerships, running things via sudo/user 
5. Installed, uninstalled, start and stop ./svc.sh 
6. Looked at the logs in _diag. It looks like ./svc.sh IS in fact registering and processing the build request, but its not actually running in the Pipeline. I see the job names, stage, etc in the logs, but nothing actually happening in Pipelines.

**Comment by anatolybolshakov** [comment]
Hi @michellehodges looks like images are not attached - could you please attach them?
Could you also share agent logs?

**Comment by anatolybolshakov** [comment]
Hi @michellehodges could you please agent logs?

**Comment by anatolybolshakov** [comment]
Closing this at the moment due to inactivity - please feel free to reopen or ping if it is still actual for you.
