### ISSUE TITLE
Agent docker image

### ISSUE THREAD

**Issue by wertzui** [microsoft/azure-pipelines-agent#3124]
From what I can see in the docs at https://docs.microsoft.com/de-de/azure/devops/pipelines/agents/docker?view=azure-devops#linux you have to create the docker images yourself.
There is also https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent which seems to be deprecated and https://hub.docker.com/r/consultent/azure-pipelines-vsts-agent which looks as if someone tried to provide an up to date docker image.

Why is there no official up to date docker image?

**Comment by guilhem** [comment]
For information, we update `Dockerfile` in documentation to get an argument `AGENT_VERSION`.
I also created a fork which build any new version of the agent:
https://github.com/guilhem/azure-pipelines-agent/commit/14204c4e1f1cd63977223bb961b342308028c8d1
docker registry:
https://github.com/users/guilhem/packages/container/package/azure-pipelines-agent

**Comment by azilber** [comment]
> From what I can see in the docs at https://docs.microsoft.com/de-de/azure/devops/pipelines/agents/docker?view=azure-devops#linux you have to create the docker images yourself. There is also https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent which seems to be deprecated and https://hub.docker.com/r/consultent/azure-pipelines-vsts-agent which looks as if someone tried to provide an up to date docker image.
> 
> Why is there no official up to date docker image?

The company I'm with provides the 2nd link you [posted](https://hub.docker.com/r/consultent/azure-pipelines-vsts-agent).  It doesn't look like Microsoft is ever going to make it easy for us again with those agents.  I hope the images we offer are a help, we currently use them in production for our clients, and they work better than the original Microsoft provided containers, especially the cleanup code we added, where sometimes old agents would remain registered, and wouldn't be able to re-register because Azure still thinks they're registered.

**Comment by wertzui** [comment]
Up

**Comment by wertzui** [comment]
Up

**Comment by wertzui** [comment]
bump

**Comment by geekzter** [comment]
@wertzui We are considering various future options to support container images for Pipeline agents. However, we are unlikely to provide a generic image that covers all scenario's with a single image.

**Comment by nkr0** [comment]
Simplest image to ship just the source can be like this.
```dockerfile
FROM ubuntu:22.04

RUN useradd -m azure
WORKDIR /home/azure
COPY vsts-agent*.tar.gz .
RUN tar -xf vsts-agent*.tar.gz && rm vsts-agent*.tar.gz
RUN ./bin/installdependencies.sh
RUN chown -R azure:azure .
USER azure
```

Users can then build their variations, for e.g., as.
```dockerfile
FROM azp
RUN DEBIAN_FRONTEND="noninteractive" apt install -yq  git iputils-ping unzip zip
COPY start.sh .
ENTRYPOINT ./start.sh
```
