### ISSUE TITLE
Update mingit to 2.28.0

### ISSUE THREAD

**Issue by stuartjsmith** [microsoft/azure-pipelines-agent#3126]
## What's not working?
The version of git is quite outdated now and needs uplifting to 2.28.0 - I have submitted a PR here https://github.com/microsoft/azure-pipelines-agent/pull/3125 but I do not know how to action getting the version of mingit uploaded to the blob storage

**Comment by mjroghelia** [comment]
@stuartjsmith This will roll out with the next agent release, in a week or so.
