### ISSUE TITLE
Branch switching and build results reuse on incremental builds...

### ISSUE THREAD

**Issue by tapika** [microsoft/azure-pipelines-agent#3134]
We have following situation - same work area 
 (For example `C:\azure-devops-agent\_work\22\s`) is being reused by multiple builds and multiple branches.

It's possible that build branch 1 produced it's own build binaries into output folder, 

after that 

there was build branch 2 built, in same output folder. First build attempt copied some assemblies which are not version compatible with build branch 2, but assemblies were not rebuilt because of incremental build. (Project assemblies are up-to-date, and referenced assemblies are not copied anymore)

In theory it's possible to automatically wipe out entire output build directory if branch was changed 
(Using `$(Build.SourceBranchName)` as comparison base)

But then build results cannot be reused.

From my own perspective this is azure devops build agent problem, as it should not reuse same work area for different branch - but theoretically if we are talking about build results reuse - maybe build agent should observe what kind of files
were born during build process and delete them using some magical criteria.

Can you give a proposal what would be the optimal way to handle this kind of problems ?

```
if not exist branch.txt echo $(Build.SourceBranchName) >branch.txt
set /p oldbranch=<branch.txt
if not %oldbranch% == $(Build.SourceBranchName) rmdir /s /q output\*.*
echo $(Build.SourceBranchName) >branch.txt
```

Is this best approach ?

**Comment by mjroghelia** [comment]
You can use the "workspace: clean" [option ](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace) on the job to ensure files from previous jobs are removed went starting a new one, but the agent doesn't provide any other mechanism to selectively decide what to clean based on branch name or other criteria.
