### ISSUE TITLE
NuGet is too old

### ISSUE THREAD

**Issue by RedRiverWeb** [microsoft/azure-pipelines-agent#3140]
Is there a way to use some NuGet version in the self-hosted agent?
The 4.1.0 is quite old and it generates restore errors (incompatible packages for example).

**Comment by mjroghelia** [comment]
You can put whatever nuget you want on a self hosted agent machine and put it in your path. You can also use the [NuGetToolInstallerV1](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/NuGetToolInstallerV1) task to make setting the particular version of nuget part of your build.

**Comment by RedRiverWeb** [comment]
Hi,

On DevOps 2019.1 I cannot set the NuGet exe path just the config and I'm on
an offline machine, so I cannot use the istaller either.
BTW you wrote down a workaround instead of answering my question.
