### ISSUE TITLE
Add --prune-tags option to "Get sources" task

### ISSUE THREAD

**Issue by luber** [microsoft/azure-pipelines-agent#3143]
## Agent Version and Platform
2.175.2 
Windows

## Azure DevOps Type and Version
on-premises Azure DevOps Server 2019: Version Dev17.M153.5

## What's not working?
when an agent is running "Get sources" task from git repo it is executing next command:
`git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --force --tags --prune --progress --no-recurse-submodules origin
`
please add also `--prune-tags` option so this tasks also clean up old unused git tags.

**Comment by jefjef** [comment]
We are currently experiencing an issue that a build server has a tag that no longer exists on the repo.
Having to manually remote into the server to prune the tags is a not-optimal workaround.
