### ISSUE TITLE
Agent can't launch containers on RHEL 7.9 due to old version of docker

### ISSUE THREAD

**Issue by cdunford** [microsoft/azure-pipelines-agent#3145]
## Agent Version and Platform
Version of your agent? 
_Current agent version: '2.175.2'_

OS of the machine running the agent? OSX/Windows/Linux/...
_Red Hat Enterprise Linux Server release 7.9 (Maipo)_

_docker version_
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-162.git64e9980.el7_8.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Mon Jun 22 03:20:20 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-162.git64e9980.el7_8.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Mon Jun 22 03:20:20 2020
 OS/Arch:         linux/amd64
 Experimental:    false
```

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
_dev.azure.com_

## What's not working?
Attempting to use `container`s for jobs, our agents running on RHEL 7.9 fail to `Initialize containers` with the following output:

```
Starting: Initialize containers
/usr/bin/docker version --format '{{.Server.APIVersion}}'
'1.26'
Docker daemon API version: '1.26'
/usr/bin/docker version --format '{{.Client.APIVersion}}'
'1.26'
Docker client API version: '1.26'
##[error]Min required docker engine API server version is '1.35', your docker ('/usr/bin/docker') server version is '1.26'
Finishing: Initialize containers
```

We are using `docker` provided in the official RHEL yum package repositories. Per the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops), RHEL 6, 7 and 8 are supported for agent deployment and there don't appear to be any specific requirements to support RHEL 7.

**Comment by andy-mishechkin** [comment]
Hello, @cdunford 
We are investigating this issue and I hope we can find decision. 
And I also note that Azure DevOps agent installation to RHEL 6/7 is not such simple as it written in documentation and requires some additional components and environment modification (unfortunately, I  have no RHEL7 and I use CentOS7 for investigation). You can find here about details: https://github.com/dotnet/core/blob/main/Documentation/build-and-install-rhel6-prerequisites.md#making-the-libraries-available-for-a-net-core-application
Also RHEL7 official repository contains Git 1.8 version, but Azure DeVops requires Git 2.0 min. version for  working. You can build required Git form source code or using most simple approach: https://computingforgeeks.com/how-to-install-latest-version-of-git-git-2-x-on-centos-7/
Please see details about it here: https://git-scm.com/download/linux
Would you please check the necessary software packages for .NET Core on your RHEL 7 and Git version ?

Thank you

**Comment by andy-mishechkin** [comment]
Hello, @cdunford, once again.
I've tested docker from official docker repository (https://docs.docker.com/engine/install/centos/), and I didn't see any errors, when I've tried to run test hello-world container (see the screenshot).
![image](https://user-images.githubusercontent.com/57713077/114184022-60c93100-9955-11eb-8c02-c4bbd6331444.png)
Also I see that official yum repository now contains docker-moby only (but perhaps it's specific for CentOS only).
Would you please to update your agent and docker first ?
If it will not fix this issue - may you provide definition of your pipeline, where you try to use docker.

Thank you.

**Comment by andy-mishechkin** [comment]
Closed, because no any activity in last 14 days.
@cdunford , please feel free to reopen, if you'll have any updates
