### ISSUE TITLE
Spurious 401 errors in agent listener log during startup

### ISSUE THREAD

**Issue by mjroghelia** [microsoft/azure-pipelines-agent#3149]
When the agent first starts, several parts of the code attempt to communicate with the service in parallel and receive 401s (auth failures) because the call to create the agent session (authentication) hasn't completed yet. This is not a real problem, but it does add spurious errors to the agent listener log. That this is "normal" behavior is confusing and creates distractions for people when investigating other problems. Fix the sequencing of connections to avoid this noise.

**Comment by mjroghelia** [comment]
@anatolybolshakov This would be a good first issue for someone to get up to speed on the agent code and will help with support a lot.

**Comment by anatolybolshakov** [comment]
@mjroghelia ok, thanks 👍

**Comment by max-zaytsev** [comment]
Hi @mjroghelia, I've started looking at this issue and noticed that for different organizations I can see different results in the _diag logs during configuration of the same agent version with the same PAT
The only difference I have found now is that the _default_ pools (where the agents were configured) have _different owners_:

- [v-mazayt]\Project Collection Service Accounts - _in this case, I can see several 401 warnings during configuration_ 
- Microsoft.VisualStudio.Services.TFS - _in this case, I see only 200 responses during configuration_

**Comment by mjroghelia** [comment]
@max-zaytsev Thanks for digging into this. To summarize the situation:

1.)	The 401 is logged from code in the vss-api-netcore lib (shared code from Azure DevOps) not agent code. It is a normal part of the OAuth flow and the logging of the auth error is generic. We can’t disable it for the normal authentication flow without losing it for unexpected authentication failures.

2.)	Whether that 401 happens on retrieving the endpoint metadata (location data) when establishing the connection or on the subsequent call to create the agent session varies based on the owner of the pool. This was news to me, but explains why I don’t always see 3 errors.

Given 1, we wouldn’t want to try to eliminate the logging of this error altogether. I don’t know exactly why 2 varies by owner, but I think we should assume requiring auth on retrieving location data is the correct thing.

It would still be good to eliminate the redundant 401s. With only one 401 followed by the logging about getting the Oath token, it is pretty clear what is happening, but with multiple errors it looks more confusing.

The 3 connections had previously been established serially, but it was switched to parallel about a year ago by one of the devs who works on the hosted pools. #2264

How about we split the difference, and await the first connection before doing the second two in parallel?
