### ISSUE TITLE
yamlgettingstarted-runlocal.md states preview coming soon, but is three years old

### ISSUE THREAD

**Issue by aviita** [microsoft/azure-pipelines-agent#3157]
There is documentation for running yml pipeline in local mode [yamlgettingstarted-runlocal.md](https://github.com/microsoft/azure-pipelines-agent/blob/d504d4ef0e82d34439aa0eb494f218c2d9146a95/docs/preview/yamlgettingstarted-runlocal.md). I would like the status of this piece of documentation clarified since it is tree years old already.

This would be useful feature to have as currently we are doing trial and error fixing pipelines by pushing yml chages to remote (feature branch), which then migh or might not work. Did not try to follow the documentation steps, as it is stated to be only in internal use.

I expect the document could be updated by now to reflect current status better. Surely the preview coming soon is not accurate if it has stayed that way for three years.

**Comment by Steven-Harris** [comment]
I would love this as well. The current process is a time sinkhole.

Here is the prior discussion for documentation purposes  #1764

**Comment by ApolonTorq** [comment]
This is still a reasonable question. It would be incredibly useful to be able to run/test pipeline yaml files locally. This issue should be re-opened as the docs still say preview coming soon.

**Comment by aviita** [comment]
Would still like an explanation to this one e.g. from @ericsciple who has committed the file originally.

I did also make a SO question just in case this would be possible in some more hacky way:
https://stackoverflow.com/questions/71224717/is-it-possible-to-run-azure-devops-self-hosted-agent-locally-against-local-non-c
