### ISSUE TITLE
Latest Agent Version Release

### ISSUE THREAD

**Issue by jeffpatton1971** [microsoft/azure-pipelines-agent#3161]
It would be very convenient if we could have an agent download that is not ONLY a static version number, but perhaps one that is released tagged with -latest. This would allow admins to be able to deploy new self-hosted agents without worrying about grabbing the latest version numbered release, and would simplify the code in our deployments to get https://blabla/vsts-agent-latest

Thanks!

**Comment by PST2** [comment]
Our org has this automated thanks to [the sample PowerShell for running the agent in Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops) which asks the server for the latest download URI and retrieves it:

```
Write-Host "1. Determining matching Azure Pipelines agent..." -ForegroundColor Cyan

$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$(Get-Content ${Env:AZP_TOKEN_FILE})"))
$package = Invoke-RestMethod -Headers @{Authorization=("Basic $base64AuthInfo")} "$(${Env:AZP_URL})/_apis/distributedtask/packages/agent?platform=win-x64&`$top=1"
$packageUrl = $package[0].Value.downloadUrl

Write-Host $packageUrl

Write-Host "2. Downloading and installing Azure Pipelines agent..." -ForegroundColor Cyan

$wc = New-Object System.Net.WebClient
$wc.DownloadFile($packageUrl, "$(Get-Location)\agent.zip")

Expand-Archive -Path "agent.zip" -DestinationPath "\azp\agent"
```
Where AZP_TOKEN_FILE is a PAT and AZP_URL is of the form https://dev.azure.com/org_id

**Comment by anatolybolshakov** [comment]
Hi @jeffpatton1971 it seems to be related to the AzDevOps API, but not the agent itself - could you please create ticket on https://developercommunity.visualstudio.com/spaces/21/index.html to get right eyes on it?

**Comment by anatolybolshakov** [comment]
Let me close this at the moment since it's not related to the agent itself.
