### ISSUE TITLE
TFS 2015 agent on Mac OSX Catalina 10.15 (.Net 5)

### ISSUE THREAD

**Issue by cm5778** [microsoft/azure-pipelines-agent#3169]
I am trying to configure agent for TFS 2015 on Mac OSX Catalina 10.15.7 
while using latest VSTS agent version 2.177.1 or pre-release I am getting "VS30063 : You are not authorized to access http://tfs:8080"
For older agent version 2.112.0 facing "System.DllNotFoundException": Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.

I have tried different solution from online but none of them working.

Help in this regard is very much appreciated

**Comment by anatolybolshakov** [comment]
Hi @cm5778 could you please check that you use actual PAT for your agent?

**Comment by anatolybolshakov** [comment]
Hi @cm5778 do you have any updates?

**Comment by anatolybolshakov** [comment]
@cm5778 I'm closing it at the moment due to inactivity, please feel free to reopen it if it's still actual for you.
