### ISSUE TITLE
[Question] Azure Pipeline Agent support for Apple M1

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/azure-pipelines-agent#3184]
Is there going to be a published release for the Azure Pipeline Agent on the Apple M1 (published as [osx-arm64](https://github.com/dotnet/runtime/blob/66a1f9754a89c86a3893dcf82285018c72f8be16/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json#L1657)) or is it expected to use the osx-x64 package on the machines running as emulated.

This would require the project to be updated to use .NET 6.0

**Comment by luigisaggese** [comment]
Any news on this topic?

**Comment by anatolybolshakov** [comment]
Hi @WardenGnaw @luigisaggese currently we have no plans to officially support it in the near time.

**Comment by sabareeshkkanan** [comment]
Well apple is rapidly moving all their products to apple silicon , it will be great if we can bump up priority on this.

**Comment by metaine** [comment]
Can we use our own Apple Silicon machine as self-hosted agent?

**Comment by nekrich** [comment]
Is there any news on this topic?
We have to put `arch -arm64` everywhere in our scripts when we want to make builds on Apple Silicon.

**Comment by anatolybolshakov** [comment]
Hi everyone, we have a plans to gradually migrate to the latest Net core version, but it could require some time - will keep you posted.

**Comment by CRamsan** [comment]
Is there any update on the timeline for arm64 support?

**Comment by BastianZim** [comment]
With the release of the new MacBook Pros, I was wondering if there are any news here?

**Comment by BastianZim** [comment]
Not stale

**Comment by mohammad-yousuf** [comment]
> Is there any update on the timeline for arm64 support?

any updates?

**Comment by fcancela** [comment]
Hey! Could you please provide some updates? 

Based on this comment I understand there is a WA: 

> Is there any news on this topic? We have to put `arch -arm64` everywhere in our scripts when we want to make builds on Apple Silicon.

Is it possible to build with arm64 architecture from the current existing macOS VMs available?

Thanks in advance!

**Comment by theolivenbaum** [comment]
Anything Microsoft?

**Comment by simonbuerger** [comment]
Unclear why they didn't post or mention this issue from there, but https://github.com/microsoft/azure-pipelines-agent/issues/3922 seems to be in progress to address this?

**Comment by alanwilter** [comment]
Any news please?

**Comment by neoswallow** [comment]
I have not tried it myself but they did release a pre-release version.
[3.214.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.214.0)
It was just that 1 release but it looks like the work is in progress.

**Comment by Soap-141** [comment]
Any updates?

**Comment by kirill-ivlev** [comment]
Hi @WardenGnaw,
Now we support macOS arm-64, you can download it from the release page.
Please let us know if you have any additional questions.

**Comment by badsyntax** [comment]
@kirill-ivlev thanks! i've installed it on our mac mini build agent and it works without problems.

will you be updating the following documentation at some point?:

- README
- Release notes "After Download:" instructions for macos
- Download arm64 for macos from "New Agent" screen in devops

**Comment by luciansmith** [comment]
I had been following this because I thought an M1 virtual machine would eventually be added to https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml  However, that page doesn't say anything about arm64 vs. not; is there a way to get one architecture over another from the YML file?  Should I request a VM for arm64 on a different issue tracker?  Thank you!

**Comment by alecglen** [comment]
@luciansmith did you figure out how to reference it in yml?

**Comment by luciansmith** [comment]
@alecglen I have not!  Thus far I am still building for M1 architectures by hand, which is not ideal.

**Comment by aykevl** [comment]
@luciansmith you do this by specifying `runs-on: macos-14`. That version is the new M1 runner. [From here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) (though it's not explained clearly in that link).

**Comment by luciansmith** [comment]
Looks like Azure doesn't have macos-14 yet; it's still at 'macOS-13', cf https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml  Thanks for the pointer!

**Comment by EstopaceMA** [comment]
any updates on this?, did someone already setup an agent on M1 machine?

**Comment by luciansmith** [comment]
That same link ( https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml ) now lists both macos-14 and macos-15, so presumably the answer is that now everyone finally has arm64 support.  The reverse will probably not be true for that long--as soon as macos-13 drops off the list, nobody will have support for x86 any more.

**Comment by jaimergp** [comment]
I wouldn't count on that. There're both a [`macos-15`](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md) and a [`macos-15-arm64`](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md) README.
