### ISSUE TITLE
[Question] Unclear what "Perform an unzip for tasks for each step." does

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/azure-pipelines-agent#3185]
## Agent Version and Platform
Version of your agent? 2.177.1
OS of the machine running the agent? win-x64

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

## What's not working?
When running `config.cmd` it asks `Perform an unzip for tasks for each step.` but there is no documentation on what that means.

What are the implications, pros, cons?

I found these two relevant PRs https://github.com/microsoft/azure-pipelines-agent/pull/3177 and https://github.com/microsoft/azure-pipelines-agent/pull/3065 but they do not have a description.

**Comment by jaygeek** [comment]
```
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.179.0             |_|          (commit bd605d6)


>> Connect:

Connecting to server ...

>> Register Agent:

Scanning for tool capabilities.
Connecting to the server.

Enter deployment group tags for agent? (Y/N) (press enter for N) >

Testing agent connection.
Enter Perform an unzip for tasks for each step. (press enter for N) >

```

**We are all waiting at this prompt until you tell us what happens next.**

**Comment by slacasse22** [comment]
I went for the default for the moment but I'm curious too!

**Comment by avivanoff** [comment]
Same here.

**Comment by anatolybolshakov** [comment]
Hi everyone, this is an option for additional security restrictions.
The main idea is that a malicious script could impact the contents of the unzipped task. By unzipping it each time, some customers believe they’re in a more secure state.
Since this is not a wide used option - we are planning to make it as command-line only flag instead of prompting this during agent configuration and update related documentation also.

**Comment by mtenrero** [comment]
@anatolybolshakov  There's a problem with unnatended installations, this new param, doesn't allow the agent to be installed silently. It always asks for a answer, Is there any new param in order to force via CLI?

**Comment by anatolybolshakov** [comment]
@mtenrero yes, you can use --AlwaysExtractTask command-line parameter to set it up

**Comment by yuanb** [comment]
So, should I answer Y or N? I am still confused what it does, and what's the implication on chonices.

Thanks

> Hi everyone, this is an option for additional security restrictions.
> The main idea is that a malicious script could impact the contents of the unzipped task. By unzipping it each time, some customers believe they’re in a more secure state.
> Since this is not a wide used option - we are planning to make it as command-line only flag instead of prompting this during agent configuration and update related documentation also.

**Comment by anatolybolshakov** [comment]
@yuanb Since enabling this options increases pipeline execution time, and it's necessary mostly for specific cases - I would suggest to leave default value - i.e. N

**Comment by tolgabalci** [comment]
My issue is the broken English/Explanation behind the prompt. Based on the discussion here the options seems to have a good purpose but it's difficult to understand what exactly is being asked in the prompt. 

> Enter Perform an unzip for tasks for each step. (press enter for N)

Why is the word "Enter" in front of the quest? I guess the user prompt mechanism always adds Enter to the beginning of the question.  But the question itself should take that in to consideration.  "Enter User account to use for the service" for example reads just fine.  So maybe change the prompt to "Enter Y to perform an unzip for task for each step. (press enter for N)

Second, why does it say "for each step".  I ran the config just once.  Why are there multiple steps.  Maybe I'm misunderstanding the inner working here, but I've been setting up agents for years now and never been confused about it until now.  To me there is only one step.  I download, extract and run config.  What are the multiple steps being implied here?

**Comment by lachlann562** [comment]
while AlwaysExtractTask sets it to Y, it doesn't seem like there is a similar switch to force it to no on the CLI, thats frustrating.

**Comment by beugnen** [comment]
Hi all,

I found the documentation which backs up what **anatolybolshakov** is saying:

_When the agent runs a job, it first downloads all the task bundles required by the job's steps. Normally, for performance, it unzips the tasks once per job even if the task is used in multiple steps. If you have concerns about untrusted code altering the unzipped contents, you can trade away a little bit of performance by having the agent unzip the task on each usage._  [Tell me more...](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-174-update#unzip-task-bundles-for-each-step)

**Comment by anatolybolshakov** [comment]
Hi everyone! We rolled out related changes - so this option should not appear during agent configuration as rarely used - please let us know if you have any other questions.
