### ISSUE TITLE
Node version changed for container job?

### ISSUE THREAD

**Issue by ihnorton** [microsoft/azure-pipelines-agent#3188]
We have a [container job](https://github.com/TileDB-Inc/TileDB/blob/dev/azure-pipelines.yml#L71-L79) running inside a CentOS5 container (manylinux1) which was working correctly until Tuesday (8 December), and now [fails](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=7938&view=logs&j=e29b7258-d60a-5387-7d85-9314f2aa9fb0) with this error when starting the first task:
```
/__a/externals/node10/bin/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.10' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.3' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /__a/externals/node10/bin/node)
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1001 dccde58c918cc5f5aacf3d071bc41a6c3aa1c44c0486b57d81414467e5fa466b /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
```

I have tried older tags of the [container](https://quay.io/repository/pypa/manylinux1_x86_64?tab=tags), which show the same problem, so I believe the issue is that something about the default node runner has changed (either the version or the build).

I see some discussion in https://github.com/microsoft/azure-pipelines-agent/issues/3042 which might match this timeline. I've tried setting `AGENT_USE_NODE10: false` in the job variables, but no change.

**Comment by ihnorton** [comment]
Note that the launch script in the snippet above _seems_ to be passing what I believe is supposed to be the "old" (Node 6?) version `/__a/externals/node/bin/node`, but the errors above indicate the actual binary that the entry script is running under is `/__a/externals/node10/bin/node`. This leads me to think the default changed. If there is a way to tell the pipeline to run this container job with whatever node version was used on Tuesday (see [last passing build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=7885&view=results)), then that would be very helpful.

**Comment by ihnorton** [comment]
This error appears to have been present in actions container runners for a while now: https://github.com/microsoft/azure-pipelines-agent/issues/3188

**Comment by mjroghelia** [comment]
@alexander-smolyakov @ihnorton CentOS 5 is not a supported platform. CentOS 6 is the oldest version Pipelines has ever supported officially. You will need to update your build to use a CentOS 6 based container. Another option would be to fork the bash task from before it was updated to Node 10 and install it in your account as a custom task.

**Comment by alexander-smolyakov** [comment]
@ihnorton, I found a related [ticket](https://github.com/Z3Prover/z3/issues/4784) for this issue, it seems you can use a `quay.io/pypa/manylinux2010_x86_64:latest` image to work around this issue. I tested it and on this image, the current version of the bash task works as expected in the container.

>> Another option would be to fork the bash task from before it was updated to Node 10 and install it in your account as a custom task.

In addition to this if you would like to fork the bash task you need to use any version before 3.179.0 since starting from this version the task executed via Node 10 handler.

**Comment by ihnorton** [comment]
Hmm, ok. Thanks for the explanation.
