### ISSUE TITLE
Linux dependency installer fails for lttng-ust dependency.

### ISSUE THREAD

**Issue by matthewhembree** [microsoft/azure-pipelines-agent#3190]
## Agent Version and Platform
Version of your agent? 2.179.0

OS of the machine running the agent? CentOS 8

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? n/a

If on-premises, which release? n/a

If dev.azure.com, what is your organization name? n/a

## What's not working?

Agent fails to pull the repo file at https://packages.efficios.com/repo.files/EfficiOS-RHEL7-x86-64.repo . This will fail for agent OSes that require [this step](https://github.com/microsoft/azure-pipelines-agent/blob/556085a6a3aa97b79fc4317748091575aa9cef44/src/Misc/layoutbin/installdependencies.sh#L198). You should investigate how to mitigate any possible unreliability with this package source.

My particular agent will run on CentOS 8, which has the package `lttng-ust` as part of the CentOS/RHEL distro's AppStream repo. It appears that you're not making the distinction for CentOS/RHEL "8" in `installdependencies.sh`. Using the distro's `lttng-ust` will mitigate this issue for CentOS/RHEL "8"

This will likely affect other RHEL based distros (e.g. Amazon Linux). edit: `installdependencies.sh` doesn't/fails to run on AL2.

Error messages:
```
'lttng-ust' installation failed with exit code '0'
Can't install dotnet core dependencies.
failed: Connection timed out.
Connecting to packages.efficios.com (packages.efficios.com)|2607:5300:203:5aae::ef3d|:443... failed: Network is unreachable.
You can manually install all required dependencies based on following documentation
https://docs.microsoft.com/en-us/dotnet/core/dependencies?pivots=os-linux&tabs=netcore31
```

**Comment by sdobrodeev** [comment]
Hi @matthewhembree this problem is still actual to you? It looks like a temporary network problem with the repository server.

**Comment by matthewhembree** [comment]
> Hi @matthewhembree this problem is still actual to you? It looks like a temporary network problem with the repository server.

@sdobrodeev This is working now, but my concern shifted to being unable to deploy agents when that server is unavailable. Is there a way to mirror that dependency under Microsoft?

**Comment by sdobrodeev** [comment]
@matthewhembree Unfortunately, we can't provide mirror for CentOS and other internet resources due to maintenance concerns.
