### ISSUE TITLE
Unable to configure a self-hosted agent

### ISSUE THREAD

**Issue by PaulaPaltinisanu** [microsoft/azure-pipelines-agent#3192]
Hello,

I am currently attempting to configure a self-hosted agent in Azure DevOps on a Windows 10 (x64) machine.
After I enter the PAT, an **SSL error** is prompted and I can no longer continue the process for setting-up my agent.
![48746-image](https://user-images.githubusercontent.com/76150523/102457007-bac28580-404a-11eb-959d-c419d9083e7f.png)

I have attempted to run the config.cmd script with the --sslskipcertvalidation parameter, but I getting the same result.

Please find the picture below and the attached logs.

Thank you!
[agent-20201216-151547-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/5707656/agent-20201216-151547-utc.log)

**Comment by alexander-smolyakov** [comment]
Hi @PaulaPaltinisanu, could you please check if your software meets the pipeline agent [prerequisites](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#check-prerequisites)?

**Comment by PaulaPaltinisanu** [comment]
Hello @alexander-smolyakov,
 I have reviewed my current setup and I can confirm it meets all the requirements. 
I had agents configured on this machine in the past, but starting a certain version for agents, I started receiving the SSL error.

Thank you!

**Comment by PaulaPaltinisanu** [comment]
Hello @alexander-smolyakov,

It turned out this issue was proxy-related; running the **config.cmd** using this command (_.\config.cmd --proxyurl PROXY:PORT_) has proved to solve my issue.

I will close this issue; thank you!
