### ISSUE TITLE
Adjust AZP_AGENT_DOWNLOAD_TIMEOUT to maximum agent zip download size

### ISSUE THREAD

**Issue by japj** [microsoft/azure-pipelines-agent#3197]
## Agent Version and Platform
Version of your agent? 2.153.1

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
Azure DevOps Server 2020

## What's not working?
Upgrade agents to 2.175.2 fails due to download timeouts

It seems that when AZP_AGENT_DOWNLOAD_TIMEOUT was introduced in https://github.com/microsoft/azure-pipelines-agent/pull/2183 , the default timeout was set to 15 due to 
```
// Allow a 15-minute package download timeout, which is good enough to update the agent from a 1 Mbit/s ADSL connection.`
```

Unfortunately, it seems vsts-agent-win-x64-2.175.2.zip (which AzureDevOps 2020 Server wants to upgrade to) has a size of 170.843.551 bytes, which would require ~22 minutes to download.

It would be good if the default download timeout has enough room to succeed the download (although I understand it can be difficult to "predict" the size of the agent zip upfront).

**Comment by anatolybolshakov** [comment]
Hi @japj thanks for reporting this - we made a fix and will roll it out soon, will let you know once it's available.

**Comment by anatolybolshakov** [comment]
Hi @japj we have rolled out the fix for this issue - please let us know if you have any other issues.
