### ISSUE TITLE
 issue with added ability to suppress the error form unshelve command during getSource #3064

### ISSUE THREAD

**Issue by karambawow** [microsoft/azure-pipelines-agent#3198]
added ability to suppress the error form unshelve command during getSource #3064

with this change the get sources Tasks does not break the Build if the Configured Branch in the Builddefinition and in the shelveset does not match!

this is a security issue because the Build will checkin this shelvset without checking out and testing

**Comment by karambawow** [comment]
HI, any news on this Topic because we stay on a Big Company on Version 2.153.1 and cant upgrade

**Comment by MarRich1** [comment]
Any new here?
We are blocked because of that

**Comment by anatolybolshakov** [comment]
Hi @karambawow @MarRich1 let me take a look at this issue

**Comment by egor-bryzgalov** [comment]
Hi @karambawow @MarRich1

Could you please provide us with some more details about your use case to allow us to investigate it further? Current behavior was chosen to resolve the issue described in ticket #1087.

**Comment by karambawow** [comment]
@egor-bryzgalov 
we use this "Bug" as a feature to prevent a GC from checkin shelvesets without appropriate maping and testing  the changes
would it be possible to add a switch to turn on/off this behavior ?

**Comment by egor-bryzgalov** [comment]
@karambawow 
Thank you for the response. I think that we can implement the switch.

**Comment by anatolybolshakov** [comment]
Hi @karambawow @MarRich1 we rolled out the fix for this issue - closing this at the moment, please let us know if you have further questions.
