### ISSUE TITLE
Publish test results fail with  ##[warning]Failed to publish test results: Cannot access a disposed object. Object name: 'TestManagementHttpClient'.

### ISSUE THREAD

**Issue by karambawow** [microsoft/azure-pipelines-agent#3199]
old Agent Version 2.153
new Agent Version 2.175
OS: Windows Server 2019
Azure DevOps Server Version Dev17.M153.5

we have following scenario
execution of multiple Mstest on the Build Agent 
and after every Mstest Call we run 

##vso[results.publish type=VsTest;mergeResults=false;publishRunAttachments=true;resultFiles=foo.trx;]

so the Agent handles the upload of the trx file to the DevOps Server with PAT 

with Agent Version 2.153 this worked well
with Agent Version 2.175 we get this Kind of Warnings in the Build

##[warning]Failed to publish test results: A task was canceled.
##[warning]Failed to publish test results: Cannot access a disposed object.
Object name: 'TestManagementHttpClient'.

it looks like that the new vsts Agent can not handle this requests Multithreaded anymore

**Comment by karambawow** [comment]
HI, any news on this Topic because we stay on a Big Company on Version 2.153.1 and cant upgrade

**Comment by MarRich1** [comment]
Any new here?
We are blocked because of that

**Comment by egor-bryzgalov** [comment]
Hi @karambawow @MarRich1 

Thank you for opening the issue. Could you please provide us with an agent and pipeline logs in debug mode so we can investigate it further.
Is it appropriate for you to use the PublishTestResults task to upload these files? It allows uploading multiple files at once 
in a convenient way.

**Comment by karambawow** [comment]
Hi @egor-bryzgalov 
this topic can be closed we focus on PublishTestResults sporadically fails to publish all results #3219 from @thomasdgx
