### ISSUE TITLE
Failed to create agent pool with Azure Scale Set

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/azure-pipelines-agent#3202]
The [Azure virtual machine scale set agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops) guide appears broken.

I've followed the steps twice and I keep getting the same error:

> The handler for VM extension type 'Microsoft.VisualStudio.Services.TeamServicesAgentLinux' has reported terminal failure for VM extension 'Microsoft.Azure.DevOps.Pipelines.Agent' with error message: '[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.0/AzureRM.py [stdout] [stderr] Running scope as unit: Microsoft.VisualStudio.Services.TeamServicesAgentLinux_1.21.0.0_528a8cc3-1e3a-455f-9b8b-a84985423559.scope [0;1;31mFailed to execute: No such file or directory[0m '. 'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot'

![image](https://user-images.githubusercontent.com/22350/103573792-b1774c80-4e83-11eb-8a0e-704f408ae6dc.png)

DevOps appears successful at scaling up the VM instances... but the agents never show up:

![image](https://user-images.githubusercontent.com/22350/103573881-d8358300-4e83-11eb-8ced-f75808f83b48.png)

**Comment by joaomoreno** [comment]
Found the issue: I was creating the scale set using the `Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest` image. Using `UbuntuLTS` made it work.

I suggest documenting this better and making the tool output a better error message.

**Comment by litan1106** [comment]
Same issue on my end when I was using custom image based on Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest

**Comment by khauser** [comment]
@joaomoreno: Could you write the complete offer you are using?

**Comment by joaomoreno** [comment]
Hm not sure what the full name is. Just using `UbuntuLTS` made it work.

**Comment by litan1106** [comment]
@khauser I was building custom Ubuntu LTS image via this offer.

![image](https://user-images.githubusercontent.com/1310539/104031775-0962cb80-5182-11eb-8db2-7ef10223d69c.png)

I encountered this error with Azure DevOps Scale Set Agent.

`
The handler for VM extension type 'Microsoft.VisualStudio.Services.TeamServicesAgentLinux' has reported terminal failure for VM extension 'Microsoft.Azure.DevOps.Pipelines.Agent' with error message: '[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.0/AzureRM.py [stdout] [stderr] Running scope as unit: Microsoft.VisualStudio.Services.TeamServicesAgentLinux_1.21.0.0_755a8c88-c937-4541-aec6-34899abc0358.scope [0;1;31mFailed to execute: No such file or directory[0m '. 'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot'
`

https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json

**Comment by litan1106** [comment]
@khauser it could be related to the devops agent with python 3 issue. https://github.com/microsoft/azure-pipelines-agent/issues/3156

**Comment by khauser** [comment]
@litan1106 Yeah, you're right. We will try with:

```
apt-get remove -y python-is-python3
apt-get install -y python-is-python2
```

**Comment by litan1106** [comment]
@khauser yes, but it's not the best when Python 2.7 already end of life. 

I hope the Microsoft team updates the Azure Pipeline agent to support python 3. (it's not the best solution to use python 2.7 because it's end of life...)

![image](https://user-images.githubusercontent.com/1310539/104339083-0af70100-54ac-11eb-833b-139e42f06f8f.png)
