### ISSUE TITLE
Pipeline hangs on publish of angular solution after upgrade to .net5.0

### ISSUE THREAD

**Issue by ojpbay** [microsoft/azure-pipelines-agent#3203]
Have recently updated by solution to .net5.0 and since then both YAML and classic pipelines fail at the dotnetcore publish task. They get stuck at the following point and the task then times out after 60 mins.

Task YAML
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

![image](https://user-images.githubusercontent.com/1391064/103875880-dd384380-50ca-11eb-9412-d4583e6dac72.png)

Consistently the last message appearing in the logs as follows:

ΓêÜ Browser application bundle generation complete.
  - Generating index html...
  ΓêÜ Index html generation complete.
  
  Initial Chunk Files               | Names     |      Size
  main.2603e7f3514f87dc9296.js      | main      |   1.29 MB
  styles.b3eb9fa204d9b2190d72.css   | styles    | 239.87 kB
  polyfills.9c3a7aa8354523970243.js | polyfills |  36.39 kB
  runtime.0e49e2b53282f40c8925.js   | runtime   |   1.45 kB
  
  1 unchanged chunks
  
  Build at: 2021-01-07T09:23:02.576Z - Hash: 61b76784a2510e3274f5 - Time: 52871ms

**Comment by ojpbay** [comment]
Issue was caused by package issue & was repeatable locally hence not related to pipelines.

**Comment by brentarias** [comment]
I seem to have the same issue.  My publish to the Azure Container Registry resulted in a "hang" here:
```
  ΓêÜ Browser application bundle generation complete.
  ΓêÜ Browser application bundle generation complete.
  - Copying assets...
  ΓêÜ Copying assets complete.
  - Generating index html...
  ```
It turns out this had something to do with being on my company's VPN.  Simply jumping off the VPN was sufficient for the publish process to work again.  Also, another staff-member had the same problem...and he too solved it by jumping off from the same VPN I was using.
