### ISSUE TITLE
Get Sources (TFVC) should support WorkspaceOptions.SetFileTimeToCheckin setting

### ISSUE THREAD

**Issue by thomasdgx** [microsoft/azure-pipelines-agent#3212]
## Agent Version and Platform
Any

## What's not working?
TFVC workspaces support to preserve the timestamps of files. Here the workspace timestamp is set to the time which is within source control. This option has to be set before calling SyncSources.

### Internally the tf vc workspace tool is called which supports the setting already.

See the **/filetime** option:
```
tf vc workspace /new [/noprompt] [/template:workspacename[;workspaceowner]]
[/computer:computername] [/comment:("comment"|@commentfile)]
[workspacename[;workspaceowner]]
[/collection:TeamProjectCollectionUrl]
[/permission:(Private|PublicLimited|Public)]
[/location:(local|server)]
[/filetime:(current|checkin)]
[/login:username,[password]]
```

### Need for both flavours:
- "Current" is useful, because Msbuild incremental build mechanisms rely on timestamps. If we default to "checkin", then the incremental build will be broken!
- "Checkin" is nonetheless helpful (if used in clean builds). In our case we have plenty of files (which are not compile results) and these get part of an MSI installer. We create incremental updates and here we don't like to transfer files, which are not changed at all. If the timestamp is the original one then the checksum of the file is the same and the file gets excluded from the update package, thus the update gets smaller (this is MSI behaviour).

## Proposal
Please add an option to keep the timestamps within the Get Sources task.

I recommend to add a variable "build.tfvc.usefiletimecheckin". If its true then filetime is set to "checkin". The default filetime remains "current". This way we opt-in and do not change existing behaviour.

**Comment by arpanshah78** [comment]
@thomasdgx I support your proposal. I ran across the same issue today and want the same feature.

**Comment by siprbaum** [comment]
This would be usefull for our usecase, too!

**Comment by anatolybolshakov** [comment]
Hi @thomasdgx thanks for reporting! Let us take a look
