### ISSUE TITLE
Variable Build.BuildNumber should not be readonly

### ISSUE THREAD

**Issue by echalone** [microsoft/azure-pipelines-agent#3217]
Since readonly pipeline variables were introduced, Build.BuildNumber is one of them. However, that buildnumber is something we want to change during build because there's no official way to change it from the default generated one when starting a build. So what we do is, we change the Build.BuildNumber variable during build to the desired number. This works perfectly fine with old agents without readonly variables, but wouldn't be possible with the new agents and would be kinda catastrophic for us.

**Comment by anatolybolshakov** [comment]
Hi @echalone could you describe your case in more details - why do you need to change it? As I see Build.BuildNumber is intended to be readonly value.

**Comment by echalone** [comment]
We have one pipeline for our all our builds (we can't make a new pipeline for every new version because of space constraints, we got a ~30 GB repository that would need to be checked out for every pipeline, not possible) and are building all our versions 1 and 2 and 3 etc. of our software with this build. Here's the issue:
If you enter for example 3.5.1.$(rev:r) for the build number in the options tab, then how should we be able to build for example a version 2.3.8 if we want to (by building another branch)? We would need to EDIT the build pipeline to change the build number, which ain't an option (people who start the build do not have the permission to edit the pipeline). I currently do this by simply setting the Build.BuildNumber variable and that works just fine. I've even written a script that will count up your revision from the last version number you build for that specific branch and will set this as the new build number. Works perfect. So why on earth are we not able to change the BuildNumber for a build? Of course you'll need that... you can't just have one build-number for a build.

**Comment by hangar18rip** [comment]
Hello,
Here is a log command to do that : 
https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#updatebuildnumber-override-the-automatically-generated-build-number
Run it from an inline script and you're done ;)

Have tried it once or twice a few years ago

**Comment by anatolybolshakov** [comment]
Thanks @hangar18rip!
@echalone does this build command work for you?

**Comment by echalone** [comment]
I didn't have time yet to test it, thanks @hangar18rip for the tip at least, I'll try it out as soon as I find some time for that, might be a few weeks ^^

**Comment by anatolybolshakov** [comment]
@echalone thanks! If you will have any further issues with it - could you please create ticket on https://developercommunity.visualstudio.com/spaces/21/index.html to get right eyes on it?

**Comment by echalone** [comment]
Thanks again @hangar18rip for the tip, but it looks like I already use that ^^ You're right, this command will not throw that error. But the thing is, it will update the Build-Number, but only with the next buildstep, not immediately. My workaround at the moment is, that I'm manually setting the Build_BuildNumber environment variable and then I'm using this command to be on the correct side of doing it too. It would be better if the build.updatebuildnumber command will update the build number immediately, simply by updating the environment variable immediatly.

**Comment by hangar18rip** [comment]
I don't know what your are doing exactly but maybe you should have a dedicated task to define your custom build number and in the other ones use the good old build number env var. I would do it this way in my pipelines, some kind of separation of concern

**Comment by echalone** [comment]
Hey, thanks, I already use a dedicated task for that but I also want to check at the end of the step if the correct build number was set. So currently I'm just doing both, first setting the enviornment variable, then checking if it was set correctly by reading the environment variable (yeah, I'm one of those "let's make extra sure" guys xD) and then using the build.updatebuildnumber to set the build variable in a way that's conform with Microsoft's idea of how to do it, all in one buildstep. So it's more of a nice-to-have if the build.updatebuildnumber command would also immediately update the environment variable.
