### ISSUE TITLE
Pipeline status banners not working for azure-pipelines-agent

### ISSUE THREAD

**Issue by NenoLoje** [microsoft/azure-pipelines-agent#3224]
In the README.md, all **Azure Pipelines** badges show "unkown":

![grafik](https://user-images.githubusercontent.com/13981145/105968779-cc566e80-6087-11eb-87d7-ea8a2826cc35.png)

**Comment by DaniilShmelev** [comment]
Good catch, thanks for spotting this. Fixed it in [this PR](https://github.com/microsoft/azure-pipelines-agent/pull/3226)
