### ISSUE TITLE
Agent shouldn't store PSModulePath as a capability

### ISSUE THREAD

**Issue by simonsabin** [microsoft/azure-pipelines-agent#3228]
## Agent Version and Platform
Version of your agent? '2.181.0'

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com/sabinio

## What's not working?
During capability scanning the agent was picking up that the psmodulepath was set to C:\Program Files\Microsoft Monitoring Agent\Agent\powershell. Because this was set the default powershell behaviour of adding the machine module path wasn't working and thus no modules could be found.

Not really sure why all the environment variables at startup are stored and they overwrite anything at startup. PSModulepath might be a special case. 

Troubleshooting this was really hard as there is nothing in the log that says the agent is overwriting all the environment variables with what is defined in the capabilities.

**Comment by anatolybolshakov** [comment]
Hi @simonsabin thanks for contribution! Related changes have already been rolled out - I'm closing this at the moment, please let us know if you have any other issues.
