### ISSUE TITLE
Wrong diagnostic for ##VSO DECODE_PERCENTS

### ISSUE THREAD

**Issue by fbrosseau** [microsoft/azure-pipelines-agent#3235]
Hello

Following pipeline wrongfully gets tagged for the DECODE_PERCENTS breaking change, but it does not make any use of the ##VSO commands.

```
steps:
- checkout: none
- task: PowerShell@2
  inputs:
    targetType: inline
    script: write-host "%"
```

Actual output:

```
Starting: PowerShell
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.180.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
Generating script.
##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
========================== Starting Command Output ===========================
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/47a4cfd4-e7bd-4cbb-8052-5dcc793deb61.ps1'
%
Finishing: PowerShell

**Comment by fbrosseau** [comment]
@max-zaytsev I believe this would be a bug.
@damccorm Thoughts? (Tagging because you appear to have been the primary committer for these changes)

**Comment by damccorm** [comment]
Hey @fbrosseau thanks for calling this out - I think this is actually sort of right that its spitting out errors, the task itself is setting variables with %25. With that said, we've gotten a lot of false positives from this change where %25 is actually a valid thing that people don't want unescaped. I put up https://github.com/microsoft/azure-pipelines-agent/pull/3241 which should fix the issue

**Comment by fbrosseau** [comment]
Thanks @damccorm for confirming.

BTW, will this open the door to being able to output multiline errors/warnings? That'd be really great and we would have multiple usecases for it.

**Comment by damccorm** [comment]
Hey @fbrosseau - this would not be related to that. Offhand I'm not sure how we format those, but we do already handle unescaping new line characters (which should be written as %0A) - again, I'm not sure how we format those in our output offhand though. If there's an issue with those, you should file a separate issue for that though, I'd prefer to keep this one focused on the %25 issue

**Comment by EzzhevNikita** [comment]
An agent with the fix for this issue has been deployed. Now closing this item, feel free to reopen it if it still actual for you.
