### ISSUE TITLE
Install lttng-ust Causes CentOS 7 Ansible Hang due to Prompt

### ISSUE THREAD

**Issue by exwindchiller** [microsoft/azure-pipelines-agent#3238]
https://github.com/microsoft/azure-pipelines-agent/blob/862c5c039f7b0711af46746512705e57bfee738e/src/Misc/layoutbin/installdependencies.sh#L198

When running from Ansible script, 'yum updateinfo' is prompting, which causes script to hang.

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: d36uatko69830t.cloudfront.net
 * extras: d36uatko69830t.cloudfront.net
 * updates: d36uatko69830t.cloudfront.net
EfficiOS-RHEL7-x86-64/signature                                                                                      |  833 B  00:00:00
Retrieving key from https://packages.efficios.com/rhel/repo.key
Importing GPG key 0xAF8437FD:
 Userid     : "RHEL Packages"
 Fingerprint: 2e70 b282 8732 2ab0 5343 9445 48ac fbc2 af84 37fd
 From       : https://packages.efficios.com/rhel/repo.key
**Is this ok [y/N]:**

**Comment by anatolybolshakov** [comment]
@exwindchiller thanks for reporting this! We merged the fix, and will let you know once it will be rolled out.

**Comment by anatolybolshakov** [comment]
Hi @exwindchiller we have rolled out related changes - I'm closing this at the moment, please let us know if you have any other issues.
