### ISSUE TITLE
Feature request: allow to set MTU manually

### ISSUE THREAD

**Issue by hez2010** [microsoft/azure-pipelines-agent#3243]
If azure pipelines agent running on k8s, in docker in docker scenario we need to set MTU value, otherwise the container in docker will face networking issues:

https://github.com/microsoft/azure-pipelines-agent/blob/9fecae130bc731a28e53ef0d8d5c630ebbb7229e/src/Agent.Worker/Container/DockerCommandManager.cs#L232

MTU value can be specified by `com.docker.network.driver.mtu`, for example:

```
docker network create -o "com.docker.network.driver.mtu=1400" --label xxxxxx
```

Can you add an option to specify MTU value manually when azure pipelines agent was setup?

**Comment by hez2010** [comment]
Any updates? This blocks azure pipeline agent being used in dind scenario.

**Comment by anatolybolshakov** [comment]
Hi @hez2010 sorry for the delay - let us take a look.

**Comment by AnnaOpareva** [comment]
Hi, @hez2010  Agent that contains the fix for the described issue has been released (v2.191.1). You need to set the environment variable AGENT_MTU_VALUE to set the MTU value, after that config and run the self-hosted agent. Could you test - does it works for you? Feel free to ping us if you will have any problem with it.

**Comment by hez2010** [comment]
Thanks for update. BTW how can I prevent Azure DevOps Server automatically downgrading my pipeline agent?

**Comment by alexander-smolyakov** [comment]
@hez2010, you could set up the `AZP_AGENT_DOWNGRADE_DISABLED` environment variable as `true` before agent configuration - to prevent the agent from downgrading.

**Comment by lesomnus** [comment]
@AnnaOpareva  Hi. I think it should be `AGENT_DOCKER_MTU_VALUE` not `AGENT_MTU_VALUE` as coded [here](https://github.com/microsoft/azure-pipelines-agent/blob/7442b8a236820e457bc02414ff56a504522e3965/src/Agent.Sdk/Knob/AgentKnobs.cs#L40C14-L40C14).
The [doc](https://github.com/microsoft/azure-pipelines-agent/blob/7442b8a236820e457bc02414ff56a504522e3965/docs/design/setMTU.md?plain=1#L12) should be updated.
