### ISSUE TITLE
Checkout: self inside a container

### ISSUE THREAD

**Issue by richardgavel** [microsoft/azure-pipelines-agent#3257]
## Agent Version and Platform
2.179.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/Ascendon

## What's not working?

We have a pipeline with a multi-repository checkout that uses a container. The checkout of the secondary repo works fine, but the checkout: self runs into the following:

```
##[error]Unable to process command '##vso[plugininternal.updaterepositorypath alias=self;]C:\vsts-agent-1\_work\14\s\Source' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Repository path 'C:\vsts-agent-1\_work\14\s\Source' should be located under agent's work directory 'C:\__w\14'.
```

We're bypassing it for now by telling the YAML to run that specific step to run on the host explicitly (target: host). 

From the debug logs of the checkout tasks, it looks like they already run with a context relative to the host, not the container (e.g. git init "C:\vsts-agent-1\_work\14\s\Pipeline" as opposed to referencing C:\_w\14\s\Pipeline). Wondering if https://github.com/microsoft/azure-pipelines-agent/blob/763575e4443b61e2957d60dca9a9e068d29ccd92/src/Agent.Worker/PluginInternalCommandExtension.cs#L63 needs that awareness?

**Comment by anatolybolshakov** [comment]
Hi @richardgavel could you please share your yaml file with some minimal repro steps?

**Comment by anatolybolshakov** [comment]
Hi @richardgavel is this issue still actual for you?

**Comment by richardgavel** [comment]
We bypassed it by forcing that particular step of the YAML to run on the
host, but I just haven't gotten around to responding to this request.

**Comment by anatolybolshakov** [comment]
@richardgavel ok, I still can't reproduce this issue with multi-checkout scenario... yaml file would be really helpful to determine exact repro steps.

**Comment by anatolybolshakov** [comment]
Hi @richardgavel do you have any updates? Could you please share your yaml file so we could investigate it further?

**Comment by anatolybolshakov** [comment]
Hi @richardgavel I'm closing it due to inactivity at the moment - please let us know if it's still actual for you.
