### ISSUE TITLE
Additional branch with commit-name while pre-checkout

### ISSUE THREAD

**Issue by migrulos** [microsoft/azure-pipelines-agent#3258]
Hello. Yesterday we updated the agent from version 2.170.1 to version 2.181.1. And after that pre-checkout in jobs started to behave strangely.
If earlier, during checkout, branches and tags were created, now another branch is added, with the name in the form of a hash of the last commit.
This creates problems when mirroring in a Gitlab.

Logs from pre-checkout:
git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --force --tags --prune --progress --no-recurse-submodules origin
git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --force --tags --prune --progress --no-recurse-submodules origin +efe1f11c630048efba55497d76077cda9d2e8149:refs/remotes/origin/efe1f11c630048efba55497d76077cda9d2e8149
From https://mysite.ru/tfs/Tfs_ETR_2010/_git/ETR_Charters
 * [new ref]           efe1f11c630048efba55497d76077cda9d2e8149 -> origin/efe1f11c630048efba55497d76077cda9d2e8149
git checkout --progress --force efe1f11c630048efba55497d76077cda9d2e8149

Of course there is no branch in Azure DevOps with name origin/efe1f11c630048efba55497d76077cda9d2e8149, it is hash of last commit.
Now we rolled back update to 2.170.1 and there is no additional branch again.

**Comment by mjroghelia** [comment]
@jeschu1 FYI, related to checkout changes.

**Comment by EzzhevNikita** [comment]
Hi @migrulos, as workaround fo this issue you can disable the fetch by commit feature. To do it you need to set an environment variable for the agent (VSTS_DISABLEFETCHBYCOMMIT) to "true". Also you can disable it directly from yml configuration by setting the VSTS.DisableFetchByCommit build variable to "true" in this way:
```
variables:
  'VSTS.DisableFetchByCommit': 'true'
```

**Comment by EzzhevNikita** [comment]
@migrulos Did you manage to try the suggested workaround? Is it work for you?

**Comment by EzzhevNikita** [comment]
Since there no response for a long time I'm closing this item currently. Feel free to reopen it in case of any future questions
