### ISSUE TITLE
Build.SourceBranchName does not include full name, if name includes forward slash

### ISSUE THREAD

**Issue by maxgio92** [microsoft/azure-pipelines-agent#3291]
### Current result

Build.SourceBranch | Build.SourceBranchName
-- | --
refs/heads/feature/mynewfeature | mynewfeature
refs/heads/bug/mybug | mybug

### Expected result
Build.SourceBranch | Build.SourceBranchName
-- | --
refs/heads/feature/mynewfeature | feature/mynewfeature
refs/heads/bug/mybug | bug/mybug

The issue is simple. The current value of `$(Build.SourceBranch)` is actually wrong, leading to non-existent named branches.

## Additional info

The same of #838 that has been closed without a real response.
For sure as a community we should contribute by opening a PR and not to pretend, but to ignore issues from the staff is another matter IMHO, so I opened this issue to track it and also be able to know where we can contribute.

**Comment by maxgio92** [comment]
In the meantime, if the need of the real name of branch it to do a `git checkout`, this should solve IMHO, basically by doing a checkout for the reference name with prefixes (e.g.: `refs/heads/<branch_name>`):
```shell
git update-ref $(Build.SourceBranch) $(Build.SourceVersion) # point the named branch reference to the build commit's SHA-1
git symbolic-ref HEAD $(Build.SourceBranch) # point the symbolic reference HEAD to the named branch reference
```

**Comment by mohag** [comment]
Changing this behaviour will break our pipelines. We use Build.SourceBranchName for container image tags, which can't contain slashes. Introducing a different variable might make sense though. (See #3076)

(My guess is that the branch name was treated like a file path, where the last part is the name)

There is an [easy workaround](https://github.com/microsoft/azure-pipelines-agent/issues/838#issuecomment-403151822). (There might be other options as well)

(The current behaviour is not correct, but breaking changes seems like a bad idea)

**Comment by anatolybolshakov** [comment]
Hi @maxgio92 this change could break other users - so creating separate variable for this purpose could be the more safe approach here.
Since adding of new variable is related to some changes in Azure DevOps side - could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by maxgio92** [comment]
Hi @anatolybolshakov, sure, thank you.

**Comment by maxgio92** [comment]
Hi @mohag that workaround isn't correct IMHO as git references strings are not always so simple. Anyway thank you :)

**Comment by maxgio92** [comment]
Sorry @anatolybolshakov but I didn't find how can I create a new one discussion/ticket there :( Could you help me?

**Comment by anatolybolshakov** [comment]
@maxgio92 sure, you can report about the issue here https://developercommunity.visualstudio.com/report?space=21&entry=problem

**Comment by maxgio92** [comment]
Thank you, I just opened a case

**Comment by anatolybolshakov** [comment]
@maxgio92 ok thanks! Could you please leave a link to developer community ticket here to track it?
Let me close this one at the moment since there's nothing to on agent side currently. Please feel free to ask any further questions.
