### ISSUE TITLE
checkout with fetchDepth: 1 does fetch tags

### ISSUE THREAD

**Issue by yene** [microsoft/azure-pipelines-agent#3294]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: checkout  

## Environment
- Azure Pipelines

## Issue Description

When using
```
  - checkout: self
    fetchDepth: 1
```
it does a `git fetch --tags ...` behind the scenes, which fetches more history than needed.

We expected it to speed up our build pipelines with big repos but there was not much change.
Could fetching tags be an option to disable?

**Comment by anatolybolshakov** [comment]
Hi @yene since this feature would require some change on Azure DevOps side also (new parameters for checkout task) - could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by anatolybolshakov** [comment]
@yene let me close this one here since it requires some changes on DevOps side also.

**Comment by yene** [comment]
https://developercommunity.visualstudio.com is where feature requests go to die

**Comment by tomasfejfar** [comment]
Haha, it died there :) https://developercommunity.visualstudio.com/content/problem/1095986/azure-pipelines-checkout-fetches-all-tags.html

**Comment by cristobal** [comment]
So sad that so many good suggestions just go to die in the devloper community whenever they have to be suggested as ideas for azure pipeline 😞. 

This should have been prioritised option in the spirit of the ongoing effort for a greener environment where we spend less un-waisted energy (irony kidding not kidding 😂 ),  since a git checkout with no tags means less bandwidth used when fetching a repo and less output to stdout means less energy used by every pipeline run 🤷🏽 

i.e.: we have a repo with over 2000k tags whenever we do a git checkout it fetches all the tags and prints them to stdout…

**Comment by yene** [comment]
We do checkout manually, now it takes 6 seconds instead of 6 minutes.

```yaml
steps:
- task: Bash@3
  displayName: 'Fast Checkout'
  inputs:
    targetType: 'inline'
    script: |
      set -ex
      git init $(System.DefaultWorkingDirectory)
      git remote add origin $(Build.Repository.Uri) || true
      git config gc.auto 0
      git config advice.detachedHead false
      git config http.version HTTP/1.1
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" fetch --force --prune --no-recurse-submodules --depth=1 origin +$(Build.SourceVersion):refs/remotes/origin/$(Build.SourceVersion)
      git checkout --progress --force $(Build.SourceVersion)

```

**Comment by cristobal** [comment]
> We do our own checkout step, now it takes 6 seconds instead of 6 minutes.
> 
> ```yaml
> steps:
> - checkout: none
> - task: Bash@3
>   displayName: 'Fast Checkout'
>   inputs:
>     targetType: 'inline'
>     script: |
>       set -ex
>       git init $(System.DefaultWorkingDirectory)
>       git remote add origin $(Build.Repository.Uri) || true
>       git config gc.auto 0
>       git config advice.detachedHead false
>       git config http.version HTTP/1.1
>       git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" fetch --force --prune --no-recurse-submodules --depth=1 origin +$(Build.SourceVersion):refs/remotes/origin/$(Build.SourceVersion)
>       git checkout --progress --force $(Build.SourceVersion)
> ```

Thanks for sharing 👍🏽

**Comment by yene** [comment]
Azure pipeline has now an option `fetchTags: false`

```
          - checkout: self
            fetchTags: false
            fetchDepth: 1

```

**Comment by IbrahimUmar** [comment]
How to run this for UI Pipeline? Thank You

**Comment by anoor21** [comment]
@IbrahimUmar Wasim :)  you can set this from pipeline setting from UI as well.
