### ISSUE TITLE
ChromeDriver version isn't compatible with Chrome version

### ISSUE THREAD

**Issue by yesenin** [microsoft/azure-pipelines-agent#3304]
## Having issue with YAML?
-

## Having issue with Tasks?
-

## Having issue with software on Hosted Agent?
-

## Having generic issue with Azure-Pipelines/VSTS/TFS?
-

## Have you tried troubleshooting?
-

## Agent Version and Platform
windows-2019, 2.183.1

## Azure DevOps Type and Version
https://lgre.visualstudio.com/

## What's not working?
Selenium auto tests cannot open Chrome

## Agent and Worker's Diagnostic Logs
```
TearDown : System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 88.0.4324.182 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
```

**Comment by anatolybolshakov** [comment]
Hi @yesenin this issue doesn't seem to be related to agent - for tools like Chrome and ChromeDriver installed on hosted images please feel free to create an issue on https://github.com/actions/virtual-environments
Let me close this one here since this repo is mostly for pipelines agent.
