### ISSUE TITLE
Container Job Initialization Failed: starting container process caused: exec: "node": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by 3wweiweiwu** [microsoft/azure-pipelines-agent#3311]
## Having issue with YAML?
No

## Having issue with Tasks?
No

## Having issue with software on Hosted Agent?
No

## Having generic issue with Azure-Pipelines/VSTS/TFS?
No

## Have you tried troubleshooting?
No

## Agent Version and Platform
Version of your agent? 2.183.1

OS of the machine running the agent? Windows 2019

## Azure DevOps Type and Version
https://{organization}.visualstudio.com

## What's not working?
I try to create a container job with following yaml.  It was working fine in hosted instance. After I switch to local container, it failed with following error:

> Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "node": executable file not found in $PATH: unknown
> Error: failed to start containers: 106585a3d5a016599eecee8843df4a601167ee0396b268196ab0b1bf32034bb5
> ##[error]Docker start fail with exit code 1

YAML:

> trigger:
> - master
> 
> jobs:
> - job: BuildAndTest
>   pool:
>     name: MVT
> 
>   container: mcr.microsoft.com/powershell:lts-ubuntu-16.04
> 
>   steps:
>   - task: power
>   - task: NodeTool@0
>     inputs:
>       versionSpec: '10.x'
>     displayName: 'Install Node.js'

Please include error messages and screenshots.

## Agent and Worker's Diagnostic Logs
[Agent_20210308-173417-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/6104781/Agent_20210308-173417-utc.log)
[Worker_20210308-214132-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/6104782/Worker_20210308-214132-utc.log)

**Comment by anatolybolshakov** [comment]
Hi @3wweiweiwu to be able to execute jobs by linux containerized agent (Windows-based Linux containers) you need to have Node.js pre-installed - please see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#linux-based-containers.
Please feel free to ask any further questions.

**Comment by 3wweiweiwu** [comment]
Thank you for the note. Just curious, why the same container image works in the Azure self-hosted instance? I didn't change anything in the image.

**Comment by anatolybolshakov** [comment]
@3wweiweiwu did you run it on ubuntu hosted agent? Since this is actual for Windows-based Linux containers - I guess it could be related to this if it's true...
