### ISSUE TITLE
How to change docker.sock path for container jobs

### ISSUE THREAD

**Issue by mo-saeed** [microsoft/azure-pipelines-agent#3323]
## Agent Version and Platform
Version of your agent? Latest

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
Container job fails with this error
```
stat -c %g /var/run/docker.sock
##[error]Exit code 1 returned from process: file name 'stat', arguments '-c %g /var/run/docker.sock'.
```
As I am using rootless setup, my docker.sock is under /run/user/****/docker.sock so how to change the default /var/run/docker.sock?

**Comment by mo-saeed** [comment]
@anatolybolshakov maybe you have a fast answer for that?  would be good if this can be changed so i don't need to make bad workarounds here

**Comment by mo-saeed** [comment]
@anatolybolshakov so I tried to use `mapDockerSocket: false` which doesn't map the sockets any more but still this step `stat -c %g /var/run/docker.sock` is executed which is really strange

**Comment by andy-mishechkin** [comment]
Hello, @mo-saeed
I've tested execution of `stat -c %g /var/run/docker.sock` on hosted `ubuntu-latest` agent. I've started the ubuntu container in background `sudo docker run --name ubuntu_bash --rm -i -t -d ubuntu bash` and tried to execute `stat -c %g /var/run/docker.sock` - all works fine (I've attached the screenshot bellow).
![image](https://user-images.githubusercontent.com/57713077/114411767-89ebfa80-9bbd-11eb-8ec2-24a685e9f516.png)

Would you please provide the link to your pipeline, where you've got this error, or some definition or repro steps, which you use in your pipeline ?
Also, did you exec `stat -c %g /var/run/docker.sock` on agent or inside of container ?

Thank you

**Comment by andy-mishechkin** [comment]
Hello, @mo-saeed
Do you have any updates ?

**Comment by andy-mishechkin** [comment]
Closed, because no any activity in 18 days.
@mo-saeed, please feel free to reopen, if you'll have any updates

**Comment by anatolybolshakov** [comment]
Hi @mo-saeed currently there is no specify custom path to docker.sock file - agent relies on /var/run/docker.sock file only - let me reopen it to take a look closer at how we could handle this.
mapDockerSocket controls mounting of this file into the container, but there is also another logic using /var/run/docker.sock file.
cc @andy-mishechkin

**Comment by T1mey** [comment]
Hello @all, Hello @anatolybolshakov 

I have the same issue. Want to start a docker image without mounting the docker.sock

So I set mapDockerSocket: false

But in the init of the container it executes a `stat -c %g /var/run/docker.sock`

![image](https://github.com/microsoft/azure-pipelines-agent/assets/10464878/f10f5837-0110-48e2-9508-33cc989deb13)

Any way to skip that ? I assumed the mapDockerSocket is enough.

**Comment by lefty-k** [comment]
This is an issue with our Docker build tasks as well. If instead of the Docker task we use a command line script to execute the docker build command it works

**Comment by lefty-k** [comment]
Following up on myself we found a work around:
In the pipeline variables tab define two variables
![image](https://github.com/microsoft/azure-pipelines-agent/assets/132050554/4e6f1b3b-1ea2-4e83-b0cd-fb40e73aa9d7)

and Refer to them as environmental variables in the Docker Task itself
![image](https://github.com/microsoft/azure-pipelines-agent/assets/132050554/8ebad034-49cf-4b34-90a6-8316d3427e8f)

The Two environmental variables are:
DOCKER_HOST with value unix:///run/user/<Your user id>/docker.sock
DOCKER_HOST_ROOTLESS_PATH with value /run/user/<Your user id>/docker.sock

Hope this helps

**Comment by son3ofSatan** [comment]
please let me kiss your lips

**Comment by silverkw** [comment]
I believe this is still an issue. We just started running docker as rootless on our docker hosts, and the Azure Release pipeline is complaining about not able to find Docker.Sock.
![image](https://github.com/microsoft/azure-pipelines-agent/assets/28108478/6b16547c-3ce5-4b6d-8e0a-76c10a86f47c)

And our Docker.sock is here under the user, not at the default location

![image](https://github.com/microsoft/azure-pipelines-agent/assets/28108478/db2a689a-174f-49ef-a08a-28fa117bf0da)

Weird thing is, command line actually works, but I want to get this working since connecting to Azure Container Registry is part of this pipeline task.
