### ISSUE TITLE
Azure Release pipeline choose Package or folder is getting error

### ISSUE THREAD

**Issue by minhhungit** [microsoft/azure-pipelines-agent#3327]
Getting error on azure Release pipeline 

Task: **Azure App Service deploy**
Property: **Package or folder**

Error detail: 

Could not load file or assembly 'BuildXL.Cache.ContentStore.Hashing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6212d9137135ce5d' or one of its dependencies. The system cannot find the file specified.

![image](https://user-images.githubusercontent.com/2279508/110932963-b7474d80-835e-11eb-9dcb-09565707a036.png)

**Comment by anatolybolshakov** [comment]
Hi @minhhungit this issue seem to be related to DevOps side, not the agent - since this repo is mostly for agent, could you please create a ticket on https://developercommunity.visualstudio.com/report?space=21&entry=problem to get right eyes on it?

**Comment by minhhungit** [comment]
okay @anatolybolshakov I will

sorry for put the issue in wrong repo, I was not sure which was correct one
