### ISSUE TITLE
SSL cert issues with dotnet.myget.org

### ISSUE THREAD

**Issue by tarunngc** [microsoft/azure-pipelines-agent#3328]
Anyone esle experiencing SSL certificate issues:

![image](https://user-images.githubusercontent.com/39346004/111208636-02e53b80-8599-11eb-9158-10d3e680943d.png)

**Comment by mjroghelia** [comment]
References to this feed have already been removed from this repo: https://github.com/microsoft/azure-pipelines-agent/pull/3306
