### ISSUE TITLE
GIT LFS Broken in latest hosted agent version

### ISSUE THREAD

**Issue by drewwilliams1982** [microsoft/azure-pipelines-agent#3344]
I'm having an issue with software on a Hosted Agent. The link [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) does not work, so don't know where else to log this.

There appears to have been an update to GIT on the hosted windows 2019 image. Between 12:47GMT and 14:40GMT the versions have changed as follows and LFS fetches no longer work:

Old agent version: `2.183.1` with `git version 2.28.0.windows.1`
New agent version is `2.184.1` with `git version 2.31.0.windows.1`

We're seeing the following error:

```
git -c http.https://isams@dev.azure.com.extraheader="AUTHORIZATION: bearer ***" lfs fetch origin refs/remotes/pull/12091/merge
Error: failed to call git rev-parse --git-dir: exit status 128 : error: bogus format in GIT_CONFIG_PARAMETERS
Not in a git repository.
fatal: unable to parse command-line config
```

**Comment by mjroghelia** [comment]
@drewwilliams1982 This is a backward-incompatibility in the latest version of git. You can mitigate the issue by declaring the System.PreferGitFromPath pipeline variable with the value "true". This will make the agent use the slightly older version of git included in the hosted VM image (2.30.2), which is known to work with the version of LFS also included in the hosted image (2.13.2). Setting this variable in your pipeline is generally a best practice when using LFS in the hosted environment, to ensure you are using a compatible LFS/git pair, per the [documentation of using LFS in Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#checkout-files-from-lfs).

**Comment by mjroghelia** [comment]
For more info on the underlying problem, see this post from the git-annex project, which encountered a similar situation with git 2.31.0 https://git-annex.branchable.com/forum/error__58___bogus_format_in_GIT__95__CONFIG__95__PARAMETERS/

**Comment by gregpakes** [comment]
Hi @mjroghelia 

I work with @drewwilliams1982 .  Unfortunately, this did not resolve the issue.

```
Updating files: 100% (53341/53341), done.
fatal: Cannot prompt because user interactivity has been disabled.
fatal: could not read Password for 'https://xxx@dev.azure.com/xxx/xxx/_git/xxx': terminal prompts disabled
Downloading xxx/ixxx/chromedriver.exe (10 MB)
fatal: Cannot prompt because user interactivity has been disabled.
fatal: could not read Password for 'https://xxx@dev.azure.com/xxx/xxx/_git/xxx': terminal prompts disabled
Error downloading object: xxx/xxx/chromedriver.exe (e952c5a): Smudge error: Error downloading xxx/xxx/chromedriver.exe (e952c5a5a7b467c979a01417a42c7fb2c5403c45d353c70b32fa4ee631d3e0ed): batch response: Git credentials for https://xxx@dev.azure.com/xxx/xxx/_git/xxxnot found.

Errors logged to D:\a\1\s\.git\lfs\logs\20210324T233331.1391537.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: xxx/xxx/chromedriver.exe: smudge filter lfs failed
##[error]Git checkout failed with exit code: 128

```

**Comment by gregpakes** [comment]
Hi @mjroghelia 

I work with @drewwilliams1982 .  Unfortunately, this did not resolve the issue.

```
Updating files: 100% (53341/53341), done.
fatal: Cannot prompt because user interactivity has been disabled.
fatal: could not read Password for 'https://isams@dev.azure.com/isams/iSAMS/_git/iSAMS': terminal prompts disabled
Downloading iSAMS.AcceptanceTests/iSAMS.AcceptanceTests.Web/chromedriver.exe (10 MB)
fatal: Cannot prompt because user interactivity has been disabled.
fatal: could not read Password for 'https://isams@dev.azure.com/isams/iSAMS/_git/iSAMS': terminal prompts disabled
Error downloading object: iSAMS.AcceptanceTests/iSAMS.AcceptanceTests.Web/chromedriver.exe (e952c5a): Smudge error: Error downloading iSAMS.AcceptanceTests/iSAMS.AcceptanceTests.Web/chromedriver.exe (e952c5a5a7b467c979a01417a42c7fb2c5403c45d353c70b32fa4ee631d3e0ed): batch response: Git credentials for https://isams@dev.azure.com/isams/iSAMS/_git/iSAMS not found.

Errors logged to D:\a\1\s\.git\lfs\logs\20210324T233331.1391537.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: iSAMS.AcceptanceTests/iSAMS.AcceptanceTests.Web/chromedriver.exe: smudge filter lfs failed
##[error]Git checkout failed with exit code: 128

```

**Comment by drewwilliams1982** [comment]
Adding System.PreferGitFromPath=true appears to work.

Thanks

**Comment by DaniilShmelev** [comment]
As @mjroghelia said, this issue is caused by an incompatibility in git versions. We're planning to release the new version of git on our Windows VM image soon.
You can use the provided workaround with `System.PreferGitFromPath` for now.
