### ISSUE TITLE
Effect of renaming a project on Azure Pipelines Agent

### ISSUE THREAD

**Issue by siddjain** [microsoft/azure-pipelines-agent#3350]
Hello,

we want to rename our Azure DevOps project:
https://docs.microsoft.com/en-us/azure/devops/organizations/projects/rename-project?view=azure-devops

does this action impact the azure pipeline agents? if so, what steps are needed to adapt to the new name? when we created the agent it was done using this command:

```
AGENT_ALLOW_RUNASROOT=true ./config.sh --environment --environmentname "Prod" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/organization-name/ --work _work --projectname 'my-project' --auth PAT --token woid6a --runasservice
```

and now we want to change project name from `my-project` to something else from Azure DevOps web portal. will this not impact the agent?

**Comment by DaniilShmelev** [comment]
Hi @siddjain! The project name is only required during the initial agent configuration, after that, the project's GUID is used, so renaming the project won't affect the agent.
Closing this for now, feel free to reopen if you encounter any issues!

**Comment by siddjain** [comment]
Thanks for clarifying. That makes sense.

________________________________
