### ISSUE TITLE
[Feature request] allow --fetch-tags and --prune to be enabled/disabled on Git Checkout task

### ISSUE THREAD

**Issue by sphanley** [microsoft/azure-pipelines-agent#3352]
My organization has discovered that if we run the exact same commands as are executed by the Microsoft-provided checkout task (which is implemented within the agent runner rather than in the pipeline-tasks repo) but we omit the `--fetch-tags` and `--prune` flags, which are not needed in our case, the performance of our checkout is significantly improved. By combining this with the changes mentioned in #3353, we've seen an 80-90% reduction in our checkout times.

It would be ideal if these could be added as parameters to the YAML command so that we could opt in and out of these flags, consistent with how `clean`, `lfs`, `persistCredentials`, etc. can be toggled.

**Comment by sphanley** [comment]
This is not stale, it's an active improvement request.

**Comment by anatolybolshakov** [comment]
@kuleshovilya could you please take a look?

**Comment by kuleshovilya** [comment]
Hello @sphanley . We are aware that checkout task is somewhat rigid when it comes to customization, but for now there are no plans for massive improvements as it will require a serious overhaul of how the task currently works. 
As an alternative solution we can offer to set checkout to none and provide script with customized checkout behaviour.
Ill close the ticket for now, but feel free to reopen it if you have any additional questions, or you can ping me at v-ikuleshov@microsoft.com

**Comment by Meir017** [comment]
@kuleshovilya I'm not sure exactly what the relationship between the `Microsoft.TeamFoundation.DistributedTask.*` packages and the agent are, they seem pretty coupled but I cannot seem to find the source code for `Microsoft.TeamFoundation.DistributedTask`.

would something like this work?

```diff
diff --git a/src/Agent.Plugins/GitCliManager.cs b/src/Agent.Plugins/GitCliManager.cs
index 83241eb2..7df10689 100644
--- a/src/Agent.Plugins/GitCliManager.cs
+++ b/src/Agent.Plugins/GitCliManager.cs
@@ -174,21 +174,24 @@ namespace Agent.Plugins.Repository
             bool reducedOutput = AgentKnobs.QuietCheckout.GetValue(context).AsBoolean();
             string progress = reducedOutput ? string.Empty : "--progress";

+            bool noTags = AgentKnobs.FetchNoTags.GetValue(context).AsBoolean();
+            string tags = noTags ? "--tags" : "--no-tags";
+
             // default options for git fetch.
-            string options = StringUtil.Format($"{forceTag} --tags --prune {progress} --no-recurse-submodules {remoteName} {string.Join(" ", refSpec)}");
+            string options = StringUtil.Format($"{forceTag} {tags} --prune {progress} --no-recurse-submodules {remoteName} {string.Join(" ", refSpec)}");

             // If shallow fetch add --depth arg
             // If the local repository is shallowed but there is no fetch depth provide for this build,
             // add --unshallow to convert the shallow repository to a complete repository
             if (fetchDepth > 0)
             {
-                options = StringUtil.Format($"{forceTag} --tags --prune {progress} --no-recurse-submodules --depth={fetchDepth} {remoteName} {string.Join(" ", refSpec)}");
+                options = StringUtil.Format($"{forceTag} {tags} --prune {progress} --no-recurse-submodules --depth={fetchDepth} {remoteName} {string.Join(" ", refSpec)}");
             }
             else
             {
                 if (File.Exists(Path.Combine(repositoryPath, ".git", "shallow")))
                 {
-                    options = StringUtil.Format($"{forceTag} --tags --prune {progress} --no-recurse-submodules --unshallow {remoteName} {string.Join(" ", refSpec)}");
+                    options = StringUtil.Format($"{forceTag} {tags} --prune {progress} --no-recurse-submodules --unshallow {remoteName} {string.Join(" ", refSpec)}");
                 }
             }

diff --git a/src/Agent.Sdk/Knob/AgentKnobs.cs b/src/Agent.Sdk/Knob/AgentKnobs.cs
index 716cdb7a..3a047870 100644
--- a/src/Agent.Sdk/Knob/AgentKnobs.cs
+++ b/src/Agent.Sdk/Knob/AgentKnobs.cs
@@ -63,6 +63,13 @@ namespace Agent.Sdk.Knob
             new EnvironmentKnobSource("VSTS_DISABLEFETCHBYCOMMIT"),
             new BuiltInDefaultKnobSource("false"));

+        public static readonly Knob FetchNoTags = new Knob(
+            nameof(FetchNoTags),
+            "If true, fetch without tags. Otherwise, fetch akk tags.",
+            new RuntimeKnobSource("VSTS.FetchNoTags"),
+            new EnvironmentKnobSource("VSTS_FETCHNOTAGS"),
+            new BuiltInDefaultKnobSource("false"));
+
         public static readonly Knob PreferGitFromPath = new Knob(
             nameof(PreferGitFromPath),
             "Determines which Git we will use on Windows. By default, we prefer the built-in portable git in the agent's externals folder, setting this to true makes the agent find git.exe from %PATH% if possible.",
```

**Comment by kuleshovilya** [comment]
@Meir017 Knobs are not production feature per se, and not really recommened for production use. 
Also, that's only changing fetches, to properly integrate it into "Get sources" task that won't be enough

**Comment by sphanley** [comment]
@kuleshovilya, thanks for the update. Disappointing to hear there isn't interest in making this change. Respectfully, I don't understand why this would take a "serious overhaul" to accomplish. As I said, there's already a number of aspects of the checkout task which can be toggled on and off via parameters, such as `clean`, `lfs`, and `persistCredentials`. This feature request would simply be a straightforward extension of that pattern to allow toggling of these additional flags passed to the underlying git call. 

My team has already written a custom script to remove these flags as well as making the change mentioned in my [second feature request](https://github.com/microsoft/azure-pipelines-agent/issues/3353), and we've found the combination to speed up a large repository checkout by >90%. I believe this would have the potential to really benefit many users.

**Comment by kuleshovilya** [comment]
The current implementation is a limiting factor here, but the claim regarding increased speed is interesting, we will certainly will be keeping tab on it

**Comment by Meir017** [comment]
> The current implementation is a limiting factor here, but the claim regarding increased speed is interesting, we will certainly will be keeping tab on it

I my team we also use a custom script to checkout, for us it reduced the checkout time from ~3 minutes to ~30 seconds

**Comment by Meir017** [comment]
> @Meir017 Knobs are not production feature per se, and not really recommened for production use. Also, that's only changing fetches, to properly integrate it into "Get sources" task that won't be enough

what is the correct way for production?

**Comment by kuleshovilya** [comment]
Exactly, and that is not really customizable through checkout without knobs, which are not recomended for production.
Now, for it to be properly introduced, new feature would need to be introduced for fetch customization, which for now is not planned.

**Comment by Meir017** [comment]
in the meantime this is a work around
```yml
      steps:
      - checkout: none
      - script: |
          git init .
          git remote add origin $(Build.Repository.Uri)
          git -c http.extraheader="Authorization: Bearer $(System.AccessToken)" fetch --no-tags --progress --verbose --depth=1 origin +$(Build.SourceBranch)
          echo "checkout commit $(Build.SourceVersion)..."
          git -c http.extraheader="Authorization: Bearer $(System.AccessToken)" checkout $(Build.SourceVersion)
        displayName: Git Checkout
```

**Comment by michielvanderros-tomtom** [comment]
> ```yaml
> ```yaml
> steps:
>       - checkout: none
>       - script: |
>           git init .
>           git remote add origin $(Build.Repository.Uri)
>           git -c http.extraheader="Authorization: Bearer $(System.AccessToken)" fetch --no-tags --progress --verbose --depth=1 origin +$(Build.SourceBranch)
>           echo "checkout commit $(Build.SourceVersion)..."
>           git -c http.extraheader="Authorization: Bearer $(System.AccessToken)" checkout $(Build.SourceVersion)
>         displayName: Git Checkout
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

But that's why many people raise this issue: We all hope you can get it on your planning :-) Please?

**Comment by michielvanderros-tomtom** [comment]
> new feature would need to be introduced for fetch customization, which for now is not planned.

But that's why many people raise this issue: We all hope you can get it on your planning :-) Please?

**Comment by alphaleonis** [comment]
We are currently encoutering throttling due to too much TSTU usage due to the large amount of data it unnecessarily fetches during  the fetch operation. I really think you should reconsider adding this feature!
