### ISSUE TITLE
[Feature request] don't restrict Git to HTTP/1.1 in Checkout task until after the checkout is complete

### ISSUE THREAD

**Issue by sphanley** [microsoft/azure-pipelines-agent#3353]
My organization has discovered that if we run the exact same commands as are executed by the Microsoft-provided checkout task (which is implemented within the agent runner rather than in the pipeline-tasks repo) but we omit the line `git config http.version HTTP/1.1`, the performance of our checkout is dramatically faster. By combining this with the changes mentioned in #3352, we've seen an 80-90% reduction in our checkout times. 

Based on the [comments in the codebase](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/GitSourceProvider.cs#L671) and the feedback we've gotten from engaging our Microsoft support contacts, we've been told that this HTTP/1.1 restriction is in place because IIS can reject large *pushes* to Azure git repos when HTTP/2 is being used. However, since the checkout job only fetches/checks out and does not do any pushes, it would be ideal if at least the invocation of `git config http.version HTTP/1.1` could be moved to **after** the initial checkout is complete, so that any subsequent pushes can be protected from failing, but the initial checkout can benefit from the massive speed benefits of not being locked to the older standard.

Alternately, since according to [the documentation that's linked in the comment mentioned above](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/headerlimits/) it seems like the header limit is user-defined, a better solution would be for the IIS instance underlying Azure Git repos to be configured correctly such that git can be properly supported over HTTP/2, as it seems likely that similar performance improvements would be seen for other git operations besides fetching.

**Comment by sphanley** [comment]
This is not stale, it's an active enhancement request.

**Comment by sphanley** [comment]
This is not stale, it's still an active enhancement request.

**Comment by anatolybolshakov** [comment]
@sphanley thanks for reporting! @MaximMalygin could you please take a look?
Is it possible/would it make sense to adjust configuration on ADO side?
We could probably invoke `git config http.version HTTP/1.` after checkout, but not sure if it's fully supported now.

**Comment by MaximMalygin** [comment]
Probably we should tested it, because i'm not sure if it works correctly for all repositories

**Comment by ismayilov-ismayil** [comment]
Hi @sphanley, thank you for your contribution.
After my tests it seems that we will not have significant change with different options on http.version parameter. Due to git client uses smart protocol, the performance is closer to HTTP/2 
Regarding your second suggestion to implement feature flag for checkout command parameters - if there is not any tag the checkout speed will same, if there is, it is necessary to download it as well.

Closing this, feel free to ask any other questions or let us know if it's still relevant for you.
