### ISSUE TITLE
kill -SIGINT #PID failed when running .sh script in pipeline, is there any suggestion on how to send SIGINT to a background task in bash script for pipeline 

### ISSUE THREAD

**Issue by wangwen-ms** [microsoft/azure-pipelines-agent#3354]

**Comment by anatolybolshakov** [comment]
Hi @wangwen-ms could you please share the error which you faced with?

**Comment by wangwen-ms** [comment]
there is a bash script which i run successfully in the local , but when running on pipeline , it will failed on killing a background process , I think the question is  i kill the process with SIGINT,  do you have any experience about how to send SIGINT when running by pipeline.

**Comment by anatolybolshakov** [comment]
@wangwen-ms in general there should not be restrictions for this command - if user which is used to run agent has enough permissions to execute 'kill' command for specified PID, it should work.

**Comment by wangwen-ms** [comment]
yes, the problem is in non-interactive shell ,the signal: SIGINT will be ignored. so is there any tips to set pipeline in interactive shell or mode?

**Comment by anatolybolshakov** [comment]
@wangwen-ms there is no ability to run interactive shell via Bash pipeline task.

**Comment by wangwen-ms** [comment]
ok, i will try other scripts to  accomplish  same function, thanks.

**Comment by anatolybolshakov** [comment]
@wangwen-ms let me close this one since it looks resolved - but please feel free to ask any further questions.
