### ISSUE TITLE
VMSS extension Microsoft.Azure.DevOps.Pipelines.Agent proxy

### ISSUE THREAD

**Issue by mleziva** [microsoft/azure-pipelines-agent#3356]
## Agent Version and Platform
TeamServicesAgentLinux 1.21

OS of the machine running the agent? OSX/Windows/Linux/...
Ubuntu 

## What's not working?
Attempting to use scale set agents behind a proxy. The Microsoft.Azure.DevOps.Pipelines.Agent fails with the following error:

`VM has reported a failure when processing extension 'Microsoft.Azure.DevOps.Pipelines.Agent'. Error message: "The Extension failed to execute: <urlopen error [Errno 101] Network is unreachable>" More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot`

Logs snippet:
`2021/04/02 16:01:30 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2] Download Pipelines Zip
2021/04/02 16:01:30 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2] https://vstsagentpackage.azureedge.net/agent/2.184.2/vsts-agent-linux-x64-2.184.2.tar.gz
2021/04/02 16:03:41 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2] <urlopen error [Errno 101] Network is unreachable>
2021/04/02 16:03:41 ERROR:[Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2] <urlopen error [Errno 101] Network is unreachable>`

When I SSH into the machine I can see that the proxy is set correctly and I have access to azureedge.net. However, when installing the extension it does not use the proxy and I don't see where I would be able to specify a proxy for it to use.

**Comment by mleziva** [comment]
Hi, has there been any movement on this? We are still not seeing the scale set agent utilize the proxy correctly

**Comment by ZachRothweiler** [comment]
Bumping this one, seeing the same issue. This prevents us from using scaleset pools

**Comment by jappenzesr** [comment]
Same issue here. We have to run the agent behind a proxy for security reasons. When will this be addressed?

**Comment by ZachRothweiler** [comment]
Found a potential solution after narrowing the problem down to the agent linux service (not specific to the Azure DevOps extension). You can work around the issue by modifying the service definition file. For a scale set, this needs to be done with a custom-data extension. Example:
```

bootcmd:
  - mkdir -p /etc/systemd/system/walinuxagent.service.d
  - echo "[Unit]\nAfter=cloud-final.service\n\n[Service]\nEnvironment=http_proxy=http://<address>:<port>\nEnvironment=https_proxy=http://<address>:<port>" > /etc/systemd/system/walinuxagent.service.d/override.conf
  - sed "s/After=multi-user.target//g" /lib/systemd/system/cloud-final.service > /etc/systemd/system/cloud-final.service
  - systemctl daemon-reload
```

**Comment by jappenzesr** [comment]
Thanks Zach. Above worked for me. We build our own agent image via a packer. Creating the file `/etc/systemd/system/walinuxagent.service.d/override.conf `
with content 
```
[Service] 
Environment=http_proxy=host:port https_proxy=host:port
```
solved the issue.

**Comment by mleziva** [comment]
Looks like this update might have fixed the problem: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#customizing-pipeline-agent-configuration

**Comment by lucasdk3** [comment]
What would be the host and port?
