### ISSUE TITLE
User groups inside container jobs does not the match the host

### ISSUE THREAD

**Issue by hommeabeil** [microsoft/azure-pipelines-agent#3362]
## Agent Version and Platform
Version of your agent? 2.181.1

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
In a container jobs, the user created inside the container does not have the same group ID (`gid`), has the agent running on the host.

Here is how a new user is created inside a container, the user ID is properly set with the useradd, but the group got something like `1002`. This is an issue, because our build copy files from the source folder (`s`) and keep the source `uid` and `gid`. This is a yocto base project, so I do not have any control on how the build can be run, and I can't run it as `root` either.

```
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 sh -c "command -v bash"
/bin/bash
whoami 
devops-agent
id -u devops-agent
112
Try to create a user with UID '112' inside the container.
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 bash -c "getent passwd 112 | cut -d: -f1 "
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 useradd -m -u 112 devops-agent_azpcontainer
Grant user 'devops-agent_azpcontainer' SUDO privilege and allow it run any command without authentication.
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 groupadd azure_pipelines_sudo
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 usermod -a -G azure_pipelines_sudo devops-agent_azpcontainer
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 su -c "echo '%azure_pipelines_sudo ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers"
Allow user 'devops-agent_azpcontainer' run any docker command without SUDO.
stat -c %g /var/run/docker.sock
998
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 bash -c "cat /etc/group"
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 groupadd -g 998 azure_pipelines_docker
/usr/bin/docker exec  e1e905822ffe62524d6fc2151020933028d6ab71b42cf29d6fb3460eaddfd1e9 usermod -a -G azure_pipelines_docker devops-agent_azpcontainer
```

Here is a workaround I can put in my build pipeline, but I find it a bit strange that I need to do it.
```yaml
jobs:
   - job: example
     container: ....  
     steps:
        - bash: chown $(id -u):$(id -g) -R $(Build.Repository.LocalPath)/sources/poky/scripts/postinst-intercepts
```

**Comment by spr0ut** [comment]
Just come across this issue while trying to diagnose why a container job runs fine on one agent, but not another. It's because one agent is running as UUID 1000 which matches the node container UUID (1000), and the broken agent was running under UUID 1002.

## Environment
Azure DevOps Server 2020 Update 1

**Comment by hommeabeil** [comment]
Does this has been fixed without been linked to it ? If no, then the issue is still active.

**Comment by anatolybolshakov** [comment]
Hi @hommeabeil thanks for reporting! Let us take a look - probably it could make sense at least try to create group with the same gid as for host user.

**Comment by kirill-ivlev** [comment]
@hommeabeil I performed an investigation with ubuntu:18.04 as a container and found that all files created inside a container were matched valid UID/GID. I can assume that behavior might be different for other containers.

Could you please provide information about the image which you are using to execute the build procedure and the name & version of the host Linux distro?

**Comment by hommeabeil** [comment]
The image we are using is currently debian:10 and the host is also debian 10.

**Comment by kirill-ivlev** [comment]
@hommeabeil 
currently, the Azure DevOps agent creating user and group with the same UID/GID that it has on the host machine,
for example: 
if you have a user with ID 1000 (but the primary group of this user is 1002 for example), inside the container Agent will create a user & group with ID 1000:1000, I assume that it can be an issue in this case.
Could you please tell me, if your user on the host machine (in this case devops-agent) has the same GID  value which are equals to the UID? (you can check it by command executed on behalf of this user:
`id -g`

If the primary group differs from the user id, in this case, I can suggest trying to set the primary group value to the same ID as a UID

**Comment by hommeabeil** [comment]
Yes this is exactly what is happening. Our agent UID is 112 and his group is 117. Is this is planned to be fixed ? It is obviously not the expected behavior. Thanks for investigating.

**Comment by DmitriiBobreshev** [comment]
the results of buddy testing are here: https://github.com/microsoft/azure-pipelines-agent/pull/3837#pullrequestreview-1019453104

**Comment by DenisRumyantsev** [comment]
The related pull request is ready — [link](https://github.com/microsoft/azure-pipelines-agent/pull/3837)
