### ISSUE TITLE
Where is the code which parses the current Azure Pipelines YAML syntax?

### ISSUE THREAD

**Issue by blake-mealey** [microsoft/azure-pipelines-agent#3373]
This is not a bug report with the agent, so I have removed all the standard Q/A as they are irrelevant.

I am trying to understand the code which parses the YAML pipelines syntax in this repository and having some difficulty. I discovered the `Agent.Listener` project's `DistributedTask.Pipelines.Yaml.PipelineParser` but this appears to be parsing an old version of the YAML syntax (the one which seems to be described by the [outdated](https://github.com/microsoft/azure-pipelines-agent/tree/master/docs/preview/outdated) docs) which involves parsing mustache templates and has no notion of parameters etc.

I have spent a considerable amount of time searching the codebase but I haven't found any other areas which seem related to parsing. Am I just missing something obvious? Does this agent not support the modern YAML syntax? Is there a different repo where this code is located?

Thanks for the help.

**Comment by mjroghelia** [comment]
The YAML is parsed in the Azure DevOps service, not on the agent. The source for the parser is not publicly available.

**Comment by blake-mealey** [comment]
Thanks for the info
