### ISSUE TITLE
Agent won't auto-update from Azure DevOps

### ISSUE THREAD

**Issue by AmittaiShapira** [microsoft/azure-pipelines-agent#3387]
## Agent Version and Platform
Version of your agent? 2.171.1 to 2.186.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com 

If dev.azure.com, what is your organization name? https://dev.azure.com/PhilipsMA

## What's not working?
Due to regulations for our product we disabled updates for agents and kept them with version 2.171.1
However the latest Azure DevOps changes made this agent version incomapitble with Azure DevOps:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/59568557/117143243-9f98ae00-ad7e-11eb-9664-f3da5ab1f0a5.png)

We tried updating all agents in the pool (around 20) from Azure DevOps, but the update failed with the following exception in the agent SelfUpdater.DownloadLatestAgent() method:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/59568557/117143430-d373d380-ad7e-11eb-9aa7-5ed841b51b16.png)

## Agent and Worker's Diagnostic Logs
See logs below.

**Comment by jpi-01** [comment]
[
[Agent_20210505-000237-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/6427385/Agent_20210505-000237-utc.log)
](url)

**Comment by AmittaiShapira** [comment]
See logs above from @jpi-01 
Additional comment:
Downloading the latest agent revision through browser works on the agent machine with no issue.
We manually updated the agents as a workaround.

**Comment by anatolybolshakov** [comment]
Hi @AmittaiShapira there seem to be timeout issue during agent automatic update - do you have any network issues?

**Comment by anatolybolshakov** [comment]
@AmittaiShapira I can't reproduce this issue during update from 2.171.1 to 2.186.1 - do you still see it reproducible?
Did you try to download the agent by following https://vstsagentpackage.azureedge.net/agent/2.186.0/vsts-agent-win-x64-2.186.0.zip from browser on agent machine? Does it work without issues?
Do you see this issue on other environments/networks?
Do you use any proxy?
And also - does this issue happen spontaneously for you, or constantly?

**Comment by AmittaiShapira** [comment]
@Anatoly ***@***.***> see below:
Did you try to download the agent by following https://vstsagentpackage.azureedge.net/agent/2.186.0/vsts-agent-win-x64-2.186.0.zip<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvstsagentpackage.azureedge.net%2Fagent%2F2.186.0%2Fvsts-agent-win-x64-2.186.0.zip&data=04%7C01%7C%7C8aa99c7036b04d2279fb08d915f085a7%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637564945046254779%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0JhMCQY5cgiPvJj2bNnueXhLdlaIwtdYzDtIii21odE%3D&reserved=0> from browser on agent machine? Does it work without issues?
Yes, downloading using the web link worked without an issue
Do you see this issue on other environments/networks?
No - we haven't really tried reproducing as the workaround for updating manually worked
Do you use any proxy?
Yes - we have our corporate proxy
And also - does this issue happen spontaneously for you, or constantly?
Not sure what you mean by that - we had around 20 agents on different boxes (all on the same virtual host) failing the same update

Thanks,
Amittai

**Comment by anatolybolshakov** [comment]
@AmittaiShapira could you please try to set 'VSTS_AGENT_HTTPTRACE', 'VSTSAGENT_TRACE' environment variables as 'true', configure the agent, let it update and share result logs?

**Comment by anatolybolshakov** [comment]
Could you please also make sure that all domains mentioned in [docs](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops) are reachable for agent?

**Comment by jpi-01** [comment]
Long story short 
I have reconfigured one of the agent using the proxy url: 

> ./config.cmd --proxyurl http://127.0.0.1:8888 --proxyusername "myuser" --proxypassword "mypass"

 With our corporate proxy, and I was able to auto update

**Comment by anatolybolshakov** [comment]
Hi @AmittaiShapira do you have any updates?

**Comment by anatolybolshakov** [comment]
Hi everyone, let me close this one due to inactivity - this looks like an external issue with connectivity not related to agent at the moment.
@AmittaiShapira please let us know if it's still actual for you.

**Comment by AmittaiShapira** [comment]
Closing works for me
