### ISSUE TITLE
Dependencies missing after switching from managed ubuntu-latest to vmss UbuntuServer 18.04-LTS

### ISSUE THREAD

**Issue by ColeSiegelTR** [microsoft/azure-pipelines-agent#3390]
Hi,

I am trying to update my Azure DevOps pipeline which currently uses hosted agent `ubuntu-latest` to use a self-hosted virtual machine scale set agent pool. The scale set agent pool is installed with the default option in Azure Portal which is `UbuntuServer 18.04-LTS` from Azure Marketplace. I have followed the tutorial here https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops which indicates to create the vmss by CLI with image `UbuntuLTS` but that is not working for me due to limitations with the default networking created via this command so I have used the portal instead.

When I check the list of software installed on the hosted agent here
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software I see that it does not include `dotnet` and yet I am able to run dotnet builds from the hosted agent, e.g. using ADO plugin below

```
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              publishWebProjects: false
              projects: "**/*.csproj"
              workingDirectory: src
              arguments: --configuration Release
```

When I run the same pipeline via scale set agent, it fails since `dotnet` is not installed on the base image.

It seems like maybe the hosted agent has additional software beyond what is listed on the documentation above. Perhaps the Azure Marketplace image is also missing dependencies that come standard with `UbuntuLTS`, as I had similar issues with `docker` being missing on the self-hosted agent vm.

Is there a recommended approach for selecting an image which I can use as a replacement for the Microsoft hosted agent? Azure DevOps has many build plugins such as the one noted above `DotNetCoreCLI@2` and it is not always clear what build dependencies are required. How can I set up my virtual machine scale set agent pool so that it is compatible with these standard Azure DevOps pipeline features? Am I supposed to use the images in this repo as a base profile for the VM? Is it expected that despite having an UbuntuLTS 18.04 VM with Microsoft.Azure.DevOps.Pipelines.Agent extension I cannot build dotnet?

```
Starting: Build
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.181.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Error: Unable to locate executable file: 'dotnet'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
Finishing: Build
```

edit: updated the build command example

**Comment by anatolybolshakov** [comment]
Hi @ColeSiegelTR you can find software installed on ms hosted images here - https://github.com/actions/virtual-environments/tree/main/images. To be able to use dotnet by agent - you need to have it installed on agent machine.
Please feel free to ask questions in https://github.com/actions/virtual-environments about ms hosted images and software provided

**Comment by anatolybolshakov** [comment]
@ColeSiegelTR I'm closing this at the moment since it looks related to images - please let us know if you have any further questions.
