### ISSUE TITLE
Azure DevOps hosted build “java” demanded capability not present

### ISSUE THREAD

**Issue by Shahyads** [microsoft/azure-pipelines-agent#3402]
SonarQube scanner “Run Code Analysis” task demands "java" capability.
On one of our agent host machines, the java capability has gone, since we switched to OpenJDK.
It is working on another server with exactly the same conditions
I don't know how an agent detect java but all java related environment variables are still defined on the agent.
Details are [here](https://community.sonarsource.com/t/azure-devops-hosted-build-java-demanded-capability-not-present/8878) 
We are using Azure DevOps Server 2020 
Agent version is 2.177.1 on Windows Server 2012 R2
I will try the latest agent version but i don't see any related topic in the release notes.

**Comment by anatolybolshakov** [comment]
Hi @Shahyads agent checks following registry keys during capability scanning for this capability:
"Software\JavaSoft\Java Runtime Environment\1.6"
"Software\JavaSoft\Java Runtime Environment\1.7"
"Software\JavaSoft\Java Runtime Environment\1.8"

As a temporary workaround - you can specify custom user capability to provide proper path.
There is a PR already in progress to solve this issue - https://github.com/microsoft/azure-pipelines-agent/pull/3381

**Comment by Shahyads** [comment]
Hi @anatolybolshakov,
thank you for your prompt support. 
actually I think it could not be the root cause.
I have two servers non of them has registry key Software\JavaSoft\Java Runtime Environment
However it works on one of them. maybe there is another parallel mechanism for detecting java.

**Comment by EzzhevNikita** [comment]
@Shahyads Fix for this issue has been released and available in the latest agent version. I am closing this item currently. Feel free to reopen it in case it still actual for you.

**Comment by ofgirichardsonb** [comment]
not fixed, see #3624
