### ISSUE TITLE
[Question] How can I replace Node.JS 10 with Node.JS 12 (or higher version) on Azure pipelines agent

### ISSUE THREAD

**Issue by dexterlea** [microsoft/azure-pipelines-agent#3406]
## Agent Version and Platform
Agent Version: **2.185.1**.

OS of the machine running the agent: **GNU/Linux (Kylin Linux Advanced Server V10 (Azalea))**.

Architecture of the machine running the agent: **mips64el**.

## Azure DevOps Type and Version
Type: **On-premises Azure DevOps Server**.

Release: **2020.1_rc2**.

## Situation
Since azure pipelines agent need external node10 to excute below bash script in `runsvc.sh`,

```bash
./externals/node10/bin/node ./bin/AgentService.js
```

I have already built node-10.24.0 with `--without-ssl` option (if without this option, built will fail on mips64el).

However, when running pipelines, error will be thrown.

![image](https://user-images.githubusercontent.com/35717851/118582355-c23ab600-b7c5-11eb-84f9-443189d465ed.png)

I've checked node github repo and found when node version >= 12.6.0, node could be compiled successfully with `--openssl-no-asm` option on `mips64el`.

https://github.com/nodejs/node/blob/v12.x/deps/openssl/config/Makefile

![image](https://user-images.githubusercontent.com/35717851/118582945-d03d0680-b7c6-11eb-886a-a840d2aa54aa.png)

https://github.com/nodejs/node/blob/v10.24.0/deps/openssl/config/Makefile

![image](https://user-images.githubusercontent.com/35717851/118583025-ef3b9880-b7c6-11eb-913a-61df177a770a.png)

I have successfully built node-12.21.0 from source on agent platform.

![image](https://user-images.githubusercontent.com/35717851/118583334-78eb6600-b7c7-11eb-92bf-5dec725326b7.png)

**How can I use Node.JS 12 to run `./bin/AgentService.js` (Simply replace node10 `node` binary file with compiled node12 binary file is not working) ?**

**Comment by anatolybolshakov** [comment]
Hi @dexterlea Node 12 is not currently supported yet - we have plans to migrate it to node 14, but currently it is not supported.

**Comment by dexterlea** [comment]
> Hi @dexterlea Node 12 is not currently supported yet - we have plans to migrate it to node 14, but currently it is not supported.

Hi @anatolybolshakov thanks for your reply.
