### ISSUE TITLE
Running tests with multi agent blocks all agents until finished

### ISSUE THREAD

**Issue by MalteFries** [microsoft/azure-pipelines-agent#3412]
We currently have the case that we run several test cases in parallel on 12 agents, one run per agent takes on average 15 minutes. However, one of our test cases has a runtime of 90 minutes. 
This results in all 11 agents wait until the 12th agent is done.
Since we are using Azure VMs and running them as self hosted agents, it means that we are paying money for 1 hour and 15 minutes where the Azure VMs are online and cannot be deallocated or used for other jobs.

The same scenario occurs when we start only one test, then still all 12 agents are blocked for the job, of which 11 idle and 1 runs test case.

The "Number of agents" option does not allow the use of variables, nor is it possible to override this value via the API.
And I can't expect from our testers to continiously edit our release pipelines to adjust the agent number

So why do all agents remain reserved for the job even though they are done and idle?
Is it possible for me to tell the agent that he is done with his job?

**Comment by beerai** [comment]
Commenting so this doesn't go stale. We also run our tests across a number of agents and have also noticed the same behaviour.

**Comment by anatolybolshakov** [comment]
Hi @beerai as I know for the current architecture job is the atomic unit of execution, which is executed by one agent. I would suggest to split up the problematic test case into separate jobs/probably use some parallel execution in code to speed it up, and allow other agents to pick up remaining tasks in separate jobs.
For more questions regarding other execution strategies available in pipelines - feel free to open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get more info.

**Comment by MalteFries** [comment]
Hi @anatolybolshakov,
we are running automated UI tests which can't be split up.
