### ISSUE TITLE
Restricting Access of Project Collection Build Service?

### ISSUE THREAD

**Issue by schwarzzz** [microsoft/azure-pipelines-agent#3414]
I have an Azure DevOps organization with multiple projects.
I want the pipelines from some projects to have access to certain repositories of another projects. Hence, I have disabled the "Limit job authorization scope to current project for non-release pipelines" restriction for my organization and respective projects.

Now, those pipelines can access _all_ repositories in my organization. I don't want that. I want to prevent access to certain repositories of certain projects.

The [Default permissions and access for Azure DevOps Documentation](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=azure-devops#git) states:
> By default, the Project Collection Build Service can read from all repositories. Any pipeline which runs within the project collection scope can potentially read any repository in the organization or collection. To remove this permission for a repository, change the Read permission to Deny for the Project Collection Build Service.

However, when I add the `Project Collection Build Service ({OrgName})` to the Security settings of a repository, the `Read` permissions are set to `Allow (system)` and whenever I overwrite it with `Deny`, the permissions are reset to the initial value again.

 How can I restrict the access as stated in the documentation?

**Comment by alexander-smolyakov** [comment]
Hi, @schwarzzz the management of permissions and access for projects is related Azure DevOps side - could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 to get the right eyes on it?

**Comment by alexander-smolyakov** [comment]
@schwarzzz Let me close this one at the moment since this question is not related to the pipeline agent. Please feel free to ask any further questions.
