### ISSUE TITLE
Agent Self Update: Ignoring the ADO Requests

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-agent#3417]
Dear All,

**Background**

Our own developed Agent controller is reverting the VM of the Agents on each Job completed.
Once command line argument of the DevOps Agent triggering the revert process when make it offline itself.

The official built-in self update process of the Agent is taking offline the Agent for minutes, this is enough to trigger the revert process.

**Inquiry**

We would like to prevent this status, that's why the  "Allow agents in this pool to automatically update" function has been disabled on Organization level.
Unfortunately, we are not able to restrict the usage of the built-in "Update all Agents" function for a limited group of users.
Compare to the restricted global settings, this is available for all users with at least Read access to the Pool.

Is there any way to ignore the update requests of the server side on the clients?

Regards,
Gabor Bernics

**Comment by anatolybolshakov** [comment]
Hi @iambernics there is no way to ignore agent update message at the moment, as I understand in general it's not a preferred option to disable it.

**Comment by anatolybolshakov** [comment]
Probably one option could be to move such agents to the separate agent pool - if you want to disable agent updates specifically for them.

**Comment by anatolybolshakov** [comment]
@iambernics closing this one at the moment due to inactivity - please let us know if you have any further questions.
