### ISSUE TITLE
Misleading error message on task run

### ISSUE THREAD

**Issue by denis-shemenko** [microsoft/azure-pipelines-agent#3421]
### Issue Description
Was playing around custom release tasks (uploaded via `tfx`)
And all consequent releases were failing with the error message (see "Actual behavior")
According to that message I was trying to build task binaries in a different ways (like x64 only, then AnyCPU again) and was failing again after upload and release re-run. 
But then I realized that the very first sentence in the whole message can be the case. 
And that's how I found that you can't have this lines in your task.json 
(Actually we have a lot of "old" tasks definitions with such a lines.):
```
"preJobExecution":{}
"postJobExecution":{}
```

while in schema:
```
"type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task (on Pre-Job stage)",
      "properties": {
        "Node10": {
          "$ref": "#/definitions/executionObject"
        },
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        }
      }
```

### Expected behaviour
Some sort of failed validation error against `tasks.schema`

### Actual behaviour
Got this error message:
##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.

### Steps to reproduce
1. Create & build any simple Powershell task
2. Make sure that you have line like this: `"preJobExecution":{}` in your task.json definition
3. Upload task to target ADO collection via `tfx`
4. Try to create & run new release with this only task

**Comment by anatolybolshakov** [comment]
Hi @denis-shemenko thanks for reporting of this issue - let us take a look if we could improve message here.
