### ISSUE TITLE
Agent Installation: Disable the auto start during the Windows Service setup

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-agent#3430]
Dear All,

We are running the Agent as interactive process with --once argument (take offline when a Job completed).
However, we would like to also deploy the Windows Service mode as failsafe running method.

When the Windows Service has been created with "sc create" for the  "V1\bin\AgentService.exe", the new service running but there is nothing happens on the Agent side technically. 
There is no log has been created into the "V1\_diag", the status is still Offline on the ADO side.

When deploying the Windows Service with the bundled ".\config.cmd" utility with same infrastructure setup, everything is fine.
However, the Agent Installer is starting the service automatically on the last step which indicate strong side effects on our managed infrastructure. 

- Is there any specific criteria for the Windows Service-based running? Any flag which indicate the running method..etc
- is there any way to disable the auto-starting during the Agent installation?

Regards,
Gabor

**Comment by iambernics** [comment]
Dear All,

Do you have any update or idea about his case?

Regards,
Gabor

**Comment by kuleshovilya** [comment]
Hello @iambernics 
I guess there are three questions:
1. How to create service without config.cmd
Just run config.cmd, but don't create a service as it's suggested at the end, and after that create it with sc.exe
This method works fine.

2. Is there any specific criteria for the Windows Service-based running? Any flag which indicate the running method..etc
You can set Windows Services to Automatic\Manual\Delayed if that's what you mean?

3. is there any way to disable the auto-starting during the Agent installation?
There's somewhat of a workaround for that. When you create a service with config.cmd, just set it to non-existent account, or account that doesnt have a lot of rights, the launch of a service will fail, and you can confiure it to whatever you need after.

**Comment by kuleshovilya** [comment]
@iambernics Do you have any other questions?

**Comment by kuleshovilya** [comment]
@iambernics We've implemented flag for this in the agent, it's awaiting deployment now. I will notify you when it's going to be available publicly

**Comment by kuleshovilya** [comment]
The feature has been merged into agent and agent has been rolled out, closing the issue
