### ISSUE TITLE
Seeing difference free disk space available on build agents running same agent images

### ISSUE THREAD

**Issue by spacesluggy74** [microsoft/azure-pipelines-agent#3433]
## Agent Version and Platform
Current agent version: '2.187.2'
Current image version: '20210525.0'

## OS of the machine running the agent?
Microsoft Windows Server 2019
10.0.17763
Datacenter

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)
https://dev.azure.com/ellucian/

## What's not working?
We are using hosted agents running on the windows-2019 image. When our pipeline runs, the build agents selected have different amounts of free space available even though the same image is being used by both agents. Both have a current agent version of 2.187.2 and are on the same machine image of 20210525.0. 

Our pipeline will build using a hosted agent where the machine name starts with "fv-" and other times the build agent's name will start with "WIN-". The only other difference we can see in the agents besides the Agent Machine Name is the AgentPerflog location. "FV" uses C:\vsts and the "WIN" agents use C:\agents.

The first step of our pipeline reports the available disk space and the number, which should be close to 10, varies depending on which build agent is used. My question is why these are different when the same images are being used and each are building the exact same repository. We expect about 10 GB of free space but are seeing different availabilities depending on which build agent is used.  There is a difference of over 1.5 GB between the two different build agents. See pictures below for details on the pipeline job and the build agents free disk space variation.

![WIN Build Agent](https://user-images.githubusercontent.com/85361465/120839090-85e1b680-c536-11eb-9faf-6c1220b458d4.PNG)
![FV Build Agent](https://user-images.githubusercontent.com/85361465/120839093-867a4d00-c536-11eb-852f-eff1fe338fb5.PNG)

**Comment by EzzhevNikita** [comment]
Hi @spacesluggy74, Microsoft Hosted agents according to [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#my-pipeline-fails-with-the-error-no-space-left-on-device) guaranteed to have 10 GB of free disc space available for users (on some agents, this number could be bigger, but only 10 GB is guaranteed).

If you are seeing agents that provide less than 10 GB of free space you need to create an issue in this repo - https://github.com/actions/virtual-environments/issues. This team is supporting images for hosted agents and they have more context on questions related to images.

**Comment by EzzhevNikita** [comment]
Hey @spacesluggy74, could we close this item, or you still have questions?

**Comment by spacesluggy74** [comment]
@EzzhevNikita you can close this item. I will post my questions in the other repo as you suggested.
