### ISSUE TITLE
Self-hosted agents release stuck at "Initialize job"

### ISSUE THREAD

**Issue by rudolfdobias** [microsoft/azure-pipelines-agent#3437]
## Agent Version and Platform
Currently 2.187.2 but had same behavior also in 2.164.6
Ubuntu 18.04.5 LTS
The system uses a proxy which is set at 4 places:
 - /etc/environment (HTTP_PROXY, HTTPS_PROXY, VSTS_HTTP_PROXY)
 - `.proxy` file at agent's root folder
 -  `--proxyurl` parameter of config.sh used at the time of installation 
 - In Variables of the release pipeline

## Azure DevOps Type and Version
https://dev.azure.com/yieldigo 

## What's not working?
After triggering a release, the agent receives the job but never completes the "Initialize job" step. 
After 15 minutes of nothing the pipeline exits with error "We stopped hearing from agent (...)". 
After triggering another release the agent won't take another job because the worker is still "busy" with the previous job even it should be canceled. And it stays stuck in this state indefinitely. 

The agent appears online green in the Deployment targets all the time.

## Agent and Worker's Diagnostic Logs
Logs in attached files.
[agent_log.txt](https://github.com/microsoft/azure-pipelines-agent/files/6631917/agent_log.txt)
[worker_log.txt](https://github.com/microsoft/azure-pipelines-agent/files/6631918/worker_log.txt)

**Comment by anatolybolshakov** [comment]
Hi @rudolfdobias does this issue happen intermittently for you or all the time?

**Comment by rudolfdobias** [comment]
> Hi @rudolfdobias does this issue happen intermittently for you or all the time?

Hi @anatolybolshakov, it happens all the time, no successful run yet.

Another information I forgot to mention - the host OS runs in a lxc container, maybe IT has something to do with this issue...

**Comment by anatolybolshakov** [comment]
@rudolfdobias could you please try to run it with environment variable VSTSAGENT_TRACE=true and share agent logs - for us to understand where it exactly hangs?
You can also send them to my email: v-anbols@microsoft.com

**Comment by Ollie-Armitage** [comment]
Hi, I'm having a similar issue to this but just with the initial configuration of the agent (./config.sh). I'm running debian 10 (did try 9 no difference), also from LXC container. I go through the configuration process:
1) Accept the Team Explorer license
2) Accept the Team Explorer URL
3) Enter the PAT,

and this is where it hangs indefinitely. Here's the log:

[Agent_20210620-085241-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/6681969/Agent_20210620-085241-utc.log)

Tried in a debian 10 VM, same steps, worked just fine, which leads me to believe this is an issue with running it on LXC containers, but what?

**Comment by anatolybolshakov** [comment]
Hi @Ollie-Armitage could you please check that issue is not related to OOM killer?
You can follow next steps to check it on your environment:
1) Set up ‘PIPELINE_JOB_OOMSCOREADJ’ environment variable as ‘-1000’ – to set up default oom_score_adj value for agent child processes as -1000.
2) Run ‘echo -1000 > /proc/$$/oom_score_adj’ – to set oom_score_adj for current shell as -1000.
3) Run agent interactively (by running run.sh script) from current shell.

**Comment by Ollie-Armitage** [comment]
Hi @anatolybolshakov, Sorry for the slow reply. I'd switched to just using a VM, but strangely setting up a new LXC container again it now works (I did do this multiple times before). I will note that on the day this was occurring there seemed to be an issue with PAT codes in general (it was taking around half an hour to generate each code on azure), so this might have been outside the scope of the agent.

Cheers anyway.

**Comment by anatolybolshakov** [comment]
@Ollie-Armitage ok got it! Let me close this one since it's resolved - feel free to ask any further questions.
