### ISSUE TITLE
unable to run azure-devops shell script tasks on docker-linux agent

### ISSUE THREAD

**Issue by msrinivascharan** [microsoft/azure-pipelines-agent#3440]
I have a shell script (file.sh) with echo message. Created self hosted agent in a Linux container with the help of Microsoft documentation.

Created a pipeline job with "Bash" task to run the shell script (file.sh).

End up with no outcome, though build successful. no error, no outcome on console. PFB error screen. please suggest.

![image](https://user-images.githubusercontent.com/13816538/122002766-2b3f2a80-cd80-11eb-9c3e-3c507099b75a.png)

![image](https://user-images.githubusercontent.com/13816538/122003348-f97a9380-cd80-11eb-93bb-6c8db7a1a2df.png)

Below is the .sh file.

#!/bin/sh
echo Hello world

Note: I am able to run same shell script from inside (docker exec -ti bash) the container.

**Comment by DenisRumyantsev** [comment]
Hi @msrinivascharan, could you please provide us [agent logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#agent-diagnostic-logs), [worker logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#worker-diagnostic-logs), and **the agent version** you use?

**Comment by DenisRumyantsev** [comment]
Hi @msrinivascharan, could you also add `cat *.sh` line into your script?

**Comment by msrinivascharan** [comment]
Hi @DenisRumyantsev .. Fixed this by making shell script executable (chmod +x file.sh) before commit and push it to git repo. thank you for your inputs.
