### ISSUE TITLE
Unable to install multiple environments on the same machine (with default agent names) when running as a service

### ISSUE THREAD

**Issue by bwgit** [microsoft/azure-pipelines-agent#3449]
## Agent Version and Platform
	
2.188.2 Windows Server 2019 Standard

## Azure DevOps Type and Version
dev.azure.com

https://bolinda.visualstudio.com

## What's not working?
Unable to install multiple environments on the same machine when running as a service. By default the agent name is the machine name. When installing an environment as a service the service name is defined as:

`vstsagent.{0}.{1}.{2}`

`{1}` is replaced with the `poolName` - however for environments - `poolName` is empty which results in:

`vstsagent.bolinda..machinename`

When we config another environment on the same machine (with the default agent name) - the existing service is replaced.

It would be ideal if the service name / display name included the environment name in place of where the pool name exists on build agents.

`src/Agent.Listener/Configuration/ServiceControlManager.cs`  generates the service name - but poolName is empty in the case of environments.

## Workaround

Specify a different agent name (other than the default machine name) for each environment.

**Comment by AnnaOpareva** [comment]
Hi, @bwgit Agent that contains the fix for the described issue has been released (v2.189.0). Could you test - does it works for you? Feel free to ping us if you will have any problem with it.

**Comment by bwgit** [comment]
Yes this works perfectly now.

Thankyou!
