### ISSUE TITLE
Unable to configure a new agent : Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by yashali** [microsoft/azure-pipelines-agent#3459]
## Agent Version and Platform
Version of your agent? vsts-agent-linux-x64-2.188.4

OS of the machine running the agent? Ubuntu 20.04.2 LTS

## Azure DevOps Type and Version
dev.azure.com 

If on-premises, which release? N/A

## What's not working?
We had some 12 agents running on one Az VM (Ubuntu 20.04.2 LTS) as processes (`./config.sh && screen ./run.sh`). All was well..

I had to run some command related to /tmp folder but it kept showing busy and we suspected that our Agents might be using /tmp. Unfortunately instead of any other clean way of stopping the agents, we killed all processes on this VM manually, including the agents'.

After the /tmp related command ran successfully, I tried running `screen ./run.sh` from one of the agent directories. And I got an error:

`Failed to create CoreCLR, HRESULT: 0x80004005`

I also had tried : 

`.agent2/run.sh ` and I got the error : 

```
ldd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory
ldd: ./bin/System.Net.Http.Native.so: No such file or directory
Failed to create CoreCLR, HRESULT: 0x80004005
```

I even downloaded a new .tar for the agent and ran a fresh `./config` . But I get the same error on `./config` as well

Is there a solution to this? Please help

**Comment by alexander-smolyakov** [comment]
@yashali, could you please try disabling CoreCLR diagnostics by setting the environment variable `export COMPlus_EnableDiagnostics = 0`, and then try running `./config` from the agent directory?

**Comment by yashali** [comment]
:) thanks! It worked

**Comment by danishskyhive** [comment]
I did export COMPlus_EnableDiagnostics=0 but still the agent startup failed with error Failed to create CoreCLR, HRESULT: 0x80004005
