### ISSUE TITLE
VSTS agent cannot access Azure CLI

### ISSUE THREAD

**Issue by AmitShewani** [microsoft/azure-pipelines-agent#3465]
## Agent Version and Platform
2.188.2 windows

OS: windows (Self hosted)

## What's not working?
From raw logs:

Using Azure CLI, trying to execute the powershell script, this is what I get:

![image](https://user-images.githubusercontent.com/28490530/126264157-cbf49b7e-fae3-47dd-b13a-509d80bbafea.png)

On the agent's VM, I have installed the cli when logged in as **my user account**,

![image](https://user-images.githubusercontent.com/28490530/126264295-365d3d8d-521d-41b5-b994-6e1162bff4d8.png)

The vsts agent is running as a **network service**

![image](https://user-images.githubusercontent.com/28490530/126264562-3e7eaf98-411b-4fc7-a78d-b3725a4d1228.png)

The same thing when ran through the Microsoft hosted agent works as expected. What am I missing here?

**Comment by tatyana-kostromskaya** [comment]
Hello @AmitShewani , did you try to restart the service after you had installed Azure CLI?

**Comment by AmitShewani** [comment]
@tatyana-kostromskaya , yes I did restart the service and restarted the server as well but it still didn't work.

**Comment by AmitShewani** [comment]
@tatyana-kostromskaya , I reinstalled the agent, verified that the system variables exist and restarted the machine. Still getting the same error.
