### ISSUE TITLE
Linux Agent Install Error: KeyError: 'substatus'. Missing substatus key in status file.

### ISSUE THREAD

**Issue by skarlupka** [microsoft/azure-pipelines-agent#3476]
## Agent Version and Platform
Version of your agent? 2.189.0

OS of the machine running the agent? Ubuntu 20.04

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
When using a VMSS agent pool the agents hang in the creating state. After logging into the system the logs report that the "substatus" key is missing via a python stack trace while completing the pre_validation_checks function. Upon further investigation, the /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2/status/1.status json file is missing the substatus key. When I add `"substatus": []` to the status file and restart `walinuxagent` the DevOps agent script finishes successfully. Its unclear how this initial status file is missing the "substatus" key

## Agent and Worker's Diagnostic Logs
[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2/Handler.sh -enable
[stdout]
2021/07/29 13:22:08 ERROR:[Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2] 'substatus'

[stderr]
Running scope as unit: Microsoft.VisualStudio.Services.TeamServicesAgentLinux_1.21.0.2_fabf314b-eb1f-45be-a353-5922a3f0c110.scope
Traceback (most recent call last):
File "./AzureRM.py", line 702, in main
enable()
File "./AzureRM.py", line 611, in enable
pre_validation_checks()
File "./AzureRM.py", line 147, in pre_validation_checks
handler_utility.add_handler_sub_status(Util.HandlerSubStatus('PreValidationCheckSuccess'))
File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2/Utils/HandlerUtil.py", line 458, in add_handler_sub_status
sub_status_list = status_object['status']['substatus']
KeyError: 'substatus'
                        
During handling of the above exception, another exception occurred:
                        
Traceback (most recent call last):
File "./AzureRM.py", line 715, in <module>
main()
File "./AzureRM.py", line 712, in main
set_error_status_and_error_exit(e, 'main', 9)
File "./AzureRM.py", line 98, in set_error_status_and_error_exit
handler_utility.set_handler_error_status(e, operation_name)
File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2/Utils/HandlerUtil.py", line 494, in set_handler_error_status
self.add_handler_sub_status(handler_sub_status)
File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.21.0.2/Utils/HandlerUtil.py", line 458, in add_handler_sub_status
sub_status_list = status_object['status']['substatus']
KeyError: 'substatus
"

**Comment by ajorkowski** [comment]
I'm seeing the same issue unfortunately :( Starting yesterday our instances do not start on our VMSS agent pool, getting the same error as described above.

**Comment by MattMencel** [comment]
I switched the VM SKU from `Standard_F2s_v2` to `Standard_F4s_v2` and increased disk size to 128GB from 32GB.

My agents are deploying now.

I also noticed however there is a newer release, 2.190.0, that just appeared so it's also possible that was the fix.

**Comment by mmrazik** [comment]
This is already resolved. The offending changes have been rolled back few days back.
