### ISSUE TITLE
Health probe

### ISSUE THREAD

**Issue by hbuckle** [microsoft/azure-pipelines-agent#3478]
## Agent Version and Platform
Version of your agent? 2.189.0

OS of the machine running the agent? Any

## Azure DevOps Type and Version
dev.azure.com

## Question
Does the agent expose a health check endpoint of any kind? I want to use automatic instance repairs on my scale set agents to detect machines that fail to start and delete them but it needs a health probe to work.

**Comment by anatolybolshakov** [comment]
Hi @hbuckle you can use Azure DevOps Services [Api](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/agents/get?view=azure-devops-rest-6.0#taskagent) to retrieve agent on/off status.

**Comment by hbuckle** [comment]
That's not quite what I'm after - I was looking for a way to add a health probe to a scale set to detect whether the agent is running or not. It needs to be a local tcp or http endpoint that the load balancer probe can call (like a liveness probe)

Reference - https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension

**Comment by anatolybolshakov** [comment]
@hbuckle got it - this sounds like scale set feature which is out of scope of agent itself - could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by hbuckle** [comment]
Well the agent itself needs to expose an http or tcp endpoint. This isn't specifcally linked to the built in azure devops scale set feature - you might want to monitor the agent health if you are installing and running it yourself (especially in containers)

**Comment by anatolybolshakov** [comment]
@hbuckle by the current design agent does not provide any endpoints - bringing this new feature will require additional security risks analysis and clarification of the purpose of this - so [developer community](https://developercommunity.visualstudio.com/search?space=21) would be a better place to give heads up on this one.

Currently you can verify agent health locally:
- For interactive mode - by checking agent output to the terminal
- For service mode - by checking service health status

**Comment by anatolybolshakov** [comment]
Let me close this one since this is a larger feature not only related to the agent itself.
