### ISSUE TITLE
UnitTest localization bugs

### ISSUE THREAD

**Issue by echalone** [microsoft/azure-pipelines-agent#3481]
# UnitTest localization problems
Five UnitTests have problems on some non-english systems (at least in German, French, Italian and Spanish) and will fail although they shouldn't. This is due to differently named system accounts in different languages and different decimal separators in different language cultures.

**I would have already fixed the problem in those UnitTests and have already created a pull request** to the master branch of this repository: https://github.com/microsoft/azure-pipelines-agent/pull/3473
**The pull request needs to be reviewed and accepted.**

## Failing UnitTests
**Microsoft.VisualStudio.Services.Agent.Tests.Listener.Configuration.ArgumentValidatorTestsL0.WindowsLogonAccountValidator**
*Fails on some non-english Windows systems with message*: Expected: True/Actual: False; Assert.True() Failure
*Reason*: On some non-english Windows systems (German, French, Italian and Spanish) the local service account is named differently, this should be taken into account (pun intended).
*The different account names are*:
* German: NT-AUTORITÄT\LOKALER DIENST
* French: AUTORITE NT\SERVICE LOCAL
* Italian: NT AUTHORITY\SERVIZIO LOCALE
* Spanish: NT AUTHORITY\SERVICIO LOC

**Test.L0.Listener.Configuration.NativeWindowsServiceHelperL0.EnsureGetDefaultServiceAccountShouldReturnNetworkServiceAccount**
*Fails on some non-english Windows systems with message*: Expected: True/Actual: False; If agent is getting configured as build-release agent, default service accout should be 'NT AUTHORITY\NETWORK SERVICE'
*Reason*: On some non-english Windows systems (German, French, Italian and Spanish) the network service account is named differently, this should be taken into account.
*The different account names are*:
* German: NT-AUTORITÄT\NETZWERKDIENST
* French: AUTORITE NT\SERVICE RÉSEAU
* Italian: NT AUTHORITY\SERVIZIO DI RETE
* Spanish: NT AUTHORITY\SERVICIO DE RED

**Test.L0.Listener.Configuration.NativeWindowsServiceHelperL0.EnsureGetDefaultAdminServiceAccountShouldReturnLocalSystemAccount**
*Fails on some non-english Windows systems with message*: Expected: True/Actual: False; If agent is getting configured as deployment agent, default service accout should be 'NT AUTHORITY\SYSTEM'
*Reason*: On some non-english Windows systems (German and French) the system account is named differently, this should be taken into account.
*The different account names are*:
* German: NT-AUTORITÄT\SYSTEM
* French: AUTORITE NT\SYSTEM

**Microsoft.VisualStudio.Services.Agent.Tests.Worker.CodeCoverage.CoberturaSummaryReaderTests.VerifyCoberturaCoverageStatisticsForValidSummaryFile**
*Fails on some non-english Windows systems with message*: Expected: 2/Actual: 24; Assert.Equal() Failure
*Reason*: On some non-english Windows systems (for example: German) the decimal separator in numbers isn't a point (but, for example, a comma). However, the hard coded test xml uses a point as the decimal separator for all numbers. It is assumed that the coverage tool will generate an xml with decimal separators according to the culture of the installed system, so the test xml should be adapted according to the culture of the installed system as well. The UnitTest should work fine after this adaption as the code already handles it that way.

**Microsoft.VisualStudio.Services.Agent.Tests.Worker.TestResults.XUnitResultReaderTests.ReadResultsReturnsCorrectValues**
*Fails on some non-english Windows systems with message*: 1042.2319/Actual: 1042,2319; Assert.Equal() Failure
*Reason*: On some non-english Windows systems (for example: German) the decimal separator in numbers isn't a point (but, for example, a comma). However, the hard coded test xml uses a point as the decimal separator for all numbers. It then generates strings out of numbers and compares those to the values read in from the test xml. However, those then might differ if the culture of the installed system does not use a point as the decimal separator. To be sure to generate the correct string out of numbers so the comparison won't fail we have to specifically state which decimal separator (the point) we want to use when generating a string out of numbers in the UnitTest.

## Agent Version and Platform
Latest master source code (since it's UnitTests) or latest version v2.189.0 of the agent.
OS of the machine running the UnitTests: Windows
Language of machine running the UnitTests: German, French, Italian, Spanish (potentially other languages if decimal separator isn't a point in those languages)

## UnitTest output
[xUnit.net 00:00:02.9401910]   Discovering: Test&#xD;
[xUnit.net 00:00:03.4152420]   Discovered:  Test&#xD;
[xUnit.net 00:00:03.5566454]   Starting:    Test&#xD;
[xUnit.net 00:00:04.3653681]       If agent is getting configured as deployment agent, default service accout should be 'NT AUTHORITY\SYSTEM'&#xD;
[xUnit.net 00:00:04.3657665]       Expected: True&#xD;
[xUnit.net 00:00:04.3660228]       Actual:   False&#xD;
[xUnit.net 00:00:04.3725354]       Stack Trace:&#xD;
[xUnit.net 00:00:04.3737561]         D:\GitHub\echalone\azure-pipelines-agent\src\Test\L0\Listener\Configuration\NativeWindowsServiceHelperL0.cs(54,0): at Test.L0.Listener.Configuration.NativeWindowsServiceHelperL0.EnsureGetDefaultAdminServiceAccountShouldReturnLocalSystemAccount()&#xD;
[xUnit.net 00:00:04.4199174]       If agent is getting configured as build-release agent, default service accout should be 'NT AUTHORITY\NETWORK SERVICE'&#xD;
[xUnit.net 00:00:04.4201525]       Expected: True&#xD;
[xUnit.net 00:00:04.4202063]       Actual:   False&#xD;
[xUnit.net 00:00:04.4203190]       Stack Trace:&#xD;
[xUnit.net 00:00:04.4204858]         D:\GitHub\echalone\azure-pipelines-agent\src\Test\L0\Listener\Configuration\NativeWindowsServiceHelperL0.cs(36,0): at Test.L0.Listener.Configuration.NativeWindowsServiceHelperL0.EnsureGetDefaultServiceAccountShouldReturnNetworkServiceAccount()&#xD;
[xUnit.net 00:00:04.5100850]       Assert.Equal() Failure&#xD;
[xUnit.net 00:00:04.5101459]                     ↓ (pos 4)&#xD;
[xUnit.net 00:00:04.5104088]       Expected: 1042.2319&#xD;
[xUnit.net 00:00:04.5104636]       Actual:   1042,2319&#xD;
[xUnit.net 00:00:04.5105159]                     ↑ (pos 4)&#xD;
[xUnit.net 00:00:04.5106731]       Stack Trace:&#xD;
[xUnit.net 00:00:04.5107625]         D:\GitHub\echalone\azure-pipelines-agent\src\Test\L0\Worker\TestResults\Legacy\XUnitResultReaderTests.cs(215,0): at Microsoft.VisualStudio.Services.Agent.Tests.Worker.TestResults.XUnitResultReaderTests.ReadResultsReturnsCorrectValues()&#xD;
[xUnit.net 00:00:05.8140472]       Assert.Equal() Failure&#xD;
[xUnit.net 00:00:05.8141035]       Expected: 2&#xD;
[xUnit.net 00:00:05.8141383]       Actual:   24&#xD;
[xUnit.net 00:00:05.8141845]       Stack Trace:&#xD;
[xUnit.net 00:00:05.8142493]         D:\GitHub\echalone\azure-pipelines-agent\src\Test\L0\Worker\CodeCoverage\CoberturaSummaryReaderTests.cs(167,0): at Microsoft.VisualStudio.Services.Agent.Tests.Worker.CodeCoverage.CoberturaSummaryReaderTests.VerifyBranchCoverageStats(List`1 coverageStats)&#xD;
[xUnit.net 00:00:05.8143303]         D:\GitHub\echalone\azure-pipelines-agent\src\Test\L0\Worker\CodeCoverage\CoberturaSummaryReaderTests.cs(40,0): at Microsoft.VisualStudio.Services.Agent.Tests.Worker.CodeCoverage.CoberturaSummaryReaderTests.VerifyCoberturaCoverageStatisticsForValidSummaryFile()&#xD;
[xUnit.net 00:00:06.4075994]       Assert.True() Failure&#xD;
[xUnit.net 00:00:06.4076571]       Expected: True&#xD;
[xUnit.net 00:00:06.4077016]       Actual:   False&#xD;
[xUnit.net 00:00:06.4077498]       Stack Trace:&#xD;
[xUnit.net 00:00:06.4078355]         D:\GitHub\echalone\azure-pipelines-agent\src\Test\L0\Listener\Configuration\ArgumentValidatorTestsL0.cs(59,0): at Microsoft.VisualStudio.Services.Agent.Tests.Listener.Configuration.ArgumentValidatorTestsL0.WindowsLogonAccountValidator()&#xD;
[xUnit.net 00:00:16.8175986]   Finished:    Test&#xD;

**Comment by anatolybolshakov** [comment]
Hi @echalone sorry for the delay - thanks for the PR! We are working on more prioritized issues at the moment, and there is some fix for agent tests which are not being run on systems with non-english locales, so it was deprioritized - we are going to review it in the near time.

**Comment by echalone** [comment]
Also not really stale, sorry only saw it now, can we please reopen this?
