### ISSUE TITLE
[Feature request] Add new agent capability that allows repositories to be checked out below work directory level on self hosted agents

### ISSUE THREAD

**Issue by echalone** [microsoft/azure-pipelines-agent#3483]
This is a feature request for a new agent capability that would allow self hosted agents to check out repositories below the work directory level (so for example below "/_work", instead of just below the build pipeline directory level for example "/_work/1"), so large repositories can be shared between build pipelines without taking up space for each and every pipeline.
This feature should be disabled by default as pipelines could otherwise interfere with each other on public agents or users on public agents could change configuration files below the work directory, which would pose a security risk.
It could for example be activated by passing a flag to the configuration command in the command line when configuring the agent.

**I would have already implemented this feature as described and have already created a pull request** to the master branch of this repository: https://github.com/microsoft/azure-pipelines-agent/pull/3475
**The pull request needs to be reviewed and accepted.**

A more thorough description of how the feature was implemented can be found in the pull request.

**Comment by DaniilShmelev** [comment]
Hi @echalone! We'll take a look at your PRs, thanks!

**Comment by echalone** [comment]
> 
> 
> Hi @echalone! We'll take a look at your PRs, thanks!

Thanks! :)

**Comment by echalone** [comment]
> Hi @echalone! We'll take a look at your PRs, thanks!

Hi, by now I had to fix merge conflicts in two of the pull requests since they are still open after half a year. I'm answering here hoping maybe this gets noticed before they are forgotten (I marked you in the pull requests too but I don't think that will trigger a notification). We are Microsoft Gold Partner if that helps with budgeting time for the bugfixes and the new work directory repository capability. Just tell me if you need information about that partnership for accounting or something like that.

**Comment by DaniilShmelev** [comment]
Hi @echalone! We have your PRs with suggestions in the backlog currently. We'll take a look at them later.

**Comment by anatolybolshakov** [comment]
@echalone by the way for the current agent implementation - for the self-hosted case it already re-uses build directory (and already checked out repositories) - if there is the same collection, pipeline definition id and the set of repositories used in a pipeline definition.

**Comment by echalone** [comment]
> @echalone by the way for the current agent implementation - for the self-hosted case it already re-uses build directory (and already checked out repositories) - if there is the same collection, pipeline definition id and the set of repositories used in a pipeline definition.

Of course, but we'd need it for different pipeline definition ids because of different variables and different triggers ;)

**Comment by echalone** [comment]
can we reopen this feature request since it's still open?
