### ISSUE TITLE
Options to either capitalise variables or leave them lowercase

### ISSUE THREAD

**Issue by byteknacker** [microsoft/azure-pipelines-agent#3514]
## General Infos
Agent name: 'Hosted Agent'
Current agent version: '2.190.0'
Ubuntu 20.04.2 LTS
dev.azure.com

## What's not working?
- Current agent behaviour: replace . with _ and toUpper() every definition variables when it run every task
- Problem: When using Terraform, it expects TF_VAR_{name of your TF var} to be case sensitive. When you define the configuration in TF, usually you use lowercase. This leads to using env vars like TF_VAR_rg_shared_name so that Terraform can take it up as its own variable named rg_shared_name and use it for the configuration. Now, if the Azure Pipeline agent is going to make everything uppercase, then I have to rename each and every single of my TF vars back to lowercase. This is very time consuming and unnecessary. 
- Proposed solution: have an optional flag or property on the variable definition in YAML such that you can choose to either leave the env vars as they are, which is expected, or to apply certain selected functions on them, such as toUpper(). 
- Example of the proposed solution:

**_YAML file that defines a Azure Pipeline_** 

```
variables:
- name: TF_VAR_awesomevar
  value: rg_awesomeapp_dev
  function: toUpper()
- group: vg-fantasticapp-infra-shared
   function: none #which is the default
```

Inside the variable group vg-fantasticapp-infra-shared there is another variable named TF_VAR_fantasticapp with the value rg_fantasticapp_test.

At runtime, I expect the variables to be resolved to:
```
TF_VAR_AWESOMEVAR=rg_awesomeapp_dev
TF_VAR_fantasticapp=rg_fantasticapp_test
```

Some final comments:

Personally, I find it easier to have the agent do things as you expect it to do by default without silently applying functions at the background. The vanilla version of some action can be just simple without any transformations. If you want transformations, then by all means add options to it. 

Relates to Issue #1645

**Comment by byteknacker** [comment]
Is there any progress on this?

**Comment by Soruk** [comment]
Hi,
Why this issue is closed automatically without any comment.
It is not fixed and I have issue with terraform => I will have to generate tfvars file to do a bypass this limitation.
