### ISSUE TITLE
Please provide a latest download URL for each package to assist with automation

### ISSUE THREAD

**Issue by NorseGaud** [microsoft/azure-pipelines-agent#3522]
We have a need to download the latest package/release for macOS and don't see a way to automate this easily without fixing the version and interpolating it in the `https://vstsagentpackage.azureedge.net/agent/${VERSION}/vsts-agent-osx-x64-${VERSION}.tar.gz`. We are requesting that this be made easier by providing a redirect to the latest package. Something like `https://vstsagentpackage.azureedge.net/agent/latest/vsts-agent-osx-x64.tar.gz`

**Comment by NorseGaud** [comment]
Temporary solution (yuck)

```
curl -s -L https://github.com/microsoft/azure-pipelines-agent/releases/latest | grep https:\/\/.*vsts-agent-osx-x64 | egrep -o 'https?://[^ "]+'
```

**Comment by svbrburgman** [comment]
Doing pretty much the same on windows with powershell on windows, but a little more advanced using the Rest API.
The last step is a bit dirty. It's JSON so I could just read the json and distict the platform, but you will still end up with two download links (pipeline and VTST agent) so i took the same shortcut as you did and grepped (select-string) on "vtst-agent" in the end. 
```
$a = (Invoke-RestMethod "https://api.github.com/repos/microsoft/azure-pipelines-agent/releases/latest") 
$b= Invoke-RestMethod $a.assets_url
$c= invoke-restmethod $b.browser_download_url
$dl = $c.downloadurl | Select-String -Pattern 'vsts-agent-win-x64'
```

**Comment by anatolybolshakov** [comment]
Hi @NorseGaud thanks for reporting! We are working on more prioritized items, but will get back to this one once be able to.

**Comment by NorseGaud** [comment]
Bump.

**Comment by mitoihs** [comment]
I would also like to use that. Does "closed as completed" mean it's done?

**Comment by j0nathontayl0r** [comment]
@NorseGaud, there's no linked PR from what I see. It's not obvious to me what URL we should be using to target $latest short of using something like the scripts listed above?

**Comment by NorseGaud** [comment]
Sorry @j0nathontayl0r, we ditched the azure pipelines/devops stuff years ago. The repo is private now. 

Why couldn't y'all provide something like `/agent/latest`?

**Comment by gitnubster** [comment]
You all gonna love this!
https://dev.azure.com/<org>/_apis/distributedtask/packages/agent?%24top=1

Extracted from azure devops services page where you can find the latest agent download.
