### ISSUE TITLE
Agent.Listener should run at a higher priority than build tasks

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/azure-pipelines-agent#3541]
In the vcpkg build fleet we are seeing a lot of 

![We stopped hearing from agent AGENTNAME. Verify the agent machine is running and has a healty network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access...](https://user-images.githubusercontent.com/1544943/134257055-c5397652-b792-4f3a-80a4-71526bc7844c.png)

failures, particularly when building large/expensive ports that want lots of CPU, like TensorFlow. Then the agent comes back on its own.

The thing is, Agent.Listener and Agent.Worker being starved for CPU is probably normal: the whole point of pipelines is to run build tasks, and build tasks want lots of cores. The agent should take some steps to avoid work it creates from taking the machine to the point it causes Pipelines to abandon the job. Ideally the worker could do something like set `nice(1)`?

## Agent Version and Platform
Version of your agent? 2.192.0, although we have seen the problem across many agent versions.

OS of the machine running the agent? OSX, although we have seen the problem on other operating systems. (We just trigger it on OSX most often because those machines have fewer cores)

## Azure DevOps Type and Version
dev.azure.com/vcpkg

## What's not working?
When doing big builds, agents regularly die and get the "we stopped hearing from ..." error.

## Agent and Worker's Diagnostic Logs
Not collected yet, since this is an enhancement request. If you want specific logs I may be able to collect them.

**Comment by lonevvolf** [comment]
We are seeing the same at least once per day.  We have a ticket open with MS, but that doesn't seem to be leading to much yet.  One build pipeline which sees this every day is actually a simple backup pipeline which copies our git repos to an external storage.  This fails with the same message, and no one can figure out what's going on.  The agent is running on a Windows image in this case, built with the standard Microsoft scripts.

**Comment by BillyONeal** [comment]
> Hi @BillyONeal please see options to set up memory limits for worker process/recommendations for oom_score_adj parameter value in [docs](https://github.com/microsoft/azure-pipelines-agent/blob/b93f8f1f4e53ddf5d9cd25090db6f71b092d177c/docs/start/resourceconfig.md).

We see the problem on all operating systems when building something that heavily uses the machine, not just Linux. It looks starved for CPU rather than RAM. The screenshot in my original post is from a MacOS machine, for instance.

However, we have seen this happen much less frequently recently. I don't know if that's something that changed in the Agent or something we changed. (And most of the cases I know about are correlated with Azure Spot just eating the whole agent :) )

**Comment by BillyONeal** [comment]
I have not seen this happen near as much recently but unless the product code is actually launching things at a lower priority I don't think this is truly fixed, as one of our workarounds right now is just using a much bigger machine than would otherwise be necessary.
