### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Manoj496** [microsoft/azure-pipelines-agent#3545]
Hi,

We've build agent version : 2.187.2. From past two weeks all our pipelines are facing issue downloading chocolatey. It says path is denied. Is it something do with updating build agents?

@azure-pipelines-bot

or else what can be done to run the pipelines back again. 

_Originally posted by @Manoj496 in https://github.com/microsoft/azure-pipelines-agent/issues/3519#issuecomment-926191604_

**Comment by EzzhevNikita** [comment]
Hi @Manoj496, could you please provide some additional information on this issue?
* Please share agent logs, they ould be found in __diag_ folder in the agent directory.
* Please share pipeline logs where you see described issue. I believe that it is an issue with a task that you are using in your pipeline to download chocolatey, but not with an agent.

**Comment by Manoj496** [comment]
Hi @EzzhevNikita 

Copy-Item : Access to the path 'C:\ProgramData\chocolatey\lib\chocolatey\chocolatey.nupkg' is denied.
At C:\agent1\_work\_temp\choco_install.ps1:555 char:1
+ Copy-Item -Path $file -Destination $nupkg -Force -ErrorAction Silentl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.CopyItemCommand

Do you reckon any inputs on this?

**Comment by Manoj496** [comment]
Means we tried all the possible ways to figure this out. But yeah build agents has nothing to do with this I guess?

**Comment by EzzhevNikita** [comment]
@Manoj496 Yes, that doesn't seem to be any problems on the agent side. I assume the problem is caused by some changes in your local environment where the agent is running. If I were you, I would start by checking the permissions of these files, this issue could be caused by the lack of permissions to the described files.

**Comment by Manoj496** [comment]
Sure okay thanks then
