### ISSUE TITLE
in a build agent VMSS in azure the agent is running without a tty

### ISSUE THREAD

**Issue by flixman** [microsoft/azure-pipelines-agent#3546]
## Agent Version and Platform
2.192

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/sede-pt-ssw2

## What's not working?
After creating the base image for the Build Agent VMSS in Azure, and submitting a job that runs msbuild, msbuild fails with the following error:
```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
  at System.Diagnostics.Process.set_PriorityClass (System.Diagnostics.ProcessPriorityClass value) [0x00049] in <8aa7fd24d39b4905aac5b2d7bfb8c80f>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.set_PriorityClass(System.Diagnostics.ProcessPriorityClass)
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x001a4] in <6266dca5985e49a9873effc0a3594efb>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
  at System.Diagnostics.Process.set_PriorityClass (System.Diagnostics.ProcessPriorityClass value) [0x00049] in <8aa7fd24d39b4905aac5b2d7bfb8c80f>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.set_PriorityClass(System.Diagnostics.ProcessPriorityClass)
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x0045b] in <6266dca5985e49a9873effc0a3594efb>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Main () [0x00028] in <6266dca5985e49a9873effc0a3594efb>:0
```
Upon inspection we see that the agent is running through atd:
```
           ├─8119 /usr/sbin/atd -f
           ├─8121 sh
           ├─8122 /bin/bash
           ├─8123 sudo -E runuser AzDevOps -c /bin/bash /agent/run.sh
           ├─8125 runuser AzDevOps -c /bin/bash /agent/run.sh
           ├─8126 /bin/bash /agent/run.sh
           └─8131 /agent/bin/Agent.Listener run
```

Should we switch to the AzDevOps user, make sure that the environment is that of the agent (so sourcing /agent/.env and exporting the variables), and run the same command, the build proceeds as expected. If running the command with strace and observing what files get opened, on the case that succeeds we see that it opens /dev/tty, whereas in the case that does not fail this does not happen.

Should I kill the process Agent.Listener and use a systemd service file like the following one, the builds also succeed:
```
[Unit]
Description=vsts agent
After=network.target

[Service]
ExecStart=/agent/run.sh
User=AzDevOps
WorkingDirectory=/agent
KillMode=process
KillSignal=SIGTERM
TimeoutStopSec=5min

[Install]
WantedBy=multi-user.target
```
Obviously, writing a service that waits for Agent.Listener to show up, to kill it and start this systemd service is an option... but just means that something is off, right? :-/

This issue is preventing us to set the VMSS into production for linux, which is delaying us quite a bit. What can be done to fix this?

**Comment by anatolybolshakov** [comment]
Hi @flixman this issue seems to be related to the agent process permissions, not the agent itself. You would need to make sure that agent process has enough permissions in your environment to execute tasks.
For questions about VMSS - you can open ticket in https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.

**Comment by flixman** [comment]
@anatolybolshakov You have a point: as the agent runs properly when set through systemd... I will report this issue in that forum. Thank you!
