### ISSUE TITLE
Linux dependencies from https://packages.efficios.com fail as certificate has expired

### ISSUE THREAD

**Issue by andyfisher100** [microsoft/azure-pipelines-agent#3556]
The linux agent relies on dependencies from https://packages.efficios.com. These dependencies can be found in the installdependencies.sh file that is shipped with the agent. The specific package needed is "lttng-ust"

The rpmkey from efficios has now expired meaning that installing the dependencies on a new system is not possible unless using "--no-check-certificate", which whilst this may be a workaround, its not a secure solution.

Its also worth noting that the header of the efficios website states that the packages are in extended maintenance and wont be updated so perhaps a new solution is required for the long term?

Below is the output from building my docker file (we run agents as docker containers) which runs the same line that is contained in the dependencies.sh file

`#7 6.408 --2021-10-04 14:12:51--  https://packages.efficios.com/repo.files/EfficiOS-RHEL7-x86-64.repo
#7 6.418 Resolving packages.efficios.com (packages.efficios.com)... 167.114.26.116, 2607:5300:203:5aae::ef3d
#7 6.472 Connecting to packages.efficios.com (packages.efficios.com)|167.114.26.116|:443... connected.
#7 6.793 ERROR: cannot verify packages.efficios.com's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=R3':
#7 6.793   Issued certificate has expired.
#7 6.793 To connect to packages.efficios.com insecurely, use `--no-check-certificate'.`

**Comment by xlz-jgoutin** [comment]
This package is also provided by the EPEL repository that is more common and more reliable : https://centos.pkgs.org/7/epel-x86_64/lttng-ust-2.4.1-4.el7.x86_64.rpm.html

But, the provided version is older than the one of efficios repository (2.4.1 instead of 2.10.7 on CentOS7).

**Comment by anatolybolshakov** [comment]
Reopened to keep it until relevant changes are being deployed.

**Comment by martinowen** [comment]
Do we know when this fix will be deployed?

**Comment by max-zaytsev** [comment]
Just as a quick update - there is a delay in deploying these changes due to recent rollbacks. We are going to continue rolling out this fix after the New Year holidays.

**Comment by PongDoesPango** [comment]
> Just as a quick update - there is a delay in deploying these changes due to recent rollbacks. We are going to continue rolling out this fix after the New Year holidays.

Are there any updates on this subject? 

How is it possible to resolve this without creating a massive security pitfall?

TX in advance.

**Comment by max-zaytsev** [comment]
@PongDoesPango The [fix](https://github.com/microsoft/azure-pipelines-agent/pull/3601) was deployed with agent [2.196.2](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.196.2)

From the pr description:
>For TLS certificates issued by Let’s Encrypt, the root certificate (DST Root CA X3) in the default chain expires on September 30, 2021. Due to their unique approach, the expired certificate will continue to be part of the certificate chain till 2024. This affects OpenSSL 1.0.2k on RHEL/CentOS 7 servers, and will result in applications/tools failing to establish TLS/HTTPS connections with a certificate has expired message.
More info [here](https://blog.devgenius.io/rhel-centos-7-fix-for-lets-encrypt-change-8af2de587fe4)
