### ISSUE TITLE
BlobNotFound on v2.193.2

### ISSUE THREAD

**Issue by mivica** [microsoft/azure-pipelines-agent#3559]
Agent Downloads links for  [v2.193.2](https://github.com/microsoft/azure-pipelines-agent/releases) go to BlobNotFound.

![image](https://user-images.githubusercontent.com/9020093/135992698-97166299-b690-4cc0-bc76-1ac205df9bb6.png)

**Comment by DaniilShmelev** [comment]
Hi @mivica! Release 2.193.2 was created by mistake. We've already removed it, so please take take a look at [release V2.193.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.193.1).
Feel free to ping me if you have any issues!
