### ISSUE TITLE
Update PowerShellCapabilitiesProvider to work with Visual Studio 2022

### ISSUE THREAD

**Issue by tatyana-kostromskaya** [microsoft/azure-pipelines-agent#3569]
Update PowerShellCapabilitiesProvider to work with Visual Studio 2022. Right now it generates capabilities only for previous versions of VS

**Comment by durandt** [comment]
Hi, 

I an interested to know if you have any timeline for the resolution of this issue. 

Regards, 

Thibault

**Comment by albrookesplowman** [comment]
Do you know when this will be released?  I have just tried the prerelease version of 2.195 and it is behaving very strangely.  I have VS2022 deployed on a self hosted agent with the 2.195.0 pipeline agent installed and configured.  So far so good... When I run my build pipeline it works OK as well but at some point in the build process, it goes wrong as the agent version is suddenly changed to version 2.194 and then the pipeline will never run again.  The pipeline I have is a yaml one and I have made sure that the vsVersion in the VSBuild task is set to "Latest".  Are there any other changes I need to make to ensure that it stays on v2.195 and not revert back to 2.194..  When I look at the output of the build stage of my pipeline I have noticed that some things think it is 2.195 and others think it is 2.194 - very confusing.... Any ideas?

Starting: Initialize job
Agent name: 'ptrisk-build2'
Agent machine name: 'ptrisk-build'
Current agent version: '2.194.0'
Agent running as: 'ptrisk-build$'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: NuGetToolInstaller (1.179.0)
Downloading task: NuGetCommand (2.194.0)
Downloading task: VSBuild (1.192.3)
Downloading task: PublishBuildArtifacts (1.192.0)
Downloading task: UseDotNet (2.195.0)
Downloading task: CmdLine (2.182.0)
Checking job knob settings.
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

**Comment by durandt** [comment]
> Hi @durandt, do you need to get correct list of capabilities or new versions of tasks that support new VS?

I need the correct list of capabilities for older builds (.Net Framework etc...) to be able to queue on the agents. Right now I add the capabilities manually, but that's a regression compared to older VS-versions.

**Comment by tatyana-kostromskaya** [comment]
@durandt , agent 2.195.0 should be fully release in a week. Then it will be automatically updated in Hosted pools. This version has already contained this change.

@albrookesplowman, do you use on-prem Azure DevOps (Azure DevOps Server)? Most likely you agent automatically downgraded to lower version. Could you please try to update agent again to 2.195.0 and set environment variable `AZP_AGENT_DOWNGRADE_DISABLED` to `true ` before launching your agent?

**Comment by older** [comment]
Would this also detect capabilities provided by with Visual Studio 2022 Build Tools?

**Comment by Satan-Claus-666** [comment]
@older As I see for now, v2.195.0 works ok with Visual Studio 2022 Build Tools. These capabilities are added: MSBuild, MSBuild_17.0, MSBuild_17.0_x64, VisualStudio, VisualStudio_17.0, VisualStudio_IDE, VisualStudio_IDE_17.0.

**Comment by durandt** [comment]
My self-hosted agents are now updated to v2.195.0 and the capabilities working properly.

**Comment by tatyana-kostromskaya** [comment]
Changes were released

**Comment by ToreDemant** [comment]
@tatyana-kostromskaya : can you comment on why these build tasks are not made to respect any specific version given so that they would forward compatible when new Visual Studio versions are released?
