### ISSUE TITLE
Can't remove old agent

### ISSUE THREAD

**Issue by pedro-gilmora** [microsoft/azure-pipelines-agent#3580]
I upgraded the AzureDevops and forgot to remove old agent
When I try to remove old agent I get this, but I don't remember url or how to access and remove it
![error](https://user-images.githubusercontent.com/33942331/138810183-f4c55cfa-28ff-494a-b044-53495c86fc03.png)

What should I do in this case

**Comment by pedro-gilmora** [comment]
> Hi @pedro-gilmora You can delete files: .agent, .credentials, and .credentials_rsaparams from the folder with your agent and after that reconfigure the agent again.

I can't find those files, can you lead me please?

**Comment by AnnaOpareva** [comment]
Hi, @pedro-gilmora 
You need to set up "show hidden files" - like in this [tutorial](https://support.microsoft.com/en-gb/windows/show-hidden-files-0320fe58-0117-fd59-6851-9b7f9840fdb2), after that - you could find files: .agent, .credentials, and .credentials_rsaparams in the folder with your agent. 
It will be looking like this:
![image](https://user-images.githubusercontent.com/84513972/139634210-3a980730-ac59-4a49-ad4d-d3c9cefb6a1f.png)

**Comment by EzzhevNikita** [comment]
Hey @pedro-gilmora, did you manage to remove the old agent?

**Comment by pedro-gilmora** [comment]
@EzzhevNikita Yes I did, thanks, I've been too bussy here, but @AnnaOpareva gave the solution about hidden files. Thanks

**Comment by EzzhevNikita** [comment]
@pedro-gilmora Since the issue was resolved for you, I am closing this ticket. Feel free to create new issues in this repo in case of future questions.
