### ISSUE TITLE
Problem creating pipeline 

### ISSUE THREAD

**Issue by pedro-gilmora** [microsoft/azure-pipelines-agent#3590]
What's going on with my pipeline creator? I'm getting this error

![image](https://user-images.githubusercontent.com/33942331/139620732-a273fb9d-0931-42c5-8b1d-80ff6bc8e321.png)

**Comment by alexander-smolyakov** [comment]
Hi @pedro-gilmora, the pipeline creator is related to the Azure DevOps side - could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 to get the right eyes on it?

**Comment by alexander-smolyakov** [comment]
@pedro-gilmora, let me close this one at the moment since this issue is not related to the pipeline agent. Please feel free to ask any further questions.
