### ISSUE TITLE
[warning]Unable to find MSBuild version '14.0' for architecture 'x86'. Falling back to version '4.0'.

### ISSUE THREAD

**Issue by magol** [microsoft/azure-pipelines-agent#3600]
I get following output when I try to build with Visual Studio 2022 using build agent version 1.151.2
We are using Azure DevOps Server Version Dev17.M153.5 and have configure the build task to use the latest version of Visual Studio. 

```
##[command]"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.151.2\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -latest -format json
##[command]"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.151.2\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
##[command]"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.151.2\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -latest -format json
##[command]"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.151.2\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json

##[warning]Visual Studio was not found. Try installing a supported version of Visual Studio. See the task definition for a list of supported versions.
##[warning]Unable to find MSBuild version '14.0' for architecture 'x86'. Falling back to version '4.0'.

##[command]"C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" "C:\agent\_work\3\s\Source\Foo.sln" /nologo /nr:false /fl /flp:"logfile=C:\agent\_work\3\s\Source\Foo.sln.log;verbosity=normal" /dl:CentralLogger,"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.151.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=7eb43cc4-0a11-42ea-9084-1d5e577161b2|SolutionDir=C:\agent\_work\3\s\Source"*ForwardingLogger,"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.151.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /p:PlatformToolset=v142 /p:MyBinaryOutputPath=C:\agent\_work\3\b /p:TreatWChar_tAsBuiltInType=true /p:ConformanceMode=true /p:platform="x64" /p:configuration="ReleaseU" /p:_MSDeployUserAgent="TFS_0ab9ca53-8fd2-4470-8e40-506d7bd28f2d_build_4_0"
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 2021-11-08 23:56:24.
Project "C:\agent\_work\3\s\Source\Foo.sln" on node 1 (default targets).
```

The build fail, how should I do to make it works?

**Comment by bertrandpsi** [comment]
Same issue on my side. I tried first on a build system where 2019 and 2022 were installed, but the build task was always using 2019 even if the agent capabilities was showing both.

**Comment by durandt** [comment]
Azure pipeline agent v2.195.0 released a few days ago now fixes detecting capabilities for VS2022 on my self-hosted agents.

**Comment by bertrandpsi** [comment]
Tried it, still not detecting VS2022 on a system where both VS2019 and VS2022 are installed.

**Comment by akitest11** [comment]
Same issue

**Comment by blakeduffey** [comment]
I'm seeing this as well.  I've tried on a Windows 2019 server that has both VS 2019 and 2022, a Windows 2019 server that has VS 2022 and previously had VS 2019 (I removed it as a test) - and a fresh Windows 2019 server that ONLY has VS 2022 (has never had  any previous version of Visual Studio).  

I get the exact same error as the original poster.  

I've been monitoring the build agent github page and am running 2.195.1 - and the error persists.

**Comment by blakeduffey** [comment]
> Azure pipeline agent v2.195.0 released a few days ago now fixes detecting capabilities for VS2022 on my self-hosted agents.

Can you provide some additional details about your working setup?

**Comment by blakeduffey** [comment]
This thread is also relevant:  https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Ft%2Fazure-devops-20201-build-solution-task-not-working%2F1584426%3Ffrom%3Demail%26viewtype%3Dall%23T-ND1605167&data=04%7C01%7CBlake.Duffey%40noblis.org%7C6e62fef74fbc4c94492b08d9b8ced394%7Ce28cbc4d93e249b48c37dbdee2a3d319%7C0%7C0%7C637744020727685430%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=knMbjC0w3oS6g48UJBiKf%2FK7P6fLw6oFhLy%2FZgHDhLI%3D&reserved=0

**Comment by cfaagaard** [comment]
We are also seeing this.
Onprem devops server: 18.181.31626.1 (Azure DevOps Server 2020 Update 1.1)
Build agent: 2.195.2 on a build server with only vs2022 installed.

**Comment by tatyana-kostromskaya** [comment]
Could you please share list of your agent capabilities regards MSBuild and VisualStudio? Does it contain `VisualStudio_17.0` and `MSBuild_17.0`?

**Comment by cfaagaard** [comment]
@tatyana-kostromskaya where can I see the tasks versions (for all the tasks, I presume?)

**Comment by cfaagaard** [comment]
this screendump is from our vs2022-only buildserver. Is this the versionnumbers you are looking for?:
![image](https://user-images.githubusercontent.com/25353502/147255849-867d3229-994e-4a9f-a5d4-34ce734cc530.png)

**Comment by tatyana-kostromskaya** [comment]
@cfaagaard, yes, thank you. Also you can find versions of the tasks in build logs at the begging of each task.

VSBuild task started to support VS 2022 after 1.192.2 version. And as far as I can see you have 1.166.2.

**Comment by cfaagaard** [comment]
Yes, but I have installed the latest update for the Azure Devops Server. And the latest build agent:
Onprem devops server: 18.181.31626.1 (Azure DevOps Server 2020 Update 1.1)
Build agent: 2.195.2 on a build server with only vs2022 installed.

And this the only _supported_ way to get the Azure Devops Server updated (including task updates), as I understand it.

And yes, I can see the vsbuild-task (in github) has support for vs2022, but I need a _supported_ way to update our Azure Devops Server.

**Comment by cfaagaard** [comment]
> @cfaagaard, yes, thank you. Also you can find versions of the tasks in build logs at the begging of each task.
> 
> VSBuild task started to support VS 2022 after 1.192.2 version. And as far as I can see you have 1.166.2.

the versions in the build logs are the same as in the screendump.

**Comment by tatyana-kostromskaya** [comment]
I don't have information about future releases of Azure DevOps Server and when they will be released.
But official release update is the only fully supported way for task update.

Manual update of the tasks is a possible solution without very high risks and I can provide you zip archives with latest released versions of these tasks  and instruction how to update it manually. 
But again this solution is not fully supported and official.

**Comment by cfaagaard** [comment]
Thanks. but it needs to be supported.

**Comment by blakeduffey** [comment]
This really is an odd choice by MS to release VS22/.net 6 to much fanfare - but simply not support it via onprem pipelines.  What's the expectation for pipeline support?

**Comment by cfaagaard** [comment]
Any news on this issue? (some people start wondering if this a sign of Microsoft phasing out Azure Devops onprem??)

**Comment by Blinchik91** [comment]
issue still exists! BUILD IS NOT WORKING!

**Comment by tatyana-kostromskaya** [comment]
Azure DevOps Server is not released often, so all new changes came there with big delay. And as far as I know patches for existing versions of Azure DevOps Server usually contains fixes for the issues and not new features.

I don't have info about future release of Azure DevOps Server, so I can't say when VS 2022 will be available there.

**Comment by tivtag** [comment]
> Azure DevOps Server is not released often, so all new changes came there with big delay. And as far as I know patches for existing versions of Azure DevOps Server usually contains fixes for the issues and not new features.
> 
> I don't have info about future release of Azure DevOps Server, so I can't say when VS 2022 will be available there.

An official statement, installation guide & roadmap would be really nice and improve trust in the product.

We are really looking forward to use .NET 6/VS 2022 in our company, but this issue is blocking us. :-)
Thank you!

**Comment by jessehouwing** [comment]
Further expanded my temporary solution for [this problem for now and hopefully for future situations with a similar issue](
https://github.com/jessehouwing/azure-pipelines-tasks-zips). The project provides pre-built versions of the tasks as well as patched versions of the tasks that can be installed side-by-side the original tasks to prevent any breaking changes.

[Download the task from the latest release](https://github.com/jessehouwing/azure-pipelines-tasks-zips/releases) and [install them into you collection](https://github.com/jessehouwing/azure-pipelines-tasks-zips#installation).

Alternatively install the tasks through an extension:

* 🛍️ [Visual Studio 2022 for Azure DevOps Server](https://marketplace.visualstudio.com/items?itemName=jessehouwing.visualstudio)
* 🛍️ [DotNetCore 6 for Azure DevOps Server](https://marketplace.visualstudio.com/items?itemName=jessehouwing.dotnetcore)

## Required agent version
You will need to [install a recent agent (2.195.0 or newer) from the azure-pipelines-agent repository](https://github.com/microsoft/azure-pipelines-agent/releases) for it to auto-detect Visual Studio 2022, or alternatively add the capabilities to the agent manually.

You may need to force Azure DevOps Server to not downgrade back to its preferred agent version. You can do so by setting the following environment variable at the system level on your server before launching the agent:

```
AZP_AGENT_DOWNGRADE_DISABLED=true
```

**Comment by ckraenzel** [comment]
As a workaround, try setting:

msbuildLocationMethod: 'location' 
msbuildLocation: 'c:\YourInstallationPath'

for the MSBuild task. That way you can circumvent the vswhere localization. Not the most elegant way but it worked for us.
