### ISSUE TITLE
Use Service Principal or Managed Identity for self-hosted agent registration?

### ISSUE THREAD

**Issue by zojovano** [microsoft/azure-pipelines-agent#3604]
## Having issue with YAML?
Please log an issue at [Azure-Pipelines-YAML](https://github.com/Microsoft/azure-pipelines-yaml). Over there we discuss YAML templates, samples for Azure Pipelines, and designs for upcoming YAML features. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.

## Having issue with Tasks?
Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.

## Having issue with software on Hosted Agent?
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.

## Having generic issue with Azure-Pipelines/VSTS/TFS?
Please report it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...

OS of the machine running the agent? OSX/Windows/Linux/...

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com

## What's not working?
Is there any way to use Service Principal or Managed identity for self-hosted agent registration (instead of documented authentication methods: PAT, Basic, etc)?
In one of scenarios I am having, the agent is deployed as a container to Azure container Instances. From time to time the container get's restarted (unplanned) and PAT token was used to do re-registration after the container restart. With the PAT token expiration policies (e.g. max 6 months), we would need to proactively rotate PAT tokens, plus PAT tokens are associated with a person so in case person leaves the team/company the whole registration needs to be repeated... 

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by anatolybolshakov** [comment]
Hi @zojovano there are no such authentications methods available for pipeline agent and Azure DevOps as I know - these types are relevant for the Microsoft Azure platform.

**Comment by zojovano** [comment]
Hi, I understand that ADO is not aware of Azure Service Principal or Managed Identity but after all these are OAuth/OpenID protocols/tokens. Why is ADO not able to trust one of App Registrations (or User Assigned Managed Identities) for the agent registration? 
ADO uses AAD for user authentication, why it would not be able to use Service Principal or Managed Identity for service/app registration? (I understand this may not be possible at the moment)

**Comment by anatolybolshakov** [comment]
@zojovano these questions are more relevant for the ADO side, although this repo is mostly for the pipeline agent itself - could you please open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by anatolybolshakov** [comment]
@zojovano closing this at the moment since it's not related to the agent itself - please feel free to ask any further questions.

**Comment by malthe** [comment]
@zojovano did you open an issue on the ADO side?

**Comment by Nicwalle** [comment]
Reopening this issue as Azure DevOps does now support Managed identity authentication. Can we imagine using a managed identity instead of a PAT token to perform the registration of the self-hosted agent running in Azure (container, VM, VMSS...)?

**Comment by AlexWehning** [comment]
Just as an update, because I was looking into the same topic:
This should be coming soon™ (currently coming to preview)
https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-222-update#pipeline-agents-can-be-registered-using-a-service-principal

**Comment by EJBF** [comment]
Starting with v3.227.x Self-Hosted Agent registration is now available using Service Principal. Today opened a ticket to Microsoft about registration with Managed Identity.

**Comment by speak2beeb** [comment]
> Starting with v3.227.x Self-Hosted Agent registration is now available using Service Principal. Today opened a ticket to Microsoft about registration with Managed Identity.

What did Microsoft say about registration with a managed identity?
