### ISSUE TITLE
config.sh fails with message: Deployment type has not been determined

### ISSUE THREAD

**Issue by stas2** [microsoft/azure-pipelines-agent#3610]
## Agent Version and Platform
Version of your agent? 2.195.0

OS of the machine running the agent? Linux x64

## Azure DevOps Type and Version
on-prem Microsoft Visual Studio Team Foundation Server

Version 15.112.26307.0

(Is this at all supported?)

## What's not working?
config.sh fails with message: Deployment type has not been determined

We have successfully been running an older version 2.155.0 of the agent on the same machine since 2019.
I now want to install the latest version, but I do not seem to be able to register a new agent. Is my TFS server too old?

## Agent and Worker's Diagnostic Logs
[Agent_20211112-164604-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7529697/Agent_20211112-164604-utc.log)

**Comment by DenisRumyantsev** [comment]
Hi @stas2, starting with release `2.194.0`, a hash validation of the pipeline agent package during self-updating was implemented. The agent needs to know the server deployment type for this. Besides that, it is used by `ConfigurationManager` [here](https://github.com/microsoft/azure-pipelines-agent/blob/629921e0faea9739aeb926a6c67a443cbf936b96/src/Agent.Listener/Configuration/ConfigurationManager.cs#L230) and [here](https://github.com/microsoft/azure-pipelines-agent/blob/629921e0faea9739aeb926a6c67a443cbf936b96/src/Agent.Listener/Configuration/ConfigurationManager.cs#L584). You can avoid this error by using the pipeline agent version `2.193.1`. Most likely, the reason why you have got this issue is that the deployment type determination has not yet been implemented for your server version.

**Comment by DenisRumyantsev** [comment]
@stas2 since TFS version 15 is still supported, we are going to fix this issue for `ConfigurationManager` by throwing warnings instead of errors. You will be able to set the environment variable `DISABLE_HASH_VALIDATION=true` to avoid this error during the self-update process.

**Comment by DenisRumyantsev** [comment]
[Related Pull Request](https://github.com/microsoft/azure-pipelines-agent/pull/3614)

**Comment by FrankHeimes** [comment]
@DenisRumyantsev Thank's for fixing this issue!
It's unfortunate however that version 2.195.0 suffers from this problem as that version also adds support for VS2022.

Can you give an estimate on when your PR will probably be merged and published?

Is there any way for me to avoid or 'sabotage' the call to `SelfUpdate()`, e.g. by blocking internet access?
I tried the following, but to no avail:
```
setx DISABLE_HASH_VALIDATION true /M
setx agent.disableupdate true /M
set DISABLE_HASH_VALIDATION=true
set agent.disableupdate=true
```

**Comment by stas2** [comment]
@DenisRumyantsev Thank you for quick reply and prompt action. I tried version 2.193.1 and it worked with TFS 15. Meanwhile we have migrated to Azure DevOps 2020 1.1, so the latest version works great.

**Comment by DenisRumyantsev** [comment]
Hi @FrankHeimes, currently, the PR is under code review and testing. We plan to merge this PR and release a new version of the agent in the near time.

Setting the `DISABLE_HASH_VALIDATION` environment variable to `true` should prevent only the hash validation during the self-update process, but not the self-update process itself.

**Comment by DenisRumyantsev** [comment]
Related changes have been merged. I will update this ticket once they will be rolled out to all Azure DevOps users.

**Comment by DenisRumyantsev** [comment]
The `2.196.*` pipeline agent release is delayed. Waiting when it will be rolled out to resolve this issue.

**Comment by alexander-smolyakov** [comment]
Hi @stas2, the agent [v2.196.2](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.196.2) was released. Could you please check that the issue is resolved now?

**Comment by stas2** [comment]
Thank you for the update. Unfortunately I cannot check the issue any more since we have updated infrastructure to newer version.
