### ISSUE TITLE
Self hosted agents have gone offline after logging of User

### ISSUE THREAD

**Issue by watcherkb** [microsoft/azure-pipelines-agent#3622]
## Agent Version and Platform
Version of your agent? 2.194.0/2.195.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

## Organization name
https://dev.azure.com/{organization}

## What's not working?
The agents are running fine for days if a User is logged in on the agent. As soon as I log off the User from agent, after some time the agents goes offline.
The agents are configured using a PAT. The windows services are running as Network Service.
Configured according to: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops

## Agent and Worker's Diagnostic Logs
[2021-11-23 06:39:37Z INFO HttpTrace] Trace System.Net.Http.Response event:
{ Response = StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/a1d7991d-5268-4484-8ae0-082bc77ab485
  WWW-Authenticate: Basic realm="https://tfsprodweusu4.app.visualstudio.com/"
  WWW-Authenticate: TFS-Federated
  X-TFS-ProcessId: 17b85701-b687-432f-b272-f5edd9c72765
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  ActivityId: 65fa0ffa-3dca-45cc-b533-73a233db94c8
  X-TFS-Session: a4588967-d8dd-4274-a2a8-cd27c4c31364
  X-VSS-E2EID: b17f0665-fcac-453e-8d93-08bbfe6519a0
  X-VSS-SenderDeploymentId: 41a8baae-7dbb-4778-98b9-0634c6329da0
  X-Frame-Options: SAMEORIGIN
  X-TFS-FedAuthRealm: https://tfsprodweusu4.app.visualstudio.com/
  X-TFS-FedAuthIssuer: https://dev.azure.com/{organization}/
  X-VSS-AuthorizationEndpoint: https://{organization}.vssps.visualstudio.com/
  X-VSS-ResourceTenant: dcce9c7b-4b25-45b1-96af-b17254623a7b
  X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
  X-TFS-FedAuthRedirect: https://spsprodweu3.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2F{organization}%2F_apis%2FconnectionData%3FconnectOptions%3D1%26lastChangeId%3D331878468%26lastChangeId64%3D331878468&redirect=1&hid=d9441b8a
  Request-Context: appId=cid-v1:e84bb7c2-a39a-4cba-abdb-625230e81c09
  Access-Control-Expose-Headers: Request-Context
  X-Content-Type-Options: nosniff
  X-Cache: CONFIG_NOCACHE
  X-MSEdge-Ref: Ref A: 38DADF2AA3B8419B882E996884A507D4 Ref B: FRAEDGE1315 Ref C: 2021-11-23T06:39:37Z
  Date: Tue, 23 Nov 2021 06:39:37 GMT
  Content-Length: 307
  Content-Type: application/json; charset=utf-8
  Expires: -1
}

**Comment by kuleshovilya** [comment]
Hello @watcherkb 
Seem's more like a system issue. Is the behavior different if you'll set it to Local System or something along those lines?
Because quick tests from our side show that on the fresh system the behavior is correct, the services keep running for hours on both Network Services and Local System.

**Comment by watcherkb** [comment]
@kuleshovilya Hey, thank you for your reply.
I've added two new workstations to our Agent Pool. One with NT-AUTHORITY\LocalService and the other with NT-AUTHORITY\NetworkService. I'll answer here as soon as I have more info about how it's going.

**Comment by watcherkb** [comment]
@kuleshovilya bad news. Both agents are offline. Can I send you the log-files?

**Comment by kuleshovilya** [comment]
@watcherkb Sure, send them over. Either here or you can send them to v-ikuleshov@microsoft.com

**Comment by watcherkb** [comment]
Solved this issue by checking and reconfiguring our firewall.
