### ISSUE TITLE
Azure Virtual Machine Scale Sets fails to install agent

### ISSUE THREAD

**Issue by mikehend** [microsoft/azure-pipelines-agent#3627]
## Having issue with YAML?
No

## Having issue with Tasks?
No

## Having issue with software on Hosted Agent?
No

## Having generic issue with Azure-Pipelines/VSTS/TFS?
NO

## Have you tried troubleshooting?
Not applicable.  Agent isn't ready to run pipeline

## Agent Version and Platform
2.195.0 (Package Install version 1.27.0.2)

OS of the machine running the agent? OSX/Windows/Linux/...
Windows 10 Pro

## Azure DevOps Type and Version
dev.azure.com

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.
Not applicable

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com
https://pbsorters.visualstudio.com/

## What's not working?
After updting custom image for virtual machine set and redeploying, new images cannot get into "Succeeded" state in Azure and never show up in agent pools.  VM(s) are running and can be accessed.  
Looking at a good deployment and a bad one, the status file shows that the EnablePipelinesAgent function in EnablePipelinesAgent.ps1 fails in the try/catch block lines 88-120.  I know this because the bad status file has this:

				{
					"status": "success",
					"code": 76,
					"name": "Enable Pipelines Agent Error",
					"formattedMessage": {
						"message": "EnablePipelinesAgent\r\n",
						"lang": "en-US"
					}
				}

and the good ones have code 77 with success. (no error in the name tag)
Looking at the code, it seems that the powershell script that is called in this block is likely never exiting...

        # So poll ourselves for 30 minutes.
        $process = Start-Process -FilePath PowerShell.exe -Verb RunAs -PassThru -ArgumentList $argList
        $loops = 0
        do 
        {
            $loops++
            Start-Sleep -Milliseconds 1000
        }
        **until ($process.HasExited -or ($loops -gt 1800))**

This is consistent with what I see in the Azure Portal, the VM stays in a "Creating (Running)" state and the VM is completely up and running but the c:\agent folder is empty except the zip file. All of the above was found in the "C:\Packages\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.27.0.2" folder.  

I have spent a bunch of time thinking I had created the image wrong, but I have followed the steps in the following page multiple times step by step.  I even waited a full hour after sysprep (even after the VM was marked stopped) to make sure nothing was happening in the background as Microsoft warned.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-a-scale-set-with-custom-image-software-or-disk-size

I don't know how to run the VMS package install manually or I would to get more details or add debugging to the ps1 script(s).

## Agent and Worker's Diagnostic Logs
Not applicable because the agent does not get installed.
I have included the status files for the install of the extension as well as a script.log and the settings file used in the automation.
[VMSIssue.zip](https://github.com/microsoft/azure-pipelines-agent/files/7591034/VMSIssue.zip)
n.

**Comment by EzzhevNikita** [comment]
@mikehend This repo is specific for the ADO agent, while your issue is mostly related to the Azure Virtual Machine Scale Sets and its configuration scripts. Could you please open an issue in [Developer Community](https://developercommunity.visualstudio.com/search?space=21) to get the right eyes on your issue?

**Comment by EzzhevNikita** [comment]
@mikehend Let me close this ticket currently since it is related to Azure VMSS, not to the agent itself. Please ask questions related to VMSS in [Developer Community](https://developercommunity.visualstudio.com/search?space=21).
