### ISSUE TITLE
Pipelines and reusing workspaces

### ISSUE THREAD

**Issue by PaulVrugt** [microsoft/azure-pipelines-agent#3628]
## Agent Version and Platform
Version of your agent? 2.195.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com/infolandcode

## What's not working?
We have a private build agent (scale set agent). We are working with a lot of different pipelines for the same repository, that uses the same sources. However, it seems that each of these pipelines always create their own workspace. This causes the sources to be redownloaded EACH time, even though the sources for the same repository are already downloaded in a different workspace for a different pipeline.

Do we have any influence on what pipelines share the same workspace? I'm unable to find any documentation on this. Our pipelines would be a lot faster if we can make different pipelines reuse the same workspace folder.

**Comment by EzzhevNikita** [comment]
Hey @PaulVrugt, the current implementation of the agent allows sharing repository resources only between the same pipelines. We aren't supporting sharing repositories between different pipeline definitions.

**Comment by PaulVrugt** [comment]
Hello @EzzhevNikita . Thanks for the quick reply! 

I was afraid of that. But hopefully you understand the issue right? Is there anything we can do about this? Is there any workaround we can use?

Can I submit a feature request somewhere? Because the current implementation is very inefficient.

**Comment by EzzhevNikita** [comment]
@PaulVrugt, Yep, as I understand you want to have the opportunity to share repository resources between different pipeline definitions. Unfortunately, there are no workarounds for your use case currently.
You can submit a feature request in this repository as a separate work item, please describe in detail your proposal and we will take a look at it once we will have the capacity for it.

**Comment by PaulVrugt** [comment]
@EzzhevNikita  thanks! See https://github.com/microsoft/azure-pipelines-agent/issues/3629

**Comment by EzzhevNikita** [comment]
@PaulVrugt Let me close this item. We will take a look at your feature request.
