### ISSUE TITLE
[FEATURE REQUEST] Shared sources for over workspaces for reusing sources

### ISSUE THREAD

**Issue by PaulVrugt** [microsoft/azure-pipelines-agent#3629]
Currently the pipeline agent always creates a workspace PER pipeline. However, this becomes very ineffecient in private agents when you have multiple pipelines using the same sources repository. In our case we have about 20 pipelines that use the sources from the same repository. Each time a different pipeline is run, the sources are fetched again in a new workspace, taking a lot of time and using a lot of disk space.

Right now, the sources are always a sub folder of the workspace. The problem would be fixed if we could somehow specify a folder for the sources separate from the workspace. Since an agent can only process 1 job at a time, we could specify a workspace independent folder for the sources, so we can reuse the sources for different pipelines.

We can go two ways with this:
- Be able to specify a shared sources folder somewhere in the YAML definition (at a global level in the pipeline, at job level or even at checkout level). At pipeline level would already do the trick for us, but I don't know if there are any technical reasons to specify it at a certain level
- There might be even a case to be made for making the shared sources folder the default mode. The "$(Build.SourcesDirectory)" can simply contain a different value, and I can't think of a reason why the sources folder should be part of the workspace at all, since the agent can only process 1 job at a time, and the git checkout task already makes sure the sources are correct.

Please let me know what you think of this request, and if you need any more input from me?

**Comment by PaulVrugt** [comment]
FYI, I would be willing to contribute to this feature if you decide it is a valid enhancement

**Comment by anatolybolshakov** [comment]
Hi @PaulVrugt thanks for reporting! This looks similar to https://github.com/microsoft/azure-pipelines-agent/issues/1506 and related PRs which we are planning to review.

**Comment by PaulVrugt** [comment]
Not stale, just lack of response from Microsoft
