### ISSUE TITLE
Requirements to migrate custom task to node10

### ISSUE THREAD

**Issue by qetza** [microsoft/azure-pipelines-agent#3631]
Hi,
I'm an author of a custom task (https://github.com/qetza/vsts-replacetokens-task) and deployed yesterday a new minor version to use the new Node10 execution handler.

Today i had to revert the changes because some users on TFS 2018 where having issues and the task would not run (https://github.com/qetza/vsts-replacetokens-task/issues/233):

> A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.

Users where using TFS 2018 with agent 2.131.0 on windows.

- Is there any minimum requirements that i need to be aware of? (the documentation on the migration doesn't include any information on the minimum TFS/Azure DevOps version or agent version)
- Should I create a new major version with a breaking change?
- Is it possible to define a fallback execution handler?

Thanks

**Comment by anatolybolshakov** [comment]
Hi @qetza Node 10 execution handler was released with [2.144.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.144.0) agent version - there is no ability to make fallback at the moment unfortunately... 
Generally it is recommended to update the server version, but major version bump could also be the option.

**Comment by qetza** [comment]
Hi @anatolybolshakov,
Thanks for the info.

Is there a way to deploy the same task with different version and minimumAgentVersion and have the agent pick the best one?

If not as the task is public i think my only option is to generate a new major version as i cannot force all users to upgrade their agent.

**Comment by anatolybolshakov** [comment]
@qetza there is no ability to let the agent choose the task this way at the moment - so yes, major version bump make sense.

**Comment by anatolybolshakov** [comment]
@qetza please let us know if you have any other questions.

**Comment by qetza** [comment]
Thanks, i’ll release a new major version then.
