### ISSUE TITLE
An option to avoid prepending Path environment variable with directory containing 'git.exe' in Checkout step

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [microsoft/azure-pipelines-agent#3634]
In Build pipeline, before repo is checked, there is initialization procedure which prepends Path variable with git.exe. 

In my self-hosted agent there is already git.exe present. This git.exe instance is linked to a config pointing to specific credential store. In my pipeline script I am cloning another helper repo. But as different git.exe is executed, different config is used so cloning this other repo fails.

I can specify the full path to my git.exe in my script, but as I'd like to avoid paths hardcoding, it would be nice to have an option:
1. To disable PATH variable modification
2. To somehow define that git.exe used by Azure should use my specific config

**Comment by jessehouwing** [comment]
There is an existing Agent_Knob to fix this `system.prefergitfrompath` set this to `true` to accomplish what you want. You can either set this in the agent's config file or in the system's environment variables. In ome cases you can simply add this as a variable of your pipeline.

https://github.com/microsoft/azure-pipelines-agent/blob/1adfc03151ede59addaf6c5e9eaa55aad57b6a7a/src/Agent.Sdk/Knob/AgentKnobs.cs#L73-L78

**Comment by EzzhevNikita** [comment]
Hey @jan-tosovsky-cz, @jessehouwing correctly mentioned that you could use _system.prefergitfrompath_ set to _true_ to achieve what you want. In this way, the agent will use git that is preinstalled in the system instead of bundled version.

**Comment by jan-tosovsky-cz** [comment]
Thanks for the hint. I am failing to find any mention in documentation WHERE actually this should be set. What is 'agent's config file'? Can you elaborate, please?

**Comment by EzzhevNikita** [comment]
@jan-tosovsky-cz You can set this variable as an environment variable in the system, where the agent is executing

**Comment by jessehouwing** [comment]
You can also add the variable to a `.env` file in the agents installation directory.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#how-do-i-set-different-environment-variables-for-each-individual-agent

Make sure you restart the agent after changing.either the global systems environment variables or the env file.

And many of these knobs will simply trigger when a pipeline variable with the right name is set, since they are also exported to the environment when a job runs.

**Comment by EzzhevNikita** [comment]
@jan-tosovsky-cz Is it still an actual issue? Could we close this work item?

**Comment by EzzhevNikita** [comment]
@jan-tosovsky-cz Let me close this issue, in case of any future questions feel free to ping me
