### ISSUE TITLE
Access PFX files from PowerShell Task in Interactive Mode

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-agent#3639]
Dear Team,

Borderline topic with the [Azure Pipelines Task Team
](https://github.com/Microsoft/azure-pipelines-task).

Is there any know issue with access the PFX files from PowerShell Task (Microsoft) when the ADO Agent run in Interactive Mode?

Getting  "The system cannot find the file specified." exception when try to import the PFX into the Personal Certificate Store:

`Import-pfxcertificate  -FilePath "$Path" -CertStoreLocation "Cert:\CurrentUser\My" -verbose -Exportable  `

$PATH is valid and same issue with `System.Security.Cryptography` Namespace.

`$certPath = "$Path"  
$pfx = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2  
$pfx.Import($certPath,$certPass,"Exportable,PersistKeySet")   
$store = New-Object System.Security.Cryptography.X509Certificates.X509Store("My","CurrentUser")   
$store.Open("ReadWrite")  
$store.Add($pfx)   
$store.Close()`

Manifest signing with Visual Studio on VSTO Projects are also not working:

```
 The "ResolveKeySource" task failed unexpectedly.
System.Security.Cryptography.CryptographicException: Access is denied.
```

On this case, the VS is also try to pick-up the PFX from the cloned repository. 

This happens only if the ADO Agent has been started in interactive mode, same code **works fine with Windows service mode.** 

Regards,
Gabor

**Comment by anatolybolshakov** [comment]
Hi @iambernics per the error message it seems to be related to some permissions issue - could it be related to the difference in permissions for user running agent interactively and user on whose behalf the service is launched?

**Comment by anatolybolshakov** [comment]
Hi @iambernics do you have any updates? Is this issue still actual for you?
