### ISSUE TITLE
VSBuild@1 task is not updated to support VS2022

### ISSUE THREAD

**Issue by juergenB234** [microsoft/azure-pipelines-agent#3640]
Build pipeline uses VSBuild@1.

- task: VSBuild@1
  displayName: 'Build solution ${{ parameters.solution }}'
  inputs:
    solution: ${{ parameters.solution }}
    vsVersion: 'latest'

The build fails and there are multiple warnings with: NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported.

The Agent downloaded this task H:\Agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.166.2
In the powershell scripts of this task there is no hint about a version 17.0

Tested with v2.195.0, v2.195.1, v2.196.0.
Agent is installed on premise on Windows Server 2012 R2 and connected with Azure DevOps Server.
Visual Studio 2022 is also installed.

**Comment by tatyana-kostromskaya** [comment]
@juergenB234 you use task version 1.166.2 which doesn't support VS2022. 
The further solution steps I will post here: https://github.com/microsoft/azure-pipelines-agent/issues/3641

Closing as duplicate.
