### ISSUE TITLE
MSBuild@1 task is not updated to support VS2022

### ISSUE THREAD

**Issue by juergenB234** [microsoft/azure-pipelines-agent#3641]
Build pipeline uses VSBuild@1.

- task: MSBuild@1
  displayName: 'Build solution ${{ parameters.solution }}'
  inputs:
    solution: ${{ parameters.solution }}
    msbuildVersion: '17.0.0.52104'
    msbuildArchitecture: 'x64'

The build fails and there are multiple warnings with: NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported.

The Agent downloaded this task H:\Agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.179.0

Trace from the task:
"H:\Agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.179.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -latest -format json
##[warning]Unable to find MSBuild version '17.0.0.52104' for architecture 'x64'. Falling back to version '16.0'.

Same result without parameter msbuildArchitecture and the default settings for msbuildArchitecture.

Tested with v2.195.0, v2.195.1, v2.196.0.
Agent is installed on premise on Windows Server 2012 R2 and connected with Azure DevOps Server.
Visual Studio 2022 is also installed.

**Comment by tatyana-kostromskaya** [comment]
@juergenB234 you use task version 1.179.0 which doesn't support VS2022. 
Which version of Azure DevOps Server do you use?

**Comment by juergenB234** [comment]
The Version is Azure DevOps Server Update 1.1 2020. There is a Patch 2. Is the updated task integrated in this patch?

**Comment by tatyana-kostromskaya** [comment]
@juergenB234 , no, this task update is not integrated to Azure DevOps Server yet

**Comment by juergenB234** [comment]
Is there a way to manually update the task?

**Comment by tatyana-kostromskaya** [comment]
Yes, I will help you with it. Do you need only VSBuild and MSBuild tasks?

**Comment by juergenB234** [comment]
Thanks. Yes, VSBuild and MSBuild.

**Comment by tbolon** [comment]
I just checked that my DevOps server is also using MSBuild v16 2019.
I tried updating the agent manually 2.195.1, but it reverted to 2.181.2 (from february).
I am surprised the agent version is lagging so much behind the latest. Is it expected ?

**Comment by tatyana-kostromskaya** [comment]
@juergenB234 , Here are zip achieves with latest versions of the tasks: 
[MSBuildV1.zip](https://github.com/microsoft/azure-pipelines-agent/files/7642688/MSBuildV1.zip)
[VSBuildV1.zip](https://github.com/microsoft/azure-pipelines-agent/files/7642689/VSBuildV1.zip)

To update these tasks in your organization please follow the instruction:

1. Unpack achieves to any location.
2. Install Node.js 
3. Install tfx-cli :
   For Linux/OSX: sudo npm install -g tfx-cli
   For Windows: npm install -g tfx-cli
6. Sign in with your account to Azure DevOps.
7. Create a personal access token or use existing one.
 To create new token:
a. Click on “User Settings” in the upper right corner of the page;
b. Select “Personal access tokens”;
c. In the opened window, click on the “+ New Token” button;
d. Enter any name for your access token and choose “Full Access”;
e. Copy and save your token!
14. Run command from a command line - `tfx build tasks upload -u https://<YOUR_ORGANISATION>.visualstudio.com/DefaultCollection -t <YOUR_PERSONAL_ACCESS_TOKEN> --task-path <PATH_TO_UPDATED_TASK>`
PATH_TO_UPDATED_TASK - path to folder of unpacked task

**Comment by tatyana-kostromskaya** [comment]
@tbolon, yes it is expected that Azure DevOps Server downgrades version of the agent to the version that is set up in the server.  
In most cases it should be safe to update version of the agent manually and turn off downgrading by using `AZP_AGENT_DOWNGRADE_DISABLED` environment variable.

You can follow the guide above to update your tasks also.

**Comment by tbolon** [comment]
> You can follow the guide above to update your tasks also.

I note your workaround, but I have instead updated each task individually. Nice timing here are this issue is only a few hours old.

Thank you for your help :)

**Comment by juergenB234** [comment]
Thank you. I was able to update the tasks and VS2022 is now detected.

**Comment by tatyana-kostromskaya** [comment]
Thank you for reply. Closing this ticket

**Comment by jessehouwing** [comment]
For future cases where the task in Azure DevOps Server needs to be upgraded, I've created a workflow on GitHub that makes the latest versions of each task available:

https://github.com/jessehouwing/azure-pipelines-tasks-zips

I've also added a script to generate a side-by-side version so you can install those alongside the older version of the task for testing or when backwards compatibility is something you want to keep in mind.

**Comment by n-sijtsma** [comment]
> For future cases where the task in Azure DevOps Server needs to be upgraded, I've created a workflow on GitHub that makes the latest versions of each task available:
> 
> https://github.com/jessehouwing/azure-pipelines-tasks-zips
> 
> I've also added a script to generate a side-by-side version so you can install those alongside the older version of the task for testing or when backwards compatibility is something you want to keep in mind.

Thanks Jesse, we will try your extension.
One thing i noticed when using the classic pipeline editor is that you have not updated the icon or company name, making it more difficult to figure out which task to pick.

![image](https://user-images.githubusercontent.com/93312076/154993880-227037ac-b42f-4287-b10f-27b173b002ed.png)
The selected one is yours and has MSBuild 17.0 available

**Comment by evakili** [comment]
@tatyana-kostromskaya Could you provide VSTestV2 update? Or tell us how to compile other tasks ourselves?

**Comment by mattiaskagstrom** [comment]
> Thank you for reply. Closing this ticket

The latest version of Azure DevOps Servies still doesn't seemt to have updated tasks. Why is this issue closed?

**Comment by cbernth** [comment]
This bug hasn't been fixed!
For an enterprise organization it's hardly feasible with a workaround that requires manual fiddling.
Can this bug please be reopened?

**Comment by No1e** [comment]
Hi. Can we get support here?

**Comment by jessehouwing** [comment]
> @tatyana-kostromskaya Could you provide VSTestV2 update? Or tell us how to compile other tasks ourselves?

See:
https://github.com/jessehouwing/azure-pipelines-tasks-zips

And for background:
https://jessehouwing.net/adding-visual-studio-2022-to-azure-devops-server-2020/

**Comment by janis-veinbergs** [comment]
VS2022 support added as of [Azure DevOps Server 2022 Update 0.1 RC Release Date: April 11, 2023](https://learn.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2022?view=azure-devops-2020#azure-devops-server-2022-update-01-rc-release-date-april-11-2023).
