### ISSUE TITLE
System Capabilities do not support VS2022

### ISSUE THREAD

**Issue by Blinchik91** [microsoft/azure-pipelines-agent#3662]
The latest Azure DevOps Agent (2.170.1) does not seem to pull the same system capabilities for VS2022 as it does for VS2019. At this time, it does not pull all capabilities related to VS2022. The capabilities we were expecting are as follows

VisualStudio -
VisualStudio_16.0 -
VisualStudio_IDE -
VisualStudio_IDE_16.0 -
VSTest -
VSTest-16.0 -
MSBuild_16.0
MSBuild_16.0_x64

and the others MSBuild paths are wrong. (Related to C:\Windows\Microsoft.NET\Framework\v4.0.30319)

So the builds in the pipeline are useless now because of some errors.

Similar issue after VS2019 released. [#2004](https://github.com/microsoft/azure-pipelines-agent/issues/2004)

**Comment by DenisRumyantsev** [comment]
Hi @Blinchik91, currently, the latest ADO agent is [2.195.2](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.195.2). Could you try to use it instead of the mentioned `2.170.1`?

**Comment by Blinchik91** [comment]
> Hi @Blinchik91, currently, the latest ADO agent is [2.195.2](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.195.2). Could you try to use it instead of the mentioned `2.170.1`?

Yes, I updated to 2.195.2 but with a very strange behavior.
After starting the Build, the agent downgrade itself to 2.170.1 ?! 
I don't know what's wrong.

Screenshot of the folder structure attached, after build start
![Image 8](https://user-images.githubusercontent.com/70434936/146150667-d085cb11-2baa-4434-a653-41bbebee2c10.jpg)

**Comment by DenisRumyantsev** [comment]
@Blinchik91 What is your server deployment type (Cloud / OnPremises)?

**Comment by Blinchik91** [comment]
> @Blinchik91 What is your server deployment type (Cloud / OnPremises)?

No it's not in the cloud, we are host the server in on our company server.
We updated our DevOps Server to the newest Version "Azure DevOps Server 2020.1.1" today.
Now it downgrades the Agend to Version 2.181.2, same behavior.

Agent Log:
> [2021-12-15 12:52:38Z INFO SelfUpdater] Version '2.181.2' of 'agent' package available in server.
[2021-12-15 12:52:38Z INFO SelfUpdater] Current running agent version is 2.195.2
[2021-12-15 12:52:38Z INFO Terminal] WRITE LINE: Der Agent wird auf eine niedrigere Version herabgestuft. Die ist in der Regel auf einen Rollback des aktuell veröffentlichten Agents zur Fehlerkorrektur zurückzuführen. Um dieses Verhalten zu deaktivieren, legen Sie die Umgebungsvariable AZP_AGENT_DOWNGRADE_DISABLED auf TRUE fest, bevor Sie Ihren Agent starten.
[2021-12-15 12:52:38Z INFO SelfUpdater] An update is available.
[2021-12-15 12:52:38Z INFO Terminal] WRITE LINE: Das Agent-Update wird ausgeführt. Fahren Sie den Agent nicht herunter.
[2021-12-15 12:52:38Z INFO Terminal] WRITE LINE: 2.181.2-Agent wird heruntergeladen.

In German it means that the Agent downgrades the version and it's a rollback mechanism and I can "disbable" it.
But this can't be the final solution because it has to work with default settings.

**Comment by cfaagaard** [comment]
We are seeing the same behavior. Onprem Devops (version Dev18.M170.8).
Installed the 2.195.1 agent and all looks good. When the very first build starts to run, the agent is downgraded.
The "Initialize job" in the pipeline says: "Current agent version: '2.170.1'"
Then the build job fails and the agents directory is changed to: 
![image](https://user-images.githubusercontent.com/25353502/146329417-ef43d592-b6af-4a4b-8dd7-cec979bf52ae.png)

**Comment by Blinchik91** [comment]
@cfaagaard 

AZP_AGENT_DOWNGRADE_DISABLED=true enviroment variable should work for you too.
I don't know if this is a common way in devops to suppress this behavior.

It seems that DevOps Server needs an update to allow this version.

**Comment by cfaagaard** [comment]
@Blinchik91  Thanks.

I will test the "enviroment variable"-workaround :-)

Do you know if the update for the devops server is available?

**Comment by Blinchik91** [comment]
> @Blinchik91 Thanks.
> 
> I will test the "enviroment variable"-workaround :-)
> 
> Do you know if the update for the devops server is available?

have a look [here](https://docs.microsoft.com/de-de/azure/devops/server/download/azuredevopsserver?view=azure-devops-2020).

The Version  2020.1.1 is the newest but only supports Agent Version 2.181.2 (without enviroment variable)

**Comment by DenisRumyantsev** [comment]
@Blinchik91 @cfaagaard Could you take a look at the note in [this documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#to-update-self-hosted-agents)?

If I'm not mistaken, the pipelines agent archive with the required version can be copied to
`C:\ProgramData\Microsoft\Azure DevOps\Agents\`

**Comment by Blinchik91** [comment]
argh... it frustrates me....

The new BuildTool 2022 are not able to build old projects (VS19 with .Net Framework WPF).

> Error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

If I intall both, 2019 and 2022, it works but new projects with .NET 6 not... (Error: .net 6 not found).
Any Ideas ?

**Comment by cfaagaard** [comment]
> argh... it frustrates me....
> 
> The new BuildTool 2022 are not able to build old projects (VS19 with .Net Framework WPF).
> 
> > Error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
> 
> If I intall both, 2019 and 2022, it works but new projects with .NET 6 not... (Error: .net 6 not found). Any Ideas ?

(in the process of upgrading devops server) in your build-job do have set the "visual studio version" to "latest version"?

**Comment by Blinchik91** [comment]
> > argh... it frustrates me....
> > The new BuildTool 2022 are not able to build old projects (VS19 with .Net Framework WPF).
> > > Error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
> > 
> > 
> > If I intall both, 2019 and 2022, it works but new projects with .NET 6 not... (Error: .net 6 not found). Any Ideas ?
> 
> (in the process of upgrading devops server) in your build-job do have set the "visual studio version" to "latest version"?

I dont know, our IT department updated it but I think so.
What is the alternative ?

**Comment by cfaagaard** [comment]
Upgraded devops server to: 18.181.31626.1 (Azure DevOps Server 2020 Update 1.1)
Then I could upgrade the agent to version 2.181.2 by clicking "update agent" in the devops website.

Downloaded and copied agent 2.195.2 to C:\ProgramData\Microsoft\Azure DevOps\Agents\ on the devops server. (the "Agents" directory I created manually)
Then I could upgrade the agent to version 2.195.2 by clicking "update agent" in the devops website.

Now I need to test my build jobs. To be continued.....

**Comment by cfaagaard** [comment]
A note: We have two build-server. One with only vs2019 and one with only vs2022. It is only the vs2022-build server that I am testing this on.

**Comment by cfaagaard** [comment]
Can not get it to work. Running into to this issue: https://github.com/microsoft/azure-pipelines-agent/issues/3600

**Comment by cfaagaard** [comment]
this blog claims that the issue is that the build tasks on the devops server, do not support visual studio 2022....
https://jessehouwing.net/adding-visual-studio-2022-to-azure-devops-server-2020/
have not tried his suggestions as our devops server is a production and I do not want to break the working build jobs.

**Comment by DenisRumyantsev** [comment]
Pending for completion of #3600

**Comment by jessehouwing** [comment]
> this blog claims that the issue is that the build tasks on the devops server, do not support visual studio 2022.... https://jessehouwing.net/adding-visual-studio-2022-to-azure-devops-server-2020/ have not tried his suggestions as our devops server is a production and I do not want to break the working build jobs.

Since the tasks are installed at the Project Collection level, you can safely test this, even on your prod server, by (temporarily) adding a Project Collection.

**Comment by jessehouwing** [comment]
Further expanded my temporary solution for [this problem for now and hopefully for future situations with a similar issue](
https://github.com/jessehouwing/azure-pipelines-tasks-zips).

[Download the task from the latest release](https://github.com/jessehouwing/azure-pipelines-tasks-zips/releases) and [install them into you collection](https://github.com/jessehouwing/azure-pipelines-tasks-zips#installation).

Alternatively install the tasks through an extension:

* 🛍️ [Visual Studio 2022 for Azure DevOps Server](https://marketplace.visualstudio.com/items?itemName=jessehouwing.visualstudio)
* 🛍️ [DotNetCore 6 for Azure DevOps Server](https://marketplace.visualstudio.com/items?itemName=jessehouwing.dotnetcore)

## Required agent version
You will need to [install a recent agent (2.195.0 or newer) from the azure-pipelines-agent repository](https://github.com/microsoft/azure-pipelines-agent/releases) for it to auto-detect Visual Studio 2022, or alternatively add the capabilities to the agent manually.

You may need to force Azure DevOps Server to not downgrade back to its preferred agent version. You can do so by setting the following environment variable at the system level on your server before launching the agent:

```
AZP_AGENT_DOWNGRADE_DISABLED=true
```

**Comment by Nighteyez07** [comment]
- It's been **7 months** since this issue was initially opened
- **5 months** since an advocate created a custom workaround
- **10 months** since the [Pipeline tasks project](https://github.com/microsoft/azure-pipelines-tasks) were originally updated to add support

Visual Studio is a Microsoft platform, Azure DevOps is a Microsoft platform. It is concerning as an advocate myself that there is such a disconnect for adding support for Microsoft's own core product into a platform designed for high level capabilities. Can we please get some attention to this?

**Comment by Blinchik91** [comment]
yes, it's crap.
Our workaround was it to update the agent manually and set the enviroment variable as @jessehouwing descriped.
Further we run msbuild via Powershell as a Task in the pipeline because the default VS Build Task does not support VS22.

**Comment by jessehouwing** [comment]
Azure DevOps 2022 is about to be released. It has official support for Visual Studio 2022.

My extension will remain available.
