### ISSUE TITLE
Visual Studio - Remove compilation errors in .g.cs files 

### ISSUE THREAD

**Issue by sathishreddy48** [microsoft/azure-pipelines-agent#3667]
Error	CS1576	The line number specified for #line directive is missing or invalid.

Platform details :
Windows 11
Microsoft Visual Studio Enterprise 2019
Version 16.11.7
netcoreapp3.1
![image](https://user-images.githubusercontent.com/30253286/146287598-d89a01eb-0c51-491e-9b12-4217ef8baad2.png)

**Comment by DenisRumyantsev** [comment]
Hi @sathishreddy48, what is your issue? Could you describe it in more detail?

**Comment by DenisRumyantsev** [comment]
Hi @sathishreddy48, could you provide more details about this issue?

**Comment by DenisRumyantsev** [comment]
Hi @sathishreddy48, I am closing this issue since there is not enough information to investigate it.
