### ISSUE TITLE
Upgrade git in Windows Agent to latest (2.34.1)

### ISSUE THREAD

**Issue by jgelon** [microsoft/azure-pipelines-agent#3668]
## Agent Version and Platform
Agent version: 2.196.1

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
Commands in renovate requiring the latest git version (> 2.33)

## Having issue with software on Hosted Agent?
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.
--> Link does not work

**Comment by kwlin** [comment]
@jgelon  & @DenisRumyantsev  I made PR voor this issue. Any thoughts about the PR's?

**Comment by mulder999** [comment]
+1 Puzzling is that MS documentation [Windows 2019 image 20220131.1](https://github.com/actions/virtual-environments/blob/win19/20220131.1/images/win/Windows2019-Readme.md) indicates that git tool should be in version `2.35.1`. How do we end up with outdated version `2.30.2.windows.1` ?

**Comment by mulder999** [comment]
I found the solution, see [here](https://github.com/microsoft/azure-pipelines-agent/pull/3693#issuecomment-1048661100)

**Comment by anatolybolshakov** [comment]
Hi everyone! We've updated git to 2.36.1 in https://github.com/microsoft/azure-pipelines-agent/pull/3839 - this will be available in the next agent release.

**Comment by crh225** [comment]
@anatolybolshakov do you know timeframe of when that will be?

**Comment by anatolybolshakov** [comment]
Hey @crh225 I'm no longer working on project, but I believe it should be already rolled out 😃 
cc @alexander-smolyakov @kirill-ivlev for confirmation maybe

**Comment by alexander-smolyakov** [comment]
Hey @crh225, we have updated git to version 2.36.1 in agent v2.206.1.

Related release notes: https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.206.1

So let me close this issue since agent v2.206.1 is now available to all ADO users.
