### ISSUE TITLE
Raspberry Pi B+ not working: version `CURL_OPENSSL_3' not found (required by ./bin/System.Net.Http.Native.so)

### ISSUE THREAD

**Issue by naymore** [microsoft/azure-pipelines-agent#3671]
I'm trying to set up an azure pipeline agent on my raspberry pi b+. ARM v6 (32bit).
I have DietPi running on my raspberry (debian bullseye based).

## Having issue with software on Hosted Agent?
```
DietPi:~/azure-devops-agent001$ ./config.sh
./bin/System.Net.Http.Native.so: /lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./bin/System.Net.Http.Native.so)
Warning: on some platforms, libcurl3 is required.
It was not found.
Execute ./bin/installdependencies.sh to install missing dependencies.
./config.sh: Zeile 86:  3132 Speicherzugriffsfehler  ./bin/Agent.Listener configure "$@"
DietPi:~/azure-devops-agent001$
```

The missing dependencies script did install some missing dependencies but apparently not all of them.
Running it a second time does not yield any different results.

```
root@DietPi:/home/dietpi/azure-devops-agent001# ./bin/installdependencies.sh
--------OS Information--------
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
------------------------------
The current OS is Debian based
--------Debian Version--------
11.1
------------------------------
/usr/bin/apt
OK:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
OK:2 https://archive.raspberrypi.org/debian bullseye InRelease
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Alle Pakete sind aktuell.
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
libkrb5-3 ist schon die neueste Version (1.18.3-6+deb11u1).
liblttng-ust0 ist schon die neueste Version (2.12.1-1).
zlib1g ist schon die neueste Version (1:1.2.11.dfsg-2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
libssl1.1 ist schon die neueste Version (1.1.1k-1+deb11u1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
libicu67 ist schon die neueste Version (67.1-7).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
-----------------------------
 Finish Install Dependencies
-----------------------------
root@DietPi:/home/dietpi/azure-devops-agent001#
```

I tried both libcurl4 (openSSL flavor) and libcurl3 (both nss and gnuTLS flavor) without any success.

My apt sources are as follows:
```
deb https://archive.raspberrypi.org/debian/ bullseye main
```

## Agent Version and Platform
Version of your agent? 2.195.2 (linux arm)

**Comment by naymore** [comment]
@anatolybolshakov maybe this is still a left over from https://github.com/microsoft/azure-pipelines-agent/issues/3027?

**Comment by anatolybolshakov** [comment]
Hi @naymore we are going to migrate agent to DotNet 6, although it could take some time to complete migration.
Seems that libcurl3 dependency is still required - have you tried to remove libcurl4 first, install libcurl3 and try to configure the agent?
Please note that agent portability is tightly depends on current DotNet version, and there are some platforms not supported - so if there are some dependencies missing (required for DotNet assemblies used on agent) - you would probably need to install them manually (please see [ticket](https://developercommunity.visualstudio.com/t/is-it-possible-to-install-the-agent-on-raspbian-de/752763)).

**Comment by naymore** [comment]
Yes. Did uninstall lbcurl4 prior to trying various libcurl3 libraries.
I udnerstand that the agent is depending on dotnet and hence the platforms currently supported by it. Debian/Ubuntu on ARM32 is indeed a [supported platform for netcore 3.1](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md) ;-)

So I hope the switch to NET 6 makes a difference here.

**Comment by mrlioncub** [comment]
this is relevant for arm64
