### ISSUE TITLE
Build tag was not added successfully (even though it was)

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/azure-pipelines-agent#3688]
This seems related to a very old issue (https://github.com/microsoft/azure-pipelines-agent/issues/1194).

I’m trying to add a build tag during our azdo pipeline based on the versions of some dependencies being used.
 
I have a powershell line that does this:
`Write-Host "##vso[build.addbuildtag]Pylance-$pylanceVersion"`
 
But the build fails with 
 `##[error]Build tag 'Pylance-2021.12.2 ' was not added successfully.`
 
Even though it WAS added successfully:
![image](https://user-images.githubusercontent.com/29436557/148457375-384986cc-1b19-4291-a473-28ad6067d863.png)
 
The build is at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5589863&view=results
 
Is anyone able to assist with this failure? Not sure what I’m doing wrong here, I’m just adding tags in the same way as the other existing ones.
We don't manage these agent pools, we just consume them. The agent pool is `VSEngSS-MicroBuild2022-1ES`

Thank you!

**Comment by anatolybolshakov** [comment]
Hi @AdamYoblick agent uses DevOps [server API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/tags/add-build-tag?view=azure-devops-rest-6.0) to add build tags (in source code [line](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/Build/BuildCommandExtension.cs#L192)) - and throws error if it returns null or there is no specified tag in the list of tags returned by API.
Could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by AdamYoblick** [comment]
Done! https://developercommunity.visualstudio.com/t/Build-tag-XXXXX-was-not-added-successf/1633307?space=21&entry=myfeedback

I'm internal to Microsoft, is there any team I can ping locally if I need to escalate at some point? 😄

**Comment by anatolybolshakov** [comment]
Hi @AdamYoblick closing this one as external here (as I see it was already resolved also on developer community).

**Comment by chengyu-liu-cs** [comment]
Hi, is this problem already solved ? As I am also getting error. 

In my case there was not error if I only use one cmd like this
`Write-Host "##vso[build.addbuildtag]XXX"`

But I got error if I add two tags in the same script task like this
```
script: |
  'Write-Host "##vso[build.addbuildtag]XXX" '
  'Write-Host "##vso[build.addbuildtag]YYY" '
```

Here is agent information
```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az84-543'
Current agent version: '2.200.2'
Operating System
Virtual Environment
Virtual Environment Provisioner
Current image version: '20220220.1'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: CmdLine (2.198.0)
Downloading task: PublishPipelineArtifact (1.198.0)
Downloading task: PowerShell (2.198.0)
```

**Comment by phenixita** [comment]
same problem here!
![image](https://user-images.githubusercontent.com/17789308/165712030-19b02e16-f5b2-4111-99da-7098dbd4dbc8.png)
Build log:
[33.txt](https://github.com/microsoft/azure-pipelines-agent/files/8580994/33.txt)

**Comment by phenixita** [comment]
[Found the solutions here](# https://developercommunity.visualstudio.com/t/Build-tag-XXXXX-was-not-added-successf/1633307#T-N1638741)

**Comment by shall-lw** [comment]
I've also just started to get this issue - the tags are all trimmed.

![image](https://user-images.githubusercontent.com/110806942/236613479-f6497f60-5087-40f9-9d38-ecdab2e37d50.png)

![image](https://user-images.githubusercontent.com/110806942/236613485-c3322ba8-44e1-4abb-9855-bbd5d8fe3447.png)
