### ISSUE TITLE
Pipeline getting stuck on a windows-latest pool image

### ISSUE THREAD

**Issue by Niharikadutta** [microsoft/azure-pipelines-agent#3691]
## Agent Version and Platform
Version of your agent? 2.195.2

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) 

If dev.azure.com, what is your organization name? https://dev.azure.com/dnceng 

## What's not working?
Pipeline requested to run on `windows-latest` image gets stuck on the job and cannot proceed with running the tasks. Same pipeline works fine when scheduled on `ubuntu-latest`. We started observing this from December, before that both used to run just fine. Can someone please help look into what is happening here?

**Comment by anatolybolshakov** [comment]
Hi @Niharikadutta could you please share YAML file of your pipeline and pipeline logs to take a look? Do you use classic editor or YAML, or release pipeline? Is this just a hang, or incorrect image?
Feel free to send it to my email - v-anbols@microsoft.com

**Comment by Niharikadutta** [comment]
Thanks @anatolybolshakov for your reply, I've reached out with all the information and YAML file.
