### ISSUE TITLE
Migrate agent to .NET 6

### ISSUE THREAD

**Issue by anatolybolshakov** [microsoft/azure-pipelines-agent#3692]
This issue is for tracking progress about agent migration to .NET 6 (or .NET 5 as intermediate step).

**Comment by wfurt** [comment]
I'de be happy to contribute @anatolybolshakov if that is interesting. I had 6.0 build worked out while back. 
I personally don't see any benefits of going through 5.x. 6.0 is LTS while 5.0 is not. 
And you would pick up fixes discussed with @DenisRumyantsev on https://github.com/dotnet/runtime/issues/58814
In both cases the old platform HttpClient is gone so you will need to make it work with managed implementation.

**Comment by alexander-smolyakov** [comment]
Closing it in a favour of this ticket:
- #3922
