### ISSUE TITLE
Hide interactive agent

### ISSUE THREAD

**Issue by matthias-schuchardt** [microsoft/azure-pipelines-agent#3720]
Agent version: 2.196.2.0
Operating system: Windows
ADO: dev.azure.com/ENERCON-WRD

When running an interactive environment resource agent, there is always a cmd-window shown. This is fine for running the agent `--once`. With autologon however a user might accidentally close the agent. I think it would be safer to start the agent hidden and only visible in the task manager. On top, it would also keep the desktop cleaner.

One would need to change the [autologon startup command](https://github.com/microsoft/azure-pipelines-agent/blob/b93f8f1f4e53ddf5d9cd25090db6f71b092d177c/src/Agent.Listener/Configuration.Windows/AutoLogonRegistryManager.cs#L339) as follows.

``` csharp
var startupCommand = $@"powershell -command ""Start-Process -WindowStyle Hidden cmd '/d /c ""{filePath}"" –startuptype autostartup {once}'""";
```

Also one would need to change the initial call to `run.cmd` after running `config.cmd`.

**Comment by EzzhevNikita** [comment]
@matthias-schuchardt  Thanks for the issue-reporting in this repository, currently we are under issues with higher priority, we will take a look at this ticket once we will have enough capacity.
