### ISSUE TITLE
Update Agents in Deployment Groups

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-agent#3721]
Hello,

There is a built-in option to update the Agents in Agent Pools automatically or via REST call individually. 

How can we proceed same functionality for the Agents in Deployment Groups?
Is there any way to trigger the Agent to update itself from a Release Pipeline or via REST call?

Using log4j series 1.x in TEE plugin to access TFVC resources on Linux Agents give priority to this case.

`Since the TEE plugin is no longer maintained and contains some out-of-date Java dependencies, starting from Agent 2.198.0 it's no longer included in the agent distribution. However, the TEE plugin will be downloaded during checkout task execution if you're checking out a TFVC repo. The TEE plugin will be removed after the job execution.` [Microsoft](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#tfvc)

Thanks a lot!

Regards,
Gabor

**Comment by EzzhevNikita** [comment]
Hey, @iambernics you can use the Updates Targets option to force an update of agents in the deployment group ([doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops#set-up-agents-on-deployment-groups)).

![image](https://user-images.githubusercontent.com/23104121/151790340-a60e434c-75bc-4831-ba3e-98378993b5c3.png)

**Comment by EzzhevNikita** [comment]
@iambernics Do you have any additional questions regarding agents' updates in deployment groups?

**Comment by EzzhevNikita** [comment]
@iambernics I am closing this ticket, for now, feel free to ping me in case of any future questions.
