### ISSUE TITLE
Docker - Do not use pre-release versions of Agent

### ISSUE THREAD

**Issue by jsheetzati** [microsoft/azure-pipelines-agent#3725]
## Agent Version and Platform
Ubuntu 20.04
Agent Version 2.198.2

## Azure DevOps Type and Version
Azure DevOps

## What's not working?
We are using the self-hosted agent running in a container. When our agents spin up, they are installing a pre-release version of the agent. Specifically, version 2.198.2, which is marked as a Pre-release. Is there a way for us to ignore pre-release versions and use the latest released version of the agent?

The `start.sh` from https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#create-and-build-the-dockerfile-1 has this logic:

```shell
AZP_AGENT_PACKAGES=$(curl -LsS \
    -u user:$(cat "$AZP_TOKEN_FILE") \
    -H 'Accept:application/json;' \
    "$AZP_URL/_apis/distributedtask/packages/agent?platform=$TARGETARCH&top=1")
```

When I run the same command, it is pulling back 2.198.2. Ideally, we have a way to ignore pre-release versions of the agent.

**Comment by EzzhevNikita** [comment]
Hey @jsheetzati, the pre-prerelease state is a part of our deployment process and actually means that we are not completed the deployment of the agent for all customers. [Here](https://github.com/microsoft/azure-pipelines-agent#latest-and-pre-release-labels-for-releases) is some more info about our deployment states.

**Comment by jsheetzati** [comment]
Thanks @EzzhevNikita, I missed that.
