### ISSUE TITLE
task.js not found for any tasks on freshly installed agent 2.198.2

### ISSUE THREAD

**Issue by vperez-dart** [microsoft/azure-pipelines-agent#3728]
## Agent Version and Platform
Version of your agent? 2.198.2

OS of the machine running the agent? Windows Server 2019 Datacenter

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? dev.azure.com

If dev.azure.com, what is your organization name? https://dart-dev.visualstudio.com

## What's not working?
We just added agents to our self-hosted pool on a new server, any builds assigned to the new agents throws errors like this:
```
[2022-02-02 18:16:24Z ERR  BuildJobExtension] Caught exception from JobExtension Initialization: System.IO.FileNotFoundException: Could not find file 'D:\BuildAgent1\_work\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\1.198.0\task.json'.
```

The directories supposed to contain task files code are empty:
```
D:\BuildAgent1\_work\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\1.198.0>dir
 Volume in drive D is Data
 Volume Serial Number is 8E18-207F

 Directory of D:\BuildAgent1\_work\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\1.198.0

02/01/2022  07:29 PM    <DIR>          .
02/01/2022  07:29 PM    <DIR>          ..
12/28/2021  03:45 AM             9,355 .signature.p7s
02/01/2022  07:29 PM    <DIR>          node_modules
02/01/2022  07:29 PM    <DIR>          Strings
               1 File(s)          9,355 bytes
               4 Dir(s)  1,093,784,256,512 bytes free
```

The same folder on another server which was provisioned at the same time around a year ago and has agents working fine:
```
D:\BuildAgent1\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\1.198.0>dir
 Volume in drive D is Data
 Volume Serial Number is 883C-34F0

 Directory of D:\BuildAgent1\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\1.198.0

01/24/2022  11:34 AM    <DIR>          .
01/24/2022  11:34 AM    <DIR>          ..
12/28/2021  03:45 AM             9,355 .signature.p7s
12/28/2021  11:31 AM             1,621 icon.png
12/28/2021  11:31 AM             1,624 icon.svg
01/24/2022  11:34 AM    <DIR>          node_modules
12/28/2021  11:31 AM             2,949 nugettoolinstaller.js
12/28/2021  11:31 AM               916 package.json
01/24/2022  11:34 AM    <DIR>          Strings
12/28/2021  11:31 AM             5,396 task.json
12/28/2021  11:31 AM             4,031 task.loc.json
12/28/2021  11:43 AM               296 task.nuspec
               8 File(s)         26,188 bytes
               4 Dir(s)  916,625,043,456 bytes free
```

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.
[Worker_20220202-181622-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7989360/Worker_20220202-181622-utc.log)
[Agent_20220202-175635-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7989362/Agent_20220202-175635-utc.log)

**Comment by vperez-dart** [comment]
Just to clarify: we got 2 identical servers provisioned as build servers a year ago. We installed agents to the first. The second one sat idle until we installed agents today.

**Comment by EzzhevNikita** [comment]
@vperez-dart I couldn't reproduce it on my end. Looks like could be a problem with the task installation of the agent, could you please manually try to remove tasks inside __tasks_ folder on the affected server, the agent will reinstall them.

If it won't help please share diagnostic logs for the pipeline, to get them you need to run a pipeline with enabled diagnostics mode, if you are using yml pipeline, you can just set _Enable system diagnostics_ toggle in _Run pipeline_ menu. If you are using a classic pipeline you will need to set _System.Debug_ and _Agent.Diagnostic_ variables to true in the pipeline. After the pipeline is completed please download the archive with logs from pipeline results UI and share it with me. These logs could contain sensitive data, so it would be better if you will send an archive to my email - v-niezz@micrsoft.com.

**Comment by vperez-dart** [comment]
Thank you, deleting _tasks folder fixed it.

This was caused by me mistakenly pointing all 4 agents to the same work folder. They likely conflicted with each other when downloading into _tasks folder.

I think this bug is in the "Ensuring task exists" steps on TaskManager which didn't detect they were incomplete. I think TaskManager should validate the task is complete and fail the build if unable to update it. Low priority thought, since workaround is to wipe _tasks folder.

**Comment by EzzhevNikita** [comment]
@vperez-dart That's great that the issue was resolved.
We will take a look at how we could improve the process of task validation to avoid such a situation as you had.
