### ISSUE TITLE
Bearer token for git auth lowercase violates RFC

### ISSUE THREAD

**Issue by davidgiga1993** [microsoft/azure-pipelines-agent#3735]
When using git checkout, the bearer token is sent as lowercase (see [code here](https://github.com/microsoft/azure-pipelines-agent/blob/453d27c94ff7e54e7576a3490758cb27a4551a82/src/Agent.Worker/Build/GitSourceProvider.cs#L191)) but according to RFC it should be with a uppercase B
see https://datatracker.ietf.org/doc/html/rfc6750#section-2.1

This may cause issues with authentication proxy servers (outside of TFS) which strictly follow the RFC. In my concret example we're using an authentication proxy to enforce 2FA and it only passes through `Bearer` tokens, not `bearer`

**Comment by EzzhevNikita** [comment]
@davidgiga1993 Thanks, for the issue reporting we will take a look at this issue.

**Comment by siprbaum** [comment]
Hm, the above pull request is still not merged ...

**Comment by davidgiga1993** [comment]
Any update on this?

**Comment by jessehouwing** [comment]
Please reopen.
