### ISSUE TITLE
TFVC - During Unshelving task files are not downloaded in directory

### ISSUE THREAD

**Issue by Baajl** [microsoft/azure-pipelines-agent#3750]
## Agent Version and Platform

Version of your agent? 2.198.3
OS of the machine running the agent? Windows 10

## Azure DevOps Type and Version
Azure DevOps Online / Private Repository

## What's not working?

During the Checkout Task of a TFVC project, files of a gated check in are correctly Unshelve but are not download in folder. 
When i look for folder informations, i can see that last modification is the same as my CI but there is no files inside this folder.

## Agent and Worker's Diagnostic Logs

Task Log.
```
Starting: Checkout talend@ to s
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Prepending Path environment variable with directory containing 'tf.exe'.
Setting environment variable TFVC_BUILDAGENT_POLICYPATH
Querying workspace information.
tf vc get /version:3707 /recursive /overwrite F:\agent\_work\4\s /loginType:OAuth /login:.,*** /noprompt
All files are up to date.
Cleaning last saved checkin metadata.
tf vc unshelve gatedcheckin@XXX /loginType:OAuth /login:.,*** /noprompt
GFC\code\beans\Tests:
Unshelving add: TestXXX_0.1.item
Unshelving add: TestXXX_0.1.properties

GFC\routes\Tests:
Unshelving add: R_TEST_SousEnsemble_2_0.1.item
Unshelving add: R_TEST_SousEnsemble_2_0.1.properties
Unshelving add: R_TEST_SousEnsemble_2_0.1.screenshot
Finishing: Checkout talend@ to s

```

**Comment by golubev-ivan** [comment]
Hi @Baajl, I haven't managed to reproduce this issue. How long have you been facing this problem and on which versions of the agent does this problem occur, other than the one you mentioned? Could you please share yaml config of your pipeline, where is this problem caused, or settings of checkout?

**Comment by Baajl** [comment]
Hi @golubev-ivan the test was done on 2.196.2 and 2.198.3 agent. 
I'm using Classic pipeline, this is the checkout :

<img width="1359" alt="Capture d’écran 2022-02-17 à 14 22 52" src="https://user-images.githubusercontent.com/2916405/154491152-e606f3ec-39f6-481b-ae39-6635b100cb22.png">
.

**Comment by Baajl** [comment]
@golubev-ivan I have identify the problem, security software with wrong configuration, i'm really sorry for the time lost. Thanks for your help
