### ISSUE TITLE
Improve Agent Capabilities Check: Output Info When No Online/Enabled Agents Satisfy Capabilities

### ISSUE THREAD

**Issue by Cpcrook** [microsoft/azure-pipelines-agent#3769]
## Agent Version and Platform
2.200.2 / 2.193.0 Windows self-hosted agents in an Azure VM

## Azure DevOps Type and Version
dev.azure.com

https://dev.azure.com/kcic

## What's not working?

**Expected**

- Given I add new build agents to an existing pool,
- And those build agents are not in parity with the capabilities of existing agents
- And I disable the existing agents in order to test the new agents
- When I enqueue a build that the new agents do not have capabilities to run
- Then I expect to see an error message indicating which capabilities are not met by the currently-enabled/online agents

Example error that is shown when _all agents_ in a pool do not have the requisite capabilities:
![image](https://user-images.githubusercontent.com/643732/156063823-caa53ebf-b9ee-495a-bf50-888bc8b2afcc.png)

**Actual Behavior**

- Given I add new build agents to an existing pool,
- And those build agents are not in parity with the capabilities of existing agents
- And I disable the existing agents in order to test the new agents
- When I enqueue a build that the new agents do not have capabilities to run
- Then the build hangs waiting for offline/disabled agents that have the required capabilities, despite those agents being offline and/or disabled.

We ran into an issue identifying what was missing capabilities wise with our newly-added build agents.  We added new agents (on a new box) to an existing pool.  With the existing (old) agents disabled, builds would hang in the queue with no feedback in the diagnostic logs or Azure Pipelines UI as to why they were not eligible to run on the new, enabled agents.

**Capabilities should only be checked against online, enabled agents, not the full pool of agents when determining if a build can be run by a given pool.** 

Alternatively (or in addition to the above request) being able to do side-by-side comparisons of agent capabilities would be useful.

**Comment by alexander-smolyakov** [comment]
@Cpcrook, the agent capabilities checking is handled by the Azure DevOps itself. Could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 to get the right eyes on it?

**Comment by Cpcrook** [comment]
@alexander-smolyakov Done: https://developercommunity.visualstudio.com/t/improve-agent-capabilities-check-output-info-when/1680059

**Comment by alexander-smolyakov** [comment]
@Cpcrook thanks! Let me close this issue then.
