### ISSUE TITLE
v2.200.2 appears to break running msiexec from a script

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/azure-pipelines-agent#3770]
## Having issue with YAML?
It's a YAML build pipeline but the issue isn't about YAML.

## Having issue with Tasks?
It doesn't look like an issue with a specific task; rather, it is more likely something related to the environment created by the agent to run builds, so I'm filing here.

## Having issue with software on Hosted Agent?
No.

## Having generic issue with Azure-Pipelines/VSTS/TFS?
I don't believe so.

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

**this link is broken :)**

## Agent Version and Platform
Version of your agent? v2.200.2

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/vcpkg

## What's not working?
Since around the same time v2.200.2 was shipped our builds' attempt to unpack an MSI fails with the message:

```
[DEBUG] 7532: cmd_execute_and_stream_data() returned 1601 after    48467 us
The Windows Installer service could not be accessed. Contact your support personnel to verify that the Windows Installer service is properly registered.
```

Did anything change about how Scale Set Agents configure the agent to run recently? It's possible another change was pushed by other folks who have permission to push stuff to our VMs but the timing lines up with this agent release.

## Agent and Worker's Diagnostic Logs
I am unable to log in to the machines in question as they are a Scale Set Agent.

**Comment by BillyONeal** [comment]
I don't see anything in the history between the previous release and now suggesting that which user etc. are used has changed; but I also don't know if the script used by Scale Set Agents to deploy the agent into the VMs is here. If there's another repo I should be looking at for that please feel free to close here and point me :)

**Comment by alexander-smolyakov** [comment]
@BillyONeal this repo is specific for the ADO agent itself, for the "Azure Virtual Machine Scale Sets" related questions and its configuration scripts please open an issue in [Developer Community](https://developercommunity.visualstudio.com/search?space=21).

**Comment by BillyONeal** [comment]
> @BillyONeal this repo is specific for the ADO agent itself, for the "Azure Virtual Machine Scale Sets" related questions and its configuration scripts please open an issue in [Developer Community](https://developercommunity.visualstudio.com/search?space=21).

You're confirming that decisions like this aren't made on behalf of the agent?

**Comment by BillyONeal** [comment]
We're seeing this issue gradually get better over time so I suspect it was one of the security things pushed to that pool or something :/. Sorry for the noise!
