### ISSUE TITLE
Windows: Registration script does not work behind proxy

### ISSUE THREAD

**Issue by SiulOgait** [microsoft/azure-pipelines-agent#3774]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting) Yes

## Agent Version and Platform
Version of your agent? N/A as issue is prior to agent running

OS of the machine running the agent? Windows

## Azure DevOps Type and Version

If dev.azure.com, what is your organization name? https://dev.azure.com/LiberataUK

## What's not working?
Hi,

The registration script for powershell in Windows that gets shown in a deployment group doesn't always work when the user is behind a proxy, it detects the proxy ok but the download of the agent zip file fails as the credentials are not set properly on the proxy.

Can the script can be customized to include proxy credentials?

Thanks :)

## Agent and Worker's Diagnostic Logs
N/A as issue is prior to agent running

**Comment by alexander-smolyakov** [comment]
Hey @SiulOgait, could you please clarify which PowerShell script you are using to register the pipeline agent? Would you mind sharing an example of this script?

**Comment by alexander-smolyakov** [comment]
@SiulOgait, is this issue still actual to you?

**Comment by SiulOgait** [comment]
Hi, Sorry for the late response.
I'm using the pre-filled PowerShell script with PAT enabled that is
generated when you create a deployment group.

[image: image.png]

Thanks for your help. Regards

**Comment by alexander-smolyakov** [comment]
@SiulOgait, thanks for clarification! This question is more relevant for the Azure DevOps side, although this repo is mostly for the pipeline agent itself - could you please open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by SiulOgait** [comment]
Hi,

I read that the script can be customized to suit varied requirements but I haven't found any info on it. Can you please let me know how to customize the script to bypass the proxy issue or how to add the proxy credentials to the script.

Cheers,
