### ISSUE TITLE
How to make the agent's process to fail whenever the job fails? - using KEDA ScaledJob to run the workload.

### ISSUE THREAD

**Issue by michalrom089** [microsoft/azure-pipelines-agent#3776]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting) - N/A

## Agent Version and Platform
Version of your agent? 2.200.2

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

## What's not working?

I'm running Pipelines jobs as KEDA scaled jobs using `--once` to shutdown the agent after the first executed job. What's I'm missing is the configuration that would make the agent process to fail whenever the job fails. Ideally, the job that created the pod would be marked as failed and kept within failed history for the further investigation.

Is this possible to do?

**Comment by DenisRumyantsev** [comment]
Hi @michalrom089, we can not start working on your question right now, but we will be back as soon as we can.

**Comment by anatolybolshakov** [comment]
Hi @michalrom089 as I know there is no such ability at the moment.

**Comment by michalromanowskiap** [comment]
Ok, thanks for the answer. I assume that there's no space for introducing this feature?

**Comment by michalrom089** [comment]
Thanks a lot. I assume that there's no space for introducing this feature?

**Comment by anatolybolshakov** [comment]
@michalrom089 yes, there is no capacity to pick it up at the moment as I know unfortunately - we are going to leave it in the backlog till we'll be able to pick it up.
