### ISSUE TITLE
java capability not detected properly with Eclipse Adoptium

### ISSUE THREAD

**Issue by michha** [microsoft/azure-pipelines-agent#3777]
Once again a java detection issue.
The Adopt OpenJDK moved to the eclipse platform (see https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/) and  also got new registry keys for the installer.

We need again something like #3533

Sidenote:
https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/powershell/Add-JavaCapabilities.ps1#L24-L25 already has some `Eclipse Foundation` variables. Maybe Eclipse changed their registry keys since those variables were added some months ago 🤷 

## Agent Version and Platform
2.200.2

Docker: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

## What's not working?
Agent doesnt show full Java capability. Only the variable `JAVA_HOME` is set. The variables `java` and `java_11_x64` are missing.
2nd Sidenote: if I manually edit `Add-JavaCapabilities.ps1` and change `Eclipse Foundation` to `Eclipse Adoptium` all 3 variables are set correctly 😃 

I listed the needed registry keys:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\agent> java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)
PS C:\agent> cd 'HKLM:\SOFTWARE\Eclipse Adoptium\JRE\11.0.14.101\hotspot\'
PS HKLM:\SOFTWARE\Eclipse Adoptium\JRE\11.0.14.101\hotspot\> dir


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Eclipse Adoptium\JRE\11.0.14.101\hotspot


Name                           Property
----                           --------
MSI                            Path                        : C:\java\
                               EnvironmentPath             : 1
                               EnvironmentPathSetForSystem : 1
                               JavaHome                    : 1
                               JavaHomeSetForSystem        : 1
                               Main                        : 1


PS HKLM:\SOFTWARE\Eclipse Adoptium\JRE\11.0.14.101\hotspot\>
```

I am unsure if the existing variables should be changed (from `Eclipse Foundation` to `Eclipse Adoptium`) or new should be added 🤔 

I need you again @EzzhevNikita 😊

**Comment by DenisRumyantsev** [comment]
Hi @michha, we can not start working on this issue right now, but we will be back as soon as we can.
