### ISSUE TITLE
Unable to point working directory to a different VM partition with sufficient space

### ISSUE THREAD

**Issue by MohamedElyaman-Eaton** [microsoft/azure-pipelines-agent#3778]
I am having a problem trying to redirect my working directory to a larger partition on a created Azure VM. As part of image creation, I edited the crontab as follows to create a directory and give all users permissions. Then I set the environment variable "VSTS_AGENT_INPUT_WORK" to point to the created directory.

```
function updateCrontabJob {
    mnt_dir="$1"
```

    # Create work folder and provide full executable permissions to this folder
    line1="@reboot sudo mkdir $mnt_dir"
    line2="@reboot sudo chmod -R 777 $mnt_dir"
    line3="@reboot sudo chmod o+x $mnt_dir "
    line4="@reboot sudo chown -R AzDevOPs $mnt_dir "
    line5="@reboot sudo chmod o+w $mnt_dir "
    line6="@reboot sudo chmod o+r $mnt_dir "

    echo "Create empty crontab"
    (crontab -l 2>/dev/null; echo "") | crontab -

    echo "Writing crontab: $line1"
    (crontab -l 2>/dev/null; echo "$line1") | crontab -

    echo "Writing crontab: $line2"
    (crontab -l 2>/dev/null; echo "$line2") | crontab -

    echo "Writing crontab: $line3"
    (crontab -l 2>/dev/null; echo "$line3") | crontab -

    echo "Writing crontab: $line4"
    (crontab -l 2>/dev/null; echo "$line4") | crontab -

    echo "Writing crontab: $line5"
    (crontab -l 2>/dev/null; echo "$line5") | crontab -

    echo "Writing crontab: $line6"
    (crontab -l 2>/dev/null; echo "$line6") | crontab 

    echo "Get file contents"
    cat /var/spool/cron/crontabs/root
}

```
updateCrontabJob /mnt/work
setEtcEnvironmentVariable "VSTS_AGENT_INPUT_WORK" /mnt/work
```
This only partially works, as there is a race condition between crontab and the VM attempting to start tasks. If crontab is able to complete the above commands before the VM starts tasks, the working directory will be successfully migrated to the bigger partition. However that is not always the case. Is there a way to ensure commands run **before** the VM starts tasks?

**Comment by DenisRumyantsev** [comment]
Hi @MohamedElyaman-Eaton, we can not start working on this issue right now, but we will be back as soon as we can.

**Comment by AndreyIvanov42** [comment]
Hi @MohamedElyaman-Eaton, sorry for the delay with answer.
I think your task can be resolved in another way. Please look here - https://azure.microsoft.com/nl-nl/blog/automate-linux-vm-customization-tasks-using-customscript-extension/. Also you can ask for help here - https://developercommunity.visualstudio.com/. 

Because your question is not directly related to the agent himself, I will close this ticket
