### ISSUE TITLE
Azure Pipelines Agent - Downgrade to a lower version with V2.200.2

### ISSUE THREAD

**Issue by shs-marcobrettschneider** [microsoft/azure-pipelines-agent#3779]
## Agent Version and Platform
Version of your agent? 2.200.2 (latest to date)

OS of the machine running the agent? Windows 10

## Azure DevOps Type and Version
Azure DevOps Server on-premise

If on-premises, which release? 2020.1

## What's not working?
Hello,

we are currently providing Azure Pipelines agents to VMs independent from the version added to Azure DevOps Server. Beforehand, we used the version 2.169.1, which works fine. Unfortunately with the newest version 2.200.2, we are facing a problem:

**"Downgrading agent to a lower version. This is usually due to a rollback of the currently published agent for a bug fix. To disable this behavior, set environment variable AZP_AGENT_DOWNGRADE_DISABLED=true before launching your agent."**

After that, The agent tries to rollback the 2.200.2 version and wants to use the version provided by our Azure DevOps Server (2.187.2).

This should in my opinion not happen. I would like to just install the azure pipelines agent and run it. There should now downgrading attempt happening.

Is this a known issue, is this a bug? I would suggest, that the newest version would be fixed such an issue. I have also seen this with the 2.198.2 and 2.198.3, so I was hoping to don't see this downgrade-message again.

Do you have any information about this?
I see that I could set the environment variable "AZP_AGENT_DOWNGRADE_DISABLED" to true, but I think it should not be the intended way. Or do I **need** to set this environment variable?

Thanks and best regards,
Marco

**Comment by anatolybolshakov** [comment]
Hi @hez2010 yes, you can use this environment variable to disable automatic downgrade to agent version originally shipped with on-prem server.
Please be aware that there could be some incompatibility issues while using newer agent versions with on-prem server.

**Comment by anatolybolshakov** [comment]
Hi @hez2010 please ping if you have any other questions.
