### ISSUE TITLE
Docker Build Container fails for exec containerHandlerInvoker.js and node/bin/node

### ISSUE THREAD

**Issue by kitsushadow** [microsoft/azure-pipelines-agent#3780]
##[debug]Using node path: /opt/myagent/externals/node10/bin/node
module.js:478
    throw err;
    ^

Error: Cannot find module '/__w/_temp/containerHandlerInvoker.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
##[error]Exit code 1 returned from process: file name '/bin/docker', arguments 'exec -i -u 1002  -w /home/vsts_azpcontainer 70a4720a7df9e529c67fea5cd8be0711ac76be1a6c4c0165d87c8928d63b2869 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name '/bin/docker', arguments 'exec -i -u 1002  -w /home/vsts_azpcontainer <container_id> /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.

## Agent Version and Platform
Version of your agent? 2.200.0

CentOS 7

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or 
Federal Client not sharing

## What's not working?
`##[debug]Using node path: /opt/myagent/externals/node10/bin/node
module.js:478
    throw err;
    ^

Error: Cannot find module '/__w/_temp/containerHandlerInvoker.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
##[error]Exit code 1 returned from process: file name '/bin/docker', arguments 'exec -i -u 1002  -w /home/vsts_azpcontainer 70a4720a7df9e529c67fea5cd8be0711ac76be1a6c4c0165d87c8928d63b2869 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name '/bin/docker', arguments 'exec -i -u 1002  -w /home/vsts_azpcontainer <container_id> /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.`

## Agent and Worker's Diagnostic Logs
Diag Logs are the same.

**Comment by anatolybolshakov** [comment]
Hi @kitsushadow could you please share your agent/worker logs (please make sure that you masked all the relevant secrets)?

**Comment by anatolybolshakov** [comment]
Hi @kitsushadow do you have any updates?

**Comment by andrey-parkhomets** [comment]
I have similar issue, running agent within a POD on AKS (v1.21.7, with containerd), as sidecar these also docker:20.10-dind container which allows to start custom containers in pipelines, but feature "container jobs" getting failed while using self hosted agents:
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/__w/_temp/containerHandlerInvoker.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
##[error]Exit code 1
```

What is the logic behind containerHandlerInvoker.js.template to be copied to containerHandlerInvoker.js ?

I see that is present in agent folder, but containerHandlerInvoker.js created only when container is created ( checked with Azure hosted agents)

**Comment by andrey-parkhomets** [comment]
I was able find workaround by sharing few folders between agent container and DinD container with few hacks, after that container jobs start working.

**Comment by Liamdoult** [comment]
Our team is facing this issue consistently in our ADO pipeline (my estimate would be 5% of runs):
``` bash
Starting: Run tests: ConfigurationTelemetry.Abstractions.Test (windows_build_container)
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.240.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
container d259484f5768a8838fbab5e74f3726f18a28ddbc873228783b426057eac322bc encountered an error during hcs::System::CreateProcess: C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js: failure in a Windows system call: The RPC server is unavailable. (0x6ba)
##[warning]RetryHelper encountered exception, will retry (attempt #: 1 Exit code 126 returned from process: file name 'C:\Windows\system32\docker.EXE', arguments 'exec -i   d259484f5768a8838fbab5e74f3726f18a28ddbc873228783b426057eac322bc C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js'.) afer 1000 ms
container d259484f5768a8838fbab5e74f3726f18a28ddbc873228783b426057eac322bc encountered an error during hcs::System::CreateProcess: C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js: failure in a Windows system call: The RPC server is unavailable. (0x6ba)
##[warning]RetryHelper encountered exception, will retry (attempt #: 2 Exit code 126 returned from process: file name 'C:\Windows\system32\docker.EXE', arguments 'exec -i   d259484f5768a8838fbab5e74f3726f18a28ddbc873228783b426057eac322bc C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js'.) afer 4000 ms
container d259484f5768a8838fbab5e74f3726f18a28ddbc873228783b426057eac322bc encountered an error during hcs::System::CreateProcess: C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js: failure in a Windows system call: The RPC server is unavailable. (0x6ba)
##[error]Exit code 126 returned from process: file name 'C:\Windows\system32\docker.EXE', arguments 'exec -i   d259484f5768a8838fbab5e74f3726f18a28ddbc873228783b426057eac322bc C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js'.
Finishing: Run tests: ConfigurationTelemetry.Abstractions.Test (windows_build_container)
```
