### ISSUE TITLE
Shared volume artifacts between container (vsts agent) and host are not getting deleted

### ISSUE THREAD

**Issue by geralexgr** [microsoft/azure-pipelines-agent#3782]
In private agent pools that have couple of agents registered inside them, I have configured the retention policies based on the organizations needs and its works only on the web and not on the OS. In more details, retention policies seem to work on the https://dev.azure.com/Project/pipeline and only 30 days of running jobs are kept. However the artifacts are not getting deleted from the OS drive on which the agents writes the data. 

Agents are created as containers inside a Windows server with docker runtime installed. A share between the host and the agents has been created in order not to fill up agents space. For example

## Have you tried troubleshooting?
No

## Agent Version and Platform
Agent.Version 2.196.2
Agent.OS Windows_NT
Architecture x64
Agent.OSVersion 10.0.17763

OS of the machine running the agent? OSX/Windows/Linux/...

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/{VivaPayments}

## What's not working?
Agents write artifacts on S:\artifacts as a mapping has been created inside C:\artifacts on the container and S:\artifacts. The problem is that those artifacts are not getting deleted from the Operating system (Windows host) although the cleaning procedure on dev.azure.com seems to be correct.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by anatolybolshakov** [comment]
Hi @geralexgr retention settings are mostly for pipeline artifacts (stored on a server) - you can schedule maintenance job to clean up stale working directories and repositories - see more details in [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser#what-is-a-maintenance-job).

**Comment by geralexgr** [comment]
@anatolybolshakov as I understand from your answer, the retention policies apply only to the below artifacts and not the ones that are saved on the container agent or the filesystem. Is that correct? As a result I should define my own cleaning procedure right?

![image](https://user-images.githubusercontent.com/3514710/158961203-6d4eab3b-b29a-42fd-9083-73f37e8a52ee.png)

**Comment by anatolybolshakov** [comment]
@geralexgr yes, you can set up maintenance job separately to make clean up on a agent machine. Feel free to open a ticket no https://developercommunity.visualstudio.com/search?space=21 to ask about more details - since this is more related to Azure DevOps infrastructure.

**Comment by geralexgr** [comment]
@anatolybolshakov Let me understand something.

Using the below documentation https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml 

it is stated that 

`The Copy Files task is preferable to the [Publish Build Artifacts task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops) because data saved with the Publish Build Artifacts task will get periodically cleaned up and deleted.`

Should with the build artifacts retention also the artifacts on the private agents be deleted? 

As we expose the artifacts on a separate folder on private container agents (C:\artifacts) the maintenance jobs will not delete the files requested as I undestand. The working directories that will get deleted do not occupy so much space in our setup, but the C:\artifacts folders do.

**Comment by geralexgr** [comment]
I created the relevant bug on below location. Closing the bug and if needed I will reopen. 

https://developercommunity.visualstudio.com/t/Azure-devops-self-hosted-container-agent/1696567?space=21&entry=problem
