### ISSUE TITLE
nuget version going backwards from windows 2019 to windows 2022

### ISSUE THREAD

**Issue by SamWhitby** [microsoft/azure-pipelines-agent#3783]
## Agent Version and Platform
Version of your agent? 2.200.2

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
**Situation**
We are using a windows-latest vm image for our pipelines that makes use of the NuGetCommand@2 task. The latest windows os version has recently been changed from windows-2019 to windows-2022. 

**Problem**
The problem is that the latest vm image seems to have a old version of nuget installed on it as the NuGetCommand@2 task is now using version 4.1.0. This was previously using 5.8.0 for the windows 2019 image. This old version does not work with our software.

The version specified in the docs say windows 2022 should be using 6.1.0.106 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#package-management

I know i can install the latest version of nuget in a separate task, however i would prefer not to do this and just use the default version installed on the vm image assuming it should be the latest.

windows 2019
![image](https://user-images.githubusercontent.com/3334161/158879004-794f41e8-707a-49b1-af53-b182bda61e90.png)
![image](https://user-images.githubusercontent.com/3334161/158878752-2ab59dce-d805-462e-a55f-0e90ae3d43ea.png)

windows 2022
![image](https://user-images.githubusercontent.com/3334161/158879234-078fab17-47b1-4ba8-b6a7-39f3ee2b7e69.png)
![image](https://user-images.githubusercontent.com/3334161/158879626-7beecb5e-3bf2-4487-9cfb-3555edcc4e71.png)

**Comment by anatolybolshakov** [comment]
Hi @SamWhitby since this is relate to the tool versions preinstalled on hosted agent machine image - could you please open a ticket on https://github.com/actions/virtual-environments/issues to get right eyes on it?

**Comment by SamWhitby** [comment]
Sure @anatolybolshakov, new issue referenced below, I'll close this one.
#https://github.com/actions/virtual-environments/issues/5258
