### ISSUE TITLE
Can not override `NO_PROXY` (`*` not mapped to ECMAScript syntax)

### ISSUE THREAD

**Issue by HofmeisterAn** [microsoft/azure-pipelines-agent#3790]
## Agent Version and Platform

- 2.200.2
- Windows

## Azure DevOps Type and Version

- https://dev.azure.com/ZEISSgroup-SMT

## What's not working?

The proxy configuration through `.proxybypass` is not exclusive. The Azure Pipelines Agent uses the proxy configuration from different sources. **It's not possible to override the configuration from `NO_PROXY` (env variable)**.

https://github.com/microsoft/azure-pipelines-agent/blob/c5e9872c7c88713401aac5111f92e20c8cfc70ab/src/Microsoft.VisualStudio.Services.Agent/VstsAgentWebProxy.cs#L130-L149

The Azure Pipelines Task SDK expect the proxy configuration in ECMAScript syntax, but other tools do not. We get following error: `Invalid regular expression: /*\.zeiss\.org/: Nothing to repeat`. Even if we set the proxy configuration through `.proxybypass`, `NO_PROXY` is read.

Our configuration:

- `.proxybypass`
    - `localhost`
    - `10\.1\.1\.\d{1,3}`
    - `.*\.zeiss\.org`
- `NO_PROXY`
    - `localhost,10.1.1.0/26,*.zeiss.org`

will set the `Agent.ProxyBypassList` variable to:

- `localhost`
- `10\\.1\\.1\\.\\d{1,3}`
- `.*\\.zeiss\\.org`
- `localhost`
- `10\\.1\\.1\\.0/26`
- **`*\\.zeiss\\.org`**

As you can see, the last item is not valid ECMAScript syntax. A lot of different tools use this syntax for `NO_PROXY`.
You already map the env variables to a different syntax (`.` → `\\.`). It's probably necessary to map `*` too.

https://github.com/microsoft/azure-pipelines-agent/blob/c5e9872c7c88713401aac5111f92e20c8cfc70ab/src/Microsoft.VisualStudio.Services.Agent/VstsAgentWebProxy.cs#L235

## Agent and Worker's Diagnostic Logs

```log
Checking job knob settings.
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY}
   Knob: NoProxy = localhost,10.1.1.0/26,*.zeiss.org Source: ${no_proxy}
   Knob: ProxyAddress = http://10.2.2.95:80 Source: ${http_proxy}
Finished checking job knob settings.

...

##[debug]Agent.ProxyUrl=http://10.2.2.95:80
##[debug]Agent.ProxyUsername=undefined
##[debug]Agent.ProxyPassword=undefined
##[debug]Agent.ProxyBypassList=["localhost","10\\.1\\.1\\.\\d{1,3}",".*\\.zeiss\\.org","localhost","10\\.1\\.1\\.0/26","*\\.zeiss\\.org"]
```

**Comment by HofmeisterAn** [comment]
The issue still exists.

**Comment by BzSpi** [comment]
Do not close !
