### ISSUE TITLE
VSTS Agent Extension in ARM template: windowsLogonAccount and windowsLogonPassword ?

### ISSUE THREAD

**Issue by adamency** [microsoft/azure-pipelines-agent#3798]
In ARM templates we can install an Azure DeploymentGroup agent on a VM this way:

```
"resources": [
  {
    "name": "[concat(parameters('vmNamePrefix'),copyIndex(),'/TeamServicesAgent')]",
    "type": "Microsoft.Compute/virtualMachines/extensions",
    "location": "[parameters('location')]",
    "apiVersion": "2015-06-15",
    "dependsOn": [
        "[resourceId('Microsoft.Compute/virtualMachines/',
                      concat(parameters('vmNamePrefix'),copyindex()))]"
    ],
    "properties": {
      "publisher": "Microsoft.VisualStudio.Services",
      "type": "TeamServicesAgent",
      "typeHandlerVersion": "1.0",
      "autoUpgradeMinorVersion": true,
      "settings": {
        "VSTSAccountName": "[parameters('VSTSAccountName')]",
        "TeamProject": "[parameters('TeamProject')]",
        "DeploymentGroup": "[parameters('DeploymentGroup')]",
        "AgentName": "[parameters('AgentName')]",
        "Tags": "[parameters('Tags')]"
      },
      "protectedSettings": {
      "PATToken": "[parameters('PATToken')]"
     }
   }
  }
]
```

and with a Dev Test Lab VM we can do it this way:

```
"artifacts": [
          {
            "artifactId": "[resourceId('Microsoft.DevTestLab/labs/artifactSources/artifacts', parameters('labName'), 'public repo', 'windows-deploymentgroup')]",
            "parameters": [
              {
                "name": "accountUrl",
                "value": "[parameters('accountUrl')]"
              },
              {
                "name": "projectName",
                "value": "[parameters('projectName')]"
              },
              {
                "name": "deploymentGroupName",
                "value": "[parameters('deploymentGroupName')]"
              },
              {
                "name": "PersonalAccessToken",
                "value": "[parameters('PersonalAccessToken')]"
              },
              {
                "name": "deploymentAgentTags",
                "value": "[parameters('deploymentAgentTags')]"
              },
              {
                "name": "agentName",
                "value": "[parameters('agentName')]"
              },
              {
                "name": "RunAsAutoLogon",
                "value": "[parameters('RunAsAutoLogon')]"
              },
              {
                "name": "windowsLogonAccount",
                "value": "[(parameters('userName')]"
              },
              {
                "name": "windowsLogonPassword",
                "value": "[parameters('password')]"
              }
            ]
          }
        ]
```

I am dependent upon the two last parameters in the dev test lab version, namely *windowsLogonAccount* and *windowsLogonPassword* as I need to be authenticated as a specific user with my agent for my pipeline to work. These parameters do not seem to exist with the TeamServicesAgent extension according to the scarce information I can find online ([link](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops), is this extension documented anywhere else ?)

And I need to use a proper VM not a dev test lab one.

Is there any way to set the logon account with the TeamServicesAgent extension ?
If not, how could I solve this problem with a normal VM ?

PS: Other sources referencing the extension => [1](https://github.com/microsoft/azure-pipelines-agent/issues/1044) [2](https://stackoverflow.com/questions/55938450/unable-to-install-terraform-extensions-on-a-vm)

**Comment by anatolybolshakov** [comment]
Hi @adamency this seems to be relevant to  TeamServicesAgent extension, not the pipeline agent itself - I would suggest to open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.

**Comment by adamency** [comment]
I found the way to do it with the `config.cmd`, but I didn't find the configuration file you mention in the agent directory nor any mention of it in the documentation. Could you tell me its location ? Alternatively, is there a way to print the current config with `config.cmd` ? I didn't find one with the help.

**Comment by anatolybolshakov** [comment]
@adamency the recommended way is to use `config.cmd` (to re-configure you would probably need to remove existing configuration first by 'config.cmd remove'), but since the agent saves configuration settings in ".agent" file (this is a hidden file in the root agent directory) - I believe you can just change it directly also.
