### ISSUE TITLE
Is the documentation accessible on a website front-end ?

### ISSUE THREAD

**Issue by adamency** [microsoft/azure-pipelines-agent#3799]
I can't find any information about the documentation, except the `documentation` folder in the git repo. Are these markdown files designed to be read only on Github or is there a documentation website for the project ?

PS: I'm asking because Microsoft Docs information for azure pipelines agents is scarce and incomplete. These are the two only links from the official docs I could find => [MS Docs: Azure Pipelines Agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser), [MS Docs Module: Create Self-Hosted Azure Agent](https://docs.microsoft.com/en-us/learn/modules/host-build-agent)

**Comment by adamency** [comment]
Nevermind, some markdown files redirect to the MS Docs and I found what I was looking for. So I understand the docs are transitioning to MS Docs, but the corresponding code is not on this repo anymore. Where is it ?

**Comment by anatolybolshakov** [comment]
Hi @adamency there is a https://github.com/MicrosoftDocs/azure-devops-docs repo for Microsoft Docs - you can open a question there or contribute and create PR.
