### ISSUE TITLE
installdependencies.sh interactively confirms installation of debsums

### ISSUE THREAD

**Issue by joakimnordling** [microsoft/azure-pipelines-agent#3800]
The pull request https://github.com/microsoft/azure-pipelines-agent/pull/3712 added debsums installation in `installdependencies.sh` using `apt install debsums`. All other dependencies are installed with `apt install -y`. Since `debsums` is not installed with `-y` we can no longer as-is let our non-interactive deployment solution install all the dependencies by just running `installdependencies.sh`.

It would be really nice if it was possible to run the `installdependencies.sh` non-interactively. 

A simple option could be to just always install debsums. If you don't want to always install it, I'd appreciate 
if you could add some flag to `installdependencies.sh` that you could use to decide if debsums is to be installed or not so that it avoids interactive questions from apt (possibly `--debsums` and `--no-debsums`).

**Comment by anatolybolshakov** [comment]
Hi @joakimnordling thanks for reporting! Let us take a look

**Comment by AndreyIvanov42** [comment]
Fixed script released

**Comment by AndreyIvanov42** [comment]
Fixed script released
