### ISSUE TITLE
Authenticate against a git repository in self-hosted agent (and avoid extraHeader warnings)

### ISSUE THREAD

**Issue by ArthurBrum** [microsoft/azure-pipelines-agent#3807]
## Description
Hi there!

I'm unsure about how to authenticate and use git operations in my **self-hosted agent**.
I've read a few discussions like this one: https://github.com/microsoft/azure-pipelines-agent/issues/1601 which came to the solution of using extraHeaders... and I'm using it, but I still get:
`##[warning]Git config still contains extraheader keys. It may cause errors.  To remove the credential, execute "git config --unset-all key-name" from the repository root`

And checking [this part of the code](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/GitSourceProvider.cs#L665), it looks like it's not the recommended way of doing this.
So my question is, how can I do it correctly so I don't get warnings? 😕

**Comment by ArthurBrum** [comment]
Ok, this works when I'm using a single repository and checkout task will check self repository. The problem is that during my tasks I have to work with different repositories.. 
So, as I see, I have to either add all the repositories one by one on the checkout task or I can do as I'm currently doing already: adding the extraHeader manually.

**Comment by ArthurBrum** [comment]
I've been doing some tests and I noticed that I was getting this warning because I wasn't cleaning the extra headers before calling the Checkout task later in the script... 
Now I'm trying to setup my jobs to remove the headers after doing all the git operations

I think I'll try to implement some postJob execution... but I don't quite get how to do it.. only found examples in json files =/
https://stackoverflow.com/a/53065029/5154371

**Comment by parshOne** [comment]
I have a question, incase if i don't want to clear extraheaders after checkout as it may be needed in subsequent steps of my pipeline, so is there any way I can force the azure pipeline to not issue warning or check internally that git --config regexp *extrhaeader command which gives us this extraheaer warning.
