### ISSUE TITLE
Is it possible to see the windowsLogonAccount set for the Agent somewhere ?

### ISSUE THREAD

**Issue by adamency** [microsoft/azure-pipelines-agent#3813]
I use an unattended configuration for my azure pipelines agent, however while the configuration and registering of the agent doesn't fail, I see in my pipeline that the actual user account used in not the one I had set. For troubleshooting purposes, is it possible to see the windows logon account actually set somewhere within the agent root directory ?

**Comment by anatolybolshakov** [comment]
Hi @adamency yes, you can check this configuration parameter in the '.agent' file in the agent root directory (this is a hidden file usually).

**Comment by anatolybolshakov** [comment]
@adamency sorry, just re-checked it - `windowsLogonAccount/windowsLogonPassword` parameters are not being stored in this file. They are used once during agent configuration to set up relevant registry keys (see info [here](https://docs.microsoft.com/en-us/sysinternals/downloads/autologon#introduction)), so I don't think that it's possible.
