### ISSUE TITLE
How can I access variable group value which is linked key vault in serverless job?

### ISSUE THREAD

**Issue by jinweili1** [microsoft/azure-pipelines-agent#3818]
Now I want to use variable group value in a serverless job, but it doesn't work.
The variable group has been linked with an azure key vault service, just like this:
![image](https://user-images.githubusercontent.com/88314516/162935360-bb5beab9-7554-4545-a5b0-0807f4954210.png)
I try many ways to use those value, but it never works.
![image](https://user-images.githubusercontent.com/88314516/162935778-4564b3fa-de44-45dd-8dee-141afab5ec49.png)
You can see I've tried to use them directly or use env to pass value or use runtime style, all of them didn't work.
So, what should I do? I don't want to use pipeline variable because this yaml pipeline just a template pipeline that means there have many other pipelines will use this template, but I can't help them to set variable every time.

**Comment by AndreyIvanov42** [comment]
Hi @jinweili1,
You'd better ask a question on this [portal](https://developercommunity.visualstudio.com/search?space=21). This repository is for working on new functionality and fixing bugs in the agent codebase.
