### ISSUE TITLE
Self Hosted VMSS tooks hours to be reconfigured by ADO on recreation

### ISSUE THREAD

**Issue by zioalex** [microsoft/azure-pipelines-agent#3829]
## Agent Version and Platform
TeamServicesAgentLinux version: 1.22
Agent version: 2.202.1
OS of the machine running the agent? Linux

## Azure DevOps Type and Version
https://dev.azure.com/swissre

## What's not working?
The VMSS is configured to be controlled by Azure DevOps. When the VMSS needs to be recreated the extension can take till 2 hours to be reconfigured leaving the Pool without available agents.
It looks like there is a background job adding the extension to the VMSS that ran with some delays.

We cannot delete the recreate the pool in ADO because it would need to be re-added in all projects.

Ideally would be to have the background automation to run upon every VMSS recreation or being able to trigger the extension installation on request.

**Comment by Kozlov-Igor** [comment]
Hi @zioalex! This seems to be a scale set question - since this repo is mostly for the pipeline agent itself - could you please open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by zioalex** [comment]
Hi @Kozlov-Igor, this is not a VMSS question. When the VMSS is controlled by ADO, the ADO's backend is responsible of all the operations.
Even pushing the new extension installation.
In every case I will open also a thread there.

**Comment by zioalex** [comment]
New thread created here https://developercommunity.visualstudio.com/t/Self-Hosted-VMSS-tooks-hours-to-be-recon/10034758?space=21&q=ado+extension+delayed&entry=problem
