### ISSUE TITLE
Got Error "Unable to deploy to the target 'abc' as the target is offline"

### ISSUE THREAD

**Issue by SudeshSharma** [microsoft/azure-pipelines-agent#3835]
Hey Guys,

Got error during deployment of the pipeline on azure VM(server 2016)

“Unable to deploy to the target ‘abc’ as the target is offline.”

I have restarted the VSTS agent on VM but got again same error.

whenever I tried to install a new agent got the below error.

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
—> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host…

I have updated Azure DevOps Services to require TLS 1.2 (Updated).

But not able to install and run the old deployment pool.

Thanks

**Comment by Kozlov-Igor** [comment]
Got Error "Unable to deploy to the target 'abc' as the target is offline" [#3835](https://git.akvelon.net:9443/git.anatoly.bolshakov/build-tasks-team-board/-/issues/263)

**Comment by anatolybolshakov** [comment]
Hi @SudeshSharma please see [similar ticket ](https://developercommunity.visualstudio.com/t/unable-to-deploy-to-the-target-the-target-is-offli/697018) for reference.
Could you please share the agent logs to take a look?

**Comment by SudeshSharma** [comment]
@anatolybolshakov 
[Agent_20220515-154612-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/8697347/Agent_20220515-154612-utc.log)

**Comment by MisinformedDNA** [comment]
In my case, the services hadn't started or had stopped on the VM.
