### ISSUE TITLE
Errors when starting up Docker image of the agent.

### ISSUE THREAD

**Issue by nlasok1** [microsoft/azure-pipelines-agent#3841]
## Having issue with software on Hosted Agent?
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation).  <- There is no such repo, so submitting it here.

## Agent Version and Platform
agent v 2.202.1

OS of the machine running the agent? OSX/Windows/Linux/...
Linux

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
Errors when starting up Docker image of the agent.

## Agent and Worker's Diagnostic Logs
Hundreds of error like this
`{"TimeStamp":"2022-05-20T14:33:06.1785415+00:00","Log":"./externals/node/lib/node_modules/npm/lib: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1786027+00:00","Log":"./externals/node/lib/node_modules/npm: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1786093+00:00","Log":"./externals/node/lib/node_modules: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1786296+00:00","Log":"./externals/node/lib: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1788058+00:00","Log":"./externals/node/bin: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1788222+00:00","Log":"./externals/node: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1788412+00:00","Log":"./externals/node10/bin: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1789063+00:00","Log":"./externals/node10: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1789107+00:00","Log":"./externals: Cannot change mode to rwxr-xr-x: Operation not permitted"}
{"TimeStamp":"2022-05-20T14:33:06.1789355+00:00","Log":"Exiting with failure status due to previous errors"}`

**Comment by antsok** [comment]
Agent built according to this [ms docs article](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#create-and-build-the-dockerfile-1). Building with ACR.

Errors happen in start.sh when unpacking tar file that this script obtains from https://vstsagentpackage.azureedge.net/agent/

**Comment by nlasok1** [comment]
Update:

As a workaround, I've built an agent in a different way than provided in previous mentioned MS docs article, by placing the agent tar download into the Dockerfile itself and it starts fine now. You can find the source code here [https://github.com/antsok/ado-aca/tree/agent-2.202.1/src/agent](https://github.com/antsok/ado-aca/tree/agent-2.202.1/src/agent)
