### ISSUE TITLE
Failed to start the custom Linux container in self hosted Windows Server 2019 due to volume mounting on .taskkey

### ISSUE THREAD

**Issue by NeroJz** [microsoft/azure-pipelines-agent#3846]
## Docker Issue
The agent could not start the docker container (custom Linux Image) due to volume mounting.

## Issue on Starting the Docker in Self Hosted Agent
The agent could not start the docker container (custom Linux Image) on Window Self Hosted machine (Windows Server 2019). It could not mount the \\_work\\.taskkey.

## Agent Version and Platform
Version agent: 2.204.0
OS Machine: Windows Server 2019

## Azure DevOps Type and Version
On-premises Azure DevOps Server

## What's not working?
The agent could not mount the volume and display the following errors:
2022-05-23T03:52:23.9854360Z ##[command]C:\Program Files\Docker\docker.EXE create --name 1113028e2e034381be6cdc4e20ec1403_***nodejs14cfcli_d90313 --label 41e4ae --network vsts_network_7bc167515b61426f98752c50ee13c5fc  -v "C:\agent\\_work\1":"/__w/1" -v "C:\agent\\_work\_temp":"/__w/_temp" -v "C:\agent\\_work\_tasks":"/__w/_tasks" -v "C:\agent\\_work\_tool":"/__t" -v "C:\agent\externals":"/__a/externals":ro -v "C:\agent\\_work\.taskkey":"/__w/.taskkey" ***/nodejs14:cfcli "node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
**2022-05-23T03:52:24.1555649Z Error response from daemon: invalid volume specification: 'C:\agent\\_work\\.taskkey:/__w/.taskkey': invalid mount config for type "bind": source path must be a directory**

**Comment by DenisRumyantsev** [comment]
Hi @NeroJz, do you have any updates? Could you use my email instead? — v-denisr@microsoft.com

**Comment by NeroJz** [comment]
Hi @KonstantinTyukalov @DenisRumyantsev, sorry for late reply. I had uninstalled the docker and run the pipeline jobs within the self hosted machine. Let me re-install the docker engine on the machine and try again. Will share these details to you all after the installation.

> Hi @NeroJz Could you please provide more details:
> 
> * [Agent diagnostic logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#agent-diagnostic-logs)
> * [Worker diagnostic logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#worker-diagnostic-logs)
> * [Debug logs of the task execution](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)
> 
> Thank you!

**Comment by DenisRumyantsev** [comment]
Hi @NeroJz, any updates? Did you manage to reinstall the Docker engine and get these details?

**Comment by NeroJz** [comment]
Hi @DenisRumyantsev, sorry for late reply. Can we revisit this issue later? Recently, we have other issues on our project and we are working on the deadline for these issues.

**Comment by DenisRumyantsev** [comment]
@NeroJz, in that case, let me close this issue for now. Please reopen it again when you get back to this issue.
