### ISSUE TITLE
Hosted Agent Image Repository hyperlink in issue template is broken

### ISSUE THREAD

**Issue by cookbr** [microsoft/azure-pipelines-agent#3854]
Looks like the _Hosted Agent Image Repository_ hyperlink under the _Having issue with software on Hosted Agent?_ section of the issue template is broken ...

>## Having issue with software on Hosted Agent?
>Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.

**Comment by KonstantinTyukalov** [comment]
Hi @cookbr thanks for the information provided!

We've prepared a PR with a fix for this problem, please take a look: https://github.com/microsoft/azure-pipelines-agent/pull/3856

**Comment by KonstantinTyukalov** [comment]
The related changes has been merged. Let me close this issue then
