### ISSUE TITLE
I am using `--addvirtualmachineresourcetags --virtualmachineresourcetags tag1=val1,tag2=val2` kind of syntax, and I also do not see the capabiliities added to the agent once it's in the pool.  This is on Ubuntu 22.04 using agent 2.204.0.

### ISSUE THREAD

**Issue by son3ofSatan** [microsoft/azure-pipelines-agent#3858]
I am using `--addvirtualmachineresourcetags --virtualmachineresourcetags tag1=val1,tag2=val2` kind of syntax, and I also do not see the capabiliities added to the agent once it's in the pool.  This is on Ubuntu 22.04 using agent 2.204.0.

_Originally posted by @jbreadner in https://github.com/microsoft/azure-pipelines-agent/issues/3086#issuecomment-1144999527_

**Comment by max-zaytsev** [comment]
@son3ofSatan Thanks for reporting! We are working on more prioritized issues now but will get back to this one soon

**Comment by tejas-nagchandi** [comment]
I am able to create tags using ```--addvirtualmachineresourcetags --virtualmachineresourcetags tag1,tag2``` syntax.

I am not sure if tags here are key-value pairs or just tags, but with "tag1,tag2" comma separated keywords, I am able to achieve the requirement.

**Comment by tejas-nagchandi** [comment]
But, the point raised in #3086 is still valid that ```--addvirtualmachineresourcetags --virtualmachineresourcetags``` arguments are missing from the help documentation.
```
./config.sh --help |grep -i addvirtualmachineresourcetags |wc -l
0
```

@max-zaytsev : Help documentation should be updated for these arguments.
