### ISSUE TITLE
Feature request: Dynamic Capabilities checked before each run

### ISSUE THREAD

**Issue by caspChristian** [microsoft/azure-pipelines-agent#3862]
The only supported way to provide capabilities is to add ".capabilities" file(?)

We need to have a capabilites check that runs before a job is assigned to an agent.
This could be a powershell script that runs when a specific capability is requested.
It could be that a service needs to be running to be able to run a job, but we can't control the service, so before agent is determined we want said powershellscript to run to get this capability value.

Specific examples is to check that docker is running, or that if a local database exists. local user is logged in and so forth.
Values that is runtime and can change several times after startup of the agent.

**Comment by vmapetr** [comment]
@caspChristian Thanks for reporting! We are working on more prioritized issues now but will get back to this one soon

**Comment by NiKiZe** [comment]
These kind of bots is just rude, remove and start maintain this repo properly instead!

**Comment by caspChristian** [comment]
WTF!? These kind of bots is just rude, remove and start maintain this repo properly instead!
Should it really be up to reporters to ping issues to "keep them alive" ??? If that what is needed then I might need to create a bot that does just that to counter.

Now please tell me how the original reported issue was dealt with if you are closing this issue, if not make sure to reopen!
