### ISSUE TITLE
Toolchain utility 'arm-linux-androideabi-as.exe' for target Arm was not found.

### ISSUE THREAD

**Issue by WilliamWatterson86** [microsoft/azure-pipelines-agent#3863]
## Agent Version and Platform
Version of your agent? 2.204.0

OS of the machine running the agent? OSX/Windows/Linux/...
Windows 

## What's not working?
Getting this error on my Xamarin Android pipelines today.  The same pipelines were working yesterday afternoon. Has something been updated?

[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1954,3): Error : error XA5105: Toolchain utility 'arm-linux-androideabi-as.exe' for target Arm was not found. Tried in path: "C:\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows"
   at Xamarin.Android.Tasks.NdkUtil.GetNdkTool(String androidNdkPath, AndroidTargetArch arch, String tool, Int32 apiLevel)
   at Xamarin.Android.Tasks.NdkUtil.GetNdkToolPrefix(String androidNdkPath, AndroidTargetArch arch, Int32 apiLevel)
   at Xamarin.Android.Tasks.Aot.<GetAotConfigs>d__80.MoveNext()
   at Microsoft.Android.Build.Tasks.AsyncTaskExtensions.WhenAllWithLock[TSource](AsyncTask asyncTask, IEnumerable`1 source, Action`2 body) in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AsyncTaskExtensions.cs:line 38
   at Xamarin.Android.Tasks.Aot.<RunTaskAsync>d__79.MoveNext()

**Comment by vmapetr** [comment]
Hi @WilliamWatterson86! Could you please provide some additional details about your pipeline - what type of agent do you use (hosted/self-hosted), an example of your YAML template, or some repro steps?

**Comment by WilliamWatterson86** [comment]
Hi @vmapetr - thanks for getting back to me.

The agent I was trying to use was the windows-2019 from the hosted Azure Pipelines pool.

I have changed the agent to Windows-latest and it seems to work ok for me.  Maybe something has changed on the windows-2019 one?

**Comment by RemcoDEV** [comment]
We experience this issue too. Any ETA when this will be fixed?

**Comment by deyupopp** [comment]
In case anyone still has this issue, this happens if you use NDK 23 or higher, with a Xamarin.Android version older than 12.2. We solved our issue by updating Xamarin.Android.

**Comment by JTOne123** [comment]
@deyupopp  what do you mean by this? Do we need to update the target framework to 12 or 12-S, 13? How can I achieve this?

**Comment by deyupopp** [comment]
It's not the target version of Android that matters here, but the version of Xamarin.Android that you use. This really depends on how you configured CI to use it. We have a script that installs a specific version.

**Comment by deyupopp** [comment]
On your local machine, it will come along by updating Visual Studio. If you want to install it without visual studio, you can find it here, under downloads:
https://github.com/xamarin/xamarin-android
