### ISSUE TITLE
making containerized agents restart after every pipeline run and not after a job

### ISSUE THREAD

**Issue by Abdulthetechguy** [microsoft/azure-pipelines-agent#3866]
Using the --once flag for self hosted build agents restarts the container after every job which could be time wasting in instances where you have multiple jobs in a pipeline. How can the container be made to restart after each pipeline and not Job. I am running the build agents on AKS clusters as statefulsets

**Comment by vmapetr** [comment]
Hi @Abdulthetechguy! As far as I know at the moment there is no ability to restart the container specifically after the pipeline completion.
