### ISSUE TITLE
Azure DevOps self-hosted agent can't install Windows RT application correctly

### ISSUE THREAD

**Issue by andy-mishechkin** [microsoft/azure-pipelines-agent#3872]
## Having issue with YAML?
No

## Having issue with Tasks?
Indirectly. Task: PowerShell@2, but it works

## Having issue with software on Hosted Agent?
No

## Having generic issue with Azure-Pipelines/VSTS/TFS?
No

## Agent Version and Platform
2.195.0

OS of the machine running the agent? 
Windows 2019

If dev.azure.com, what is your organization name?
https://fairetaildev.visualstudio.com

## What's not working?
Hello, guys!
We have a self-hosted Azure DevOps agent, which installed locally on machine and works as Windows service  from admin account. I need to deploy Windows RT application to this machine using this agent, which should be installed for other user account. I have created the PowerShell script for  this:

`param(
      [Parameter()] [string] $PackageDirectory = "C:\WindowsRTAppMsix",
      [Parameter()] [string] $otherUser = '.\User',
      [Parameter()] [string] $otherUserPassword                         #Should be specified in script parameters
  )
  
  Push-Location $PSScriptRoot
  $securePassword = ConvertTo-SecureString $otherUserPassword -AsPlainText -Force
  $credential = New-Object System.Management.Automation.PSCredential $otherUser, $securePassword
  
  Write-Host "Installing the Windows RT application"
  $MsixPath = Join-Path -Path $PackageDirectory -ChildPath "my_package.msix"
  $MsixCommand = "&{ Import-Module AppX; Add-AppxPackage $MsixPath }"
  Start-Process powershell.exe -Credential $credential -ArgumentList $MsixCommand -Wait`

When I start this script locally on machine in PowerShell session, which runs from admin account (the same account as for AzDo Agent Service) - all works as expected, and "otherUser" gets Windows RT application icon in your start menu.
But when I try to run this script in the PowerShell@2 task in AzDo release - I've got not any errors in log, and release finished successfully, but "otherUser" has no Windows RT application installed (I think, you can use any Windows RT application for reproducing).
Also, if I use in script
` Start-Process powershell.exe -ArgumentList $MsixCommand -Wait ` instead of `Start-Process powershell.exe -Credential $credential -ArgumentList $MsixCommand -Wait ` - Windows RT application will successfully installed for admin account.
Could you explain, please, how to install Windows RT application correctly with custom credentials through Azure DevOps.
Thank You!

**Comment by kirill-ivlev** [comment]
Hi @andy-mishechkin,
Sorry for leave you request without any response,
could you please share pipeline or powershell task logs and confirm that issue is still exist for you?

**Comment by kirill-ivlev** [comment]
@andy-mishechkin unfortunately, we didn't receive any response from you. If the problem is still actual for you, please feel free to re-open this item
