### ISSUE TITLE
Error NU1102 Unable to find package vss-api-netcore with version (>= 0.5.179-private)

### ISSUE THREAD

**Issue by icnocop** [microsoft/azure-pipelines-agent#3877]
Hi.

Thank you for azure-pipelines-agent.

When trying to build the latest code on the master branch, I get the following error:
```
Error	NU1102	Unable to find package vss-api-netcore with version (>= 0.5.179-private)
  - Found 55 version(s) in NuGet VSS Private MyGet Feed [ Nearest version: 0.5.129-private ]
  - Found 0 version(s) in nuget.org
  - Found 0 version(s) in Azure DevOps Test Result Parser MyGet Feed	Agent.PluginHost
```

I have the following NuGet Package Manager Sources configured in Visual Studio:
1. Name: nuget.org
Source: https://api.nuget.org/v3/index.json
2. Name: Azure DevOps Test Result Parser MyGet Feed
Source: https://www.myget.org/F/testresultparser/api/v3/index.json
3. Name: NuGet VSS Private MyGet Feed
Source: https://www.myget.org/F/nugetvssprivate/api/v3/index.json

I didn't expect to have to manually enter two additional NuGet package sources (in Visual Studio).
I expected the vss-api-netcore 0.5.179-private NuGet package to be published and publicly accessible so I can build the latest code.

Thank you.

Related: #2167

**Comment by SvetlanaMaliugina** [comment]
Hi @icnocop, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by Thefrank** [comment]
not actually stale for me: "restsdk" is the only feed in all of the `NuGet.Config` files used and
- does not like seeing current SDKs. 3.1 and 5 are EOL/EOS.
- feeds like Nuget.org's works but does not contain `vss-api-netcore`

**Comment by drolevar** [comment]
Anyone? Having the same issue.

**Comment by MichaelDenwood** [comment]
Yes, we are having the same issue
