### ISSUE TITLE
BatchScript@1 task may create additional environment variables when modifyEnvironment is set to true

### ISSUE THREAD

**Issue by rfbeiboer** [microsoft/azure-pipelines-agent#3886]
**Situation**
In certain conditions, running the BatchScript@1 task with modifyEnvironment set to true may lead to additional environment variables to be created that were not there before the task was run, and are also not created by the batch script itself. This occurs when an environment variable exists with a value containing multiple lines and the second (or later) line containing an equal character (=). The line containing the equal character is treated as an environment variable itself and will be added to the environment. The part before the equal character becomes the name of the variable, the part after the equal character becomes the value.

**Example**
- An environment variable exists with 2 lines of text. Line 2 contains `text=another text`
- Run a BatchScript@1 task with modifyEnvironment set to true
- Notice that after running the task, an additional environment variable with the name `text`, having value `another text` exists

**Responsible source code**
_File_: `src/Agent.Workers/Handlers/ProcessHandler.cs`
_Method_: `OnOutputDataReceived`
This method parses the output of the SET command, listed as `key=value` lines. The caveat is that when a variable with a multi-line value is listed, the EOL characters produce separate lines that are parsed individually by the method. This leads to misinterpreting the output of the set command, which causes the additional environment variables to be created, when they contain the equal character

**Comment by AndreyIvanov42** [comment]
Thank you, we will look into this issue
