### ISSUE TITLE
On Prem OSX Agent Update

### ISSUE THREAD

**Issue by dmccolloughOneGas** [microsoft/azure-pipelines-agent#3889]
## Agent Version and Platform
Version of your agent? 2.205.0

OS of the machine running the agent? OSX, macOS Monterey 12.4

## Azure DevOps Type and Version
on-premises TFS/Azure DevOps Server

If on-premises, which release? Azure DevOPS server 2020 Update 1.1

## What's not working?
We have 3 OSx agents running on a Mac Mini. All are running as a service.
When I got to the Agent Pool and click on the button to update all agents, Click on the update button to the confirm update.

Wait some time, check back to see what the version of the build agent is and it has NOT updated.

We were on 2.202.1 and we tried to update to 2.205.0 and it never shows the agent's being on the new version.

Is this not an automated update on Mac OS ?
Only way I could get it updated was to uninstall the service, delete the agent and then re-install and add back all of it's capabilities.

**Comment by AndreyIvanov42** [comment]
Hi, thanks for reporting.
We will take a look at this issue

**Comment by sergey-koryshev** [comment]
I couldn't reproduce the issue on Macbook M1 (Monterey 12.6). 

@dmccolloughOneGas, could you please attach logs of agent from folder `_diag` when agent update fails if you still experiences the issue?

**Comment by dmccolloughOneGas** [comment]
@sergey-koryshev I just updated the agents on our Mac build server. Must have been something I was doing wrong the first time. It updated today without an issue.

Please close the ticket.

Thanks for the help.
