### ISSUE TITLE
configure self-hosted agent on Jetson NX (ARM64) fails 

### ISSUE THREAD

**Issue by sassonyaniv** [microsoft/azure-pipelines-agent#3896]
hey ,

i am trying to configure my self host agent running on Jetson NX (arm64) with ubuntu 18.04 .
i get a permissions error , but neither a sudo chmod 777 or running as root helped.

i am using an agent version 2.204.0 for arm64.

also, running ./bin/installdependencies.sh didn't resolved the libcurl3 not found issue.

thanks for your help.
yaniv

nvidia@nvidia-desktop:/myagent$ . config.sh 
./bin/System.Net.Http.Native.so: /usr/lib/aarch64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./bin/System.Net.Http.Native.so)
Warning: on some platforms, libcurl3 is required.
It was not found.
Execute ./bin/installdependencies.sh to install missing dependencies.
Error reported in diagnostic logs. Please examine the log for more details.
    - /home/nvidia/myagent/_diag/Agent_20220704-082922-utc.log
An error occurred: Permission to read the directory contents is required for '/home/nvidia/myagent' and each directory up the hierarchy. Access to the path '/' is denied.
nvidia@nvidia-desktop:~/myagent$

**Comment by DmitriiBobreshev** [comment]
Hello @sassonyaniv, thank you for your question, make sure that you have at least executed access to all directories in your case it will be /, /home, /home/nvidia also /home/nvidia/myagent should have full access for user.
Also, you could try apt-get install libcurl3 [manually](https://www.howtoinstall.me/ubuntu/18-04/libcurl3/), and to be sure maybe it's related to this one - https://askubuntu.com/questions/1087576/version-curl-openssl-3-not-found?
Do you have any other libssl versions installed on your environment?

**Comment by sassonyaniv** [comment]
hey,

you were right , my os permissions were very weird, had to reset them.
i could install libcurl3 but it has some conflict with other packages (ros-melodic, i had to reinstall it), now everything is working 
   
thank you very much
