### ISSUE TITLE
vso[artifact.upload] performance is ridiculously slow

### ISSUE THREAD

**Issue by KarstenB** [microsoft/azure-pipelines-agent#3915]
## Agent Version and Platform
Version of your agent? 2.204

OS of the machine running the agent? Linux Debian Bullseye

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

If dev.azure.com, what is your organization name? 
https://dev.azure.com/siemens-energy-siprotec

## What's not working?
We are building our software and want to upload artifacts. The name and amount of artifacts is not easily known ahead of time, so we are using the `##vso[artifact.upload containerfolder=testresult;artifactname=uploadedresult]c:\testresult.trx` command, pointing to a directory, which is working exactly as we expect it. However the performance is simply unacceptable.

The files that are generated/uploaded are small, but there are lots of them, like 19.000 files which are 20mb in total (450kb compressed). One upload took 30minutes! We then went ahead and compressed all files to a 7z before upload and the total execution time, including upload was 5 seconds. 

5 seconds sounds acceptable, but 30 minutes is beyond ridiculously.

**Comment by KarstenB** [comment]
When I manually use `PublishPipelineArtifact@1` it only takes 18s, which I would consider fair given that the data is uncompressed.

**Comment by jrummell** [comment]
I'm seeing this same issue on self-hosted agents. Publishing with `PublishPipelineArtifact@1` sometimes takes 20+ minutes for a couple 5 MB zip files. Other times it takes 30 seconds. It just started for me this week.
