### ISSUE TITLE
Unable to run .NET MAUI Mac catalyst built with MS hosted macOS agent x64 on MacBook arm64 (m1) chip. 

### ISSUE THREAD

**Issue by mohammad-yousuf** [microsoft/azure-pipelines-agent#3916]
**Issue Description:** 

My Azure DevOps pipeline running on MS hosted macOS agent is unable to run .pkg app after installation on macOS arm64, whereas it runs fine on intel processor mac.

**Comment by DenisRumyantsev** [comment]
Hi, @mohammad-yousuf, currently the agent is not supported for `macOS M1` as the agent still uses `.NET 3.1`.
However, we are going to migrate the agent to `.NET 6` in the nearest future, and this issue will be resolved after migration.

**Comment by mohammad-yousuf** [comment]
Hi @DenisRumyantsev, thanks for getting back, do we have a timeframe for this?

**Comment by DenisRumyantsev** [comment]
@mohammad-yousuf, we do not have the exact date, but we have created a public ticket about the `.NET 6` migration — [link](https://github.com/microsoft/azure-pipelines-agent/issues/3922).

So, feel free to track the progress of the migration in the public ticket, and let me close this issue.
