### ISSUE TITLE
Migration to `.NET 6` (`OpenSSL 3.0` and `M1` architecture support)

### ISSUE THREAD

**Issue by alexander-smolyakov** [microsoft/azure-pipelines-agent#3922]
## Description

At the moment Azure Pipelines Agent targets the `.NET Core` v.`3.1`. We need to migrate it to `.NET 6` to provide support for:
- OpenSSL 3.0
- Native support for `M1` architecture

## Current progress

- [x] Update codebase to target `.Net 6`
- [x] Update release pipeline to provide a native build for the `M1` platform 
- [x] Update CI checks to test new platforms (In progress)
- [x] Verify and test the agent update process for the self-hosted pipeline agents
- [ ] Test the Azure Pipelines Agent build on the main target platforms (In progress)

### Testing 

| *OS (Reduction + Version)*   | *Architecture* | *Testing Status* |
| ---------------------------- | -------------- | ---------------- |
| Windows 7 SP1 ESU            | x64            | Completed        |
| Windows 8.1                  | x64            | Completed        |
| Windows 10                   | x64            | Completed        |
| Windows 10                   | x86            | Completed        |
| Windows 11                   | x64            | Completed        |
| Windows Server 2022 Standard | x64            | Completed        |
| Windows Server 2019 Standard | x64            | Completed        |
| Windows Server 2016          | x64            | Completed        |
| Windows Server 2012          | x64            | Completed        |
| CentOS 8                     | x64            | Completed        |
| Debian 10                    | x64            | Completed        |
| Fedora 33                    | x64            | Completed        |
| Linux Mint 17                | x64            | Completed              |
| RHEL 9                       | x64            | Completed        |
| Suse Enterprise 12.3         | x64            |Completed              |
| Ubuntu 18.04                 | x64            | Completed        |
| Ubuntu 20.04                 | x64            | Completed        |
| Ubuntu 22.04                 | x64            | Completed        |
| Ubuntu 22.04                 | arm32          |      Completed                              |
| Ubuntu 22.04                 | arm64          |   Completed                       |
| Debian 10                    | arm32          |       Completed                   |
| MacOS 12                     | x64            |          Completed                          |
| MacOS 12                     | arm64          |        Completed                  |

## Breaking changes
- Dropped support for RHEL 6 - [Related announcement](https://docs.microsoft.com/en-us/azure/devops/release-notes/2022/pipelines/sprint-199-update#upcoming-upgrade-to-net-6--red-hat-6-deprecation)
- The `AZP_AGENT_USE_LEGACY_HTTP` agent knob will be deprecated - [Related announcement](https://github.com/microsoft/azure-pipelines-agent#announcement----azp_agent_use_legacy_http-agent-knob-future-deprecation)

## Questions
TBD

## Mitigation ways
TBD

**Comment by alexisatkinson** [comment]
Given that .NET Core is EOL on 13th December 2022 and the .NET 6 move appears to be a pre-requisite for Ubuntu 22.04 support, is there a view on the likely ETA for .NET 6 support to drop?

**Comment by sanderdam** [comment]
Just out of curiosity...
The AgentService project targets .Net Framework 4.5.
Are there plans for also migrating this to .Net6?

**Comment by sphanley** [comment]
We're now past the End of Support date for .Net Core 3.1. Is there any timeline available yet for when the .Net 6 migration is expected to be complete and released to users?

**Comment by MichelZ** [comment]
Another month passed by. What's the status of this? @alexander-smolyakov

**Comment by alexander-smolyakov** [comment]
Hey @MichelZ, I'm no longer working on this project. Probably @kirill-ivlev @LiliaSabitova @max-zaytsev could share the current status of this migration.

**Comment by alexisatkinson** [comment]
Not sure why it hasn't been posted here previously, but worth reading:

[https://devblogs.microsoft.com/devops/upgrade-of-net-agent-for-azure-pipelines/](https://devblogs.microsoft.com/devops/upgrade-of-net-agent-for-azure-pipelines/)

The current (as of writing) pre-release .NET build agent version is at https://github.com/microsoft/azure-pipelines-agent/releases (see the v3.x releases further down the page)

**Comment by sphanley** [comment]
Huge thanks for calling that out, @alexisatkinson. It's really frustrating to know that my team could have begun testing the MacOS arm64 runner months ago if Microsoft had just linked that announcement here.

**Comment by kirill-ivlev** [comment]
@sphanley sorry for the lack of updates in this ticket, in general, we have completed all required testing and started to provide public releases, you can find it on our [Releases page](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.214.0).
We will be appreciated any feedback regarding the new agent.

We will update this ticket once the agent will roll out in the main distribution channel.

**Comment by hheexx** [comment]
@kirill-ivlev It would be nice to have a way to update without reinstalling. 
You could add update command to v2 cmd or something in web admin for agent pools.
Something like prerelase update channel.

**Comment by amrmesbah** [comment]
@kirill-ivlev is there any estimation on when this will be rolled out to the main channel?

**Comment by Muhammed9991** [comment]
Looks like everything is completed. Do we have a timeline for when this will merged?

**Comment by lietu** [comment]
So, if I download the latest pre-release version `3.217.0`, I still have to do these manual patches to get it to install and run on Ubuntu 22.04:

```bash
sed -i "s@liblttng-ust0@liblttng-ust1@g" bin/installdependencies.sh
sed -i "s@libssl1\.1@libssl3@g" bin/installdependencies.sh
sed -i "s@libicu67@libicu70@g" bin/installdependencies.sh
```

Hope these get actually incorporated into the project, but for anyone else this might be all you really need right now to get it running on the almost a year old Ubuntu LTS.

**Comment by kuqin12** [comment]
Is there any plan to add the support for Windows ARM64? Or the Windows x64 is considered the coverage for ARM64 arch?

**Comment by sphanley** [comment]
I see that the last two 3.x agent releases are no longer marked "prerelease". Does this mean it's considered to be stable and official at this point? Has there been any communication on the topic?

**Comment by hheexx** [comment]
It has been pushed to updates, you can update to 3.x from web UI

**Comment by kirill-ivlev** [comment]
@sphanley Yes, the 3.x agent is in a stable and official release.

Some useful information also might be found in [this blog](https://devblogs.microsoft.com/devops/upgrade-of-net-agent-for-azure-pipelines/) post.

Closing this ticket since no future action is required.
