### ISSUE TITLE
How to get a ARM64 based agent in Azure pipeline

### ISSUE THREAD

**Issue by blueww** [microsoft/azure-pipelines-agent#3935]
## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...
OS of the machine running the agent? OSX/Windows/Linux/...

Platform  of your agent: ARM64

I see ARM64 based agent is support in https://github.com/microsoft/azure-pipelines-agent/blob/614efcb60ce620196ee83d417d37cb7a452c97d8/.azure-pipelines/pipeline.yml#L140
We need ARM64 machine for our pipeline, so I try to use the above VMImage but failed. 
How to use ARM64 VMImage in Azure Pipeline?

1. I use following image in my pipeline
```
        pool:
          name: 1ES_ARM_Agent_Pool
          vmImage: Ubuntu_2004_ARM64
```

Then The pipeline failed with : 

> There was a resource authorization issue: "The pipeline is not valid. Could not find a pool with name 1ES_ARM_Agent_Pool. The pool does not exist or has not been authorized for use. For authorization details, refer to [https://aka.ms/yamlauthz."](https://aka.ms/yamlauthz.%22)

2. Then I remove `name: 1ES_ARM_Agent_Pool`, and see the pipeline failed with 

> ##[warning]An image label with the label Ubuntu_2004_ARM64 does not exist.

**Comment by LiliaSabitova** [comment]
HI @blueww!
You can use any of the [available](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software) virtual machines in Microsoft-hosted pools.
**1ES_ARM_Agent_Pool** - this is an internal pool, so that's why it's not available.

If you need ARM64 machine to run jobs on - you should set up your own Virtual Machine with this architecture.

**Comment by blueww** [comment]
@LiliaSabitova 

Thanks for the reply!

When will Azure pipeline has available machine on ARM64?

**Comment by LiliaSabitova** [comment]
@blueww 

Currently ARM64 machines are [in preview](https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/).
If you have your own machine on ARM64, you can run agent on it.

Also you can address your question to the [team who is responsible for the VM images](https://github.com/actions/runner-images).

**Comment by blueww** [comment]
@LiliaSabitova 

We don't have a physical ARM64 machine in hand, in this case, is there anyway to validate PR with ARM64 platform by azure pipeline ?

Besides that, if we plan to buy an ARM64 machine (it will take time), do you any recommendation for the module of the machine to buy？ And any guild to add the ARM64 machine to azure pipeline?

**Comment by Jonathon52306** [comment]
> 

You can use oracle cloud. Their ARM64 server is really cheap

**Comment by blueww** [comment]
@Jonathon52306 

I find a guild for ARM64 Azure VM onboard. https://microsoft.sharepoint.com/teams/SantaClara/SitePages/Onboarding.aspx

As Azure VM already support ARM64 by following this guild, would you please add the ARM64 support to Azure piepline?

**Comment by BriceLag** [comment]
Hi @LiliaSabitova ,
Have you got any news about that ticket ?
On our side, we have created an ARM64 custom image, create a VMSS, based on our custom image, add it into Azure Devops, but when we want to use it we have that error message: 
VM has reported a failure when processing extension 'Microsoft.Azure.DevOps.Pipelines.Agent'. Error message: "The Extension failed to execute: The current CPU architecture is not supported. Deployment agent requires x64 architecture." More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot.
Thank you ! :-)

**Comment by LiliaSabitova** [comment]
Hi @BriceLag, could you please advise which OS and version of agent do you use? Did you tried to use the latest version of agent?  Could you please try it and provide the logs in case if issue still reproduces.
To get these logs, could you run the pipeline with System.Debug and agent.diagnostic pipeline variables enabled (set to true)?

variables:
System.Debug: true
agent.diagnostic: true

To prevent security issues, you can send these logs to these emails:

[v-lisabitova@microsoft.com](mailto:v-lisabitova@microsoft.com)
[akvelon-build-tasks@microsoft.com](mailto:akvelon-build-tasks@microsoft.com)
["Review logs" documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs)

**Comment by ida-greuelr** [comment]
We are facing the same problem when using a private agent pool based on the new ARM64  machines offered by Azure, i.e. Instance name: *D8plds v5*.

We use the same configuration, like we use for our AMD64 based pools in relation to scaling configurations and installed OS packages. When starting a pipeline in azure devops and set the pool to our ARM64 based agent pool, the pipeline auto-scales an instance correctly but fails with the following message:

![arm64_provisioning_fail](https://user-images.githubusercontent.com/41747375/196266457-290830ac-5fe1-46fb-bc5c-54bba7e16cf2.png)

Did we miss any extra steps related to azure devops? We are switching the pool during pipeline runtime for a specific stage, like we did with our other pool definitions.

**Comment by LiliaSabitova** [comment]
Spoke with VMSS team and got the answer that ARM64 architecture is not supported with elastic pools.
If you want to use ARM64 you will have to use self-hosted pools.
[Article about VMSS agents.](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#supported-operating-systems)

**Comment by BriceLag** [comment]
I keep hope because of that annoncement: 
https://azure.microsoft.com/fr-fr/updates/generally-available-arm64-support-in-aks/
So, the VMSS should support soon ARM64 :-)

**Comment by ida-greuelr** [comment]
> Spoke with VMSS team and got the answer that ARM64 architecture is not supported with elastic pools. If you want to use ARM64 you will have to use self-hosted pools. [Article about VMSS agents.](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#supported-operating-systems)

Alright, good to know. Thanks for the answer :)

**Comment by mauve** [comment]
ARM64 machines and ARM64 ScaleSets are no longer in Preview, can we reopen this bug please?

**Comment by mauve** [comment]
@LiliaSabitova ping

**Comment by lareeth** [comment]
I have raised an issue in the vsts-azurevm-extension repo, but I'm getting no response either.

https://github.com/microsoft/vsts-azurevm-extension/issues/230

**Comment by lareeth** [comment]
@LiliaSabitova could you assist on getting some eyes on https://github.com/microsoft/vsts-azurevm-extension/issues/230

**Comment by denravonska** [comment]
Any news on this? This was closed as completed almost two years ago yet there's no way, at least according to the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software), to select an ARM agent.
