### ISSUE TITLE
Connecting to the server' error for v.2.181.2>

### ISSUE THREAD

**Issue by sam-crisp** [microsoft/azure-pipelines-agent#3948]
Running Ubuntu 20.04 and could never get service to go past the 'Connecting to the server' error to Azure DevOps Server. Thought it might be SSL related but no logs to indicate. I installed 7 different versions of the agent including the prerelease 2.209.0 to see if anything could help. No dice; same connecting standoff. 

[Took the suggestion here](https://github.com/microsoft/azure-pipelines-agent/issues/3176) and installed v2.165.0 and finally got it to connect! But I sent over the first job and the agent updates to 2.181.2 (even though the agent pool is set to NOT auto update). 

Once it updates, I'm back to the 'Connection to the server' error. 

Very frustrating; I have no way to build on a linux os. 

```xxxx@xxxx-adp02:~/vsts-2.165.0$ sudo ./svc.sh status

/etc/systemd/system/vsts.agent.acustgint\x2dtfs01.LINUX\x2dBUILD\x2d01.acudevint\x2dadp02.service
● vsts.agent.acustgint\x2dtfs01.LINUX\x2dBUILD\x2d01.acudevint\x2dadp02.service - Azure Pipelines Agent (acustgint-tfs01.LINUX-BUILD-01.acudevint-adp02)
     Loaded: loaded (/etc/systemd/system/vsts.agent.acustgint\x2dtfs01.LINUX\x2dBUILD\x2d01.acudevint\x2dadp02.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-08-27 12:33:06 UTC; 5s ago
   Main PID: 99767 (runsvc.sh)
      Tasks: 9531 (limit: 9530)
     Memory: 1.7G
     CGroup: /system.slice/vsts.agent.acustgint\x2dtfs01.LINUX\x2dBUILD\x2d01.acudevint\x2dadp02.service
             ├─ 5792 ./externals/node/bin/node ./bin/AgentService.js
             ├─ 5799 /home/xxxx/bin/Agent.Listener run --startuptype service
             └─99767 /bin/bash /home/xxxx/vsts-2.165.0/runsvc.sh

Aug 27 12:33:06 acudevint-adp02 systemd[1]: Started Azure Pipelines Agent (acustgint-tfs01.LINUX-BUILD-01.acudev…adp02).
Aug 27 12:33:06 acudevint-adp02 runsvc.sh[99767]: /home/xxxx/vsts-2.165.0/runsvc.sh: fork: retry: Resource tem…ailable
Aug 27 12:33:07 acudevint-adp02 runsvc.sh[99767]: /home/xxxx/vsts-2.165.0/runsvc.sh: fork: retry: Resource tem…ailable
Aug 27 12:33:09 acudevint-adp02 runsvc.sh[99767]: /home/xxxx/vsts-2.165.0/runsvc.sh: fork: retry: Resource tem…ailable
Hint: Some lines were ellipsized, use -l to show in full.
xxxx@xxxx-adp02:~/vsts-2.165.0$ ./run.sh
Scanning for tool capabilities.
Connecting to the server.
2022-08-27 12:33:48Z: Listening for Jobs
Agent update in progress, do not shutdown agent.
Downloading 2.181.2 agent
Waiting for current job finish running.
Generate and execute update script.
Agent will exit shortly for update, should back online within 10 seconds.
xxxx@xxxx-adp02:~/vsts-2.165.0$ renamed '/home/xxxx/vsts-2.165.0/_diag/SelfUpdate-20220827-123429.log' -> '/home/xxxx/vsts-2.165.0/_diag/SelfUpdate-20220827-123429.log.succeed'
Scanning for tool capabilities.
Connecting to the server.```

_Originally posted by @sam-crisp in https://github.com/microsoft/azure-pipelines-agent/issues/3176#issuecomment-1229185561_

**Comment by emi662002** [comment]
I'm experiencing the same, but I get sporadicly some further, sometimes even connection, (though it hangs when receiving a job)

it's exactly whats described here:
https://github.com/microsoft/azure-pipelines-agent/issues/3093#issuecomment-726202183

i'm using Ubuntu 20.04.

**Comment by DmitriiBobreshev** [comment]
Hi @sam-crisp!
Thanks for your request, we've added this issue to our backlog. We'll take a look at it once we have enough capacity.

**Comment by kirill-ivlev** [comment]
@emi662002 Could you please confirm that this problem exists on the latest agent releases? 2.211.1 as an example?

**Comment by emi662002** [comment]
> @emi662002 Could you please confirm that this problem exists on the latest agent releases? 2.211.1 as an example?

I get the same error with v2.210.1 I guess my script is not updating to the latest (beta ? ) 

agent v2.210.1             |_|          (commit fae6a0b)
>> End User License Agreements:
Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.
A copy of the Team Explorer Everywhere license agreement can be found at:
  /azp/license.html
>> Connect:
Connecting to server ...
>> Register Agent:
Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
2022-09-17 12:49:30Z: Settings Saved.
4. Running Azure Pipelines agent...
Starting Agent listener with startup type: service - to prevent running of an agent in a separate process after self-update
Scanning for tool capabilities.
Connecting to the server.

**Comment by sergey-koryshev** [comment]
@sam-crisp, @emi662002 could you please try to use pre-release of .NET 6 version of agent and see if it resolves the issue? https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.212.0

We saw alike issue which was related to the fact that `.NET 3.1` hangs on some environments by some reason. Did you tried to configure agent on fresh installed `Ubuntu 20.04`?

**Comment by emi662002** [comment]
this is what I get installed right now
ubuntu 20.04
agent v2.213.2             |_|          (commit 4f90e68)

btw, im using this https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#create-and-build-the-dockerfile-1

i will try to change the script to download the pre-release...

**Comment by emi662002** [comment]
> @sam-crisp, @emi662002 could you please try to use pre-release of .NET 6 version of agent and see if it resolves the issue? https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.212.0
> 
> We saw alike issue which was related to the fact that `.NET 3.1` hangs on some environments by some reason. Did you tried to configure agent on fresh installed `Ubuntu 20.04`?

this is what I get installed right now
ubuntu 20.04
agent v2.213.2 |_| (commit https://github.com/microsoft/azure-pipelines-agent/commit/4f90e68aaafa0393021e8330f2d0bc7c0697be0b)

btw, im using this https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#create-and-build-the-dockerfile-1

i will try to change the script to download the pre-release...

**Comment by emi662002** [comment]
> @sam-crisp, @emi662002 could you please try to use pre-release of .NET 6 version of agent and see if it resolves the issue? https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.212.0
> 
> We saw alike issue which was related to the fact that `.NET 3.1` hangs on some environments by some reason. Did you tried to configure agent on fresh installed `Ubuntu 20.04`?

I can confirm, this works with the given pre-release.
When can we expect this release to be available as latest?

**Comment by sergey-koryshev** [comment]
@emi662002 we are currently testing agent based on `.NET 6` but unfortunately I can't say you when it will happen. You can check [roadmap](https://learn.microsoft.com/en-us/azure/devops/release-notes/features-timeline) and related [blog post](https://devblogs.microsoft.com/devops/upgrade-of-net-agent-for-azure-pipelines/) to get more information.

Let me to close the issue as mitigated, feel free to reactivate it or create new one.
