### ISSUE TITLE
[Feature request] Add new agent capability that allows repositories to be checked out below work directory level on self hosted agents

### ISSUE THREAD

**Issue by echalone** [microsoft/azure-pipelines-agent#3951]
This is a feature request for a new agent capability that would allow self hosted agents to check out repositories below the work directory level (so for example below "/_work", instead of just below the build pipeline directory level for example "/_work/1"), so large repositories can be shared between build pipelines without taking up space for each and every pipeline.
This feature should be disabled by default as pipelines could otherwise interfere with each other on public agents or users on public agents could change configuration files below the work directory, which would pose a security risk.
It could for example be activated by passing a flag to the configuration command in the command line when configuring the agent.

**I would have already implemented this feature as described and have already created a pull request** to the master branch of this repository: https://github.com/microsoft/azure-pipelines-agent/pull/3475
**The pull request needs to be reviewed and accepted.**

A more thorough description of how the feature was implemented can be found in the pull request.

PS: I'm reopening/readding this issue since https://github.com/microsoft/azure-pipelines-agent/issues/3483 was wrongfully closed by a stale-bot, it's not really stale, it just hasn't been processed yet

**Comment by DmitriiBobreshev** [comment]
Hi @echalone!

Thank you for your request and for the PR, we will test & review it, once we will have capacity.

**Comment by echalone** [comment]
ah damn, I was too late, this is not stale, this is actually still open :/
