### ISSUE TITLE
Appium UI tests fails after ~15 minutes of Agent inactivity

### ISSUE THREAD

**Issue by Xiphereal** [microsoft/azure-pipelines-agent#3971]
## Agent Version and Platform
Version of your agent? 2.198.3/2.210.1

OS of the machine running the agent? Windows NT 10.0.19044

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? On-premise Azure DevOps Server

If on-premises, which release? 2020 Update 1.2

## What's not working?
Some context: we're implementing UI tests with Appium and WinAppDriver, to be executed on self-hosted Agents. Currently, we have a "prototype UI test", which consist on opening a given app, check that it has been opened by interacting with it, and closes it again.

Out test fails when the Agent is inactive for ~15 minutes. If the Agent is restarted or has executed a successful build over the last 15~ minutes (for example, chaining successful UI test build runs, with less than ~15 minutes between runs), the UI tests passes as expected. The test fails on the step of checking that the app has been opened, by interacting with it.

## Agent and Worker's Diagnostic Logs
I'll attach several Agents log, when Workers executing the failing Job where instantiated:

[Agent_20220919-104856-utc](https://gist.github.com/Xiphereal/34de1f3572046dc5cfeefcd3bdbcad14)
[Agent_20220919-104433-utc](https://gist.github.com/Xiphereal/0f85aacf808e8618a1b7162f00447949)
[Agent_20220919-104318-utc](https://gist.github.com/Xiphereal/69b17445fb84cf225daa78fccca1412e)

[Worker_20220919-110526-utc](https://gist.github.com/Xiphereal/d97bb0f9e433b013014dda576833ca38)
[Worker_20220919-113900-utc](https://gist.github.com/Xiphereal/b3a53f5beec8e1b927d7d3a4b0c935bb)

If needed, I can also attach a successful run.

**Comment by max-zaytsev** [comment]
Hi @Xiphereal,
We are working on more prioritized issues at the moment but will get back to this one soon.
At this moment could you please post your question here https://developercommunity.visualstudio.com/search?space=21&entry=problem

**Comment by Xiphereal** [comment]
Done, [here](https://developercommunity.visualstudio.com/t/Appium-UI-tests-fails-after-15-minutes/10156083?space=21&entry=problem&q=Appium+UI+tests+fails+after+%7E15+minutes+of+Agent+inactivity) it is.
