### ISSUE TITLE
MSB1009 Project file does not exist with agent version 2.211.0

### ISSUE THREAD

**Issue by leeh14** [microsoft/azure-pipelines-agent#3982]
Once the agent version went from 2.210 to 2.2111 my scheduled builds without changing anything suddenly kept throwing the MSB1009 error.
Version 2.210:
![image](https://user-images.githubusercontent.com/6685053/194064210-59567e1d-5737-42f7-9929-2cf423b5bdc0.png)
Then later in the day it updated to 2.211
![image](https://user-images.githubusercontent.com/6685053/194064357-508e2ae2-20d8-4367-a5b2-a5b6ecfaf429.png)
According to the debug message i believe the issue most likely is related to the resolve path missing quotes or it isn't currently working
When it was working:
![image](https://user-images.githubusercontent.com/6685053/194064629-a63a108d-8308-401f-b90a-9f2446681c37.png)
Currently:
![image](https://user-images.githubusercontent.com/6685053/194064719-f796f7aa-6656-4284-b93f-c87eaba78620.png)
When it was working you can see that the resolve path has the correct path with it:
![image](https://user-images.githubusercontent.com/6685053/194065067-c6e4fa5c-6f20-46eb-a4f6-f357bc87781f.png)
Then with the new version 
![image](https://user-images.githubusercontent.com/6685053/194065182-0ec736ca-5a82-4e31-a89b-d6170211eaf5.png)
you can see it didn't resolve the $ thus its looking at the wrong location
The only difference between the two builds does look to be only the agent version being different. I've already checked azure status for the pipelines and there is nothing there

**Comment by max-zaytsev** [comment]
@leeh14 was the version of the visual studio build task changed?

**Comment by leeh14** [comment]
@max-zaytsev  nope the version was not changed. It has been at 1.x the entire time
![image](https://user-images.githubusercontent.com/6685053/194094860-1541bd62-37a6-4deb-9b77-c93ed551f6bf.png)
I believe it shows in the 3rd and fourth screen shot as 1.208.0 both times Let me know if that's not the build version you're looking for

**Comment by leeh14** [comment]
@max-zaytsev That looks like it did the trick if you don't mind me asking am I correct to assume because the default value was true it wasn't correctly resolving the path?
I appreciate your quick assistance in this matter.

**Comment by max-zaytsev** [comment]
@leeh14 There was a change in tf vc command manager which caused this problem. Setting `agent.TfVCUseSecureParameterPassing` to `false` helps to fall back to the previous logic.
We are going to investigate the issue and prepare a hotfix.  Thank you for reporting!

**Comment by max-zaytsev** [comment]
@leeh14 could you please provide us with[ pipeline json](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/clone-import-pipeline?view=azure-devops&tabs=classic#build-pipeline) file for investigation?
You can send it to v-mazayt@microsoft.com

**Comment by leeh14** [comment]
@max-zaytsev I have sent the email
