### ISSUE TITLE
Linux Agent: "free(): corrupted unsorted chunks" error after starting job

### ISSUE THREAD

**Issue by amasolini** [microsoft/azure-pipelines-agent#3993]
## Agent Version and Platform
Version of your agent? v2.211.1 (commit 09f0f48)

OS of the machine running the agent? AlmaLinux 8.6 (Sky Tiger)

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
After triggering a release pipeline (with a small, almost empty script that does nothing inside), the agent is crashing with the following error:

Connecting to the server.
2022-10-14 19:16:47Z: Listening for Jobs
2022-10-14 19:18:25Z: Running job: Release
free(): corrupted unsorted chunks
./run.sh: line 68:  1943 Aborted                 (core dumped) "$DIR"/bin/Agent.Listener run $*

**Comment by LiliaSabitova** [comment]
Hi @amasolini, thank you for reporting the issue. I'm sorry, but we don't support AlmaLinux 8.6.
You can find list of supported operating systems [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#check-prerequisites).
By the way, have you had previous versions of agent working fine on your system before?

**Comment by LiliaSabitova** [comment]
Closing the issue because there is no answer.
Please re-open it in case of questions related to this topic.

**Comment by amasolini** [comment]
Hi @LiliaSabitova , sorry for the late response, I haven't seen the notifications before.

Just to answer your question and for the record, I have never been able to make the agent work on that specific machine, but I did tried installing it under an Ubuntu 20.04, facing similar issues. I'm going to switch to Ubuntu again and i'll reopen the issue (changing the details).
