### ISSUE TITLE
 ./svc.sh: command not found

### ISSUE THREAD

**Issue by CraigCraig-jpeg** [microsoft/azure-pipelines-agent#3998]
The command failed with exit code 1
  0. Determining if Azure Pipelines agent is configured...
  1. Determining matching Azure Pipelines agent...
  2. Downloading and installing Azure Pipelines agent...
  3. Configuring Azure Pipelines agent...
  [sudo] password for ***: sudo: ./svc.sh: command not found

tried this fix https://github.com/Microsoft/azure-pipelines-agent/issues/1435

but it fails with 

E: Package 'libicu67' has no installation candidate
Reading package lists... Done
Building dependency tree
Reading state information... Done
libicu66 is already the newest version (66.1-2ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-----------------------------
 Finish Install Dependencies
-----------------------------
 
Specifications 
- OS: Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1020-azure x86_64)
- -> Image is running in vsphere
- -> image is replicate of azure ubuntu-latest image thats used in azure devops
- Version of agent:
- -> link https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-win-x64-2.211.1.zip
- -> version 2.211.1.

Desired outcome: 
i just want the svc.sh files to show up to pop the agent into systemd, not sure why it thinks its not installing it

**Comment by CraigCraig-jpeg** [comment]
tried to get logs but none avalable

**Comment by Roman-Shchukin** [comment]
Is the link to the agent in your comment correct? This is Window version but you are talking about Ubuntu.
> link https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-win-x64-2.211.1.zip

Did you follow this recommendation to run installdependencies.sh?
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#:~:text=The%20agent%20installer%20knows%20how%20to%20check%20for%20other%20dependencies.%20You%20can%20install%20those%20dependencies%20on%20supported%20Linux%20platforms%20by%20running%20./bin/installdependencies.sh%20in%20the%20agent%20directory.

**Comment by Roman-Shchukin** [comment]
HI @CraigCraig-jpeg do you have any updates?

**Comment by Roman-Shchukin** [comment]
Hi @CraigCraig-jpeg , close this issue. Feel free to ask any other questions or let us know if it's still relevant for you.
