### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by alenros** [microsoft/azure-pipelines-agent#4004]
Latest pre-release version is 3.212.0
The release before that was 2.211.1
Shouldn't the pre-release version be 2.212?

https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.212.0

**Comment by Roman-Shchukin** [comment]
It's pre-release of agent version on .net 6.
2.211.1 version on .net 3.1
3.xxx and 2.xxx version will supported simultaneously. We will add a description to this release
