### ISSUE TITLE
Xamarin.Build.Download - Error : Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by vincentcastagna** [microsoft/azure-pipelines-agent#4009]
## Agent Version and Platform

Using **"windows-2022"** as vmImage for the pool.

The exact issue on some agents is : 

`[error]C:\Users\VssAdministrator\.nuget\packages\xamarin.build.download\0.11.0\buildTransitive\Xamarin.Build.Download.targets(52,3): Error : Cannot create a file when that file already exists.`

Version of your agent? 2.211.1

```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'WIN-47H1L50AF85'
Current agent version: '2.211.1'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20221024.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: gitversion/setup (0.9.14)
Downloading task: gitversion/execute (0.9.14)
Downloading task: NuGetToolInstaller (1.208.1)
Downloading task: MSBuild (1.211.0)
Downloading task: PublishBuildArtifacts (1.200.0)
Downloading task: PostBuildCleanup (3.1.1)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = C:\agents\perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Plugin: 'Test Result Parser plugin' is running in background.
Plugin: 'Test File Publisher plugin' is running in background.
Start tracking orphan processes.
Finishing: Initialize job
```

OS of the machine running the agent? Windows

## What's not working?

All agents named **"WIN-XXX"** will produce a Xamarin.Build.Download error : 

`[error]C:\Users\VssAdministrator\.nuget\packages\xamarin.build.download\0.11.0\buildTransitive\Xamarin.Build.Download.targets(52,3): Error : Cannot create a file when that file already exists.`

Agent machine name: 'fv-az132-286' **IS WORKING**  and does NOT produce this error.

## Question is : what is different between  **fv-az132-286** AND **WIN-47H1L50AF85**

We tried to specify the agent computer name but it throws. Also this is not a viable fix. 

`No agent found in pool Azure Pipelines which satisfies the following demand: Agent.ComputerName. All demands: Agent.ComputerName -equals fv-az132-286, Agent.Version -gtVersion 2.163.1`

## Agent and Worker's Diagnostic Logs

`[error]C:\Users\VssAdministrator\.nuget\packages\xamarin.build.download\0.11.0\buildTransitive\Xamarin.Build.Download.targets(52,3): Error : Cannot create a file when that file already exists.`

**Comment by kirill-ivlev** [comment]
@vincentcastagna thank you for reporting that! 
Could you please confirm that the same pipelines fail on one agent but work fine on another, depending on the selected agent? 
Is it possible to share a minimal pipeline defenition that has this issue?
