### ISSUE TITLE
Questions of getting a fresh new VM  for each job in the pipeline (Microsoft-hosted agent)

### ISSUE THREAD

**Issue by MarsWangyang** [microsoft/azure-pipelines-agent#4014]
## Agent Version and Platform
```2.211.1```

OS of the machine running the agent? 
```Windows 2022```

## Azure DevOps Type and Version
dev.azure.com

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.
```https://dev.azure.com/marswang0522/```

## What's not working?
1. **Agent machine question**: I looked for the doc and found out that it describe a feature of Microsoft-hosted agents is "Each time you run a pipeline, you get **a fresh virtual machine** for each job in the pipeline. " I tried to build with different Agent jobs in a pipeline. I can't see the directories or files which set in Agent job0 in the beginning when Agent job 2 is running the same Windows 2022 image. However, the `Agent machine name` in different Agent jobs with same image would be the same one. What does this `Agent machine name` stand for? Is it the virtual machine we will get when a new Agent job is running?
Reference: [Microsoft-hosted agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#microsoft-hosted-agents)
<img width="1035" alt="Screenshot 2022-10-31 at 10 21 28 PM" src="https://user-images.githubusercontent.com/68472667/199039621-e0fe07f8-6595-441a-a063-32625e664686.png">
<img width="1032" alt="Screenshot 2022-10-31 at 10 22 06 PM" src="https://user-images.githubusercontent.com/68472667/199039631-eb67c677-be40-4176-88e1-7f93864f4de2.png">

2. *Agent jobs sequence*: The pictures I post above encountered that I create Agent jobs from 0 to 2. Is it should be run in sequentially like Agent Jobs 0 -> 1 -> 2, and completed this pipelines? However, you can see that in the pictures above. Agent Job 2 ran first and then Agent Job 0, Agent Jobs 1. What is the mechanism behind the listener of agent to decide which Agent Jobs run first? 

## Agent and Worker's Diagnostic Logs
`No`

**Comment by kirill-ivlev** [comment]
@MarsWangyang thank you for reaching us!

1. Yes this is just the hostname of the provided virtual machine.
2. For the job sequences and order you can check in [this article ](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline)

**Comment by MarsWangyang** [comment]
@kirill-ivlev Thank you for such a quick reply.
I just check the IP address of two different Agent Jobs and I think it should be different VMs between two Agent Jobs even if they used the same image, just using the same hostname? or it actually use VMSS to scale out/in so the name would be identical but  IP addresses of both Agent Jobs are different.

**Comment by DmitriiBobreshev** [comment]
Hi @MarsWangyang. As you rightly pointed out, two jobs are independent in one pipeline with an ms-hosted agent, so every job has its own new VM (but they use [the same image](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)), they could have the same hostname as well, but not necessary.

We can't say what is under the hood(VMSS or another scale balancer or nothing), but you can make your [own scale set](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops) if you need.

Also, in case you need, there is a way to communicate between jobs via [variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#conditions)

**Comment by MarsWangyang** [comment]
Hi @DmitriiBobreshev 
Thank you for the explanation.
