### ISSUE TITLE
v3.212.0 throws NullReferenceException

### ISSUE THREAD

**Issue by VladimirKhvostov** [microsoft/azure-pipelines-agent#4015]
## Agent Version and Platform
Version of your agent? v3.212.0

## Repro
See discussion at https://developercommunity.visualstudio.com/t/Secure-file-download-throwing-Object-ref/10183848?sort=newest&scope=follow&viewtype=all which have an easy repro steps.

The issue was introduced in the https://github.com/microsoft/azure-pipelines-agent/pull/3973/

Thanks,
--Vladimir

**Comment by kirill-ivlev** [comment]
@VladimirKhvostov Thank you for reporting it, we will have a look

**Comment by LiliaSabitova** [comment]
PR: https://github.com/microsoft/azure-pipelines-agent/pull/4018

**Comment by LiliaSabitova** [comment]
Merged to master and dotnet6-agent branches
