### ISSUE TITLE
self hosted agent error on the AKS cluster 1.22.15

### ISSUE THREAD

**Issue by shzshi** [microsoft/azure-pipelines-agent#4017]
## Having issue with software on Hosted Agent?
I have self hosted agent using ubuntu 18.04 docker image and it worked fined on the AKS (1.19.x) , but last week I upgraded the my aks cluster to 1.22.15 my ADO agents are failing with error below 

The SSL connection could not be established, see inner exception.

## Have you tried troubleshooting?
I tried to troubleshoot by creating a new docker agent with ubuntu 20.04 , but I keep getting same error and also followed few post within these github issues , but I am still getting same error. 

## Agent Version and Platform
Version of your agent? v2.211.1 and ubuntu 20.04

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server
If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com

## What's not working?
Please include error messages and screenshots.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by kirill-ivlev** [comment]
Hi @shzshi thank you for reporting that.
Could you please share exception details (agent log, could be found in _diag folder), and specify agent version.

**Comment by sergey-koryshev** [comment]
@shzshi to investigate the issue further we need to look at logs of agent, because we need to see inner exception. You can ask an owner of your AKS cluster to do it if you don't have an access to it.

**Comment by sergey-koryshev** [comment]
I close the issue because of inactivity. Please feel free to reactivate it or create new one.
