### ISSUE TITLE
Agent doesn't wait until docker is ready before accepting container jobs

### ISSUE THREAD

**Issue by daniel-anova** [microsoft/azure-pipelines-agent#4050]
## Agent Version and Platform
Version of your agent? 2.213.1

ubuntu 20.04 image built of [runner-images commit f6632ff5](https://github.com/actions/runner-images/commit/f6632ff53b24db9705c5b15bf90dbf05cc3fe295)

## Azure DevOps Type and Version
dev.azure.com/anovateam/

## What's not working?

As [reported here](https://developercommunity.visualstudio.com/t/Agent-in-VMSS-gets-assigned-job-before-f/10193312?q=job+starts+before+agent+ready), when using a VMSS that can scale to 0 replicas the agent will not wait for the newly spun up VM is fully ready before it attempts to run a job.

In my case the pipeline uses container tasks and docker not fully started when the agent accepts the job, thus fetching the container fails as the agent can't access docker socket.

Please include error messages and screenshots.

```
Starting: Initialize containers
/usr/bin/docker version --format '{{.Server.APIVersion}}'
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
'
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'version --format '{{.Server.APIVersion}}''.
Finishing: Initialize containers
```

Using a workaround job to delay the startup with the following bash code:

```yaml
- job: WaitForDocker
  steps:
    - checkout: none
    - bash: |
        while (! docker stats --no-stream ); do
          echo "Waiting for Docker to launch..."
          sleep 1
        done
```

```
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash /agent/_work/_temp/e32747f6-fb5c-44ed-a861-4c0a43195065.sh
/agent/_work/_temp/e32747f6-fb5c-44ed-a861-4c0a43195065.sh: line 1: docker: command not found
Waiting for Docker to launch...
/agent/_work/_temp/e32747f6-fb5c-44ed-a861-4c0a43195065.sh: line 1: docker: command not found
Waiting for Docker to launch...
/agent/_work/_temp/e32747f6-fb5c-44ed-a861-4c0a43195065.sh: line 1: docker: command not found
Waiting for Docker to launch...
/agent/_work/_temp/e32747f6-fb5c-44ed-a861-4c0a43195065.sh: line 1: docker: command not found
Waiting for Docker to launch...
/agent/_work/_temp/e32747f6-fb5c-44ed-a861-4c0a43195065.sh: line 1: docker: command not found
Waiting for Docker to launch...
/agent/_work/_temp/e32747f6-fb5c-44ed-a861-4c0a43195065.sh: line 1: docker: command not found
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Waiting for Docker to launch...
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
Finishing: Bash
```

This however isn't reliable as I can't guarantee the job runs on the same agent as the container-dependent job.

## Agent and Worker's Diagnostic Logs

Think it's not needed for this case.

**Comment by daniel-anova** [comment]
We've seen had to move our VMSS agents to another region (northcentralus) and now occasionally encountering the `2022-11-25T15:04:15.3090540Z ##[error]File not found: 'docker'` error even with the previous workaround.

**Comment by DmitriiBobreshev** [comment]
Hi @daniel-anova, @davidandradeduarte, at this moment we are trying to implement it and now we have [the PR](https://github.com/microsoft/azure-pipelines-agent/pull/4100)  that probably resolves your problem, I'm additionally ping you when there PE will be included in new agent version so you could check that it will fix your issue.

**Comment by JoostVoskuil** [comment]
Seems that https://github.com/microsoft/azure-pipelines-agent/pull/4100 is inside agent software v2.217.2 but this issue is not resolved for us.

![image](https://user-images.githubusercontent.com/4078158/217007049-0424c77b-2d2c-4c03-a037-51f8d6be1e8b.png)

**Comment by DmitriiBobreshev** [comment]
Hi @daniel-anova, agent version 2.217.2 with docker retries was released for ms-hosted agents, now it should retry docker command for some time in cases when docker is not started yet.

@davidandradeduarte, I'm so sorry, that didn't see that you're using [DockerV0 ](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerV0/task.json) task, this issue about [container jobs](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)  in the agent, could you please create a relevant issue in [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repository? sorry again.

@JoostVoskuil your problem usually happens when docker is not installed in the system or doesn't present in path, could you please create a new issue for it in the [azure-pipelines-agent](https://github.com/microsoft/azure-pipelines-agent) repository

**Comment by DmitriiBobreshev** [comment]
Hi @daniel-anova, could you please share the status? Are there any problems that still exist?

**Comment by daniel-anova** [comment]
Tried running a test in our Scaleset pool with 2.217.2 agents and seems container jobs no longer fail when the VMs are starting out.

Think we can consider the issue resolved.
