### ISSUE TITLE
build agent doesn't show up when installed via the Extension API.

### ISSUE THREAD

**Issue by igaw** [microsoft/azure-pipelines-agent#4054]
## Agent Version and Platform
v2.213.1

OS of the machine running the agent?

Debian-11

## Azure DevOps Type and Version
https://dev.azure.com/linux-nvme

## What's not working?
Build agent doesn't show up when installing it via the Extension.

When registering the agent by hand: 

```sh
./config.sh \
   --unattended \
   --acceptteeeula \
   --url https://dev.azure.com/linux-nvme \
   --work _work \
   --auth PAT \
   --token <token> \
   --runasservice \
   --pool linux-nvme
```

the agent is correctly registered and everything seems to work. Though, when I try to install the agent via the Extension API the agent is not showing up as build agent. FWIW, it shows up as deploy agent though.

There are the parameters I used to register the agent:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
       "vmName": {
            "value": "LinuxNvmeRGpool"
        },
        "location": {
            "value": "westeurope"
        },
        "vstsAccountUrl": {
            "value": "https://dev.azure.com/linux-nvme"
        },
        "teamProject": {
            "value": "nvme-cli"
        },
        "deploymentGroup": {
            "value": "linux-nvme"
        },
        "agentName": {
            "value": "buildvm"
        },
        "patToken": {
            "value": null
        },
        "tags": {
            "value": ""
        }
    }
}
```

## Agent and Worker's Diagnostic Logs
[Agent_20221111-133915-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/9990722/Agent_20221111-133915-utc.log)
[Agent_20221111-133919-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/9990723/Agent_20221111-133919-utc.log)

**Comment by igaw** [comment]
I must have been blind, I just saw that the log contains:

  `[2022-11-11 13:39:20Z WARN VisualStudioServices] Authentication failed with status code 401.`

But I have not idea why the PAT token works when registering by hand.

**Comment by igaw** [comment]
Comparing the dot config file left behind from the Extension (*.orig) against the `config.sh` step by hand, shows this:

```sh
-rw-r--r--  1 azureuser azureuser       194 Nov 11 14:52 .agent
-rw-r--r--  1 azureuser azureuser       276 Nov 11 13:45 .agent.orig
-rw-r--r--  1 azureuser azureuser       268 Nov 11 14:52 .credentials
-rw-r--r--  1 azureuser azureuser       268 Nov 11 13:45 .credentials.orig
-rw-------  1 azureuser azureuser      1667 Nov 11 14:52 .credentials_rsaparams
```

```diff
--- .agent.orig 2022-11-11 13:45:03.577206541 +0000
+++ .agent      2022-11-11 14:52:55.948949176 +0000
@@ -1,11 +1,9 @@
 ﻿{
   "acceptTeeEula": true,
-  "agentId": 16,
+  "agentId": 17,
   "agentName": "buildvm",
-  "poolId": 14,
+  "poolId": 24,
   "poolName": "linux-nvme",
   "serverUrl": "https://dev.azure.com/linux-nvme/",
-  "workFolder": "_work",
-  "deploymentGroupId": 22,
-  "projectId": "ab992a5e-61b3-439f-ab1a-5a8389afa666"
+  "workFolder": "_work"
 }
```

```diff
--- .credentials.orig   2022-11-11 13:45:02.657173052 +0000
+++ .credentials        2022-11-11 14:52:53.204907980 +0000
@@ -1,7 +1,7 @@
 ﻿{
   "scheme": "OAuth",
   "data": {
-    "clientId": "7e9dd0a0-4347-4e60-9dc1-57a4a3f945a8",
+    "clientId": "0c331a44-f2cf-484b-8e14-261bff584438",
     "authorizationUrl": "https://vssps.dev.azure.com/linux-nvme/_apis/oauth2/token",
     "oauthEndpointUrl": "https://vssps.dev.azure.com/linux-nvme/_apis/oauth2/token"
   }
```

The `.credentials_rsaparams` file is missing in the Extension install step.

**Comment by igaw** [comment]
BTW, the PAT token is with all rights and from my account as admin and I am using it for both ways to register the agent. So I think we can ignore this part.

Some more experiments and starring at the logs and  the main difference I could see is how the `poolID` is gathered. In the good case we end up with the `poolID = 24`:

```
[2022-11-11 16:24:10Z INFO Terminal] WRITE LINE: 
[2022-11-11 16:24:10Z INFO Terminal] WRITE LINE: >> Register Agent:
[2022-11-11 16:24:10Z INFO Terminal] WRITE LINE: 
[2022-11-11 16:24:10Z INFO CommandSettings] Arg 'pool': 'linux-nvme'
[2022-11-11 16:24:10Z INFO BuildReleasesAgentConfigProvider] Found pool linux-nvme with id 24 and name linux-nvme
[2022-11-11 16:24:10Z INFO CommandSettings] Arg 'agent': ''
[2022-11-11 16:24:10Z INFO CommandSettings] Flag 'unattended': 'True'
```

and in the bad case it is `poolID = 14`:

```
[2022-11-11 13:39:17Z INFO Terminal] WRITE LINE: 
[2022-11-11 13:39:17Z INFO Terminal] WRITE LINE: >> Register Agent:
[2022-11-11 13:39:17Z INFO Terminal] WRITE LINE: 
[2022-11-11 13:39:17Z INFO CommandSettings] Arg 'projectname': 'nvme-cli'
[2022-11-11 13:39:17Z INFO CommandSettings] Arg 'deploymentgroupname': 'linux-nvme'
[2022-11-11 13:39:17Z INFO DeploymentGroupAgentConfigProvider] Found deployment group linux-nvme with id 22
[2022-11-11 13:39:17Z INFO DeploymentGroupAgentConfigProvider] PoolId for deployment group 'linux-nvme' is '14'.
[2022-11-11 13:39:17Z INFO DeploymentGroupAgentConfigProvider] Project id for deployment group 'linux-nvme' is 'ab992a5e-61b3-439f-ab1a-5a8389afa666'.
[2022-11-11 13:39:17Z INFO CommandSettings] Arg 'agent': 'buildvm'
```

**Comment by igaw** [comment]
This would boil down to the fact that the `Configure` JSON input differs here:

good case:

```json
  "Pool": "linux-nvme",
  "ProjectName": null,
```

bad case:

```json
  "Pool": null,
  "ProjectName": "nvme-cli", 
```

**Comment by igaw** [comment]
I've destroyed my pool and created it again. I noticed that the warning which I ignored so far:

![image](https://user-images.githubusercontent.com/1050803/201396170-64484780-82a0-42b9-a799-60fb398f21bf.png)

So it looks like I might have an old pool in my system from my previous experiments which will be found using the `ProjectName` approach. Because the new pool got the id 25.

**Comment by igaw** [comment]
The agent is still able to register to pool 14 even after I delete all pools I could find in the UI. So the question is how do I delete this hidden pool?

**Comment by igaw** [comment]
Deleted the origination, created a new one but still get the warning and the agent gets not registered (some authentication error) Though this time the pool id is 13. So something has changed.

**Comment by KonstantinTyukalov** [comment]
Hi @igaw, thanks for the reporting! We'll look into the issue once we've dealt with the higher priority tickets

**Comment by igaw** [comment]
FWIW, I did some more experiments and recreated my complete setup but now I fighting with a new problem. The Extension is not able register anymore. This step worked flawlessly before. Maybe I did something wrong in the recreation bits. I'll try again.

**Comment by igaw** [comment]
I gave up on this problem and decided against using the extension.
