### ISSUE TITLE
Error trying to run ./svc.sh install (systemd-escape: command not found)

### ISSUE THREAD

**Issue by danysp21** [microsoft/azure-pipelines-agent#4055]
### ****Agent Version and Platform**
**Version of your agent?****

`vsts-agent-rhel.6-x64-2.163.1`

**OS of the machine running the agent?**
`Red hat 6`

### **Azure DevOps Type and Version**
`dev.azure.com`

### **What's not working?**

```
[operator@XXXX myagent]$ sudo ./svc.sh install operator
./svc.sh: line 3: systemd-escape: command not found
Creating launch agent in /etc/systemd/system/
Run as user: operator
Run as uid: 510
gid: 510
mv: cannot move `./bin/vsts.agent.service.temp' to `/etc/systemd/system/': No such file or directory
Failed: failed to copy unit file
```

An attempt was made to execute the command to generate the service but these errors appeared, apparently this file is not compatible with the version of RedHat 6.10
[svc.zip](https://github.com/microsoft/azure-pipelines-agent/files/9993549/svc.zip)

**Comment by danysp21** [comment]
Hi how are things,

Apparently `systemd` is not compatible with the version of the operating system that I have rhel6.

I think that in this version they use the `upstart`

**Comment by KonstantinTyukalov** [comment]
This seems to be the problem reported earlier - https://github.com/microsoft/azure-pipelines-agent/issues/2117
Let us check what we can do here

**Comment by danysp21** [comment]
Thanks for the answer, when I carry out all the steps indicated in the link, at the end when I want to start the service `service az4 start` the following appears:
`Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at Microsoft.VisualStudio.Services.Agent.Util.StringUtil.ConvertToBoolean(System.String, Boolean)
   at Agent.Sdk.Knob.KnobValue.AsBoolean()
   at Agent.Sdk.PlatformUtil.get_UseLegacyHttpHandler()
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.Main(System.String[])
/etc/init.d/az4: line 74:  5011 Aborted                 (core dumped) "$DIR"/bin/Agent.Listener run $*`
I have tried placing executing without success:

`export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`

**Comment by danysp21** [comment]
I solved the problem by adding the following line in the `Agent.Listener.runtimeconfig.json` file:
```
{
    "runtimeOptions": {
        "configProperties": {
            "System.Globalization.Invariant": true
        }
    }
}

```
 now the `service az4 start` command works but even so I see that it continues to be executed by the user and if I close the connection the process crashes.
Is there something else I should do?

This is how it stays in the message

```
[XXXX@XXXX ~]$ service az4 start
Scanning for tool capabilities.
Connecting to the server.
2022-11-19 06:44:43Z: Listening for
```
