### ISSUE TITLE
Updating NodeJS 16 to patch vulnerabilities

### ISSUE THREAD

**Issue by easkay-castlight** [microsoft/azure-pipelines-agent#4075]
## Agent Version and Platform
Version of your agent? 2.213.2

OS of the machine running the agent? OSX/Windows/Linux/...
Linux x64 (Ubuntu 18.04)

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
dev.azure.com

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.
N/A

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com
https://dev.azure.com/castlightfinancial

## What's not working?
Vulnerability scanning tools have detected that the NodeJS binary installed by the agent (`<agent_dir>/externals/node16/bin/node`) is version `16.15.1` which is vulnerable to various CVEs. Is it please possible to patch the agent to use a newer verseion of NodeJS 16? Such as 16.17.1?

## Agent and Worker's Diagnostic Logs
N/A

EDIT1: updated organisation answer to be a URL.

**Comment by max-zaytsev** [comment]
@easkay-castlight thank you for reporting the issue.
We'll take a look at it

**Comment by easkay-castlight** [comment]
Hey @max-zaytsev and @Roman-Shchukin, I'm sorry to bother you but I was wondering when/how this change would get released. I just installed what I think is the latest released version of the agent without NodeJS 6 (pipelines-agent-linux-x64-2.214.1.tar.gz), however the version of NodeJS 16 is still 16.15.1.

I think perhaps I'm missing something here, as I expected that with these changes merged, the binary would be updated.
```
myagent/externals/node16/bin/node --version
v16.15.1
```

Any guidance would be appreciated.
