### ISSUE TITLE
Variable $(Build.Repository.Name) not working as expected

### ISSUE THREAD

**Issue by Grenston** [microsoft/azure-pipelines-agent#4078]
I am trying to setup a cross-repository policy and have written a build validation pipeline.
The checkout step I am using is as follows
```- checkout: git://Project-Name/$(Build.Repository.Name)@$(Build.SourceBranch)```

Whenever there is a pull request in any repository of my project this pipeline will trigger.
In my case ```$(Build.SourceBranch)``` is referring to the pull request and that's what I want, but ```$(Build.Repository.Name)``` is referring to the name of the pipeline repo instead of the triggering repo.

**Comment by DenisRumyantsev** [comment]
@Grenston thanks for your question.
We are currently working on higher-priority issues and we will work on your question as soon as we can

**Comment by Roman-Shchukin** [comment]
Hi @Grenston, we're looking into the issue with Build.Repository.Name and Build.SourceBranch variables. Could you try to use System.PullRequest.SourceRepositoryURI and System.PullRequest.SourceBranch variables instead of them? I assume this solution will work for you.

**Comment by lachlann562** [comment]
I have also discovered that ${{ variables['Build.Repository.Name'] }} does not work. System.PullRequest.* variables do not seem to be populated either when a CI build in a resource repository triggers the pipeline.

**Comment by buys-stash** [comment]
I have the same issue. However since I need to know which repository the Pull Request is triggered from and I need to know this inside my pipeline I wrote the code below:

`trigger: none

  steps:
  - checkout: self
    persistCredentials: true
  - checkout: git://$(System.TeamProject)/$(SourceRepositoryURI)@$(system.pullRequest.sourceBranch)
    persistCredentials: true

  - task: PowerShell@2
    displayName: "Get Pull Request Repository"
    inputs:
      targetType: "inline"
      script: |
        # Organization URI for Azure DevOps and header for authentication based on SYSTEM ACCESSTOKEN
        $adoProjectUri = ($Env:organization + $Env:project).Replace(" ", "%20")
        $header = @{Authorization = 'Basic ' + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$($Env:SYSTEM_ACCESSTOKEN)")) }

        # Get the correct repository
        $uri = $adoProjectUri + "/_apis/git/pullrequests/" + $Env:PullRequestId + "?api-version=7.0"
        $pullRequestRepository = (Invoke-RestMethod -Method GET -Uri $uri -Headers $header).repository
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      PullRequestId: $(System.PullRequest.PullRequestId)
      project: $(System.TeamProject)
      organization: $(System.CollectionUri)`

This way I can retrieve the repository from the Pull Request. However if you need to use this declaratively in your YAML then this is no solution, I am aware of that.

Hopefully someone from the team reads this and can give us a solution.

**Comment by Nagesh29** [comment]
@DenisRumyantsev 
Any updates on the this issue? I am still facing the same issue.
Build.Repository.Name not working for me.

**Comment by DenisRumyantsev** [comment]
Hi @Nagesh29 @sofarojo @buys-stash @lachlann562 @Grenston, does this solution work for you? —

```yml
trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: <repo-id>
    type: git
    name: <project-name>/<repo-name>
    ref: $(Build.SourceBranch)
    trigger:
      branches:
        include:
        - '*'

steps:
- checkout: <repo-id>
- bash: |
    echo "Hello, World!"
    pwd
    ls
    git status
```

**Comment by DenisRumyantsev** [comment]
Hi @Nagesh29 @sofarojo @buys-stash @lachlann562 @Grenston, any updates? Is the above solution suitable for you?

**Comment by sambracke** [comment]
They're asking after a variable containing the repository name, not the branch name...
I also have the same issue, wanting to use the name of the repo where the pipeline YAML is stored to determine where data (terraform state) gets written.

**Comment by DenisRumyantsev** [comment]
Hello @sambracke @Nagesh29 @sofarojo @buys-stash @lachlann562 @Grenston, please feel free to use the `pipeline.repository.name` pipeline variable instead of the `build.repository.name` pipeline variable.
I am closing this issue for now.
Feel free to reopen it if you think that the `pipeline.repository.name` pipeline variable does not work as expected.

**Comment by amirhooshangkarami** [comment]
hello @DenisRumyantsev 
we want to use build.repository.name to get triggering repository that not woks correctly.
pipeline.repository.name containing the name of the repository in which the pipeline is defined.

the solution is to use:
- checkout: myrepo
    #  condition: eq(variables['BUILD.REPOSITORY.NAME'], 'myrepo')
instead of:
- checkout: git://PROJECTNAME/$(Build.Repository.Name)

but when we use if for many repository this solution is not suitable.
TNX

**Comment by JWiinikka** [comment]
> Hello @sambracke @Nagesh29 @sofarojo @buys-stash @lachlann562 @Grenston, can you please check if the `$(pipeline.repository.name)` variable works as expected for you?
> 
> Triggering repo `$(build.repository.name)` — the first repo that has been modified. Triggered repo `$(pipeline.repository.name)` — the second repo with the `yml` file of the pipeline that detected changes in the first repo.
> 
> ```yaml
> trigger: none
> 
> pool:
>   vmImage: ubuntu-latest
> 
> resources:
>   repositories:
>   - repository: <repo-id>
>     type: git
>     name: <project-name>/<repo-name>
>     ref: $(Build.SourceBranch)
>     trigger:
>       branches:
>         include:
>         - '*'
> 
> steps:
> - checkout: <repo-id>
> - bash: |
>     echo "Triggering repo that has been modified (build.repository.name): $(build.repository.name)"
>     echo "Triggered repo with this YML file (pipeline.repository.name): $(pipeline.repository.name)"
> ```

As noted by @amirhooshangkarami , this information isn't correct. build.repository.name does NOT reference the triggering repo (such as a PR), but instead references the repo hosting the pipeline being triggered by the validation policy. Pipeline.repository.name references the same repo, the one hosting the yaml of the generic pipeline.

In my specific example, I have 2 repos, in different projects.

My Templates repo is in project A, and my dev modified repo for a product is in Project B. Devs update this repo in Project B, we'll call the repo "coderepo". I have a branch policy in Project B that runs a yaml pipeline in my Template repo in Project A. This policy works, and it shows up and executes on PRs. However, both of the aforementioned predefined variables return only Templates repo, and never return coderepo, even though the code change and PR were for coderepo.

Additionally, I'd prefer to just have it checkout "self" based on the triggering repo, as I have repos across projects and even providers (ADO/Github) that I'd like to be able to execute through this. Obviously, for some of these, the triggering mechanism will be different, but I'd like them all to route through the same generic template.

**Comment by ksitterle** [comment]
As a workaround you can extract the name from the System.PullRequest variables, as they don't seem to have the same bug.

```
  - name: PR_repo_name
    value: $(basename $(System.PullRequest.SourceRepositoryURI))
```

**Comment by tlaukkanen** [comment]
I would suggest to reopen this as the bug still exists. [Documentation for Build variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services) mentions that `Build.Repository.Name` should contain "The name of the triggering repository" - but instead it is the name of the repository where pipeline yaml is defined.

I would assume you can't change the value but at least fix the documentation. Workaround on getting the triggering repository name from `System.PullRequest.SourceRepositoryURI` only works for pull request builds - not e.g. CI builds as others have mentioned.

**Comment by yrdeboer** [comment]
> As noted by [@amirhooshangkarami](https://github.com/amirhooshangkarami) , this information isn't correct. build.repository.name does NOT reference the triggering repo (such as a PR), but instead references the repo hosting the pipeline being triggered by the validation policy. Pipeline.repository.name references the same repo, the one hosting the yaml of the generic pipeline.
> 

Perhaps useful to note that the information is at least _partially correct_ as Build.Repository.Name at runtime has the correct value.

Consider the following pipeline yaml which is stored in my **repo-2** and can be triggered by a commit to repo-1:

```
trigger:
- main

pool:
  name: SelfHostedForPipelineJobs
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: id-repo-1
    type: git
    name: repo-1
    ref: $(Build.SourceBranch)
    trigger:
      branches:
        include:
        - main
        - test

steps:
- checkout: id-repo-1
- bash: |
    echo "Triggering repo that has been modified (build.repository.name): $(build.repository.name) $BUILD_REPOSITORY_NAME"
    echo "Triggered repo with this YML file (pipeline.repository.name): $(pipeline.repository.name) $PIPELINE_REPOSITORY_NAME"
  displayName: $(Build.Repository.Name)
```

Below the output when a commit to repo-1 was the trigger. Note that the value of Build.Repository.Name is as expected in the bash script, but not as it appears in the displayName of the bash step:

![Image](https://github.com/user-attachments/assets/1e09b420-0c48-48ff-907d-899b558137cc)
