### ISSUE TITLE
Maintenance job should also clean old pipeline task versions

### ISSUE THREAD

**Issue by gertvdh** [microsoft/azure-pipelines-agent#4090]
## Agent Version and Platform
2.200.2

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) https://mecoms.visualstudio.com

## What's not working?
I schedule a maintenance job on the agent pool. That job doesn't seem to clean older versions of certain pipeline tasks. So under build agent working directory \ folder "_tasks" \ task folder for example the DotNetCoreCLI<guid> I see a lot of version folders.

It might be a good idea to also cleanup older versions of all tasks ever used by the agent. Some tasks are updated regularly, and versions may pile up.

**Comment by sergey-koryshev** [comment]
@microsoft/azure-pipelines-platform could you please take a look at this question?

**Comment by sergey-koryshev** [comment]
@gertvdh thank you for the suggestion. I added it to our backlog, we will work on it in order of priority.

**Comment by benketteridge** [comment]
The explosion in disk space used by _work and particularly _work/_tasks is getting to be a problem.
Is this anywhere near reaching the top of the backlog?
v 3.227.2 (Sept 2024)

**Comment by BenDuguid-MRM** [comment]
Agreed, this is not stale.

Our self-hosted build agents have 14.5GB of tasks sitting in the work folder.

![WinDirStat view of the top of _w\_tasks](https://github.com/user-attachments/assets/0fab1f45-047f-4391-9f4a-0f74fc25298f)

**Comment by anubi** [comment]
Stale dependencies causes certain security-aware folks to get nervous, so it would be nice if they would get pruned.
