### ISSUE TITLE
What could cause Github events to get lost (not triggering a pipeline when they should)?

### ISSUE THREAD

**Issue by ThijsBroersen** [microsoft/azure-pipelines-agent#4130]
I have seen events in Github not triggering Azure Pipelines. It happens very rarely. I noticed the issue when some required check was stuck on pending: `Expected — Waiting for status to be reported`. There was no Azure Pipeline triggered. Pushing another commit, or closing/opening a PR will trigger the pipeline again. But, of course, it is inconvenient if pipelines are not being triggered when they should. 
I could not find any existing issue describing this problem. Does anyone else have experienced the same? What could cause this? Is the event processing failing on the agent side? Is GitHub perhaps unable to sent the event without retry?

**Comment by DmitriiBobreshev** [comment]
Hi @ThijsBroersen, thank you for the feedback, it's actually a common problem which not related to the Azure Pipelines, but to GitHub, you can try the solution from [this Discussion](https://github.com/orgs/community/discussions/25720) or create a new thread in it if it won't help. Sorry, but we can't help with it.
