### ISSUE TITLE
Support gMSA accounts for setup of agent

### ISSUE THREAD

**Issue by joshcorr** [microsoft/azure-pipelines-agent#4138]
I know support for running the Service under gMSA has been recently added in #3970 

But is there support for installing the agent using a gMSA account? From my attempts it does not appear to be supported. And I cannot find documentation stating it is/is not supported. 

In my test the gMSA is a member of the Build Service Accounts as well as the Build Administrators for testing. I am using the `--auth Negotiate` option. When trying to use only the `--username` it fails without the `--password` option. When I tried to provide a bogus password to `--password` option it fails.

Looking in the Log I see status code 401. And a TFS400813 error code. And it appears it is trying NTLM and not Kerberos (which is what I would expect to see for a gMSA)

Any help much appreciated on this.

**Comment by KonstantinTyukalov** [comment]
Hi @joshcorr, thanks for reporting!

We are currently working on the higher priority issues, but will get back soon.

Could you share [the agent diagnostic logs](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#agent-diagnostic-logs) from the `_diag` agent directory?

You can email this logs here: v-ktyukalov@microsoft.com

**Comment by joshcorr** [comment]
I can see about getting you some logs, but was hoping this would be an easy question to answer. 

It either does or doesn't support GMSA for the specified `--username` switch

**Comment by joshcorr** [comment]
This is not stale. I will be working on getting logs.
