### ISSUE TITLE
VMSS ADO agents are auto upgraded to pre-release version 2.217.2. Error: Docker command not found.

### ISSUE THREAD

**Issue by zaidmohd** [microsoft/azure-pipelines-agent#4149]
Customers VMSS ADO agents were working fine on version 2.214.1. But today morning they were automatically upgraded to pre-release version 2.217.2.
Why the VMSS ADO agents are auto upgraded to pre-release version 2.217.2 ?
This broke all Production Container pipelines with error: "File not found: 'docker'"
Starting: Initialize job
Agent name: 'vmssp283c00005L'
Agent machine name: 'vmssp283c00005L'
Current agent version: '2.217.2'
Agent running as: 'AzDevOps'
Prepare build directory.
Set build variables.
Download all required tasks.
Checking job knob settings.
Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT)
Finished checking job knob settings.##[error]
File not found: 'docker'
Finishing: Initialize job

**Comment by zaidmohd** [comment]
Both the containers resource and bash command failing to check for docker. The OS is:
                        "imageReference": {                            "publisher": "Canonical",                            "offer": "UbuntuServer",                            "sku": "18.04-LTS",                            "version": "latest"                        }

Running Cloud Init:
#cloud-config
package_upgrade: true
packages:  - docker

groups:  - docker

**Comment by ivanduplenskikh** [comment]
Hi @zaidmohd, could you please share pipeline logs in debug mode to take a look? You can retrieve them by following [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#view-and-download-logs) .
To set up debug (verbose) mode - you can use options described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs) .

Could you share these logs and your pipeline definition name with me on my email v-ivandu@microsoft.com.

**Comment by ivanduplenskikh** [comment]
Could you please run `docker version` command on your Azure VM using `Run command` feature
![image](https://user-images.githubusercontent.com/115665590/217225445-1680b7c8-56e5-4fab-a076-87a64a34b03b.png)

**Comment by zaidmohd** [comment]
@ivanduplenskikh : I have shared the details over email.

**Comment by zaidmohd** [comment]
This issue is auto-resolved.
