### ISSUE TITLE
agent doesn't load powershell user module directory

### ISSUE THREAD

**Issue by sharkzor** [microsoft/azure-pipelines-agent#4159]
## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...

2.211.1

OS of the machine running the agent? OSX/Windows/Linux/...

Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?

devops

## What's not working?
Please include error messages and screenshots.

Installing and importing powershell modules.

The var $Env:PSModulePath
Looks like 
C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\;C:\Program Files\Microsoft Monitoring Agent\Agent\AzureAutomation\7.3.1455.1

And is missing the users "\Documents\WindowsPowerShell\Modules"

I had to manually adjust the task and add the folder

$my = [Environment]::GetFolderPath('MyDocuments') + "\WindowsPowerShell\Modules
$Env:PSModulePath = $Env:PSModulePath + ";$my"

**Comment by max-zaytsev** [comment]
@sharkzor is it a [self-hosted](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#install) agent?

**Comment by sharkzor** [comment]
> @sharkzor is it a [self-hosted](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#install) agent?

Yes, selfhosted

**Comment by max-zaytsev** [comment]
> The var $Env:PSModulePath
> Looks like
> C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell;C:\Program Files\Microsoft Monitoring Agent\Agent\AzureAutomation\7.3.1455.1

Did you add "\Documents\WindowsPowerShell\Modules" to PSModulePath before starting the agent?

**Comment by sharkzor** [comment]
> @sharkzor
> 
> > The var $Env:PSModulePath
> > Looks like
> > C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell;C:\Program Files\Microsoft Monitoring Agent\Agent\AzureAutomation\7.3.1455.1
> 
> Did you add "\Documents\WindowsPowerShell\Modules" to PSModulePath before starting the agent?

should be there by default.
when i rdp into the machine with this user, it has the correct path. via the devops agent, somehow this gets mixed up and the mydocuments default path is missing

**Comment by max-zaytsev** [comment]
According to the [documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath?view=powershell-7.3)

> On Windows, the location of the user-specific CurrentUser scope is the $HOME\Documents\PowerShell\Modules folder

Can you check what is the value of the $HOME variable when a pipeline is running? (It seems like in your case $HOME points to C:\Program Files)

Could you also restart the agent (re-start a shell if you use it in the interactive mode or restart the agent service)?

**Comment by sharkzor** [comment]
Hi, was checking $home of our agents, but seems like everything is back to normal. not sure what happened, because i tried restarting, updating the agents etc...
could be some pipeline messed it up, but with lots of teams and lots of pipelines its like finding a needle in a haystack.
