### ISSUE TITLE
Dotnet 6 Migration - add Rocky Linux to supported OS upgrade list

### ISSUE THREAD

**Issue by lumarel** [microsoft/azure-pipelines-agent#4173]
## Description

We have noticed a message on some of our Self-hosted Azure Pipelines Agents (in the Maintenance log):

`##[warning]The operating system the agent is running on is "rocky" (OS name: 9.1), which has not been tested with the .NET 6 based v3 agent. The v2 agent wil not automatically upgrade to the v3 agent. You can manually download the .NET 6 based v3 agent from https://github.com/microsoft/azure-pipelines-agent/releases. See https://aka.ms/azdo-pipeline-agent-version`

Looking at the [support OS list](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#linux), and further on the [best-effort supported OS list](https://github.com/dotnet/core/blob/main/linux-support.md#red-hat-enterprise-linux-family-support) Rocky Linux should be able to upgrade to the v3 version. (I can also see RHEL 9 in #3922, which means there should really not be a problem)

If wanted I can also further test and send a PR for that.

## Agent Version and Platform
Version of your agent? 2.217.2
OS of the machine running the agent? Rocky Linux 9.1

## Azure DevOps Type and Version
dev.azure.com

P.S. If you are already adding Rocky Linux, please also add AlmaLinux for our friends over their.

**Comment by lareeth** [comment]
I have a PR for this raised already here: https://github.com/microsoft/azure-pipelines-agent/pull/4116

**Comment by LiliaSabitova** [comment]
Hi @lareeth thank you for your suggestion!
We will consider adding Rocky Linux 9.1 and AlmaLinux to the list of supported systems after thorough testing v3 Agent on them.

**Comment by lumarel** [comment]
Any updates on this?
Can I provide any information to accelerate the solving of this?

**Comment by lumarel** [comment]
Is there somewhere a test path that has to be taken for Rocky Linux 8 and 9, so I can speed up the merge of the PR to make it supported? (if there would be a difference to RHEL this would be considered a distribution bug)

**Comment by son3ofSatan** [comment]
‫أُرسلت من الـ iPhone‬
