### ISSUE TITLE
[BUG]: --sslskipcertvalidation flag doesn't work on windows machines

### ISSUE THREAD

**Issue by xiafanfan** [microsoft/azure-pipelines-agent#4189]
### What happened?

The same Windows machine can successfully set up self-hosted agent 2.193.0. But will get an SSL verification issue if set up agent v 2.217.2. The same command was used.

In the agent log, the flag is successfully set to true:
![image](https://user-images.githubusercontent.com/45205308/223632355-e7ef05ac-21b9-49dd-b414-374bbf556bbf.png)
It still check the certificate chain.
![image](https://user-images.githubusercontent.com/45205308/223632628-068dbfbe-518b-4603-ac51-757dca508d53.png)

We found that the direct cause is the root certificate of dev.azure.com in the chain is not installed on the server. And it cannot be automatically downloaded due to some connection issue.

By comparing the source code [Comparing releases/2.193.0...releases/2.217.2 · microsoft/azure-pipelines-agent (github.com)](https://github.com/microsoft/azure-pipelines-agent/compare/releases/2.193.0...releases/2.217.2), the new version added steps to validate the certificate.
![image](https://user-images.githubusercontent.com/45205308/223633381-87798708-a08b-4905-81e8-a777266d7117.png)

It appears the SSL cert chain verification can be only bypassed when (OS is not Windows || AZP_AGENT_USE_LEGACY_HTTP is set). But the "--sslskipcertvalidation flag cannot bypass this verification. 
![image](https://user-images.githubusercontent.com/45205308/223633103-9297ec00-8f79-4996-81f3-361ae4ef6e40.png)

### Versions

self-hosted agent 2.217.2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by ChengYen-Tang** [comment]
Is there any way to solve this problem?
