### ISSUE TITLE
[BUG]: Self-hosted (offline server) azure-pipelines-agent is broken

### ISSUE THREAD

**Issue by Supervicto** [microsoft/azure-pipelines-agent#4190]
### What happened?

JobRunner always failed (code 102)

Self-hosted Linux/Windows agents offline server can't fetch "https://raw.githubusercontent.com/microsoft/azure-pipelines-agent/master/src/Agent.Listener/net6.json"

Please remove or skip on exception :
Line 325: `[..] || File.GetLastWriteTimeUtc(supportOSfilePath) < DateTime.UtcNow.AddHours(-1)[...]`

https://github.com/microsoft/azure-pipelines-agent/commit/82f092c913351d71d59b0e18364309148a8fb999

Workaround:
Linux:
`touch net6.json -d '10 years'`
Windows: 
`Set-ItemProperty .\net6.json -Name LastWriteTimeUtc -Value ((Get-ItemProperty .\net6.json).LastWriteTimeUtc).AddYears(10)`

### Versions

azure-pipelines-agent 2.218.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

On-Premise

### Azure DevOps Server Version (if applicable)

2022

### Operation system

RHEL 8.6 / Windows 2019

**Comment by LiliaSabitova** [comment]
Hi @Supervicto thanks for reporting! We'll take a look soon.
