### ISSUE TITLE
[BUG]: FailAgentOnUnsupportedOs contains a broken url

### ISSUE THREAD

**Issue by dfederm** [microsoft/azure-pipelines-agent#4193]
### What happened?

```
  "FailAgentOnUnsupportedOs": "This operating system will stop receiving updates of the Pipelines Agent in the future. To be able to continue to run pipelines please upgrade the operating system or set an environment variable or agent knob \"AGENT_ACKNOWLEDGE_NO_UPDATES\" to \"true\". See https://aka.ms/azdo-pipeline-agent-nosupport for more information.",
```

The link https://aka.ms/azdo-pipeline-agent-nosupport is broken

### Versions

Current

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [X] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by LiliaSabitova** [comment]
Hi @dfederm, thank you for reporting!
We're already working on this, and have a PR: https://github.com/microsoft/azure-pipelines-agent/pull/4196#pullrequestreview-1334552757
