### ISSUE TITLE
[BUG]:  assets.json for release v2.214.2 contains urls for platforms that are not available

### ISSUE THREAD

**Issue by FrankGlez** [microsoft/azure-pipelines-agent#4198]
### What happened?

Attempting to construct the download url for latest non-prerelease agent for win-x64 using the data returned from 'https://api.github.com/repos/microsoft/azure-pipelines-agent/releases'  causes an error because the not all architectures have a release created for the bug-fix. This is inconsistent with the values returned from the assets list for same release: https://github.com/microsoft/azure-pipelines-agent/releases/download/v2.214.2/assets.json

only the urls for RHEL 6 x64 have a file that can be  downloaded
the rest of the urls are entries and lead to an error
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:64e25975-801e-009e-3c70-53c126000000 Time:2023-03-10T16:53:57.0337467Z</Message>
</Error>

non existent files/versions should not be included in the assets.json

### Versions

        "name": "vsts-agent-win-x64-2.214.2.zip",
        "platform": "win-x64",
        "version": "2.214.2",

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Relevant log output

```shell
│   }
│ ': exit status 1. Output: Exception: 
│ Line |
│   15 |      throw $result
│      | 
│ ~~~~~~~~~~~~~
│      |
│ Exception calling "DownloadFile" with "2" argument(s): "The remote
│ server returned an error: (404) Not Found." At
│ C:\Packages\Plugins\Microsoft.CPlat.Core.RunCommandWindows\1.1.15\Downloads\script1.ps1:40
│ char:5 +     $WebClient.DownloadFile($Uri, $agentZip); +
│ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          :
│ NotSpecified: (:) [], ParentContainsErrorRecordException     +
│ FullyQualifiedErrorId : WebException  
│ 
╵
```

**Comment by sergey-koryshev** [comment]
Thank you @FrankGlez, we will take a look at this issue.
