### ISSUE TITLE
Windows ARM64: Add Windows ARM64 builds to release

### ISSUE THREAD

**Issue by kuqin12** [microsoft/azure-pipelines-agent#4206]
### Describe your feature request here

There has been announcement regarding Azure pipelines moving to .NET core, which would support Windows ARM64: https://devblogs.microsoft.com/devops/upgrade-of-net-agent-for-azure-pipelines/.

And I do see that agent releases 3.x were being made available every few weeks. However, there were no official builds for Windows ARM64 along with those 3.x releases.

On the other hand, Windows ARM64 is not included in the planning table from this ticket: https://github.com/microsoft/azure-pipelines-agent/issues/3922. Does this mean that it will not be available in this migration? If not, is this on the roadmap for the upcoming phases? Can we have any ETA on this?

Thanks in advance!

**Comment by avivanoff** [comment]
@sergey-koryshev, is Windows ARM64 still not on the map?
