### ISSUE TITLE
[enhancement]: Run container jobs on self hosted agents

### ISSUE THREAD

**Issue by andyfisher100** [microsoft/azure-pipelines-agent#4208]
Im not sure if this would be more agent or server but it would be nice to be able to run container jobs on Agents running on my own infrastructure, the same way the hosted agents can as documented here https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases

**Comment by kirill-ivlev** [comment]
Hi @andyfisher100, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by Eisklaue** [comment]
I would also agree with this and if we could use job containers on self hosted agents in an AKS. This would reduce the size of our container currently used and increase the security/speed of the pipelines.

**Comment by andyfisher100** [comment]
Didn’t realise it was stale. Can this be reopened

**Comment by andyfisher100** [comment]
@kirill-ivlev can this be reopened please so it keeps some visibility
