### ISSUE TITLE
[BUG]: Errors when accepting auth type in Azure Web Apps for Containers Windows App Service

### ISSUE THREAD

**Issue by dsetlock** [microsoft/azure-pipelines-agent#4210]
### What happened?

When attempting to configure the agent in an Web App for Containers Windows App Service, it fails when attempting to choose an authentication type. The error reads: 

'Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read'

This affects both cmd, and powershell. Installing the agent in -unattended mode may get past the issue but has other issues in my configuration but the log doesn't indicate if it simply timed out, or did not know how to fail gracefully. 

### Versions

Web App for Containers, Windows Docker Container using mcr.microsoft.com/dotnetframework/sdk:4.8-windowsservercore-ltsc2019, agent vsts-agent-win-x64-2.217.2, and vsts-agent-win-x64-2.210.1 .  

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [x] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2020.1

### Version controll system

Git

**Comment by kirill-ivlev** [comment]
Hi @dsetlock , thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.
