### ISSUE TITLE
[enhancement]: Taskmanager code does not parse execution nodehandler's argumentFormat property in task.json

### ISSUE THREAD

**Issue by gitnubster** [microsoft/azure-pipelines-agent#4211]
### Describe your feature request here

I want to make use of the `argumentFormat` property under the task.json - execution - Node[16]. I noticed it is not being processed by the agent's [taskmanager script](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/TaskManager.cs).

The tasks schema json file seems to [allow](https://github.com/microsoft/azure-pipelines-task-lib/blob/2915809e2a7e354b83d3c80ac8889781e2fe1590/tasks.schema.json#L532) it though.

When made possible, I can give arguments to my script instead of using environment variables / inputs in my custom task. And use the args with `process.argv` or so.

So hereby I want to make a feature request.

**Comment by kirill-ivlev** [comment]
Hi @gitnubster,
Thank you for reporting this issue.

Could you please share a bit more context, Do you want to pass arguments to your task directly (not from vars/input)? And  pleas, if it is possible, provide a few scenarios that this approach is more useful than inputs

The main idea of inputs was that it is supported by ADO UI and you can configure it from there, also we are providing some security checks on these inputs.

**Comment by gitnubster** [comment]
Hi @kirill-ivlev,

Thanks for responding. This is my situation where the enhancement would be good to have it:

- Custom (nonpublic) ADO extension; having a dev+prod version. Enabling customizable settings via an admin hub group (like the global message banner extension works) as a UI layer.
- Task under that extension; uses the unique extension id as a key for retrieving the settings stored under an ADO api url.
- Task.json values (like argumentFormat, version, taskname+id) are replaced when building/packing the extension.
- Extension version (=dev or prod) to build+pack+publish is determined by git branch name and a yaml template, not allowing any extra tasks.

Indeed, the obvious way is environment variables or task input variables, but that means more details visible to the user. And overridable (by default).
I don't want to replace hardcoded values in my node task script, nor in my extension hub group script during build/packing the extension.

I know of the azure-devops-extension-sdk npm package having a getExtensionContect().extensionId. I do use that in my hub group script with success, but I cannot get the SDK to work in my node task (window undefined error). I think I understand that now, that the SDK can't work on an agent, different context, not running js in a browser but running js in Node on an agent.

Maybe _I have to_ use the obvious way (and try some hiding and restricting), but then again, there is this property `argumentFormat`, so why not :)

The security/validation part of not having arguments working now on the Node handler I understand. So no argueing on that, it opens possibilities. But the powershell handler does allow argumentFormat, if I read the Taskmanager code correctly.

**Comment by gitnubster** [comment]
@kirill-ivlev. A little abstract without code to share. But I worked around it with a config file, including a tokenreplacement task during the extension build, replacing the necessary value in that config. The extension still uses `getExtensionContext()` part to get the correct key for use in the api url, and the task now uses the config as input. A bit ugly right?

So I'm thinking of rewriting these worked around parts completely by making use of npm run script arguments, as an npm run script task is already in place. And use another keyvalue instead of the extension id. Didn't thought of that before, but to me that looks 'cleaner' than the current workaround with desperately trying to hold onto the extension id. Did that mainly because that variable is available in the pipeline, and the original / bad idea to make use of the sdk in my task script while that is technically not possible.

But I still think it's a nice idea to have the node handler arguments working as expected, that would be the 'cleanest' solution for me.
