### ISSUE TITLE
[BUG]: 'docker' not found in agent version 3.218.0

### ISSUE THREAD

**Issue by MariusGrandeAndersen** [microsoft/azure-pipelines-agent#4219]
### What happened?

##[error]Unhandled: Unable to locate executable file: 'docker'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

2.217.2 agent version build worked ok. Same Docker@2 version as the one that failed: 2.214.0

Our agent pool updated automatically to 3.218.0 today, and my theory is that this is what broke this. 
This is breaking our windows pipelines.

### Versions

Windows-2022 3.218.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 2022

**Comment by ivanduplenskikh** [comment]
Duplicate: https://github.com/microsoft/azure-pipelines-tasks/issues/18039
