### ISSUE TITLE
[BUG]: 3.218.0 still marked pre-release and not appearing as "latest" release

### ISSUE THREAD

**Issue by DirkFoe** [microsoft/azure-pipelines-agent#4221]
### What happened?

dev.azure.com is updating agents to v.3.218.0, but that version is still marked as "Pre-release" here. This makes our security architects nervous ;-) Our Agent 2.217.2 never got updated to the "latest" release 2.218.1, but to 3.218.0 instead.

Also, when you look for the "latest" release, you won't find v3.218.0 but 2.218.1. This breaks a couple of checks on the agent being up-to-date ( https://github.com/microsoft/azure-pipelines-agent/releases/latest  leads to 2.218.1 not 3.218.0, as well as the repo front page is showng v2.218.1 as (latest) even though dev.azure.com obviously thinks that 3.218.0 is (latest).

### Versions

3.218.0, dev.azure.com Self-Hosted / Linux.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

RHEL 7, RHEL 8

**Comment by DirkFoe** [comment]
Thanks for clearing this up (and also for relabeling).

I already knew about the [2 Agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v3-agent?view=azure-devops#what-is-the-timeline-for-agent-version-3-deployment) - that is what brought me here because the auto-update to v3 already started but v3 was still "Pre-Release" here. 
In my opinion, the "Latest" label should have been set to the v3 as soon as the agent update was able to select it. This way it should be easier for everyone: Remaining v2 users are shown they're no longer using the latest version and v3 users don't feel like beta testers ;-)

**Comment by ivanduplenskikh** [comment]
This is not beta testing, just information that not everyone has the latest changes.
I'm closing this issue for now.
If you have additional questions or need further information feel free to reopen it.
