### ISSUE TITLE
[Question]: Can the bundled NodeJS be updated to patch vulnerabilities?

### ISSUE THREAD

**Issue by easkay-castlight** [microsoft/azure-pipelines-agent#4232]
### Describe your question

Similar to #4075, security scanning tools have reported that the version of NodeJS 16 installed with the agent is vulnerable to several CVEs. Could the bundled version of NodeJS 16 please be updated to at least 16.19.1?

EDIT1: I will attempt to submit a PR later today.

### Versions

pipelines-agent-linux-x64-2.218.1 running on Ubuntu 18.04

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 18.04

### Version controll system

Git

### Azure DevOps Server Version (if applicable)

N/A

**Comment by KonstantinTyukalov** [comment]
Hi @easkay-castlight thanks for the reporting! We'll take a look at it
For future security issues you find, please check our policy: https://github.com/microsoft/azure-pipelines-agent/security/policy

thank you

**Comment by KonstantinTyukalov** [comment]
The fix comes with [new agent release](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.220.1).
Once it will be rolled out for all customers, we'll close this issue as resolved.
Thanks!

**Comment by kirill-ivlev** [comment]
@easkay-castlight agent should be available for all customers, please let us know if the issue is not resolved for you.
