### ISSUE TITLE
[enhancement]: Use service principals & managed identities for connection

### ISSUE THREAD

**Issue by clemlesne** [microsoft/azure-pipelines-agent#4233]
### Describe your feature request here

Hello,

Service principals & managed identities support for Azure DevOps SaaS [has been announced few days ago](https://devblogs.microsoft.com/devops/introducing-service-principal-and-managed-identity-support-on-azure-devops). It would awesome to be able to use this to use agents without password or tokens at all.

[See the doc.](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops)

I’m developing [an Helm chart for the agents on Kubernetes](https://github.com/clemlesne/azure-pipelines-agent), this would be a wonderful addition to the project.

**Comment by KonstantinTyukalov** [comment]
Hi @clemlesne thanks for the reporting! We're working on higher priority issues, but we'll get back to this one soon

**Comment by Luckless** [comment]
@KonstantinTyukalov I see you have PR https://github.com/microsoft/azure-pipelines-agent/pull/4255 for the SPs

it's important to note that MI is also greatly needed.

We want to be able to write self-managed agents that register/deregister themselves with no tokens using the user-assigned MI associated to the agent VM

**Comment by clemlesne** [comment]
@Luckless, added the feature (https://github.com/microsoft/azure-pipelines-agent/issues/4544#issue-2014800494), really nice btw.

**Comment by phmcder** [comment]
I am also in need of this
