### ISSUE TITLE
[Question]: How to configure proxy with Azure Pipelines Agent For Linux

### ISSUE THREAD

**Issue by jamesbwilkinson** [microsoft/azure-pipelines-agent#4244]
### Describe your question

I need to use a proxy server to enable outgoing connectivity with the agent. If I install the agent manually and use ./run --proxyurl xxx then all works great. However I would like to use the extension "Azure Pipelines Agent For Linux" but its not clear if I can use a proxy config here, the options at installation do not provide the option to include a proxy. Is there anyway to configure a proxy when using the VM extension? I didn't find anything in the documentation.

### Versions

Ubuntu 22.04 with agent 3.218.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

**Comment by vmapetr** [comment]
Hi @jamesbwilkinson, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by gt97** [comment]
If I understand well the question when you configure the agent you have to use the parameter proxyurl for config.sh:

./config.sh --proxyurl http://xxxxx

If the agent is already installed in the root folder of the agent you can create a file called .proxy with inside one row withe the url of the proxy without reconfiguring the agent

**Comment by jamesbwilkinson** [comment]
Thanks @gt97 for the tip. However if using a scale set, this doesn't work as you can't manually make changes to each vm as they are continually created/destroyed due to demand. It would be helpful to have this option as part of the extension.

**Comment by jamesbwilkinson** [comment]
Still open, not stale.
