### ISSUE TITLE
[Question]: Clarification on usage telemetry

### ISSUE THREAD

**Issue by dominiquehunziker** [microsoft/azure-pipelines-agent#4246]
### Describe your question

Is an agent running in a container in AKS considered a "Docker container", i.e., is the metric supposed to indicate usage of Docker or more generally an agent running in a (Linux) container?

When I run the corresponding shell script I get false for the check for "Docker container". IMO this is because Kubernetes no longer uses Docker as the container engine and, therefore, the check for Docker specific output is not sufficient to check if the agent is being run in a container.

Requested to raise this a separate question here: https://github.com/microsoft/azure-pipelines-agent/pull/4166#issuecomment-1509060590

### Versions

Agent version 3.218.0 / Ubuntu 20.04

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

**Comment by vmapetr** [comment]
Hi @dominiquehunziker, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.
