### ISSUE TITLE
[BUG]: ##vso[artifact.upload artifactname=Test]C:\test.txt truncates file name on upload

### ISSUE THREAD

**Issue by JohnSchmeichel** [microsoft/azure-pipelines-agent#4256]
### What happened?

Using the artifact.upload logging command is lopping off the first character in the file name if the file being uploaded is at the root directory.

```
echo Test > C:\test.txt
echo ##vso[artifact.upload artifactname=Test]C:\test.txt
```
Pipeline logs:
```
Async Command Start: Upload Artifact
Uploading 1 files
Max dedup parallelism: 192
Building file tree
Uploaded 0 out of 7 bytes.
Uploaded 7 out of 7 bytes.
Associating files
Total files: 1 ---- Associated files: 0 (0%)
File upload succeed.
Upload 'C:\test.txt' to file container: '#/24864114/Test'
Associated artifact 67 with build 626559
Async Command End: Upload Artifact
```

Pipeline artifacts:
![image](https://user-images.githubusercontent.com/20784649/234967327-e671a0e5-7caf-4082-8198-6f9e4a745477.png)

### Versions

3.220.0 / Microsoft Windows Server 2022 10.0.20348

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by max-zaytsev** [comment]
@JohnSchmeichel thanks for reporting!
We are working on more prioritized issues at the moment but will get back to this one soon.
