### ISSUE TITLE
[BUG]: No agent found in pool XXX which satisfies the specified demands: azureps, Agent.Version -gtVersion 2.144.0 

### ISSUE THREAD

**Issue by IAMManuel** [microsoft/azure-pipelines-agent#4258]
### What happened?

After our agent upgrade to 3.220.0 we got this error: 

`No agent found in pool XXX which satisfies the specified demands: azureps, Agent.Version -gtVersion 2.144.0 `

But we can see that our agents are up and running with the good version (3.220.0)

![image](https://user-images.githubusercontent.com/2425292/235509755-fc2b08cb-d77e-478b-a4f4-55a6a473bb44.png)

### Versions

Agent version 3.220.0 / Windows 10

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 10

### Version controll system

git

### Relevant log output

```shell
##[Error 1]
No agent found in pool XXX which satisfies the specified demands: azureps, Agent.Version -gtVersion 2.144.0
```

**Comment by theuntested** [comment]
How didi you solve this? John

**Comment by miksch123** [comment]
There is the high probablility that if you do not use the agent version you get when you want to add an additional agent (the prompt that appears with the download link and the information to extract the zip and run the config.cmd), you may run into this issue.
