### ISSUE TITLE
[BUG]: DISABLE_NODE6_DEPRECATION_WARNING is on by default

### ISSUE THREAD

**Issue by JoostVoskuil** [microsoft/azure-pipelines-agent#4261]
### What happened?

In PR https://github.com/microsoft/azure-pipelines-agent/pull/3650/commits/42e8eec1ac3c2a6714e6577debfbbcf7d048c721 the knob DISABLE_NODE6_DEPRECATION_WARNING is turned on by default.

Now there is no warning anymore when tasks are using Node6. Why is this? Why is this approved and isn't it better when it is default is turned on?

Because of the deprecation of node6 tasks I would expect that this is turned OFF! (so users will see warnings)

### Versions

latest

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [X] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by DenisRumyantsev** [comment]
@JoostVoskuil thanks for reporting this! We will take a look if we can turn off this knob by default.

**Comment by Drgwari** [comment]
DON'T DISABLED NODE6 DEPRECATION_WARNING
default (ISSUE #4261)

**Comment by JoostVoskuil** [comment]
Any updates on this?
