### ISSUE TITLE
[Question]: Microsoft hosted agent connection ETIMEDOUT

### ISSUE THREAD

**Issue by MaryanneNjeri** [microsoft/azure-pipelines-agent#4266]
### Describe your question

When using the Microsoft hosted agents to run a long operation, like pushing multiple configurations with the Azure App configuration Push task, the task fails after running for like 1min with the error
"FetchError: request to [URL] failed, reason: connect ETIMEDOUT [IP ADDRESS]"

**Note** This only happens in Microsoft-hosted agents even after increasing the timeoutInMins to 40mins, on self-hosted agents this task succeeds. This only happens when running long-running operations, otherwise, it works fine.

I was wondering why this only happens in Microsoft-hosted agents and not in self-hosted agents. I've seen similar issues 
https://developercommunity.visualstudio.com/t/azure-pipeline-is-failing-intermittently-with-erro/1076388
https://stackoverflow.com/questions/66396936/newman-cli-on-azure-devops-throwing-connect-etimedout

Kindy advise
### Versions

Windows latest

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by ismayilov-ismayil** [comment]
Hi @MaryanneNjeri, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
