### ISSUE TITLE
Remove OpenSSL 1.x dependency for Agent 3.x

### ISSUE THREAD

**Issue by MichelZ** [microsoft/azure-pipelines-agent#4267]
It seems that the installdependencies.sh script still installs libssl1.x (at least on Ubuntu 22.04) (see comment below)

The script should be adjusted to use the latest supported version of OpenSSL now that agent is .NET6.

See https://github.com/microsoft/azure-pipelines-agent/issues/3922#issuecomment-1464875424 for details.

**Comment by ismayilov-ismayil** [comment]
Hi @MichelZ, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by DmitriiBobreshev** [comment]
Starting [3.225.](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.225.0)0 all scripts are capable with libssl.

Closing this issue
