### ISSUE TITLE
[BUG]: persistCredentials should apply to submodules

### ISSUE THREAD

**Issue by mquilling** [microsoft/azure-pipelines-agent#4295]
### What happened?

The git config `http.extraHeader` is only set for the base repository. e.g.
```
git config --get http.https://scm/org/repo.extraheader
```
when submodules are present the authentication need to be explicitly provided otherwise you end up getting 
```
fatal: could not read Username for 'https://scm/': terminal prompts disabled
```
the solution was to use
```
-c http.extraHeader="$(git config --get http.https://scm/org/repo.extraheader)"
```
or set this value in the config for each submodule repo...which is my preference to have this done by the agent.

### Versions

```
Current agent version: '3.220.2'
```

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by ivanduplenskikh** [comment]
Hi @mquilling thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
