### ISSUE TITLE
[Question]: Are some directories slower to access than others?

### ISSUE THREAD

**Issue by craigbrown** [microsoft/azure-pipelines-agent#4296]
### Describe your question

I'm seeing some odd patterns with our pipeline, which runs on a Windows hosted agent.

The `dotnet restore` step (which runs in <2s on my machine) will vary wildly in how long it takes to run on the agent - from 10s anywhere up to 3mins. This step uses the version of .NET installed at `C:\Program Files\dotnet\dotnet.exe`.

When I add a UseDotNet task with `installationPath: '$(Pipeline.Workspace)/dotnet'`, so that the restore step will use the path `D:\a\1\dotnet\dotnet.exe`, it's much more consistent - taking around 10s.

I am using a Cache task to get the cached nuget packages before running the restore task. As part of adding this step, I added a `NUGET_PACKAGES` environment variable, and set this to also be in the `$(Pipeline.Workspace)` i.e. on the D:\ drive instead of the default location on the C:\ drive. When I did this I noticed a performance improvement even when I took the Cache task away.

All this is adding up to a pattern - **is the C:\ drive slower than the D:\ drive?**

It's possible this is all just a fluke and I'm just happening to see quicker runs by coincidence when taking the C:\ drive out of the equation. But I feel like I'm seeing enough of a pattern that it's worth asking the question.

### Versions

Current agent version: '3.220.2'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20230508.3
  Included Software: https://github.com/actions/runner-images/blob/win22/20230508.3/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230508.3
Runner Image Provisioner
  2.0.171.1
Current image version: '20230508.3'

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by ivanduplenskikh** [comment]
Hi @craigbrown thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by craigbrown** [comment]
Not stale.
