### ISSUE TITLE
[enhancement]: Support `win-arm64` runtime

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/azure-pipelines-agent#4303]
### Describe your feature request here

I understand that the limiting factor for running on Windows on ARM is the [external dependencies][1], so I thought it would be a good idea to track the status of those dependencies. They are:

- [ ] Node
	- https://github.com/nodejs/build/issues/2540
	- Available from Node 20
	- Related #4240
- [ ] git
	- https://github.com/git-for-windows/git/issues/3107
	- This is more-or-less complete
	- Unofficial builds available https://github.com/dennisameling/git/releases
- [ ] git LFS
	- Available from v3.0.1
	- https://github.com/git-lfs/git-lfs/releases/tag/v3.0.1
- [ ] NuGet
- [ ] azcopy
- [ ] pdbstr
	- Looks like this is bundled from the Windows SDK?
- [ ] symstore
- [ ] vstsom
- [ ] vswhere

[1]: https://github.com/microsoft/azure-pipelines-agent/blob/08c5ddf9006bf44f63b47c54dc2157039a656699/src/Misc/externals.sh#L145-L182

**Comment by kirill-ivlev** [comment]
Hi @JamieMagee,
Thank you for raising this issue, right now we don't have plans to support ARM64 on Windows in the near future. We will keep this item to track any progress related to Windows ARM64 support.

**Comment by billti** [comment]
I'm struggling to understand the story here. The docs at https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v3-agent?view=azure-devops state (emphasis mine) "The new agent version supports new Apple silicon hardware and newer operating systems like Ubuntu 22.04, or **Windows on ARM64**"

Above you state "we don't have plans to support ARM64 on Windows in the near future"

I'm trying to build Python wheels for Windows on ARM64 in our DevOps pipeline, so any guidance on if this is possible and clarity on the DevOps support appreciated.

**Comment by JamieMagee** [comment]
This is not stale.

**Comment by kuqin12** [comment]
> I'm struggling to understand the story here. The docs at https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v3-agent?view=azure-devops state (emphasis mine) "The new agent version supports new Apple silicon hardware and newer operating systems like Ubuntu 22.04, or **Windows on ARM64**"
> 
> Above you state "we don't have plans to support ARM64 on Windows in the near future"
> 
> I'm trying to build Python wheels for Windows on ARM64 in our DevOps pipeline, so any guidance on if this is possible and clarity on the DevOps support appreciated.

Same here. But our issue occurs during installing the wheels, the step will trigger the host to prompt errors like below and fail that step:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/42554914/29785537-e3d6-474f-a56a-e0743c68efdf)
![image](https://github.com/microsoft/azure-pipelines-agent/assets/42554914/159f9667-70e3-4b73-8e89-48db848bda25)

The pipeline used is here: https://github.com/microsoft/mu_devops/blob/c95e8e584e65dfc827968b866474d6c999d970dd/Steps/SetupPythonPreReqs.yml#L30

Any guidance on how to fix this issue?

**Comment by HarryGwinnell** [comment]
Any chance this has been revisited and plans to support it added @kirill-ivlev ?

At Build we announced further Windows new ARM64 powered hardware, including new Azure SKUs (https://techcommunity.microsoft.com/t5/azure-compute-blog/announcing-the-preview-of-new-azure-vms-based-on-the-azure/ba-p/4146353) which we'd love to use for ADO agents.

**Comment by RuneH-MSFT** [comment]
@kirill-ivlev - Having the Microsoft.VisualStudio.Services.TeamServicesAgent extension support Windows on ARM64 is very important for being able to introduce ARM64 support in other tools and services. Without having the ability to run Azure DevOps pipelines on Windows for ARM64 VMs, we will not be able to have a functional engineer system to introduce support for Windows on ARM64 in other services.

**Comment by AdityaMankal-MS** [comment]
Hello @RuneH-MSFT, @JamieMagee, @HarryGwinnell, @kuqin12, @billti,

Thank you for your interest in Agents for Windows ARM-64. We’ve just begun development and will be releasing it soon.
