### ISSUE TITLE
[enhancement]: red hat 8 and 9? 

### ISSUE THREAD

**Issue by ozbillwang** [microsoft/azure-pipelines-agent#4305]
### Describe your feature request here

Read the documents in this report, seems the agent currently only supports to red hat 7.2, any plans for red hat 8 or 9?

**Comment by kirill-ivlev** [comment]
@ozbillwang thank you for your question.
We support RedHat 8 & 9 as well, 7.2 is a minimal requirement
You can find all supported Linux distro here: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/linux-agent?view=azure-devops

Please let me know if you have any additional questions.

**Comment by ozbillwang** [comment]
Not really.

Here are the test logs:

1. confirm I am running the command in rhel 8

```
 cat /etc/*release
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
```
2. when run the script `enableagent.sh`, I got the error that  `apt: command not found`, which `apt` is only in Ubuntu/debian

```
$  bash ./enableagent.sh "$AZP_URL" "$AZP_POOL" "$AZP_TOKEN"

...
Installed:
  lttng-ust-2.8.1-11.el8.x86_64                                                                     userspace-rcu-0.10.1-4.el8.x86_64                                                                    

Complete!
-----------------------------
 Finish Install Dependencies
-----------------------------
./enableagent.sh: line 60: apt: command not found
configuring build agent

  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v3.220.2             |_|          (commit d68a74b)
```

**Comment by ozbillwang** [comment]
seems this issue can be ignored, and add a follow up command `sudo yum install -y at` to make sure `at` command is installed

**Comment by kirill-ivlev** [comment]
@ozbillwang  you can also install all required dependencies by invoking installdependencies.sh (shipped with the agent)
