### ISSUE TITLE
Trying to use the API to trigger an auto-update of the agent

### ISSUE THREAD

**Issue by blakeduffey** [microsoft/azure-pipelines-agent#4306]
### Describe your question

On Azure Devops Server 2019, I could copy the updated agent to %ProgramData%\Microsoft\Azure DevOps\Agents and then issue an 'update agent'.

This folder does not exist on Azure Devops Server 2022 - so I'm trying to update it via the API.

I issue the command, and agent 'current status' changes to

`Sent agent update message.  Agent will auto-update shortly.`

It stays that way for a couple minutes and then returns to 'idle'.

But the version remains 3.218.0.

### Versions

Version Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20230418.1)
Windows 2022 server

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

Windows 2022

### Azure DevOps Server Version (if applicable)

Version Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20230418.1)

**Comment by DmitriiBobreshev** [comment]
Hi @blakeduffey, thank you for the feedback! If you're trying to update an agent using this [API](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#how-can-i-trigger-agent-updates-programmatically-for-specific-agent-pool) it's still looking for the files inside %ProgramData%\Microsoft\Azure DevOps\Agents(in cases when you don't have internet access) and just triggers the pretty same logic as when you updating it via GUI in AzureDevops Server. 

In your case if the folder doesn't exist you can just create it manually, the check is case-sensitive so be careful when creating it. After that, you can update the agents as you did in ADO Server 2019.

**Comment by blakeduffey** [comment]
Perfect!  Thanks so much.
