### ISSUE TITLE
[Question]: How to set a runtime Knob for a specific pipeline

### ISSUE THREAD

**Issue by afscrome** [microsoft/azure-pipelines-agent#4317]
### Describe your question

Certain setup failures in webdriver cause some of our test runs to hit https://github.com/microsoft/azure-pipelines-tasks/issues/17548 .  The dotnet test process finishes, but the dotnet test step in ado hangs until the task is canceled, or the job hits the 60 second timeout.

A suggestion has been to set the `VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT` knob, however I don't see how to do that on the hosted agent pools.  Attempting to set the variable `VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT` in the yaml pipeline results in the pipeline to refeuse to schedule with an error

![image](https://github.com/microsoft/azure-pipelines-agent/assets/289860/805146ca-04d6-48e7-af52-7b2bdc834a3a)

In looking at the code, the knob has a `RuntimeKnobSource` and I can also see in the "Initalise Job" phase it loads the knob, which together I'd assume means it is expected this knob could be set on a per job basis.  How do I override this for a single job.  (The pipeline is running against the `ubunut-latest` hosted agent, although I experience the same issue pointing this to a self hosted agent).

Logs from the `DotNetCoreCLI@2` task for which I'm trying to use this knob to fix.

```
...
Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration:  - /home/vsts/work/1/Foo/Bar.dll (net6.0)
```
HANG - the next set of logs don't show up until the job times out, or is explicitly cancelled

```
The STDIO streams did not close within 10 seconds of the exit event from process '/usr/bin/dotnet'. This may indicate a child process inherited the STDIO streams and has not yet exited.
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : [ '' ]
##[error]The operation was canceled.
```

### Versions

Agent: 3.220.5

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

**Comment by DmitriiBobreshev** [comment]
Hi @afscrome, thank you for the question, you could set the knob using UI with [User-defined capabilities](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#manually-entered-agent-demands) for hosted agents.
![image](https://github.com/microsoft/azure-pipelines-agent/assets/106314398/6dafca41-eb1d-4016-a2bd-56ccede18dc6)
Just click on the plus button and add VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT.

![image](https://github.com/microsoft/azure-pipelines-agent/assets/106314398/73fcf008-3719-48f6-8a91-9e4eb744c2be)

**Comment by msherms2** [comment]
I know this is closed but just in case someone finds this, adding a user variable did not work for me. I use YAML pipelines from Azure DevOps and it worked when I set the variable in my YAML. If i set it with a user defined one as shown above, I did not see the entry listed in the job knob settings.
