### ISSUE TITLE
[enhancement]: Support Sparse Checkout

### ISSUE THREAD

**Issue by bdovaz** [microsoft/azure-pipelines-agent#4325]
### Describe your feature request here

For monorepo repositories this is a must to be able to speed up builds as much as possible.

I see that this very thing has been recently merged by @dscho into the GitHub checkout action: https://github.com/actions/checkout/pull/1369

Would this same functionality be possible in azure pipelines?

Thanks!

**Comment by KonstantinTyukalov** [comment]
Hi @bdovaz thanks for the reporting! We're currently working on higher priority issues, but we'll get back this this one soon.

**Comment by dscho** [comment]
Note that the `actions/checkout` PR relies on partial clones to be supported server-side, something that Azure Repos could only do via emulation using the GVFS protocol (which so far is only supported using Microsoft's Git fork, which is not installed on the build agents by default).

**Comment by bdovaz** [comment]
No stale

**Comment by dscho** [comment]
> Note that the `actions/checkout` PR relies on partial clones to be supported server-side, something that Azure Repos could only do via emulation using the GVFS protocol (which so far is only supported using Microsoft's Git fork, which is not installed on the build agents by default).

Note that [partial clones are now supported by Azure Repos](https://devblogs.microsoft.com/devops/git-partial-clone-now-supported-in-azure-devops/)!

**Comment by bdovaz** [comment]
Although it is an improvement, it has nothing to do with the purpose of this issue.

The big improvement would be that at a high level through the `checkout` task we can make a `sparse checkout` indicating the directories to include as you can do in Github from your PR from half a year ago.

**Comment by sanghel-orbyta** [comment]
any way to bump priority on this one?

monorepos consume agent time uselessly doing full checkouts...

**Comment by ToreDemant** [comment]
Seems to be related to these:
https://developercommunity.visualstudio.com/t/Sparse-Checkout--Partial-Clone-for-nati/10607236
https://developercommunity.visualstudio.com/t/Support-Gits-sparse-checkout-in-the-Azu/10472337

**Comment by Khayoann2** [comment]
I proposed this one 
https://developercommunity.visualstudio.com/t/Sparse-Checkout--Partial-Clone-for-nati/10607236
So i’m also waiting this feature …
Please 🙏

**Comment by mggrand** [comment]
If anyone is interested, I wrote the sparse checkout as a template, which can then be used as follows:
```
- template: sparse-checkout.yml
    parameters:
      folders:
        - frontend
        - resources
```
with the template `sparse-checkout.yml`
```
parameters:
  - name: folders
    type: object
    default:

  - name: fetchLfs
    type: boolean
    default: true

  - name: persistCredentials
    type: boolean
    default: false

steps:
  - checkout: none
  - pwsh: |
      function Start-Group($name){ Write-Host "##[group]$name"}
      function End-Group { Write-Host "##[endgroup]"}

      function Run-Cmd($command){
          Write-Host "##[command]$command"
          Invoke-Expression $command
      }


      $folders = "${{ join(' ',parameters.folders) }}"
      $repositoryUri = "$(Build.Repository.Uri)"
      Write-Host "Sync repository folders '$folders' to '$pwd'"
            
      Start-Group "Getting git version info"
      Run-Cmd "git version"
      Run-Cmd "git lfs version"
      End-Group

      if(Test-Path ".git"){
        Start-Group "Cleanup existing repository"
        # Existing directory
        $null = Remove-Item ".git/index.lock" -Force -ErrorAction SilentlyContinue
        $null = Remove-Item ".git/shallow.lock" -Force -ErrorAction SilentlyContinue

        $currentRemote = Run-Cmd "git remote get-url origin"
        if($currentRemote -ne $repositoryUri){
            Write-Host "Current fetch url: $currentRemote"
            Write-Host "New repository fetch url: $repositoryUri"
            Write-Host "##[warning]Fetch urls do not match. Clean the whole directory"
            $null = Remove-Item ./* -Force -Recurse
        }
        else{
            Run-Cmd "git remote remove origin"
            Run-Cmd "git clean -ffxd"
            Run-Cmd "git reset --hard"
        }
        End-Group
      }

      Start-Group "Initialize the repository"
      Run-Cmd "git init"
      Run-Cmd "git sparse-checkout init --cone"
      if($folders.Length -gt 1){
        Run-Cmd "git sparse-checkout add $folders"
      } else {
        Write-Host "No folders were provided for the sparse checkout"
      }
      Run-Cmd "git lfs install --local"
      End-Group

      Start-Group "Configure the repository"
      Run-Cmd "git remote add origin $repositoryUri"
      Run-Cmd "git config core.sparsecheckout true"
      Run-Cmd "git config gc.auto 0"
      Run-Cmd "git config --get-all http.$($repositoryUri).extraheader"
      Run-Cmd "git config --get-all http.proxy"
      Run-Cmd "git config http.version HTTP/1.1"
      End-Group


      Start-Group "Fetching the repository"
      Run-Cmd "git --config-env=http.extraheader=env_var_http_extraheader fetch --force --no-tags --progress --prune --no-recurse-submodules --verbose --depth=1 origin +$(Build.SourceVersion):refs/remotes/origin/$(Build.SourceVersion)"
      if("${{ parameters.fetchLfs }}" -eq "true"){
        Run-Cmd "git --config-env=http.extraheader=env_var_http_extraheader lfs fetch origin refs/remotes/origin/$(Build.SourceVersion)"
      } else {
        Write-Host "Skipping lfs fetch"
      }
      End-Group


      Start-Group "Checkout the repository"
      Run-Cmd "git checkout --force --progress refs/remotes/origin/$(Build.SourceVersion)"
      End-Group

      if("${{ parameters.persistCredentials }}" -eq "true"){
        Start-Group "Persist credentials in the repository"
        Run-Cmd "git config http.$($repositoryUri).extraheader `"$($env:env_var_http_extraheader)`""
        End-Group
      }

      if("$($env:env_var_vsts_debug)" -eq "true"){ 
        Start-Group "Print directory outputs"
        Run-Cmd "Get-ChildItem -Recurse"
        End-Group
      }

    displayName: "Clone partial git repo"
    env:
      env_var_http_extraheader: "AUTHORIZATION: bearer $(System.AccessToken)"
      env_var_vsts_debug: $[eq(variables['System.Debug'], true)]

```

**Comment by bdovaz** [comment]
https://developercommunity.visualstudio.com/t/Support-Gits-sparse-checkout-in-the-Azu/10472337#T-N10776291

**Comment by bdovaz** [comment]
Added in https://github.com/microsoft/azure-pipelines-agent/pull/5015 and will be in release [v3.247.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.247.1)

Closing...

**Comment by bdovaz** [comment]
There is no documentation for this feature yet?

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines

cc @jnilau @merlynomsft

**Comment by PaulVrugt** [comment]
docs would be really helpful

**Comment by jnilau** [comment]
@bdovaz documentation is out of my hands but it is in the works

**Comment by jnilau** [comment]
@PaulVrugt there was a holiday deployment freeze but it has ended now and we will be continuing rollout on the ADO side

**Comment by baterja** [comment]
It's good to finally have it! I'm still waiting until it's documented before I show it to my teams. Is there an issue (or anything else that may be tracked) on the docs side?

**Comment by PaulVrugt** [comment]
I just logged issue https://github.com/microsoft/azure-pipelines-agent/issues/5113 @bdovaz

**Comment by arielmoraes** [comment]
How to set the agent knob when using the managed agent?

**Comment by arielmoraes** [comment]
@ChristopherHX  yes, I've tried that, but it seems we can't change system variables:

> Cannot override system variable 'AGENT_USE_SPARSE_CHECKOUT_IN_CHECKOUT_TASK'

**Comment by arielmoraes** [comment]
@ChristopherHX yes I'm using the variables block, are you using a Microsoft hosted agent or self hosted?

**Comment by arielmoraes** [comment]
I don't know how you are managing to change the variable because the documentation clearly states Predefined variables are readonly and can't be changed, with the exception of Build.Clean and System.Debug.

https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
