### ISSUE TITLE
[Question]: Agent Update available? Version 3.220.2 agent doesn't find new Version 3.220.5 ?

### ISSUE THREAD

**Issue by MichelZ** [microsoft/azure-pipelines-agent#4329]
### Describe your question

We are currently running self-hosted Agent Version `3.220.2`, but it seems that `3.220.5` is released (says 3 weeks ago) - Online agents seem to have the new version installed.

Yet, when I click `Update all agents`, it says `Sent agent update message. Agent will auto-update shortly`, but the message just stays there.

The agent log says:
>[2023-06-23 14:16:05Z INFO Agent] Refresh message received, kick-off selfupdate background process.
>[2023-06-23 14:16:05Z INFO SelfUpdater] Version '2.218.1' of 'agent' package available in server.
>[2023-06-23 14:16:05Z INFO SelfUpdater] Current running agent version is 3.220.2
>[2023-06-23 14:16:05Z INFO SelfUpdater] We don't downgrade agent from 3.* to 2.*, skipping update
>[2023-06-23 14:16:05Z INFO SelfUpdater] Can't find available update package.
>[2023-06-23 14:16:06Z INFO Agent] Auto update task finished at backend, there is no available agent update needs to apply, continue message queue looping.

So it seems there is no new version available?
Is there any way to check the latest version available on the service itself?

### Versions

3.220.2, Windows 10 22H2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Version controll system

Git

**Comment by cremor** [comment]
Duplicate of #4321

**Comment by max-zaytsev** [comment]
@MichelZ can you please try updating the agent? It should be fixed now

**Comment by MichelZ** [comment]
@max-zaytsev That seems to work across Windows and Linux agents, yep! Thanks
