### ISSUE TITLE
[BUG]: Granting permissions to AzDevOps account is not robust in VMSS scenario

### ISSUE THREAD

**Issue by ianjirka** [microsoft/azure-pipelines-agent#4336]
### What happened?

# Scenario

I have configured my VMSS agents to have the work directory be on the temp/resource disk.  I did this by configuring the agent as such via the CustomScript extension

```bash
mkdir -p /mnt/agent/_work
echo VSTS_AGENT_INPUT_WORK=/mnt/agent/_work >> /etc/environment
```

## Expected

I expected the agent be able to write to this location, but it cannot.  

## Workaround 1 (unsuccessful)

My first attempt, following the instructions [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-a-scale-set-with-custom-image-software-or-disk-size) which suggests:
 > you can create a user named AzDevOps, and grant that user the permissions you require. This user will be created by the scaleset agent startup script if it doesn't already exist.

```bash
useradd AzDevOps
chown -R AzDevOps:AzDevOps /mnt/agent
chmod -R 775 /mnt/agent
```

The problem is, using this methodology, the `enableagent.sh` script fails to apply other permissions to the user.  Specifically, the docker group.  This is because the script looks for the presence of the user and, if found, doesn't do any configuration of the user at all.  This means the documented solution cannot work.

## Workaround 2  (successful but fragile)

To work around fully, I need to copy script details from `enableagent.sh` into my script, which now looks like this:

```bash
useradd -m AzDevOps
usermod -a -G docker AzDevOps
usermod -a -G adm AzDevOps
usermod -a -G sudo AzDevOps

chmod -R +r /home
setfacl -Rdm "u:AzDevOps:rwX" /home
setfacl -Rb /home/AzDevOps
echo 'AzDevOps ALL=NOPASSWD: ALL' >> /etc/sudoers

chown -R AzDevOps:AzDevOps /mnt/agent
chmod -R 775 /mnt/agent
```

Any future changes can easily break my VMSS now.

## Suggestion:
- Allow me to provide a script that runs after enableagent.sh, so I can add only my relevant configuration after the AzDevOps user is created.  This is robust for other scenarios.
- If VSTS_AGENT_INPUT_WORK is present, have enableagent.sh create the directories and permissions it needs when it creates the AzDevOps user.  Probably a simpler change but narrower in impact as well.

### Versions

Azure Pipelines VMSS Agent/latest version
Ubuntu 2022.04 LTS

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by kirill-ivlev** [comment]
Hi @ianjirka,
Thank you for the feature suggestion, right now we are working on more prioritized tickets, and will come back soon.

**Comment by odegroot** [comment]
I would also like a reliable way of configuring the `AzDevOps` user profile to be ready for jobs.

In my case, that means marking the 'PSGallery' package-repo as trusted (`Set-PSResourceRepository -Name 'PSGallery' -Trusted`), which can only be done for the current user. Since the CustomScript extension runs _before_ the `AzDevOps` user exists, it cannot do that. (With the nuances as described above)
