### ISSUE TITLE
[BUG]: The enableservicesidtypeunrestricted flag is not documented

### ISSUE THREAD

**Issue by aledeniz** [microsoft/azure-pipelines-agent#4342]
### What happened?

The enableservicesidtypeunrestricted flag is not documented.
I had to read the source code to figure out it existed.

### Versions

3.220.5, but I noticed this also in previous versions.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Relevant log output

```shell
.\config.cmd --help doesn't list enableservicesidtypeunrestricted anywhere. 
I have Googled Microsoft Learn for that, I didn't got any hit either.
```

**Comment by DenisRumyantsev** [comment]
Hi, @aledeniz thanks for reporting!
We will consider how we can improve our docs and add a description for this flag.
