### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by austinmfb** [microsoft/azure-pipelines-agent#4351]
### Describe your question

Trying to identify what agent version is required to run yaml pipelines. Seems like ours is too old, but I can't find documentation to confirm.

### Versions

Azure DevOps version 2.122.1 Windows_NT version 10.0.14393

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Version controll system

git

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2020 Update 1.2

**Comment by ismayilov-ismayil** [comment]
Hi @austinmfb, in terms of new feature and security issues it is worth to upgrade your agent to the latest version.
