### ISSUE TITLE
Tasks and tool folder caching

### ISSUE THREAD

**Issue by taktakpeops** [microsoft/azure-pipelines-agent#4365]
### Describe your feature request here

Hello,

We are currently running the Azure DevOps runners in our own infrastructure using Kubernetes. 

Our runners are ephemeral, therefore, every time a job completes, the runner is killed and a new one starts. 

To optimize the time it takes to run 1 job, we decided to implement some caching logic for the _tasks and _tool folders in the _work directory.

Our current strategy makes use of rsync for Linux and Robocopy for Windows in order to populate the 2 folders before starting the agent and at the end of the agent process to retrofit any modifications to our persistent storage.

In the ADO runners documentation, there is a section suggesting to cache the tools but nothing about the tasks even if it seems to be working based on our testing.

However, even if we can choose a shared folder for the tools, it seems that tasks such as UseDotNet aren’t handling concurrent write (currently it uses the cp command from ShellJS). Same issue happens with the download of the tasks when the job is in the init phase.

Would it be possible to add concurrent write support for both use cases to allow us to simply mount our caching volume rather than doing the rsync / robocopy at the beginning and at the end of the job?

**Comment by aleksandrlevochkin** [comment]
Hi @taktakpeops! Thank you for your question.
We are currently working on higher-priority issues, but we will get back to this one as soon as we can.

**Comment by taktakpeops** [comment]
Hello @aleksandrlevochkin - any update regarding this feature request?
