### ISSUE TITLE
[Question]: Self-hosted Linux Docker image sqlpackage capability

### ISSUE THREAD

**Issue by Eonasdan** [microsoft/azure-pipelines-agent#4368]
### Describe your question

I am attempting to get `sqlpackage` to be registered as a capability in a self-hosted Ubuntu docker image. I've installed the package via the dotnet cli. However, it doesn't show as a capability and the pipeline fails because it's missing.

![image](https://github.com/microsoft/azure-pipelines-agent/assets/1006516/bb4fbdf6-1288-4f79-a0c6-5e2a498499f5)

<details>
<summary>Dockerfile</summary>

```yaml

FROM mcr.microsoft.com/powershell:lts-ubuntu-22.04
RUN apt-get update \
    && apt-get install --no-install-recommends \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    git \
    iputils-ping \
    jq \
    lsb-release \
    software-properties-common \
    dotnet-sdk-7.0 \
    dotnet-sdk-6.0 \
    unzip \
    wget

RUN dotnet tool install -g microsoft.sqlpackage
ENV PATH="$PATH:/root/.dotnet/tools"
```

</details>

### Versions

Agent: 3.220.5
OS: Ubuntu 22.04

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

**Comment by aleksandrlevochkin** [comment]
Hi @Eonasdan thank you for your question! Please check with the [SqlPackage documentation](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-pipelines?view=sql-server-ver16) to verify that the utility has been installed correctly. Also make sure to restart the agent after adding a new capability to pick up the changes.

**Comment by Eonasdan** [comment]
I think I solved this by doing this instead:

```dockerfile
# Install sql package
RUN curl -Lo sqlpackage.zip https://aka.ms/sqlpackage-linux \
    && unzip sqlpackage.zip -d /opt/sqlpackage \
    && chmod +x /opt/sqlpackage/sqlpackage \
    && rm /sqlpackage.zip
ENV SqlPackage=/opt/sqlpackage/sqlpackage # this seems to be the correct way of making the capability show up
```

I'm running in to other unrelated issues, so I can't completely confirm that it's working

**Comment by Roman-Konstantinov** [comment]
Hello @Eonasdan,

Did you find the solution for the issue?

**Comment by Eonasdan** [comment]
Hi @Roman-Konstantinov. Yes, I belive my comment above was what made that work. Just make sure that the path is the same:

```dockerfile
# Install sql package
RUN curl -Lo sqlpackage.zip https://aka.ms/sqlpackage-linux \
    && unzip sqlpackage.zip -d /opt/sqlpackage \ <--- this path
    && chmod +x /opt/sqlpackage/sqlpackage \ <--- this path
    && rm /sqlpackage.zip
ENV SqlPackage=/opt/sqlpackage/sqlpackage <--- this path
```

(remove `<--- this path` from the above or you will get errors)
