### ISSUE TITLE
[BUG]: agent capabilities doesn't work in pipeline

### ISSUE THREAD

**Issue by Shahyads** [microsoft/azure-pipelines-agent#4369]
### What happened?

We are using Azure DevOps Server 2022.0.1
Agent version 3.220.5 and 2.217.2 and 2.190.0

On the agent there is an agent capability VisualStudio_IDE equals C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE
It is detected by the agent. I don't have any environment variable on the pipeline agent host machine.

In a build pipeline I have a variable TFSSecurityFullPath equals $(VisualStudio_IDE)\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TFSSecurity.exe
It doesn’t calculate the value correctly. It seems the agent capabilities are not passed to the pipeline as a variable.

### Versions

I tested it on Agent version 3.220.5 and 2.217.2 and 2.190.0
Azure DevOps Server 2020 update 1 and azure devops server 2022.0.1

### Environment type (Please select at least one environment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2022.0.1

### Operation system

Windows Server 2019

### Version control system

TFVC

**Comment by LiliaSabitova** [comment]
Hi @Shahyads, , thanks for reporting.
Could you please provide pipeline debug & diagnostic logs? You can retrieve them by following [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#view-and-download-logs). You should also set up 'Agent.Diagnostic' pipeline variable as 'true' before pipeline run.
And could you please also provide your pipeline's yaml file.
For security reasons you can share logs and files to my mailbox: [v-lisabitova@microsoft.com](mailto:v-lisabitova@microsoft.com)

**Comment by Shahyads** [comment]
Hi @LiliaSabitova 
the pipeline that i've tested is Classic. it is not a YAML pipeline 
to reproduce the issue you can simply 
1- Create a pipeline 
2- Add command line task to echo $(Agent.ComputerName)
3- run the pipeline
4- in the output log you cannot see the value of Agent.ComputerName
you can try it with any other agent capabilities like $(Java) etc.

**Comment by Shahyads** [comment]
Hi @LiliaSabitova  
I found this extension [Agent Capabilities](https://marketplace.visualstudio.com/items?itemName=fernfrost.agent-capabilities&ssr=false#overview) 
I think it should be built-in functionality of the agents
