### ISSUE TITLE
[BUG]: fetchTags option doesn't work when fetchDepth is set to 0

### ISSUE THREAD

**Issue by mkot02** [microsoft/azure-pipelines-agent#4391]
### What happened?

I tested `featchTags: false` option and it looks like it's not working properly when the repository in unshallow copy (fetchDepth: 0). The problem is that agent it always running with --prune-tags option which causes git to actually fetch tags. This is documented in **PRUNING** section of (git-fetch)[https://git-scm.com/docs/git-fetch#_pruning] documentation:

> The --prune-tags option is equivalent to having refs/tags/*:refs/tags/* declared in the refspecs of the remote. This can lead to some seemingly strange interactions:
> ```
> # These both fetch tags
> $ git fetch --no-tags origin 'refs/tags/*:refs/tags/*'
> $ git fetch --no-tags --prune-tags origin
> ```

### Versions

| Key | Value |
| -- | -- |
| Agent.Version | 2.218.1 |
| Agent.OS | Windows_NT |
| Agent.OSArchitecture | X64 |
| Agent.OSVersion | 10.0.19043 |

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Relevant log output

```shell
git config http.version HTTP/1.1
git --config-env=http.extraheader=env_var_http.extraheader -c http.proxy="http:/X.X.X.X:3128" fetch --force --no-tags --prune --prune-tags --progress --no-recurse-submodules origin
```

**Comment by kirill-ivlev** [comment]
Hi @mkot02,  thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.
