### ISSUE TITLE
Is it possible to update the Agent using the command line?

### ISSUE THREAD

**Issue by KingstonFE** [microsoft/azure-pipelines-agent#4397]
### Describe your feature request here

Sometimes, automatic updates are not feasible in certain environments. Can I download the new version of the azure-pipelines-agent package and use the Command line to update the current Self-Agent version?

**Comment by DmitriiBobreshev** [comment]
Hi @KingstonFE, unfortunately, we don't have a command line argument for an update, but as a temporary solution you could use
[bash ](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/update.sh.template) or [cmd](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/update.cmd.template) template, basically the script just [links ](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/update.sh.template#L105) new version with bin folder.

We'll try to implement an agent update via the cmd interface in the future.

**Comment by edwardkuo** [comment]
I also believe that having an offline installation method is very important.

**Comment by tinylabspace** [comment]
I might say that is possible I've done something similar. It isn't updating the currently installed agent but scripting the replacement of an agent. Run a "config.cmd remove ...." against the old agent and then a "config.cmd /unattended ..." to configure a new one using the new version. Or use the replace switch.
