### ISSUE TITLE
[Question]: Why does build script dev.sh only support RHEL version 7?

### ISSUE THREAD

**Issue by pixdrift** [microsoft/azure-pipelines-agent#4403]
### Describe your question

When attempting to execute the dev.sh build script on versions of EL Linux above 7, the following error is produced by `dev.sh`

```
-----------------------------------------
  Platform / RID detection
-----------------------------------------
RHEL supported only for version 7
```

The related code is here:
https://github.com/microsoft/azure-pipelines-agent/blob/master/src/dev.sh#L67-L75

Is there a specific reason that only RHEL 7 is supported for build? eg. glibc version, or available library versions? or is this check now deprecated?

The original check looks to have been added about 4 years ago, and more recently updated in this PR from a week ago:
https://github.com/microsoft/azure-pipelines-agent/pull/4393

With RHEL (EL) 7 in the maintenance support phase which ends June 2024, can this script be updated to support newer EL versions (8.x and 9.x)?

If there are issues with building on newer versions, is someone able to to point me to relevant documentation for the issue?

### Versions

Azure DevOps Linux agent latest.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by DenisRumyantsev** [comment]
Hi @pixdrift, do you have any issues when using the Linux-x64 agent build (latest version) on RHEL version 7 or higher?

**Comment by DenisRumyantsev** [comment]
@pixdrift, thank you for reporting this issue, I will fix it.

**Comment by pixdrift** [comment]
Hi @DenisRumyantsev, thanks for your time looking into this.

I am happy to test changes, but when you refer to 'latest version' are you referring to code currently in `master`? or are you referring to your draft PR that hasn't been merged? Can you provide a commit id for the code you would like me to validate, and I can take a look.

I reviewed your draft PR and can see the changes made in version detection, but I noticed on line 70 it's still setting the following for all versions of RHEL 7+.
https://github.com/microsoft/azure-pipelines-agent/pull/4408/commits/5a95efa811970213861a8272e28c3879ff56b082#diff-95882556eb41db695edcfc6974dcd9f408399babe67bf69af83c27b9d73dbeeeR70


`DETECTED_RUNTIME_ID='rhel.7.2-x64'`

Do we know what is consuming this RUNETIME_ID?, the compiler? If so, does it have a different target for newer versions of RHEL? I am concerned we may be inadvertently targeting an older RHEL version because it's working but may break in the near future if that target is deprecated.

Additionally, do we know why this check was here? is it purely to set compiler configuration? and is that requirement still valid, or should RHEL be moving to a generic target (ie. was this a workaround that is no longer required?).

**Comment by DenisRumyantsev** [comment]
@pixdrift the pipelines agent is supported for RHEL version 7 and higher. The agent build for the `rhel` runtime ID is exactly the same as for the `linux-x64` runtime ID, so it will be removed from the agent CI (this will not affect you). The `dev.sh` script will be fixed soon for building the agent on RHEL.

**Comment by DenisRumyantsev** [comment]
@pixdrift, the `dev.sh` build script should work fine in the `master` branch
