### ISSUE TITLE
[BUG]: In Azure DevOps Server, collection scoped PAT is allowed for agent registration but not for agent removal

### ISSUE THREAD

**Issue by Gabriel123N** [microsoft/azure-pipelines-agent#4426]
### What happened?

While using container based agents deployed inside a K8S cluster, I noticed that the agent were not removed whenever the pod was terminated.

After a bit of debugging, I noticed that the agent removal script returned an unauthorized error on my server url.

To register the agent, I was using a PAT scoped to the collection the agent was added to. When I changed the PAT to one that was scoped to the organization, the removal errors stopped and the agent was removed whenever the pod was terminated.

### Versions

Both 3.220.0 and 2.210.1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2022.0.1 patch 1

### Operation system

Windows Server 2022

**Comment by ismayilov-ismayil** [comment]
Hi @Gabriel123N, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
