### ISSUE TITLE
[Question]: Is it possible to configure the Pipeline to run with non-root user?

### ISSUE THREAD

**Issue by g3rzi** [microsoft/azure-pipelines-agent#4430]
### Describe your question

When I run commands in the Pipeline YAML, it runs the commands with a user named `vsts`.  
The user is part of the sudoer group without a need for a password.  

```shell
$ id
uid=1001(vsts) gid=127(docker) groups=127(docker),4(adm),101(systemd-journal)

$ sudo -lU vsts
Matching Defaults entries for vsts on <machine_id>:
    env_reset, mail_badpass,
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin,
    use_pty

User vsts may run the following commands on <machine_id>:
    (ALL) NOPASSWD: ALL
```

Is there a way to limit the pipeline to run non-privileged users?  So even the vsts wouldn't be able to use `sudo` and run privileged commands.   
Or the only is to limit it from the script itself ?

### Versions

Azure DevOps Online (latest) versions 

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by ismayilov-ismayil** [comment]
Hi @g3rzi 
As described [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#capabilities-and-limitations) there is limitation over Microsoft hosted agents. When pipeline starts it creates new fresh container for each job. In terms of installing required application and dependencies it runs with high privilege and passwordless. Unfortunately, there is not any plan to amend this behavior. You can use self-hosted agent with any customizations.

**Comment by g3rzi** [comment]
Is it a new **container**? It looks like it runs a new VM each time (based on the process list).
