### ISSUE TITLE
[BUG]: Problem with enough size in disk in agent deploy azure

### ISSUE THREAD

**Issue by daviht7** [microsoft/azure-pipelines-agent#4434]
### What happened?

hello, I have a problem in build pipeline azure, i'm using agent self hosted to build application .net framework 4.5 and it's happening problem in build because it shows that not exists space enough in disk of machine of agent, but it exists space , anyone can help me?

### Versions

version current

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows 11

### Relevant log output

```shell
##[section]Starting: Initialize job
Current agent version: '2.153.1'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: NuGetToolInstaller
##[warning]Failed to download task 'NuGetToolInstaller'. Error There is not enough space on the disk.

##[warning]Back off 15.104 seconds before retry.
##[error]A task was canceled.
##[section]Finishing: Initialize job
```

**Comment by ismayilov-ismayil** [comment]
Hi @daviht7, thanks for reporting. Could you please enable system.debug and share the agent log with us. Please consider removing or masking any confidential information.
