### ISSUE TITLE
[Question]: what is correct run script for running in docker

### ISSUE THREAD

**Issue by MirKml** [microsoft/azure-pipelines-agent#4435]
### Describe your question

Hi, I read the doc about running agent in docker on linux
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux

there is starup.sh script which ends with
`./run.sh "$@" & wait $!`

But there is an issue https://github.com/microsoft/azure-pipelines-agent/pull/3636 which creates the `run-docker.sh` and recommended it as replacement for `run.sh`. It's still presented on latest agent. But in the documentation, `run.sh` is presented but it received no updates.

So what is the best script to run the agent? I think `run-docker.sh` - it's younger and fix some issue. But in documentation older one `run.sh` is mentioned.

### Versions

latest 3.x Azure pipeline agent for Linux

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Linux with docker

**Comment by ismayilov-ismayil** [comment]
Hi @MirKml, thanks for reporting. We will look and update the doc if necessary.

**Comment by frankhaugen** [comment]
> Hi @MirKml, thanks for reporting. We will look and update the doc if necessary. 

This is still unresolved?

**Comment by MirKml** [comment]
> This is still unresolved?
@frankhaugen I think unresolved. We still use
`run-docker.sh`, it's presented in latest agent release. It was set up by previous developer.

Nothing mentioned in doc about diference run.sh vs run-docker.sh

**Comment by aakash-pinc** [comment]
Any update on this? Should we need to use run.sh or run-docker.sh?

**Comment by CesarAchig** [comment]
I would also like to know if there is any update on this matter

**Comment by johnwc** [comment]
If you are running the self-hosted agent in a container, and you want to be able to use the update agent functionality from the azure devops UI; then you need to be using the `run-docker.sh` script. 

I just tested this, if you use the `run.sh` script, the agent will not come back online without user intervention. When I swapped to using `run-docker.sh`, and requested the agent to update from the UI, the agent updated and come back online to listen for jobs.
