### ISSUE TITLE
[BUG]: launching self-hosted agent from powershell core prompt causes powershell-based tasks to fail

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-agent#4438]
### What happened?

I provisioned a new self-hosted agent and ran it interactively using `./run.cmd` from a `pwsh` prompt in my system. All jobs containing a powershell based task fail with obscure error messages:

See: https://jessehouwing.net/vsbuild-task-fails-on-self-hosted-azure-pipelines-agent/

Turns out this is caused by launching the agent from a powershell core prompt. Stopping the agent and starting it from PowerShell 5.1 or from a Windows Shell solves the issue. Would be nice if the agent detected this and would fail to start with a proper error message.

### Versions

Azure DevOps Service 
Windows 11 version 22H2 (0S Build 22621.2283)
Azure Pipelines Agent 3.225.0
VSBuild task: 1.214.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11 version 22H2 (0S Build 22621.2283)

### Version controll system

Git

### Relevant log output

```shell
2023-09-18T13:24:55.1897667Z ##[section]Starting: VSBuild
2023-09-18T13:24:55.2042232Z ==============================================================================
2023-09-18T13:24:55.2042611Z Task         : Visual Studio build
2023-09-18T13:24:55.2042705Z Description  : Build with MSBuild and set the Visual Studio version property
2023-09-18T13:24:55.2042827Z Version      : 1.214.0
2023-09-18T13:24:55.2042907Z Author       : Microsoft Corporation
2023-09-18T13:24:55.2042985Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
2023-09-18T13:24:55.2043127Z ==============================================================================
2023-09-18T13:24:56.8956825Z ##[error]The following error occurred while loading the extended type data file: Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member AuditToString is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member AccessToString is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Sddl is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Access is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Group is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Owner is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Path is already present.

2023-09-18T13:24:57.0291684Z ##[error]The 'ConvertTo-SecureString' command was found in the module 'Microsoft.PowerShell.Security', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Security'.
2023-09-18T13:24:57.0552980Z ##[section]Finishing: VSBuild
```

**Comment by DenisRumyantsev** [comment]
Hi @jessehouwing, could you set the `AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL` pipeline variable / agent environment variable to `true` and run your pipeline again?

**Comment by jessehouwing** [comment]
> AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL

I set it as an environment variable in the `pwsh` promt, but that works!

![image](https://github.com/microsoft/azure-pipelines-agent/assets/4173387/0b9804f6-52a5-434e-b9c1-40e5fbf6073c)

**Comment by DenisRumyantsev** [comment]
@jessehouwing, let me close this issue for now. Feel free to reopen it or open a new issue if you have more questions.

**Comment by jessehouwing** [comment]
It's still a but I need to enable an agent knob for it to work normally :). I'd at least expected a warning in the logs upon launching the agent.

**Comment by endorria** [comment]
Not working when running as a service with agent v 3.230.0

**Comment by WizMe-M** [comment]
> Hi @jessehouwing, could you set the `AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL` pipeline variable / agent environment variable to `true` and run your pipeline again?

Hi @DenisRumyantsev! Could you help me? How can I set this var correctly?
I do that in this way:
```yaml
pool:
  name: mypool

variables:
  AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL: 'true'
  
steps:

  - powershell: |
      $env:Path
    displayName: 'Print paths'
```
but still receive an error. 
What am I doing wrong? How can I specify env variable for agent (can I) ?

**Comment by jessehouwing** [comment]
> > Hi @jessehouwing, could you set the `AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL` pipeline variable / agent environment variable to `true` and run your pipeline again?
> 
> Hi @DenisRumyantsev! Could you help me? How can I set this var correctly? I do that in this way:
> 
> ```yaml
> pool:
>   name: mypool
> 
> variables:
>   AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL: 'true'
>   
> steps:
> 
>   - powershell: |
>       $env:Path
>     displayName: 'Print paths'
> ```
> 
> but still receive an error. What am I doing wrong? How can I specify env variable for agent (can I) ?

I've had to set it in the systems environment variables, then had to restart the agent.
