### ISSUE TITLE
[Question]: Issue with Running Azure DevOps Self-Hosted Agent in Docker as Non-Root User

### ISSUE THREAD

**Issue by arielrahmane** [microsoft/azure-pipelines-agent#4444]
### Describe your question

I am in the process of setting up an Azure DevOps pipelines agent within an Azure Container Instance. I have been advised against running the Docker instance with root privileges due to potential security risks. I am now attempting to configure the Docker instance to run as a non-root user, but I am encountering several issues.

## What I tried doing
1. Followed the instructions in [this guide](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops) to set up a self-hosted agent.
2. Created a Dockerfile as shown below.
3. Attempted to add a non-root user, which resulted in build errors due to permission issues with the `apt-get` command.
4. Encountered additional issues when trying to run the container in rootless mode (see [this issue](https://github.com/microsoft/azure-pipelines-agent/issues/4297))

## What I want to achieve
The Docker instance should be able to run as a non-root user without encountering permission denied errors or other issues.

#### Actual Behavior
- Permission denied errors occur when installing packages as a non-root user.
- Additional issues are observed when running the container in rootless mode.

#### Questions
- How can I modify the Dockerfile to prevent permission denied errors when installing packages as a non-root user?
- Are there any known solutions or workarounds for the issues encountered when running the container in rootless mode?

#### Additional Information
Here is the Dockerfile I am using:
```Dockerfile

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV NODE_MAJOR=18

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
  apt-transport-https=2.0.9 \
  ca-certificates=20230311ubuntu0.20.04.1 \
  curl=7.68.0-1ubuntu2.19 \
  gpg=2.2.19-3ubuntu2.2 \
  gnupg=2.2.19-3ubuntu2.2 \
  lsb-release=11.1.0ubuntu2 \
  software-properties-common=0.99.9.12 \
  zip=3.0-11build1 \
  && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list


RUN mkdir -p /etc/apt/keyrings && \
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  apt-utils=2.0.9 \
  git=1:2.25.1-1ubuntu3.11 \
  iputils-ping=3:20190709-3 \
  jq=1.6-1ubuntu0.20.04.1 \
  terraform=1.5.7-1 \
  nodejs=18.18.0-1nodesource1 \
  && rm -rf /var/lib/apt/lists/*

RUN npm install --global yarn@^1.x.x

RUN curl -fsSL https://download.red-gate.com/maven/release/org/flywaydb/enterprise/flyway-commandline/9.17.0/flyway-commandline-9.17.0-linux-x64.tar.gz | tar -xvz && \
  ln -s "$(pwd)/flyway-9.17.0/flyway" /usr/local/bin

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

ENV TARGETARCH=linux-x64

WORKDIR /azp

COPY ./start.sh .
RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]

HEALTHCHECK --interval=1m --timeout=10s --start-period=5s --retries=3 \
  CMD pgrep -F /var/run/azp_agent.pid || exit 1

```

### Versions

ubuntu:20.04

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by DenisRumyantsev** [comment]
Hi @arielrahmane, can you try adding this right before `ENTRYPOINT`?

```dockerfile
RUN useradd agent
RUN chown agent /azp/
USER agent
```

**Comment by DenisRumyantsev** [comment]
@arielrahmane thank you for reporting this, the documentation has been updated.
