### ISSUE TITLE
[enhancement]: add support for git partial clone in checkout step

### ISSUE THREAD

**Issue by gregjhogan** [microsoft/azure-pipelines-agent#4453]
### Describe your feature request here

[git partial clone](https://git-scm.com/docs/partial-clone) support can benefit large repositories in CI. Using shallow clone (currently supported) limits what git commands work and shallow clone isn't ideal for self-hosted agents that can preserve their git repo state between builds.

Here is an example of what I would like to see support for:
```sh
git clone --filter=blob:none --recurse-submodules --also-filter-submodules https://github.com/<org>/<repo>
```

This is a great summary of partial clone features and how they compare to shallow clone:
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

**Comment by aleksandrlevochkin** [comment]
Hi @gregjhogan thank you for reaching out regarding this enhancement. We're working on higher-prioritized issues at the moment but will get back to this one soon.

**Comment by ericmattingly** [comment]
@gregjhogan Just wanted to let you know that --filter is now supported on Azure DevOps Repos, we are continuing to prioritize adding this support in the checkout step but for now you can do a manual git command pipeline to achieve the a filtered clone - https://devblogs.microsoft.com/devops/git-partial-clone-now-supported-in-azure-devops/

**Comment by ajeckmans** [comment]
I'd personally still prefer this to be an option of the checkout step.

**Comment by jnilau** [comment]
Hi @gregjhogan and @ajeckmans,

git partial cloning will be available as a checkout option soon but only for blobless and treeless fetches. The changes on the agent side was done in [this PR](https://github.com/microsoft/azure-pipelines-agent/pull/4693) and we'll be rolling out the YAML changes in the next few weeks. I can drop another comment here when rollout is complete.

**Comment by jnilau** [comment]
Rollout completed!
