### ISSUE TITLE
[enhancement]: Include MacOS ARM64 links in release assets

### ISSUE THREAD

**Issue by JaapManenschijn** [microsoft/azure-pipelines-agent#4509]
### Describe your feature request here

I noticed that while there is is ARM64 support for agents on MacOS, the `assets.json ` file included with a release does not include download links to the corresponding agents.
In addition to that, the link to the MacOS ARM64 pipeline agent on the [Release page](https://github.com/microsoft/azure-pipelines-agent/releases) actually points to the x64 agent instead.

In the setup i'm working on we automatically download the latest agent version by downloading the `assets.json` file and then finding the agent download url inside of it. This previously worked fine for x64 but we want to switch to ARM64, so the entries not being there does not help. We've worked around it for now by manually constructing the correct download url, but it would be nice to have them added to the assets file.

**Comment by max-zaytsev** [comment]
@JaapManenschijn thanks for reporting this! We'll take a look at the PR

**Comment by kirill-ivlev** [comment]
@JaapManenschijn thank you for raising this question.
As I see these changes already merged and the latest releases contain this information, I'm closing this issue.
Once again, thank you for reporting!
