### ISSUE TITLE
[Question]: How to install a vsis extension to my agent server?

### ISSUE THREAD

**Issue by FisherMS** [microsoft/azure-pipelines-agent#4529]
### Describe your question

How to install a vsis extension to my agent server?
I need install some vsis exntensions to my agent server . But I don't know how to operation it.

### Versions

v3.227.1/ windows 2018

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows 2018

**Comment by vmapetr** [comment]
Hi @FisherMS thank you for your question!
Please check the following instructions to see how to install the extensions:
1) Azure DevOps Services - https://learn.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops&tabs=browser
2) Azure DevOps Server - https://learn.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops-2022&tabs=browser
3) How to publish an extension to the Marketplace - https://learn.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops#publish-your-extension

**Comment by FisherMS** [comment]
Hi @vmapetr 
I found the Devops server on https://learn.microsoft.com/en-us/azure/devops/server/download/azuredevopsserver?view=azure-devops
Thank you very much.
