### ISSUE TITLE
ARM64 support for VM Scale Sets

### ISSUE THREAD

**Issue by icornett** [microsoft/azure-pipelines-agent#4535]
### Describe your feature request here

Please implement an architectural check on the agents to enable ARM64 VMSS agents.  Presently, the only check is on the OS. Since it's possible to create an ARM64 VMSS the agent fails to install.

**Comment by aleksandrlevochkin** [comment]
Hi @icornett thank you for reporting this issue. We are currently working on higher prioritized issues, but we'll get back to this one as soon as possible.
