### ISSUE TITLE
[enhancement]: Self-managed agents able to (de)register themselves with no tokens using the user-assigned Azure AD Managed Identity associated to the agent machine

### ISSUE THREAD

**Issue by clemlesne** [microsoft/azure-pipelines-agent#4544]
### Describe your feature request here

Relates to https://github.com/microsoft/azure-pipelines-agent/issues/4233#issuecomment-1530240172.

**Comment by aleksandrlevochkin** [comment]
Hi @clemlesne, thank you for proposing this enhancement, we are working on higher prioritized issues at the moment, but we will get back to this one as soon as possible.

**Comment by phmcder** [comment]
I am also in need of this

**Comment by markstoel** [comment]
I'm actually surprised that given the statement that of version 3.227.1 Service Principal is supported, and I quote: "You can register an agent using a Service Principal starting with [agent version 3.227.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.227.1) by specifying SP as the agent authentication option."
[](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/service-principal-agent-registration?view=azure-devops)
This is not fully implemented yet. 
Anyway, same here. Also in need of this.

**Comment by robertblowers-nasstar** [comment]
To also add my support for this ticket.  

Been able to configure an agent unattended and running it with --once mode
`  ./config.sh --unattended \
  --agent "${AZP_AGENT_NAME:-$(hostname)}" \
  --url "${AZP_URL}" \
  --auth "SP" \
  --clientid "${AZP_CLIENT_ID}" \
  --tenantid "${AZP_TENANT_ID}" \
  --clientsecret $(cat "${AZP_TOKEN_FILE}") \
  --pool "${AZP_POOL:-Default}" \
  --work "${AZP_WORK:-_work}" \
  --replace \
  --acceptTeeEula & wait $!`
  
  But when the agent comes to deregister itself after running the job it gets:
  `<html>
<body>

Removing agent from the server
--
Error reported in diagnostic logs. Please examine the log for more details.
- /azp/_diag/Agent_20240314-170513-utc.log
Failed: Removing agent from the server
VS30063: You are not authorized to access https://dev.azure.com.


</body>
</html>`

This feature would look to remedy this problem

**Comment by hilariocoelho** [comment]
This would be a very helpful feature so we can setup self hosted agents without any token on AKS using pod assigned identity

**Comment by clemlesne** [comment]
Not completed at all.

**Comment by patrix87** [comment]
Can we reopen that ?
This is still not working and Azure is "phasing out" PAT ...

**Comment by patrix87** [comment]
I think I have fixed the issue by modifiying the start.sh
It does introduce a security issue since you now have to keep the clientsecret in the environment for the duration of the life of the container.

[start.sh.txt](https://github.com/user-attachments/files/20471291/start.sh.txt)
