### ISSUE TITLE
[BUG]: Feature Check For "UseMaskingPerformanceEnhancements" Causes an Issue With TFS 2018

### ISSUE THREAD

**Issue by noldoreldar** [microsoft/azure-pipelines-agent#4545]
### What happened?

 ->
TFS 2018 (Version 16.131.28601.4) does not have the feature "DistributedTask.Agent.UseMaskingPerformanceEnhancements". So this endpoint returns an HTTP error and this line here causes a failure during the job run.

`JobDispatcher.cs` 
...
`private async  Task RunAsync(Pipelines.AgentJobRequestMessage message, WorkerDispatcher previousJobDispatch, WorkerDispatcher newJobDispatch)`
...
`var newSecretMaskerFeaturFlagStatus = await featureFlagProvider.GetFeatureFlagAsync(HostContext, "DistributedTask.Agent.UseMaskingPerformanceEnhancements", Trace);`
...
After we manually commented this line out locally and had a new build from branch "releases/3.230.2", the agent started working with no issues.

### Versions

TFS 2018 (Version 16.131.28601.4)

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

TFS 2018 (Version 16.131.28601.4)

### Operation system

TFS -> Windows Server 2018
Agent -> Docker Container

**Comment by aleksandrlevochkin** [comment]
@noldoreldar Thank you for reporting, we'll take a look at this issue.

**Comment by kirill-ivlev** [comment]
@noldoreldar this check is now optional, could you please confirm that with latest agent your issue is resolved?
