### ISSUE TITLE
[BUG]: Microsoft.VCToolsVersion.v143.default.props contains wrong version

### ISSUE THREAD

**Issue by jbrezina** [microsoft/azure-pipelines-agent#4554]
### What happened?

As described in [this issue](https://github.com/microsoft/azure-pipelines-tasks/issues/19320), there is a wrong version contained within the file `c:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.v143.default.props`. The version should be **14.38.33130** but it is **14.37.32822**.

### Versions

Agent name: 'Hosted Agent'
Agent machine name: 'fv-az290-93'
Current agent version: '3.230.0'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
Image: windows-2022
Version: 20231126.1.0
Included Software: https://github.com/actions/runner-images/blob/win22/20231126.1/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20231126.1
Runner Image Provisioner
2.0.321.1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022 10.0.20348

**Comment by DenisNikulin5** [comment]
Hi @jbrezina  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by jbrezina** [comment]
Hi, any updates on this please? This is a one line fix and it is a blocker for c++ pipelines to work correctly.. this issue is regularly recurring so it would be great, if you have any check on this though

**Comment by antonfirsov** [comment]
@DenisNikulin5 FYI one of the dotnet/runtime pipelines was also broken because of this, which was really nasty to diagnose. We had to go with a workaround, would be nice to get rid of it.

**Comment by jbrezina** [comment]
@DenisNikulin5 Hi, it would be great if you find the time to fix this one line so everyone does not have to investigate this issue and spend a lot of men-hours to find the solution as described here [Latest Visual Studio version (17.9.1) causes a linker error calling thread::sleep_for from a static library linked to Unreal](https://developercommunity.visualstudio.com/t/Latest-Visual-Studio-version-1791-ca/10598722#T-N10605771) and then implement the workaround until you find the time to fix this.
Also it would be great if you somehow automate the check for this as it is a repetitive issue.

**Comment by DenisNikulin5** [comment]
Hi @jbrezina. We're back to your problem. As I can see the azure cloud image (windows-2022) has an issue.
But this repo is only related to the agent itself, so please recreate the issue in https://github.com/actions/runner-images.
