### ISSUE TITLE
[BUG]: Ubuntu libssl package version does not exist any more in installdependencies.sh

### ISSUE THREAD

**Issue by angaaruriakhil** [microsoft/azure-pipelines-agent#4555]
### What happened?

We have self hosted agents running Ubuntu 22.04 in a VMSS hosted in Azure, in Australia East. 

The pipeline agent is not installing properly on our agents during the provisioning process, which leads to the VM being classed as unhealthy and then gets removed by Azure. The provisioning process is using the latest release, vsts-agent-linux v3.230. 

Inspecting the logs during the install process using the command: 

`sudo cat "/var/log/azure/Microsoft.VisualStudio.Services.TeamServicesAgentLinux/enableagent.log"`

yields the following logs: 

```
id -u
+ user_id=0
+ '[' 0 -ne 0 ']'
+ '[' -e /etc/os-release ']'
+ echo '--------OS Information--------'
+ cat /etc/os-release
+ echo ------------------------------
+ '[' -e /etc/debian_version ']'
+ echo 'The current OS is Debian based'
+ echo '--------Debian Version--------'
+ cat /etc/debian_version
+ echo ------------------------------
+ command -v apt
+ '[' 0 -eq 0 ']'
+ apt update

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

After this, there are no further logs, the VM is effectively stuck until Azure removes it and tries again with a new VM to no avail. 

Doing some investigation in **bin/installdependencies.sh** there is the following line of code on line 84: 

`wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb`

This path has a hardcoded version, 2.17. Looking at the [repository](http://security.ubuntu.com/ubuntu/pool/main/o/openssl/), the package should be version 2.20 as 2.17 doesn't exist anymore. 

Could this be updated please? 

### Versions

Pipeline agent: vsts-agent-linux 3.230 and 3.232.1, 
OS - Ubuntu 22.04

### Environment type (Please select at least one environment where you face this issue)

- [] Self-Hosted
- [ ] Microsoft Hosted
- [x] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

**Comment by markatky46** [comment]
We are also having this issue. Is there any update?

**Comment by markatky46** [comment]
Is there any update on this issue?

**Comment by markatky46** [comment]
@DenisNikulin5 pls could you or one of the team provide an update on this for me? It is causing major problems for us

**Comment by kirill-ivlev** [comment]
@markatky46 sorry for the delay, issue should be fixed for now, could you please confirm it?

**Comment by kirill-ivlev** [comment]
I'm closing this issue since we didn't recieve any responce from you.
Please feel free to bump it, if it still an issue.
