### ISSUE TITLE
Agent 3.230.2 queues but never runs (since upgrade on pipeline agent)

### ISSUE THREAD

**Issue by blakeduffey** [microsoft/azure-pipelines-agent#4566]
### What happened?

Upgraded from 3.227. to 3.230 on our self-hosted agents.  Jobs are queuing but never actually running.  

```
Queued: Today at 4:28 PM

The agent request is already running or has already completed.
Job preparation parameters
```

ADO Server is Version Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20231109.3)

### Versions

ADO Server is Version Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20231109.3)

self-hosted agent (Windows) is 3.230.2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

ADO Server is Version Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20231109.3)

### Operation system

Windows 2022

### Version controll system

git

**Comment by tinylabspace** [comment]
This is the same issue I'm referring to in #4562 https://github.com/microsoft/azure-pipelines-agent/issues/4562#issuecomment-1850906534.

**Comment by DmitriiBobreshev** [comment]
Hi @dihaase, thank you for the feedback, the error is the same as in [4562](https://github.com/microsoft/azure-pipelines-agent/issues/4562), closing this issue, you can track the progress in the [4562](https://github.com/microsoft/azure-pipelines-agent/issues/4562)
