### ISSUE TITLE
[Question]: How to restore missing dependencies ?

### ISSUE THREAD

**Issue by g3rzi** [microsoft/azure-pipelines-agent#4572]
### Describe your question

I am able to make changes in the agent and build through the script `dev.cmd` but when I open the solution with Visual Studio 2017 it shows me that all the dependencies are missing although they are not:  
![image](https://github.com/microsoft/azure-pipelines-agent/assets/11998736/032ef2cd-fc94-4bf9-a4d7-435d3609da3a)

It makes debugging harder because I can see some of the object properties. For example, in the [RunAsync](https://github.com/microsoft/azure-pipelines-agent/blob/ba6e423917bbb628b461a2cce75712d80c069a1c/src/Agent.Worker/JobRunner.cs#L46) function in the `JobRunner` class of `Agent.Worker` I wanted to see the properties of the `Pipelines.AgentJobRequestMessage` object which is part of the dependency `Microsoft.TeamFoundation.DistributedTask.WebApi.dll` but the solution can't find it.   

Is there a simple way to restore them? I tried with `dotnet restore` without success.  

### Versions

latest, this is a general question, it happens in every solution I tried.  

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

**Comment by DmitriiBobreshev** [comment]
Hi @g3rzi, the Microsoft.TeamFoundation.DistributedTask.WebApi.dll is a part of the vss-api-netcore package. 
You can restore the package by adding https://pkgs.dev.azure.com/mseng/PipelineTools/_packaging/nugetvssprivate/nuget/v3/index.json as a package source in your NuGet setup.

**Comment by kirill-ivlev** [comment]
HI @g3rzi!
Please let us know if you still facing this issue, otherwise we planning to close this issue soon.

**Comment by g3rzi** [comment]
Thanks,

I edited the `NuGet.Config` to be like that (based on the URL @DmitriiBobreshev wrote):
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="restsdk" value="https://pkgs.dev.azure.com/mseng/PipelineTools/_packaging/nugetvssprivate/nuget/v3/index.json"/>
	<add key="AzureDevOps" value="https://pkgs.dev.azure.com/mseng/PipelineTools/_packaging/nugetvssprivate/nuget/v3/index.json" />
  </packageSources>
</configuration>

```

But after restart of Visual Studio, it still doesn't show a reference to [Pipelines.AgentJobRequestMessage](https://github.com/microsoft/azure-pipelines-agent/blob/f87750b36c64c82400cb53791975e8f0f50fcd77/src/Agent.Worker/Worker.cs#L60C15-L60C15).  

The problem is much larger than that, all the dependencies appear to be missing:  
![image](https://github.com/microsoft/azure-pipelines-agent/assets/11998736/c614cfe8-0a9b-4ceb-928e-4086a05220f5)


Did you try to download the repository from scratch?

**Comment by kirill-ivlev** [comment]
Hi @g3rzi, could you please confirm that you can build agent using` .\src\dev.cmd build` layout command?

**Comment by g3rzi** [comment]
Yes, it works. 
After I run:  
```
PS D:\azure-pipelines-agent-3.225.2\src> .\dev.cmd layout
<REDACTED>
PS D:\azure-pipelines-agent-3.225.2\src> .\dev.cmd build
...
  Build succeeded.
      0 Warning(s)
      0 Error(s)

  Time Elapsed 00:00:00.29
/d/azure-pipelines-agent-3.225.2/src
...

**Comment by StingyJack** [comment]
@kirill-ivlev  - please confirm that VS 2017 is the version of VS that should be used for this.

**Comment by kirill-ivlev** [comment]
@StingyJack not really, I'm using VS 2022 with no issues.
But, before building from MSVS you need to build using dev scripts to restore these dependencies.

Closing this one, since issue is resolved.
