### ISSUE TITLE
[Question]: How to print extra information about self-hosted agent in the pipeline output

### ISSUE THREAD

**Issue by nosalan** [microsoft/azure-pipelines-agent#4579]
### Describe your question

I would like to display custom metadata about the self-hosted agent, so that it's visible in the pipeline output. For example the current agent version or image name or anything else.

A nice place to show it would be at the beginning of the job output, for example:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/2273250/811625c7-d37b-4b62-928e-9e878f3ad7a7)

Is there any way to do this, for example by passing some env variables to the agent binary?

### Versions

Azure DevOps / Ubuntu

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Version controll system

Git

**Comment by ivanduplenskikh** [comment]
@nosalan, there are [logging and formatting commands](https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#logging-command-format) that write to the pipeline log.

**Comment by ivanduplenskikh** [comment]
@nosalan, the agent/pipeline doesn't have any built-in mechanism for printing any kind of additional metadata to the beginning of output.
Only with creating additional pipeline step which can parse information that you need and add it to output with commands described in link above.
