### ISSUE TITLE
Self Hosted Azure Agent with Auto Logon is not starting as Administrator

### ISSUE THREAD

**Issue by bhargavkumar-65** [microsoft/azure-pipelines-agent#4606]
### Describe your question

Hi Team,

We are using below Agent in windows server 2019.
[v3.232.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.232.1)
But we observed that Azure Agent with Auto Logon is not starting as Administrator after the configuration. 

We have some VMs with agent 2.x version configured those run as administrator by default.
The process followed to configure the agent was same.

.\config.cmd --unattended --agent '<agent-name>' --pool '<agent-pool-name>' --url '<azure-dev-ops-organization-url>' --auth 'PAT' --token '<token>' --runAsAutoLogon --windowsLogonAccount '<domain\user-name>' --windowsLogonPassword '<windows-password>' is the command we use in Powershell AdminMode

### Versions

[v3.232.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.232.1)

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows server 2019

**Comment by ismayilov-ismayil** [comment]
Hi @bhargavkumar-65, thanks for reporting.
Could you please confirm that the windows user which you pass credentials as parameter, is in administrator group?

**Comment by bhargavkumar-65** [comment]
@ismayilov-ismayil  Yes, the user is in administrator group, in fact there is only one user in the machine.

**Comment by ismayilov-ismayil** [comment]
@bhargavkumar-65  we are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by ismayilov-ismayil** [comment]
@bhargavkumar-65  After investigation I found out that the `--runAsAutoLogon `  argument doesn't mean to run it as Administrator. It requires to set it up by administrator privilege due to create startup script. 
If you want to run it with administrator privilege, please, create agent as a service.

**Comment by ismayilov-ismayil** [comment]
Hi @bhargavkumar-65, closing this one - feel free to ask any other questions or let us know if it's still relevant for you.
