### ISSUE TITLE
[enhancement]: support unattended configuration with a service principal

### ISSUE THREAD

**Issue by afeld** [microsoft/azure-pipelines-agent#4641]
### Describe your feature request here

The `./config.sh` doesn't seem to have flags to allow use of a service principal - more details in https://github.com/MicrosoftDocs/azure-devops-docs/issues/13864#issuecomment-1928675057. Thanks!

**Comment by DenisRumyantsev** [comment]
@afeld thanks for reporting this. We will check if we can add a new flag to the config.

**Comment by Bjego** [comment]
Just had the same issue. We do have a pat based version running in docker and kubernetes. But to reduce complexity it would be great to add the missing flags.

**Comment by rafasc** [comment]
They're not documented, but they exist and are usable.

https://github.com/microsoft/azure-pipelines-agent/blob/57947b0ed6fbe4eebd5fc8912820b8f97323c0b1/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L140-L141

https://github.com/microsoft/azure-pipelines-agent/blob/57947b0ed6fbe4eebd5fc8912820b8f97323c0b1/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L149

It also honors their respective environment variables:
```
VSTS_AGENT_INPUT_CLIENTSECRET
VSTS_AGENT_INPUT_CLIENTID
VSTS_AGENT_INPUT_TENANTID
```
using the mechanism described in https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux-agent?view=azure-devops#unattended-config

I looked at the agent code the service principal support is not well documented.

**Comment by afeld** [comment]
Hey, sorry for the slow response. You were correct about those different flags, but it took a while for me to get the whole thing working. Updated the docs with what I found: https://github.com/MicrosoftDocs/azure-devops-docs/pull/14154 Thanks for the help!

**Comment by afeld** [comment]
Oops, I should have said explicitly: `--auth SP` worked! For the Docker use case, a token was needed for getting the agent package list (in `start.sh`), so ended up passing that in as the PAT. Misleading that it's not a "personal" token, but it works.
