### ISSUE TITLE
[BUG]: System.debug=true not working

### ISSUE THREAD

**Issue by saevios** [microsoft/azure-pipelines-agent#4686]
### What happened?

I am not sure if anyone else is experiencing this on the latest agent, but if I execute a pipeline with:

``` yaml
variables:
  System.Debug: = true
```
then I don't receive any debug messages in the console logs. It was working in earlier versions

### Versions

Azure DevOps Agent 3.234.0 / 

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022 Datacenter Azure Edition 21H2 20348.2322

**Comment by ivanduplenskikh** [comment]
Hi @saevios,

Try to declare the variable as:
```
variables:
  system.debug: 'true'
```
Link to the documentation: https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemdebug

**Comment by saevios** [comment]
Tried that. Also tried lowercase system.debug. doesn't seem to work. Also tried double quotations. Like I said, it was working before
