### ISSUE TITLE
[BUG]: Replace Node16 with node20 in runsvc.sh

### ISSUE THREAD

**Issue by kodzis-eib** [microsoft/azure-pipelines-agent#4687]
### What happened?

By default node16 is installed with Systemd service on Linux in runsvc.sh, but node16 is not supported any longer by vendor. Please bump node default version to node20 to tackle vuln sec issues in the future.

### Versions

3.236.1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

RedHat 9

### Version controll system

GIT

**Comment by ivanduplenskikh** [comment]
Hi @kodzis-eib thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by kodzis-eib** [comment]
Any news?

**Comment by vmapetr** [comment]
Hi @kodzis-eib !
We are planning to implement the required changes but do not have ETA yet. 
We'll keep you posted on any updates.

**Comment by vmapetr** [comment]
@kodzis-eib 
We prepared the fix and merged it - https://github.com/microsoft/azure-pipelines-agent/pull/4719. We also going to release and deploy the updated agent in next several days.

**Comment by vmapetr** [comment]
@kodzis-eib We finished the deployment of the agent release [v3.238.0 ](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.238.0) that includes the new node version in runsvc.sh. 
I'll close this issue, please feel free to reopen it in case if you have additional questions.
