### ISSUE TITLE
[Question]: iOS build on self-hosted agent on mac M1 is slow

### ISSUE THREAD

**Issue by t0x1c123** [microsoft/azure-pipelines-agent#4692]
### Describe your question

Hello, we have been using a self-hosted agent on a physical Mac mini M1 for some time now. The build of our iOS React Native application used to take approximately 15 minutes. After updating macOS to the latest version 10.15.7 and Xcode to version 15, our build slowed down to approximately 40 minutes. We tried replacing the build task in Azure Pipeline with Fastlane, and it indeed helped. The build time on Fastlane is now 24 minutes. It's strange that when I run the same command in the local console on the Mac, the build only takes 5 minutes. This suggests that the agent is slowing down the build. Are we doing something wrong? Thank you.

### Versions

Agent version: 3.234.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Mac OS 10.15.7

**Comment by kirill-ivlev** [comment]
Hi @t0x1c123,
thank you reporting this. Actually tasks/agents execute same commands as you do in terminal, so, there should not be such difference.
May I ask you to enable system.debug (pipeline/or environment variable) and attach logs to this issue? (the part where build starts)
