### ISSUE TITLE
[enhancement]: please add XCode 15.3 to macOS-13 build agent

### ISSUE THREAD

**Issue by gjmoyer** [microsoft/azure-pipelines-agent#4710]
### Describe your feature request here

I have upgraded to XCode 15.3 locally and this updated the pins version in Package.resolved file from 2 to 3 which then throws unknown 'PinsStorage' version '3' error on build agent 3.236.1 on macos-13 (macOS 13.6.4). Xcode 15.3 was released March 5, 2024.

**Comment by DmitriiBobreshev** [comment]
Hi @gjmoyer, thank you for the feedback. 
We are the agent's repo and can't control images. But you can create an issue in [runner-images](https://github.com/actions/runner-images) repository. 
I'm closing the issue as irrelevant.

**Comment by j-fritsch** [comment]
@DmitriiBobreshev, maybe I am misunderstanding something, but your link goes to the GitHub Actions runner-images repo. Is there a repo for Azure Devops that we can create issues in?

**Comment by DmitriiBobreshev** [comment]
Yes, Azure DevOps and gh actions share images, here is the ref on [mslearn](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#recent-updates)
![image](https://github.com/microsoft/azure-pipelines-agent/assets/106314398/25299101-6e13-4718-b4ae-1be96ffd9503)
