### ISSUE TITLE
[Question]: persistCredentials: true - Token Only Lasts For 1 Hour?

### ISSUE THREAD

**Issue by v1ferrarij** [microsoft/azure-pipelines-agent#4713]
### Describe your question

I have been working on a pipeline which builds VM Images in Azure, due to the nature of the pipeline, the pipeline takes more than 1 hour to complete.

At the end of the pipeline when the build of the image completes, we want to tag our repository.

I have found that if a pipeline runs for longer than 1 hour, **persistCrendentials: true** becomes redundant, it appears as though the credentials expire, thus meaning I cannot run git commands at the end of the pipeline.

Is this expected behaviour, could you add an option to extend the token life time?

### Versions

Azure DevOps Services

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Version controll system

Git

**Comment by DmitriiBobreshev** [comment]
Hi @v1ferrarij, thank you for the question, 60 minute is default timeout for the jobs, you can increase that time by passing [timeoutInMinutes](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#agentless-tasks) parameter in the job.

**Comment by v1ferrarij** [comment]
Hi @DmitriiBobreshev 
I think there is confusion with the question I asked.
My issue is not around job time out, my question was around timeout for the OAuth token, I have no issues running jobs for over 60 minutes.
Are you able to re-review the question please?

**Comment by DmitriiBobreshev** [comment]
Hi @v1ferrarij, sorry for the misunderstanding, are you using Azure Pipelines GitHub [App](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#github-app-authentication) for authentication?

**Comment by DmitriiBobreshev** [comment]
Got it, thanks! Yes, this is expected behaviour when you're using Azure Pipelines GitHub [App](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#github-app-authentication) for authentication. When you perform a checkout step it executes under a new token created by  Azure Pipelines GitHub App and authenticates as a GitHub App [installation](https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#about-github-app-installations), unfortunately, such tokens expire after [1hour](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app) and, unfortunately, we can't control the behaviour.
![image](https://github.com/microsoft/azure-pipelines-agent/assets/106314398/30b4c588-da47-4807-8d8a-2a06c4633d4b).

**Comment by v1ferrarij** [comment]
> Got it, thanks! Yes, this is expected behaviour when you're using Azure Pipelines GitHub [App](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#github-app-authentication) for authentication. When you perform a checkout step it executes under a new token created by Azure Pipelines GitHub App and authenticates as a GitHub App [installation](https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#about-github-app-installations), unfortunately, such tokens expire after [1hour](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app) and, unfortunately, we can't control the behaviour. ![image](https://private-user-images.githubusercontent.com/106314398/313628965-30b4c588-da47-4807-8d8a-2a06c4633d4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDAxOTgsIm5iZiI6MTcxMDgzOTg5OCwicGF0aCI6Ii8xMDYzMTQzOTgvMzEzNjI4OTY1LTMwYjRjNTg4LWRhNDctNDgwNy04ZDhhLTJhMDZjNDYzM2Q0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwOTE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTY0NzdmMDg3YWNlNTdkNDRmMGRjZTdmMWZhOTI5ZDg2MDUxODg1MzI4ZGM5NDJhYzdjZDM2ODY4YmMzNDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BhuyJPw7kiLF7UfR9EHnXFQywESqxyas2zR7f4gHrtM).

Ah okay that makes sense, do you know if the behaviour is different when using OAuth connection?

I have a workaround which is working, which was to put the Git commands in a separate job which only runs depending on the previous job, this works, but not ideal I guess.

**Comment by v1ferrarij** [comment]
@DmitriiBobreshev  Hi again,
Do you know if the access token this step sets includes permission to call the GitHub API ?

```
steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0
```

**Comment by v1ferrarij** [comment]
Hey @DmitriiBobreshev 
Ah no worries, I managed to get the token from the step I sent, but it looks like the token does not have permission to call the GitHub API, only clone and read repos.
I was trying to avoid setting up a token in GitHub as its more to maintain and port over to ADO.
Thanks
