### ISSUE TITLE
[Question]: How to remove/override ProxyBypassList/no_proxy 

### ISSUE THREAD

**Issue by madacsbotond** [microsoft/azure-pipelines-agent#4718]
### Describe your question

I have a problem, that my pipelines are failing on our self-hosted agents. 
Everything is fine, until the Publish Pipeline Metadata step. 
I can see that my agent.proxybypasslist contains a list of addresses like: ["localhost","127\\.0\\.0.*", "\\.someaddress\\.cloud"] and the step fails with an error message: ##[error]Unhandled: Invalid regular expression: /*\.someaddress\.cloud/: Nothing to repeat.

At my agent at tha capabilities menu I can see that a no_proxy system capability is set to the same as agent.proxybypasslist (["localhost","127\\.0\\.0.*", "\\.someaddress\\.cloud"]). 
How can I manually override this setting? 
I made a file called .proxybypass at my self hosted agent directory, which contains just the localhost address. 
I tried creating a user-defined capability with a name and value VSO_AGENT_IGNORE = no_proxy,NO_PROXY,NoProxy. 
Also tried overriding it from the pipeline with a variable agent.proxybypasslist.

Where does this no_proxy variable comes from? If I print out env variables and grep for "no_proxy" I cannot find someaddress.cloud in it (tried restarting VM, restarting service, updating env variables with env.sh). 
What can or should I do to remove or change/override this no_proxy variable? 

### Versions

3.236.1 / Ubuntu 20.04.6 LTS

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04.6 LTS

### Version controll system

git & github

**Comment by KonstantinTyukalov** [comment]
@madacsbotond, `no_proxy` is an agent knob variable which is only obtained from the process environment where the agent started. Please make sure this variable is not specified/specified correctly when you configure/run your agent.

**Comment by madacsbotondpal** [comment]
Thank you for your repply, but I don't really know where does that variable comes from, at my service users environmental variables I cannot see where that someaddress.ai comes from. My users no_proxy env variable is not the same as I can see at the capabilities.

**Comment by madacsbotond** [comment]
Hi,
It is one of my other profiles, but still waiting for an answer.

**Comment by KonstantinTyukalov** [comment]
@madacsbotond @madacsbotondpal could you check environment variables of process where agent is started, and agent diagnostic logs?
You can view agent logs by following this [instruction](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops&tabs=windows-agent)
