### ISSUE TITLE
[BUG]: --enableservicesidtypeunrestricted flag not documented

### ISSUE THREAD

**Issue by paulhickman-ec** [microsoft/azure-pipelines-agent#4728]
### What happened?

Run .\config --help

The flag --enableservicesidtypeunrestricted that was added in #3795 is not documented.

### Versions

3.236

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022

**Comment by KonstantinTyukalov** [comment]
Hi @paulhickman-ec, thanks for the reporting! We are working on higher priority issues now, but we'll get back to this one soon

**Comment by vmapetr** [comment]
Hi @paulhickman-ec, we updated the [agent documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops), with information about `enableservicesidtypeunrestricted` flag for agent 2.* and 3.* versions.

**Comment by finisl** [comment]
> Hi @paulhickman-ec, we updated the [agent documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops), with information about `enableservicesidtypeunrestricted` flag for agent 2.* and 3.* versions.

Thanks! I was just looking for this 5 minutes ago.
