### ISSUE TITLE
[BUG]: error NU1102: Unable to find package <packagename> with version from Private Nuget Feed

### ISSUE THREAD

**Issue by ISAF87** [microsoft/azure-pipelines-agent#4732]
### What happened?

The scenario:
We updated a nuget package that we published to our private nuget feed (in Azure Devops). All well here, proper version, no pre-release.
Next we update the package in the solution to use it, without issue. So the publish of the package is working as expected.

When we commit our changes and deploy the application or website, the nuget restore fails. In general this works fine, but if we have multiple new versions of the nuget package, say within the hour, we notice it fails in the DotNetCoreCLI@2 step.

Part of the log:
error NU1102: Unable to find package Packages.Models with version (>= 2024.3.25.8) 
error NU1102: - Found 46 version(s) in feed-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx [ Nearest version: 2024.3.25.7 ] 
error NU1102: - Found 0 version(s) in NuGetOrg 

When looking at the .nuget/packages folder on the build server, the nearest version package is indeed the latest version it has of that particular package (2024.3.25.7)
I do notice that 2024.3.25.3, 2024.3.25.5 and 2024.3.25.8 (latest) are missing from the folder. Would suspect more versions are missing compared to the feed, but not all eventually make it into a production release.

We are running 2 buildagents on the same server, running on the same service account, so sharing the nuget package folder.

Could there be caching involved?

### Versions

Agent Version: 3.326.1
Windows version: Windows Server 2019 Datacenter

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by ISAF87** [comment]
note: a requeue after about an hour works as expected.

**Comment by vmapetr** [comment]
Hi @ISAF87, thank you for reporting this issue!
I'm closing this issue since it been resolved, please reopen it if the issue reoccurs.

**Comment by ISAF87** [comment]
It is not resolved, just less urgent because after a certain amount of time requeuing the build/release does work.
Every now and then this still occurs.
