### ISSUE TITLE
[BUG]: Azure pipeline credentials expire unexpectedly before job's maximum duration

### ISSUE THREAD

**Issue by fabrideci** [microsoft/azure-pipelines-agent#4736]
### What happened?

Our Azure DevOps YAML pipeline utilizes an ARM service connection with workload identity federation via OpenID Connect for Azure access. The pipeline operates smoothly until approximately the 55th minute mark, at which point the environment credentials seem to vanish, as indicated by the error output below. Although we recognize the default 60-minute job timeout, it’s unclear if this issue is related to that timeout or if it’s associated with the OIDC token’s lifecycle.

**EDIT**: actually, since we've bought 3 Microsoft-hosted parallel jobs, according to [your documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#capabilities-and-limitations) each job should have the capacity to run for up to 360 minutes (6 hours). Hence, it's definitely an issue if the underlying environment credentials vanish just after ~60 minutes by default.

### Versions

3.236.1 / Ubuntu

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04.4 LTS

### Relevant log output

```shell
AggregateAuthenticationError: ChainedTokenCredential authentication failed.
CredentialUnavailableError: EnvironmentCredential is unavailable. No underlying credential could be used. To troubleshoot, visit https://aka.ms/azsdk/js/identity/environmentcredential/troubleshoot.
CredentialUnavailableError: WorkloadIdentityCredential: is unavailable. tenantId, clientId, and federatedTokenFilePath are required parameters. 
      In DefaultAzureCredential and ManagedIdentityCredential, these can be provided as environment variables - 
      "AZURE_TENANT_ID",
      "AZURE_CLIENT_ID",
      "AZURE_FEDERATED_TOKEN_FILE". See the troubleshooting guide for more information: https://aka.ms/azsdk/js/identity/workloadidentitycredential/troubleshoot  
CredentialUnavailableError: ManagedIdentityCredential: The managed identity endpoint is indicating there's no available identity. Message: invalid_request Status code: 400
```

**Comment by fabrideci** [comment]
@vmapetr

**UPDATE**: actually, since we've bought 3 Microsoft-hosted parallel jobs, according to [your documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#capabilities-and-limitations) each job should have the capacity to run for up to 360 minutes (6 hours). Hence, it's definitely an issue if the underlying environment credentials vanish just after ~60 minutes by default.

**Comment by vmapetr** [comment]
Hi @fabrideci  thanks for reporting! 
We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by fabrideci** [comment]
Hello @vmapetr , did you have any chance to look into this? The issue has been opened for a few months now without any feedback. Thank you!

**Comment by fabrideci** [comment]
For whoever's facing this particular issue, I managed to resolve the `CredentialUnavailableError: EnvironmentCredential is unavailable. No underlying credential could be used.` error by following the related troubleshooting instructions at [Troubleshoot an Azure Resource Manager workload identity service connection](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/troubleshoot-workload-identity?view=azure-devops#error-messages), by creating a workload identity service connection which uses managed identity authentication - Managed Identity tokens have a [lifetime of around 24 hours](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/managed-identities-faq#are-managed-identities-tokens-cached).

**Comment by presidio-ddg** [comment]
@fabrideci Thx! Confirming this solved our issues too. The new (working) service connection's subj identifier has the format 
`/eid1/c/pub/t/` whereas the previous one had `sc://`
