### ISSUE TITLE
[BUG]: Pipeline fails with Failed to create CoreCLR, HRESULT: 0x80004005 

### ISSUE THREAD

**Issue by lewisoptellum** [microsoft/azure-pipelines-agent#4741]
### What happened?

All my self hosted devops pipelines are failing with `Failed to create CoreCLR, HRESULT: 0x80004005 ` . I am not aware of any updates which have caused this. I have seen the solution [here](https://stackoverflow.com/questions/68349359/unable-to-configure-a-new-agent-failed-to-create-coreclr-hresult-0x80004005) and tried it with no luck.

### Versions

Ubuntu 22.04.2 LTS
Agent 3.236.1
dotnet 8.0.203

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04.2 LTS

### Version controll system

git

### Relevant log output

```shell
##[error]Failed to create CoreCLR, HRESULT: 0x80004005
,##[error]We stopped hearing from agent fern00. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
```

**Comment by vmapetr** [comment]
Hi @lewisoptellum thanks for reporting! 
We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by lewisoptellum** [comment]
Thanks a lot. Do you have any suggestions for a work around at the minute? Currently our entire CI is blocked by this issue is all.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lewisoptellum** [comment]
Adding the following to `runsvh.sh` solved the issue:

```bash
# insert anything to setup env when running as a service
export COMPlus_EnableDiagnostics=0
```

**Comment by cliedeman** [comment]
I am having the same intermittent issue and don't know how to debug it.

@lewisoptellum How did you figure out that solution?

**Comment by rw-SebastianSzemer** [comment]
issue is still reproducible

**Comment by koppor** [comment]
Happens here afterr a recent update of an Ubuntu 24.04 system.
