### ISSUE TITLE
[BUG]: Agent does not support preview versions of Microsoft.VisualStudio.Product.BuildTools

### ISSUE THREAD

**Issue by Nico-1987** [microsoft/azure-pipelines-agent#4747]
### What happened?

We deployed a preview version of the Visual Studio Build Tools (17.10.0-preview2) on our build server.
When setting up a new agent, the expected Visual Studio system capabilities for VS are not set.
(MSBuild_17.0, MSBuild_17.0_x64, VisualStudio, VisualStudio_17.0, VisualStudio_IDE, VisualStudio_IDE_17.0)

We traced it down to the VisualStudioFunctions.ps1 file that does not search for the prerelease versions of the BuildTools, only for the real Visual Studio editions.

Please add logic to the agents to support the preview versions of the Build Tools.
When adding " -prerelease" to the vswhere.exe line in the VisualStudioFunctions.ps1 script, the agent works properly.
https://github.com/microsoft/azure-pipelines-agent/blob/db013b8f5114bf4fbc5008a23a90e17325fe04ce/src/Misc/layoutbin/powershell/CapabilityHelpers/VisualStudioFunctions.ps1#L41

### Versions

Reproduced in 3.225.3, confirmed in the sources the issue still exists

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2022 Update 1

### Operation system

Windows 10

### Version controll system

Git

**Comment by Nico-1987** [comment]
Additionally, is there any documentation on how to set the IncludePrereleaseVersions flag?
Is this supposed to be set as a system variable?

       if($env:IncludePrereleaseVersions -eq $true)
        {
            $preReleaseFlag = "-prerelease"
        }

**Comment by ivanduplenskikh** [comment]
@Nico-1987, could you [set environment variable](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4#use-the-variable-syntax) **IncludePrereleaseVersions** before execution?

Example:
```powershell
$env:IncludePrereleaseVersions = $true
# Execute necessary script that uses IncludePrereleaseVersions variable
```

**Comment by Nico-1987** [comment]
> @Nico-1987, could you [set environment variable](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4#use-the-variable-syntax) **IncludePrereleaseVersions** before execution?
> 
> Example:
> 
> ```powershell
> $env:IncludePrereleaseVersions = $true
> # Execute necessary script that uses IncludePrereleaseVersions variable
> ```

Yes i have tried that.
If you look at the script you can see the Preview flag is only used for the Enterprise lookup, not for the build scripts.
I think you need to add the $preReleaseFlag into line 41, to ensure its actually used

**Comment by ivanduplenskikh** [comment]
@Nico-1987, I've created a [PR](https://github.com/microsoft/azure-pipelines-agent/pull/4791) with adding `-prerelease` flag to lookup vsbuildtools.

The environment variable `$env:IncludePrereleaseVersions` is set in [PowerShellCapabilitiesProvider.cs](https://github.com/microsoft/azure-pipelines-agent/blob/5341d766e62377d8b68739b72ca84da79be5d24b/src/Microsoft.VisualStudio.Services.Agent/Capabilities/PowerShellCapabilitiesProvider.cs#L33) by enabling an agent knob [EnableVSPreReleaseVersions](https://github.com/microsoft/azure-pipelines-agent/blob/5341d766e62377d8b68739b72ca84da79be5d24b/src/Agent.Sdk/Knob/AgentKnobs.cs#L463) therefore to lookup for prerelease version, you can set `$env:ENABLE_VS_PRERELEASE_VERSIONS` to `$true`

**Comment by Nico-1987** [comment]
Looks good, thanks

**Comment by ivanduplenskikh** [comment]
[The agent](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.240.0) with this change is now available for use.
