### ISSUE TITLE
[enhancement]: Build Agent still does Not Discover Xamarin/Android Capabilities with VS 2022

### ISSUE THREAD

**Issue by jeoffman** [microsoft/azure-pipelines-agent#4751]
### What happened?

agent does not automatically pick up VS2022 installed - i.e. Agent doesn't recognize Xamarin SDKs and automatically find capabilities

You have to manually add the capabilities to the agent so it will pick up Xamarin jobs

### Versions

Build Agent - all

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Server 2022

**Comment by ivanduplenskikh** [comment]
Hi @jeoffman thanks for contribution! Let us take a look.

**Comment by ivanduplenskikh** [comment]
@jeoffman, could you please create your PR from the original repository not a fork?

**Comment by ivanduplenskikh** [comment]
@jeoffman, I've cherry-picked your changes to a new [PR](https://github.com/microsoft/azure-pipelines-agent/pull/4792)

**Comment by ivanduplenskikh** [comment]
[The agent](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.240.0) with this change is now available for use.
