### ISSUE TITLE
[BUG]: Runs in Azure Self-Hosted agent are not following FIFO principle

### ISSUE THREAD

**Issue by biswajitsamal59** [microsoft/azure-pipelines-agent#4770]
### What happened?

I have one self-hosted azure pipeline agent and one pipeline. The pipeline is getting triggered on any merge to develop branch. 1 pipeline run takes around 4 hour. Within 30m span 5 developers committed code to develop branch. It triggered 5 runs on that one agent. 1 is running and 4 are in pipeline queue. How agent is going to execute those 4 pending runs. Is it on first in first out (FIFO) principle or something else? In my case 4th run got executed before 2nd run (This is not happening always). And there is no manual intervention to bump-up the run in the queue. 

### Versions

Agent Version 3.227.2 / Windows 10

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 10

**Comment by aleksandrlevochkin** [comment]
Hi @biswajitsamal59, thank you for reporting this issue. To my knowledge, the pipeline queue must follow the FIFO principle. If you experience any problems related to that, please open a ticket on https://developercommunity.visualstudio.com/AzureDevOps, as the agent assignment and orchestration happen on ADO side.

As for your point about manual intervention, I believe you may use the Run next button to bump the priority of a queued job: https://learn.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-175-update#run-this-job-next

**Comment by rdebath** [comment]
@aleksandrlevochkin Yeh, no. It's not FIFO, looks random to me. I get jobs running before jobs that were queued an hour earlier every day.
