### ISSUE TITLE
[enhancement]: Update to dotnet 8

### ISSUE THREAD

**Issue by Meir017** [microsoft/azure-pipelines-agent#4780]
### Describe your feature request here

current dotnet version used is dotnet 6

```xml
<TargetFramework>net6</TargetFramework>
<RuntimeFrameworkVersion>6.0.26</RuntimeFrameworkVersion>
```

dotnet 8 was released back in November 2023, dotnet 6 is reachind EOL by November 2024

**Comment by DenisNikulin5** [comment]
Hi @Meir017
The agent team knows this. Of course, the agent will be updated before dotnet 6 reaches EOL. Thank you!

Can I close this issue?
