### ISSUE TITLE
[BUG]: Slowed down builds on hosted agents

### ISSUE THREAD

**Issue by Jens-Schmitt** [microsoft/azure-pipelines-agent#4781]
### What happened?

Since 10.04.2024 our build no longer takes 25 minutes, but suddenly more than 60 minutes. After approx. 10 min => 30-40 build tasks the CPU is at 100% and remains at this value. Then all tasks are delayed until the pipeline timeout occurs after 2 hours.

No changes on the build definition yaml file, no code changes. Image type: windows-latest.

### Versions

Current agent version: '3.236.1'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Current image version: '20240407.1.0'

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Version controll system

GIT

**Comment by KonstantinTyukalov** [comment]
Hi @Jens-Schmitt, could you please also share pipeline yaml slice to reproduce the issue?

**Comment by Jens-Schmitt** [comment]
[Build-enc.m.yml.txt](https://github.com/microsoft/azure-pipelines-agent/files/15188756/Build-enc.m.yml.txt)

**Comment by Jens-Schmitt** [comment]
@DenisNikulin5: The agent logs contain private information that I am not allowed to share. I could extract the task headers - if that would be enough...?

**Comment by KonstantinTyukalov** [comment]
@Jens-Schmitt  could you please create a ticket in [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps) to have a private communication channel?
Agent logs would really help us to investigate the root cause of the issue, so please share with us all the info which is possible in your case.
If you decide to send us the agent logs, please do so in a private conversation and ensure that all sensitive data is removed.
Thank you

**Comment by Jens-Schmitt** [comment]
You can find the logs here: https://developercommunity.visualstudio.com/t/Slowed-down-build-on-hosted-agent/10638569

**Comment by Jens-Schmitt** [comment]
$(AZP_ENABLE_RESOURCE_UTILIZATION_WARNINGS) has apparently been removed today.

We are back to normal. The builds run again for 25 min. There is no longer a timeout after 2 h. The CPU no longer goes to 100%.

Thanks for the investigation and the effort.

**Comment by pratiksoni1408** [comment]
Hello Jens,

May I know what the root cause was as I am facing same issue.
