### ISSUE TITLE
[Question]: TF200016: The following project does not exist: 1ESPipelineTemplates.

### ISSUE THREAD

**Issue by Allanrocksti** [microsoft/azure-pipelines-agent#4783]
Good afternoon guys

I have a modified version of azure-pipelines-agent to support correctly the OpenShift.
I'm trying to update the azure-pipelines-agent to version 3.238.0 but, I had this problem on run pipeline:

`/xxx.yml: TF200016: The following project does not exist: 1ESPipelineTemplates. Verify that the name of the project is correct and that the project exists on the specified Azure DevOps Server.`

But I'm not have modified any pipeline files of this project, and I don't have idea where to find 1ESPipelineTemplates repository.
I had seen only topics making a migration to 1ESPipelineTemplates, but I don't find 1ESPipelineTemplates repository or file.
Any guys can give me a help?

### Versions

azure-pipelines-agent version 3.238.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by ivanduplenskikh** [comment]
@Allanrocksti, these are internal templates.
You may revert this (PR)[https://github.com/microsoft/azure-pipelines-agent/pull/4670]

**Comment by ivanduplenskikh** [comment]
Hi @Allanrocksti, I'm closing this one - feel free to ask any other questions or let us know if it's still relevant for you.
