### ISSUE TITLE
[Question]: Offline upgrade of Deployment targets

### ISSUE THREAD

**Issue by hedasp** [microsoft/azure-pipelines-agent#4785]
### Describe your question

For offline Deployment targets(doubling as environment targets too) we try to upgrade the installed agent using the "Upgrade targets" option in Azure DevOps UI for the Deployment group. 
This triggers the src/Agent.Listener/SelfUpdater.cs script as expected and tries to download the current version 'https://vstsagentpackage.azureedge.net/agent/3.238.0/vsts-agent-win-x64-3.238.0.zip' to 'C:\agentfolder\_work\_update\agent1.zip'
This fails, due to lacking firewall opening. 

The following should be an option according to this documentation: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents
"For servers with no internet access, manually copy the agent zip file to the following folder to use as a local file. Create the Agents folder if it is not present.
Windows: %ProgramData%\Microsoft\Azure DevOps\Agents"

But the SelfUpdater does not check this folder at all. 
Adding the zip file directly to the '_work\_update\' folder does not work either, as it's cleaned when update script is running. Renaming it to "agent1.zip" did nothing either. 

What is the recommended approach for upgrading offline deployment groups? 

### Versions

Azure DevOps Agent Version: 3.224.1
Windows Server 2022
Azure DevOps Services

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 2022

### Version controll system

Azure Repo

**Comment by ivanduplenskikh** [comment]
@hedasp, have you attempted to place the agent zip file on Azure DevOps Server machine?
From your description it looks like you tried to place the agent on the machine that runs the agent itself

**Comment by hedasp** [comment]
We use Azure DevOps Service - so we don't have our own Azure DevOps Servers to place the agent zip file. 
The machine that runs the agent itself tries to download the zip from the official URL, so the question is if we could point it to a local path containing the zip file with updated version instead.

**Comment by ivanduplenskikh** [comment]
@hedasp, in this context, you have two options. You may either configure your security system settings as per [the documentation](https://learn.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4) which includes setting up allowed address lists and network connections, or you can manually install the latest version of the agent.

Also, there is [an issue](https://github.com/microsoft/azure-pipelines-agent/issues/4397) that can be related

**Comment by hedasp** [comment]
@ivanduplenskikh thanks for getting back to me so quickly. 
So basically, manually install the latest version = re-configuring the agent? 
Will lose some history then I guess, so not super ideal.

**Comment by ivanduplenskikh** [comment]
@hedasp, in this case you have the option to replace the old agent version with the new agent version.
The **credentials** files and **_work**/**_diag** folders will be preserved.

**Comment by hedasp** [comment]
Thanks for getting back to me,@ivanduplenskikh 
" replace the old agent version with the new agent version " This is probably what I'm looking for, but the question is how to actually do this.

**Comment by ivanduplenskikh** [comment]
@hedasp, you may download the release from the [releases](https://github.com/microsoft/azure-pipelines-agent/releases) page and extract it to the existing directory.

An example would be:
```powershell
Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$HOME\Downloads\vsts-agent-win-x64-agent-version.zip", "agent_directory", $true)
```

In this way, files and directories which were generated by the agent will be persist.
