### ISSUE TITLE
When I was using the Agent, I found that the Windows-64-bit compressed package for version 3.238.0 does not contain the externals/node10 folder.

### ISSUE THREAD

**Issue by zhenyu-lan** [microsoft/azure-pipelines-agent#4790]
### What happened?

When I was using the Agent, I found that the Windows-64-bit compressed package for version 3.238.0 does not contain the externals/node10 folder. The download link is: https://vstsagentpackage.azureedge.net/agent/3.238.0/vsts-agent-win-x64-3.238.0.zip.

### Versions

3.238.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

windows server 2022

**Comment by ivanduplenskikh** [comment]
@zhenyu-lan, the agent from attached link contains the node10 folder:
```
vsts-agent-win-x64-3.238.0.zip\externals\node10\bin
```
Could you double check it please?

**Comment by zhenyu-lan** [comment]
![image](https://github.com/microsoft/azure-pipelines-agent/assets/62124738/8841bd7b-6846-4723-b8bf-7c722d11d416)

**Comment by zhenyu-lan** [comment]
I well renew download again ,
![image](https://github.com/microsoft/azure-pipelines-agent/assets/62124738/6e305349-52b6-4e22-ba8b-5ce833add5fc)

**Comment by ivanduplenskikh** [comment]
@zhenyu-lan, there are two versions of agent packages.
The **vsts-agent-*** includes Node 6 and Node 10, whereas the **pipelines-agent-*** does not.
The [PR](https://github.com/microsoft/azure-pipelines-agent/pull/4737) that removes Node 10 has been merged.
Additionally, a [PR](https://github.com/microsoft/azure-pipelines-agent/pull/4773) for updating the documentation is underway.

If you need to use Node 10 in your pipelines, you can add the [UseNodeV1](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-node-v1?view=azure-pipelines) step.

**Comment by ivanduplenskikh** [comment]
Hi @zhenyu-lan, I'm closing this one as external - feel free to ask any other questions or let us know if it's still relevant for you.
