### ISSUE TITLE
[Question]: Azure DevOps Agent Service vs SMS Agent Host Service 

### ISSUE THREAD

**Issue by hedasp** [microsoft/azure-pipelines-agent#4800]
### Describe your question

When upgrading the Agent Service to newer version on deployment target group, we faced an issue where ccmexec(SMS Agent Host Service) process was holding files in /externals folder even after Agent Service was stopped. 
typically files in /externals/tf/ and /externals/git/ 
Any insight on what these processes are and how to make sure they finish in time for the self-upgrade script to run successfully? 
As long as the process was active, the script couldn't rename/move the externals folder.
Also, to re-run the _update.cmd script, we had to rename the /bin folder from versioned to just bin again. 

### Versions

Azure DevOps Agent 3.220.2->3.238.0
Windows Server 2022

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 2022

### Version controll system

Azure Repo

**Comment by kirill-ivlev** [comment]
Hi @hedasp!
thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon
