### ISSUE TITLE
[Question]: 401 when running `./src/dev.sh layout` or `build`, no local versions of microsoft.aspnetcore.app.ref

### ISSUE THREAD

**Issue by lettucemode** [microsoft/azure-pipelines-agent#4817]
### Describe your question

I followed the instructions [here](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/contribute.md). Upon running `/src/dev.sh layout`, it mostly succeeded, but failed during the restore step with the below error. Subsequent runs of `build` produce the same error.

```
-----------------------------------------
  Building
-----------------------------------------
MSBuild target = Build
MSBuild version 17.9.8+610b4d3b5 for .NET
  4c7bc633572b50c0ee2e0b218805563cdc7979ea
  Building 4c7bc633572b50c0ee2e0b218805563cdc7979ea --- win-x64
  Determining projects to restore...
  Failed to download package 'Microsoft.WindowsDesktop.App.Ref.6.0.30' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_
  packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.windowsdesktop.app.ref/6.0.30/microsoft.windowsdesktop.app.ref.6.0.30.nupk 
  g'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.windowsdesktop.app.ref'; please provid 
  e authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: 43C4F9C7-2492-46EB-99DA-1BF1477F 
  A698)).

<omit many more lines of the above due to retries>

Failed: build
~/source/repos/azure-pipelines-agent
```
According to #4327 it appears that a package needs to be saved to this feed. I am external to Microsoft, so I don't think I can provide any valid authentication. If there's anything I can do to resolve, just let me know.

### Versions

latest code from master
Windows 11
git version 2.39.0.windows.2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Version controll system

Git

**Comment by KonstantinTyukalov** [comment]
Hi @lettucemode I'm unable to reproduce your issue. Could you try to run `git clean -xfd` in the repo root?
What does the `dotnet restore` command return?

**Comment by lettucemode** [comment]
@KonstantinTyukalov as it turns out, as of 10 minutes ago, the `build` & `layout` commands are working as expected. I then ran `git clean -xfd` and then `dotnet restore` in the root per your suggestion, and there are no errors. 
```
$ dotnet restore
  Determining projects to restore...
  Restored C:\Users\2know\source\repos\azure-pipelines-agent\src\Agent.Plugins\Agent.Plugins.csproj (in 637 ms).
  Restored C:\Users\2know\source\repos\azure-pipelines-agent\src\Agent.Sdk\Agent.Sdk.csproj (in 643 ms).
  Restored C:\Users\2know\source\repos\azure-pipelines-agent\src\Microsoft.VisualStudio.Services.Agent\Microsoft.VisualStudio.Services.Agent.csproj (in 642 ms).
  Restored C:\Users\2know\source\repos\azure-pipelines-agent\src\Test\Test.csproj (in 641 ms).
  Restored C:\Users\2know\source\repos\azure-pipelines-agent\src\Agent.PluginHost\Agent.PluginHost.csproj (in 663 ms).
  Restored C:\Users\2know\source\repos\azure-pipelines-agent\src\Agent.Listener\Agent.Listener.csproj (in 671 ms).
  Restored C:\Users\2know\source\repos\azure-pipelines-agent\src\Agent.Worker\Agent.Worker.csproj (in 674 ms).
```
Thanks for your time spent looking into this! I'll go ahead and close.

**Comment by lettucemode** [comment]
@KonstantinTyukalov as it turns out, as of 10 minutes ago, the `build` & `layout` commands are working as expected. I then ran `git clean -xfd` and then `dotnet restore` in the root per your suggestion, and there are no errors. 
```
$ dotnet restore
  Determining projects to restore...
  Restored ...\source\repos\azure-pipelines-agent\src\Agent.Plugins\Agent.Plugins.csproj (in 637 ms).
  Restored ...\source\repos\azure-pipelines-agent\src\Agent.Sdk\Agent.Sdk.csproj (in 643 ms).
  Restored ...\source\repos\azure-pipelines-agent\src\Microsoft.VisualStudio.Services.Agent\Microsoft.VisualStudio.Services.Agent.csproj (in 642 ms).
  Restored ...\source\repos\azure-pipelines-agent\src\Test\Test.csproj (in 641 ms).
  Restored ...\source\repos\azure-pipelines-agent\src\Agent.PluginHost\Agent.PluginHost.csproj (in 663 ms).
  Restored ...\source\repos\azure-pipelines-agent\src\Agent.Listener\Agent.Listener.csproj (in 671 ms).
  Restored ...\source\repos\azure-pipelines-agent\src\Agent.Worker\Agent.Worker.csproj (in 674 ms).
```
Thanks for your time spent looking into this! I'll go ahead and close.
