### ISSUE TITLE
Cannot get Visual Studio prerelease version detection to work

### ISSUE THREAD

**Issue by avivanoff** [microsoft/azure-pipelines-agent#4819]
### Describe your question

I am trying to get prerelease version of Visual Studio to work. So far I was trying to set ENABLE_VS_PRERELEASE_VERSIONS or IncludePrereleaseVersions environment variables with no luck. Since this is the first time I am trying to use agent knobs, do I even do this right?

### Versions

3.239.1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by KonstantinTyukalov** [comment]
Hi @avivanoff, could you show how you specify this variable?

**Comment by avivanoff** [comment]
I was able to get it to work.
