### ISSUE TITLE
[enhancement]: Log output to console and file at the same time

### ISSUE THREAD

**Issue by srkidd** [microsoft/azure-pipelines-agent#4825]
### Describe your feature request here

Is it possible to output the log to console and file at the same time? We have requirements where we want to still see the live output from the agent but want to upload the log to our own observability stack at the end of a pipeline run. I see the agent has `-- disableloguploads` but this would only get use the file part and we would lose the live stream to the service.

**Comment by srkidd** [comment]
https://github.com/srkidd/azure-pipelines-agent/tree/users/srkidd/enable-stream-and-file-output

I have created a fork and got it working. I have tested locally.

**Comment by vmapetr** [comment]
Hi @srkidd thanks for reporting! 
We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by srkidd** [comment]
Created a PR for it

https://github.com/microsoft/azure-pipelines-agent/pull/4829

**Comment by vmapetr** [comment]
Closing the issue, since the related changes were merged in this PR: https://github.com/microsoft/azure-pipelines-agent/pull/4920 
Thank you for your contribution!
