### ISSUE TITLE
Build issues with new agent 3.240.1

### ISSUE THREAD

**Issue by meetsekhar** [microsoft/azure-pipelines-agent#4834]
### Describe your question

We are seeing build failures in NET6.0 App. 

`Error CS***25: Invalid expression term ''`
`Error CS1646: Keyword, identifier, or string expected after verbatim specifier: @`

Didn't have this problem when using 3.239.1..  Here is what we tried

1. Added a UseDotNet@2 -- sdk 
`Tool to install: .NET Core sdk version 6.x.`
`Found version 6.0.423 in channel 6.0 for user specified version spec: 6.x`

Agent downloaded 6.0.423 and we had successful build but failed when publishing nuget package due to size limitation on the nuspec file. 

2. Added a UseDotNet@2 -- runtime 
   `Tool to install: .NET Core runtime version 6.x.`
   `Found version 6.0.31 in channel 6.0 for user specified version spec: 6.x`
   
  Build still failed.. 
  

Code builds on our local dev machine. 

Here is what we see in the last successful build --
`Agent name: 'Hosted Agent'`
`Current agent version: '3.239.1'`
`Operating System
Microsoft Windows Server 2022`
`10.0.20348`
`Datacenter`
`Runner Image`
`Image: windows-2022`
`Version: 20240514.3.0`
**`MSBuild version 17.9.8+610b4d3b5 for .NET`**

Any help appreciated

Regards

### Versions

Microsoft Hosted Agent -3.240.1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

Windows-latest

### Azure DevOps Server Version (if applicable)

Version Dev19.M239.1

**Comment by tkasparek** [comment]
Caused by new image version. Not related to agent.
