### ISSUE TITLE
[BUG]: Agent version 3.238.0 can't support TFVC Build pipelines

### ISSUE THREAD

**Issue by alben-zhu** [microsoft/azure-pipelines-agent#4842]
### What happened?

I have a pipeline about TFVC,but via version 3.238.0, it failed. via version 2.153.1 it success. Because 3.238.0 can't deal with "
Local path under $(build.sourcesDirectory)"
[6.txt](https://github.com/user-attachments/files/15832322/6.txt)
![11](https://github.com/microsoft/azure-pipelines-agent/assets/172742267/bd9c399b-4f11-4b82-989a-9644c06c8247)

### Versions

Agent version 3.238.0/winserver 2019

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2019.1

### Operation system

windows server 2019

**Comment by max-zaytsev** [comment]
>Because 3.238.0 can't deal with "Local path under $(build.sourcesDirectory)"

@alben-zhu can you clarify, please.  What is the expected behavior? What did you get on the 2.153.1 version and what do you see on the 3.238.0

Can you please share checkout step logs for both successful and unsuccessful runs?

**Comment by alben-zhu** [comment]
> > Because 3.238.0 can't deal with "Local path under $(build.sourcesDirectory)"
> 
> @alben-zhu can you clarify, please. What is the expected behavior? What did you get on the 2.153.1 version and what do you see on the 3.238.0
> 
> Can you please share checkout step logs for both successful and unsuccessful runs?
[successful.zip](https://github.com/user-attachments/files/15910244/successful.zip)
[unsuccessful.zip](https://github.com/user-attachments/files/15910245/unsuccessful.zip)
TFVC build pipeline will set a local path of the agent machine. 2.153.1 can recognize the local path,but 3.238 can't. please check the logs about the two files.

**Comment by max-zaytsev** [comment]
@alben-zhu I couldn't reproduce it. Could you please enable the debug mode and send again the logs for successful and not successful runs (including checkout step)

https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops&tabs=windows-agent#configure-verbose-logs

**Comment by alben-zhu** [comment]
[success.zip](https://github.com/user-attachments/files/16095648/success.zip)
[unsuccess.zip](https://github.com/user-attachments/files/16095652/unsuccess.zip)
@max-zaytsev
