### ISSUE TITLE
[Question]: scaled down agents are not shown in offline mode after upgrading to 3.241.0

### ISSUE THREAD

**Issue by sambitr** [microsoft/azure-pipelines-agent#4879]
### Describe your question

Hi There, After upgrading our docker-in-docker based self-hosted agents to 3.241.0, we are not seeing our scaled down agents in offline mode in the agent pool. I can see older versioned agents in offline mode though.

This is happening only when the cronjob automatically scaled down the agent pods in kubernetes. When we manually delete the agent pod, it appears in offline mode.

Every evening at 7 PM UTC, our agents scaled down from 30 to 12 pods and in the next morning at 7AM, they scale back to 30 pods. Those 18 agent pods who were scaled down, should be visible as offline in the agent pool section. But they are not.

Our older agent pods, who were in version 2.194.0 are shown as offline. 

Any new feature added to the version that does this?

### Versions

version 3.241.0

ubuntu:22.04

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu:22.04

**Comment by sambitr** [comment]
Can someone answer this? My agent deployment  just got scaled down and I don't see any offline agents any more. I need to understand how the agent is marked as offline. Because manually deleting the agent pod makes them offline in the agent pool. So why the scale down operation does not mark them as offline?

**Comment by ivanduplenskikh** [comment]
@sambitr, this issue appears to be related to AzureDevOps, as the agent hasn't changed to inform ADO that it's alive.
This repo is primarily for the agent - I would suggest opening a ticket on the [Azure DevOps Community](https://developercommunity.visualstudio.com/AzureDevOps) portal to get the right eyes on it.

**Comment by sambitr** [comment]
Thanks @ivanduplenskikh , I got response on the Azure DevOps community portal.
