### ISSUE TITLE
[Question]: How to do multiple conditions in a pipeline

### ISSUE THREAD

**Issue by GBCSIM1** [microsoft/azure-pipelines-agent#4887]
### Describe your question

I am looking to do multiple conditions in my pipeline which includes my parameters file and a value

Here is my paramters at the top of the Page:
parameters:
  - name: lzFileName
    displayName: 'LandingZone file name'
    type: string
    default: 'ccc_npd_testing.json'
  - name: serviceConnection
    displayName: 'Service connection name'
    type: string
  - name: doWhatIf
    displayName: 'Only do What If'
    type: boolean
    default: false
  - name: operationType
    displayName: 'operationType'
    type: string
    values: ['Create', 'Update']
    default: 'Create'
  - name: branchName
    displayName: 'Branch name of subscription'
    type: string

so originally i had one condition which if the update is selected on the pipeline: 

  - ${{ if startsWith(parameters.operationType, 'Update')}}:
  this works great.

However I want to add it so if its not equal to a 0 value on parameters file for budgetAmount:

  - ${{ if startsWith(parameters.operationType, 'Update'), ne(parameters.budgetAmount.value, '0')}}:
  
  This doesn't work. Any ideas? The parameter for the budget is specified within the code so not right at the top of the page.

### Versions

ubuntu-latest

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

**Comment by DmitriiBobreshev** [comment]
Hi @GBCSIM1, unfortunately, [runtime parameters](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script) are only available before the job started and not on the agent's side.

What you can do is add a [condition](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops) to your pipeline. [The conditions](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops#conditions-under-which-a-stage-job-or-step-runs) are evaluated before each step/job on the agent's side, so if you change the value of parameter/variable in some step, it will have an actual state when conditions are evaluated.
