### ISSUE TITLE
[enhancement]: Microsoft Hosted Agent is not taking stable version of chromedriver which is 126.0.6478.182 instead its taking 126.0.6478.126 which is causing session problems while executing selenium cases

### ISSUE THREAD

**Issue by HrishikeshRangdale-gep** [microsoft/azure-pipelines-agent#4899]
### Describe your feature request here

[enhancement]: Microsoft Hosted Agent windows 2022 image is not taking stable version of chromedriver which is 126.0.6478.182 instead its taking 126.0.6478.126 which is causing session problems while executing selenium cases

**Comment by vmapetr** [comment]
Hi @HrishikeshRangdale-gep, thank you for your request!
Latest Windows 22 image is delivered with the Chrome Driver 126.0.6478.126 by default (https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md). 
I'm closing this ticket as external one - this repo is related only to the AzDO agent issues - please open the ticket in the runner images repo (https://github.com/actions/runner-images/issues), to update the software on the image. 
Thanks!
