### ISSUE TITLE
[Question]: Azure DevOps YAML Pipelines are failing at default checkout task

### ISSUE THREAD

**Issue by PhanindraReddyP** [microsoft/azure-pipelines-agent#4902]
### Describe your question

Azure Pipelines are failing at default checkout task in all the agents in one of our self hosted agent machines with error "fatal: Cannot prompt because terminal prompts have been disabled."

### Versions

Version Dev19.M233.1 (AzureDevOps_M233_20240212.1)

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Version controll system

GIT

**Comment by vmapetr** [comment]
Hi @PhanindraReddyP, thank you for your question!
Could you please run the pipeline with the enabled debug logs (https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops&tabs=windows-agent#configure-verbose-logs) to provide more information about the issue?
