### ISSUE TITLE
[enhancement]: Specify which network the container should use instead of creating a new one

### ISSUE THREAD

**Issue by erstert3st** [microsoft/azure-pipelines-agent#4903]
### Describe your feature request here

Every 80 times the new NAT network created by Azure fails to connect to my network. 
You can use the  add options: "--network SecondNetwork", but Docker uses the first network as the primery one....
My solution is to use the SecondNetwork with:
 Set-NetIPInterface -InterfaceAlias "Ethernet 2" -InterfaceMetric 1,
Or is there a other solution ?

**Comment by vmapetr** [comment]
Hi @erstert3st, thank you for your report.
This looks like an external issue related to the Azure networking, while this repo is for the issues related to the Azure Agent, I would suggest to open a ticket on [AzureDevOps ](https://developercommunity.visualstudio.com/AzureDevOps) to get right eyes on it.
