### ISSUE TITLE
[BUG]: Oracle Linux (8.10) warns it is not supported

### ISSUE THREAD

**Issue by im-aIex** [microsoft/azure-pipelines-agent#4941]
### What happened?

After upgrading to Agent v3.243.0 the pipeline warns
> The operating system version this agent is running on (ol OS name: 8.10) is not supported on an upcoming update to the Pipelines Agent.

The agent is hosted on Oracle Linux 8.10, which should be the same as the supported RHEL.

### Versions

Agent: v3.243.0
OS: Oracle Linux 8.10

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Oracle Linux 8.10

**Comment by DenisRumyantsev** [comment]
@im-aIex thanks for reporting this! We will disable these warnings and include Oracle Linux (8+) into the list of supported OS.

**Comment by lareeth** [comment]
We are also getting this same error on Rocky 8 and 9 which are also RHEL derivatives

I had raised a PR to add Rocky support over a year ago with no response: https://github.com/microsoft/azure-pipelines-agent/pull/4116

**Comment by corppeon** [comment]
Alma Linux, another RHEL derivative is also being flagged as unsupported

**Comment by im-aIex** [comment]
> We will disable these warnings and include Oracle Linux (8+) into the list of supported OS.

Any update on disabling these warnings? @DenisRumyantsev

**Comment by zeinrich** [comment]
@DenisRumyantsev, I'm attempting to build an agent using either ol89-lvm or ol93-lvm.  In both cases, I'm now seeing this error when Azure DevOps attempts to deploy the agent service:

Azure Pipelines Extension failed with message: The Extension failed to execute: The current OS version will not be supported by the .NET 6 based v3 agent. See https://aka.ms/azdo-pipeline-agent-version

Oracle Linux 8.9 and 9.3 are on the list of supported versions (Oracle Linux 7 and above).

**Comment by lareeth** [comment]
This is due the following line in the vsts extension, checking if the system is in the `net6.json` file

https://github.com/microsoft/vsts-azurevm-extension/blob/22837968eaa91d3c687783af4d8955576dc9ab9c/ExtensionHandler/Linux/src/Utils/HandlerUtil.py#L542

Weirdly, the code in the extension hasn't changed, but this issue started at 16:00 UTC on the 4th of October, none of our custom agents have been able to launch since then. Unfortunately the vsts-azurevm-extension team don't publish release notes or tags that align with the code, so its hard to see what's changed and when.

**Comment by zeinrich** [comment]
Meanwhile the `net8.json` (https://raw.githubusercontent.com/microsoft/azure-pipelines-agent/master/src/Agent.Listener/net8.json) includes "ol" versions "8+".

We saw this issue at least as of the 3rd of October and possibly sooner.  Unfortunately our diagnostic logs don't go that far back, and I failed to make an accurate enough internal report to have a more exact timeframe.

**Comment by tgwbean** [comment]
@DenisRumyantsev I created a PR ([#5010](https://github.com/microsoft/azure-pipelines-agent/pull/5010)) to add ol 7+ (like mentioned in doku and as it is for rhel to net6.json.

This is blocking our VMSS instances from starting up and registering as agent.

**Comment by DenisRumyantsev** [comment]
Related changes were merged in the PR mentioned right above, so I close this issue.
