### ISSUE TITLE
[Question]: Self-hosted event hooks or ways to monitor job status?

### ISSUE THREAD

**Issue by frittsy** [microsoft/azure-pipelines-agent#4994]
### Describe your question

Hi there,

I'm looking for a way to know if a self-hosted agent is actively running a job or not, locally on the machine and not via polling the Azure DevOps API.

Is there any sort of event-based hook that I can utilize from the agent that will execute something when a job starts/ends? Or is there anything I can monitor on the filesystem that would indicate whether the agent is actively running a job or not?

Thank you in advance 

### Versions

Azure DevOps version 3.242.1 - Windows Server 2022
Azure DevOps version 3.240.1 - Ubuntu 22.04

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022, Ubuntu 22.04

### Version controll system

Git

**Comment by max-zaytsev** [comment]
@frittsy I'm not sure I understood your question correctly.

You can probably just check if the Agent.Worker process is running on your machine.
```
PS C:\Users\v-mazayt> Get-Process -Name Agent.Worker*

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    723      70    69924      99308       7.89  37600   2 Agent.Worker
```

**Comment by frittsy** [comment]
I just wanted to make sure there wasn't some built-in feature of the agent itself that I could leverage, that would run a custom script when a job starts for example.

But what you suggested will work for me, I can monitor for that process. Thank you for the idea!
