### ISSUE TITLE
JFYI: reported git bug that's relevant to build agents

### ISSUE THREAD

**Issue by elibarzilay** [Microsoft/azure-pipelines-agent#500]
> Version of my agent

2.104.1

> OS of the machine running the agent? OSX/Windows/Linux...

Linux, Ubuntu 14.04

> VisualStudio.com or On-Prem TFS?

VisualStudio.com

> If VisualStudio.com, what is your account name? http://account.visualstudio.com

elbarzil
## **What's not working?**

I have the token thing turned on in the build definition ("Allow Scripts to Access OAuth Token"), which makes the agent do a little dance of setting it and then unsetting it, which leaves the repo in the worker's source directory with many `[http "https://..."]` lines.

I've tracked this to a git bug which I reported: [here](https://public-inbox.org/git/CALO-gutdz5VMgoRmbqEa9UiaTC+L2Sy2n-3AF+zfPr-X8+1U4A@mail.gmail.com/) (Sorry about the weird url, gmane.org looks dead ATM.)  But just letting you know in case you'll want to hack around it, or in case there are other complaints.

**Comment by TingluoHuang** [comment]
@elibarzilay Thanks for report this, i noticed this problem while i am testing, I can fix the config file by call `git config --remove-section`, however, since we allow customer scripting git in build agent, they might add extra config value to that section. I understand having thousands of build per day will add lots of junk into the config file. I will think of finding a safe way to clean your config file.

**Comment by elibarzilay** [comment]
@TingluoHuang -- well, see the replies I got in that thread...  The main problem happens when adding a config variable to a file that already has an empty section -- git will miss it, and blindly add a new section header.  (This is combined with the fact that removing a variable and leaving a section header leaves the header in -- looks like they want to remove such headers too, which is more tricky.)

So a quick and not-too-dirty way to fix it would be to add a second setting that never changes:

    URL="https://foo.visualstudio.com/_git/bar"
    git config http.$URL.autoset true
    git config http.$URL.extraheader "AUTHORIZATION: bearer ********"
    ...
    git config --unset-all http.$URL.extraheader

And that will resolve it.  Of course, the bogus-but-looks-meaningful variable can be set to something that can actually be useful -- a quick look at the man page shows a number of potential candidates:

    git config http.$URL.sslVerify true
    git config http.$URL.maxRequests 1
    git config http.$URL.userAgent "git/$(git --version)/$(Agent.Listener --version)"

The last one is nice in that you get more version logging which can be useful.
