### ISSUE TITLE
[Question]: ,##[error]The hosted runner encountered an error while running your job. (Error Type: Disconnect). ,##[warning]Received request to deprovision: The request was cancelled by the remote provider.

### ISSUE THREAD

**Issue by nimblenitin** [microsoft/azure-pipelines-agent#5006]
### Describe your question

,##[error]The hosted runner encountered an error while running your job. (Error Type: Disconnect).
,##[warning]Received request to deprovision: The request was cancelled by the remote provider.

Getting this error while running build task for reactjs

### Versions

Image: ubuntu-latest
Agent: Hosted Agent

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Version controll system

azure devops

**Comment by ivanduplenskikh** [comment]
@nimblenitin, I found a remarkably [similar](https://developercommunity.visualstudio.com/t/an-error-occurred-while-provisioning-resources/831706) issue on the DevCommunity portal, and from the comments, it seems that it might be temporary problem on the backend side.
I recommend submitting a ticket at https://developercommunity.visualstudio.com/AzureDevOps to ensure the appropriate team can look into it.

**Comment by ivanduplenskikh** [comment]
@nimblenitin, I'm closing this issue for now. Feel free to reopen it if you have additional questions

**Comment by nimblenitin** [comment]
@ivanduplenskikh  the issue you shared seems to be specific to mac based image, we are using Ubuntu based image, can you please share if there is any specific limit on the ram and cpu for microsoft hosted agents?

**Comment by ivanduplenskikh** [comment]
@nimblenitin, for information on the hardware specifications of Microsoft Hosted agents, please consult [this documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware)
