### ISSUE TITLE
Need to be able to specify a fixed work folder for a build definition

### ISSUE THREAD

**Issue by drolevar** [microsoft/azure-pipelines-agent#706]
## **Agent version and platform**
2.106.0
Ubuntu 16.04.1 LTS
## **VSTS type and version**
On-Prem TFS 2015 QU3
## **What's not working?** 
Need to be able to specify a fixed work folder for a build definition.
Certain libraries embed source location inside them. Being able to set a fixed folder for a build definition will help to enable reproducible builds.

**Comment by ericsciple** [comment]
there is a `Don't sync sources` checkbox on the repository tab of the build definition now. you should update to a newer agent before using that feature though. from the agent pools UI you can click to update a pool

**Comment by ericsciple** [comment]
i'll assume that was a good solution. if you need control over the location, then i think that is a pretty good option. please reopen if i've missed something.

**Comment by drolevar** [comment]
Does the 'Update pool' function work with Linux agents?
Also, which release is this function introduced in?


Best regards,
Andrij Abyzov

**Comment by bryanmacfarlane** [comment]
@drolevar - yes, it started working reliably around 2.104+

**Comment by drolevar** [comment]
My current agent runs 2.106, as a systemd service. However, it's not
getting updated. Will check the logs.


Best regards,
Andrij Abyzov

**Comment by drolevar** [comment]
So, 2 questions:

1. Which version includes "Don't sync sources" option?
2. Update package apparently is downloaded from the TFS server. I'm using
on-prem TFS 2015 Update 3. Is that possible to use that to auto-upgrade
Linux agents? If yes, then where should I put the update packages?
Because now the log says "There is no package for agent and
ubuntu.16.04-x64"


Best regards,
Andrij Abyzov

**Comment by ericsciple** [comment]
sorry i missed that you are using an on prem release.

auto-update to a version greater than 2.106 wont work since your TFS server is still at 2015 U3. a record in the tfs db knows the latest version and your on-prem TFS instance only knows about the version it shipped with.

the "Don't sync source" UI option is currently only available on VSTS - will be included in TFS 2017 U1 on-prem release.

what you can do instead is set a variable SkipSyncSource to true. the 2.106 agent doesn't have the feature, so you will need to update your agent.

**Comment by drolevar** [comment]
Ok, found that one. If I understand correctly, setting this flag disables
all the repository mappings.
Then, if I understand correctly, case all the source handling logic has to
be reimplemented manually, including building with a shelveset, building a
certain changeset etc.
I guess, my task can be achieved by manually tweaking SourceFolder.json.


Best regards,
Andrij Abyzov

**Comment by ericsciple** [comment]
@chrisrpatterson @bryanmacfarlane to consider this scenario

ok, yes that is a lot of overhead.

fyi we are working on cleanup jobs, so if you manipulate the source mapping files, that folder may get deleted in the future.

**Comment by vtbassmatt** [comment]
This issue has sat undiscussed for over 3 years. If anyone needs us to consider something here, they should open a new issue.
