### ISSUE TITLE
NUnit 3 Test Results - Incorrect Test Duration values

### ISSUE THREAD

**Issue by plneto** [Microsoft/azure-pipelines-agent#754]
## **Agent version and platform**
Version of your agent?
Tried both 2.110.0 and v2.111.1
<br>
OS of the machine running the agent?
OSX
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
VisualStudio.com 
<br>
## **What's not working?** 
The test duration values are not being populated correctly when using NUnit 3 test results. 

The total duration seems to be populating the seconds correctly but it's ignoring the milliseconds.
It was 0:00:08.212 but it shows only 0:00:08.000. The individual tests are always showing 0s.

I ran the build once with all the sample test cases from the https://github.com/nunit/nunit.xamarin repository, and I also added 2 tests with Thread.Sleep to test the duration (test_duration - 3 seconds, failed_test_duration - 5 seconds).

Test Results: https://github.com/nunit/nunit.xamarin/files/706940/UnitTestsResults.xml.zip

![Screenshot](https://cloud.githubusercontent.com/assets/5697434/21966616/630f166e-dbc2-11e6-833b-2c803060241c.png)

**Comment by stephenmichaelf** [comment]
@plneto Are you still getting this issue?

I ran some tests and it seems to be accurate to the millisecond:

![image](https://user-images.githubusercontent.com/450490/29285745-88c6c164-80fd-11e7-9bc1-0ab11d048ee8.png)

I do see that yours says NUnit Test Runner, not sure how you had things setup. Mine is using NUnit3 and the VSTest Task.

**Comment by plneto** [comment]
@stephenmichaelf Yes, I'm still having this issue. I'm using https://github.com/nunit/nunit.xamarin to generate the test results. 

Does the format from my test results file look different to yours?

**Comment by TingluoHuang** [comment]
@nigurr can you take look this issue?

**Comment by TingluoHuang** [comment]
@nigurr

**Comment by plneto** [comment]
@nigurr I can't see the milliseconds on your test results.

**Comment by TingluoHuang** [comment]
@plneto @nigurr is this issue still going on?
