### ISSUE TITLE
Agent can't run on x86 machine

### ISSUE THREAD

**Issue by NikolayKash** [Microsoft/azure-pipelines-agent#789]
## **Agent version and platform**
v2.111.1
<br>
Windows 8.1 x32
<br>
## **VSTS type and version**
VisualStudio.com

<br>
## **What's not working?** 
There is no version for x86
<br>

**Comment by NikolayKash** [comment]
we need to deploy to windows 8.1 x86 machine and it is impossible with the new machine group approach as it requires to install an agent to a target machine

**Comment by chrisrpatterson** [comment]
The deployment group feature is really targeted for server based applications and not for client app deployment.  Can you help us understand why you need to target windows 8.1 x86.

**Comment by NikolayKash** [comment]
Hi @chrisrpatterson .

we have a  solution which we deploy to two levels:  Back-end servers and Clients.  

Our clients are windows 8.1 x32, we can't use x64 as our client app linked to some old components which runs only on x32. 

We are using now machine groups under Test hub but they are going to be removed. 
Our deploy  process is based on  tags which allows us to add new machines to be deploy just add it to machine group.
So our deployment process is machine name agnostic 
When machine groups under Test hub will be removed, only new machine group allows to specify tags.

**Comment by StarWars999123** [comment]
Hi @chrisrpatterson, 

I know, its not connected to the machine group request that @NikolayKash mentioned here, but we would also need a deployment to 32bit-Windows 7 for test purposes. The client-system has limited ressources and so it is a 32bit OS.
Why was it not possible to compile a 32bit agent? Can you give us some more insights into the problems you experienced thereby?

**Comment by CInk-Ibrahim** [comment]
We also need this feature as we have many x86 machines we need to deploy.  Is it possible to use it by compiling ourselves ? We would like to use it even if it is not supported.

**Comment by ChadEQ** [comment]
We would also like this feature supported.  We have old components we build with that aren't supported on 64 bit.  I haven't thoroughly tested, but have successfully built on a 32 bit box using the agent after adding an x86 target (to all of the projects).  All test pass as well.

**Comment by TingluoHuang** [comment]
you can always try to compile yourself.

**Comment by ChadEQ** [comment]
Yes, but we would prefer it to be supported.

**Comment by schenkjan** [comment]
Same here, we also have the need to run the build agent on a x86 machine.
Was anyone able to compile it for x86 and can give directions?

**Comment by ChadEQ** [comment]
Built a working x86 version using the dev.cmd but first changed the win7-x64 target to win10-x68 in dev.sh and the csproj files.

**Comment by schenkjan** [comment]
Thank you @ChadEQ, your hint helped me to create a x86 build agent.

Unfortunately it still didn't run on my Windows Server 2008 box since .Net Core only supports Windows Server 2008 from **R2** onwards :cry:.

**Comment by LokiMidgard** [comment]
@chrisrpatterson We original testet our client software using `Functional Tests`. Those are now depricated and so we tried to switching to the proposed replacement `Visual Studio Test`. This now requires installing the `vsts-agent` on the test machine. Unfortunalty we test on diffrent Windows versions wit different architectures. After all our client needst to run on all Windows Systems since Windows 7.

Maybe I have overlooked something, but if `vsts-agent` is not offical supported on x86 machiens how should we run tests on x86 machines? Is there some setting to also run those tests remote like with functional tests?

**Comment by LokiMidgard** [comment]
I were also able to build it my selfe targeting x86. But in addition I also needed to change `externals.sh`.

´´´bash
# Download the external tools only for Windows.
if [[ "$PLATFORM" == "windows" ]]; then
    acquireExternalTool "$CONTAINER_URL/azcopy/1/azcopy.zip" azcopy
    acquireExternalTool "$CONTAINER_URL/pdbstr/1/pdbstr.zip" pdbstr
    acquireExternalTool "$CONTAINER_URL/mingit/2.17.1.2/MinGit-2.17.1.2-64-bit.zip" git
    acquireExternalTool "$CONTAINER_URL/symstore/1/symstore.zip" symstore
    acquireExternalTool "$CONTAINER_URL/vstshost/m122_887c6659/vstshost.zip" vstshost
    acquireExternalTool "$CONTAINER_URL/vstsom/m122_887c6659/vstsom.zip" vstsom
    acquireExternalTool "$CONTAINER_URL/vswhere/1_0_62/vswhere.zip" vswhere
    acquireExternalTool "$NODE_URL/v${NODE_VERSION}/win-$RUNTIME/node.exe" node/bin
    acquireExternalTool "$NODE_URL/v${NODE_VERSION}/win-$RUNTIME/node.lib" node/bin
    acquireExternalTool "https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe" nuget
fi
´´´

`$RUNTIME` will be replaced with x86 or x64. I think in theory MinGit must also be replaced, but my build did not use git and there were no 32-bit version to download at the `$CONTAINER_URL`. So it seems to work for me regardless.

**Comment by StefanKert** [comment]
We have the same requirement as some of the preposters. We have to run tests on a 32 bit Windows 7 and since the Functional Test tasks are deprecated we thought about installing the agent on each of these machines. Since it is not supported is there any other (recommended) way to run tests on these kind of machines?

**Comment by TingluoHuang** [comment]
#1844 

We add x86 support while consume dotnet core 2.1.

here is the RC build.
https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.141.0

we are in the process of validation will release to service soon, i am closing this issue.
