### ISSUE TITLE
Custom PS task HttpClient Async threading problem

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/azure-pipelines-agent#881]
## **Agent version and platform**
2.114.0
<br>
Hosted and on W2016
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://mummy.visualstudio.com
<br>
## **What's not working?** 
This is a difficult question. Can't truly understand what is going wrong but my custom build task that ran without a glitch for over a year is not working anymore. It is based on the PowerShell3 execution handler and intermittently (randomly) fails complaining that The stream does not support concurrent IO read or write operations once I do make a PostAsync call on my instance of HttpClient. However, if I do trigger the cmdlet that encapsulates this call as a background job via via a Start-Job cmdlet, the issue can't be reproduced anymore. Also, from an interactive run in ISE it can't be reproduced.
I described here the issue in more details http://stackoverflow.com/questions/43014894/httpclient-and-stream-issues.
As this started happening in the last couple of weeks, I suspect it has something to do with the agent itself. Is there anyone who could help me understand what is happening and who is trying to access this stream and cause this issue?

Thanks

**Comment by TingluoHuang** [comment]
@mmajcica do you use your private agent or use the hosted agent? we print out agent version as part of build log, can you check the log see when the first failure happen what is the version of the agent?

**Comment by mmajcica** [comment]
@TingluoHuang this is reproducible both on the hosted agent and on my private agent running 2.114.0.

**Comment by ericsciple** [comment]
Does it repro from an interactive agent? or only when the agent is running as a service?

**Comment by ericsciple** [comment]
more details on this issue: https://github.com/Microsoft/vsts-tasks/issues/3858

**Comment by mmajcica** [comment]
@ericsciple this was a good one. On the interactive agent it is not reproducible. I did till now 5 runs on the interactive agent and not a single issue.
Where does this bring us as with the conclusion? How to diagnose precisely why this is happening?

Tnx

**Comment by mmajcica** [comment]
@ericsciple 
Sorry I was claiming the victory too soon. On the sixth run on the interactive agent it failed with the famous error:
The stream does not support concurrent IO read or write operations.

Is there a way to understand who is trying to access this stream?

**Comment by mmajcica** [comment]
The only way to have that call always to succeed is to wrap it inside a Start-Job { } and then wait for the result. This is wired as since VS2015RTM it never failed before.
I'm having serious difficulties in understanding what is happening and it is quite frustrating.
I will test it on TFS2015 and TFS2017 to try to understand with which version of the agent the issues starts to manifests itself, maybe that could help understanding why of it.
As usual, any suggestion is more then welcome.

**Comment by bryanmacfarlane** [comment]
Is this still an issue?

**Comment by mmajcica** [comment]
@bryanmacfarlane I have no idea as I abandoned PowerShell for that extension and haven't had chance to test it again.

**Comment by bryanmacfarlane** [comment]
Thanks.  I will close for now.
